apache/netbeans

javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/completion/beans/BeanModelBuilder.java, javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/completion/beans/FxDefinitionKind.java
Using NamedArg annotation on constructors parameters, find immutable objects that are OK in fxml editor.
@sdedic  could you take a look (you wrote the original code). I'm not that familiar with Mirror stuff or with fxml...
=> [NETBEANS-4745] Include immutable objects for fxml editor identification

enterprise/j2ee.sun.dd/licenseinfo.xml, enterprise/j2ee.sun.dd/src/org/netbeans/modules/j2ee/sun/dd/impl/resources/sun-resources_1_2.dtd, enterprise/j2ee.sun.dd/src/org/netbeans/modules/j2ee/sun/dd/impl/resources/sun-resources_1_4.dtd
The `j2ee.sun.dd` module referenced two DTDs that were not part of the repository; they were part of NB 8.2 however. Fails layers consistency tests during `commit-validation`
=> Commit validation fixes: Recovered missing sun-resource DTDs.

extide/gradle/src/org/netbeans/modules/gradle/GradleProjectCache.java, extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java, extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDistributionProviderImpl.java
Well, this one handles local wrapper distributionUrl (used in netbeans-gradle-tooling) also adds the change detection if the wrapper distribution changes which forces reload of the project.
The ```GradleDistributionManager.getWrapperDistributionURI()``` is a new public API. I have not increased the version number as the whole ```GradleDistributionManager``` is new in the upcoming release.
=> [NETBEANS-3600] Added Gradle wrapper distribution change detection.

platform/autoupdate.ui/arch.xml
In the [Apache Netbeans documentation overview](https://bits.netbeans.org/dev/javadoc/), the Auto Update UI module shows module name instead a short description.
This PR adds a short description in the arch-what answer and moves api export entries to the arch-overall answer.
=> Change platform/autoupdate.ui/arch.xml arch-what question

java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Update link to javadoc 15 now that is in general availability
Before:
https://download.java.net/java/early_access/jdk15/docs/api/
After:
https://docs.oracle.com/en/java/javase/15/docs/api/
=> [NETBEANS-4824] - General Availability for javadoc 15

java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImpl.java
It seems supporting MODULE_PROCESSOR_PATH in Gradle breaks annotation processor detection.
I've checked, the Maven plugin does not support this classpath, as well as the support is new in 12.1 for Gradle
See: https://github.com/apache/netbeans/blob/a04b626ec6293b4f0e3006a726ffcc121a2af313/java/java.source.base/src/org/netbeans/modules/java/source/indexing/APTUtils.java#L392
here decided if the MODULE_PROCESSOR_PATH is provided the isModule is true and NB tries to read the information through the Module however that does not provide the Lombok service providers. It maybe a bug in our Module implementation or a bug in Lombok
This PR just simply removes the support of MODULE_PROCESSOR_PATH from the classpath implementation for Gradle.
=> [NETBEANS-4762] Fixing Lombok in Gradle Projects

platform/o.n.bootstrap/src/org/netbeans/ModuleManager.java, platform/o.n.bootstrap/src/org/netbeans/Util.java, platform/o.n.bootstrap/test/unit/data/jars/client-module-depend-broken.mf, platform/o.n.bootstrap/test/unit/data/jars/client-module-depend-frag.mf, platform/o.n.bootstrap/test/unit/data/jars/client-module-depend-host.mf, platform/o.n.bootstrap/test/unit/data/jars/client-module-needs-broken.mf, platform/o.n.bootstrap/test/unit/data/jars/client-module.mf, platform/o.n.bootstrap/test/unit/data/jars/client-module/org/foo/Something.java, platform/o.n.bootstrap/test/unit/data/jars/fragment-module-auto.mf, platform/o.n.bootstrap/test/unit/data/jars/fragment-module-missing-token.mf, platform/o.n.bootstrap/test/unit/data/jars/fragment-module-reg.mf, platform/o.n.bootstrap/test/unit/data/jars/fragment-module.mf, platform/o.n.bootstrap/test/unit/data/jars/host-module.mf, platform/o.n.bootstrap/test/unit/src/org/netbeans/ModuleManagerTest.java, platform/o.n.core/test/qa-functional/src/org/netbeans/core/validation/ValidateModulesTest.java
The `netbeans.libs.javafx.*` library family print warnings on startup. There are several such libraries, each providing `org.openide.modules.jre.JavaFX`, but with `OpenIDE-Module-Needs: ` that demands a specific OS. Since they are `autoload`, they do not activate on their own on startup (c.f. eager and regular modules), but only when demanded.
Some other module depends on the provided token, enabling the (autoload) fragment. The fragment enables its host (also autoload), and the host attempts to load all the remaining fragments. Since the other autoloads have unsatisfied dependencies, a warning is printed to the log - quite bloated:
```
WARNING [org.netbeans.core.modules]: Module StandardModule:org.netbeans.libs.javafx.macosx jarFile: …
```
=> Do not report unsatisfied autoload fragments triggered by host module.

extide/gradle/src/org/netbeans/modules/gradle/api/execute/RunUtils.java, platform/openide.io/src/org/openide/io/BridgingIOProvider.java, platform/openide.io/test/unit/src/org/openide/io/BridgingIOProviderTest.java
I've got a `NullPointerException` while working on [java.lsp.server debugging](https://github.com/JaroslavTulach/netbeans/tree/java-lsp-server-debugging-attempt2):
```
at org.openide.io.BridgingIOProvider$BridgingIOColorPrint.print(BridgingIOProvider.java:299)
at org.openide.windows.IOColorPrint.print(IOColorPrint.java:68)
at org.netbeans.modules.gradle.api.execute.RunUtils.executeGradleImpl(RunUtils.java:206)
at org.netbeans.modules.gradle.api.execute.RunUtils.executeGradle(RunUtils.java:123)
at org.netbeans.modules.gradle.ActionProviderImpl.invokeProjectAction(ActionProviderImpl.java:266)
at org.netbeans.modules.gradle.ActionProviderImpl.invokeAction(ActionProviderImpl.java:137)
at org.netbeans.modules.java.lsp.server.debugging.launch.NbLaunchDelegate.lambd …
```
=> Avoid NPE in BridgingIOProvider when using null color

platform/o.n.bootstrap/src/org/netbeans/Util.java
Fresh build of current master and then try to activate any of the java related plugins will end in a `java.lang.NullPointerException`.
Plugins that fail to activate:
- Developing NetBeans
- Groovy
- JavaFX2
- Java SE
- Java Web and EE
This was integrated by [PR-2390](https://github.com/apache/netbeans/pull/2390). 
Do not know if there is a special way of handling this operation that @sdedic would need.
=> [NETBEANS-4840] - Fix NullPointerException when activating plugins

extide/gradle/src/org/netbeans/modules/gradle/api/execute/RunUtils.java, ide/code.analysis/manifest.mf, ide/code.analysis/src/org/netbeans/modules/analysis/api/CodeAnalysis.java, ide/javascript2.debug/nbproject/project.xml, ide/parsing.indexing/manifest.mf, ide/parsing.indexing/nbproject/project.properties, ide/parsing.nb/manifest.mf, ide/parsing.nb/nbproject/project.properties, ide/projectapi.nb/manifest.mf, ide/projectapi.nb/nbproject/project.xml, ide/projectapi/manifest.mf, ide/projectui/apichanges.xml, ide/projectui/arch.xml, ide/projectui/nbproject/project.properties, ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectList.java, ide/spi.debugger.ui/src/org/netbeans/modules/debugger/ui/DebuggerManagerListener.java, ide/web.browser.api/manifest.mf, java/maven/src/org/netbeans/modules/maven/spi/actions/AbstractMavenActionsProvider.java, nbbuild/antsrc/org/netbeans/nbbuild/AutoUpdateCatalogParser.java, platform/o.n.bootstrap/src/org/netbeans/CLIHandler.java, platform/openide.windows/src/org/openide/windows/DummyWindowManager.java, platform/settings/nbproject/project.properties, platform/settings/src/org/netbeans/modules/settings/RecognizeInstanceObjects.java
While working on [java.lsp.server debugging](https://github.com/JaroslavTulach/netbeans/tree/java-lsp-server-debugging-attempt2) various issues with module dependencies, their ability to run in headless mode, to run without `core.windows` module, etc. have been identified. This PR is my attempt to bring them into NetBeans master branch.
The most important (from my architect perspective) is the new "branding API" to prevent open projects to be reopened on the application start. With the `LOAD_PROJECTS_ON_START=false` the system always starts with no projects opened.
=> Cleanup of not just dependencies

.asf.yaml
According to current configuraiotn https://gitbox.apache.org/schemes.cgi?netbeans we only put PR in the worklog.
I guess that previously we had a label showing pr available. So using asf.yaml file from infra to get it again + configuration
label: Add a 'pull-request-available' label to referenced tickets.
link: Add a link to the GitHub PR/issue when it's opened to the referenced Jira ticket.
=> Add asf.yaml file to ease configuration

extide/gradle/netbeans-gradle-tooling/src/main/groovy/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.groovy, extide/gradle/src/org/netbeans/modules/gradle/GradleProjectCache.java
The annotationProcessorPath has been introduced in Gradle 4.6 as a replacement of compileClasspath for annotation processors. The usage of the compile classpath quickly become deprecated in Gradle 4.7. Gradle 5.0 and above does not accept annotation processors on compile classpath. 
NetBeans 12.0 supports the annotationProcessorPath, though it breaks the compatibility with pre-Gradle 5.0 projects. This PR adds that compatibility back.
=> [NETBEANS-4848] Use compile classpath as annotation path before Gradle 5.0

platform/spi.quicksearch/apichanges.xml, platform/spi.quicksearch/manifest.mf, platform/spi.quicksearch/nbproject/project.properties, platform/spi.quicksearch/nbproject/project.xml, platform/spi.quicksearch/src/org/netbeans/modules/quicksearch/CategoryResult.java, platform/spi.quicksearch/src/org/netbeans/spi/quicksearch/SearchProvider.java, platform/spi.quicksearch/src/org/netbeans/spi/quicksearch/SearchResponse.java, platform/spi.quicksearch/test/unit/src/org/netbeans/modules/quicksearch/ObsoleteSupportTest.java, platform/spi.quicksearch/test/unit/src/org/netbeans/modules/quicksearch/ProviderModelTest.java, platform/spi.quicksearch/test/unit/src/org/netbeans/modules/quicksearch/SlowProviderTest.java, platform/spi.quicksearch/test/unit/src/org/netbeans/modules/quicksearch/UnitTestUtils.java
I've been working with a Quicksearch provider and I noticed that while the Provider can check whether the search query was cancelled when calling `addResult` to the response, there's no way to check if the search was cancelled if the Provider is unable to find any item. In my case, the SearcProvider continues to search even if a new query has been created (provided the Provider still did not found anything).
This simple addition would allow to cancel even such empty-result searches.
=> Quicksearch API allows to check for cancel.

java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/editor/JavaToCHyperlinkProvider.java
Seen e.g. when doing Ctrl-click in a code from a library, which is not a project.
=> Prevent NPE from JavaToCHyperlinkProvider when no project available.

java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImpl.java
Well it seems even a non modular project is required to fill out the moduleBoot as
https://github.com/apache/netbeans/blob/5743f22f60aac775a0a2ebb3c8a8f6d6be39ac45/java/java.source.base/src/org/netbeans/modules/java/source/parsing/JavacParser.java#L1134
checks that for detecting Java 9 and up
=> [NETBEANS-4844] Non-empy modulebootpath shall be provided for non-modular code as well.

enterprise/web.freeform/nbproject/project.properties, ide/db/nbproject/project.properties, java/java.project.ui/nbproject/project.properties, java/java.project.ui/test/qa-functional/src/projects/LibrariesTest.java, java/java.project/nbproject/project.properties, nbbuild/build.xml, nbbuild/installer/jnlp/build.xml, nbbuild/templates/projectized.xml, nbbuild/test/unit/src/org/netbeans/nbbuild/FixTestDependencies.properties, nbbuild/test/unit/src/org/netbeans/nbbuild/FixTestDependenciesPass.properties, platform/core.osgi/nbproject/project.properties, websvccommon/websvc.saas.codegen/nbproject/project.properties
[NETBEANS-4854](https://issues.apache.org/jira/browse/NETBEANS-4854)
- Started NetBeans and ensure the log didn't have any errors or new warnings
- Activate all plugins
- Test a maven and ant projects
- Checked every path changed in this PR was correct
=> [NETBEANS-4854] - Fix wrong classpaths

enterprise/j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/resources/build-impl.xsl, enterprise/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/resources/build-impl.xsl, enterprise/web.project/src/org/netbeans/modules/web/project/resources/build-impl.xsl, java/java.j2semodule/src/org/netbeans/modules/java/j2semodule/resources/build-impl.xsl, java/java.j2seproject/src/org/netbeans/modules/java/j2seproject/resources/build-impl.xsl
This commit adds the missing `debug-single-method` ant target which is
attached to "Debug Focused Test Method" menu item in Test files.
ant -f "/home/siddhesh/Masters/CS5010 PDP/lab3-starter-dungeon" -Dnb.internal.action.name=debug.single.method - 
Djavac.includes=dungeon/MedievalLevelBuilderTest.java -Dtest.method=testAddGoblins - 
Dtest.class=dungeon.MedievalLevelBuilderTest debug-single-method
Target "debug-single-method" does not exist in the project "Lab_3". 
BUILD FAILED (total time: 0 seconds)
I tested by modifying my build-impl.xml file locally.
The `debug-single-method` target is only found in 5 java files and no ant xml files. Ant files have `debug-test-method` target but it appears in only one java file. I am not sure which is the correct one so I kept both in the …
=> [NETBEANS-591] Cannot debug failed test method from Test results window

nbbuild/antsrc/org/netbeans/nbbuild/Arch-default-arch-where.xsl
Change link generated in the Javadoc from old Netbeans Mercurial repository to Apache Gt repository.
=> Change repo link in documentation

ide/db.drivers/external/binaries-list, ide/db.drivers/external/postgresql-42.2.16-license.txt, ide/db.drivers/nbproject/project.properties, ide/db.drivers/src/org/netbeans/modules/db/drivers/Bundle.properties, ide/db.drivers/src/org/netbeans/modules/db/drivers/PostgreSQLDriver.xml, ide/db.drivers/src/org/netbeans/modules/db/drivers/postgresql.xml
Notes:
- Fix security vulnerability CVE-2020-13692 
- Minor bug fixes
[Releases Notes](https://jdbc.postgresql.org/documentation/changelog.html)
- Started NetBeans and ensure the log didn't have any errors or new warnings
- Checked that the file had been downloaded and referenced inside the Ant Library Manager
`jar:nbinst://org.netbeans.modules.db.drivers/modules/ext/postgresql-42.2.16.jar!/`
=> [NETBEANS-4664] - Upgrade JDBC PostgreSQL from 42.2.10 to 42.2.16

ide/core.ide/arch.xml, ide/core.ide/nbproject/project.properties
Change the ide/core.ide arch-what response to show a description instead the current value in the [Netbeans APIs overview.](https://bits.netbeans.org/12.1/javadoc/)
=> Change ide/core.ide arch-what response

.asf.yaml
The rules for participating in the [Hacktoberfest](https://hacktoberfest.digitalocean.com/) have changed this year: https://hacktoberfest.digitalocean.com/hacktoberfest-update
> We’re making Hacktoberfest opt-in only for projects – which maintainers can do simply by adding the ‘hacktoberfest’ topic to a repository.
This PR adds the hacktoberfest topic to allow this project to be included in the participating projects.
=> Hacktoberfest opt-in

enterprise/javaee.wildfly/licenseinfo.xml, enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/javaee_7.xsd, enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/jboss-common_6_0_1.xsd, enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/jboss-common_8_1.xsd, enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/jboss-web_14_1.xsd, enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/jboss-web_7_3_1.xsd, enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/jsp_2_2.xsd, enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/web-common_4_0.xsd, enterprise/web.core/build.xml, enterprise/web.core/src/org/netbeans/modules/web/taglib/resources/j2ee_1_4.xsd, enterprise/web.core/src/org/netbeans/modules/web/taglib/resources/javaee_5.xsd, extide/gradle/build.xml
This PR reestablishes the possibility to build netbeans offline. Offline in this case means, that thirdparty dependencies can be downloaded once and after that is done, the build can be done without a network connection.
This is the sequence:
0. Change into the netbeans source directory
1. Download release properties: `wget -O ../netbeansrelease.json "https://gitbox.apache.org/repos/asf?p=netbeans-jenkins-lib.git;a=blob_plain;f=meta/netbeansrelease.json"`
2. Download external binaries: `ant download-all-extbins`
3. Run the build: `ant -Dmetabuild.jsonurl=file:../netbeansrelease.json`
Steps 1+2 need an internet connection, step 3 can be run offline.
=> (Re)enable building netbeans offline

platform/api.progress.nb/arch.xml
Add a response for the arch-what answer in the platform/api.progress.nb  module to show a description in the [Netbeans APIs overview.](https://bits.netbeans.org/12.1/javadoc/)
=> Add response for platform/api.progress.nb arch-what answer 

.github/workflows/main.yml
Add GitHub action job to check errors on Javadoc generation.
=> Check Javadoc build using GitHub action

java/java.source.base/src/org/netbeans/modules/java/source/ElementUtils.java, javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/FXMLCompletion2.java
@sdedic could you take a look at this fix.
The assertion was due to CompilerInfo not having a list of modules. Fixed in `FXMLCompletion2.Q.Taks.run` with the getPackageElement:
```
ci = CompilationInfo.get(result);
// following populates module info, partial fix for [NETBEANS-4832]
ci.getElements().getPackageElement("java.lang");
```
This fixed code completion inside an UI element, for example<Label.../>"
However there was an NPE inside a list, for example in`<children>...</children>`. This was fixed by what looks like a bug/oversight in `ElementUtils.getTypeElementByBinaryName`.
In FxIncludeCompleter.createCompleter
```
TypeMirror tm = prop.getType().resolve(ctx.getCompilationInfo());
```
returned null which causes NPE in jdk.  fixed by the identity check in
``` …
```
=> [NETBEANS-4832] Avoid assertion & NPE in fxml code completion

README.md, nbbuild/build.xml
Add `javadoc-nb` ant task at root project level like the `javadoc-nb` ant task available at module level to display the generated javadoc.
=> Ant task to display generated Javadoc

ide/spi.debugger.ui/src/org/netbeans/modules/debugger/ui/DebuggerManagerListener.java
This is a headless check, corresponding to the existing one in `engineAdded` method.
=> Do not tear down debugger UI in a headless mode.

java/maven/apichanges.xml, java/maven/arch.xml, java/maven/manifest.mf, java/maven/src/org/netbeans/modules/maven/NbMavenProjectImpl.java, java/maven/src/org/netbeans/modules/maven/api/execute/RunUtils.java, java/maven/src/org/netbeans/modules/maven/debug/DebuggerChecker.java, java/maven/src/org/netbeans/modules/maven/debug/MavenJPDAStart.java, java/maven/src/org/netbeans/modules/maven/options/MavenSettings.java, java/maven/test/unit/src/org/netbeans/modules/maven/NbMavenProjectImplTest.java, java/maven/test/unit/src/org/netbeans/modules/maven/api/execute/Bundle_test.properties, java/maven/test/unit/src/org/netbeans/modules/maven/api/execute/RunUtilsTest.java, java/maven/test/unit/src/org/netbeans/modules/maven/options/Bundle_test.properties, java/maven/test/unit/src/org/netbeans/modules/maven/options/MavenSettingsTest.java
I am helping to build an [application on top of the NetBeans](https://github.com/JaroslavTulach/netbeans/tree/java-lsp-server-debugging-attempt2/java/java.lsp.server/nbcode) Platform and Java support (both Maven and Gradle) which has a completely different UI.
The default behavior of "reusing output tabs" in Maven doesn't suite my use-case. I'd prefer each Maven execution to request new tab. Also the "compile on save" behavior is problematic - my application doesn't have the project configuration options to turn it on/off (yet), so it is safer to just disable it altogether: this is made possible (via branding) in bac26b5
The other problem is related to debugging (and I have witnessed it in NetBeans from time to time): When you launch a debugging, but the Maven script execution fails, the …
=> Maven branding configuration API and robustness improvement

java/api.debugger.jpda/apichanges.xml, java/api.debugger.jpda/manifest.mf, java/api.debugger.jpda/src/org/netbeans/api/debugger/jpda/ExceptionBreakpoint.java, java/debugger.jpda.ant/antsrc/org/netbeans/modules/debugger/jpda/ant/JPDAStart.java, java/debugger.jpda.ui/nbproject/project.xml, java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/breakpoints/ExceptionBreakpointPanel.java, java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/models/BreakpointsNodeModel.java, java/debugger.jpda/nbproject/project.xml, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/breakpoints/BreakpointsEngineListener.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/breakpoints/BreakpointsReader.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/breakpoints/ExceptionBreakpointImpl.java, java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/BreakpointsClassFilterTest.java, java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/ExceptionBreakpointTest.java
As I need to use these constants in some follow-up changes, I decided to create grammatically correct names so that the wrong ones do not spread more. The deprecated ones will stay there for compatibility reasons.
=> Grammatically incorrect constants in ExceptionBreakpoint deprecated and replaced with grammatically correct names.

.travis.yml, extide/gradle/nbproject/project.xml, extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectFactory.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/AbstractGradleProjectTestCase.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/NbGradleProjectFactoryTest.java, platform/openide.modules/test/unit/src/org/openide/modules/DummyInstalledFileLocator.java
Well this makes the Gradle tests run by Travis. I'm not sure if I'm right on the apisupport.
=> [NETBEANS-4889] Remove extide <-> apisupport cyrcular dependency on tests

platform/core.ui/src/org/netbeans/core/ui/options/filetypes/IgnoredFilesPreferences.java, platform/masterfs/src/org/netbeans/modules/masterfs/GlobalVisibilityQueryImpl.java
ignore files pattern in the misc tab.
It will prevent indexing those folders while using NetBeans for the
first time and opening a web project with a package.json and/or a
bower.json.
=> NETBEANS-4893 - Added node_modules and bower_components to the option

profiler/lib.profiler/test/unit/src/org/netbeans/lib/profiler/heap/HeapSegmentTest.java, profiler/lib.profiler/test/unit/src/org/netbeans/lib/profiler/heap/HeapUtils.java
Commit 8b59038 demonstrates the problems when reading a Hprof file with multiple segments. The current code yields:
```
java.lang.IllegalArgumentException: Invalid dump tag 0 at position 1415
at org.netbeans.lib.profiler.heap.HprofHeap.readDumpTag(HprofHeap.java:1138)
at org.netbeans.lib.profiler.heap.HprofHeap.fillHeapTagBounds(HprofHeap.java:1215)
at org.netbeans.lib.profiler.heap.HprofHeap.<init>(HprofHeap.java:140)
at org.netbeans.lib.profiler.heap.HeapFactory.createHeap(HeapFactory.java:80)
at org.netbeans.lib.profiler.heap.HeapFactory.createHeap(HeapFactory.java:49)
```
The code in `HprofHeap` seems to assume only one segment is active. Can it be made ready for multiple segments or at least read them one by one.
=> WIP: [NETBEANS-4618] Heap dump with multiple segments yields exceptions.

platform/openide.explorer/src/org/openide/explorer/view/OutlineView.java, platform/openide.explorer/test/unit/src/org/openide/explorer/view/OutlineViewSynchronizationTest.java
Prevent PropertyChangeEvents in ExplorerManager during tree synchronization if multiple OutlineViews share one single ExplorerManager.
See Jira Issue: https://issues.apache.org/jira/browse/NETBEANS-4857
=> [NETBEANS-4857] prevent property change events during tree sync

enterprise/maven.j2ee/nbproject/project.xml, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroActionsProvider.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroExecutionChecker.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroProjectHook.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ReloadAction.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/resources/action-mapping.xml
This is a bug fix. 
- Delegates action provider to `J2eeActionsProvider` for non-Payara Micro projects. By introducing "micro" packaging via payara-micro-maven-plugin, a separate ActonProvider will be introduced in another PR.
- Currently `-Dnetbeans.deploy.clientUrlPart` is not supported by the Payara Micro Maven plugin, will be fixed should soon in another PR.
=> [NETBEANS-4559] Web Project Properties Dialog fails to save Relative URL

java/gradle.java/nbproject/project.xml, java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImpl.java, java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/CompileClassPathImpl.java, java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/GradleSourcesImpl.java, java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/SourceClassPathImpl.java, java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceForBinary.java
This one shall fix: 
https://github.com/lkishalmi/gradle-modular-calculator tests.
Also along with #2439 this can make javafx.base module load without any warnings. Other javafx modules are not necessary configured well in Gradle, they might live on the custom --module-source-path defined for the JavaC.
=> [NETBEANS-4896] Classpath Fixes for Gradle Java projects

extide/gradle/apichanges.xml, extide/gradle/arch.xml, extide/gradle/manifest.mf, extide/gradle/src/org/netbeans/modules/gradle/execute/AbstractGradleExecutor.java, extide/gradle/src/org/netbeans/modules/gradle/spi/GradleSettings.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/spi/Bundle_test.properties, extide/gradle/test/unit/src/org/netbeans/modules/gradle/spi/GradleSettingsTest.java, java/java.lsp.server/nbcode/branding/modules/org-netbeans-modules-gradle.jar/org/netbeans/modules/gradle/spi/Bundle.properties, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceIOContext.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceContextTest.java, java/java.lsp.server/vscode/README.md, java/java.lsp.server/vscode/package.json, java/java.source.base/src/org/netbeans/modules/java/source/parsing/JavacParser.java
Invoking the "Java: Compile Workspace" on a Maven project prints empty lines. Removing `"\n"` lines altogether. The EOL character is implicitly present in the previous line.
Avoiding usage of `invokeLater` when in headless mode in Gradle: edc2ff9
Branding API (like the [one in Maven](https://github.com/apache/netbeans/pull/2427)) to disable output reuse: e29dfe1
=> Bugfixes for VSCode and Gradle

extide/gradle/apichanges.xml, extide/gradle/manifest.mf, extide/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java, extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java, extide/gradle/src/org/netbeans/modules/gradle/actions/ActionToTaskUtils.java, extide/gradle/src/org/netbeans/modules/gradle/actions/CustomActionRegistrationSupport.java, extide/gradle/src/org/netbeans/modules/gradle/actions/GradleBaseTokenProvider.java, extide/gradle/src/org/netbeans/modules/gradle/actions/ProjectActionMappingProviderImpl.java, extide/gradle/src/org/netbeans/modules/gradle/api/execute/RunUtils.java, extide/gradle/src/org/netbeans/modules/gradle/customizer/BuildActionsCustomizer.java, extide/gradle/src/org/netbeans/modules/gradle/spi/actions/ProjectActionMappingProvider.java, extide/gradle/src/org/netbeans/modules/gradle/spi/actions/ReplaceTokenProvider.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/api/execute/RunUtilsTest.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/spi/actions/ReplaceTokenProviderTest.java, java/gradle.java/nbproject/project.xml, java/gradle.java/src/org/netbeans/modules/gradle/java/GradleJavaTokenProvider.java, java/gradle.java/src/org/netbeans/modules/gradle/java/JavaActionProvider.java
Well it is a bit more than I thought at first. At the start I would have checked only the existence of runSingle task, though if I remember someone would have liked run task defined for certain executable class in his project. With this pr run.single action can be redefined to use a ```run${selectedClassName}``` task.
=> [NETBEANS-4908] Enable run/debug single when the suitable task is provided by the Gradle project.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchRequestHandler.java
This change assures that an error during launch is propagated to the client.
The ResponseError's message is displayed in an error dialog in VSCode.
=> Propagate a launch error to the client.

platform/openide.filesystems.nb/arch.xml
Fix javadoc generation error: `[arch] file:/home/runner/work/netbeans/netbeans/platform/openide.filesystems.nb/arch.xml:2: The processing instruction target matching "[xX][mM][lL]" is not allowed.` derived from https://github.com/apache/netbeans/pull/2402
=> Fix javadoc generation

enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/plugin/resources/pom.xml.ftl
https://mvnrepository.com/artifact/fish.payara.maven.plugins/payara-micro-maven-plugin is used by pom.xml's freemarker template in Payara Micro modules which is generated during conversion of simple maven web application to Payara Micro maven application. The version upgrade is in the template file.
=> Upgrade payara-micro-maven-plugin to v1.3.0

java/java.navigation/src/org/netbeans/modules/java/stackanalyzer/StackLineAnalyser.java, java/java.navigation/test/unit/src/org/netbeans/modules/java/stackanalyzer/StackLineAnalyserTest.java
Since JDK 9, stack traces may contain optional module names, like:
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:282)
But, the stack trace analyzer in NetBeans does not understand these lines. This patch tweaks the analyzer to understand lines with modules. It does not use the module name, though - so far does not seem to be really necessary.
=> Stack trace analyzer needs to understand modular stack traces.

java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/AbstractGradleClassPathImpl.java, java/java.hints/nbproject/project.properties, java/java.hints/src/org/netbeans/modules/java/hints/project/IncompleteClassPath.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.source.base/src/org/netbeans/modules/java/source/parsing/CompilationInfoImpl.java
When a Gradle project is initially created/opened, it usually misses its JAR libraries. It makes little sense to parse its sources. For that one can use `getFlags() => Flag.INCOMPLETE` to prevent the Java parsing infrastructure from attempting to parse the source.
Moreover the infrastructure adds a hint to the first line of the source file to show `ProjectProblems` dialog or, in case of VSCode, to build the workspace.
After the (priming) build, the project state should be re-checked and the classpath should remove its `INCOMPLETE` flag.
=> Using Incomplete classpath to indicate unloadable Gradle project

java/java.source.base/src/org/netbeans/modules/java/source/parsing/OutputFileManager.java, java/java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/WriteArbitraryClassFileAPTest.java
-that have a name different from any source file in the source roots
-even while running in the editor
But neither of these seems to be working - fixing.
=> Annotation processors may generate class files: 

platform/openide.loaders/src/org/openide/text/DataEditorSupport.java
Confirm the `UserQuestionException` in headless mode so that external changes are reloaded.
Re-creation of https://github.com/apache/netbeans/pull/2472 targeting `delivery` branch.
=> Reload external changes automatically in headless mode.

extide/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java, extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java, extide/gradle/src/org/netbeans/modules/gradle/api/execute/RunUtils.java, extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java, java/maven/src/org/netbeans/modules/maven/ActionProviderImpl.java, java/maven/src/org/netbeans/modules/maven/NbMavenProjectImpl.java, java/maven/src/org/netbeans/modules/maven/api/NbMavenProject.java, java/maven/src/org/netbeans/modules/maven/execute/MavenCommandLineExecutor.java
Continuation of #2464 - once a build on unloadable Gradle project successfully finishes, then let's schedule a reload to bring the module to loadable state:
* opening unloadable project shall show a fix https://user-images.githubusercontent.com/26887752/96404352-fff94100-11da-11eb-931b-d6cdcbf1ed95.png 
* after invoking it, the build is started
* when finished, the project is refreshed
Ideally the fix disappears and one can invoke "Start Debugging".
=> Refresh unloadable Gradle/Maven project after successful build

ide/html.editor.lib/nbproject/project.xml, java/javadoc/nbproject/project.xml, java/javadoc/src/org/netbeans/modules/javadoc/hints/Analyzer.java
Prevent a crash on JDK 16, which does not have the com.sun.tools.doclint.HtmlTag (internal) class.
=> [NETBEANS-4919] Avoiding dependency on javac internal classes from javadoc/.../Analyzer, using NetBeans' HTML information instead.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
Since the whole document text is removed and re-added, all breakpoints were renumbered to line 1. This fix fixes case where there are no changes between saved file and the didOpen state; there's still slight chance that didOpen will report a different content to the LSP server. Fixing that will probably require some trickery in openide.text ...
=> [lsp] partial fix of invalidation of breakpoints during file open

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeClientCapabilities.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeClientWrapper.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeLanguageClient.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ShowStatusMessageParams.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceUIContext.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractLspStatusDisplayer.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/UIContext.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/protocol.ts
StatusDisplayer messages displayed in VSCode's 'Extension Status' statusbar item - or anywhere the LSP client likes. This is different to `showMessage` defined by the LSP protocol, which typically displays alerts or notifications that require an action; status bar messaes are less obtrusive. Also different from `logMessage` that only appears in an output together with e.g. debug messages.
Relatively unrelated change: moved `Lookups.lookupWith` from the build action to an interceptor for all messages received by the LSP endpoint.
=> StatusDisplayer messages remoted to LSP client.

ide/editor.lib2/src/org/netbeans/api/editor/EditorRegistry.java, ide/editor.lib2/src/org/netbeans/modules/editor/lib2/EditorApiPackageAccessor.java, ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/BreadcrumbsImpl.java, ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandler.java, ide/lsp.client/test/unit/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandlerTest.java
The LSP client was not properly sending the didClose event, and when a file was re-opened, it wasn't fully registered e.g. to provide hyperlinks. Attempting to correct.
=> [NETBEANS-4910] Correcting open and close events sent from the LSP client to the LSP server.

java/java.editor/src/org/netbeans/modules/editor/java/JavaCodeTemplateProcessor.java, java/java.editor/test/unit/src/org/netbeans/modules/editor/java/JavaCodeTemplateProcessorTest.java
This PR is my attempt to add support for static imports in code templates. I've added an additional hint `staticImport` for the Java Code Template Processor. When processed by the processor, a static import declaration and static member identifier will be added to the source code. From the user's perspective, this will work something like this:
=> Add support for static imports in code templates

ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/HyperlinkProviderImpl.java
The LSP HyperlinkProvider is registered for every document. It expects,
that documents always provide token sequences. This assumption is
invalid and the calls need to be guarded agains null token sequences.
Observed backtrace:
```
SEVERE [global]
at org.netbeans.modules.lsp.client.bindings.HyperlinkProviderImpl.getHyperlinkSpan(HyperlinkProviderImpl.java:76)
at org.netbeans.modules.lsp.client.bindings.HyperlinkProviderImpl.isHyperlinkPoint(HyperlinkProviderImpl.java:62)
at org.netbeans.lib.editor.hyperlink.HyperlinkOperation.findProvider(HyperlinkOperation.java:266)
at org.netbeans.lib.editor.hyperlink.HyperlinkOperation.performHyperlinking(HyperlinkOperation.java:224)
at org.netbeans.lib.editor.hyperlink.HyperlinkOperation.keyPressed(HyperlinkOperation.java …
```
=> Prevent NullPointerException from LSP HyperlinkProvider

java/java.lsp.server/vscode/README.md, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts
It all started with a bug report: Java Language Server ignores `JAVA_HOME` environment variable. Then it continued with a discussion and the conclusion was made to mimic behavior of the existing VSCode Java extension. E.g. to search locations:
- `netbeans.jdkhome` setting (workspace then user settings)
- `java.home` setting (workspace then user settings)
- `JDK_HOME` environment variable
- `JAVA_HOME` environment variable
- current system path
`netbeans.jdkhome` is checked to give the user chance to exactly specify JDK just for NbCode. Other locations are checked for compatibility reasons.
As soon as `netbeans.jdkhome` or  `java.home` settings are set the NbCode Java part is restarted.
=> Search for JDK in typical location

java/java.lsp.server/vscode/README.md, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts
Apache NetBeans Language Server extension isn't the only Java supporting
extension. To avoid duplicated code completion and other misleading clashes
the extension disables certain functionality known to cause problems. This
behavior can be disabled by setting `netbeans.conflict.check` setting to `false`.
=> Avoid conflicts with other Java extensions

cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/breakpoints/BreakpointAnnotationListener.java, enterprise/glassfish.eecommon/src/org/netbeans/modules/glassfish/eecommon/api/DomainEditor.java, enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/api/application/DDProvider.java, enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/api/ejb/DDProvider.java, enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/common/ComponentBeanMultiple.java, enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/common/DescriptionBeanMultiple.java, enterprise/payara.eecommon/src/org/netbeans/modules/payara/eecommon/api/DomainEditor.java, enterprise/weblogic.common/src/org/netbeans/modules/weblogic/common/RemoteLogInputReader.java, enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/support/SourceGroupSupport.java, ide/db/src/org/netbeans/modules/db/explorer/action/GrabTableHelper.java, ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/DefaultPathRecognizer.java, ide/spi.debugger.ui/src/org/netbeans/modules/debugger/ui/views/debugging/DebugTreeView.java, ide/xml.core/src/org/netbeans/modules/xml/dtd/grammar/DTDGrammar.java, ide/xml.tax/src/org/netbeans/modules/xml/tax/beans/editor/TreeNodeFilterCustomEditor.java, ide/xsl/src/org/netbeans/modules/xsl/grammar/XSLGrammarQuery.java, java/ant.debugger/src/org/netbeans/modules/ant/debugger/DebuggerAntLogger.java, java/ant.debugger/src/org/netbeans/modules/ant/debugger/breakpoints/BreakpointAnnotationListener.java, java/dbschema/src/org/netbeans/modules/dbschema/SchemaElement.java, java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/SchemaElementImpl.java, java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/TableElementImpl.java, java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/JPDAStart.java, java/websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/support/SourceGroupSupport.java, platform/api.templates/src/org/netbeans/api/templates/CreateFromTemplateImpl.java, platform/core.netigso/nbproject/project.properties, platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java
Hey, it's me again.. The Netbeans Rust Remover..
There are a bunch of warnings related to raw type usage of the Map interface..
[repeat] /home/bwalker/src/netbeans/enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/support/SourceGroupSupport.java:170: warning: [rawtypes] found raw type: Map
[repeat]         Map result;
[repeat]         ^
[repeat]   missing type arguments for generic class Map<K,V>
[repeat]   where K,V are type-variables:
[repeat]     K extends Object declared in interface Map
[repeat]     V extends Object declared in interface Map
This change cleans some of this up..
=> [NETBEANS-4925] - cleanup Map raw type warnings..

extide/gradle/arch.xml, extide/gradle/netbeans-gradle-tooling/src/main/groovy/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.groovy, extide/gradle/netbeans-gradle-tooling/src/test/data/simple-with-tests/build.gradle, extide/gradle/netbeans-gradle-tooling/src/test/data/simple-with-tests/settings.gradle, extide/gradle/netbeans-gradle-tooling/src/test/data/simple/settings.gradle, extide/gradle/netbeans-gradle-tooling/src/test/data/unresolvable/settings.gradle, extide/gradle/src/org/netbeans/modules/gradle/GradleModuleFileCache21.java, extide/gradle/src/org/netbeans/modules/gradle/GradleProjectCache.java, extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java, extide/gradle/src/org/netbeans/modules/gradle/cache/ProjectInfoDiskCache.java, extide/gradle/src/org/netbeans/modules/gradle/nodes/ConfigurationsNode.java
Well, this one brings back the module dependencies under the configuration node in Gradle Projects.
Half of this PR allows the Gradle side of the tooling library debugged.
The GradleModuleFileCache21 is a bit odd ball here using NIO Path instead of File or File Objects, that might be reworked later, I just had it on hand from another project of mine.
Probably this PR finishes my Gradle work for 12.2.
=> [NETBEANS-3789] Fix missing artitact nodes in Gradle Project Configurations.

extide/gradle/src/org/netbeans/modules/gradle/execute/TrustProjectPanel.java, ide/projectui/src/org/netbeans/modules/project/ui/problems/Bundle.properties, java/java.lsp.server/nbcode/integration/nbproject/project.xml, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/LspDialogDisplayer.java, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/LspServerUtils.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeLanguageClient.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceUIContext.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractDialogDisplayer.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/NotifyDescriptorAdapter.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/UIContext.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/ui/AbstractDialogDisplayerTest.java
I've implemented a `AbstractDialogDisplayer` that, if registered will remote `notify()` and `notifyLater` through `UIContext` into the remote LSP client. I've tested locally on Gradle projects; but it has still some limitations, like Project Problems tend to display a customizer ... so I've commented out the final registration of the service.
I'd like to pull in the infrastructure for collaboration.
=> Infrastructure to display simple confirmations/questions in LSP client.

ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/HyperlinkProviderImpl.java, ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandler.java
This is a tweak to:
https://github.com/apache/netbeans/pull/2483
The LSP client's hyperlink provider should ignore files that are not handled by the LSP client (for performance reasons, at least), this patch moves the flag at a more correct place. Sorry I didn't have time to look at 2483, and for trouble with this bug.
=> Avoid registering the LSP client's hyperlink provider unless the given file is handled by the LSP client.

extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java, extide/gradle/src/org/netbeans/modules/gradle/api/GradleProjects.java, extide/gradle/src/org/netbeans/modules/gradle/nodes/ConfigurationsNode.java
Just to utilize the GradleModuleFileCache21 a bit more, added some code which help find the sources and javadocs more reliably.
This fixes the issue with not finding those artifacts on JavaFx projects.
=> [NETBEANS-4535] Better way to detect sources and javadocs in Gradle Projects

php/php.phpdoc/src/org/netbeans/modules/php/phpdoc/PhpDocScript.java
https://issues.apache.org/jira/browse/NETBEANS-4901
- PHPDocumentor 3 doesn't have this option
```
Options:
-t, --target[=TARGET]                          Path where to store the generated output
--cache-folder[=CACHE-FOLDER]              Path where to store the cache files
-f, --filename[=FILENAME]                      File to parse, glob patterns are supported. Provide multiple options of this type to add
multiple files. (multiple values allowed)
-d, --directory[=DIRECTORY]                    directory to parse, glob patterns are supported. Provide multiple options of this type to add
multiple directories. (multiple values allowed)
--encoding[=ENCODING]                      encoding to be used to interpret source files with
--extensions[=EXTENSIONS]                  Provide multiple …
```
=> [NETBEANS-4901] Remove the `--progressbar` option

php/php.editor/src/org/netbeans/modules/php/editor/indent/FormatVisitor.java, php/php.editor/test/unit/data/testfiles/formatting/netbeans4970.php, php/php.editor/test/unit/data/testfiles/formatting/netbeans4970.php.formatted, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/indent/PHPFormatterTest.java
https://issues.apache.org/jira/browse/NETBEANS-4970
Before:
```php
<?php
function test(): callable {
return function ($test): void {
echo "test";
};
}
```
After
```php
<?php
function test(): callable {
return function ($test): void {
echo "test";
};
}
```
=> [NETBEANS-4970] Incorrect formatting for lambda functions

java/java.lsp.server/vscode/package.json
@gmcdonald wrote in [INFRA-21017](https://issues.apache.org/jira/browse/INFRA-21017) that the Apache Software Foundation is going to own [Marketplace](https://marketplace.visualstudio.com) publisher named `asf`. Updating the record in `package.json`.
=> [INFRA-21017] Apache marketplace publisher is asf.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
In a scenario when the user initially presses `CTRL-N` in VS Code, then saves a file with some contents, a sequence `didOpen`, `didChange` is fired that requires the server to create an empty content file in its internal buffer although the file is already saved on the disk with non-empty content.
Fixed in `TextDocumentServiceImpl` and added a relevant testcase.
=> Ensure document state is consistent after unnamed is saved.

groovy/gradle.groovy/build.xml, groovy/gradle.groovy/manifest.mf, groovy/gradle.groovy/nbproject/project.properties, groovy/gradle.groovy/nbproject/project.xml, groovy/gradle.groovy/src/org/netbeans/modules/gradle/groovy/Bundle.properties, groovy/gradle.groovy/src/org/netbeans/modules/gradle/groovy/RecommendedPrivilegedTemplatesImpl.java, groovy/groovy.support/nbproject/project.xml, nbbuild/cluster.properties
This one is just laying some groundwork for upcoming changes.
@JaroslavTulach I marked this one as eager load and this is not a dependee of the Groovy Kit. Is that Ok? The Maven Groovy support is a regular module and Groovy Kit depends on it.
@svenreimers would it be Ok to make Groovy Support module to public, or shall we live with the friend dependencies.
=> [NETBEANS-1972] Initial Groovy Support Module for Gradle

platform/openide.io/src/org/openide/io/BridgingIOProvider.java, platform/openide.io/test/unit/src/org/openide/io/BridgingIOProviderTest.java
But Lookups.fixed does not allow null.
Would be ideal for 12.2, but I realize it is quite late. Would help running OpenJDK tests in the VS Code.
=> ioContainer in IOProvider.getIO(...) is allowed to be null.

ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/CodeTemplateInsertHandler.java, ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/CodeTemplateParameterImpl.java, ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/textsync/TextRegionManagerEvent.java, ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/textsync/TextSync.java, ide/editor.codetemplates/test/unit/src/org/netbeans/lib/editor/codetemplates/CodeTemplateInsertHandlerTest.java, ide/editor.codetemplates/test/unit/src/org/netbeans/lib/editor/codetemplates/CodeTemplateParameterImplTest.java
https://issues.apache.org/jira/browse/NETBEANS-4646
Before:
After:
=> [NETBEANS-4646] Fix completionInvoke hint in code templates

java/java.lsp.server/build.xml, java/java.lsp.server/nbcode/nbproject/platform.properties, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/vscode/src/extension.ts, java/java.source.base/src/org/netbeans/api/java/source/JavaSource.java, platform/autoupdate.cli/src/org/netbeans/modules/autoupdate/cli/ModuleOptions.java
The best way to solve [NETBEANS-4981](https://issues.apache.org/jira/browse/NETBEANS-4981) and bring the Apache NetBeans Language Server VSCode experience to users of JDK8 is to mimic the same functionality the NetBeans IDE provides on JDK8 - e.g. to ask the user to download `nbjavac`.
This PR is my attempt to do so.
=> [NETBEANS-4981] Install nbjavac when needed

java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/LspDialogDisplayer.java
The implementation has been already integrated into `origin` (and then merged into `master`), this commit just enables `DialogDisplayer` remoting implementation for the next release cycle.
=> Enable limited DialogDisplayer emulation over LSP.

java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
The field name of `JCInstanceOf.clazz` was changed to `JCInstanceOf.pattern` in late 2019 in the JDK sources of javac.
CasualDiff.java  already contains a method to look up the correct field via reflection, but
one case of directly referencing the original field was not changed, and causes a
NoSuchFieldError in the move inner to outer level refactoring (and likely elsewhere).
=> [NETBEANS-4469] Fix NoSuchFieldError from refactorings on JCInstanceOf.clazz which was renamed

ide/editor.lib/apichanges.xml, ide/editor.lib/arch.xml, ide/editor.lib/src/org/netbeans/editor/BaseCaret.java
In ide/editor/lib/BaseCaret there's
```
newCaretBounds = c.getUI().modelToView(
c, offset, Position.Bias.Forward);
// [TODO] Temporary fix - impl should remember real bounds computed by paintCustomCaret()
if (newCaretBounds != null) {
newCaretBounds.width = Math.max(newCaretBounds.width, 2);
}
```
When offset is sitting on a TAB character,
editor.lib2's TabView's `modelToViewChecked(int offset, Shape alloc,...` does
```
mutableBounds.width = 1;
return mutableBounds;
```
So the min of 2 applies and the caret drawing code gets a graphics context with clip width of 2.
This causes a drawing problem for the caret which can be ovserved in NetBeans. The problem may be exacerbated for plugins that provide their own caret. This fix provides a workaround that can be used by plugins until (if) the …
=> [NETBEANS-4940] Workaround for caret-on-TAB drawing issue

java/java.lsp.server/nbcode/integration/nbproject/build-impl.xml, java/java.lsp.server/nbcode/nbproject/build-impl.xml, java/java.lsp.server/vscode/package.json
@jisedlac noticed error in spelling the name of the VSCode extension.
=> Spell NetBeans with capital N and capital B

java/java.lsp.server/vscode/src/extension.ts
When trying to run/debug a Java program before the Apache NetBeans DAP Server finishes its initialization a cryptic error message is shown in VSCode UI. Run/debug actions should wait for DAP server init.
=> Wait for DAP server init before run/debug.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java
Processing of the DAP command `stackTrace` throws the following exception on Windows:
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Sources/micronaut-sandbox/project_212_8_gradle/demo/src/main/java/com/example/Application.java
at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
at java.nio.file.Paths.get(Paths.java:84)
at org.netbeans.modules.java.lsp.server.debugging.NbProtocolServer.stackTrace(NbProtocolServer.java:291)
To fix this, Paths.get(...) is called with correct argument.
=> DAP command 'stackTrace' throws exceptions on Windows.

php/php.dbgp/manifest.mf, php/php.dbgp/nbproject/project.xml, php/php.editor/manifest.mf, php/php.editor/nbproject/project.properties, php/php.editor/nbproject/project.xml, php/php.kit/manifest.mf, php/php.kit/nbproject/project.xml, php/php.refactoring/manifest.mf, php/php.refactoring/nbproject/project.xml, php/php.smarty/manifest.mf, php/php.smarty/nbproject/project.xml, php/php.symfony/manifest.mf, php/php.symfony/nbproject/project.xml, php/php.zend/manifest.mf, php/php.zend/nbproject/project.xml, php/php.zend2/manifest.mf, php/php.zend2/nbproject/project.xml, php/spellchecker.bindings.php/manifest.mf, php/spellchecker.bindings.php/nbproject/project.xml
There are incompatible API changes. e.g.
- `ASTPHP5Parser.createDispatch*`
- `ASTPHP5Symbols.T_*`
See: #2504
=> Increase the major version for php.editor

java/java.lsp.server/vscode/src/extension.ts
When changing JDKs using GraalVM's extension UI, the vscode kills Apache Language Server (ALS), but then the ALS extensions notices that the channel to ALS broke and restarts it again ... killing the instance. The channel closes again etc etc.
This patch should prevent restarts if the process was killed *because of* a deliberate restart.
=> [NETBEANS-5007] Prevent endless restarts when changing JDKs.

.github/workflows/main.yml
Update `shivammathur/setup-php` GitHub action dependency to fix GitHub action deprecation error.
```
Error: Unable to process command '::add-path::/home/runner/.composer/vendor/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
=> Update GitHub action dependency to fix error

java/java.lsp.server/nbcode/nbproject/platform.properties
Using F12 on String & co. didn't open the String source. With `org.netbeans.modules.lexer.nbbridge` included in `nbcode` suite, it works again.
=> Turning on lexer.nbbridge enables Go to declaration in VSCode

platform/o.n.bootstrap/launcher/unix/nbexec
JDK is not found on macOS Big Sur due to changes the `/usr/libexec/java_home`
1.  It no longer works with `--failfast` and a `+` used in the `-v` argument
2. It will return whatever  is contained in the environment variable `JAVA_HOME` regardless of arguments passed in.
3. if `JAVA_HOME` is set and is empty, it will return an empty string.
4. Removing `--failfast` does not break functionality on earlier versions of macOS.
Below are tests run on clean install of macOS Big Sur running in a VM
```
% /usr/libexec/java_home -V                                                
Matching Java Virtual Machines (3):
15.0.1 (x86_64) "AdoptOpenJDK" - "AdoptOpenJDK 15" /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home
11.0.9 (x86_64) "AdoptOpenJDK" - "AdoptOpenJDK 11" …
```
=> Fix call to find jdkhome using /usr/libexec/java_home for macOS Big Sur.

platform/o.n.bootstrap/launcher/unix/nbexec
This is a cherry-pick of #2545 to the delivery branch which would go into release122 for rc3
=> [NETBEANS-5042] Fix call to find jdkhome using /usr/libexec/java_home for macOS Big Sur.

java/java.lsp.server/nbcode/nbproject/platform.properties
Well piggybacking on #2546 is a nasty thing to do.
=> [NETBEANS-5043] Turning on lexer.nbbridge enables Go to declaration in VSCode

java/java.lsp.server/vscode/BUILD.md, java/java.lsp.server/vscode/README.md, java/java.lsp.server/vscode/package.json
Improving `README.md` to look better in VS Code user interface:
Plus backporting fix for #2538
=> End user oriented README.md and dedicated BUILD.md

php/php.editor/src/org/netbeans/modules/php/editor/codegen/CGSGenerator.java, php/php.editor/src/org/netbeans/modules/php/editor/codegen/CGSInfo.java, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/codegen/SelectedPropertyMethodsCreatorTest.java
https://issues.apache.org/jira/browse/NETBEANS-5029
Changes default value for generating public modifier of constructor/getters/setters to enabled.
=> [NETBEANS-5029] PHP - generated methods are public by default

php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion.java, php/php.editor/test/unit/data/testfiles/completion/lib/nb4650/nb4650.php, php/php.editor/test/unit/data/testfiles/completion/lib/nb4650/nb4650.php.testNb4650_01.completion, php/php.editor/test/unit/data/testfiles/completion/lib/nb4650/nb4650.php.testNb4650_02.completion, php/php.editor/test/unit/data/testfiles/completion/lib/tests241902/issue241902.php.testUseCase1.completion, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionNb4650Test.java
https://issues.apache.org/jira/browse/NETBEANS-4650
Example code:
```php
namespace Test;
trait MyTrait{}
namespace TestTrait;
use Test\MyTrait; // here
use Test\{
MyTrait // here
};
class MyClass{}
```
=> [NETBEANS-4650] Fix code completion for traits of use and group use statements

php/php.editor/src/org/netbeans/modules/php/editor/model/nodes/ConstantDeclarationInfo.java, php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInArrayExpression/spreadOperatorInArrayExpression.php.testSpreadOperatorInArrayExpression_02.completion, php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInArrayExpression/spreadOperatorInArrayExpression.php.testSpreadOperatorInArrayExpression_02a.completion, php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInArrayExpression/spreadOperatorInArrayExpression.php.testSpreadOperatorInArrayExpression_03.completion, php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInArrayExpression/spreadOperatorInArrayExpression.php.testSpreadOperatorInArrayExpression_04.completion, php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInArrayExpression/spreadOperatorInArrayExpression.php.testSpreadOperatorInArrayExpression_GlobalConst_01.completion, php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInArrayExpression/spreadOperatorInArrayExpression.php.testSpreadOperatorInArrayExpression_GlobalConst_02.completion, php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInArrayExpression/spreadOperatorInArrayExpression.php.testSpreadOperatorInArrayExpression_GlobalConst_03.completion, php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInArrayExpression/spreadOperatorInArrayExpression.php.testSpreadOperatorInArrayExpression_GlobalConst_05.completion, php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInArrayExpression/spreadOperatorInArrayExpression.php.testSpreadOperatorInArrayExpression_GlobalConst_09.completion
https://issues.apache.org/jira/browse/NETBEANS-5028
Improves display of array constant in code completion.
Uses short array format, displays first item in array, indicates more elements in array.
Before:
After:
=> [NETBEANS-5028] PHP - improved display of constant in code completion

php/php.editor/src/org/netbeans/modules/php/editor/CodeUtils.java, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/CodeUtilsTest.java
https://issues.apache.org/jira/browse/NETBEANS-5027
Improves display of array used as default parameter value.
Uses short array format, displays first item in array, indicates more elements in array.
Before:
After:
=> [NETBEANS-5027] PHP - improved display of array parameter

.gitignore
When one does the following command:
$ANT_HOME/bin/ant test-platform
Numerous test related files get created that should be ignored..
[bwalker@localhost netbeans]$ git status
On branch master
Untracked files:
(use "git add <file>..." to include in what will be committed)
platform/o.n.bootstrap/test/unit/data/jars/agent/org/agent/HelloWorld.class
...
platform/o.n.bootstrap/test/unit/data/jars/uses-api/usesapi/UsesPublicClass.class
nothing added to commit but untracked files present (use "git add" to track)
This change to .gitignore adds these directories to be ignored..
=> [NETBEANS-5032] - update .gitignore to include a few test dirs..

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleEval.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/expr/InvocationExceptionTranslated.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java
Mainly in watches, where space is limited, it's hard to see the real evaluation error due to a long prefix text.
In case of Truffle languages if there is a `n` variables in watches, which is not present in the current scope, the used gets following error message:
`Failed to evaluate. Reason: Exception occurred in target VM: ReferenceError: n is not defined`
That's simply too long.
This change limits that to the most important part:
`ReferenceError: n is not defined`
=> Provide shorter evaluation error, without the unneccessary prefix.

.gitignore, .travis.yml, java/java.lsp.server/build.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/vscode/.vscode/launch.json, java/java.lsp.server/vscode/BUILD.md, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/test/runTest.ts, java/java.lsp.server/vscode/src/test/suite/extension.test.ts, java/java.lsp.server/vscode/src/test/suite/index.ts, java/java.lsp.server/vscode/src/test/ws/empty.ts
Executing some VS Code extension integration tests. The execution of the [first test failed](https://travis-ci.org/github/apache/netbeans/jobs/744801153) - e.g. the travis gate correctly verifies the behavior of our extension.
Next step is to initialize the extension and get its (programmatic) version: 9219db8 - that shall succeed.
The last test creates `pom.xml` and a `.java` source in a workspace and invokes its compilation. Then it checks the result. I guess that is enough for now and quite a bit of functionality is covered.
This was failing on the gate as the "compile" command was executed sooner than language client with its `java.build.workspace` action was really initialized. This should be [fixed now](https://github.com/apache/netbeans/pull/2549/commits/3dbed9d6b1f5855ce99cc227bff9 …
=> Initial VSNetBeans extension integration tests.

enterprise/glassfish.javaee/src/org/netbeans/modules/glassfish/javaee/Hk2OptionalFactory.java, enterprise/glassfish.javaee/src/org/netbeans/modules/glassfish/javaee/templates/WebLogicDDWizardIterator.java, enterprise/j2ee.ejbrefactoring/src/org/netbeans/modules/j2ee/ejbrefactoring/EjbRefactoringPlugin.java, enterprise/javaee.project/src/org/netbeans/modules/javaee/project/api/ant/ui/wizard/J2eeVersionWarningPanel.java, enterprise/javaee.project/src/org/netbeans/modules/javaee/project/api/ant/ui/wizard/ProjectServerPanel.java, enterprise/payara.eecommon/src/org/netbeans/modules/payara/eecommon/dd/wizard/PayaraDDWizardIterator.java, enterprise/websvc.manager/src/org/netbeans/modules/websvc/manager/model/WebServiceListModel.java, enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/support/SourceGroupSupport.java, harness/o.n.insane/src/org/netbeans/insane/scanner/ScannerUtils.java, ide/db/src/org/netbeans/api/db/explorer/support/DatabaseExplorerUIs.java, ide/spi.debugger.ui/src/org/netbeans/modules/debugger/ui/DebuggerManagerListener.java, ide/xml.core/src/org/netbeans/modules/xml/dtd/grammar/DTDGrammar.java, ide/xml.tax/src/org/netbeans/modules/xml/tax/beans/editor/TreeNodeFilterCustomEditor.java, ide/xsl/src/org/netbeans/modules/xsl/grammar/XSLGrammarQuery.java, java/ant.debugger/src/org/netbeans/modules/ant/debugger/AntDebugger.java, java/java.examples/src/org/netbeans/modules/java/examples/J2SESampleProjectIterator.java, java/java.hints.ui/src/org/netbeans/modules/java/hints/spiimpl/refactoring/InspectAndRefactorPanel.java, java/java.platform.ui/src/org/netbeans/modules/java/platform/ui/PlatformsCustomizer.java, java/java.source.queriesimpl/src/org/netbeans/modules/java/source/queriesimpl/TemplateWizardIterator.java, java/websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/support/SourceGroupSupport.java, java/xml.tools.java/src/org/netbeans/modules/xml/tools/java/generator/GenerationUtils.java, platform/core.startup.base/src/org/netbeans/core/startup/layers/LocalFileSystemEx.java, platform/openide.filesystems/src/org/openide/filesystems/MultiFileObject.java, platform/openide.util/src/org/openide/util/TopologicalSortException.java, profiler/profiler.nbmodule/src/org/netbeans/modules/profiler/nbmodule/NbModuleProjectProfilingSupportProvider.java, webcommon/web.webkit.tooling/src/org/netbeans/modules/web/webkit/tooling/networkmonitor/ModelItem.java
I am trying to cleanup a bunch of the Set raw type warnings.. They look like this..
[repeat] /home/bwalker/src/netbeans/cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/breakpoints/CPPLiteBreakpointActionProvider.java:50: warning: [rawtypes] found raw type: Set
[repeat]     private static final Set actions = Collections.singleton (
[repeat]                          ^
[repeat]   missing type arguments for generic class Set<E>
[repeat]     E extends Object declared in interface Set
This change reduces the warnings dramatically. The ones remaining are in public interfaces
and it's beyond the scope for me to tackle that.. Hopefully, in the future.
=> [NETBEANS-5053] - cleanup Set raw type warnings..

enterprise/web.jsf/src/org/netbeans/modules/web/jsf/impl/facesmodel/JSFConfigComponentImpl.java, enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/support/SourceGroupSupport.java, ide/api.debugger/src/org/netbeans/spi/debugger/ContextAwareSupport.java, ide/schema2beans/src/org/netbeans/modules/schema2beans/JavaBeansUtil.java, ide/xml.text/src/org/netbeans/modules/xml/text/structure/XMLDocumentModelProvider.java, java/form/src/org/netbeans/modules/form/layoutdesign/LayoutUtils.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/jpqleditor/JPQLExecutor.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/provider/DataNucleusProvider.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/provider/DefaultProvider.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/provider/EclipseLinkProvider.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/provider/HibernateProvider.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/provider/KodoProvider.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/provider/OpenJPAProvider.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/provider/ToplinkProvider.java, java/java.source.base/src/org/netbeans/modules/java/source/pretty/VeryPretty.java, java/performance/actionsframework/src/org/netbeans/actions/spi/ContextProviderSupport.java, java/performance/actionsframework/src/org/netbeans/actions/spi/ProxyContextProvider.java, php/php.editor/src/org/netbeans/modules/php/editor/parser/UnknownAnnotationLine.java, php/php.editor/src/org/netbeans/modules/php/editor/parser/annotation/LinkParsedLine.java, php/php.editor/src/org/netbeans/modules/php/editor/parser/astnodes/PHPDocTag.java, platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/results/cpu/StackTraceSnapshotBuilder.java, webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/JsCompletionItem.java, webcommon/web.inspect/src/org/netbeans/modules/web/inspect/webkit/knockout/unused/UnusedBindingsPanel.java
In many places there are unchecked conversion warnings.. This change reduces these errors
when using Collections.EMPTY_MAP to a bare minimum..
For example,
[repeat] /tmp/netbeans/enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/support/SourceGroupSupport.java:172: warning: [unchecked] unchecked conversion
[repeat]             result = Collections.EMPTY_MAP;
[repeat]                                 ^
[repeat]   required: Map<FileObject,SourceGroup>
[repeat]   found:    Map
Clean this up..
=> [NETBEANS-5066] - cleanup usage of EMPTY_MAP warnings..

php/php.editor/src/org/netbeans/modules/php/editor/model/impl/FunctionScopeImpl.java, php/php.editor/test/unit/data/testfiles/completion/lib/nb5062/nb5062.php, php/php.editor/test/unit/data/testfiles/completion/lib/nb5062/nb5062.php.testNb5062Self_01.completion, php/php.editor/test/unit/data/testfiles/completion/lib/nb5062/nb5062.php.testNb5062Self_02.completion, php/php.editor/test/unit/data/testfiles/completion/lib/nb5062/nb5062.php.testNb5062Self_03.completion, php/php.editor/test/unit/data/testfiles/completion/lib/nb5062/nb5062.php.testNb5062Static_01.completion, php/php.editor/test/unit/data/testfiles/completion/lib/nb5062/nb5062.php.testNb5062Static_02.completion, php/php.editor/test/unit/data/testfiles/completion/lib/nb5062/nb5062.php.testNb5062Static_03.completion, php/php.editor/test/unit/data/testfiles/gotodeclaration/testNb5062/testNb5062.php, php/php.editor/test/unit/data/testfiles/markoccurences/testNb5062/testNb5062.php, php/php.editor/test/unit/data/testfiles/testNb5062.php.testNb5062_01a.occurrences, php/php.editor/test/unit/data/testfiles/testNb5062.php.testNb5062_01b.occurrences, php/php.editor/test/unit/data/testfiles/testNb5062.php.testNb5062_01c.occurrences, php/php.editor/test/unit/data/testfiles/testNb5062.php.testNb5062_01d.occurrences, php/php.editor/test/unit/data/testfiles/testNb5062.php.testNb5062_01e.occurrences, php/php.editor/test/unit/data/testfiles/testNb5062.php.testNb5062_01f.occurrences, php/php.editor/test/unit/data/testfiles/testNb5062.php.testNb5062_01g.occurrences, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionNb5062Test.java, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/GotoDeclarationNb5062Test.java, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/OccurrencesFinderImplNb5062Test.java
https://issues.apache.org/jira/browse/NETBEANS-5062
```php
<?php
class Test1
{
private function getTest2() {
return Test2::returnStatic();
}
public function testMethod() {
echo "Test1" . PHP_EOL;
}
public function test() {
$static1 = $this->getTest2(); // Before: $static1 is recognized as Test1, After $static1 is recognized as Test2
var_dump($static1); // object(Test2)#2 (0) {}
$static1->testMethod();
}
}
class Test2
{
public static function returnStatic() {
return new static();
}
public function testMethod() {
echo "Test2" . PHP_EOL;
}
}
$test = new Test1();
$test->test();
```
=> [NETBEANS-5062] PHPDoc static type incorrectly resolved when returned by another class

php/php.editor/src/org/netbeans/modules/php/editor/csl/SemanticAnalysis.java, php/php.editor/test/unit/data/testfiles/semantic/anonymousClass01.php, php/php.editor/test/unit/data/testfiles/semantic/anonymousClass01.php.semantic, php/php.editor/test/unit/data/testfiles/semantic/class005.php, php/php.editor/test/unit/data/testfiles/semantic/class005.php.semantic, php/php.editor/test/unit/data/testfiles/semantic/unusedPrivateConst.php, php/php.editor/test/unit/data/testfiles/semantic/unusedPrivateConst.php.semantic, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/SemanticAnalyzerTest.java
https://issues.apache.org/jira/browse/NETBEANS-5052
Marks unused private constants in PHP Editor in same way as unused private fields and methods.
In following example `BAR3` is marked as unused:
=> [NETBEANS-5052] Mark unused private constants

ide/spi.debugger.ui/apichanges.xml, ide/spi.debugger.ui/manifest.mf, ide/spi.debugger.ui/src/org/netbeans/spi/debugger/ui/DebuggingView.java, java/debugger.jpda.truffle/nbproject/project.xml, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleAccess.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/breakpoints/impl/TruffleBreakpointsHandler.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/TruffleStackFrame.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/models/TruffleDVFrame.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/source/Source.java, java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/FrameInfo.java, java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/GuestObject.java, java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/JPDATruffleAccessor.java, java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/JPDATruffleDebugManager.java, java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/SourcePosition.java, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/DebugAdapterContext.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbSourceProvider.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/breakpoints/NbBreakpoint.java, java/java.lsp.server/vscode/package.json
Sources that have no File associated are put to a special virtual SourceFS filesystem. We add the MIME type information and use these files in NetBeans. It's also assured that breakpoints submitted into these files are resolved correctly.
A simple API change needs to be done: `DVFrame.getSourceMimeType()`.
=> Display sources loaded from String and find their MIME type.

java/java.lsp.server/vscode/package.json
This change is necessary to have files with `application/javascript` MIME type recognized as JavaScript files. VSCode recognizes `text/javascript` only by default.
Sources that come from evaluations may have just `<eval>` name, without an extension. In that case just the associated MIME type defines the language of the source.
=> Inform VSCode that application/javascript is also a MIME type of JavaScript.

enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/index/CompositeComponentModel.java, enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/index/JsfBinaryIndexer.java
We have several JSF libraries that contain both JSF components and JSF composite components.
When the JSF library is open in NetBeans, all JSF components are found within the editor.
When the JSF library is referenced as external JAR, only the JSF components are recognised by the editor, not the JSF composite components.
The fix as suggested in:
https://stackoverflow.com/questions/21607320/jsf-composite-components-in-jar-not-recognised-in-netbeans
works for us.
https://issues.apache.org/jira/browse/NETBEANS-5057
=> [NETBEANS-5057] fix for indexing JSF composite components

java/java.lsp.server/vscode/src/extension.ts, platform/autoupdate.cli/src/org/netbeans/modules/autoupdate/cli/ModuleOptions.java, platform/autoupdate.cli/src/org/netbeans/modules/autoupdate/cli/PrintTable.java
There are problems with booting up `VSNetBeans` - @jisedlac reported problems on Windows:
```
java.io.EOFException
at java.io.DataInputStream.readFully(DataInputStream.java:197)
at org.netbeans.CLIHandler.initialize(CLIHandler.java:822)
at org.netbeans.CLIHandler.initialize(CLIHandler.java:360)
at org.netbeans.MainImpl.execute(MainImpl.java:168)
at org.netbeans.MainImpl.main(MainImpl.java:60)
at org.netbeans.Main.main(Main.java:58)
Exit code 4294967041
```
Also, if you have ever seen _Apache NetBeans Language Server not enabled!_ message  then [scanning just StdOut](https://github.com/apache/netbeans/pull/2576/commits/ad38e1d7b0c739d2d4f53e90c49e2683b6cd184c) shall help.
There is something wrong in `CLIHandler`. This PR isn't (yet) a fix for the problem, but it shall certainly make the …
=> Make the --module --list CLI command more robust

php/php.editor/src/org/netbeans/modules/php/editor/indent/CodeStyle.java, php/php.editor/src/org/netbeans/modules/php/editor/indent/FmtOptions.java, php/php.editor/src/org/netbeans/modules/php/editor/indent/TokenFormatter.java, php/php.editor/src/org/netbeans/modules/php/editor/indent/ui/Bundle.properties, php/php.editor/src/org/netbeans/modules/php/editor/indent/ui/FmtBlankLines.form, php/php.editor/src/org/netbeans/modules/php/editor/indent/ui/FmtBlankLines.java, php/php.editor/test/unit/data/testfiles/formatting/blankLines/MaxPreservedLines01.php, php/php.editor/test/unit/data/testfiles/formatting/blankLines/MaxPreservedLines01.php.formatted, php/php.editor/test/unit/data/testfiles/formatting/blankLines/MaxPreservedLines02.php, php/php.editor/test/unit/data/testfiles/formatting/blankLines/MaxPreservedLines02.php.formatted, php/php.editor/test/unit/data/testfiles/formatting/blankLines/MaxPreservedLines03.php, php/php.editor/test/unit/data/testfiles/formatting/blankLines/MaxPreservedLines03.php.formatted, php/php.editor/test/unit/data/testfiles/formatting/issue176453.php.formatted, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/indent/PHPFormatterBlankLinesTest.java
https://issues.apache.org/jira/browse/NETBEANS-5075
Removes multiple empty lines from PHP code.
Adds setting under Formatting/PHP/Blank Lines.
Formatting options:
=> [NETBEANS-5075] Remove consecutive empty lines when formatting PHP code

platform/core.network/src/org/netbeans/core/network/proxy/NbProxySelector.java
The JDK (AdoptOpenJDK in this case) returns an unmodifiable collection, so we should not call add/addAll on it, but create a new ArrayList instead.
=> Avoid to call add/addAll on a potentially unmodified collection

php/php.editor/src/org/netbeans/modules/php/editor/indent/FormatVisitor.java, php/php.editor/test/unit/data/testfiles/formatting/blankLines/OpenClosePHPTag06.php, php/php.editor/test/unit/data/testfiles/formatting/blankLines/OpenClosePHPTag06.php.formatted, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/indent/PHPFormatterBlankLinesTest.java
https://issues.apache.org/jira/browse/NETBEANS-5096
Fixes blank lines formatting after open tag in script starting with shebang.
Setting for "After Open Tag" is applied instead of "After Open Tag in HTML".
Sample script:
```php
#!/usr/bin/php
<?php 
echo "Hello World!\n";
```
=> [NETBEANS-5096] Fix formatting in executable script

php/php.composer/src/org/netbeans/modules/php/composer/PhpProjectConvertor.java
https://issues.apache.org/jira/browse/NETBEANS-5108
Full name of Composer package name is used in Usages window and File selector.
Before:
After:
=> [NETBEANS-5108] Use complete Composer package name

enterprise/j2ee.earproject/src/org/netbeans/modules/j2ee/earproject/ui/customizer/EarProjectProperties.java, enterprise/j2ee.genericserver/nbproject/project.properties, enterprise/web.jsf/src/org/netbeans/modules/web/jsf/wizards/ManagedBeanPanel.java, enterprise/web.jsf/src/org/netbeans/modules/web/jsf/wizards/PersistenceClientSetupPanel.java, enterprise/web.jsf/src/org/netbeans/modules/web/jsf/wizards/TemplateClientPanelVisual.java, ide/xml.core/src/org/netbeans/modules/xml/dtd/grammar/DTDParser.java, ide/xml.text/src/org/netbeans/modules/xml/text/structure/XMLDocumentModelProvider.java, java/i18n.form/nbproject/project.properties, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/jpacontroller/JpaControllerSetupPanel.java, platform/openide.filesystems/test/unit/src/org/openide/filesystems/URLMapperTestHidden.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/ClassDumpSegment.java
A lot of places in the code has generic use commented out.. For example, the following in
LayoutModel.java
public void unsetSameSize(List/*<String>*/ components, int dimension) {
Iterator i = components.iterator();
while (i.hasNext()) {
String cid = (String)i.next();
LayoutComponent lc = getLayoutComponent(cid);
removeComponentFromLinkSizedGroup(lc, dimension);
}
}
All I've done here is enable it to reduce the warnings and test out the code to make sure it works correctly.
=> [NETBEANS-4458] - enable use of generics

ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java, ide/lsp.client/src/org/netbeans/modules/lsp/client/options/LanguageStorage.java, ide/lsp.client/test/unit/src/org/netbeans/modules/lsp/client/options/LanguageStorageTest.java
The caching of the LSP client that is rooted in project2MimeType2Server
does not work. In the WeakHashMap the keys are help by weak references
and the key is invalidated, once it is GCed. The URIs that are used
as keys become immediately eligible for GC and thus the cache is not
used at all.
To fix this, use a regular HashMap with WeakReference values.
The LSP Clients themselves are either strongly referenced from other
components or can be collected. To not create excessive start/stops of
servers, an additional strong reference is retained for a certain time
after the last bind request was issued. Only after the timeout has
occured, that extra reference is released and the bindings could become
eligible for GC.
=> [NETBEANS-5142] LSP Client creates excessive processes

java/performance/actionsframework/src/org/netbeans/actions/examples/MiniEdit.java
I'm trying to remove the use of a deprecated API that hinders updating the Java version.
MiniEdit.java uses a really old deprecated API. This API prevents us from upgrade the Java
source version in the project properties file.
So step #1 is to remove the use of the old deprecated API.
=> [NETBEANS-5031] - remove use of deprecated APIs in MiniEdit.java

.github/workflows/main.yml
It seems that Xdebug 3 is installed via GitHub Actions. So, we have to fix the ini values. Let's wait for the build job result of this change. 
https://xdebug.org/docs/upgrade_guide
- `xdebug.remote_enable=on` to `xdebug.mode=debug`
- `xdebug.remote_port=9003`: This value is used by default
=> Fix ini values for Xdebug 3

webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/hints/ErrorCheckingSupport.java
When reviewing, please compare also the [original semantics (before the refactoring)](https://github.com/apache/netbeans/commit/580d925e0608690eb3462aad37de15cdf0259853#diff-37427eeda3bcf06f91cce8d11efead9489dbe75a90f4d7433c183846c8a43577L89) with this fixed behaviour.
=> [NETBEANS-5155] retain fallback to file's MIME type.

ide/lib.terminalemulator/src/org/netbeans/lib/terminalemulator/Line.java, ide/lib.terminalemulator/src/org/netbeans/lib/terminalemulator/MyFontMetrics.java, ide/lib.terminalemulator/src/org/netbeans/lib/terminalemulator/Sel.java
I think the best solution would be to rewrite a lot of `ide/lib.terminalemulator` code. Anyway this PR fixes text selection problem which was brought by #2509.
=> [NETBEANS-5070] fix errors on text selection

nbbuild/antsrc/org/netbeans/nbbuild/MergeTrymeArgs.java, nbbuild/build.xml
nbbuild/build.xml uses JavaScript to construct tryme.args property from tryme.arg.* properties. This, however, does not work for JDK 15+, as there is no default JS engine for it. I was thinking of various ways to fix it, but, in the end, this does not seem like a particularly important feature, and my proposal is to simple remove the feature to joing tryme.arg.* properties into tryme.args property.
=> Removing the need for a default JS engine in JDK to call ant tryme.

enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/ClientData.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/ContextAttributes.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/ContextData.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/CookieIn.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/CookieOut.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/CookiesData.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/DispatchData.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/Dispatches.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/EngineData.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/Headers.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/MonitorData.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/Param.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/RequestAttributesIn.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/RequestAttributesOut.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/RequestData.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/ServletData.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/SessionData.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/SessionIn.java, enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/SessionOut.java
In cleaning up Vector raw types, I noticed a bunch of imports in the
Enterprise Web.Monitor module that could use some cleanup.
It's bad form to use the "*" when importing. It's pulls in every class in the import.
In addition, it can break  modularization.
=> [NETBEANS-5185] - cleanup imports in the Enterprise Web.Monitor module

java/java.api.common/src/org/netbeans/modules/java/api/common/classpath/ModuleClassPaths.java, java/java.api.common/test/unit/src/org/netbeans/modules/java/api/common/classpath/ModuleClassPathsTest.java, java/java.source.base/src/org/netbeans/modules/java/source/parsing/PatchModuleFileManager.java, java/maven/src/org/netbeans/modules/maven/queries/UnitTestsCompilerOptionsQueryImpl.java, java/maven/test/unit/src/org/netbeans/modules/maven/queries/UnitTestsCompilerOptionsQueryImplTest.java
So, the problem here is that some Maven projects have a `module-info` for module `$m` in `src/main/java` and another for `$m` in `src/test/java`, which overrides the main one. (Note the module names are the same.) The `maven-compiler-plugin` will then put the `src/main/java` on patch path for (test) `$m`:
https://github.com/apache/maven-compiler-plugin/blob/1b206fe40156bb9814ed8b804a23362ec2b41daa/src/main/java/org/apache/maven/plugin/compiler/TestCompilerMojo.java#L335
This is an attempt to simulate this inside NetBeans, although I am by far not sure if it is correct. It:
-does the tweak in the module projects to include the `--patch-module` option
-tweaks `PatchModuleManager`, so that if we have caches for the main sources, we use the caches
-tweaks the `ClassPath` content so that the …
=> [NETBEANS-4550] Handling tests that have a module-info overriding module-info from sources.

ide/jumpto/src/org/netbeans/modules/jumpto/common/ItemRenderer.java
Also corrected a NotNull ->NullAllowed annotation, based on that ```HighlightingNameFormatter.Builder.create().setCamelCaseSeparator(separatorPattern)``` actually allows null.
=> [NETBEANS-5176] Trivial NPE check on a NullAllowed field on GoTo Type

java/maven/src/org/netbeans/modules/maven/execute/defaultActionMappings.xml
I cannot run/debug tests in [HTML/Java API](https://github.com/apache/netbeans-html4j/tree/master/generic) because they use `@JavaScriptBody` annotation and require post-processing. However, by default Maven doesn't invoke `process-test-classes` before execution. I was considering to fix it by writing `nbactions.xml` file, but it seems better to make it default, which is what this PR does.
Current failure is:
```
-------------------------------------------------------
Running org.netbeans.html.presenters.spi.test.GenericTest
Configuring TestNG with: TestNG652Configurator
SEVERE: When using @JavaScriptBody methods, one needs to either:
- include asm-5.0.jar on runtime classpath
- post process classes, see http://bits.netbeans.org/html+java/dev/net/java/html/js/package-summary.html#post-proc …
```
=> Process test classes before executing single test

ide/css.editor/src/org/netbeans/modules/css/indexing/api/CssIndex.java, ide/css.editor/test/unit/data/testProject/nbproject/project.properties, ide/css.editor/test/unit/data/testProject/nbproject/project.xml, ide/css.editor/test/unit/data/testProject/public_html/test.html, ide/css.editor/test/unit/data/testProject/public_html/test1.css, ide/css.editor/test/unit/data/testProject/public_html/test2.css, ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/ProjectTestBase.java, ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/csl/CssGotoDeclarationTest.java, ide/css.editor/test/unit/src/org/netbeans/modules/css/indexing/api/CssIndexTest.java, ide/css.prep/test/unit/src/org/netbeans/modules/css/prep/editor/CPCssIndexModelTest.java, ide/css.prep/test/unit/src/org/netbeans/modules/css/prep/editor/refactoring/CPWhereUsedQueryPluginTest.java, ide/parsing.lucene/src/org/netbeans/modules/parsing/lucene/support/Queries.java, ide/parsing.lucene/test/unit/src/org/netbeans/modules/parsing/lucene/support/QueriesTest.java
When the index storage of CSS grammar elements was modified to store values individually (74a5e17), not all use-sites were updated. This PR fixes this and adds unit tests for the CSS index functions.
=> [NETBEANS-4739] CSS Go to Declaration , does not work

ide/xml.lexer/src/org/netbeans/api/xml/lexer/XMLTokenId.java, ide/xml.text/src/org/netbeans/modules/xml/text/resources/Bundle.properties, ide/xml.text/src/org/netbeans/modules/xml/text/resources/XML-fontsColors.xml, ide/xml.text/test/qa-functional/src/org/netbeans/modules/xml/text/syntax/data/goldenfiles/ColoringTest/testXMLColoring.pass
**Recommended Retest**
1. Start netbeans
2. Enter Options->Fonts & Colors
3. Select XML for the language
4. Select Pi Content
5. Change the Foreground color to something other than the default [0,0,124] (Which is illegible in FlatLafDark)
6. Note that the color in the preview box changes.  (The text `version="1.0"`)
6. Exit netbeans
7. Repeat steps 1-3
8. Verify `version="1.0"` is the newly selected color.
Note 1:  In the master branch (and many versions before that), after restarting netbeans, the color will be restored to the original [0,0,124]
Note 2:  This fix also fixes the name styling for the PI  Target and PI End Delimiter.
=> [NETBEANS-4256] Fixed inconsistent xml fontcolor tag names.

ide/css.lib/src/org/netbeans/modules/css/lib/api/properties/GrammarResolver.java, ide/css.lib/test/unit/src/org/netbeans/modules/css/lib/api/properties/GrammarResolverTest.java
When checking the global values, the input state needs to be reset after
the possible values are checked. Before this change the right grammar
element was found, but then could not be processed, because the state
of the input was already changed by the checking.
=> [NETBEANS-5214] Fix handling of global values

webcommon/javascript.cdnjs/src/org/netbeans/modules/javascript/cdnjs/ui/FilesNode.java
https://issues.apache.org/jira/browse/NETBEANS-4783
When adding new files from CDNJS new files are not selected by default.
=> [NETBEANS-4783] Unselect added files from CDNJS by default

java/java.source.base/src/org/netbeans/modules/java/source/PostFlowAnalysis.java, java/java.source.base/src/org/netbeans/modules/java/source/builder/ElementsService.java, java/java.source.base/src/org/netbeans/modules/java/source/usages/SourceAnalyzerFactory.java, java/java.source.base/test/unit/src/org/netbeans/api/java/source/ElementUtilitiesTest.java
Symbol.islocal (internal javac API) has been renamed in JDK 16, re-implementing using standard API to avoid the dependency on the internal API.
=> Symbol.islocal has been renamed in JDK 16, avoiding the use of it

java/jshell.support/src/org/netbeans/modules/jshell/tool/JShellTool.java
When I tried some code with JShell I found out that there were differencies in default imports between JShell from jdk and internal JShell from Netbeans. Default imports from JDK JShell :
jshell> /imports
|    import java.io.*
|    import java.math.*
|    import java.net.*
|    import java.nio.file.*
|    import java.util.*
|    import java.util.concurrent.*
|    import java.util.function.*
|    import java.util.prefs.*
|    import java.util.regex.*
|    import java.util.stream.*
Netbeans JShell :
[1]-> /imports
|    import java.util.*
|    import java.io.*
|    import java.math.*
|    import java.net.*
|    import java.util.concurrent.*
|    import java.util.prefs.*
|    import java.util.regex.*
I think it would be better if these default imports would be the same.
=> update default imports for JShell

ide/code.analysis/manifest.mf, ide/code.analysis/src/org/netbeans/modules/analysis/Bundle.properties, ide/code.analysis/src/org/netbeans/modules/analysis/resources/layer.xml
https://issues.apache.org/jira/browse/NETBEANS-5210
Inspection settings (from Code > Inspect) can be exported from Tools > Options.
Settings are registered under Miscellaneous > Code Inspections.
=> [NETBEANS-5210] Export code inspection settings

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractDialogDisplayer.java
Using VSNB ext 12.2.252 and GraalVM 21.1.0 JDK8 CE build.
* Create Micronaut App project - see [wiki](https://cwiki.apache.org/confluence/display/NETBEANS/Apache+NetBeans+extension+for+Visual+Studio+Code)
* Click icon in Explorer to add file, name it e.g. "HellController.java"
* paste in content for HelloController.java sample.
* Rename the file in VSCode explorer to "HelloController.java"
* VSNetBeans complains file was changed on disk and has to be reloaded.
* Check the PROBLEMS window in VSCode it still lists "HellController.java" as having improperly named class.
* Press F5 for debugging the project it prints to console   :
```
Info: Saving HellController ...
Info: Save All finished.
and dialog appears with "Cannot save HellController" message from VSNB ext
```
*    Close the folder …
=> Renaming modified src.java file leads to Cannot save src.java error. Hotfix.

php/php.editor/src/org/netbeans/modules/php/editor/resources/layer.xml, php/php.editor/src/org/netbeans/modules/php/editor/verification/Bundle.properties, php/php.editor/src/org/netbeans/modules/php/editor/verification/PSR4Hint.java, php/php.editor/test/unit/data/testfiles/verification/PSR4/testClassNameDifferent/Vendor/App/ClassName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testClassNameDifferent/Vendor/App/ClassName.php.testClassNameDifferent.hints, php/php.editor/test/unit/data/testfiles/verification/PSR4/testClassNameDifferentCase/Vendor/App/ClassName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testClassNameDifferentCase/Vendor/App/ClassName.php.testClassNameDifferentCase.hints, php/php.editor/test/unit/data/testfiles/verification/PSR4/testClassNameOk/Vendor/App/ClassName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testInterfaceNameDifferent/Vendor/App/InterfaceName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testInterfaceNameDifferent/Vendor/App/InterfaceName.php.testInterfaceNameDifferent.hints, php/php.editor/test/unit/data/testfiles/verification/PSR4/testInterfaceNameDifferentCase/Vendor/App/InterfaceName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testInterfaceNameDifferentCase/Vendor/App/InterfaceName.php.testInterfaceNameDifferentCase.hints, php/php.editor/test/unit/data/testfiles/verification/PSR4/testInterfaceNameOk/Vendor/App/InterfaceName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testNamespaceDifferent/Vendor/App/ClassName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testNamespaceDifferent/Vendor/App/ClassName.php.testNamespaceDifferent.hints, php/php.editor/test/unit/data/testfiles/verification/PSR4/testNamespaceDifferentCase/Vendor/App/ClassName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testNamespaceDifferentCase/Vendor/App/ClassName.php.testNamespaceDifferentCase.hints, php/php.editor/test/unit/data/testfiles/verification/PSR4/testNamespaceOk/Vendor/App/ClassName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testSubNamespaceOk/App/ClassName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testSubNamespaceOk/App/ClassName.php.testSubNamespaceOk.hints, php/php.editor/test/unit/data/testfiles/verification/PSR4/testTraitNameDifferent/Vendor/App/TraitName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testTraitNameDifferent/Vendor/App/TraitName.php.testTraitNameDifferent.hints, php/php.editor/test/unit/data/testfiles/verification/PSR4/testTraitNameDifferentCase/Vendor/App/TraitName.php, php/php.editor/test/unit/data/testfiles/verification/PSR4/testTraitNameDifferentCase/Vendor/App/TraitName.php.testTraitNameDifferentCase.hints, php/php.editor/test/unit/data/testfiles/verification/PSR4/testTraitNameOk/Vendor/App/TraitName.php, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/verification/PSR4HintTest.java
https://issues.apache.org/jira/browse/NETBEANS-377
- Added hints for [PSR-4 Autoloader](https://www.php-fig.org/psr/psr-4/) standard.
- Checks that class/interface/trait declaration matches file name.
- Checks that namespace matches directory structure.
- Highlights only non-matching part of namespace.
=> [NETBEANS-377] Add PSR-4 hints

ide/parsing.api/src/org/netbeans/modules/parsing/api/Source.java
Since the patch removes `assert`, it deserves some explanation. The thing to remember up front is: in normal NetBeans IDE or NetBeans application that uses Parsing modules, there's just **a single instance** of `SourceFactory` interface, and that instance has just **a single** cache. By default `DefaultSourceFactory` in Parsing API in `implspi` package (which is NOT public, btw).
The interface was introduced during API/UI split in the past, and one of the driving scenarios were server applications (hey, LSP is another of them !) that could _eventually_ support multi-tenancy. The check was there to ensure that a retruned `Source` buffer really belongs to the calling context.
We do not have multi-tenancy server scenario (any more): It never was in NB IDE and the offspring projects died one …
=> Hotfix: remove redundant check that causes LSP tests to fail.

java/maven/src/org/netbeans/modules/maven/output/ExecPluginOutputListenerProvider.java
The Gluon JavaFX templates use the org.openjfx:javafx-maven-plugin maven plugin to run, as a result, the maven goal javafx:run was never treated the same as a normal Java application which uses the org.codehaus.mojo:exec-maven-plugin maven plugin.
I've added the goal javafx:run to the list of supported exec goals in `ExecPluginOutputListenerProvider.java`
=> [NETBEANS-5148] Added javafx:run to supported execgoals

platform/openide.util/src/org/openide/util/NbBundle.java, platform/openide.util/test/unit/src/org/openide/util/NbBundleTest.java
Changed NbBundle to read Bundle files using UTF-1 encoding by default, and
automatically switch to ISO-8859-1 if UTF-1 decoding fails. System property
java.util.PropertyResourceBundle.encoding can alter the behavior
like for PropertyResourceBundle (from JDK9).
=> [NETBEANS-5181] Update NbBundle to read bundle files like JDK9 does (UTF-8 then ISO-8859-1)

java/java.hints/src/org/netbeans/modules/java/hints/errors/CreateClassFix.java, java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceExpressionBasedMethodFix.java, java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceMethodFix.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/LspServerUtils.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ConstructorGenerator.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/vscode/src/extension.ts
- [GR-28602] Request textDocument/codeAction failed when selecting source code for Introduce var refactor
- [GR-28596] Implementing an interface results in NullPointerException
- [GR-28601] GeneratorUtils$DuplicateMemberException: Class member already exists form Generate Constructor source action
- [GR-28604] GeneratorUtils$DuplicateMemberException: Class member already exists thrown from introduce element hints
- [GR-28614] IllegalStateException from Rename Symbol
=> Various fixes for LSP codeAction and rename requests.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/DebugAdapterContext.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbDisconnectRequestHandler.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/LspInternalHandle.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/OperationContext.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractProgressEnvironment.java
Followup to the previous ProgressHandle PRs. Changes the way `OperationContext` records created handles: they are recorded as soon as the `InternalHandle` instance is created (so it may not be started at the time someone calls `getHandles`).
The DAP server is then able to collect ProgressHandles created during the course of `invokeAction` call; hopefully the 1st will be the handle to the Executor.
=> Support executor ProgressHandle cancel over DAP protocol.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
Two changes:
-the LSP clients don't (AFAIK) understand the jar:file: URI/URLs. So we use a file-based cache. But internally we should still use the original jar:file: file, as various question (ClassPath, CompilerOptions) have answer for these original URIs
-properly filtering out hints when their severity is disabled for the given file inside the LSP Server.
=> [NETBEANS-5229] Fixing mapping of jar:file URI to cache and back; disabling ErrorDescriptions in cases when they should be disabled.

extide/gradle/src/org/netbeans/modules/gradle/GradleModuleFileCache21.java
Trivial fix to close the Stream using try with resources.
=> [NETBEANS-5177] Fix filehandle leak in GradleModuleFileCache21

platform/openide.util.ui/src/org/netbeans/modules/openide/util/NbMutexEventProvider.java, platform/openide.util.ui/test/unit/src/org/netbeans/modules/openide/util/NbMutexEventProviderTest.java, platform/openide.util/apichanges.xml, platform/openide.util/manifest.mf, platform/openide.util/src/org/openide/util/Mutex.java
While working on #2652 it turned out that `OpenProjectList` class is using `Mutex.EVENT` to deliver changes and that the call disassociates the event deliver from the originating request. One option is to modify `OpenProjectList` to deliver events synchronously (at least in `GraphicsEnvironment.isHeadless()` mode, the other is to make sure effective lookup set by `Lookups.executeWith` is properly propagated through `Mutext.EVENT` methods. That's what this PR proposes.
=> Let Mutex.EVENT methods co-operate with Lookups.executeWith(...)

php/php.editor/src/org/netbeans/modules/php/editor/verification/PSR4Hint.java
https://issues.apache.org/jira/browse/NETBEANS-5253
Fixes NPE in PSR-4 hint when user navigates to PHP stubs.
To test use following code:
```php
$now = new \DateTime();
```
and then navigate to declaration of `DateTime`.
=> [NETBEANS-5253] Fix NPE in PSR-4 hint

php/php.dbgp/src/org/netbeans/modules/php/dbgp/packets/DbgpMessage.java
https://issues.apache.org/jira/browse/NETBEANS-5249
Added hint how to enable logging with Xdebug 3.
Before: 
After:
To test the dialog I added invocation of `notifyPacketError()` at the beginning of `DbgpMessage.create()` method. Starting debug session will then show multiple dialog boxes (one for each message received from Xdebug).
=> [NETBEANS-5249] PHP debugger - improved Xdebug log hint

php/php.dbgp/src/org/netbeans/modules/php/dbgp/ui/DbgpMethodBreakpointPanel.form, php/php.dbgp/src/org/netbeans/modules/php/dbgp/ui/DbgpMethodBreakpointPanel.java
https://issues.apache.org/jira/browse/NETBEANS-5228
Enables support for breakpoint on return from function in PHP debugger.
Originally disabled in 2008 because of bug in Xdebug, the bug was fixed in 2009.
=> [NETBEANS-5228] Enable 'return' breakpoint in PHP debugger

php/php.dbgp/src/org/netbeans/modules/php/dbgp/packets/Property.java, php/php.dbgp/src/org/netbeans/modules/php/dbgp/packets/PropertyValueResponse.java
https://issues.apache.org/jira/browse/NETBEANS-5234
Fixed processing of `property_value` command response.
Because response does not contain variable name, it has to be copied from command.
For details see [Xdebug documentation](https://xdebug.org/docs/dbgp#property-get-property-set-property-value) 
Fixed `Property.setName()` because code for adding attribute did not work.
=> [NETBEANS-5234] PHP debugger - fix display of long strings

php/php.dbgp/manifest.mf, php/php.dbgp/nbproject/project.xml, php/php.dbgp/src/org/netbeans/modules/php/dbgp/DebuggerOptions.java, php/php.dbgp/src/org/netbeans/modules/php/dbgp/packets/FeatureGetCommand.java, php/php.dbgp/src/org/netbeans/modules/php/dbgp/packets/InitMessage.java, php/php.project/manifest.mf, php/php.project/src/org/netbeans/modules/php/project/api/PhpOptions.java, php/php.project/src/org/netbeans/modules/php/project/ui/options/Bundle.properties, php/php.project/src/org/netbeans/modules/php/project/ui/options/PhpDebuggerPanel.form, php/php.project/src/org/netbeans/modules/php/project/ui/options/PhpDebuggerPanel.java, php/php.project/src/org/netbeans/modules/php/project/ui/options/PhpDebuggerPanelController.java, php/php.project/src/org/netbeans/modules/php/project/ui/options/PhpOptions.java
https://issues.apache.org/jira/browse/NETBEANS-2843
- Adds PHP debugger option to enable/disable support of resolved breakpoints in Xdebug.
- Adds new Xdebug feature 'resolved_breakpoints'.
- Requests use of resolved breakpoints during debug session initialization.
- Supported by XDebug 2.8 or newer.
=> [NETBEANS-2843] PHP debugger - support for resolved breakpoints

php/php.editor/src/org/netbeans/modules/php/editor/codegen/CGSGenerator.java
https://issues.apache.org/jira/browse/NETBEANS-5261
Changes settings of PHP code generators to shared in project.
Style of generated getters/setters/constructors is part of coding standard so it should be part of shared settings.
=> [NETBEANS-5261] Shared settings for PHP code generators

java/java.lsp.server/nbcode/integration/manifest.mf, java/java.lsp.server/nbcode/nbproject/platform.properties, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/LspInternalHandle.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/OperationContext.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/ProgressOperationEvent.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/ProgressOperationListener.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java, java/java.lsp.server/vscode/package-lock.json, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/test/suite/extension.test.ts, platform/core.execution/manifest.mf, platform/core.execution/src/org/netbeans/core/execution/ExecutionEngine.java, platform/core.execution/src/org/netbeans/core/execution/RunClassThread.java, platform/core.execution/test/unit/src/org/netbeans/core/execution/CoreExecutionCompatibilityTest.java, platform/openide.execution/nbproject/project.properties, platform/openide.execution/src/org/openide/execution/ExecutionEngine.java, platform/openide.execution/test/unit/src/org/openide/execution/ExecutionCompatibilityTest.java, platform/openide.execution/test/unit/src/org/openide/execution/ExecutionEngineHid.java
Maven executor forks the execution into a separate thread, and only then it creates a `ProgressHandle`. The handle is likely to be created **after** the _DAP_ call finishes, so it is not collected by the current code. I've implemented a event source  + listener interface to listen on create/finish of progress-generating tasks. _DAP_ operation can now establish a listener and receive a ProgressHandle even after the original launch request returns; it can connect the `ProgressHandle` to the `DebugContext`.
The default execution engine implementation should support default `Lookup` passing, so the threads it creates operate in the caller's context.
The tests of LSP server must run in headless mode; without that property, some code takes wrong path, blocking test execution on UI that nobody …
=> Properly stop Maven execution from LSP/DAP

extide/gradle/arch.xml, ide/projectui/arch.xml, java/java.lsp.server/nbcode/branding/modules/org-openide-loaders.jar/org/netbeans/modules/openide/loaders/Bundle.properties, java/java.lsp.server/nbcode/integration/nbproject/project.xml, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/Bundle.properties, java/maven/arch.xml, nbbuild/javadoctools/links.xml, nbbuild/javadoctools/properties.xml, nbbuild/javadoctools/replaces.xml, platform/core.multiview/arch.xml, platform/core.network/arch.xml, platform/o.n.core/arch.xml, platform/openide.awt/arch.xml, platform/openide.awt/src/org/openide/awt/Actions.java, platform/openide.loaders/apichanges.xml, platform/openide.loaders/arch.xml, platform/openide.loaders/manifest.mf, platform/openide.loaders/src/org/netbeans/modules/openide/loaders/AskEditorQuestions.java, platform/openide.loaders/src/org/netbeans/modules/openide/loaders/Bundle.properties, platform/openide.loaders/src/org/openide/loaders/Bundle.properties, platform/openide.loaders/src/org/openide/text/DataEditorSupport.java, platform/openide.loaders/test/unit/src/org/netbeans/modules/openide/loaders/AskEditorQuestionsTest.java, platform/openide.loaders/test/unit/src/org/netbeans/modules/openide/loaders/Bundle_da.properties, platform/openide.loaders/test/unit/src/org/netbeans/modules/openide/loaders/Bundle_no.properties, platform/openide.windows/arch.xml, platform/options.api/arch.xml
VS Code manages files itself. Rename, copy, delete is handled by their UI and only later notified to the NetBeans backend. This PR provides branding API, to disable showing dialogs to the user and provide a default answer. This approach builds on previous branding APIs introduced for example in #2427, #2386, etc.
=> Don't show reload/save dialogs in VSNetBeans

java/java.j2seplatform/apichanges.xml, java/java.j2seplatform/arch.xml, java/java.j2seplatform/manifest.mf, java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/api/Bundle.properties, java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/queries/SourceJavadocAttacherUtil.java, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/AbstractJ2SEAttacherTestBase.java, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/api/Bundle_da.properties, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/api/Bundle_no.properties, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/libraries/J2SELibrarySourceJavadocAttacherTest.java, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/libraries/JavadocForBinaryQueryLibraryImplTest.java, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/libraries/LibraryTestUtils.java, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/libraries/SourceForBinaryQueryLibraryImplTest.java, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/libraries/TestLibraryProviderImpl.java, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformSourceJavadocAttacherTest.java, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/queries/DefaultSourceJavadocAttacherTest.java, java/java.lsp.server/nbcode/branding/modules/org.netbeans.modules.java.j2seplatform.jar/org/netbeans/modules/java/j2seplatform/api/Bundle.properties, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/j2seplatform/api/Bundle.properties
This PR is somewhat inspired by #2685: LSP tests now hang on displaying 'attach sources' for a Java platform, which is traditionally handled by `GraphicsEnvironment.isHeadless()`. But @JaroslavTulach approach shows a way how to do that more politely and allow the application to select which parts of the interaction are applicable in the final environment.
I have slightly modified the support made by @dbalek for 12.3; the `SourceJavadocAttacher.attachSources()` call could (IMHO) fail in a headless environment, since it got no `plugin` from the library + platform Attachers. @dbalek please review the behaviour: the other attachers now do nothing in 'yes' mode - they could possibly use the `Definer` SPI as well.
The actual bundle keys may still need to be modified based on discussion in …
=> Allow "Attach sources/javadoc" UIs to be branded out.

ide/options.editor/src/org/netbeans/modules/options/colors/SyntaxColoringPanel.java
Scrolling using mouse wheel (or scroll arrow buttons) in "Options > Fonts & Colors > Syntax > Preview area" (select language "Yaml") is very slow (1-3 pixel) because a `JPanel` is used as view in a `JScrollPane`. Since `JPanel` does not implement the `javax.swing.Scrollable` interface, the scrollpane uses a unit increment of 1. So clicking scroll arrow arrows (or rotating mouse wheel one tick) scrolls only 1-3 pixel (depending on OS and scroll amount specified in OS settings).
This fix simply sets unit increment to 10.
This is similar to other code in NB:
https://github.com/apache/netbeans/search?q=setUnitIncrement
This affects all Lafs.
For FlatLaf, this also improves smooth scrolling (using trackpad) reported here:
https://issues.apache.org/jira/browse/NETBEANS-5025
=> [NETBEANS-5025] Fix wheel/trackpad scrolling in Options > Fonts & Colors > Syntax > Preview area

java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Add entry to the OFFICIAL_JAVADOC Map
[JDK 17 API Javadoc](https://download.java.net/java/early_access/jdk17/docs/api/)
=> [NETBEANS-5164] - Add javadoc for JDK 17 early access

nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java, nbbuild/binaries-default-properties.xml, nbbuild/build.xml
Always download Maven binaries by default rather than relying on local .m2 cache (issues with Jenkins builds).
Expose binaries.repos property so source repositories of binaries can be configured, including local .m2 if desired.
Passing eg. `-Dbinaries.repos="file:///<HOME>/.m2/repository/ https://repo1.maven.org/maven2/"`to ant still allows use of local binaries if necessary.
=> Don't use local .m2 cache in build by default.

cpplite/cpplite.debugger/external/binaries-list, cpplite/cpplite.debugger/external/cpplite-mi-f8f8250283be-license.txt, cpplite/cpplite.debugger/nbproject/project.properties, cpplite/cpplite.debugger/nbproject/project.xml
Publishing fails with "-SNAPSHOT" dependencies. This PR uses the id of
the originating mercurial commit as version.
=> Fix versioning of external dependency cpplite-mi

platform/core.multitabs/src/org/netbeans/core/multitabs/impl/DocumentSwitcherTable.java
https://issues.apache.org/jira/browse/NETBEANS-5272
Fixes issue when files from different projects with same name are not grouped correctly.
Adds sorting by project path to ensure files from same project are together.
Sample project reproducing the issue is available in JIRA.
=> [NETBEANS-5272] Fixed grouping of documents in document switcher

java/java.lsp.server/build.xml, java/java.lsp.server/vscode/src/extension.ts
- `PrepareBundles` task should use the same versions of NPMs as the extension itself
- stop LSP client before killing server while restarting NBLS
=> Fixing failing build.

ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/FeatureProjectFactory.java, ergonomics/ide.ergonomics/test/unit/src/org/netbeans/modules/ide/ergonomics/fod/FeatureProjectFactoryTest.java
Basically, if the project marker file relative path contains `../`, we attempt to use the parent file. But, the `../` is never stripped from the marker file relative path. Trying to fix here.
=> Fixing a mistake in ergonomics project detection, so that it can detect OpenJDK projects.

ide/css.editor/src/org/netbeans/modules/css/editor/module/main/StandardPropertiesHelpResolver.java
When the documentation for the target property could not be found, the
whole page of the CSS module was passed as help text. The rendering of
the HTML in combination with a popup menu caused problems on hide.
The documentation could be rendered, but on hide, the EDT is stuck in a
call to:
javax.swing.PopupFactory$MediumWeightPopup.hide()
Instead of rendering the whole documentation, the information "there is
no documenation" is rendered. While not optimal, it at least prevents a
heard freeze.
=> [NETBEANS-5304] CSS: Prevent UI blocking on undocumented properties

platform/libs.flatlaf/external/binaries-list, platform/libs.flatlaf/external/flatlaf-1.0-rc2-license.txt, platform/libs.flatlaf/nbproject/org-netbeans-libs-flatlaf.sig, platform/libs.flatlaf/nbproject/project.properties, platform/libs.flatlaf/nbproject/project.xml
Updates FlatLaf to latest version to fix `Enter` key regression:
https://issues.apache.org/jira/browse/NETBEANS-5299
https://github.com/JFormDesigner/FlatLaf/releases/tag/1.0-rc2
=> [NETBEANS-5299] Update FlatLaf from 1.0-rc1 to 1.0-rc2

extide/gradle/src/org/netbeans/modules/gradle/execute/navigator/TasksPanel.java
I've seen this issue only once so far, when closed some Gradle projects, having no project open in the IDE.
Then opening new other Gradle projects were throwing that NPE.
=> [NETBEANS-5340] Prevent NPE on TaskNode when opening Gradle Projects

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbSourceProvider.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbThreads.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchRequestHandler.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchWithDebuggingDelegate.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/vscode/package-lock.json, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts
This is a fix of NETBEANS-5326
If Run test/Debug test code lenses are used through LSP protocol, the actual test output is not visible. In case of Debug tes, the output is visible when it succeeds, however, it is significantly cut when it fails, preventing from seeing the test failure.
Correction of output from Run/Debug code lens actions.
- In case of Debug, the TerminatedEvent was sent too soon. Now, similar to Run, the TerminatedEvent is sent when the application terminates.
- Run now runs in the same was as "Run Without Debug" - through startDebugger with noDebug = true. This is necessary for consistency and proper output display.
- A NPE associated with a missing source path in case of Run is addressed
=> [NETBEANS-5326] LSP codelens output fixes

java/java.lsp.server/nbcode/branding/modules/org-openide-loaders.jar/org/netbeans/modules/openide/loaders/Bundle.properties
As described in NETBEANS-5319, when new files are added through LSP (e.g. in a VSCode extension), breakpoints do not work in these files at all.
If a file is modified, then breakpoints are submitted to wrong locations depending on the scope of the modification.
The reason is that NetBeans LSP backend is holding modified documents and VSCode updates files on disk at the same time. But breakpoints are resolved to disk locations that correspond to the sate before the files were modified. Until the files are saved through the NetBeans, breakpoints will resolve to wrong locations.
This fix allows to save modifications it got through the LSP protocol, which synchronizes the content and allows breakpoints to resolve as expected.
=> [NETBEANS-5319] Always do save modified files when used through LSP.

java/java.lsp.server/vscode/CHANGELOG.md
Update of CHANGELOG.MD for NetBeans VSCode ext. release 12.3
=> VSCode NetBeans (LSP) changelog update for 12.3 rel.

platform/openide.dialogs/src/org/openide/DialogDisplayer.java
the word "method" is repeated twice
=> docs (DialogDisplayer notifyLater) small typo

java/java.lsp.server/build.xml, java/java.lsp.server/nbcode/integration/manifest.mf, java/java.lsp.server/nbcode/integration/nbproject/project.xml, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml, java/java.lsp.server/nbcode/integration/test/unit/src/org/netbeans/modules/nbcode/integration/VerifyJustOneUpdateCenterTest.java, java/java.lsp.server/nbcode/nbproject/platform.properties, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/test/suite/extension.test.ts
Gregor Kováč [reported problems on subsequent start of VSNetBeans](https://lists.apache.org/thread.html/r07d0861858590e3a047d284d1443b8794912f4caeb231a3de19efedc%40%3Cusers.netbeans.apache.org%3E) and we have tracked down the problem to autoupdate!
There is `updatecenters` module in VSNetBeans since 90d2af9 - it is needed to install `nbjavac` on JDK8. However it also provides other update centers.
There is code checking whether Apache NetBeans `java.lsp.server` module is properly started. It [uses a regexp](https://github.com/apache/netbeans/blob/master/java/java.lsp.server/vscode/src/extension.ts#L350) to parse the output and searches for:
```ts
stdOut.match(/org.netbeans.modules.java.lsp.server.*Enabled/)
```
However, since recently there has been a release of updates and the output now …
=> Avoid autoupdating existing NetBeans modules.

platform/libs.flatlaf/external/binaries-list, platform/libs.flatlaf/external/flatlaf-1.0-license.txt, platform/libs.flatlaf/nbproject/org-netbeans-libs-flatlaf.sig, platform/libs.flatlaf/nbproject/project.properties, platform/libs.flatlaf/nbproject/project.xml
This FlatLaf update fixes a regression in FlatLaf 1.0-rc2 (and older)
that breaks the Jvi plugin as soon as a popup should be shown. 
E.g. pressing `:w` in editor.
https://issues.apache.org/jira/browse/NETBEANS-5362
FlatLaf 0.31, which was used in NB 12.2 (and before), did not have this issue.
So only NB 12.3 betas are affected.
The NPE occurs when invoking `PopupFactory.getSharedInstance().getPopup( owner, contents, x, y )`
with `null` as `owner`, which is actually unusual.
`PopupFactory` is e.g. used to show popups for code completion.
There are about 30 source files in NB repo that use `PopupFactory`:
https://github.com/apache/netbeans/search?q=popupfactory
So it is possible that also some popups in NB core are affected by this Flatlaf bug.
Hope we can get this fix into 12.3 beta 3.
=> [NETBEANS-5362] Update FlatLaf from 1.0-rc2 to 1.0 to fix NPE in Jvi plugin when showing popup

java/gradle.java/src/org/netbeans/modules/gradle/java/action-mapping.xml
See [NETBEANS-5353](https://issues.apache.org/jira/browse/NETBEANS-5353) description; this PR attempts to use gradle's up-to-date checks so unnecessary compilations are avoided during test runs/debugs.
@lkishalmi  please review.
=> [NETBEANS-5353] Use cleanTest instead of rerun-tasks to force test to run

extide/gradle/src/org/netbeans/modules/gradle/ProjectTrust.java, extide/gradle/src/org/netbeans/modules/gradle/api/execute/RunUtils.java
If the user acknowledges run of the gradle build script in the IDE, the script may be reloaded from time to time, for example as result of __Fix project problems__ or other occasions. If the user did not check "Trust permanently" in the question, the IDE would ask the user repeatedly even during the same IDE session.
This change in 932c71c will change the behaviour that after user's acknowledgement, the IDE trust the buildscript within this IDE run only - and won't ask again.
The other commits that were originally part of this PR were separated to PR #2765 per @lkishalmi request.
=> [NETBEANS-5318] Temporary script trust.

ide/projectui/src/org/netbeans/modules/project/ui/problems/BrokenReferencesImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/NotifyDescriptorAdapter.java
During LSP testing with gradle, I've found out that if problem resolution fails, the action may be repeated again. Along the way, I've also noticed that the LSP `DialogDisplayer` implementation does not stip `&` that mark mnemonic characters in String options (choices) - LSP protocol does not support such pattern (yet).
=> Broken project auto-resolution repeats actions

.travis.yml, nb/updatecenters/extras/nbjavac.api/release/modules/ext/nb-javac-15.0.0.2-api.jar.external, nb/updatecenters/extras/nbjavac.impl/release/modules/ext/nb-javac-15.0.0.2-impl.jar.external, nbbuild/antsrc/org/netbeans/nbbuild/AutoUpdate.java, nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java
Let `AutoUpdate` task recognize m2:/ URL scheme, so VSCode build can install additional nbjavac modules from Maven.
The [BUILD.md](https://github.com/apache/netbeans/blob/234392d4fc125d4e20a116598821b2cfd378dfc6/java/java.lsp.server/vscode/BUILD.md) file suggests to use:
```bash
java/java.lsp.server$ ant build-lsp-server -D3rdparty.modules=.*nbjavac.*
```
to build the LSP server with additionally installed `nbjavac` modules. The download no longer works since #2759 - the `AutoUpdate` task hasn't be updated to understand the `m2:/` protocol. This PR:
* calls from `AutoUpdate` task to `DownloadBinaries` to handle the `m2:/` protocol
* modifies the travis check to use the `-D3rdparty.modules` property, so we have some test coverage
* the [release …
=> Let AutoUpdate task recognize m2:/ URL scheme

nb/updatecenters/extras/nbjavac.api/release/modules/ext/nb-javac-15.0.0.2-api.jar.external, nb/updatecenters/extras/nbjavac.impl/release/modules/ext/nb-javac-15.0.0.2-impl.jar.external, nbbuild/antsrc/org/netbeans/nbbuild/AutoUpdate.java, nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java
m2:/ became a defacto API for the autoupdate mechanism. Both OpenJFX and
nb-javac rely on being able to be downloaded via the ".external" files
mechanism and third party modules could also rely on the exact syntax
of the URLs.
Instead of modifying the URL format, a new ad-hoc parser is introduced
to convert the m2 URL into maven coordinates.
=> Restore original format of m2:/ URLs modified by aa256463dcefb3b95bec6b7ac74e04a960015bc9

extide/o.apache.tools.ant.module/src/org/apache/tools/ant/module/bridge/AntBridge.java, extide/o.apache.tools.ant.module/test/unit/data/compile/Test.java, extide/o.apache.tools.ant.module/test/unit/data/compile/build.xml, extide/o.apache.tools.ant.module/test/unit/src/org/apache/tools/ant/module/bridge/AntBridgeTest.java
As noted here:
https://github.com/apache/netbeans/pull/2761#issuecomment-787094888
When compiling using `ant` inside the IDE, `--release` does not work properly. The reason is that `javac` for the compilation is load using a (somewhat weird) ClassLoader magic, and is missing the registration for `JDKPlatformProvider`. The registration is normally in module-info, but the ClassLoader magic load javac in an unnamed module, and that requires META-INF/services registration.
The proposed patch here is only to inject the registration. Eventually, we may want to try a simpler way to use `javac` from `ant` while running inside the IDE.
=> Register JDKPlatformProvider when creating javac in ant's ClassLoader.

extide/gradle/src/org/netbeans/modules/gradle/GradleProjectProblemProvider.java
When the user triggers Priming Build from Project problems window, another "Trust the project" dialog appears immediately. The Project Problems window already warned about potential code execution done as part of the Gradle script.
This is inconsistent with manual Build action:
- open a fresh untrusted, unprimed gradle project
- dismis Project Problems window
- execute Project | Build or Build from project's context menu
=> no warning, no dialog, project becomes trusted.
This PR let the Priming Build behave just as a regular build: mark the project as trusted.
=> Trust priming build, as the user already saw the warning.

nbbuild/packaging/netbeans-dev_snap/snap/snapcraft.yaml
This is a small experimental patch affects ~10 people using netbeans-dev Snap
It set the build to Java 11, and also have the experiment to use the SNAP_USER_DATA directory copy feature of Snap. If it goes well, I'm going to have something like that for the netbeans Snap as well. That would actually mean, there would be no upgrade dialog to be displayed when the software is updated, snap would copy the previous user/cache dir over. Also when switching back a release the old userdir would be used.
As this change does not affect anything else in NB, I'm going to merge it without approval, reviewers were added for notification purposes only.
=> Use Java 11 to Build NetBeans dev Snap

ide/projectapi/apichanges.xml, ide/projectapi/manifest.mf, ide/projectapi/src/org/netbeans/spi/project/ActionProvider.java, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/LspServerState.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/maven/manifest.mf, java/maven/nbproject/project.xml, java/maven/src/org/netbeans/modules/maven/ActionProviderImpl.java, java/maven/src/org/netbeans/modules/maven/InternalActionDelegate.java, java/maven/src/org/netbeans/modules/maven/problems/MavenModelProblemsProvider.java, java/maven/src/org/netbeans/modules/maven/problems/SanityBuildAction.java, java/maven/test/unit/src/org/netbeans/modules/maven/problems/PrimingActionTest.java
Sometimes it is good idea to **automate** the priming build. So far, the only way how to do it is to  `ProjectProblemsProvider`s and "somehow" detect a priming build is required. So I have defined `COMMAND_PRIME` Project action to be implemented by specific project types that require some sort of 'initialization' before they can be fully used. Currently they are `maven` and `gradle`. 
Maven support comes in the second commit. I tried to avoid multiple runs of the 'priming build', so if the build is run, an additional request will just piggyback on the execution. But once the execution completes, another ProblemResolver invocation will re-build the project.
In maven, I didn't want to pollute even more `ActionProviderImpl` that already has very complex dependencies. At the same time, I …
=> Priming build action support

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
When a file is renamed on disk by the client, and the client opens it in a new view, a `didClose` is fired on the old and `didOpen` on the new file's URI (location). But the LSP server failed to process properly the old file and return back empty diagnostics. So after renaming or deleting the file, the client still thinks there are problems/hints in the no-longer-existing filename.
I have changed the behaviour by tracking what files were reported the diagnostics to, and if the file vanishes, the LSP server will actively call `publishDiagnostics` with an empty list to clear the client. 
During the course, I have found many places where the code relied on that the file actually exists, but for example VSCode happily calls Code Lens service even for files that were deleted by GIT operation, …
=> Graceful handling of renamed/deleted files.

enterprise/web.jsf/src/org/netbeans/modules/web/jsf/wizards/ManagedBeanIterator.java
see https://issues.apache.org/jira/browse/NETBEANS-5090
=> [NETBEANS-5090] fix missing Serializable interface when a @ViewScoped  CDI bean is created via JSF CDI Bean Wizard

java/maven/test/unit/src/org/netbeans/modules/maven/problems/PrimingActionTest.java
I passed a failing test into master :( sorry, it succeeded on my local machine and I overlooked it among spurious error produced regularly by Travis. We should stabilize the testsuites somehow so they give **reliable** assesment of the PR ...
The culprit was the `dependency` in the project, which was satisfied on my local machine (from local M2 repo), but apparently is not at the build VM. For the test purposes, I only need project that is in a good shape, so project w/o any dependencies should do it.
=> Maven: Fixed failing test.

php/php.dbgp/src/org/netbeans/modules/php/dbgp/ConnectionErrMessage.java
https://issues.apache.org/jira/browse/NETBEANS-5438
Fixes an issue in which Netbeans copies an incorrect configuration for the PHP xdebug port, despite showing the correct configuration to the user.
The xdebug `remote_port` configuration was replaced by `client_port`, as described in [the upgrade guidelines](https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_port). Netbeans suggests the configuration correctly and allows the user to copy it to the clipboard:
However, when the user copies the values, the IDE copies the old value instead of the new one, as shown in the image below:
The current changes fix such behavior.
=> [NETBEANS-5438] Fix incorrect PHP xdebug3 port config when copying to clipboard

java/java.lsp.server/nbcode/integration/nbproject/project.xml, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/nbcode/integration/LspInputOutputProvider.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/nbcode/integration/LspProgressEnvironment.java, java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java, java/maven/src/org/netbeans/modules/maven/execute/CommandLineOutputHandler.java
When Maven repository transfer is cancelled from LSP client, the following exception may be printed to the log:
```
WARNING [org.eclipse.lsp4j.jsonrpc.RemoteEndpoint]: Notification threw an exception: {
"jsonrpc": "2.0",
"method": "window/workDoneProgress/cancel",
"params":
{ "token": "7c465cf8-43c0-4ef4-a7c9-fb0eb456a779" }
}
java.lang.UnsupportedOperationException
at org.eclipse.lsp4j.services.LanguageServer.cancelProgress(LanguageServer.java:96)
Caused: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at …
```
=> LSP progress cancel request may not work

java/maven/.gitignore, java/maven/manifest.mf, java/maven/src/org/netbeans/modules/maven/queries/MavenParentRootImpl.java, java/maven/test/unit/data/parent-projects/basic/child/pom.xml, java/maven/test/unit/data/parent-projects/basic/pom.xml, java/maven/test/unit/data/parent-projects/multi/first/child/pom.xml, java/maven/test/unit/data/parent-projects/multi/first/pom.xml, java/maven/test/unit/data/parent-projects/multi/pom.xml, java/maven/test/unit/data/parent-projects/multi/second/pom.xml, java/maven/test/unit/data/parent-projects/nested/first/child/pom.xml, java/maven/test/unit/data/parent-projects/nested/pom.xml, java/maven/test/unit/data/parent-projects/nested/second/pom.xml, java/maven/test/unit/data/parent-projects/single/pom.xml, java/maven/test/unit/data/parent-projects/skipped/first/child/pom.xml, java/maven/test/unit/data/parent-projects/skipped/first/pom.xml, java/maven/test/unit/data/parent-projects/skipped/pom.xml, java/maven/test/unit/data/parent-projects/skipped/second/pom.xml, java/maven/test/unit/data/parent-projects/unrelated/child/pom.xml, java/maven/test/unit/data/parent-projects/unrelated/pom.xml, java/maven/test/unit/src/org/netbeans/modules/maven/queries/MavenParentRootImplTest.java
Simple, but somewhat caching implementation of `ParentProjectProvider` and `RootProjectProvider` for maven projects. Works strictly by containment - does not uses `parent` inheritance relationship.
Let `q = p.parentProject`, `r = p.rootProject`. Then `p` will be built if either `r` or `p` is built.
=> [NETBEANS-5545] ParentProject and RootProject query support for Maven projects

php/php.phing/src/org/netbeans/modules/php/phing/exec/PhingExecutable.java
https://issues.apache.org/jira/browse/NETBEANS-5373
Removed parameter `-logger` because its value is incompatible with Phing 3.
=> [NETBEANS-5373] Fixed compatibility with Phing 3

profiler/lib.profiler/test/unit/src/org/netbeans/lib/profiler/heap/HeapSegmentTest.java, profiler/lib.profiler/test/unit/src/org/netbeans/lib/profiler/heap/HeapUtils.java, profiler/profiler.heapwalker/nbproject/project.xml, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/ClassesController.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/FieldsBrowserController.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/HeapFragmentWalker.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/InstancesController.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/InstancesListController.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/OverviewController.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/model/AbstractHeapWalkerNode.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/model/BrowserUtils.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/model/HeapWalkerNode.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/model/ObjectArrayNode.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/model/ObjectFieldNode.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/model/ObjectNode.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/model/PrimitiveArrayNode.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/ui/FieldsBrowserControllerUI.java, profiler/profiler.heapwalker/test/unit/src/org/netbeans/modules/profiler/heapwalk/model/HeapWalkerNodeTest.java
Recently I was working on generating `.hprof` files manually, without dumping the Java heap by the JVM. I have created a [builder library](https://www.graalvm.org/tools/javadoc/org/graalvm/tools/insight/heap/HeapDump.html) to provide nice Java API around the [Java Profiler Heap Dump Format](http://hg.openjdk.java.net/jdk6/jdk6/jdk/raw-file/tip/src/share/demo/jvmti/hprof/manual.html) and I am using it in the [GraalVM Insight](https://github.com/oracle/graal/blob/master/tools/docs/Insight-Manual.md#Heap-Dumping) to heap dump JavaScript, Ruby, Python and other dynamic languages.
When analyzing the generated heap dump with NetBeans 12.3 I noticed `<classLoader> = null` almost every where - see the [original snapshot](https://github.com/oracle/graal/blob/04e2a3c014c524e8de804365cd5c17a11676e68b …
=> Avoid displaying unnecessary `<classLoader>` field.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/LspServerState.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
Especially with gradle subproject, it happens that if the gradle project is not opened, diagnostics run on the project's sources report missing identifiers. The LSP server can internally automatically open project owner when the LSP client opens a file from that project.
This PR performs `asyncOpenSelectedProjects` using the file being opened. If the project is *being opened* (including priming build), the actual `OpenedProjects.open` call will be postponed until after that process completes.
For projects that whose open operation completed already, the Future in `beingOpened` is completed, so calling `asyncOpenSelectedProjects` on an opened project will also complete immediately.
I've changed the semantic of `beingOpened` to keep the completed Futures as a sign that a priming build is …
=> Auto-open project owner of the opened file.

java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/GradleSourcesImpl.java, java/gradle.java/src/org/netbeans/modules/gradle/java/nodes/SourcesNodeFactory.java
This change allows Gradle Source groups to display a source group from another project ownership. Previously an error node was created in this case, as having such entities in a project is generally a bad practice. With this change such source groups are coming with an error badge and some warning text.
I was thinking about putting this under an experimental feature flag, though I hope the number of such Gradle projects are really low.
=> [NETBEANS-5141] Support Gradle Source Groups from Alien Projects

ide/html.editor/src/org/netbeans/modules/html/editor/completion/AttrValuesCompletion.java
https://issues.apache.org/jira/browse/NETBEANS-4587
* Updated list of values for `method` attribute in forms.
* Added completion for `enctype` and `method` attributes of `<form>` element.
* Added completion of `target` attribute of `<a>`, `<button>`, `<form>` and `<input>` elements.
* Improved names of `FORM_ENCTYPE_SUPPORT` and `FORM_METHOD_SUPPORT`.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-method
For easier review I made two commits. The first one groups definitions for same element together and removes duplicates. The second one makes actual changes in completion.
=> [NETBEANS-4587] Code completion for HTML forms

java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/options/JavaDebuggerPanel.java
In "Tools" -> "Options" -> "Java" -> "Java Debugger", fix show "Visual Debugging" panel
=> Fix show 'Visual Debugging' options

java/java.lsp.server/nbcode/branding/modules/org-openide-text.jar/org/netbeans/modules/openide/text/Bundle.properties, java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBAttr.java, platform/openide.text/apichanges.xml, platform/openide.text/arch.xml, platform/openide.text/manifest.mf, platform/openide.text/src/org/netbeans/modules/openide/text/AskEditorQuestions.java, platform/openide.text/src/org/netbeans/modules/openide/text/Bundle.properties, platform/openide.text/src/org/openide/text/Bundle.properties, platform/openide.text/src/org/openide/text/CloneableEditorSupport.java, platform/openide.text/test/unit/src/org/netbeans/modules/openide/text/AskEditorQuestionsTest.java, platform/openide.text/test/unit/src/org/netbeans/modules/openide/text/Bundle_da.properties, platform/openide.text/test/unit/src/org/netbeans/modules/openide/text/Bundle_no.properties
- `Reload externally modified file` question should not appear in LSP clinet
- Lambdas correctly attributed in code completion when using nb-javac
=> LSP: Various stability issues with more complex project fixed.

ide/projectui/src/org/netbeans/modules/project/ui/Bundle.properties, ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectList.java, ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectListSettings.java, ide/projectui/src/org/netbeans/modules/project/ui/ProjectChooserAccessory.form, ide/projectui/src/org/netbeans/modules/project/ui/ProjectChooserAccessory.java, ide/projectui/src/org/netbeans/modules/project/ui/actions/NewProject.java, ide/projectui/src/org/netbeans/modules/project/ui/actions/OpenProject.java, ide/projectui/src/org/netbeans/modules/project/ui/groups/Group.java, ide/projectui/test/unit/src/org/netbeans/modules/project/ui/ProjectChooserAccessoryTest.java, java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteActionProvider.java, webcommon/web.clientproject/src/org/netbeans/modules/web/clientproject/ui/action/ClientSideProjectActionProvider.java
Sváťa exposed existing Maven concept of priming build as an action in #2795. Support for such action is making its way throughout other project types (#2816) and I believe it is time to use the new API to improve user experience in NetBeans IDE! Let's add a _trust and prime_ checkbox to the following dialog:
NetBeans pays quite a lot of attention to security of its users. NetBeans does its best to shield developers against attacks like [CVE-2020-11986](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11986). Clearly a user consent is needed to execute anything from the build. The IDE cannot execute random scripts when users are searching directories (via Favorites window) or opening random text files (via CLI or _File/Open_).
However users of other IDEs are surprised by questions …
=> Offer to trust and prime the project when it is being opened.

.travis.yml, ergonomics/ide.ergonomics/build.xml, ergonomics/ide.ergonomics/src-ant/org/netbeans/modules/ide/ergonomics/ant/ExtractLayer.java, extra/libs.javafx.linux/manifest.mf, extra/libs.javafx.macosx/manifest.mf, extra/libs.javafx.win/manifest.mf, java/editor.htmlui/nbproject/project.properties, java/form/src/org/netbeans/modules/form/resources/layer.xml, java/java.source.base/src/org/netbeans/modules/java/source/PostFlowAnalysis.java, nbbuild/templates/projectized.xml, platform/libs.javafx/manifest.mf, platform/o.n.bootstrap/src/org/netbeans/ModuleManager.java, platform/o.n.bootstrap/src/org/netbeans/Util.java
I am in a need to test `java.mx.projects` module on JDK15+ and I realized that our testing framework isn't really easy to use on JDK11+. As such I decided to return back to basics and fix at least commit validation. The first commit enables `ant commit-validation` on JDK15. Subsequent commits will fix the failures.
=> Execute commit validation on JDK15 and JDK11

extide/gradle/src/org/netbeans/modules/gradle/queries/ParentRootProviderImpl.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/queries/ParentRootProviderTest.java
During implementation of [NETBEANS-5430](https://issues.apache.org/jira/browse/NETBEANS-5430) I've noticed that ProjectUtils.parentOf() does not work navigate well from Gradle subprojects upwards. Fix attahed + testcases.
=> Fixed ProjectUtils.parentOf() for gradle subprojects.

php/php.editor/src/org/netbeans/modules/php/editor/actions/Bundle.properties, php/php.editor/src/org/netbeans/modules/php/editor/actions/FixDuplicateImportStmts.java, php/php.editor/src/org/netbeans/modules/php/editor/actions/FixUsesAction.java, php/php.editor/src/org/netbeans/modules/php/editor/actions/ImportDataCreator.java, php/php.editor/test/unit/data/testfiles/actions/testImportData/testImportData_01.php.importData, php/php.editor/test/unit/data/testfiles/actions/testImportData/testImportData_02.php.importData, php/php.editor/test/unit/data/testfiles/actions/testImportData/testImportData_03.php.importData, php/php.editor/test/unit/data/testfiles/actions/testImportData/testImportData_04.php.importData, php/php.editor/test/unit/data/testfiles/actions/testImportData/testImportData_05.php.importData, php/php.editor/test/unit/data/testfiles/actions/testImportData/testImportData_06.php.importData, php/php.editor/test/unit/data/testfiles/actions/testImportData/testImportData_07.php.importData, php/php.editor/test/unit/data/testfiles/actions/testImportData/testImportData_issue227304.php.importData, php/php.editor/test/unit/data/testfiles/actions/testImportData/testImportData_issue246537a.php.importData, php/php.editor/test/unit/data/testfiles/actions/testImportData/testImportData_issue246537b.php.importData
https://issues.apache.org/jira/browse/NETBEANS-5350
Added buttons "Change Nothing" and "Restore Defaults" to Fix Uses dialog.
This is useful when user just wants to remove unused `use` statements or wants to fix only a few imports and dialog contains large number of items.
Initial state  and state after "Restore Defaults":
State after "Change Nothing":
=> [NETBEANS-5350] Improved Fix Uses dialog

java/maven/src/org/netbeans/modules/maven/runjar/MavenExecuteUtils.java, java/maven/src/org/netbeans/modules/maven/runjar/RunJarStartupArgs.java
Looks like that after #2731 I cannot execute my [talk2compiler](https://github.com/jaroslavtulach/talk2compiler) project:
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "this.line" is null
at org.netbeans.modules.maven.runjar.PropertySplitter.nextPair(PropertySplitter.java:65)
at org.netbeans.modules.maven.runjar.MavenExecuteUtils.splitJVMParams(MavenExecuteUtils.java:642)
at org.netbeans.modules.maven.runjar.MavenExecuteUtils.splitAll(MavenExecuteUtils.java:618)
at org.netbeans.modules.maven.runjar.RunJarStartupArgs.checkRunConfig(RunJarStartupArgs.java:130)
at org.netbeans.modules.maven.execute.MavenCommandLineExecutor.run(MavenCommandLineExecutor.java:238)
at org.netbeans.core.execution.RunClassThread.doRun(RunClassThread.java:132)
at …
```
=> Avoid NPE when executing some Maven projects.

extide/gradle/src/org/netbeans/modules/gradle/GradleProjectCache.java
This one is an additional fix for NETBEANS-5484. The root cause of NETBEANS-5484 is that NetBeans evaluates a directory as non-project, since the applied heuristics can't tell otherwise. However after NB turned to Gradle for the exact project information, Gradle updates it's sub project information.
So after all of these when the user clicks on the Sub projects node. Upon the full information in the Gradle Project NB can ask for a project on a directory which previously identified as non-project so returning null instead of evaluating that directory again.
This simple fix clears the NB non-project cache when more information is available from Gradle, so the re-evaluation would happen and identify the directory as a project.
=> [NETBEANS-5484] Clear NB Non-Project cache when we have more info from Gradle

platform/o.n.swing.tabcontrol/nbproject/project.properties, platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/ButtonPopupSwitcher.java
Fixes a problem I've run into several times on Mac OS - if another application steals focus
while the popup switcher is open, the switcher can wind up in a state where it is listening
twice, and is hidden as soon as you release the mouse button.
Fix is to add AWTEvent.WINDOW_EVENT_MASK to the set of AWTEvents listened for, check that
there really is no active window (to avoid confusion around heavyweight AWT popups) and
hide the popup in that case.
=> Popup tab switcher should hide when another application steals focus

platform/openide.loaders/src/org/openide/loaders/TemplateWizardIterImpl.java
As far as I can tell there is no way to disable a Previous button in the wizard because TemplateWizardIterImpl does not delegate the call to the wrapped iterator.
I think the current one-liner fixes that.
While searching I also found a thread talking about this from 2015 http://netbeans-org.1045718.n5.nabble.com/Re-how-to-disable-previous-button-in-one-of-wizards-td5741265.html where Graeme found the same fix.
draganknin had this closing statement there:
>I hope so that this will be fixed soon. Until it does I will stick with reflection. 
6 short years later I think this PR fixes it.
Most of the code seems to have been written by @JaroslavTulach, which is why I added him as a reviewer. I wouldn't have bothered him directly otherwise (and I do apologize if it's too much noise).
=> Delegates from TemplateWizardIterImpl.hasPrevious

java/java.source.base/src/org/netbeans/api/java/source/GeneratorUtilities.java, java/java.source.base/src/org/netbeans/modules/java/source/GeneratorUtilitiesAccessor.java, java/java.source.base/src/org/netbeans/modules/java/source/transform/ImmutableTreeTranslator.java, java/java.source.base/test/unit/src/org/netbeans/api/java/source/gen/ImportAnalysis2Test.java
This should fix the failing re-writes of import in the backporting nb-javac. Basically, without this patch, manual changes to import statements are thrown away when import analysis is adding any imports.
=> Fixing codegen handling of both rewrite of an import and an adding of an import due to qual ident.

java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Update link to javadoc 16 now that is in general availability
Before:
https://download.java.net/java/early_access/jdk16/docs/api/
After:
https://docs.oracle.com/en/java/javase/16/docs/api/
=> [NETBEANS-5490] - General Availability for javadoc 16

ergonomics/ide.ergonomics/src-ant/org/netbeans/modules/ide/ergonomics/ant/ExtractLayer.java
Master has failed to compile for me. It turned out that ant **1.10.1** I have been using does not support methods `stream()` and `isEmpty()` in that interface. ant **1.10.8** NetBeans itself is distributing is OK. But just removing the `@Override` may fix the build and allow earlier versions to be used.
Setting to WIP as the entire `commit-validation` failed for me once, but I wasn't able to verify whether it is some local problem or systematic problem with the method (i.e. isEmpty) actually not being called. Let's see what the CI says.
=> Fixing build for older ant versions.

java/java.mx.project/nbproject/project.xml, java/java.mx.project/src/org/netbeans/modules/java/mx/project/Compliance.java, java/java.mx.project/src/org/netbeans/modules/java/mx/project/suitepy/Parse.java, java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/ComplianceTest.java, java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/ParseSuitesTest.java, java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/SdkSuiteTest.java, java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/SuiteCheck.java, java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/TrufleSuiteTest.java
`java.mx.projects` module is using JavaScript engine to parse the `suite.py` files (after transforming them to JSON format). This is no longer working on JDKs that don't carry JavaScript implementation - e.g. JDK15+.
This PR replaces usage of JavaScript with existing NetBeans parsing library `json_simple`.
=> Use JSON parser to understand java.mx.projects.

ide/projectui/src/org/netbeans/modules/project/ui/OpenProjectList.java, ide/projectui/src/org/netbeans/modules/project/ui/ProjectChooserAccessory.java
I changed the Accessory panel so that it enables the checkbox when there's NO action provider at all. In reality that does not happen with well-behaved projects, as they have at least Build or Run actions. But Ergonomics-proxies have no actions on them (at least they appeared so).
Later, during open, the `getSupportedActions()` check is done again, to see whether the project really supports the action. Seemed to be working fine for PHP (and Maven, Ant, Gradle) on my clean setup.
=> [NETBEANS-5524] Check for priming action before use.

java/java.lsp.server/nbcode/branding/modules/org-netbeans-modules-maven-indexer.jar/org/netbeans/modules/maven/indexer/api/Bundle.properties, java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteActionProvider.java, java/maven.indexer/manifest.mf, java/maven.indexer/src/org/netbeans/modules/maven/indexer/api/RepositoryPreferences.java, java/maven.indexer/test/unit/src/org/netbeans/modules/maven/indexer/api/Bundle_te_ST.properties, java/maven.indexer/test/unit/src/org/netbeans/modules/maven/indexer/api/RepositoryPreferencesTest.java, java/maven/apichanges.xml, java/maven/arch.xml, java/maven/manifest.mf, java/maven/nbproject/project.xml, java/maven/src/org/netbeans/modules/maven/ProjectOpenedHookImpl.java
Users of VSNetBeans complain about the Maven index download (some users of NetBeans IDE, like me, complain as well) and the fact that there is no UI to disable it. To address their complains right now, before some final solution[1] is implemented, I propose to introduce branding API and use it in the `nbcode` suite to disable the download in VSNetBeans.
[1] Ideally I'd like the queries to Maven to be handled online by sending a query to https://search.maven.org/#search|ga|1|guice & co.
=> Branding API to disable Maven index download

harness/apisupport.harness/macosx-launcher-src/Sources/AppLauncher/main.swift, harness/apisupport.harness/release/launchers/app.sh, nb/ide.launcher/macosx/Sources/NetBeansLauncher/main.swift
Update macOS Native Launchers to call the unix launcher shell scripts instead of duplicating the logic in the scripts.
As @neilcsmith-net pointed out in https://github.com/apache/netbeans/pull/2563#issuecomment-765627457 this will avoid having to update the logic in yet another place as we do with the Windows Launcher.
=> [NETBEANS-5004] Update macOS native launchers to call launcher shell script rather than nbexec

java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionCollector.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchRequestHandler.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/TestProgressHandler.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/progress/TestProgressHandlerTest.java, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/protocol.ts, java/java.lsp.server/vscode/src/testAdapter.ts, platform/api.progress/src/org/netbeans/modules/progress/spi/Controller.java, platform/api.progress/src/org/netbeans/modules/progress/spi/ProgressEvent.java
A set of essential fixes for 12.4 Beta:
- Test Explorer support should show standard output in debug console
- Test Explorer support for multi projects
- Test Explorer should prevent duplicate classes in UI
- Test Explorer should support for junit ParameterizedTests
- Failing ServerTest fixed
- Fixed deadlock in Java code completion over LSP
- Fixed run single method over LSP
=> LSP: Test Explorer essential fixes

nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ConfigureProxy.java
This is an improvement on the NetBeans build system, specifically the task which downloads binary prerequisites from Central Maven or https://netbeans.osuosl.org/binaries.
As per the explanation in [NETBEANS-5478](https://issues.apache.org/jira/browse/NETBEANS-5478) a hard-coded connect timeout of 5 seconds will not work in some build environments because of the "network first touch penalty" (I'm looking at you GitHub Actions (= Azure)). This PR makes the connect timeout configurable so that it will be possible to do:
`ant -DdownloadBinaries.connectTimeoutMs=30000 ....`
(which will set the connect timeout to 30 seconds)
Current behavior is not changed, i.e the default is 5000 mseconds ... which I personally find low'ish, but admittedly has worked well for most users over the years. It …
=> [NETBEANS-5478]: DownloadBinaries task: 5 secs connect time is not enough

profiler/lib.profiler/build.xml, profiler/lib.profiler/external/binaries-list, profiler/lib.profiler/external/profiler-external-binaries-ASF.txt
Use ASF-created binaries for Windows X86, Windows X64, MacOS X64, Linux X86 and Linux X64. The ASF-binaries includes the fix for [NETBEANS-1428](https://issues.apache.org/jira/browse/NETBEANS-1428). For the rest of the platforms that were supported in the past (for example HP-UX, Solaris, Linux ARM) we keep these binaries in the distribution but they are no longer receiving bug fixes and they therefore _don't_ have the fix [NETBEANS-1428](https://issues.apache.org/jira/browse/NETBEANS-1428).
This PR continues (for now) to use the "external binaries" mechanism even if this mechanism was never intended for binaries originating from Apache NetBeans itself (duh!, they are not 'external'). In this light I probably didn't need to create the file `external/profiler-external-binaries-ASF.txt` but …
=> Profiler lib native binaries: use ASF binaries with fix for NETBEANS-1428

enterprise/j2ee.core/src/org/netbeans/api/j2ee/core/Profile.java, enterprise/payara.eecommon/nbproject/org-netbeans-modules-payara-eecommon.sig, enterprise/payara.eecommon/src/org/netbeans/modules/payara/eecommon/api/config/J2EEVersion.java, enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/config/PayaraV5.xml
This PR adds the Jakarta EE 8 profile support to Server config.
- J2EE 1.3 - Profile version 1.3 & J2EEVersion 1.3
- J2EE 1.4 - Profile version 1.4 & J2EEVersion 1.4
- Java EE 5 - Profile version 1.5 & J2EEVersion 5.0
- Java EE 6 - Profile version 1.6 & J2EEVersion 6.0
- Java EE 7 - Profile version 1.7 & J2EEVersion 7.0
- Java EE 8 - Profile version 1.8 & J2EEVersion 8.0
- Jakarta EE 8 - Profile version 8.0 & J2EEVersion 8.0.0 **(added by this PR)**
=> NETBEANS-5313 Payara Server not listed in the registered application servers list for Jakarta EE 8 profile

extide/gradle/src/org/netbeans/modules/gradle/options/GradleExperimentalSettings.java
This does not solve loading issues reported in [NETBEANS-5540](https://issues.apache.org/jira/browse/NETBEANS-5540), but disables the newer code for 12.4, while retaining the possibility to test it.
=> [NETBEANS-5540] Workaround for 12.4 beta: disable lazy-load by default.

java/java.mx.project/nbproject/project.xml, java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteSources.java, java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/editor/JavaToCHyperlinkProvider.java, platform/masterfs/nbproject/project.xml, platform/masterfs/src/org/netbeans/modules/masterfs/filebasedfs/FileBasedFileSystem.java, platform/masterfs/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/BaseFileObj.java, platform/masterfs/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/FileObjectFactory.java, platform/masterfs/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/FileObjectKeeper.java, platform/masterfs/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/FolderObj.java, platform/masterfs/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/ReplaceForSerialization.java, platform/masterfs/test/unit/src/org/netbeans/modules/masterfs/filebasedfs/BaseFileObjectTestHid.java, platform/masterfs/test/unit/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/WatcherDeadlockTest.java, platform/openide.filesystems/apichanges.xml, platform/openide.filesystems/manifest.mf, platform/openide.filesystems/src/org/openide/filesystems/AbstractFileObject.java, platform/openide.filesystems/src/org/openide/filesystems/AbstractFolder.java, platform/openide.filesystems/src/org/openide/filesystems/FileObject.java, platform/openide.filesystems/src/org/openide/filesystems/MultiFileObject.java, platform/openide.filesystems/src/org/openide/filesystems/VirtualFileObject.java, platform/openide.filesystems/test/unit/src/org/openide/filesystems/FileObjectTestHid.java
@dougxc is working on changes in `mx` and they interfere with the way `java.mx.projects` deal with references to libraries. While debugging I realized that, ideally, one could clone [graal repository](https://github.com/oracle/graal) and open `truffle` suite without `mx build` - e.g. compiling anything. The IDE should handle that.
Well, it should, but it doesn't - if the JAR in `mxbuild` directory isn't present - no URL, but rather `null` was returned as its location. Then it was impossible to locate sources that produce that JAR. Commit 3387fc6 changes that - it returns (generic) JAR location even if it doesn't exist.
The change is based on long time needed, but never really implemented API change that now allows to create `FileObject` instances for files that don't exist: a19c3e3 - say …
=> Return FileObject for non-existing JARs.

extide/gradle/netbeans-gradle-tooling/src/main/groovy/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.groovy, extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java
This patch allows the IDE to read projects that require Gradle 7.0.
I've created another PR #2861, that would bump the tooling version used in NetBeans to 7.0 (actually it is 7.0-rc-2), though not sure if that could fit for 12.4, that is needed for the IDE to be run on JDK 16 and have the Gradle integration work.
This one is safe for 12.4
=> [NETBEANS-5522] Minimal support for Gradle 7.0

extide/gradle/nbproject/project.xml, extide/libs.gradle/external/binaries-list, extide/libs.gradle/external/gradle-tooling-api-7.0-license.txt, extide/libs.gradle/external/gradle-tooling-api-7.0-notice.txt, extide/libs.gradle/manifest.mf, extide/libs.gradle/nbproject/project.properties, extide/libs.gradle/nbproject/project.xml, java/gradle.java/apichanges.xml, java/gradle.java/manifest.mf, java/gradle.java/src/org/netbeans/modules/gradle/java/api/GradleJavaSourceSet.java, java/gradle.test/nbproject/project.xml
Well, let's prepare for this. As it happened before the Gradle and NetBeans release come really close again.
This upgrade is required, if someone would like to use NetBeans on Java 16, even if the target project is using an older JDK.
=> [NETBEANS-5541] Upgrade Gradle Tooling to 7.0

webcommon/javascript2.json/tools/Json.g4
The "json.g4" antlr grammar generates files with wrong licenses.
=> json.g4 wrong licenses

php/php.editor/src/org/netbeans/modules/php/editor/elements/BaseFunctionElementSupport.java, php/php.editor/test/unit/data/testfiles/codegen/testNetbeans5370/testNetbeans5370.php, php/php.editor/test/unit/data/testfiles/codegen/testNetbeans5370/testNetbeans5370.php.testNetbeans5370_01.codegen, php/php.editor/test/unit/data/testfiles/codegen/testNetbeans5370/testNetbeans5370.php.testNetbeans5370_02.codegen, php/php.editor/test/unit/data/testfiles/completion/lib/nb5370/testAbstract.php, php/php.editor/test/unit/data/testfiles/completion/lib/nb5370/testAbstract.php.testAbstract.cccustomtpl, php/php.editor/test/unit/data/testfiles/completion/lib/nb5370/testInterface.php, php/php.editor/test/unit/data/testfiles/completion/lib/nb5370/testInterface.php.testInterface.cccustomtpl, php/php.editor/test/unit/data/testfiles/verification/ImplementAbstractMethodsHintError/testNetbeans5370.php, php/php.editor/test/unit/data/testfiles/verification/ImplementAbstractMethodsHintError/testNetbeans5370.php.testNetbeans5370.hints, php/php.editor/test/unit/data/testfiles/verification/ImplementAbstractMethodsHintError/testNetbeans5370.php.testNetbeans5370Fix_01.fixed, php/php.editor/test/unit/data/testfiles/verification/ImplementAbstractMethodsHintError/testNetbeans5370.php.testNetbeans5370Fix_02.fixed, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/codegen/SelectedPropertyMethodsCreatorTest.java, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionNb5370Test.java, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/verification/ImplementAbstractMethodsHintErrorTest.java
https://issues.apache.org/jira/browse/NETBEANS-5370
```php
<?php
namespace Netbeans5370;
abstract class TestAbstractClass
{
/**
* @return string[]
*/
abstract public function testAbstract(): array;
}
// before
class TestClass1 extends TestAbstractClass {
public function test(): string[] {
}
}
// after
class TestClass1 extends TestAbstractClass {
public function test(): array {
}
}
```
=> [NETBEANS-5370] Prevent generating abstract methods with PHPDoc return array type

platform/o.n.core/src/org/netbeans/core/NotifyExcPanel.java, platform/o.n.core/test/unit/src/org/netbeans/core/NotifyExceptionTest.java
By default errors are displayed by blinking icon in bottom right corner in the production builds. Development builds (those with `-ea`) however display dialogs. That can be pretty annoying, especially when there is a lot of subsequent errors. I suggest to use the same mode as in production builds - e.g. to comment out the `assert use = true` check.
=> Always display errors as an icon in bottom right corner

platform/libs.flatlaf/external/binaries-list, platform/libs.flatlaf/external/flatlaf-1.1.2-license.txt, platform/libs.flatlaf/nbproject/project.properties, platform/libs.flatlaf/nbproject/project.xml, platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/Bundle.properties, platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties, platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java, platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties, platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafOptionsPanel.form, platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafOptionsPanel.java, platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafOptionsPanelController.java, platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafPrefs.java, platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties, platform/options.api/src/org/netbeans/modules/options/OptionsPanel.java
This is a follow up to #2839, which unfortunately causes some problems in open editors when changing "Unified title bar" flag in FlatLaf Options: the line numbers ruler was hidden and sometimes I had the impression that some editing features no longer work. The problem was that `FlatLaf.updateUI()` was used to update all UI delegates. This PR no longer does this.
Changes:
- update from 1.1.1 to 1.1.2
- Options: option "Unified window title bar" is now enabled by default because this looks much better, especially in dark theme
- Options: disabling option "Window decorations" now works without restart
- Options: changing option "Unified window title bar" now works without `FlatLaf.updateUI()`, which fixes lost line numbers in editors
- Options: if option "Unified window title bar" is …
=> FlatLaf: update from 1.1.1 to 1.1.2 and fix/improve options

java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/idebinding/HintsTaskTest.java, java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Hacks.java
This fixes a problem where (without nb-javac), placing this into a `.hint` file:
```
$1.length() :: $1 instanceof java.lang.String;;
```
Will produce an error on $1.
=> Fix parsing of constraints if the current parser does not have source files.

java/java.source.base/src/org/netbeans/api/java/source/TreeUtilities.java, java/java.source.base/src/org/netbeans/modules/java/source/parsing/FindAnonymousVisitor.java, java/java.source.base/test/unit/src/org/netbeans/api/java/source/TreeUtilitiesTest.java, java/java.source.nbjavac/src/org/netbeans/modules/java/source/nbjavac/parsing/FindAnonymousVisitor.java, java/java.source.nbjavac/src/org/netbeans/modules/java/source/nbjavac/parsing/PartialReparserImpl.java, java/java.source.nbjavac/src/org/netbeans/modules/java/source/nbjavac/parsing/PartialReparserService.java, java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBEnter.java, java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBJavacTrees.java, java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBParserFactory.java, java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBTreeMaker.java
Please see:
https://issues.apache.org/jira/browse/NETBEANS-5322
for the problem description
The issue is that when Trees.getScope() is called, for vanilla javac, it will assign new anonymous innerclass names to any anonymous innerclasses it encounters, and then drops them to revert back to the original state. But, with nb-javac, we use IndexedClassDecl to keep the anonymous innerclass names stable, and hence the real anonymous innerclasses are dropped at the end of getScope().
On one hand, this could be solved in nb-javac, but I believe we want (or must) avoid the tricks with IndexedClassDecl. These were done mostly for debugger, which needs to know the binary names of classes at least to set breakpoints at correct places. getScope() has been improved significantly and I hope it is good …
=> [NETBEANS-5322] Removing IndexedClassDecl.

java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/SourceLevelQueryImpl.java, java/java.openjdk.project/test/unit/src/org/netbeans/modules/java/openjdk/project/SourceLevelQueryImplTest.java
The OpenJDK projects need to look at one more place when detecting source level.
=> Fixing source level detection for OpenJDK projects in 'open' directory.

enterprise/web.jsf/src/org/netbeans/modules/web/jsf/facelets/resources/templates/compositionTemplateClient.template
see https://issues.apache.org/jira/browse/NETBEANS-5114
=> [NETBEANS-5114] add missing namespace for facelets composition template client

platform/core.netigso/test/unit/src/org/netbeans/core/netigso/EnabledAutoloadTest.java, platform/core.osgi/nbproject/project.properties, platform/libs.felix/external/binaries-list, platform/libs.felix/external/org.apache.felix.main-7.0.0-license.txt, platform/libs.felix/external/org.apache.felix.main-7.0.0-notice.txt, platform/libs.felix/nbproject/project.properties, platform/libs.felix/nbproject/project.xml, platform/libs.osgi/external/binaries-list, platform/libs.osgi/external/osgi-8.0-license.txt, platform/libs.osgi/nbproject/project.properties, platform/libs.osgi/nbproject/project.xml
I have tried Felix 7.0.0 with a minimal application and it seems that URL handling is fixed.
=> [NETBEANS-5499] Upgrade Felix library, works on JDK16.

dlight/mercurial.remote/src/org/netbeans/modules/mercurial/remote/ui/update/ResolveConflictsExecutor.java, dlight/subversion.remote/src/org/netbeans/modules/subversion/remote/ui/update/ResolveConflictsExecutor.java
Reusing/adapting ResolveConflictsExecutor.java from ide/subversion and ide/mercurial into dlight/subversion.remote and dlight/mercurial.remote, respectively. 
With this PR dlight/subversion.remote and dlight/mercurial.remote seem to compile and test properly, but we may need to review how well they work once CND runs in the IDE.
=> [NETBEANS-4663][CND] ResolveConflictExecutor in mercurial/subversion remote

cnd/cnd.utils/src/org/netbeans/modules/cnd/utils/resources/mime-resolver-hex-based.xml
Adding a mime-resolver-hex-based.xml replacement to the cnd.utils module, that was missing from the 4th Oracle donation.
=> [NETBEANS-5557] [CND] mime-resolver-hex-based.xml

extide/o.apache.tools.ant.module/nbproject/project.xml, extide/o.apache.tools.ant.module/src/org/apache/tools/ant/module/run/TargetExecutor.java, ide/csl.api/nbproject/project.xml, ide/csl.api/src/org/netbeans/modules/csl/api/UiUtils.java, ide/csl.api/src/org/netbeans/modules/csl/editor/hyperlink/GoToSupport.java, ide/csl.api/src/org/netbeans/modules/csl/hints/infrastructure/HintsPanelLogic.java, java/debugger.jpda.ui/nbproject/project.xml, java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/ConnectPanel.java, platform/api.search/nbproject/project.xml, platform/api.search/src/org/netbeans/modules/search/GraphicalSearchListener.java, platform/api.search/src/org/netbeans/modules/search/ReplaceTask.java, platform/autoupdate.cli/nbproject/project.xml, platform/core.ui/nbproject/project.xml, platform/core.ui/src/org/netbeans/core/ui/warmup/MenuWarmUpTask.java
When I was prototyping for LSP, I stumbled upon some uses of Progress API that were unnecessarily tied to Swing. So replacing usage of `api.progress.nb` calls with equivalent `api.progress` + reducing dependencies between modules.
=> Reducing dependencies on Swing API when basic API exists.

extide/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java, extide/gradle/src/org/netbeans/modules/gradle/GradleProjectLoader.java, extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java, extide/gradle/src/org/netbeans/modules/gradle/ReloadAction.java, extide/gradle/src/org/netbeans/modules/gradle/action-mapping.xml, extide/gradle/src/org/netbeans/modules/gradle/api/GradleProjects.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/AbstractProjectLoader.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleProjectLoaderImpl.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java, extide/gradle/src/org/netbeans/modules/gradle/spi/newproject/TemplateOperation.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/AbstractGradleProjectTestCase.java, java/api.java/apichanges.xml, java/api.java/manifest.mf, java/api.java/nbproject/project.xml, java/api.java/src/org/netbeans/api/java/queries/SourceJavadocAttacher.java, java/api.java/src/org/netbeans/spi/java/queries/SourceJavadocAttacherImplementation.java, java/api.java/test/unit/src/org/netbeans/api/java/queries/SourceJavadocAttacherTest.java, java/gradle.java/nbproject/project.xml, java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceAttacherImpl.java, java/java.j2seplatform/nbproject/project.xml, java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/queries/DefaultSourceJavadocAttacher.java, java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/queries/QueriesCache.java, java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/queries/SelectRootsPanel.java, java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/queries/SourceJavadocAttacherUtil.java, java/java.j2seplatform/test/unit/src/org/netbeans/modules/java/j2seplatform/queries/DefaultSourceJavadocAttacherTest.java, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/LspRunOffEdtProvider.java
This is a follow-up to #2499 - the support developed for downloading javadoc/source is extended to:
- a project action
- a `SourceJavadocAttacherImplementation.Definer` plugin
This allows the user to click "Download" in the NetBeans IDE - and ask Gradle to download sources for the user. After (successful) download, the source re-opens instead of .class file. Since the source is downloaded to Gradle-managed area, from that point on its `SourceForBinaryQueryImplementation` should return the newly acquired source automatically.
During the course, I've made some little improvements:
- `SourceJavadocAttacher` now calls subsequent SPI implementations in the case a former fails to process the resource (the `AttachmentListener` reports a failure). This allows to bail out in case of some network …
=> NETBEANS-5590] Support for assisted download of sources/javadocs for dependencies

platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java, platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties, platform/spi.quicksearch/src/org/netbeans/modules/quicksearch/QuickSearchComboBar.java
This PR fixes/improves styling of quicksearch field in menubar and vertically centers text component when menubar is embedded into window title bar.
Before:
After:
Before:
After:
If menubar is **not embedded** into window title bar, it looks the same as before:
Also fixes vertical centering of quicksearch text in Windows L&F (before/after):
=> FlatLaf: fix/improve styling of quicksearch field in menubar

platform/keyring.impl/src/org/netbeans/modules/keyring/gnome/libsecret/Gio.java, platform/keyring.impl/src/org/netbeans/modules/keyring/gnome/libsecret/Glib.java, platform/keyring.impl/src/org/netbeans/modules/keyring/gnome/libsecret/GnomeLibSecretProvider.java, platform/keyring.impl/src/org/netbeans/modules/keyring/gnome/libsecret/LibSecret.java, platform/keyring.impl/test/unit/src/org/netbeans/modules/keyring/gnome/libsecret/GnomeLibSecretProviderTest.java
Thank you @matthiasblaesing for the libsecret bindings: https://github.com/matthiasblaesing/JNA-Demos/tree/master/LibSecret
I just put it together into GnomeLibSecretProvider.java
Gio.java, Glib.java & Libsecret.java are without a change from your github except I changed the license header with the one from other netbeans files. Is that correct? Or should it have the one you used?
The unit test is passing, I tested saving DB password and proxy password into it from the IDE. Below are some screenshots from how the saved passwords look like in seahorse app in gnome. The gibberish in the last one is part of the test data from the unit test. 
I also tested renaming libsecret in my system temporarily and the IDE used the Fallback KeyringProvider then (like before this change).
=> NETBEANS-4150 added a KeyringProvider using libsecret for new versions of Gnome

ide/css.prep/src/org/netbeans/modules/css/prep/layer.xml, ide/gsf.testrunner/src/org/netbeans/modules/gsf/testrunner/layer.xml, ide/gsf.testrunner/src/org/netbeans/modules/gsf/testrunner/resources/description.html, ide/ide.kit/nbproject/project.properties, ide/ide.kit/test/qa-functional/src/org/netbeans/modules/ide/kit/VerifySimpleTemplatesTest.java, ide/projectuiapi/arch.xml, ide/projectuiapi/src/org/netbeans/spi/project/ui/templates/support/package.html, ide/xml/src/org/netbeans/modules/xml/resources/templates/emptyXML.xml.template, java/java.lsp.server/nbcode/nbproject/platform.properties, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/LspTemplateUI.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts, java/java.project.ui/src/org/netbeans/modules/java/project/ui/resources/Classes.html, java/java.source/src/org/netbeans/modules/java/JavaDataObject.java, java/java.source/src/org/netbeans/modules/java/source/resources/OverriddenMethodBody.template, java/junit.ui/src/org/netbeans/modules/junit/ui/resources/JUnit3Suite.java.template, java/junit.ui/src/org/netbeans/modules/junit/ui/resources/JUnit4Suite.java.template, java/junit.ui/src/org/netbeans/modules/junit/ui/resources/JUnit5Suite.java.template, java/spring.beans/src/org/netbeans/modules/spring/beans/resources/templates/springXMLConfig.template, java/testng.ui/src/org/netbeans/modules/testng/ui/resources/TestNGSuite.xml.template, javafx/javafx2.project/src/org/netbeans/modules/javafx2/project/templates/FXML_java_1.template, platform/templates/src/org/netbeans/modules/templates/resources/layer.xml, platform/templates/src/org/netbeans/modules/templates/resources/templatesOther.html, webcommon/web.clientproject/src/org/netbeans/modules/web/clientproject/resources/clientside-description.html, webcommon/web.clientproject/src/org/netbeans/modules/web/clientproject/resources/layer.xml
Exposes `DataObject.createFromTemplate` for _simple_ templates from `Templates` folder to VSCode users in a simple few step UI. CCing @Ondrej-Douda, @jisedlac
Select the _New from Template..._ item and:
* select the group - e.g. __Java__, __JUnit__, __HTML__, __Other__
* select the actual template
* if the action was invoked from palette (_Ctrl-Shift-P_) specify location
* specify name for the new object/file
At the end new file opens in the editor. Testing extension is available at its [jenkins builder](https://ci-builds.apache.org/job/Netbeans/job/netbeans-vscode-new-from-template/) and is updated with every change to this PR.
=> New from Template for VSCode.

extide/gradle/src/org/netbeans/modules/gradle/GradleModuleFileCache21.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/GradleModuleFileCache21Test.java
I have changed the `gavsplit`, since versions provided in the artifact ID contain 4th component, the `{timestamp}-{sequenceno}` for Mavenrepo SNAPSHOT artifacts.
I changed the code to search from the start, as the 'official' syntax for artifact ID is `group`:`artifact`:`version`[:`classifier`][@`ext`] ... so looking for 3rd `:` delimiter seems to satisfy both this and `group`:`artifact`:`version`:`timestamp`-`sequence` which comes to `gavSplit` for Maven SNAPSHOTs.
=> [NETBEANS-5587] Support SNAPSHOT versions of dependencies.

platform/masterfs/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/BaseFileObj.java, platform/masterfs/test/unit/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/FolderObjTest.java, platform/openide.filesystems/src/org/openide/filesystems/FileObject.java, platform/openide.filesystems/test/unit/src/org/openide/filesystems/FileObjectTestHid.java
Jan discovered a surprising misbehavior in masterfs related to invalid child and its parents in e450db5. This PR expands the filesystem TCK and fixes masterfs implementation. Jan also suggested that:
```java
assert !ch.isValid()) : "Let's assume file object is not valid";
try (OutputStream os = ch.getOutputStream()) {
os.write("Ahoj".getBytes("UTF-8"));
}
```
should work. True one can use the [javax.tools.FileObject](https://docs.oracle.com/javase/8/docs/api/javax/tools/FileObject.html) this way. As the `FileObject.getOutputStream()` method is `final`, it was easy to implement such behavior across all the `FileSystem` implementations.
=> More consistency for virtual file objects

java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java, java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/CompileWorkerTestBase.java, java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorkerTest.java
While doing background scan, and compiling classfiles for CoS without nb-javac, warnings should not be considered to be errors, and should not cause error repair code to be triggered.
=> javac warnings should not cause background indexing to Repair the code.

java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteActionProvider.java, java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/SdkSuiteTest.java, java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/SuiteActionProviderTest.java
A [mistake has been made](https://github.com/apache/netbeans/pull/2822/files#r619574208) when implementing #2822 - now build/rebuild actions are disabled for _mx projects_. This PR fixes that by returning `true` for all supported actions and `false` only otherwise.
When at it I also fixed long opened problem - to run/debug unit test one had to build first, otherwise the changes were not visible - now the build happens before running tests automatically. With 8c3b56d the VSNetBeans UI also knows when run/debug test action is over and can hide the debugging toolbar.
This is not a stopper for 12.4 (who cares about mx projects anyway?), but please consider this PR for inclusion in 12.4, if there is a chance.
=> Build & Rebuild actions are disabled in mx projects!

cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPLiteActionsProvider.java, cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPLiteDebugger.java, cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/ni/NIDebuggerProviderImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ConnectionSpec.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/LspArgsProcessor.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/LspSession.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/DebugAdapterContext.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/Debugger.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbLspServer.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/ConnectionSpecTest.java, java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/api/NIDebugRunner.java
It's unfortunate, that GDB bug https://sourceware.org/bugzilla/show_bug.cgi?id=26139 is affecting the newly introduced native image debugging. We need to warn users about that, since native image debugging is practically unusable with the buggy version. A change needs to be done in LSP as well, to be able to show the warning in VSCode.
I'm providing two commits.
1) Introducing `LspSession`, which provides LSP and DAP servers. The getters provide the servers while they are running, they are cleared when they finish. This is handled by `ConnectionSpec`, the launch of the servers was changed to return after the server is launched and the `ConnectionSpec` is waiting for the server finish explicitly, to be able to manage the servers in the `LspSession` instance.
2) We check the version of …
=> LspSession associates LSP and DAP servers, and check of gdb version.

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleAccess.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/source/SourceFilesCache.java
When there's a Java breakpoint in some parts of the Graal's guest language implementation code, it collides with the guest script debugging handled by Truffle API. That leads to deadlock - it's not possible to continue from such breakpoint.
This PR resolves the deadlock by notification about method invocation, and assuring that `skipSuspendedEventClearLeakingReferences` is sensitive to its method breakpoint only.
=> Prevent from breakpoint collision in TruffleAccess.

ide/projectui/src/org/netbeans/modules/project/ui/SimpleTargetChooserPanelGUI.java
Well I get a nasty NPE when try to create a folder out of a project. This might be triggered by another bug in the system as it is unlikely to have a sourcegroup without a project though in the context of the ```SimpleTargetChooserPanelGUI``` class having the project field as ```null``` is indeed allowed. 
This is a trivial fix to prevent an NPE when that happen.
Unfortunately I do not know how to reliably reproduce this event. On one of my IDE instances it happens all the time, the other instance it does not.
=> [NETBEANS-5640] Fixing potential NPE on out of project Folder creation

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleAccess.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/TruffleVariable.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/impl/TruffleScope.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/impl/TruffleStackVariable.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/models/TruffleVariablesNodeModel.java, java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/JPDATruffleAccessor.java
This is fixing duplicated `this` - the frame's receiver object.
Adapting to the recent changes in Truffle debugger. Removing the deprecated `getArguments()` and providing all scopes with appropriate receiver and variable information.
=> Provide all Truffle scopes with correct receiver information.

java/gradle.java/src/org/netbeans/modules/gradle/java/GradleJavaTokenProvider.java, java/gradle.java/src/org/netbeans/modules/gradle/java/queries/FileBuiltQueryImpl.java
A trivial fix for potential NPE-s.
(NETBEANS-5475)[https://issues.apache.org/jira/browse/NETBEANS-5475] is originally marked as blocker.
It would be nice to have it in the next RC, if I had not missed the train
=> [NETBEANS-5475] fix potential NPE after GradleJavaSourceSet.relativePath() calls

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
LSP server sometimes produces very funny messages. Because of indexing features and project contents, we need to "open" the projects and perhaps prime them (so subprojects are read etc), but that happens 'behind the scenes' for the user - the user only knows he's working with a file. So a message "file belongs A to a project B" appears. But:
- if the `FileObject` passed to the asyncOpen() is the project itself, the message was very informative: "File /foo/bar/projectX belongs to project projectX...".
- the full path to file can be VERY long
=> Improved messages when project is opened bcs of file being worked on.

harness/o.n.insane/src/org/netbeans/insane/impl/InsaneEngine.java
Maybe it would be better to modify `NbInstrumentation` in Bootstrap to create a subclass only when required, the 'live' instance with unlinkable methods is a potential source of issues - @jtulach  ?
But even when I've made a subclass (I didn't finish the work, the factory for NbInstrumentation has to be moved elsewhere) the Class object for the subclass was still in some (classloader ?) array, so it didn't help my cause.
So I've patched Insane traversal - now it ignores SecurityException that complains about `java.lang` package
=> [NETBEANS-5638] Insane should ignore stub classes in traversal.

extide/gradle/src/org/netbeans/modules/gradle/nodes/BuildScriptsNode.java
BuildScript nodes can be found in project view by this new finder added.
=> [NETBEANS-4252] Added PathFinder to Gradle Build Scripts Node

extide/gradle/src/org/netbeans/modules/gradle/GradleModuleFileCache21.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/GradleModuleFileCache21Test.java
Well, this one fixes a regression detected by Scott Palmer.
I do not think this would be a major issue. Probably would happen on a few strange Gradle projects.
I put this against delivery and marked it for 12.4, so if the RM-s decide we need an rc3, then it would be nice to include this one.
@sdedic I've changed the argument order in assert equals as the first parameter is the expected value, the second one is the one that shall be tested.
=> [NETBEANS-5587] Fix regression in gavSplit

enterprise/micronaut/nbproject/project.xml, enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionProvider.java, enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautHoverProvider.java, ide/api.lsp/apichanges.xml, ide/api.lsp/arch.xml, ide/api.lsp/manifest.mf, ide/api.lsp/nbproject/project.properties, ide/api.lsp/nbproject/project.xml, ide/api.lsp/src/org/netbeans/api/lsp/Hover.java, ide/api.lsp/src/org/netbeans/api/lsp/HyperlinkLocation.java, ide/api.lsp/src/org/netbeans/spi/lsp/HoverProvider.java, ide/api.lsp/test/unit/src/org/netbeans/api/lsp/HoverTest.java, ide/api.lsp/test/unit/src/org/netbeans/api/lsp/HyperlinkLocationTest.java, java/java.editor/nbproject/project.xml, java/java.editor/src/org/netbeans/modules/editor/java/JavaHoverProvider.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java, java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementJavadoc.java, nbbuild/build.properties, nbbuild/javadoctools/links.xml, nbbuild/javadoctools/properties.xml, nbbuild/javadoctools/replaces.xml
- `Hover` and `HoverProvider` introduced that allow to resolve a hover information at a given document offset and return its content vial LSP
- Implementations for Java and Micronaut config Yaml files provided
=> LSP: Provide hover information in Micronaut yaml files.

extide/gradle/apichanges.xml, extide/gradle/manifest.mf, extide/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java, extide/gradle/src/org/netbeans/modules/gradle/GradleProject.java, extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectFactory.java, extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java, extide/gradle/src/org/netbeans/modules/gradle/ReloadAction.java, extide/gradle/src/org/netbeans/modules/gradle/ReloadProjectDependenciesDecorator.java, extide/gradle/src/org/netbeans/modules/gradle/api/NbGradleProject.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/DiskCacheProjectLoader.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleProjectLoaderImpl.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/AbstractGradleProjectTestCase.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/NbGradleProjectImplTest.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/ProjectTrustTest.java, java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImpl.java, java/gradle.java/test/unit/src/org/netbeans/modules/gradle/GradleCoreAccessor.java, java/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImplTest.java
This is an attempt to solve [NETBEANS-5627](https://issues.apache.org/jira/browse/NETBEANS-5627) and [NETBEANS-5629](https://issues.apache.org/jira/browse/NETBEANS-5629)
**It is still work in progress - but complete enough for feedback**
Major highlights of the change:
- a fresh new (untrusted) project still loads as `FALLBACK` state. **But** the Fallback heuristic is immediately applied, so the project (typically) knows its (java) source groups.
- creation attempts to load `EVALUATED` quality. This will eventually load cached info, if available
- with LegacyProjectLoader loading from above EVALUATED the project creation will not invoke Gradle build (the same as now).
- Lookup is initialized with plugins from the start: Fallback loader guesses something, and there's also …
=> [NETBEANS-5627] [NETBEANS-5629] Gradle early Lookup and Classpath initialization.

extide/gradle.dists/build.xml, extide/gradle.dists/manifest.mf, extide/gradle.dists/nbproject/project.properties, extide/gradle.dists/nbproject/project.xml, extide/gradle.dists/src/org/netbeans/modules/gradle/dists/Bundle.properties, extide/gradle.dists/src/org/netbeans/modules/gradle/dists/DistribitionSourceWatchList.java, extide/gradle.dists/src/org/netbeans/modules/gradle/dists/DistributionNodeFactory.java, extide/gradle.dists/src/org/netbeans/modules/gradle/dists/DistributionSourcesImpl.java, extide/gradle.dists/src/org/netbeans/modules/gradle/dists/LookupProviders.java, extide/gradle.dists/src/org/netbeans/modules/gradle/dists/api/GradleDistProject.java, extide/gradle.dists/src/org/netbeans/modules/gradle/dists/api/GradleDistProjectBuilder.java, extide/gradle/manifest.mf, extide/gradle/netbeans-gradle-tooling/src/main/groovy/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.groovy, extide/gradle/src/org/netbeans/modules/gradle/cache/ProjectInfoDiskCache.java, nbbuild/cluster.properties
Gradle distribution plugin can be handy from time to time. This PR would add a SourceGroup in the project node for existing dist directories.
Unfortunately Gradle distributions are represented in Gradle as CopySpec-s which are enough to copy required files, but its API is developed for flexible composition, so it does not offer proper introspection. This plugin just assume that the default folder for distribution related sources is ```<project root>/src/<distribution name>/dist```
See: https://docs.gradle.org/current/userguide/distribution_plugin.html
=> [NETBEANS-2373] Better than nothing support for Gradle Distribution dirs

extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/DiskCacheProjectLoader.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleProjectLoaderImpl.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/NbGradleProjectImplTest.java
Call me dumb: a while after I merged [PR-2924](https://github.com/apache/netbeans/pull/2924), the [NbGradleProjectImplTest](https://github.com/apache/netbeans/compare/master...sdedic:gradle/loadtest-fix?expand=1#diff-72dfc9a2d87b3278ba23d2642ce186c38cbd15e9b7795ce23d9d1b9850eadb6b) started to occasionally fail. The cause is that while the test makes a copy of the project dir, it does not maintain file timestamps - so cache may get copied a little earlier than the build.gradle file.
In addition, I've discovered [this nice issue in JDK](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8177809)...
I have added some detailed logging during debugging, that could be worth to preserve for future diagnostics of the loading process
=> Sync timestamps in test. Detailed logging added.

cpplite/cpplite.project/src/org/netbeans/modules/cpplite/project/BuildConfiguration.java
As reported here:
http://mail-archives.apache.org/mod_mbox/netbeans-users/202104.mbox/%3C56b6c75f-daca-1d28-1805-7e301639c2c2%40slipbits.com%3E
Running a cpplite project when no Run command was specified fails with an exception. When reading configuration, empty values should be ignored (as are missing values), so that the Run action is properly disabled.
=> In cpplite project, when reading configuration, an empty string should not be considered a valid configuration.

ide/db/src/org/netbeans/modules/db/explorer/Bundle.properties, ide/db/src/org/netbeans/modules/db/explorer/dlg/AddConnectionWizard.java, ide/db/src/org/netbeans/modules/db/explorer/dlg/AddDriverDialog.java, ide/db/src/org/netbeans/modules/db/explorer/dlg/ChoosingConnectionNamePanel.java, ide/db/src/org/netbeans/modules/db/explorer/dlg/ChoosingDriverPanel.java, ide/db/src/org/netbeans/modules/db/explorer/dlg/ChoosingSchemaPanel.java, ide/db/src/org/netbeans/modules/db/explorer/dlg/ConnectionPanel.java, ide/db/src/org/netbeans/modules/db/explorer/dlg/NewConnectionPanel.java, ide/db/src/org/netbeans/modules/db/util/Bundle.properties, ide/db/src/org/netbeans/modules/db/util/DriverListUtil.java, ide/db/src/org/netbeans/modules/db/util/JdbcUrl.java, ide/db/test/unit/src/org/netbeans/modules/db/util/DriverListUtilTest.java
Various small UI improvements to the Database module's "New Connection" wizard:
- Refactor the wizard to avoid depending on hardcoded wizard panel indexes.
- Improve two error messages in "New Connection" wizard.
- Avoid a spurious 'Specified class is not a driver' warning in certain situations.
- When detecting the Microsoft SQL Server JDBC driver, avoid showing an ancient version number.
- Add a default port number for Microsoft SQL Server.
- Tidy up presentation names in the JDBC URL format dropdown.
- Decrease the timeout of the connection validation step.
=> [NETBEANS-5656] Various smaller fixes in the database New Connection wizard

nbbuild/javadoctools/build.xml
=> [NETBEANS-5655] Fix build error caused by non-ASCII quotes in an arch.xml file

java/java.editor/test/unit/data/goldenfiles/org/netbeans/modules/java/editor/imports/ComputeImportsTest/14/testException-filtered.pass, java/java.editor/test/unit/data/goldenfiles/org/netbeans/modules/java/editor/imports/ComputeImportsTest/14/testException-unfiltered.pass, java/java.editor/test/unit/src/org/netbeans/modules/java/editor/view/JavaViewHierarchyRandomTest.java
https://issues.apache.org/jira/browse/NETBEANS-5699
1. com.sun.java.util.jar.pack.Attribute removed since JDK 14. Added new pass file for the same.
2. getNextVisualPositionFrom(int) method in javax.swing.plaf.basic.BasicTextUI class does not allow values greater than document length since JDK 9. Modified test method testModelToViewAtBoundaries for the same.
=> [NETBEANS-5699] - Fixed test cases failing on JDK17

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/AttachConfigurations.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/NbAttachRequestHandler.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbDebugSession.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/DebugConnector.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/protocol.ts
This PR introduces debugger attach for JPDA debugger in Apache NetBeans VSCode extension.
We provide the attach connectors in a dynamic way (according to what the current JVM provides on the current user OS).
In the VSCode UI the attach actions are available via the Run combo-box, clicking on "Java 8+..." suggests two items on Linux ("Attach to Port" and "Attach to Process") and three items on Windows ("Attach to Shared Memory" in addition).
"Attach to Process" shows a quick pick with running processes eligible for debugger attach.
The selected attach action can be added to `launch.conf` for customization via a button with "Configure" icon next to the attach action.
Two new commands are introduced:
`java.attachDebugger.configurations` - to retrieve a list of debugger attach …
=> [NETBEANS-5346] Debugger attach in VSCode extension.

platform/openide.execution/src/org/openide/execution/ExecutionEngine.java, platform/openide.io/src/org/openide/windows/IOProvider.java
The following error started to appear in tests:
```
[junit] java.lang.NullPointerException
[junit] 	at org.netbeans.modules.gradle.ActionProviderImpl.lambda$null$6(ActionProviderImpl.java:340)
[junit] 	at org.netbeans.modules.gradle.execute.ProjectConfigurationSupport.executeWithConfiguration(ProjectConfigurationSupport.java:96)
[junit] 	at org.netbeans.modules.gradle.ActionProviderImpl.lambda$invokeProjectAction2$7(ActionProviderImpl.java:326)
[junit] 	at org.openide.util.Task.notifyFinished(Task.java:215)
[junit] 	at org.netbeans.modules.gradle.execute.GradleDaemonExecutor$GradleTask.finish(GradleDaemonExecutor.java:419)
[junit] 	at org.netbeans.modules.gradle.execute.GradleDaemonExecutor.run(GradleDaemonExecutor.java:246)
[junit] 	at org.openide.util.Task.run(Task.java:232)
```
This is …
=> Fixes NPE and potential lockup in tests.

platform/core.nativeaccess/src/org/netbeans/core/nativeaccess/NativeWindowSystemImpl.java
On Windows, when dragging window system tags with the mouse, the following spurious error message may appear on the console running the NetBeans IDE or a NetBeans Platform application:
```
java.lang.UnsupportedOperationException: Set sun.java2d.noddraw=true to enable transparent windows
at com.sun.jna.platform.WindowUtils$W32WindowUtils.setWindowAlpha(WindowUtils.java:796)
at com.sun.jna.platform.WindowUtils.setWindowAlpha(WindowUtils.java:1940)
[catch] at org.netbeans.core.nativeaccess.NativeWindowSystemImpl.setWindowAlpha(NativeWindowSystemImpl.java:88)
at org.netbeans.core.windows.view.dnd.DragAndDropFeedbackVisualizer.createDragWindow(DragAndDropFeedbackVisualizer.java:89)
at org.netbeans.core.windows.view.dnd.DragAndDropFeedbackVisualizer.start(DragAndDropFeedbackVisualizer.java:110) …
```
=> [NETBEANS-5723] Avoid spurious error log message when dragging window system tabs

groovy/groovy.editor/nbproject/project.xml, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/CompletionHandler.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/CompletionItem.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/MethodCompletion.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/TypesCompletion.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/CompletionAccessor.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/GroovyElementsProvider.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/JavaElementHandler.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/java/JavaElementHandle.java
Completion items that were taken from indexes or java classes had either no `ElementHandle` or some simple one, which did not allow to resolve them back. I added a Handle subclass that records java support's ElementHandle or at least FQNs more or less suficient to find an `ElementHandle` later (for creations not backed by Element from the java support).
=> Completion items imported from Java delegate to ElementJavadoc to get the content.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbProcessConsole.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractLspInputOutputProvider.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbProcessConsoleTest.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/ui/LspIOAccessor.java
During testing of [NETBEANS-5744](https://issues.apache.org/jira/browse/NETBEANS-5744) I have found that there are two lockups related to stream closing, which is done during process termination:
- `StreamDecoder` synchronizes around its `read()` (reading the underlying InputStream) and so does `close`. So closing an `InputStreamReader` while read is pending will block the close() thread.
- `PipedInputStream` close() just sets a flag, but does not actually wake up potentially waiting reader and does not cause writer to return `-1` EOF indicator.
The patch attempts to fix it, as close() to streams bound to the process I/O may happen asynchronously when the client terminates the process. I've attempted to write tests that check the close can be done from other thread while read is pending / …
=> [NETBEANS-5744] Avoid java.io deadlock of close vs. pending read.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/AttachConfigurations.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/DebugConnector.java, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/protocol.ts
Currently, only the "Attach to Process" has a command associated, which lets the user to pick a process from a list.
Other attach configurations need to be edited with the desired values before they can be used.
To improve the usability, we create commands for individual attach attributes that ask the user for a value. This makes the attach configurations readily usable without any editing of the configurations themselves.
We also split the configurations between "Initial" and "Dynamic", as marking all of them as "Dynamic" caused unexpected behavior. Only the attach configurations are "Dynamic".
=> Debugger attach configurations ask for user input and configurations are split between Initial and Dynamic.

profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofGCRoots.java, profiler/lib.profiler/test/unit/src/org/netbeans/lib/profiler/heap/HeapTest.java, profiler/lib.profiler/test/unit/src/org/netbeans/lib/profiler/heap/heapDumpLog.txt, profiler/profiler.oql/test/unit/src/org/netbeans/modules/profiler/oql/engine/api/impl/OQLEngineTest.java
Rather than always going through all the GC roots, let's build a mapping from Thread ID -> `ThreadObjectHprofGCRoot` during a single iteration. This may be a very useful fix when [project Loom](https://openjdk.java.net/projects/loom/) and its hundreds of threads become common. I've just tried to open a dump with 400000 threads and it didn't finish in five minutes! Then I gave up.
This PR is written by me and I have a right to integrate it to Apache NetBeans project. However, to keep difference between other `.hprof` reading libraries minimal, I want to provide a permission to use the patch with same license as NetBeans had when Oracle donated them to Apache.
=> Avoid o(n^2) complexity when associating frames with threads in a heap dump.

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/Utils.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleAccess.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleStrataProvider.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/TruffleStackFrame.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/models/DebuggingTruffleActionsProvider.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/models/DebuggingTruffleTreeModel.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/models/TruffleDVFrame.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/source/Source.java, java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/FrameInfo.java, java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/JPDATruffleAccessor.java, java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/SourcePosition.java
Even though it's adviced that instrumentable Truffle Nodes provide `SourceSection`, it may happen that some Truffle language implementation does not provide it.
In the Truffle debugger implementation we need to count with `null` `SourceSection`.
=> Fixed NPEs in Truffle debugger when SourceSection is null.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/NbAttachRequestHandler.java
In VSCode, when either Attach to Process or Attach to Port is used, VSCode attaches to process in both cases, shows running threads, but it does not stop on breakpoint.
When Pause is clicked in the debugger toolbar, then it stops, but `MalformedURLException: unknown protocol: debug` exception is printed to NBLS output.
The problem was in missing `initialized` notification from the server to the client.
=> Debugger attach needs to be initialized.

platform/openide.loaders/apichanges.xml, platform/openide.loaders/manifest.mf, platform/openide.loaders/src/org/openide/loaders/DataFolder.java, platform/openide.loaders/src/org/openide/loaders/MultiDataObject.java, platform/templates/nbproject/project.xml, platform/templates/test/unit/src/org/netbeans/modules/templates/PropertiesProviderTest.java
To use `DataFolder.createFromTemplate` on project templates, like [the one in gradle](https://github.com/apache/netbeans/blob/master/java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/layer.xml#L30), we need to propagate `packageBase`, `groupId`, etc. properties.
=> Propagate createFromTemplate parameters to folder subobjects

nbbuild/templates/common.xml
The system property `cluster.path.final` is set when running unit tests, but when on Windows the last cluster in the list is separated using `:`. Fixed using the platform dependent system property `path.separator`.
=> Fix bug on using a platform dependent path separator

groovy/groovy.editor/manifest.mf, groovy/groovy.editor/nbproject/project.xml, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/CompletionHandler.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/CompletionItem.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/CompletionAccessor.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/GroovyCompletionCollector.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/GroovyCompletionImpl.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/GroovyElementsProvider.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/HTMLJavadocParser.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/JavaElementHandler.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/TransformationHandler.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/utils/GroovyUtils.java, groovy/groovy.editor/test/unit/data/testfiles/completion/method/completionInsideFor1/CompletionInsideFor1.groovy.testCompletionInsideFor1_2.completion, groovy/groovy.editor/test/unit/data/testfiles/completion/method/completionNoPrefixString1/CompletionNoPrefixString1.groovy.testCompletionNoPrefixString1.completion, groovy/groovy.editor/test/unit/data/testfiles/completion/method/completionNoPrefixString2/CompletionNoPrefixString2.groovy.testCompletionNoPrefixString2.completion, groovy/groovy.editor/test/unit/data/testfiles/completion/operators/spreadOperator1/SpreadOperator1.groovy.testSpreadOperator1_stringArray_all.completion, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/AccessCCTest.java, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/CamelCaseCCTest.java, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/CodeCompletionTest.java, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/DuplicatesCCTest.java, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/FieldCCTest.java, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/GroovyCCTestBase.java, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/InferenceCCTest.java, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/NewVarsCCTest.java, ide/csl.api/test/unit/src/org/netbeans/modules/csl/api/test/CslTestBase.java
Groovy support has very open APIs, so virtually anyone can derive from Groovy classes; that made a factory approach used in Java unsuitable - need to support potential alien implementations as well. At the same time I didn't want to expose any further APIs, although it was beneficial to add fields / getters to individual `CompletionItem` subclasses - so I have use package Accessor pattern to create/query the completion items. The accessor interface is hidden in a nonpublic package.
I moved most of the `CompletionHandler` implementation to a nonpublic package, `CompletionHandler` just delegates to it; gives a freedom to add methods for the module's internal consumption / testing.
The `CompletionCollector` implementation just translates original Groovy completion suggestions to the LSP …
=> Groovy Code Completion support available through LSP protocol.

java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/resources/LambdaBody.template, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/resources/OverriddenMethodBody.template, java/java.lsp.server/nbcode/integration/test/unit/src/org/netbeans/modules/nbcode/integration/VerifySimpleTemplatesTest.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/LspTemplateUI.java
One complain  was that it is not possible to cancel the creation of a template. Addressed by 270ec4e. 
Another complain suggested to avoid display _"Unrecognized file"_ obtained from a node short description  - addressed by ignoring it in 125b650.
Then there were complains about some templates producing empty files  - as such I wrote a test in c7de9d7 to go through all available templates and verify they lead to non-empty result. Few didn't and those are branded out in 3b3aec0. Moreover some Dušan's templates couldn't be instantiated without providing some variables - fixed in 6bd46cd.
=> Improving usability of New from Template in VSNetBeans.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java
The launch request handler checks if the selected action is actually enabled in the project; if not, it will attempt to guess an appropriate alternative configuration and suggests it to the LSP client using a notification.
=> LSP server informs client about unsuccessful launch.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/vscode/src/extension.ts
Adding Run/Debug with project configurations for main methods into VSCode code lenses.
By default, only Run for Continuous Mode (in Gradle) and Micronaut's Dev mode (in Maven) is added.
The continuous mode/dev mode does not woth with the debugger, which is intentional. I'm introducing `ProjectConfigurationProvider.configurationAffectsAction()` to check whether an action is actually defined by a particular configuration.
=> Add Run with configuration into code lenses.

enterprise/micronaut/nbproject/project.xml, enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/micronaut-actions.xml, java/api.maven/manifest.mf, java/api.maven/test/unit/src/META-INF/generated-layer.xml, java/api.maven/test/unit/src/org/netbeans/api/maven/MavenActionsTest.java, java/api.maven/test/unit/src/org/netbeans/api/maven/test-maven-actions.xml, java/api.maven/test/unit/src/org/netbeans/api/maven/test-maven-actions2.xml, java/maven/apichanges.xml, java/maven/manifest.mf, java/maven/src/org/netbeans/modules/maven/configurations/M2ConfigProvider.java, java/maven/src/org/netbeans/modules/maven/customizer/ActionMappings.form, java/maven/src/org/netbeans/modules/maven/customizer/ActionMappings.java, java/maven/src/org/netbeans/modules/maven/customizer/Bundle.properties, java/maven/src/org/netbeans/modules/maven/execute/ActionToGoalUtils.java, java/maven/src/org/netbeans/modules/maven/spi/actions/MavenActionsProvider.java
A follow-up to 3004, similar support to **disable project action** in a configuration is now implemented for Maven. The action customizer allows a simple way to disable an action, or to revert the 'disabled' instruction to a default configuration's action mapping.
Micronaut impl was updated to disable Debugs in 'dev mode' (`mn:run`).
=> Support for disabling actions in Maven (used by Micronaut)

java/maven/src/org/netbeans/modules/maven/configurations/M2ConfigProvider.java
I overlooked a failing test, merged the erroneous code to the master - sorry :( The failure was caused by [temporarily setting active configuration to `default`](https://github.com/apache/netbeans/blob/master/java/maven/src/org/netbeans/modules/maven/configurations/M2ConfigProvider.java#L431) which caused processing that lead to **permanent** configuration switch. This change skips all processing (comparing to available configs, loading persistent active setting, ...) if the local override is active.
=> Temporary configuration takes precedence, does not fire changes.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceIOContext.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractLspInputOutputProvider.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceContextTest.java
When LSP client runs "compile workspace" operation, the (gradle) compiler's I/O is bound to the LSP `WorkspaceIOContext`. Then after Gradle finishes, the `GradleExecutor` thread remains stuck:
```
"exec_Build (3)_1" #51 prio=5 os_prio=0 tid=0x00007f04a1187800 nid=0x67d2 waiting for monitor entry [0x00007f0510afa000]
java.lang.Thread.State: BLOCKED (on object monitor)
at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:191)
- waiting to lock <0x0000000719a499a8> (a org.netbeans.modules.java.lsp.server.ui.AbstractLspInputOutputProvider$LspIO$1)
at java.io.InputStreamReader.close(InputStreamReader.java:199)
at org.netbeans.modules.java.lsp.server.ui.AbstractLspInputOutputProvider$LspIO$1.close(AbstractLspInputOutputProvider.java:152)
at …
```
=> Prevent deadlock - Workspace shared IO supports close on input stream.

java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Add entry to the `OFFICIAL_JAVADOC` Map
https://download.java.net/java/early_access/jdk18/docs/api/
=> [NETBEANS-5801] - Add javadoc for JDK 18 early access

groovy/groovy.editor/nbproject/project.xml, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/PathFinderVisitor.java, groovy/libs.groovy/manifest.mf, groovy/libs.groovy/nbproject/project.xml
Packages of transformers were not exported from groovy lib; Groovy delegates to `TransformationClassloader` from groovy.editor to load transformers / extensions, but that one did not see neither transformers (from groovy core) or the extension ones in the module classloaders, so it delegated to URL classloader loading from user project's dependencies. But those extensions then attempted to use types from Groovy core (already loaded by module classloader), and loaded them again using the TransformationClassloader. CCE occured.
Whole Groovy API must be exported; the additions are more or less trial-and-error except the `subpackage` as the whole `groovy.`  subtree seems to be used by extensions.
=> Exported more packages to allow transformation loading, prevents Linkage errors

ide/api.lsp/src/org/netbeans/api/lsp/HyperlinkLocation.java, ide/csl.api/src/org/netbeans/modules/csl/editor/hyperlink/GoToSupport.java
2nd attempt to fix NPEs thrown to LSP client when hovering over source code. The DeclarationFinder sometimes returns DeclarationLocation.NONE (i.e. erroneous annotation in Groovy source), which gets reported through the CompletableFutures and fails later as it contains `null` FileObject.
=> Avoid NPEs when Finder returns DeclarationLocation.NONE or no FObject.

ergonomics/ide.ergonomics/groovy.properties, ergonomics/ide.ergonomics/java.properties, ergonomics/ide.ergonomics/test/unit/src/org/netbeans/modules/ide/ergonomics/DynamicVerifyTest.java, extide/gradle/src/org/netbeans/modules/gradle/spi/GradleFiles.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/NbGradleProjectFactoryTest.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/spi/GradleFilesTest.java, java/maven/src/org/netbeans/modules/maven/execute/MavenCommandLineExecutor.java, java/maven/src/org/netbeans/modules/maven/newproject/ArchetypeTemplateHandler.java, java/maven/test/unit/src/org/netbeans/modules/maven/newproject/ArchetypeCreateTest.java
[NETBEANS-5768](https://issues.apache.org/jira/browse/NETBEANS-5768) reports that our Gradle support isn't able to properly recognize
```bash
gradle init --type java-application --test-framework junit-jupiter --dsl groovy --package com.example --project-name example
```
This PR fixes that. It also moves the Ergonomics registration of Gradle build scripts to `java` cluster - it is my understanding that groovy support isn't required when dealing with Gradle anymore.
=> [NETBEANS-5768] Recognize gradle projects with settings.gradle only file

extide/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java, java/gradle.java/src/org/netbeans/modules/gradle/java/JavaActionProvider.java, java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceAttacherImpl.java
As part of work on 'Continuous' gradle mode, the infrastructure started to test actions for `isEnabled()` before actually invoking them. That broke source+javadoc attacher introduced in 12.4, that downloads sources/javadocs for the user - the java code never reported the actions as 'enabled', but carried them out anyway. And to be even better, the attacher relied on ActionProgress to report `finished` which never happened, since gradle's `ActionProviderImpl` returned silently without reporting anything if the client invoked a disabled action.
As a result, the Attacher blocked, the user needs to cancel it from the UI (or will run indefinitely if run headless).
=> Source/javadoc attacher must report download actions as enabled.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
Two fixes.
1. If the project is not known, thanks to @JaroslavTulach  null check the call proceeds through a series of async calls to finally return an empty array; this change does the same in a short path. I think that with no project, the original code does not wait on any Future from the backlog of projects being opened, so the change should have no impact on the sequence of operations.
2. The commit a2446ef introduced `HintsInvoker` invocation during execution of `codeAction` LSP request; although the request can return an unfinished `CompletableFuture`, which allows the client to issue additional requests through LSP protocol, the impl fully computed the code actions, then returned a `completedFuture`. The change only forks the heavy computation to background, and completes the …
=> Small LSP fixes

java/java.api.common/src/org/netbeans/modules/java/api/common/singlesourcefile/LaunchProcess.java, java/java.api.common/src/org/netbeans/modules/java/api/common/singlesourcefile/SingleSourceFileUtil.java, java/java.api.common/test/unit/src/org/netbeans/modules/java/api/common/singlesourcefile/SingleSourceFileUtilTest.java
Bug report: Create single `Hello.java` in an empty folder, with its `main`... method. Run and debug using JDK8. `Hello.class` file appears in the same folder. Change JDK to JDK11. Debug it. Following output prints to Debug console and it does not debug:
```
Listening on 51317 
User program running 
LineBreakpoint Hello.java : 3 successfully submitted.
error: class found on application class path: Hello
```
This PR fixes the problem by recompiling the `.class` if it already exists and continues executing using `java -cp ...` just like on JDK8 even on newer JDKs.
=> Prefer .class execution over .java if the class already exists

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/AttachConfigurationCompletion.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/AttachConfigurations.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/ConfigurationAttribute.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/ConfigurationAttributes.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/NbAttachRequestHandler.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/LaunchConfigurationCompletion.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ProjectConfigurationCompletion.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/UtilsTest.java, java/java.lsp.server/vscode/package-lock.json, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/launchConfigurations.ts
The server side can provide completion for run/debug configurations that are put into launch.json file.
The launch.json is parsed on the client and depending on the position, the server is asked to provide either:
- whole configurations, or
- additional attributes into an existing configuration, or
- value of an attribute in a configuration
We're adding a dependency on `jsonc-parser`, a single parsing by the client simplifies completion providers. It's added into a new file `launchConfigurations.ts` not to add more clutter into the main `extension.ts`. The client also handles the necessary commas before/after the inserted text.
A new command `java.project.configuration.completion` is called to retrieved the completion from the server.
To add a completion it's enough to implement and …
=> Completion provider for VS Code's launch.json.

extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleCommandLine.java, extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleExecConfiguration.java, extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java, extide/gradle/src/org/netbeans/modules/gradle/execute/GradleExecAccessor.java, java/gradle.java/nbproject/project.xml, java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceAttacherImpl.java, java/gradle.java/test/unit/src/org/netbeans/modules/gradle/api/execute/GradleExecApiTrampoline.java, java/gradle.java/test/unit/src/org/netbeans/modules/gradle/queries/GradleSourceAttacherImplTest.java, java/gradle.java/test/unit/src/org/netbeans/modules/java/j2seplatform/api/Bundle_da.properties, java/gradle.java/test/unit/src/org/netbeans/modules/java/j2seplatform/api/Bundle_no.properties, java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/queries/SourceJavadocAttacherUtil.java
There was a typo in PR #3029 -- an [inverted condition](https://github.com/apache/netbeans/pull/3029/files#diff-5c103f8068d80ea76751550a19a5c963ccf80879987162a74edba320ee218eefR306).  The actual [typo is fixed here](https://github.com/apache/netbeans/pull/3040/files#diff-5c103f8068d80ea76751550a19a5c963ccf80879987162a74edba320ee218eefR306) - one liner change. There was yet another [subtle bug (still unnoticed)](https://github.com/apache/netbeans/pull/3040/files#diff-c49a8b6e435ec670b8a00303efd7cee16fa59f7ed89ecde40a3b5766b20814acR177): if plugin did not attach anything the API still reported success through the listener.
The rest of this PR are tests and test infrastructure: for the source download to be reliably initiated, I've needed to run Gradle in tests with a different gradle user …
=> Fixed source+javadoc Gradle download

groovy/groovy.editor/manifest.mf, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/GroovyIndexer.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyParser.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/utils/GroovyUtils.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeClientCapabilities.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts
The groovy parser (or better: type resolution) is terribly slow, so it quite undermines usability of Groovy + Spock sources in the project. This PR makes it possible to disable indexing - with all the negative effects on the quality of code completion when the source is finally parsed - so that LSP client can disable it.
NetBeans IDE user can eventually disable it too using a system property; but the feature should remain undocumented and officially unsupported, since I (we) hope the parser's performace could be improved during the next release cycle.
=> Optionally disable groovy support in NBJLS

extide/gradle/src/org/netbeans/modules/gradle/spi/newproject/BaseGradleWizardIterator.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/LspTemplateUI.java
@JaroslavTulach started with a patch for `BaseGradleWizardIterator` that just attaches a `ProgressHandle` to the `TemplateOperation` created; but it turned out that in LSP the actual creation needs to be done asynchronously, otherwise the message reception thread won't be able to receive `workDoneProgressToken` from the client before the creation completes.
=> Report progress from Gradle's CreateFromTemplateHandler

enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroActionsProvider.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroExecutionChecker.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroProjectHook.java
Payara Micro Maven tools are built on top of Maven Web Application features and if Micro Application not detected then delegating call to default feature of Web Application. In this PR, the delegation call has been removed which causes the twice deployment for cleaned or newly created project.
=> NETBEANS-5143 Fixes Maven web app twice deployment issue

platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/AquaEditorTabCellRenderer.java, platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/AquaEditorTabDisplayerUI.java, platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/AquaViewTabDisplayerUI.java
This PR fixes scaling problems that occur in the window system tabs on the Aqua LAF on Retina displays (2x HiDPI scaling). All MacBooks and other Apple displays use retina scaling these days.
The fix is to use Graphics.fillRect instead of Graphics.drawLine; see the comment in the code. The patch adds a new "drawLine" utility method in the tab displayer UI classes for this purpose, and then does a plain search-and-replace of "g.drawLine(" with "drawLine(g, ", with no other changes.
Note that on MacOS, standard UI panel borders are two device pixels thick on Retina screens. So scaling everything up 2x on Retina displays is the right thing to do, and looks consistent with native MacOS apps.
The fixes are illustrated below, with retina scaling (2x) enabled. When viewing these images, be sure …
=> [NETBEANS-5698] Fix tabcontrol painting on MacOS retina displays (Aqua LAF)

enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/WildflyDeploymentFactory.java, harness/apisupport.harness/build.xml, java/lib.jshell.agent/agentsrc/org/netbeans/lib/jshell/agent/NbJShellAgent.java, java/lib.jshell.agent/nbproject/project.properties, nbbuild/templates/common.xml, platform/core.startup/src/org/netbeans/core/startup/Asm.java, platform/libs.asm/external/asm-9.2-license.txt, platform/libs.asm/external/binaries-list, platform/libs.asm/nbproject/project.properties, platform/libs.asm/nbproject/project.xml
Library Notes:
- JDK 18 support
- JDK 17 support
- JDK 16 support (sealed classes), new ASM9 api version
- Add some input validations in ClassReader
- Replace -debug flag in Printer with -nodebug (-debug continues to work)
- ClassReader.readStream() performance improvements
- Javadoc fixes
- 12 bug fixes
- Verify successfull execution of libraries and licenses Ant test
- Checked the files had been downloaded and placed at `/netbeans/platform/core/`
[ASM Web Page](https://asm.ow2.io/index.html)
[Release Notes](https://asm.ow2.io/versions.html)
Next version of Jacoco will [depend](https://github.com/jacoco/jacoco/blob/master/org.jacoco.doc/docroot/doc/changes.html#L40) on this …
=> [NETBEANS-5546] - Update asm from 8.0.1 to 9.2

platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/windows8/DPIUnscaledBorder.java, platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/windows8/Windows8LFCustoms.java, platform/o.n.swing.tabcontrol/nbproject/project.properties, platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/WinFlatEditorTabCellRenderer.java, platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/WinFlatEditorTabDisplayerUI.java, platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/WinFlatUtils.java, platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/WinFlatViewTabDisplayerUI.java, platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/Windows8VectorTabControlIcon.java, platform/openide.awt/src/org/openide/awt/Windows8VectorCloseButton.java
This PR modernizes the look of the main NetBeans tabs components on the Windows LAF, and makes them look good on all the standard HiDPI scalings supported on Windows (100%, 125%, 150%, 175%, 200%, and 225%).
A before/after comparison is shown here, first at 100% scaling (regular, non-HiDPI screens). To review these images, be sure to view them at 100% scaling on your screen. (If you have a HiDPI screen yourself, you may need to adjust your browser's zoom level so that each pixel in the screenshot corresponds to one device pixel on your screen.)
The new tabs adhere to the following design principles:
* Keep the tabs consistent with the style in native Windows 10 dialogs. This style is also used in the regular JTabbedPane, which is used in NetBeans e.g. in the "Output" pane.
* Keep the tab …
=> [NETBEANS-5673] Modernize tab controls in the Windows LAF

apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/MavenWhiteListQueryImpl.java, enterprise/j2ee.genericserver/src/org/netbeans/modules/j2ee/genericserver/ide/GSJ2eePlatformFactory.java, enterprise/web.jsf/src/org/netbeans/modules/web/jsf/JSFFrameworkProvider.java, enterprise/websvc.manager/src/org/netbeans/modules/websvc/manager/model/WebServiceListModel.java, enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/codegen/model/GenericResourceBean.java, java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/GradleSourcesImpl.java, platform/autoupdate.services/src/org/netbeans/modules/autoupdate/services/Utilities.java, platform/core.multiview/src/org/netbeans/core/multiview/MultiViewActionMap.java, platform/core.multiview/src/org/netbeans/core/multiview/MultiViewTopComponentLookup.java, platform/openide.nodes/src/org/openide/nodes/CookieSet.java, platform/openide.options/src/org/openide/options/VetoSystemOption.java
This change will remove the last remaining warnings about raw type HashSet.
[repeat] /home/bwalker/src/netbeans/platform/core.multiview/src/org/netbeans/core/multiview/MultiViewActionMap.java:124: warning: [rawtypes] found raw type: HashSet
[repeat]         Set keys = new HashSet();
[repeat]                        ^
[repeat]   missing type arguments for generic class HashSet<E>
[repeat]     E extends Object declared in class HashSet
At this point, we have removed all warnings related to this.. Hooray!!
=> [NETBEANS-5683] - remove last remaining HashSet raw type warnings..

nb/autoupdate.pluginimporter/src/org/netbeans/modules/autoupdate/pluginimporter/Installer.java, nb/o.n.upgrader/src/org/netbeans/upgrade/AutoUpgrade.java, nb/o.n.upgrader/test/unit/src/org/netbeans/upgrade/AutoUpgradeTest.java
Quick fix for allowing version like 12.4.301 as for Apache NetBeans we were set with Float
test is on  nb/o.n.upgrader/test/unit/src/org/netbeans/upgrade/AutoUpgradeTest.java.
copied to Autopudate. 
Reorder modifier around
=> allow more dot separated digit for version scheme

platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/BusyIcon.java
The window system tabs component has a spinning "busy" icon which is displayed e.g. while the Navigator is initially loading. This issue's Pull Request replaces the current bitmap-based icon (busy_icon.png) with a scalable spinner graphic (drawn with Java2D code) that looks better on HiDPI/Retina screens. This benefits all LAFs. Screenshot attached below.
The spinner graphic is made to look identical to the spinner that is shown on the MacOS/Aqua LAF when a JProgressBar is used with the JProgressBar.style=circular client property.
=> [NETBEANS-5696] HiDPI-scalable "spinner" icon for window system tabs

ide/editor.actions/src/org/netbeans/modules/editor/actions/ToggleAction.java
Fix incorrect checkbox state shown by 'Show Editor Toolbar' and other boolean editor preference actions.
To reproduce the original bug:
1) Open a file for editing in the NetBeans editor.
2) Click View->"Show Only Editor"
3) Click View->"Show Editor Toolbar"
4) Click View->"Show Only Editor"
5) Click View->"Show Editor Toolbar"
6) There's now a checkmark next to View->"Show Editor Toolbar", even though there is no editor toolbar showing.
The problem was that the relevant actions were wrapped in WrapperAction, which cannot track changes in selection state. The state is initialized once and never subsequently updated. The fact that the checkbox state sometimes seems to track actual changes is merely an accident--it just toggles itself whenever the action is invoked from that particular …
=> [NETBEANS-5726] Fix JCheckboxMenuItem state for 'Show Editor Tooolbar'

ide/projectui/src/org/netbeans/modules/project/ui/actions/ActiveConfigAction.java, platform/core.windows/src/org/netbeans/core/windows/view/ui/toolbars/ToolbarConfiguration.java, platform/core.windows/src/org/netbeans/core/windows/view/ui/toolbars/ToolbarContainer.java, platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/windows8/EditorToolbarBorder.java, platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/windows8/Windows8LFCustoms.java, platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/windows8/WindowsDPIWorkaroundIcon.java, platform/openide.actions/src/org/openide/actions/HeapView.java, platform/openide.loaders/src/org/openide/awt/MenuBar.java, platform/openide.loaders/src/org/openide/awt/Toolbar.java
This PR includes a few smaller improvements that were made to the Windows LAF while working on modernized tab components. Several of these relate to NetBeans' appearance when HiDPI scaling is active. Summary:
- Apply previous border tweaks for HiDPI screens in a few more places, notably in tooltips and the quick search text field, and in the editor toolbar. Improve JSpinner borders.
- Make the background color of tooltips consistent with that of other Windows 10 apps.
- Add some pixels of left margin to the editor toolbar.
- More improvements added in another commit, see the second pair of screenshots further below.
The screenshots below are from _before_ the fixes were applied.
- Also apply the workarounds from NETBEANS-3592 to JCheckboxMenuItem and friends. This fixes the following …
=> [NETBEANS-5697] Various LAF/HiDPI improvements on Windows

ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/CustomIndexerImpl.java
It was observed, that with a big project, massive time was spend in 
org.openide.util.EditableProperties.addItem(). Given, that none of the
benefits of EditableProperties take hold:
- the properties are used as pure backing store, without the expectation
of a user to modify them
- the order of the entries is irrelevant
- the file is not put into VCS (it is in the cache path)
- special line break handling is not relevant
the easiest work around is to drop usage of EditableProperties and
use plain Properties.
=> Use j.u.Properties instead of o.o.u.EditableProperties to reduce CPU usage

platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/gtk/GtkLFCustoms.java
This PR just makes NetBeans more aware of GTK used with a dark theme. The implementation is trivial, does not support GTK theme changes happening when NetBeans is running. It's a better than nothing approach.
=> [NETBEANS-5864] Sightly better support of GTK with a dark theme

enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/BasePropertiesVisual.form, enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/BasePropertiesVisual.java, enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/MicronautLaunchService.java, java/java.lsp.server/nbcode/integration/release/config/Preferences/org/netbeans/modules/java/hints/default/org.netbeans.modules.java.hints.jdk.ConvertTextBlockToString.properties
- When creating a new Micronaut projects, current version of the `https://micronaut.io/launch/` service supports JDK 8, 11, and 16 only (unlinke the previous versions that supported JDKs from 8 to 15). Changing the new Micronaut project wizard to ask service for supported JDK versions.
- ConvertTextBlockToString hint disabled by default in Language Server.
=> Micronaut: Allow for creating project on JDK 16.

php/php.editor/src/org/netbeans/modules/php/editor/csl/SemanticAnalysis.java, php/php.editor/test/unit/data/testfiles/semantic/netbeans5719_01.php, php/php.editor/test/unit/data/testfiles/semantic/netbeans5719_01.php.semantic, php/php.editor/test/unit/data/testfiles/semantic/netbeans5719_02.php, php/php.editor/test/unit/data/testfiles/semantic/netbeans5719_02.php.semantic, php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/SemanticAnalyzerTest.java
https://issues.apache.org/jira/browse/NETBEANS-5719
- Scan constructor arguments of an anonymous class
=> [NETBEANS-5719] Unused property hint is shown when the property is used as a constructor argument

java/refactoring.java/src/org/netbeans/modules/refactoring/java/resources/Bundle.properties, java/refactoring.java/src/org/netbeans/modules/refactoring/java/resources/mf-layer.xml
Added OptionsExport config to the java refactoring module so that NetBeans can migrate custom "inspect and transform" rules to new config folders automatically.
=> Jackpot rule files migration

php/php.editor/src/org/netbeans/modules/php/editor/csl/FoldingScanner.java
https://issues.apache.org/jira/browse/NETBEANS-5480
- The folding features do not have options to enable/disable each item at the moment
although there are options for each whole language (There are Enable Code Folding checkboxes)
- Users can add `-J-Dnb.php.editor.doNotFoldPhptag=true` on boot
See also: https://lists.apache.org/thread.html/r355eeab1ffcf4a96fa19847dc26256f2bd76d574573e69eb8e1f4b66%40%3Cdev.netbeans.apache.org%3E
Attached Screenshots
- https://lists.apache.org/api/email.lua?attachment=true&id=r355eeab1ffcf4a96fa19847dc26256f2bd76d574573e69eb8e1f4b66@%3Cdev.netbeans.apache.org%3E&file=9d4409e8b72c68c4e0869b4d41811cd9037fd2e2d79c7e7a8ba2e3e06de0fa7b
- https://lists.apache.org/api/email.lua?attachment=true&id=r355eeab1ffcf4a96fa19847dc26256f2bd76d574573e69eb8e1f4b66@%3Cdev.net …
=> [NETBEANS-5480] Add an option(system property) to disable the feature to fold PHP tags

java/java.disco/src/org/netbeans/modules/java/disco/Client.java, java/java.disco/src/org/netbeans/modules/java/disco/FoojayPlatformInstall.java, java/java.disco/src/org/netbeans/modules/java/disco/QuickPanel.java, java/java.disco/src/org/netbeans/modules/java/disco/QuickPkgSelection.java
Fix Linux, NPE and display issues for OpenJDK download (Disco) integration.
Make sure we get a quick package option on Linux.
Expand quick package filter to include tar.gz on Linux and macOS.
Exclude LibCType.MUSL on Linux - incorrectly coming up as option.
Only bold actual LTS labels.
Exclude early access versions- take up slider space on quick options, but none show up anyway.
Change wizard display name to more obviously describe the option, and make text localizable.
Workaround for NPE inside Disco Client library with unknown distributions.
=> Few quick bug fixes for OpenJDK download wizard

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/ClassNodeCache.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/CompilationUnit.java, groovy/libs.groovy/nbproject/project.xml
Poor performance of the Groovy parser was the reason #/3042 allows to disable Groovy indexing. I've discovered some hot points in Groovy parsing; [attaching profiling data to this PR for reference](https://github.com/apache/netbeans/files/6849268/sampler-10ms.zip)
Groovy parser tries to call `getResource` on parsing ClassLoader, which in turn delegates to `URLClassLoader` that goes through all JARs included in the compilation. While URLClassLoader may be quite fast, adding a **negative** cache for misses would avoid querying 20+ JAR implementations for a resource that is already known to be missing.
Next the parser for whatever reason tries to **load a Class to JVM** which is both slow and **dangerous** as class initializers may be run. This feature can be disabled in parser's options.
In …
=> Force bytecode parsing. Cache resource misses.

ide/editor/test/unit/src/org/netbeans/modules/editor/BaseDocumentUnitTestCase.java, java/java.editor/test/unit/src/org/netbeans/modules/editor/java/JavaFormatterArrayInitOrEnumUnitTest.java, java/java.editor/test/unit/src/org/netbeans/modules/editor/java/JavaFormatterUnitTest.java, java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
These probably never passed for the current formatting implementation. Formatting needs to be able to parse the input, but many of the samples are not really parseable. This patch attempts to fix that, and also tries to create the setup the Document so that the formatter has enough information to perform the parse.
=> Fix java.editor's Java formatting tests

ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/ResultDisplayHandler.java, ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/api/Manager.java, ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/api/TestResultDisplayHandler.java
WeakReference to `ResultDisplayHandler` erroneously garbage collected.
=> [NETBEANS-5863] "Test results" spuriously clears tests during run.

java/refactoring.java/src/org/netbeans/modules/refactoring/java/resources/mf-layer.xml
The wrong bundle was referenced to specify the displayName for the
refactoring rules.
=> Fix Options export after b5587b9a9f2b254218cce5fa910d93cd10988a04

java/java.lsp.server/nbcode/branding/modules/org-netbeans-modules-gradle.jar/org/netbeans/modules/gradle/api/execute/Bundle.properties
This is an option that is available in NetBeans IDE, but not accessible in LSP client.
=> Branded in "Trust all gradle" button.

groovy/groovy.editor/apichanges.xml, groovy/groovy.editor/arch.xml, groovy/groovy.editor/nbproject/project.properties, groovy/groovy.editor/nbproject/project.xml, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/util/CompletionContext.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/ApplyGroovyTransformation.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyParser.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/ApplyGroovyTransformationProcessor.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/CompilationUnit.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/ParsingCompilerCustomizer.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/SimpleTransformationCustomizer.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/resources/layer.xml, groovy/groovy.editor/test/unit/src/META-INF/services/org.codehaus.groovy.transform.ASTTransformation, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/parser/GroovyParserTest.java, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/test/DisableTransformersStub.java, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/test/GroovyTestTransformer.java, ide/parsing.indexing/apichanges.xml, ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/IndexingTask.java, ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/RepositoryUpdater.java, ide/parsing.indexing/src/org/netbeans/modules/parsing/spi/indexing/support/IndexingSupport.java
First commit: the hack made in [#3042](https://github.com/apache/netbeans/pull/3042/files#diff-890da1cd8d2dce9fb90de0ac649bf9a371f88aface37ee8dca28fa366b1e2554R134) is formalized as [an API in `parsing.indexing`](https://github.com/apache/netbeans/compare/master...sdedic:groovy/manage-transformations?expand=1#diff-59871e7c12a8f51236f02db6b30608e72129fb0e9a613531b27612a020447a5aR199). Just a simple `boolean` that identifies tasks created by Indexing infrastructure. 
I've added layer-based declarative instructions to enable or disable transformations for parsing, indexing or both. This declarative format is not an API itself, bcs per @JaroslavTulach  suggestion, I have created (and documented) [`ApplyGroovyTransformation`](https://github.com/apache/netbeans/compare/master...sdedic:groovy/man …
=> [Groovy] Manage AST transformations

platform/libs.flatlaf/external/binaries-list, platform/libs.flatlaf/external/flatlaf-1.5-license.txt, platform/libs.flatlaf/nbproject/project.properties, platform/libs.flatlaf/nbproject/project.xml
Update FlatLaf from 1.4 to 1.5 to:
- fix missing texts in file chooser: https://issues.apache.org/jira/browse/NETBEANS-5865
- fixes an occasional application crash on Windows 10 with native window decorations enabled
https://github.com/JFormDesigner/FlatLaf/releases/tag/1.5
BTW I've accidentally pushed this directly to NetBeans delivery branch some minutes ago.
I've undone it. Hope this does not cause problems.
Sorry.
Edit: And I should not have used `delivery` as branch name for this PR. Sorry.
=> [NETBEANS-5865] FlatLaf: fix missing texts in file chooser (update FlatLaf from 1.4 to 1.5)

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java
`CompletableFuture.supplyAsync()` is using `InnocuousForkJoinWorkerThread` by default, which has no permissions.
Using `RequestProcessor` instead.
=> [NETBEANS-5887] Use RequestProcessor to fix SecurityException:setContextClassLoader.

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/ASTUtils.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/GroovyIndexer.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/StructureAnalyzer.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/CompletionItem.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/elements/ast/ASTClass.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/elements/ast/ASTField.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/elements/ast/ASTMethod.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/inference/MethodInference.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/inference/TypeInferenceVisitor.java, groovy/groovy.editor/test/unit/data/testfiles/completion/flow/reassignment/Reassignment.groovy, groovy/groovy.editor/test/unit/data/testfiles/completion/flow/reassignment/Reassignment.groovy.testReassignment_1.completion, groovy/groovy.editor/test/unit/data/testfiles/completion/flow/reassignment/Reassignment.groovy.testReassignment_2.completion, groovy/groovy.editor/test/unit/data/testfiles/completion/method/methods4/Methods4.groovy, groovy/groovy.editor/test/unit/data/testfiles/completion/method/methods4/Methods4.groovy.testMethods4.completion, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/FlowCCTest.java, groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/MethodCCTest.java
* Abstract methods were not indexed at all, since [they have no code](https://github.com/apache/netbeans/compare/delivery...sdedic:groovy/completion-inner-classes3?expand=1#diff-6ee817fd5ae2474a0c13faafb5907287e443661413bb3a5adef6c6a250280e12L303). 
* Indexer did not dive [into inner types](https://github.com/apache/netbeans/compare/delivery...sdedic:groovy/completion-inner-classes3?expand=1#diff-a15c71a9d9bb85f1b65d31becc69c263b500c5c1fc6cea716b1629d4f531e08fR278), 
* Navigator works bad with inner types, displayed `OuterType$InnerType`
* Variable type was obscured by assignments later than caret position.
=> Indexing of inner classes/interfaces

cpplite/cpplite.debugger/nbproject/project.xml, cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPLiteDebugger.java, cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPLiteDebuggerConfig.java, cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/api/Debugger.java, cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/ni/NIDebuggerProviderImpl.java, cpplite/cpplite.debugger/test/unit/src/org/netbeans/modules/cpplite/debugger/AbstractDebugTest.java, ide/nativeimage.api/manifest.mf, ide/nativeimage.api/src/org/netbeans/modules/nativeimage/api/debug/NIDebugger.java, ide/nativeimage.api/src/org/netbeans/modules/nativeimage/spi/debug/NIDebuggerProvider.java, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/AttachConfigurations.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/AttachNativeConfigurations.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/NbAttachRequestHandler.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/Processes.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbDebugSession.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts, java/java.nativeimage.debugger/manifest.mf, java/java.nativeimage.debugger/nbproject/project.xml, java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/actions/Bundle.properties, java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/actions/NIAttachCustomizer.form, java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/actions/NIAttachCustomizer.java, java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/actions/Processes.java, java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/api/NIDebugRunner.java
We have a launch of native image working. But attach to a running process of native image was missing.
This PR introduced the attach to both NetBeans and LSP/VSCode.
A list of running processes is provided, sorted from the newest to the oldest. In NetBeans it's added to the attach dialog, in VSCode we're introducing `nativeImage.attachDebugger.pickProcess` command.
=> Attach to a running Native Image.

enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
When adding a new server, after selecting "Glassfish Server" and pressing next, when selecting an install location, the GUI searches for a valid instance by comparing all possible instances (versions) with the one found in the location specified.
```
org.netbeans.modules.glassfish.common.wizardsServerWizardIterator::isValidInstall
org.netbeans.modules.glassfish.common.ServerDetails::isInstalledInDirectory
```
If the Glassfish version is 6.2, it shows it has found 6.1, but then goes on with the 6 version, as the 6.1 instance says it's 6.
`org.netbeans.modules.glassfish.common.ServerDetails::getVersion`
Now 6.1 says it's 610 and 6.0 says it's 600 as other versions do.
Fixes small bug in Jakarta EE 9 GlassFish 6 Support (#2902).
=> Fixes wrong detection message when selecting a GF6.2 location.

extide/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java, extide/gradle/src/org/netbeans/modules/gradle/actions/ActionToTaskUtils.java, extide/gradle/src/org/netbeans/modules/gradle/actions/ConfigurableActionsProviderImpl.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/actions/ConfigurableActionsProviderImplTest.java
See [NETBEANS-5906](https://issues.apache.org/jira/browse/NETBEANS-5906). The main issue was that **enabled** is defined by **GradleActionProviders**, but the Navigator creates its own custom action (that do not belong to any proivider, naturally). 
Similarly user-defined custom actions are not managed by any provider. So this omission is likely to break any user-defined custom actions, too: Since they are reported as disabled, they won't be processed.
During implementation I've discovered [NETBEANS-5918](https://issues.apache.org/jira/browse/NETBEANS-5918): funny issue caused by a weak listener that is not referenced from anywhere and is GCed. So the cache does not react properly when a **gradle.properties** or a action mapping XML files are created in the project dir.
Finally …
=> NETBEANS-5906: treat custom actions as enabled

java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/HtmlJavaPagesNodeFactory.java, java/gradle.htmlui/test/unit/src/org/netbeans/modules/gradle/htmlui/CreateArchetypeTest.java
When a Gradle project for Java Frontend Application is created (like in #3095), it doesn't navigate user to `pages` directory with `index.html` - finding that directory is quite tricky and hurts experience of those who try to use this support. The PR fixes that by creating a dedicated node, if the `src/main/webapp/pages` directory is found.
Laszlo, can you please check if I am using the Gradle project extension mechanism properly? It does work, but maybe there are better ways to achieve the same.
Sváťo, maybe the plugin could register actions and associate Run with `bck2brwsrShow -t` without the need to specify that in the `gradle.properties`? However I haven't found an example to do it - `micronaut` project doesn't seem to specify that, but I think @sdedic has created an API that should …
=> Exposing "Frontend UI Pages" to users of Java Frontend Application

platform/openide.actions/src/org/openide/actions/HeapView.java
This fixes an issue with the heap view text being ugly and illegible on dark LAFs such as FlatLaf Dark. Not a major issue, but really stands out in the UI.
Unfortunately, #2965 added a hardcoded, non-optional highlight colour to the text. I considered making the value truly optional (ie. don't render the highlight at all if no key), but deriving the colour from the background colour should work OK.
=> [NETBEANS-5910] Fix illegible heap view text with dark LAFs

java/java.disco/src/org/netbeans/modules/java/disco/BrowsePanel.java, java/java.disco/src/org/netbeans/modules/java/disco/BrowseWizardPanel.java
Recent reporting of JDK 17 as GA by Disco (itself probably in error) shows that the quick selection doesn't handle the inability to find a download link very well.  This simple fix changes the quick selection text to show `Searching...` and to wait for Disco response before enabling next button in wizard. Also shows an error message and keeps next button disabled if Disco lookup fails.
=> Fix silent errors in Disco support when no valid response for quick selection

java/java.lsp.server/build.xml, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml, java/java.lsp.server/nbcode/integration/test/unit/src/org/netbeans/modules/nbcode/integration/VerifyPresentUpdateCentersTest.java, java/java.lsp.server/vscode/BUILD.md
The `.vsix` file as published on [marketplace](https://marketplace.visualstudio.com/items?itemName=ASF.apache-netbeans-java) has traditionally been assembled together with `nbjavac` library for better cross-JDK editing support and ability to run the extension on JDK8 without any additional downloads. Time to make it the default. That's what  1d74cad does.
In addition to that I am opening access to default release catalog - originally removed in a panic by ac183a7904d1c53d7e89df18e36bcc8188005b19 - turned out that properly building the `.vsix` file with proper metarelease information and also fa85b5178041cba0ab65d70ec2e6a6340a04ef5e is enough to prevent the former problems.
Moreover having the update center enabled allows one to install additional modules not packaged in `.vsix` by …
=> By default build release-like version of .vsix

nbbuild/misc/hints-settings.xml
I am all for _clean code_ and keeping our sources without warnings and not applied hints. However, the default set of hints includes "convert to functional operations" and I find that one particularly annoying. I am quite fine using _OPFL - old plain for loops_ most of the time.
As such I propose to suppress the hint a bit. Make it visible only on affected line, for example. I have used the NetBeans IDE UI that allows to disable the hint and following change appeared on my disk. I assume, if we integrate it, the "convert to functional operations" hint is going to be suppressed (a bit).
Various IDEs offer summaries of errors/warnings in the code and I'd be really thankful if only important hints were included in such summaries.
=> Keep old plain for loops in NetBeans sources

java/java.lsp.server/build.xml, java/java.lsp.server/vscode/BUILD.md, java/java.lsp.server/vscode/package.json, platform/autoupdate.cli/manifest.mf, platform/autoupdate.cli/src/org/netbeans/modules/autoupdate/cli/CodeNameMatcher.java, platform/autoupdate.cli/src/org/netbeans/modules/autoupdate/cli/ModuleOptions.java, platform/o.n.bootstrap/src/org/netbeans/IllegalModuleException.java, platform/o.n.bootstrap/src/org/netbeans/ModuleManager.java
Support for editing so called _API support_ projects has been intentionally left out of VSNetBeans. It is archaic and out of interest of the new generation of developers. However we, the NetBeans oldtimers, do care about editing/compiling/debugging Apache NetBeans sources.
To balance the need of these two target groups I propose a simple way to build own customized VSNetBeans extension with _API support_ modules in. Just build the extension as you are used to and then execute:
```bash
java/java.lsp.server/vscode$ npm run apisupport
```
Then you can open any Apache NetBeans project and work with it without any limitations:
```bash
java/java.lsp.server/vscode$ code --extensionDevelopmentPath=`pwd` ../../platform/autoupdate.cli/
```
Should the project still not be recognized, consider …
=> Eating VSCode own Dog Food

ide/projectapi/src/org/netbeans/modules/projectapi/LazyLookup.java, ide/projectapi/src/org/netbeans/modules/projectapi/LazyLookupProviders.java, ide/projectapi/src/org/netbeans/spi/project/support/DelegatingLookupImpl.java, ide/projectapi/test/unit/src/org/netbeans/modules/projectapi/LazyLookupTest.java, ide/projectapi/test/unit/src/org/netbeans/spi/project/support/DelegatingLookupDeadlock5914Test.java
Visual inspection of `LazyLookupProviders` code suggests an inconsistency: `Object.wait()` waits on value of `LOCK[0]` and such value can be provided without  setting calling `Object.notifyAll()`. This should be an easy fix for [this deadlock](https://issues.apache.org/jira/secure/attachment/13032558/13032558_12.5-beta2-threaddump-1629986898821.tdump).
The rest of the [NETBEANS-5914](https://issues.apache.org/jira/browse/NETBEANS-5914) issue is going to be exorcized by 9227546
=> [NETBEANS-5914] Call notifyAll + avoid delivering changes under a lock

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/CompilationUnit.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/MethodCompletion.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/TypesCompletion.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/JavaElementHandler.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/java/JavaElementHandle.java
The missing call is causing exceptions when the completion is invoked from LSP.
=> Get elements resolved before working with types.

java/java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/CloneAndCloneableTest.java, java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/ImplementAllAbstractMethodsTest.java, java/java.hints/test/unit/src/org/netbeans/modules/java/hints/suggestions/ImplementMethodsTest.java, java/java.source.base/test/unit/src/org/netbeans/api/java/source/GeneratorUtilitiesTest.java, java/java.source/src/org/netbeans/modules/java/source/resources/GeneratedMethodBody.template, java/java.source/src/org/netbeans/modules/java/source/resources/LambdaBody.template, java/java.source/src/org/netbeans/modules/java/source/resources/OverriddenMethodBody.template
While working on #2960 I forgot to modify Java code templates. That's annoying as these templates are exactly something that needs customization:
Clicking the URL in editor opens the template.
=> Include URLs in Java code templates for easier customization

profiler/lib.profiler/manifest.mf, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HeapFactory.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofByteBuffer.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofHeap.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofMappedByteBuffer.java, profiler/lib.profiler/test/unit/src/org/netbeans/lib/profiler/heap/HeapFromBufferTest.java, profiler/lib.profiler/test/unit/src/org/netbeans/lib/profiler/heap/HeapSegmentTest.java, profiler/lib.profiler/test/unit/src/org/netbeans/lib/profiler/heap/HeapTest.java
Certain environments are special and do not provide direct access to the filesystem. As such I cannot use `java.io.File`, `java.io.FileInputStream` & co. Yet processing `.hprof` files may be needed even in such environments. Let's provide an API to load an `.hprof` file content from a `ByteBuffer`. The other issue is `CachedDirectory` - it cannot be used either, as it is directly accessing the filesystem. As far as I can say the current code seems to be ready to work without `CachedDirectory`, this PR just provides a way to request cache-less mode via a new API method.
=> Library to process Heap dumps without accessing java.io.File

java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/DeadlockDetectorImpl.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/JDIExceptionReporter.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/JPDADebuggerImpl.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/SingleThreadWatcher.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/actions/StepActionProvider.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/models/JPDAThreadGroupImpl.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/models/JPDAThreadImpl.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/models/ObjectTranslation.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/models/ThreadsCache.java, java/java.lsp.server/manifest.mf, java/java.lsp.server/nbcode/branding/modules/org-netbeans-modules-debugger-jpda.jar/org/netbeans/modules/debugger/jpda/Bundle.properties, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/variables/NbVariablesRequestHandler.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/layer.xml
Remote debugging over slow connections (about 180ms to 200ms per single JDI call that involves JDWP communication over the globe) has a significant impact on debugger experience.
A speed up is achieved by removal of unused functionality, by caching and by parallelization of requests.
=> Performance optimizations to speed up remote debugging.

platform/openide.nodes/src/org/openide/nodes/Node.java, platform/openide.nodes/test/unit/src/org/openide/nodes/LazyNodeTest3196.java
There's a bug in org.openide.nodes.Node.setChildren(Children). Basically, if Children.LEAF.getNodesCount() is _ever_ called, from any module, then Node implementations that switch from Children.LEAF to another Children implementation will no longer get lazy loading behavior.
(This bug was found in a NetBeans Platform application that relies heavily on lazy loading of nodes. It calls setChildren(Children.LEAF) in order to prevent an an expansion handle from appearing in OutlineView for nodes that are known to have no children, and then calls setChildren again if children later do appear.)
See https://issues.apache.org/jira/browse/NETBEANS-3196 for more details.
=> [NETBEANS-3196] Fix lazy Node loading when switching from Children.LEAF to another Children instance

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/GroovyIndexer.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyParser.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/NbGroovyErrorCollector.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/ClassNodeCache.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/CompilationUnit.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/NbClassNodeResolver.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/PerfData.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/PerfStatCompilationUnit.java, groovy/libs.groovy/nbproject/project.xml
This PR adds some performance counters and hacks that allow individual Groovy compiler's phases and visitors to be measured during parsing. Statistics are printed at the end of each parsing task and in case of indexing, summary and a per-file averages are printed after root's indexing completes.
The performance logs are enabled by setting `org.netbeans.modules.groovy.editor.compiler.PerfData` loglevel to `FINER` or more.
Next, the PR changes resource loading for Groovy:
- the resource is loaded using NB `ClassPath` (which uses FileSystems) rather than through `ClassPath.createClassLoader()`, which seems to be very slow.
- java classes are loaded from java indexer caches: this speeds up loading referenced classes from the project itself
As a result, the Groovy parsing is **about 5-10 times …
=> Performance: groovy loads classes using FileSystems

ide/api.java.classpath/src/org/netbeans/api/java/classpath/ClassPath.java
During some implementation I've mindlessly modified the result of `ClassPath.getRoots()` call ... and then spent more than 5 hours by hunting down the bug since it wasn't originally obvious, but "sometimes" the parser stopped to resolving symbols against the classpath. "sometimes" = when the added (debugging) code run and modified the ClassPath caches for all IDE.
I think making the code fool-proof is worth the array-copy overhead...
=> Return a copy instead of cached array

profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/AbstractLongMap.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/CacheDirectory.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/ClassDump.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/DominatorTree.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/File.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HeapFactory.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HeapProgress.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofByteBuffer.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofFileBuffer.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofHeap.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofLongMappedByteBuffer.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofMappedByteBuffer.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/JavaIoFile.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/LongBuffer.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/LongMap.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/NearestGCRoot.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/NumberList.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/Progress.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/RandomAccessFile.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/StackFrameSegment.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/StackTraceSegment.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/StringSegment.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/Systems.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/TreeObject.java
In the quest to [make the Heap library work without file access](https://github.com/apache/netbeans/pull/3148) I am refactoring the code logic to be `java.io.File` and `java.io.RandomAccessFile` free. The commit a69dca3 creates two package private classes `File` and `RandomAccessFile` (naming is chosen to minimize the size of the diff) and moves all the I/O code into them. The rest of the code stays untouched as much as possible.
There are other two problems:
*  lib.profiler is calling into `SwingUtilities.invokeLater` - eliminated by ab8b1e5 - the idea is to keep compatibility of `HeapProgress`, but unless somebody (e.g. a Swing UI of profiler) calls it, the class is not going to initialize
*  lib.profiler is using `ex.printStackTrace()` - 1998eb2  solves it the same way as I/O access - …
=> Concentrating I/O access into JavaIoFile private class

ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/CodeTemplateCompletionProvider.java, java/java.editor/src/org/netbeans/modules/java/editor/resources/Bundle.properties, java/java.editor/src/org/netbeans/modules/java/editor/resources/DefaultAbbrevs.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/SurroundWithHint.java, java/java.lsp.server/vscode/src/extension.ts
- Problem with too complex surround with menu fixed - original menu narrowed down couple of most common items only, the rest is available on generic `Surround with ...` invocation.
- Surround with try produces broken code - fixed
- Entries for `try/catch` and `try/catch/finally` added
=> LSP: Various Surround With refactoring fixes.

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyParser.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/NbGroovyErrorCollector.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/CompilationUnit.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/NbClassNodeResolver.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/PerfData.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/PerfStatCompilationUnit.java
I've missed yet another resource lookup through ClassLoader.  In the case of `NbClassNodeResolver`, alll resources were loaded by the parent (= `ClassLoaderSupport` created by `ClassPath`) of the GroovyclassLoader (= `ParsingClassLoader`) so the resource lookup through ClassPath's classloader is completely unnecessary. in addition, loadByClassLoading was set to false, so I've deleted the relevant part of the code.
i also completely disabled error failures in compilation phases; Groovy tends to bail out on trivial errors (like imported symbol not exists) and will skip later more interesting compilation phases which attribute the tree.
=> Avoid ClassLoader resource lookups

ide/db.sql.visualeditor/build.xml
Was compiling on a very very old clone and java file generated from javacc were old 3.2 and not deleted.
Should be more rebuildable
=> ant clean fix for javacc java file

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyParser.java, groovy/groovy.editor/test/unit/data/testfiles/BookmarkController.groovy.indexed, ide/csl.api/test/unit/src/org/netbeans/modules/csl/api/test/CslTestBase.java
Merge of #3175 has introduced bugs - test failures. It turned out that in that PR merge process, I didn't check properly Travis :-/
So this PR:
* only suppresses errors after parsing phase. There is an 'error recovery' that handles errors thrown from the parsing. This bug failed some tests.
* updates `BookmarkController.groovy.indexed` golden file: originally, the compiler failed on non-existent imported symbol and did not proceed to phase 6-7 where accessor methods are generated
* used `IndexingTask` marker API to indicate indexing is in progress; groovy.editor will not run static analysis that may produce additional errors: this is the original behaviour.
=> Fix test failures in Groovy.editor

java/java.source.base/src/org/netbeans/api/java/source/TypeMirrorHandle.java, java/java.source.base/test/unit/src/org/netbeans/api/java/source/TypeMirrorHandleTest.java
`ErrorType` constructor signature in vanilla javac differ from the corresponding signature in nb-javac. Temporary fix until fixed in nb-javac.
=> NETBEANS-6080: NoSuchMethodError thrown while applying CreateClassFix.

extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java, extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDistributionProviderImpl.java
Fixed an NPE when no distribution dir found using a file location.
=> [NETBEANS-6055] Prevent NPE form GradleDistributionManager

cpplite/cpplite.editor/src/org/netbeans/modules/cpplite/editor/lsp/LanguageServerImpl.java
There are various scenarios where the start routine for the language
server could result in a null value. If on that value Pair#second is
called, this results in a direct NullPointerException being raised.
The value needs to be checked first before the #second invocation is
done.
=> Prevent NullPointerException in CPP LanguageServerImpl

java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionCollector.java, java/java.editor/src/org/netbeans/modules/java/editor/codegen/ToStringGenerator.java, java/java.hints/src/org/netbeans/modules/java/hints/errors/ErrorFixesFakeHint.java, java/java.hints/src/org/netbeans/modules/java/hints/errors/MagicSurroundWithTryCatchFix.java, java/java.hints/src/org/netbeans/modules/java/hints/errors/SurroundWithTryCatchLog.form, java/java.hints/src/org/netbeans/modules/java/hints/errors/SurroundWithTryCatchLog.java, java/java.lsp.server/nbcode/integration/release/config/Preferences/org/netbeans/modules/java/hints/default/org.netbeans.modules.java.hints.errors.ErrorFixesFakeHintSURROUND_WITH_TRY_CATCH.properties, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ExtractSuperclassOrInterfaceRefactoring.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java, java/java.lsp.server/vscode/src/testAdapter.ts, java/refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/MoveFileRefactoringPlugin.java
* GR-33924: Code completion partially broken in method bodies in latest builds.
* GR-32319: Hover failed: ClassCastException: FilterDocument cannot be cast to LineDocument.
* GR-33740: Using .class on a type completes with null on the end.
* GR-31747: JUnit tests that fail to initialise lead to false success state.
* GR-33741: Quick fix for checked exception should not add java.util.logging.
* GR-33804: Null related message in Extract Superclass. 
* GR-33785: Try/catch block with resources.
* GR-33778: Can't rename constructor.
* GR-33807: Generate toString method default template.
* GR-33789: VSCode is accepting moving inner class inside itself.
=> LSP: various refactor bugfixes

cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/breakpoints/PersistenceManager.java, ide/javascript2.debug/src/org/netbeans/modules/javascript2/debug/breakpoints/io/PersistenceManager.java, ide/spi.debugger.ui/apichanges.xml, ide/spi.debugger.ui/arch.xml, ide/spi.debugger.ui/manifest.mf, ide/spi.debugger.ui/src/org/netbeans/modules/debugger/ui/PersistenceManager.java, java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/breakpoints/PersistenceManager.java, java/java.lsp.server/nbcode/integration/nbproject/project.xml, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/LspDebuggerOptions.java, java/java.lsp.server/nbcode/integration/test/unit/src/org/netbeans/modules/nbcode/integration/VerifyDebuggerPersistence.java, java/java.lsp.server/nbproject/project.xml
Debugger has it's own `Properties` API for settings persistence.
We use it in LSP to override the default for breakpoints and watches persistence.
=> Do not persist breakpoints and watches when debugging through LSP server.

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyParser.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/provider/JavaElementHandler.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/language/GroovyDeclarationFinder.java
Even after recent delivery merge, I've found some more places where I should call .toPhase().
=> Must reach ELEMENTS_RESOLVED before working with java els

java/java.hints/src/org/netbeans/modules/java/hints/jdk/CheckRegex.java, java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/CheckRegexTest.java
The severity of the CheckRegexp of VERIFIER causes all lines in source
files containing a regexp to be marked as warning. This is invalid, as
the regexp are perfectly ok.
The severity is reduced to HINT. That way the hint is readily available
when the regexp is under the cursor, but does not clutter the whole
file.
=> CheckRegexp hint causes all lines with regexp shown with a warning

enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties, enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java, enterprise/glassfish.common/test/unit/src/org/netbeans/modules/glassfish/spi/UtilsTest.java, enterprise/glassfish.tooling/nbproject/project.properties, enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java, enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/ConfigBuilderProvider.java, enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/GlassFishV6_2_1.xml, enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/JavaSEPlatform.java
With Glassfish 6.2.1 support for JDK 17 was added, so meta data for
that version was added.
The version detection was improved in the following way:
If an exact match is found, that entry is used. Else the list of
server definitions is iterated from highest to lowest. The highest
definition, where the version number is lower than or equal to the
target version is used to configure the server.
As an example: If you try to configure Glassfish 6.2.2, it will not
find an exact match. Instead 6.2.1 is matched. Prior to this change,
the configuration for 6.0 would have been chosen.
=> [NETBEANS-5734] Add details for Glassfish 6.2.1 server and improve version detection

java/maven/src/org/netbeans/modules/maven/execute/CommandLineOutputHandler.java
Chars were written as bytes to a stream, ignoring the encoding.
By wrapping the stream in a writer, chars can now be encoded properly.
Chose to not specify the encoding so that the default can be used or
overwritten by -Dfile.encoding=UTF-8.
JDK 18+ uses UTF-8 as default, it will be probably best practice
to set the encoding to UTF-8 for most JDK 17 projects too, while using
the new 'native.encoding' property for edge cases.
=> [NETBEANS-6115] UTF-8 input is broken in Maven project.

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/models/TruffleDVFrame.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/source/Source.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java
Handle possible exceptions thrown by `Paths.get(URI)` and provide a custom URL with the source content when the original file URL is not readable.
=> Handle any script's URI and provide script content when not readable from file.

groovy/groovy.support/src/org/netbeans/modules/groovy/support/api/GroovySources.java
[NETBEANS-6068] Add back SOURCES_TYPE_JAVA into GroovySources::getGroovySourceGroups
This change added as part of [NETBEANS-4975](https://issues.apache.org/jira/browse/NETBEANS-4975) seems to be a cause of some issues reported in [NETBEANS-6068](https://issues.apache.org/jira/browse/NETBEANS-6068).
@lkishalmi could you take a look at this, which reverts a part of #2507 I'm not sure of the reasoning for this change, and I don't use Groovy much, but as it was raised as a potential blocker for 12.6 I had a look.  This seems to at least to be the cause of some exceptions mentioned in NETBEANS-6068
=> [NETBEANS-6068] Add back SOURCES_TYPE_JAVA into GroovySources

java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/JackpotTrees.java, java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java
* JackpotTrees.createInstance() will match constructors directly - no filling up with null objects anymore
* extracted typesafe factory methods to keep the fragile code in one place and make it hopefully easier to update it in future
=> [jackpot] Attempt to make JackpotTrees more robust.

ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/CodeTemplateInsertHandler.java
After successful classtype completion, a new auto-completion should
appear for constructor selection, without having to press ctrl+space again.
Regression since 12.3.
took me a while to find this. Had to git bisect to find a9871c5085106f1ffd6c1c7ec594774185cf69d6 which introduced this small regression.
It seems to work fine, I keep this as draft until I did a bit more manual testing.
example:
```java
new ArrayL
```
press ctrl+space, enter
```java
new ArrayList<>
```
should show a completion window for the constructors without having to press ctrl+space again, since the completion is not finished.
=> [NETBEANS-6114] Restore automatic constructor completion functionality.

java/java.editor/src/org/netbeans/modules/java/editor/resources/fontsColors.xml
[NETBEANS-5962](https://issues.apache.org/jira/browse/NETBEANS-5962) Remove default bgcolor for multiline Strings - inherited and illegible on various editor themes. This was reported against FlatLaf Dark but it affects others too. This is a quick fix for 12.6 - need to consider how to display indents and make sure they work across all editor themes, in particular handling dark ones.
cc/ @arusinha @jlahoda
=> [NETBEANS-5962] Remove default bgcolor for multiline Strings

java/java.source.base/src/org/netbeans/modules/java/source/parsing/VanillaPartialReparser.java
The verification step of the VanillaPartialReparser serialises the
reparsed tree to a string and comparse these. The issue is, that the
toString result of a CapturedType contains the sequence
"capture#NUMBER". Number is the hashCode of the mirror. As hashCode
is not overwriten, this is more or less a random number and thus
meaningless for the tree comparisson leading to invalid incorrect
partial reparsing reports
This normalises it to a plain capture.
=> VaniallaPartialReparser reports incorrectly reparsed files

platform/autoupdate.services/build.xml, platform/autoupdate.services/src/org/netbeans/modules/autoupdate/services/Utilities.java, platform/autoupdate.services/test/unit/src/org/netbeans/modules/autoupdate/services/UtilitiesTest.java
Utilities#getKeyStore needs to check the supplied trustlevel against
the trustlevel reported by the KeyStoreProvider. Else all keystores
are returned for all levels and thus all KeyStores are reported on
level TRUST.
=> Consider the reported trustlevel of the KeyStoreProvider when querying KeyStores

.travis.yml, java/maven.embedder/nbproject/project.xml, java/maven.embedder/src/org/netbeans/modules/maven/embedder/impl/MavenProtocolHandler.java, java/maven.embedder/test/unit/src/org/netbeans/modules/maven/embedder/impl/MavenProtocolHandlerTest.java, java/maven.embedder/test/unit/src/org/netbeans/modules/maven/embedder/impl/NbRepositoryCacheTest.java
Consider this URL: m2:/com.dukescript.nbjavac:nb-javac:jdk-17%2B35:jar
it refers to the artifact with the components:
groupId:    com.dukescript.nbjavac
artifactId: nb-javac
version:    jdk-17+35
type:       jar
In the version string jdk-17%2B35, the + character is URL encoded and
needs to be decoded before used in the maven resolver to create the
artifact.
=> m2 URL components need to be URL decoded before being used to create the artifact

java/java.hints/src/org/netbeans/modules/java/hints/jdk/IteratorToFor.java, java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/IteratorToForTest.java
IteratorToFor.whileIdiom() only triggered on code without generics. Added another rule for the generic case.
All other rules in this inspection did take generics into account already, this one had it missing.
=> [jackpot] added generics aware rule to IteratorToFor inspection

java/java.source.base/src/org/netbeans/api/java/source/TreeUtilities.java
Currently, if unenter fails (most likely because it is missing on a given version of JDK, like 11), an error is printed into System.err. This patch changes that to a `Log`. When we upgrade the baseline javac, then this should become a direct method call, I believe, but if there will be another RC of 12.6, it might be nice to not print the errors into System.err.
=> If unenter is not available (on older javac versions), print the error into a log, rather than into System.err

ide/libs.graalsdk/src/org/netbeans/libs/graalsdk/impl/GraalEngine.java
According to [GraalSDK documentation](https://docs.oracle.com/en/graalvm/enterprise/20/sdk/org/graalvm/polyglot/Value.html#as-java.lang.Class-), the `as` method may throw ClassCastException if the passed object does not fit into the supported cases; the [Invocable.getInterface](https://docs.oracle.com/javase/7/docs/api/javax/script/Invocable.html#getInterface(java.lang.Object,%20java.lang.Class)) however returns `null` in such case.
=> [NETBEANS-6171] Interpret ClassCast as "interface unsupported"

java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts
Some users of VSNetBeans complained that _Language server in VSCode is mixing contents from different workspaces._
> Sometimes I work with two checkouts of our repos, e.g. one on a brach that I'm currently actively working on, 
> and a second one to produce quick fixes, or to babysit a merge.
>
> If I open both workspaces at the same time, then the language server seems to mix up the symbols from 
> the two workspaces.
>
> ... searching for a class finds two copies. The second one (located in `src/...`) is the correct one from this workspace. 
> The first one (located in `~/git/.../...`) is from another workspace. In the second workspace it's the other way round 
> (i.e. the first one is correct and shows a project name, the second one shows a full path and is from the other workspace).
> …
=> Allow VSCode users to choose 'local' - e.g. per workspace userdir

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleAccess.java
Fix of a NPE reported internally:
```
java.lang.NullPointerExceptionjava.lang.NullPointerException
at org.netbeans.modules.debugger.jpda.truffle.access.TruffleAccess.getBreakpointInfos(TruffleAccess.java:460)
```
=> Fix of NPE in TruffleAccess.

enterprise/payara.tooling/nbproject/org-netbeans-modules-payara-tooling.sig, enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/data/JDKVersion.java, enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/data/StartupArgsEntity.java, enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/ServerTasks.java, enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/parser/JvmConfigReader.java, enterprise/payara.tooling/test/unit/src/org/netbeans/modules/payara/tooling/data/JDKVersionTest.java
Payara Platform 5.2021.8 support HotSwap Agent via DCEVM which is activated by jvm-options in domain.xml.
With the introduction of the HotSwap feature, JVM Options in domain.xml need to be filtered out based on the JVM name.
For e.g: In the following snippet Azul is the vendor name and Dynamic Code Evolution is the VM name both JVM options should be activated based on the Vendor or VM name.
````
<jvm-options>[Azul-1.8.0u222|1.8.0u260]-XX:+UseOpenJSSE</jvm-options>
<jvm-options>[9|]-Djdk.attach.allowAttachSelf=true</jvm-options>
<jvm-options>[Dynamic Code Evolution-11.0.10|]-XX:HotswapAgent=core</jvm-options>
<jvm-options>[Dynamic Code Evolution-11.0.10|]-Xlog:redefine+class*=info</jvm-options>
````
=> Filter jvm-options based on VM name

ide/css.editor/nbproject/project.properties, ide/css.editor/src/org/netbeans/modules/css/editor/indent/CssIndentTask.java, ide/css.editor/test/unit/data/testfiles/case005.less, ide/css.editor/test/unit/data/testfiles/case005.less.formatted, ide/css.editor/test/unit/data/testfiles/case006.scss, ide/css.editor/test/unit/data/testfiles/case006.scss.formatted, ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/indent/CssIndenterTest.java, ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/indent/LessIndenterTest.java, ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/indent/ScssIndenterTest.java
If not excluded, the braces are split into multiple lines and invalidated.
=> Exclude less (@{}) and scss (#{}) string interpolation from formatting

webcommon/web.clientproject/src/org/netbeans/modules/web/clientproject/ClientSideProjectConvertor.java
If package.json is a string (invalid format) a ClassCastException is
raised and not a ParseException. The ClassCastException should be
handled identically to the other fatal exceptions.
=> Handle invalid package.json only containing a single string

extide/gradle/netbeans-gradle-tooling/src/main/groovy/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.groovy, extide/gradle/src/org/netbeans/modules/gradle/GradleProjectErrorNotifications.java, extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java, extide/gradle/src/org/netbeans/modules/gradle/api/GradleConfiguration.java, extide/gradle/src/org/netbeans/modules/gradle/nodes/ConfigurationsNode.java, java/gradle.java/src/org/netbeans/modules/gradle/java/JavaSEProjectIconProvider.java
Slightly more than just disabling the warnings on java-platform Gradle projects.
Did some testing on the weekend including the test why api and some other configurations are not showing up in the UI.
Those are the configurations the users often use. It turned out that Gradle marks those configurations as non-resolvabe (canBeResolved property is false).
So I made some adjustments to let them displayed.
Before:
After:
=> [NETBEANS-5846] Minimal support of java-platfom Gradle projects.

java/java.hints/src/org/netbeans/modules/java/hints/bugs/Bundle.properties, java/java.hints/src/org/netbeans/modules/java/hints/bugs/Tiny.java, java/java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/Bundle_test.properties, java/java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/TinyTest.java
The "String.replaceAll(".", )" probable-bug inspection was limited to the '.' character and the `replaceAll` method.
This PR rewrites it to apply to more single-char Strings consisting of a single regex control character and to more methods which expect regexes.
examples:
```
"f.o.o".replaceAll(".",  "")
=>
"f.o.o".replaceAll("\\.",  "")
"f$o$o".split("$")
=>
"f$o$o".split("\\$")
str.replaceFirst("(", "[")
=>
str.replaceFirst("\\(", "[")
```
=> [jackpot] Rewrite "String::replaceAll with dot" inspection to apply to more cases and methods

nbbuild/antsrc/org/netbeans/nbbuild/GitBranchHash.java
Fix from an unmerged commit #3151.
=> Small improvement on GitBranchHash which is able to get at least the hash of a detached HEAD

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NetBeansRunSinglePlugin.java
This PR fixes typo introduced in #3326 that broke `runSingle` task, which is used by "run" or "debug" actions on a single file (a class with a psv main method).
=> Fixed typo: runSingle presence depends on runClassName property.

nbbuild/misc/prepare-bundles/src/main/java/org/netbeans/prepare/bundles/PrepareBundles.java
This is simple fix for the situation, when newer version of npm is used during building VSCode extension. It filters out .packe-lock.json from the files that needs a license.
=> [NETBEANS-6235] Build of vscode extension fails

ide/xml.retriever/test/unit/src/org/netbeans/modules/xml/retriever/impl/SecureURLResourceRetrieverTest.java
As @sdedic and @JaroslavTulach noticed the unittest fails and can't be fixed at this point in time:
https://github.com/chromium/badssl.com/issues/482
=> Deactivate broken xmlretriever test (client cert expired and a new one is not yet issued)

nb/ide.branding/build.xml, nb/ide.branding/o.n.swing.plaf/src/org/netbeans/swing/plaf/Bundle_nb.properties, nb/ide.branding/src/org/netbeans/modules/ide/branding/layer.xml
Switch to FlatLaf Light as default look and feel, and editor profile, for the IDE.  This is the simplest approach using nb/ide.branding, so keeps the existing defaults for the platform, and the laf used for the upgrader dialog.
Related to discussion at https://lists.apache.org/thread/9v3tlz8klqs93c1z6s0kvg03tr8w6kdx
=> Switch to FlatLaf Light as default look and feel for IDE

harness/nbjunit/src/org/netbeans/junit/NbTestCase.java, java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java, java/java.completion/test/unit/data/goldenfiles/org/netbeans/modules/java/completion/JavaCompletionTaskTest/1.8/afterAbstract.pass, java/java.completion/test/unit/data/goldenfiles/org/netbeans/modules/java/completion/JavaCompletionTaskTest/1.8/afterSealed.pass, java/java.completion/test/unit/data/goldenfiles/org/netbeans/modules/java/completion/JavaCompletionTaskTest/1.8/afterSealedClassName.pass, java/java.completion/test/unit/data/goldenfiles/org/netbeans/modules/java/completion/JavaCompletionTaskTest/1.8/finalClass.pass, java/java.completion/test/unit/data/org/netbeans/modules/java/completion/data/Sealed.java, java/java.completion/test/unit/src/org/netbeans/modules/java/completion/JavaCompletionTask115FeaturesTest.java
minor bugfix:
`contains(String)` was called on a `Set` containing `Modifier` enums - which is always false.
Although we can't use the two sealed enums directly since they are JDK 17+, they can be still queried via a little utility method.
Added auto completion tests for sealed class declaration.
=> fixed class modifier auto completion for sealed classes.

java/java.lsp.server/vscode/src/explorer.ts, java/java.lsp.server/vscode/src/extension.ts
When a JDK is switched, and the lang client is restarted, the old TreeViewService is still active as well as any handlers it hooked to the vscode. This PR adds unregistration/disposal of the service on Lang client stop.
=> Dispose/disconnect tree view after client stop.

java/java.hints.declarative/nbproject/project.xml, java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/Hacks.java, java/java.j2seplatform/nbproject/project.xml, java/libs.javacapi/external/binaries-list, java/libs.javacapi/external/nb-javac-jdk-17.0.1-ga-license.txt, java/libs.javacapi/nbproject/project.properties, java/libs.javacapi/nbproject/project.xml, java/libs.nbjavacapi/external/binaries-list, java/libs.nbjavacapi/external/nb-javac-jdk-17.0.1-ga-license.txt, java/libs.nbjavacapi/manifest.mf, java/libs.nbjavacapi/nbproject/project.properties, java/libs.nbjavacapi/nbproject/project.xml, nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
Run on JDK-8.  Try to invoke Go To Declaration on a class that comes from Java platform or a library jar. The following exception is thrown:
```
java.lang.NoSuchMethodError: com.sun.source.tree.CompilationUnitTree.getPackage()Lcom/sun/source/tree/PackageTree;
at org.netbeans.modules.java.j2seplatform.queries.DefaultSourceLevelQueryImpl.parsePackage(DefaultSourceLevelQueryImpl.java:203)
at org.netbeans.modules.java.j2seplatform.queries.DefaultSourceLevelQueryImpl.lambda$isModular$1(DefaultSourceLevelQueryImpl.java:148)
at java.util.Optional.orElseGet(Optional.java:267)
at org.netbeans.modules.java.j2seplatform.queries.DefaultSourceLevelQueryImpl.isModular(DefaultSourceLevelQueryImpl.java:147)
at org.netbeans.modules.java.j2seplatform.queries.DefaultSourceLevelQueryImpl.getSourceLevel(Defaul …
```
=> Use ToolProvider from libs.javacapi, not from bootclasspath

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java, java/java.lsp.server/vscode/src/extension.ts, java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementOpen.java, java/maven/src/org/netbeans/modules/maven/queries/MavenSourceJavadocAttacher.java
Computation of a type's `Location` is expensive. Especially for the types form library jars when their corresponding source jars have to be downloaded first. This PR prevents computation of the final `Location' for every type item displayed in the selection list; the final `Location` is computed lazily for the selected type item only.
=> LSP: attempt to speed up open type action.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchRequestHandler.java, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/test/suite/testutils.ts, java/maven/src/org/netbeans/modules/maven/newproject/TemplateUtils.java, java/maven/src/org/netbeans/modules/maven/runjar/RunJarPrereqChecker.java
For consistency reasons we execute project Run/Debug actions instead of file Run/Debug in VSCode. File-sensitive actions are provided as code lenses. Via project's Run/Debug actions users get consistent behavior.
Currently there was `mainClass` property set to `${file}` in VSCode's `launch.json`. We are changing `mainClass` property to be optional, it's not set in newly created `launch.json` and we're using `file` property set to `${file}` to get the context. `mainClass` allows to set a specific file as a context to Run/Debug. When not set, we use `file` to determine the current project to run Run/Debug on.
We need to adjust Maven projects to be able to Run/Debug without `mainClass` set. The project should know it's entry point. Currently, when you create a new Maven project from …
=> LSP + VSCode extension: Run/Debug via project actions.

groovy/groovy.editor/nbproject/project.xml
There has to be used new version of nbjavac.
=> [NETBEANS-6276] Groovy CC doesn't work on JDK 1.8

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NetBeansRunSinglePlugin.java, extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java, java/java.lsp.server/vscode/src/extension.ts
Code lens actions are run via `runDebug` in `extension.ts` and they use a special launch configuration that did not inherit the configuration from `launch.json`. This is why any additional properties set in `launch.json` were not applied. We merge the launch configuration in `mergeWithLaunchConfig()`.
Gradle project run/debug now applies environment variables set via `runEnvironment` project's property.
`NetBeansRunSinglePlugin` can be simplified now, the set of the environment variables is removed and we set `System.in` and `runWorkingDir` for all Java executions.
=> Merge the code lens actions with the launch config properties and adapt Gradle to apply env.

ide/db/apichanges.xml, ide/db/nbproject/project.properties, ide/db/src/org/netbeans/api/db/explorer/ConnectionManager.java, ide/db/src/org/netbeans/modules/db/explorer/ConnectionList.java, ide/db/src/org/netbeans/modules/db/explorer/action/MakePreferred.java, ide/db/src/org/netbeans/modules/db/explorer/node/ConnectionNode.java, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBCommandProvider.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeNodeRegistry.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeViewProvider.java, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/explorer.ts, java/java.lsp.server/vscode/src/extension.ts
This PR required an API change in `ConnectionManager` in the DB module - but IMHO quite beneficial, since the IDE code now can also use the 'preferred' connection for whatever features not originating from the DB Connection node. For example SQL embedded in Java / other code files may also benefit from the added API.
The LSP client may query the default connection and also set it - the value will be persisted by the NBLS.
=> LSP: Allow to specify default DB connection

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/PerfStatCompilationUnit.java
Groovy editor's internal performance counters override `final` groovy compiler's member field's value using reflection, which does not work on JDK17. These performance counters are likely to become obsolete so the easiest way how to avoid mostly harmless notification in the `message.log` is to log it only if the performance dumps are enabled.
// cc: @ppisl
=> Avoid spurious exception in log. Warn if perf counters are enabled on incompatible JDK

java/java.lsp.server/arch.xml, java/java.lsp.server/nbcode/integration/src/META-INF/services/org.openide.explorer.ExtendedDelete, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml, java/java.lsp.server/nbproject/project.properties, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/LspServerState.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchRequestHandler.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/DefaultDecorationsImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeNodeRegistryImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/TreeItemData.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/LspTemplateUI.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ProjectActionParams.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/protocol.ts
The following actions were enabled:
- PROJECTS (view caption):
- inline:  new project, collapse all 
- context: build workspace, clean workspace, run/debug workspace
- PROJECT (node):
- inline:  new from template, run/debug project
- context: clean project, build project, test project
- PACKAGE (node):
- inline:  new from template
- context: delete package
CLASS (node):
- context: delete class?
=> Added more actions to LSP Projects View

ide/parsing.indexing/apichanges.xml, ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/FileObjectCrawler.java, ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/FilteringIterable.java, ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/IndexabilityQuery.java, ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/IndexabilityQueryContextAccessor.java, ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/IndexabilitySupport.java, ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/RepositoryUpdater.java, ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/TimeStamps.java, ide/parsing.indexing/src/org/netbeans/modules/parsing/spi/indexing/IndexabilityQueryImplementation.java, ide/parsing.indexing/test/unit/src/org/netbeans/modules/parsing/impl/indexing/RepositoryUpdaterTest.java
This commit adds a query, that allows plugins to prevent files from
being indexed completely or by certain indexers.
One motivator for this is the JS indexer in combination with huge
node_modules directories. In the case of angular/typescript projects the
JS indexer does not help with development, as code assistence is
provided by the typescript LSP server. But the JS indexer is ran anyway
and created huge scan times and big indices. With these new hooks a
plugin could limit the indexing when an angular project is detected.
=> Allow plugins to exclude files from being indexed

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ui/refactoring.css, java/java.lsp.server/vscode/src/explorer.ts
Sometimes an error "Element with id 15 is already registered" was printed. During debugging, it seems that children are requested several times in a row:
```
[Trace - 2:22:10 PM] Sending request 'nodes/children - (12)'.
Params: {
"nodeId": 5
}
[Trace - 2:22:10 PM] Received response 'nodes/children - (12)' in 51ms.
Result: [
9
]
[Trace - 2:22:10 PM] Sending request 'nodes/info - (13)'.
Params: {
"nodeId": 9
}
[Trace - 2:22:11 PM] Received response 'nodes/info - (13)' in 87ms.
Result: {
"collapsibleState": 1,
"contextValue": "",
"iconUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAABHUlEQVR4XuWTQU7DMBBFc6PWMw7cp4GDJNykgitQVaikSLAB0TWCfVnAAhqxKGr8mRmnCNpIDUis+NLTeGzPH9lxkuT/aFCUOCimyPILDIozZEdTiRNs7mtVlk+k+FyKSxzmWlhasea2gTgFUR8sMcKSe5BnsO9hOL7ByegWx+MZhqNrG2v0lMKKE …
```
=> Maintain data identity for duplicit info requests

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/breakpoints/GroovyBreakpointFactory.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
1. When we get no ClassPath in `GroovyBreakpointFactory.java`, we suppose the file name for single-file execution.
2. Prevent from NPE when project is null in `WorkspaceServiceImpl.java`
3. `findProjectConfigurations` need to return the desired value and not wrap it in the Future.
=> Single file Groovy Run and Debug in VSCode.

java/java.lsp.server/vscode/package.json
When vscode starts with a folder that do not contains any nice files like `.java` or `.groovy`, the Apache NBLS extension does not activate at all ! Still the UI shows `Projects` and `Databases` views, but empty - as the relevant `TreeDataProvider`s are not registered yet.
This PR will just make appearance of those views depend on NBLS extension to become ready (it sets up a context variable).
=> Show Databases and Projects views only after NBLS extension activates.

ide/css.prep/src/org/netbeans/modules/css/prep/sass/SassCli.java
With default NetBeans modern sass implementations cannot be used, because it defaults to the unmaintained ruby-sass implementation, which supports the command line switch **--cache-location**.
There is a System property to switch that but it defaults to ruby sass. This PR just changes the default value, so most users can just use modern sass and the minority using ruby-sass can set the value to false expliciteley.
There is still an issue with the sourcemaps option, but until #1234 is sorted out, this PR will make Sass usable again for most users, which is IMHO priority.
=> Change nb.sass.libsass to TRUE, to fix broken SASS

platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/LFCustoms.java, platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/gtk/GtkLFCustoms.java, platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/metal/MetalLFCustoms.java, platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/nimbus/NimbusLFCustoms.java, platform/options.api/nbproject/project.properties, platform/options.api/src/org/netbeans/modules/options/OptionsPanel.java
Use default colors in options panel when GTK laf is used.
Tested in Ubuntu 20.04 with default theme. 
Before:
After:
=> Options panel use GTK default colors

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NetBeansRunSinglePlugin.java
When a Micronaut Gradle app is run, following message is printed:
```
> Task :run
Execution optimizations have been disabled for task ':run' to ensure correctness due to the following reasons:
- Property 'jvmArgumentProviders.$0' was implemented by the Java lambda 'org.netbeans.modules.gradle.tooling.NetBeansRunSinglePlugin$$Lambda$1154/0x00000008409ea840'. Reason: Using Java lambdas is not supported as task inputs. Please refer to https://docs.gradle.org/7.3.1/userguide/validation_problems.html#implementation_unknown for more details about this problem.
```
While this is not a severe issue, it's distracting and the user has a little chance to understand what this means.
We need to replace the lambda with an anonymous class in `NetBeansRunSinglePlugin` to get rid of the message.
=> Rewrite lambda to an inner class to prevent from Gradle warning about execution optimizations.

php/php.code.analysis/manifest.mf, php/php.code.analysis/nbproject/project.xml, php/php.code.analysis/src/org/netbeans/modules/php/analysis/parsers/PHPStanReportParser.java, php/php.code.analysis/test/unit/data/phpstan/phpstan-log-html-entities.xml, php/php.code.analysis/test/unit/src/org/netbeans/modules/php/analysis/parsers/PHPStanReportParserTest.java
https://issues.apache.org/jira/browse/NETBEANS-6315
- Escapes HTML entities in message from PHPStan report
Before - message on right side of Inspector does not show `<string>`:
After - message on right side is complete:
=> [NETBEANS-6315] Escape HTML entities in PHPStan report

java/java.lsp.server/vscode/src/explorer.ts, java/java.lsp.server/vscode/src/extension.ts
This PR fixes two bugs. First - call me an idiot, but I used just syntax-sugar conversion instead of `Number(x)` to convert item IDs (which are numeric) to numbers. I did not notice it during var inspection in the debugger (just '9' vs 9) ... therefore items were not matched and updated properly, the items were never found in the `treeData` Map.
Second is a race condition: sometimes, especially with lazy-initialized Nodes in NBLS, a query for Children started to initialize the Children, and so a certain `nodes/nodeChanged` could be received **before** the vscode even received the first `nodes/info` response for the node; the node change was then simply ignored. That results in dangling nodes, nodes like 'Please wait...' which are in the tree indefinitely etc.
The fix is to track those …
=> Really convert IDs to numbers to use with Map. Re-fetch items that have been marked as changed.

ide/editor.lib2/src/org/netbeans/modules/editor/lib2/highlighting/SyntaxHighlighting.java, ide/editor.util/src/org/netbeans/lib/editor/util/swing/DocumentUtilities.java, ide/textmate.lexer/src/org/netbeans/modules/textmate/lexer/SyntaxHighlighting.java
The `TokenHierarchy.isActive()` is not called with the associated Document's read lock, as can be seen from the stack trace in the associated issue.
This change adds read lock to `SyntaxHighlighting`, which makes `TokenHierarchy.isActive()` to be called with the read lock.
=> [NETBEANS-6312] Assure that TokenHierarchy is called with Document's read lock.

extide/gradle/src/org/netbeans/modules/gradle/loaders/DiskCacheProjectLoader.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleArtifactStore.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/loaders/DiskCacheProjectLoaderTest.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/loaders/testReloadProject.gradle
For detailed explanation, see [bug description](https://issues.apache.org/jira/browse/NETBEANS-6305). The fix is actually a workaround - the cached project structure/information is validated against global artifact cache. The cached info is rejected if the global artifact cache does not contain items that would have been present/updated if the current IDE instance had loaded the project fully and created the caches (both global and project).
A test is attached that demonstrates the issue, if [the validation call](https://github.com/apache/netbeans/pull/3375/files#diff-e0b2de3f6a585632d92c8419e75f246740dcb1f90a52b33e4a58147423b69bdbL45) is removed.
=> NETBEANS-6307: check global artifact cache, ignore per-project cached  structure if not consistent.

java/java.lsp.server/vscode/src/explorer.ts, java/java.lsp.server/vscode/src/extension.ts
This PR is rather intricate. It turned out that `vscode` is probably confused by aggressive change events fired from the NBLS. The PR attempts to buffer changes for nodes that are being just queried by vscode: if such a change is received, it is put aside. Once queries for the node (children, info) are resolved, a vscode node change will be fired for the node - which will probably result in an additional `getTreeItem` or `getChildren` call. 
With this queue in place, nodes seem to refresh properly.
I added some logging (now disabled by a constant in the code) - but logs to the Output channel of the NBLS extension: if the LSP trace is enabled at the same time, the LSP message traces are interleaved with the tree processing diagnostics. It's easier to find out what and when is happening.
=> Delay change events for node after the node's pending queries are resolved

java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/runConfiguration.ts
This PR introduces the Run Configuration view in the Explorer activity of the VS Code.
The Run Configuration view enables easy customizations of the currently selected Java 8+ launch configuration. The settings are persisted in context of the project/workspace.
=> Run Configuration UI for the Explorer view

java/java.lsp.server/nbcode/nbproject/platform.properties
The NBLS distribution contains a broken client-side project support: some modules are there, some are not, like HTML parser & co. Given the feature is not really used (vscode as the primary LSP client uses a different langserver for JS, Node) and it is broken anyway, I'd prefer to remove it form the NBLS distribution.
We can later add it back, but with all dependencies so that it really works. Now the client-side project errors out with an exception:
```
java.lang.IllegalArgumentException: No parser for mime type: text/html
at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.findMimeParser(DataObjectEnvFactory.java:78)
at org.netbeans.modules.parsing.api.ParserManager.findParser(ParserManager.java:374)
at org.netbeans.modules.parsing.api.ParserManager.parseWhenScanFinished(ParserManage …
```
=> Disable client-side projects and nodejs support.

java/java.lsp.server/arch.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/URITranslator.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/DefaultDecorationsImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeViewProvider.java, java/java.lsp.server/vscode/package.json
It turned out that simply o.n.api.project.Project 'cookie' exposed is not sufficient for presenting sensible actions. The PR makes some additional checks and adds `is:project` and `is:projectRoot` magic labels to LSP exported `contextValue`s.
Overview of changes made in LSP server:
- just physical folders - that is convertible to j.io.File are marked as `is:folder`. This prevents strange things as 'New from Template' on a folder in a JAR ;)
- `is:project` is placed on a Node that has `Project` in its Lookup, and also a `FileObject` that correspond to that project's root directory. Since there are some grouping nodes (i.e. Build Scripts) that **also** refer to the project root dir, there's an additional check that if a node represents a project root (implies a folder) then its immediate …
=> Various fixes of project / folder actions presence in vscode

ide/spi.editor.hints.projects/src/org/netbeans/modules/editor/hints/projects/settings/FileHintPreferencesProviderImpl.java, ide/spi.editor.hints.projects/src/org/netbeans/modules/editor/hints/projects/settings/OpenGlobalPreferencesImpl.java, ide/spi.editor.hints/apichanges.xml, ide/spi.editor.hints/manifest.mf, ide/spi.editor.hints/nbproject/project.properties, ide/spi.editor.hints/src/org/netbeans/modules/editor/hints/settings/friend/OpenGlobalPreferences.java, ide/spi.editor.hints/src/org/netbeans/spi/editor/hints/settings/FileHintPreferences.java, java/spi.java.hints/src/org/netbeans/spi/java/hints/ErrorDescriptionFactory.java
When selecting "Configure ... Hint" in the editor, when per project hints settings are in effect, the project settings should be open rather than the global settings.
=> Fixing the configure hint sub-fix to work more properly for per-project hint settings.

enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/admin/ServerAdmin.java, enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/IdeContext.java, enterprise/j2ee.api.ejbmodule/src/org/netbeans/modules/j2ee/api/ejbjar/Car.java, enterprise/j2ee.api.ejbmodule/src/org/netbeans/modules/j2ee/api/ejbjar/Ear.java, enterprise/j2ee.api.ejbmodule/src/org/netbeans/modules/j2ee/api/ejbjar/EjbJar.java, enterprise/j2ee.api.ejbmodule/src/org/netbeans/modules/j2ee/spi/ejbjar/CarImplementation.java, enterprise/j2ee.api.ejbmodule/src/org/netbeans/modules/j2ee/spi/ejbjar/EarImplementation.java, enterprise/j2ee.api.ejbmodule/src/org/netbeans/modules/j2ee/spi/ejbjar/EjbJarFactory.java, enterprise/j2ee.api.ejbmodule/src/org/netbeans/modules/j2ee/spi/ejbjar/EjbJarImplementation.java, enterprise/j2ee.common/src/org/netbeans/modules/j2ee/common/ui/BrokenServerSupport.java, enterprise/j2ee.common/src/org/netbeans/modules/j2ee/common/ui/NoSelectedServerWarning.java, enterprise/j2ee.dd.webservice/src/org/netbeans/modules/j2ee/dd/api/webservices/DDProvider.java, enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/api/client/DDProvider.java, enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/api/web/DDProvider.java, enterprise/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/EjbJarProvider.java, enterprise/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/api/EjbJarProjectGenerator.java, enterprise/payara.common/src/org/netbeans/modules/payara/common/ui/JavaPlatformsComboBox.java, enterprise/payara.eecommon/src/org/netbeans/modules/payara/eecommon/dd/loader/PayaraDDProvider.java, enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/admin/ServerAdmin.java, enterprise/web.jsf/src/org/netbeans/modules/web/jsf/api/JsfComponentUtils.java, ide/editor.deprecated.pre65formatting/src/org/netbeans/modules/editor/FormatterIndentEngine.java, ide/editor.plain.lib/src/org/netbeans/editor/ext/plain/PlainSyntax.java, ide/editor.plain.lib/src/org/netbeans/editor/ext/plain/PlainTokenContext.java, ide/xml.catalog.ui/src/org/netbeans/modules/xml/catalog/lib/StreamEnvironment.java, ide/xml.catalog.ui/src/org/netbeans/modules/xml/catalog/spi/CatalogDescriptor.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/entitygenerator/EntityMember.java, java/maven/src/org/netbeans/modules/maven/api/output/OutputUtils.java, platform/api.progress.nb/src/org/netbeans/api/progress/ProgressHandleFactory.java, platform/openide.loaders/src/org/openide/loaders/CreateFromTemplateAttributesProvider.java
Cleanup warnings related to improper deprecation annotation..
Like this..
[repeat] /home/bwalker/src/netbeans/platform/openide.options/src/org/openide/text/NbDocument$Colors.java:31: warning: [dep-ann] deprecated item is not annotated with @Deprecated
[repeat] public final class NbDocument$Colors extends org.openide.options.SystemOption {
[repeat]              ^
[repeat] 48 warnings
[copy] Copying 1 file to /home/bwalker/src/netbeans/platform/openide.options/build/classes
=> [NETBEANS-6337] - remove annotation warnings related to deprecating

webcommon/javascript2.editor/test/unit/data/testfiles/with/test01.js, webcommon/javascript2.editor/test/unit/data/testfiles/with/test01.js.testWith_01.occurrences, webcommon/javascript2.editor/test/unit/data/testfiles/with/test01.js.testWith_02.occurrences, webcommon/javascript2.editor/test/unit/data/testfiles/with/test01.js.testWith_03.occurrences, webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/JsTestBase.java, webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/JsWithFastTest.java, webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/JsWithTest.java
1) The tests, that rely on information from the JS classpath (stub
definitions fail if classpath scanning is still in progress, so this
change forces repository updates to happen and delay test running
until scanning is done.
2) Changes to test input cause golden files to be out of sync. Align
input and golden files to match.
Tests were not actives for travis or github as execution takes to long.
=> Fix html.angular, js2.editor, js2.nodejs and js2.requirejs tests

platform/core.windows/src/org/netbeans/core/windows/model/DefaultModeModel.java
Not every FileObject is backed by j.i.File, need to compute some (hopefully) sensible full path for all FileObjects.
=> [NETBEANS-5901] Handling of FileObjects not backed by j.i.File when sorting by full path is requested.

java/libs.javacapi/build.xml, java/libs.javacapi/nbproject/project.properties
- caused compiler errors since several javac versions were in cp (if the local copy is old)
- removed javac.source property since the module has no sources anyway
=> javac wrapper module should clean its "external" folder.

platform/api.search/src/org/netbeans/modules/search/BasicSearchForm.java, platform/api.search/src/org/netbeans/modules/search/PatternSandbox.java, platform/api.search/src/org/netbeans/modules/search/TextRegexpUtil.java, platform/api.search/src/org/netbeans/modules/search/matcher/DefaultMatcher.java, platform/api.search/src/org/netbeans/modules/search/matcher/FastMatcher.java, platform/api.search/test/unit/src/org/netbeans/modules/search/TextRegexpUtilTest.java
The search dialog (`ctrl+shift+F or ctrl+shift+H `) didn't support searching for multi-line Strings since it used the wrong matcher for the task when a multi-line String was provided.
Updated the UI too. Its now resizable and the combo box editors are now multi-line capable.
Dialog looks identical on first open:
but when the window is resized vertically:
=> Allow searching for multi-line Strings.

ide/lsp.client/src/org/netbeans/modules/lsp/client/Utils.java, ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/FoldManagerImpl.java, ide/lsp.client/test/unit/src/org/netbeans/modules/lsp/client/bindings/FoldManagerImplTest.java
Extracts FoldInfo list computation into a new method in order to be testable in unit tests. 
Adds some unit tests.
Introduces Utils.getEndCharacter(..) that gets last character index of given line.
Changes FoldInfo calculation in case of FoldingRanges endCharacter is NULL.
=> [NETBEANS-6328] avoid IllegalArgumentException in FoldManagerImpl

ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/FoldManagerImpl.java, ide/lsp.client/test/unit/src/org/netbeans/modules/lsp/client/bindings/FoldManagerImplTest.java
The LSP specification specifies for the startCharacter:
The zero-based character offset from where the folded range starts. If
not defined, defaults to the length of the start line.
In contrast to the specification the first character was choosen as the
start of the fold, hiding for example the function name.
=> Follow LSP specification for null value for startCharacter in FoldingRange

extide/gradle/src/org/netbeans/modules/gradle/GradleProject.java, extide/gradle/src/org/netbeans/modules/gradle/GradleProjectProblemProvider.java, java/java.hints/src/org/netbeans/modules/java/hints/infrastructure/JavaErrorProvider.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java, java/java.lsp.server/vscode/package.json
When a project problem is detected, there is no way to resolve it from within VSCode extension.
This PR introduces `java.project.resolveProjectProblems` command, which attempts to resolve the project problems and when they are not resolved, it displays the resolution error.
`JavaErrorProvider` displays a dull `error(0): null` message, which we change to `error(1): <line:column range>`
The gradle project needs to be adapted to provide the resolution error message.
=> Be able to resolve project problems in VSCode extension.

.travis.yml, nbbuild/travis/print-junit-report.sh
This should hopefully print a list of failed tests if a job fails and make reading the travis log about 20% less painful.
=> print simple junit report on travis job failure.

java/java.hints/src/org/netbeans/modules/java/hints/suggestions/Lambda.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
Do not produce CodeActions for errors with empty description as they prevents all CodeActions from displaying in VSCode client.
=> LSP: Do not produce CodeActions for errors with empty description.

cnd/cnd.editor/test/unit/src/org/netbeans/modules/cnd/editor/cplusplus/CLangFormatTestCase.java, cnd/cnd.lexer/test/unit/data/testfiles/apr_portable.h.txt, cnd/cnd.lexer/test/unit/data/testfiles/istream.txt, cnd/cnd.lexer/test/unit/src/org/netbeans/modules/cnd/lexer/CppFlyTokensTestCase.java, cnd/cnd.lexer/test/unit/src/org/netbeans/modules/cnd/lexer/CppLexerPerformanceTestCase.java, cnd/cnd.makeproject/build.xml
This one:
- Restores the C/C++ Samples.
- Passes cnd.lexer tests (includes new source from other ASF projects)
- Passes cnd.editor tests (ignores test with clang format not available through libclank now).
=> [cnd] small-1.4 makeproject samples, editor/lexer tests

cnd/cnd.remote/nbproject/project.xml, cnd/cnd.remote/test/unit/src/org/netbeans/modules/cnd/remote/fs/FullRemoteCodeModelTestCase.java, cnd/cnd.remote/test/unit/src/org/netbeans/modules/cnd/remote/fs/RemoteCodeModelTestCase.java, cnd/cnd.remote/test/unit/src/org/netbeans/modules/cnd/remote/full/FullRemoteBuildTestCase.java, cnd/cnd.remote/test/unit/src/org/netbeans/modules/cnd/remote/test/RemoteBuildTestBase.java, cnd/cnd.toolchain/test/unit/src/org/netbeans/modules/cnd/toolchain/api/ValidateRegistryTestCase.java, cnd/cnd/test/unit/src/org/netbeans/modules/cnd/test/CndCoreTestUtils.java
This adds more passing tests to the cnd cluster (cnd.remote, cnd, cnd.toolchain)
cnd.remote depended on "cnd.model.api", which we have not integrated in Apache NetBeans (to be replaced with LSP). Tests that required validating the model 
- FullRemoteCodeModelTestCase, 
- RemoteCodeModelTestCase, 
- FullRemoteBuildTestCase, 
- RemoteBuildTestBase
are modified accordingly dropping this dependency.
After this the cnd cluster should test properly (dlight cluster requires some extra care, though).
=> [cnd] small-1.5 More cnd tests

ide/dlight.nativeexecution/README-tests.txt, ide/dlight.nativeexecution/test/unit/data/cndtestrc, ide/dlight.nativeexecution/test/unit/data/testuserinfo
One can test the "dlight.nativeexecution" module doing real connections to a remote server. The tests do then real ssh and sftp connections to the server, and perform different tests.
This isn't documented elsewhere, this PR details what is needed to run these tests.
=> dlight.nativeexecution test documentation

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractLspInputOutputProvider.java, platform/openide.io/src/org/openide/io/BridgingIOProvider.java
The console is closed only when both standard and error outputs are closed.
Also a correct stream is referred in `BridgingIOProvider`.
=> LSP console IO is made more reliable, output is not lost now.

java/java.source.base/src/org/netbeans/modules/java/source/save/PositionEstimator.java
Prevents IllegalStateExceptions from CasualDiff caused by wrong estimated positions of certain ErroneousTrees in a syntactically broken source (where endPosition < startPosition).
=> Modified to prevent IllegalStateExceptions from CasualDiff.

.github/workflows/ensure-jdk8.yml, java/java.source.base/src/org/netbeans/modules/java/source/parsing/FileObjects.java, java/java.source.base/test/unit/src/org/netbeans/api/java/source/ClassIndexTest.java, java/java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/ClasspathInfoTest.java, java/java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/PartialReparseTest.java
Since #2761 we use `--release 8` consistently to compile NetBeans code except modules that need to change `-bootclasspath`. By specifying `-bootclasspath` to `javac` one disables `--release` and uses the actual API of the underlaying JDK. As we currently compile with JDK-11 that means API of JDK-11 and as [NETBEANS-6285](https://issues.apache.org/jira/browse/NETBEANS-6285) and its many duplicates show, it can cause problems.
The best way to shield us against that is to build on JDK-11 and test (at least something) on JDK-8. This PR adds new GitHub Action to do so. It [fails](https://github.com/JaroslavTulach/netbeans/runs/4726963523) on the CI as well as  locally:
Now we can fix the problem as outlined in [NETBEANS-6349](https://issues.apache.org/jira/browse/NETBEANS-6349).
=> [NETBEANS-6285] Shield against usage of JDK-11 API.

ide/projectui/src/org/netbeans/modules/project/ui/ProjectsRootNode.java, java/java.source.base/src/org/netbeans/api/java/source/ModificationResult.java, platform/openide.util/src/org/openide/util/RequestProcessor.java
How do you search for failures in Travis and GitHubActions runs? I search for `failed` like in `The test XYZTest failed`. However there are other, disturbing occurrences of that word in the test logs. There was [52 occurrences in a recent log](https://github.com/apache/netbeans/runs/4729484163). Here are three examples:
```
[junit] WARNING: Warning - project of class org.netbeans.modules.java.source.usages.TestSupport$TestProject in /home/runner/work/netbeans/netbeans/java/java.source.base/build/test/unit/work/o.n.m.j.s.u.S/sipwop/prj0 failed to supply a LogicalViewProvider in its lookup
```
```
[junit] SEVERE: Error in RequestProcessor org.netbeans.modules.editor.settings.storage.preferences.PreferencesImpl$1
[junit] org.openide.util.RequestProcessor$SlowItem: task failed due to: …
```
=> Avoid using word failed in non-fatal debug messages

cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPLiteDebugger.java, java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/breakpoints/JPDABreakpointsHandler.java
When submitting a breakpoint into a Java native image, we consult the list of source files from the executable to determine the correct destination file.
The breakpoint's file is resolved relative to the `sources` folder, which is expected to be the sibling of the executable file.
When the `sources` folder is not found, breakpoints are resolved to locations that do not exist in the executable.
To verify the correctness of file paths, we use a newly introduced `NIDebugger.listSources()` method.
=> Native image breakpoints work with shared libraries.

java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java, java/java.source.base/manifest.mf, java/java.source.base/src/org/netbeans/api/java/source/TreeUtilities.java, java/java.source.base/src/org/netbeans/modules/java/source/NoJavacHelper.java, java/java.source.base/src/org/netbeans/modules/java/source/indexing/JavaCustomIndexer.java, java/java.source.base/test/unit/src/org/netbeans/api/java/source/gen/TryTest.java, java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorkerTest.java, java/java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/JavacParserTest.java, java/java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/PartialReparseTest.java, java/java.source/src/org/netbeans/modules/java/source/JBrowseModule.java, java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/JackpotTrees.java, java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java
post nb-javac 17 on-by-default refactoring
- removed "get nb-javac" dialog and nb-javac checks
- removed sealed class workaround added in #3228
- trees cleanup after #3283 
- removes ByteBuddy interceptors and reflection code
- some SourceVersion related cleanup
=> nb-javac checks cleanup and dialog removal.

ide/utilities/src/org/netbeans/modules/utilities/Bundle.properties, ide/utilities/src/org/netbeans/modules/utilities/ReportNBIssueAction.java, nb/bugzilla.exceptionreporter/nbproject/project.properties, nb/bugzilla.exceptionreporter/src/org/netbeans/modules/bugzilla/exceptionreporter/Bundle.properties, nb/ide.branding.kit/nbproject/project.xml, nb/uihandler.exceptionreporter/nbproject/project.properties, platform/lib.uihandler/nbproject/project.properties, platform/uihandler/nbproject/project.properties
disabling the module does two things:
- removes the "Help us improve NetBeans" dialog which appears on second start (and counterpart in general options)
- and the exception reporter functionality (window -> ide tools -> exception reporter)
non of this worked anymore anyway as far as I can tell.
todo: travis might fail if it has a test config for it, we will see.
=> disabled uihandler modules (exception+statistics reporter).

ide/projectui/test/unit/src/org/netbeans/modules/project/ui/AppTemplate.java.template, java/maven/src/org/netbeans/modules/maven/resources/App.java.template, java/maven/src/org/netbeans/modules/maven/resources/AppTest.java.template, platform/api.templates/test/unit/src/org/netbeans/modules/templates/AppTemplate.java.template
The recently added new maven based java project templates use a formatting which is different to NetBeans' default formatting settings. I think they should be consistent to whatever the default formatter is configured with.
(had to fix multi-line search and replace first before i could find the templates :) see https://github.com/apache/netbeans/pull/3393)
=> Formatted the templates to be inline with the default java formatting.

nbbuild/templates/projectized.xml
Add binaries.repos property to downloadbinaries call in projectized.xml. This was accidentally left out in a #2710 Amongst other things, this helps with testing libraries only in local .m2 cache.
Tiny fix cherry picked from something else I was working on which I'm rewriting.
=> Add binaries.repos property to downloadbinaries call in projectized.xml.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbSourceProvider.java
The Path can be treated as an URI on UNIX, but not on Windows. Paths starting with the drive letter are not valid URIs, this is why we need to convert the Path to URI and then to String to get a valid URI String representation.
=> Convert source path to URI String.

java/maven/src/org/netbeans/modules/maven/execute/cmd/ShellConstructor.java, java/maven/src/org/netbeans/modules/maven/options/MavenSettings.java, java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.java
added minimal support for https://github.com/mvndaemon/mvnd
maven home has the following layout:
```
bin/mvn
lib/*.jar
```
while mvnd home looks like:
```
bin/mvnd
mvn/  <- bundled maven home
```
This PR allows users to set a mvnd home as a maven home, NetBeans will then use mvnd and also be able to query the maven version from the bundled maven home.
did a little bit of manual testing and it seems that everything is working fine.
potentially related jira issue:
https://issues.apache.org/jira/browse/NETBEANS-4746
=> maven daemon support

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ChangeMethodParametersRefactoring.java
ChangeMethodParametersRefactoring should not allow for refactoring library classes.
=> LSP: Do not refactor library classes.

java/java.mx.project/build.xml
@jlahoda reported that the `ant -f java/java.mx.projects test` is failing on subsequent executions - because the `mx build` is executed on 1st run and not then. This PR changes the build script to invoke `mx build` everytime `ant test` is invoked.
=> Always call mx build before running the java.mx.projects tests

java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
An attempt to fix failing `ServerTest` from lsp on Travis CI, job `Test Java modules with nb-javac on Java 8`.
I've found out that the test probably catches a wrong process: at least on local, there was also indexing and some other processes going on, so the captured cancellation token might represent a different task than the compilation one.
I've rewritten the test so it does not rely on Maven, the mocked LSP client captures just the specific command's progress. The test now verifies that a cancel instruction from the LSP client will reach the appropriate `Cancellable` instance in the LSP server  - but nothing more; the previous version could eventually verify that a build can be cancelled.
=> Simplified cancelHandle test.

nbbuild/travis/print-junit-report.sh
This is a follow-up to #3403 -- I've noticed that the `xmllint --xpath '//testsuite/testcase[./failure]/@name' $file | cut -f2 -d '='`  only selects the 1st failed test, in case there are more failed cases in the testsuite.
During last hunt for a CI-failing test (that did not fail on local at all), I've also missed stderr/out for the failed suite. And also the actual assert stacktrace, since not all asserts have String message, the stacktrace can help to identify the exact failure.
Now the output is as follows:
```
=================== JUnit Report Summary / failed tests ===================
org.netbeans.modules.java.lsp.server.protocol.ServerTest
failed: testCancelProgressHandle
failed: testAnnotationCompletion
org.netbeans.modules.java.lsp.server.UtilsTest
failed: testEncode2JSON
errored: …
```
=> Better report of failures, append stderr/out.

enterprise/glassfish.eecommon/src/org/netbeans/modules/glassfish/eecommon/api/Utils.java, enterprise/j2ee.sun.ddui/src/org/netbeans/modules/j2ee/sun/share/configbean/templates/SunDDVisualPanel.java
This is a bug fix PR that fixes the creation of `glassfish-web.xml` deployment descriptor.
**Issue 1:**
If the server is not assigned to the project then glassfish-web.xml path is incorrect.
- Server attached then descriptor path: webapp/WEB-INF/glassfish-web.xml
- Server is not attached then the descriptor path: webapp/glassfish-web.xml
Fixed by checking the relative path of standard DD `web.xml`.
**Issue 2:**
Old Java EE and J2EE `glassfish-web.xml` templates no more exist and check for WebApp version 4.0 not added to `getSunDDFromProjectsModuleVersion` which skips the creation of `glassfish-web.xml`.
Fixed by returning the template `org-netbeans-modules-glassfish-eecommon-ddtemplates-java_ee/glassfish-web.xml`.
=> Fixes creation of a Glassfish deployment descriptor

java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteSources.java
Certain [mx](http://github.com/graalvm/mx) projects define libraries with `path()` relative to the suite location . So far the value of `MxLibrary.path()` has been ignored for regular (non-JDK) libraries. This PR checks the value and resolves it relatively to the root of the suite.
CCing @gilles-duboscq, @ansalond, @Ondrej-Douda
=> Honor MxLibrary.path() if specified

java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/Condition.java, java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintsParser.java, java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/MethodInvocationContext.java, java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/conditionapi/Variable.java, java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintsParserTest.java
I forgot to add a commit to https://github.com/apache/netbeans/pull/3395
This is the actual support of int literals for rule conditions - the rule API of part 1 alone won't do anything.
sorry!
=> [jackpot] Add sourceVersion(int) to rule file utils and deprecate enum variant. (part 2)

ide/db.sql.editor/src/org/netbeans/modules/db/sql/analyzer/SQLStatementAnalyzer.java, ide/db.sql.editor/src/org/netbeans/modules/db/sql/editor/completion/SQLCompletionProvider.java, ide/db.sql.editor/src/org/netbeans/modules/db/sql/editor/completion/SQLCompletionQuery.java, ide/db/apichanges.xml, ide/db/nbproject/project.properties, ide/db/src/org/netbeans/api/db/sql/support/SQLIdentifiers.java, ide/db/test/unit/src/org/netbeans/api/db/sql/support/SQLIdentifiersTest.java
This allows autocompletion to be possible when no connection is yet established.
This is a clean PR based on #2820
=> [NETBEANS-189] Updates for Sql autocomplete and [NETBEANS-5831] Create a SQL Standard Quoter for Use with Connectionless Cases

java/java.lsp.server/vscode/src/extension.ts
All actions to run/debug tests available in Test Explorer fail when no source is opened in editor with the message `Variable ${file} can not be resolved. Please open an editor.`. This is an attempt to fix that.
=> VSCode: Cannot run tests via when no file is opened in editor.

platform/libs.flatlaf/external/binaries-list, platform/libs.flatlaf/external/flatlaf-2.0-license.txt, platform/libs.flatlaf/nbproject/project.properties, platform/libs.flatlaf/nbproject/project.xml
Update FlatLaf to v2: https://github.com/JFormDesigner/FlatLaf/releases/tag/2.0
There are (nearly) no visual differences compared to previous used version, except the slightly changed [check boxes and radio buttons](https://github.com/JFormDesigner/FlatLaf/pull/414).
The main benefits of FlatLaf v2 for NetBeans are the reworked [core themes](https://github.com/JFormDesigner/FlatLaf/pull/390) (easier changing colors), the possibility to [change the accent color](https://github.com/JFormDesigner/FlatLaf/pull/375) and the [FlatLaf Theme Editor](https://www.formdev.com/flatlaf/theme-editor/). This should it make it relative easy to change colors/style of the light and dark themes to differentiate more from IntelliJ IDEA look.
E.g. adding following to …
=> Update FlatLaf from 1.6.1 to 2.0

enterprise/payara.common/src/org/netbeans/modules/payara/common/LogViewMgr.java, enterprise/payara.common/src/org/netbeans/modules/payara/common/StartTask.java
This PR fixes the log formatting issue (prepends **|#]** end of the line) by using the `LogFileFilter` which accepts the log in the following format:
````
[#|
2008-07-20T16:59:11.738-0700|
INFO|
Payara10.0|
org.jvnet.hk2.osgiadapter|
_ThreadID=11;_ThreadName=Thread-6;org.glassfish.admin.config-api [1794];|
Started bundle org.glassfish.admin.config-api [1794]
|#]
````
=> NETBEANS-3042 Fixes Payara Server log formatting issue

ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java
Seems sensible to not run the LSP servers for diff windows. There does not seem to be a very clean way, so just looking at the directory names.
=> [NETBEANS-5565] Disable running LSP servers for VCS diffs.

enterprise/websvc.metro.lib/external/binaries-list, enterprise/websvc.metro.lib/external/metro-2.4.8-license.txt, enterprise/websvc.metro.lib/nbproject/project.properties, enterprise/websvc.metro.lib/src/org/netbeans/modules/websvc/metro/lib/Bundle.properties, enterprise/websvc.metro.lib/src/org/netbeans/modules/websvc/metro/lib/metro.xml
Notes:
- Bug fix release
- Integrate santuario 2.1.7 and its dependencies
- Support for JDK 11/17
- Support for JPMS
- It is fully binary compatible with previous releases of the project Metro released by Oracle.
Testing:
- Verify successfull execution of unit tests for module 'websvc.metro.lib'
- Verify successfull execution of libraries and licenses Ant test
- Successfully create JAX-WS Web Service, deploy it and consume it with a Java SE Application
as per documentation https://netbeans.org/kb/docs/websvc/jax-ws.html
[Metro Web Page](https://projects.eclipse.org/projects/ee4j.metro)
=> [NETBEANS-6394] - Upgrade Metro from 2.4.4 to 2.4.8

ide/core.multitabs.project/nbproject/project.properties, ide/core.multitabs.project/src/org/netbeans/core/multitabs/project/ProjectSupportImpl.java, platform/core.multitabs/src/org/netbeans/core/multitabs/impl/ButtonPopupSwitcher.java, platform/core.multitabs/src/org/netbeans/core/multitabs/impl/ProjectColorTabDecorator.java, platform/core.multitabs/src/org/netbeans/core/multitabs/impl/ProjectSupport.java, platform/core.multitabs/src/org/netbeans/core/multitabs/impl/TabLayoutManager.java
issue:
1) tools -> options -> appearance -> doc tabs -> check sort opened docs by project
2) open some files, open the tab switcher popup on the upper right corner of the editor
3) you will notice first open does not group by projects as requested
4) open it again... should work now
fix for document switcher popup not grouping by project on first use:
- file owner query is now a blocking opperation with timeout
- under normal conditions the query returns a result right away
- if it doesn't for whatever reason it won't block the EDT due to the timeout
- fallback is the regular tab list
- it fixes the issue as side effect + avoids repaint flickering of the original impl
=> [NETBEANS-5209] Document switcher popup not grouping by project on first use.

java/refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/RenameTransformer.java, java/refactoring.java/test/unit/src/org/netbeans/modules/refactoring/java/test/RenameTest.java
see https://issues.apache.org/jira/browse/NETBEANS-4274
=> [NETBEANS-4274] fix refactoring of class member when a new name is the same as the name of a local variable

ide/libs.svnClientAdapter.javahl/external/adapter-javahl-1.14.0-license.txt, ide/libs.svnClientAdapter.javahl/external/binaries-list, ide/libs.svnClientAdapter.javahl/external/javahl-1.14.0-license.txt, ide/libs.svnClientAdapter.javahl/nbproject/project.properties, ide/libs.svnClientAdapter.javahl/nbproject/project.xml, ide/libs.svnClientAdapter.javahl/src/org/netbeans/libs/svnclientadapter/javahl/JavaHlClientAdapterFactory.java, ide/libs.svnClientAdapter/external/adapter-base-1.14.0-license.txt, ide/libs.svnClientAdapter/external/binaries-list, ide/libs.svnClientAdapter/nbproject/project.properties, ide/libs.svnClientAdapter/nbproject/project.xml
Well, let's see if we could just update to SubVersion 1.14 on JavaHL.
Also made the SvnClientAdapterFactory so it would be easier to re-implement the SvnKit adapter, whoever would do that.
I'd also like to test if the current (1.14.0) JavaHL would also work with version 1.13 (Ubuntu 20.04) and 1.9 (Ubuntu 18.04) as well.
=> Updated Subversion support to 1.14.0

java/java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertToVarHint.java, java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertToVarHintTest.java
Fix #3466 do not provide hint to convert type to var for method references.
=> [#3466]  do not show Convert Type to Var hint for method references

java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
After using code completion for e.g. `System.out`, a syntax error due to unfinished statement is usually reported. At the same time VSCode client asks for all available CodeActions (Hints) at the current line. One of the hints offers creating a static import for `System.out` and therefore a diff computation for such change touches the `ErroneousTree` representing the unfinished statement. Change to the `CasualDiff` was necessary to correctly handle this situation.
=> LSP: java.source.save.CasualDiff: Illegal values after using CodeCompletion.

extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java, extide/gradle/src/org/netbeans/modules/gradle/ProjectTrust.java, extide/gradle/src/org/netbeans/modules/gradle/cache/ProjectInfoDiskCache.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/DiskCacheProjectLoader.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleProjectLoaderImpl.java, java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImpl.java, java/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImplTest.java
This PR attempts to fix gradle test suite that is randomly failing just on CI. The root cause is that obviously I've written the test wrong ;) the original idea was to test what will happen if:
- the project is trusted
- it has been compiled, closed, IDE restarted
- the project is opened again.
Since I didn't want to bring all the NbModuleSuite machinery, the test just moved the original project, created a copy == new `FileObject` and opened the project again. New FileObject means new Project.
But some Gradle caches rely on `j.io.File`, not FileObjects, so [at this point](https://github.com/apache/netbeans/blob/master/java/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImplTest.java#L248) the `prj2` was a new instance, but its `GradleFiles` key into …
=> Fix for testPreTrusted gradle test failing on CI

extide/gradle/src/org/netbeans/modules/gradle/loaders/AbstractProjectLoader.java, extide/gradle/src/org/netbeans/modules/gradle/spi/newproject/TemplateOperation.java
Well, in this case the isGradleProjectLoaded() and the getGradlePorject() in NbGradleProjectImpl does not really agree, if the project is only initialized with a FALLBACK grade project. That would result infinite nesting at [AbstractProjectLoader:74](https://github.com/apache/netbeans/blob/6146b70dd3d1b2a269f934c5a457b1aa876ceb88/extide/gradle/src/org/netbeans/modules/gradle/loaders/AbstractProjectLoader.java#L74)
Strangely it did not cause problems elsewhere so far. This fix may/may not be ported to NB13. @sdedic please evaluate what would happen with this change. (I keep this one on master for the time being).
I know the main reason of this change to load the info from disk cache if that would exists. A better solution would have been to get the Disk cache loader give back better than …
=> [NETBEANS-6117] Fix Gradle project loading in template operations.

ergonomics/ide.ergonomics/javafx.properties
as discovered on the dev-list, the "Java Frontend Application" wizzard is trying install/load the old nb-javac plugin.
This should fix it. (tested it once as described on the mail to verify)
@neilcsmith-net ping
=> javafx ide.ergonomics config should not try to load the old nb-javac.

extide/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java
Fixing another fallout of disabled custom tasks in the IDE UI. ActionToTaskUtils::isActionEnabled always reports the `Run Gradle / Tasks..` action in project menu as disabled, so the action does nothing.  Switch to using custom prefix for name as in TaskNode actions.
I initially used a hidden action name checked in ActionToTaskUtils, but then noticed that the working version of this in the navigator just uses the custom prefix.
=> [NETBEANS-6323] Fix Gradle popup menu Tasks.. action not working.

platform/api.search/src/org/netbeans/modules/search/BasicSearchForm.java, platform/api.search/src/org/netbeans/modules/search/BasicSearchProvider.java, platform/api.search/src/org/netbeans/modules/search/Bundle.properties, platform/api.search/src/org/netbeans/modules/search/PatternSandbox.java, platform/api.search/src/org/netbeans/modules/search/ui/ShorteningCellRenderer.java
https://github.com/apache/netbeans/issues/3487
with this PR applied the following should be possible again:
1. press CTRL+SHIFT+H (or F)
2. type to enter search string
3. press ENTER to trigger search
(no mouse required)
which should be to my knowledge EXACTLY as it was before.
=> search/replace dialog: set shift+enter as line break and add multi-line info message.

java/maven/src/org/netbeans/modules/maven/TestChecker.java, java/maven/src/org/netbeans/modules/maven/execute/DefaultReplaceTokenProvider.java
When editing JUnit class of integration test, I expect "Test File", "Debug Test File", "Run Focused Test Method" or "Debug Focused Test Method" to run "integration-test.single" or "debug.integration-test.single" actions instead of "test.single" or "debug.test.single".
The goal of this feature is to run integration test during integration-test phase and so after pre-integration-test.
=> failsafe:integration-test from contextual menu

platform/api.search/src/org/netbeans/modules/search/matcher/BufferedCharSequence.java
With an empty file the BufferedCharSequence fails to be initialized:
```
java.lang.IllegalArgumentException: Buffer size <= 0
at java.base/java.io.BufferedInputStream.<init>(BufferedInputStream.java:207)
at org.netbeans.modules.search.matcher.BufferedCharSequence$Source.initStreams(BufferedCharSequence.java:562)
Caused: java.io.IOException
Caused: org.netbeans.modules.search.matcher.BufferedCharSequence$SourceIOException
at org.netbeans.modules.search.matcher.BufferedCharSequence$Source.initStreams(BufferedCharSequence.java:570)
at org.netbeans.modules.search.matcher.BufferedCharSequence$Source.<init>(BufferedCharSequence.java:494)
at org.netbeans.modules.search.matcher.BufferedCharSequence.<init>(BufferedCharSequence.java:145)
[catch] at …
```
=> Ensure BufferedInputStream is not initialized with a buffer size of 0

ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java, ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/CompletionProviderImpl.java, ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/SemanticHighlight.java, ide/textmate.lexer/src/org/netbeans/modules/textmate/lexer/resources/fontsColors.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
Trying to use the semantic highlighting in https://github.com/apache/netbeans/pull/1475, I've found a few bugs in the handling of the LSP semantic highlighting (and also a bug in the LSP client code completion update to a new LSP4J version). This patch should be fixing that. If possible, it would make sense to me to put it into NB 13.
=> Fixes to LSP client/server related to semantic highlighting.

.gitignore, nbbuild/antsrc/org/netbeans/nbbuild/ReleaseJsonProperties.java, nbbuild/build.xml, nbbuild/rat-exclusions.txt
Cache netbeansrelease.json in nbbuild/ - use -Dneedjsondownload=true to force update.
Write netbeansrelease.json to same location in source release to ensure source builds not affected by future changes to file in repository.
Squashed and tidied up version of #2421 by @ebarboni for merging to delivery.  Didn't want to force push to that branch without consent and need to get in for rc2.
Should fix #3456
=> Cache netbeanrelease.json for offline builds and source releases.

.travis.yml, java/java.lsp.server/build.xml, java/java.lsp.server/vscode/package-lock.json, java/java.lsp.server/vscode/package.json
Updating `vsce` to the 2.6.4 version to prevent security vulnerabilities reported during VSCode extension build.
=> Updating vsce to the 2.6.4 version.

ide/html/src/org/netbeans/modules/html/templates/html.html, ide/html/src/org/netbeans/modules/html/templates/xhtml.xhtml
Using the New from Template... action in a Micronaut / Gradle project to create a new HTML page results in an invalid html:
```
The following has evaluated to null or missing:
==> doctype  [in template "Templates/Other/html.html" at line 21, column 3]
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----
----
FTL stack trace ("~" means nesting-related):
- Failed at: ${doctype}  [in template "Templates/Other/html.html" at line 21, column 1]
----
<html> …
```
=> New From Template creates an invalid HTML page

platform/libs.flatlaf/external/binaries-list, platform/libs.flatlaf/external/flatlaf-2.0.1-license.txt, platform/libs.flatlaf/nbproject/project.properties, platform/libs.flatlaf/nbproject/project.xml
Unfortunately there is a memory leak in FlatLaf 2.0, which is fixed in 2.0.1.
The memory leak is in UI delegates for components `JPanel`, `JSeparator` and `JToolBar.Separator`.
There is always a reference from a static hash map to the **last created component** of that type.
So if e.g. a dialog (that uses `JPanel`) is closed, it can not released until a new `JPanel` is created somewhere else...
Memory leak issue: https://github.com/JFormDesigner/FlatLaf/issues/471
=> Update FlatLaf from 2.0 to 2.0.1

enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/plugin/Constants.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/Bundle.properties, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/DeployOnSaveManager.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroActionsProvider.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroExecutionChecker.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroPropertiesPanel.form, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroPropertiesPanel.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/MicroPropertiesPanelProvider.java, enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ReloadAction.java
This is a feature PR to enable Hot Deploy support to the Payara Micro application.
Follow the below steps to run the Payara Micro Application with the Hot Deploy feature. For more details about usage: https://docs.payara.fish/community/docs/documentation/ecosystem/netbeans-plugin/payara-micro.html
- Create the Payara Micro project via NetBeans's Main Menu > New Project > Java with Maven > Payaara Micro Appliaction
- Check the Hot Deploy option from Payara Micro Project Properties > Payara Micro section
- Run the Payara Micro application 
- Modify and save the source
- Application instance should be reloaded with the updated log in the output console.
=> Payara Micro Hot Deploy support in Apache NetBeans

java/java.lsp.server/vscode/src/extension.ts
VSNetBeans currently detects installation of MS Java ext pack and informs user it disables some services of it, code lenses and code completion. See [extension.ts:284](https://github.com/apache/netbeans/blob/f9c75266d97f86c4ae7eaa214ee31bb6164a283e/java/java.lsp.server/vscode/src/extension.ts#L284):
```js
conf.update('java.test.editor.enableShortcuts', false, false).then(() => {}, disablingFailed);
conf.update('java.debug.settings.enableRunDebugCodeLens', false, false).then(() => {}, disablingFailed);
```
This PR changes the behavior to more politely coexist with M$ Java extension. It asks the user to disable one of the extensions manually.
=> [NETBEANS-6384] Detect another Java support ext and recommend to Disable one.

profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/CacheDirectory.java, profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HeapFactory.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/HeapFragmentWalker.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/HeapWalker.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/HeapWalkerManager.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/OverviewController.java, profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/ui/OverviewControllerUI.java
I've created a simple library to generate `.hprof` files: [HeapDump](https://www.graalvm.org/tools/javadoc/org/graalvm/tools/insight/heap/HeapDump.html). It follows the [Java Profiler Heap Dump Format](http://hg.openjdk.java.net/jdk6/jdk6/jdk/raw-file/tip/src/share/demo/jvmti/hprof/manual.html) specification, however it allows more than regular JVMs do. Regular JVMs always dump the whole heap in a single round, while the [HeapDump](https://www.graalvm.org/tools/javadoc/org/graalvm/tools/insight/heap/HeapDump.html) allows one to generate _multiple segments_.
There already is support for reading these multisegment files in the Apache NetBeans Profiler library - it just isn't exposed in the heapwalker UI. This PR fixes that. The fix isn't "fancy", but it does its job. When an additional …
=> Exposing simple UI action to open next segment of a heap dump

harness/apisupport.harness/release/run.xml, nbbuild/build.xml
When using Java 9+ for debugging/running NetBeans from NetBeans on Windows,
then the 64-bit architecture of the JVM was not detected correctly and
`netbeans.exe` was used instead of `netbeans64.exe` to launch NetBeans.
This affects not only NetBeans core development, but also NetBeans module development.
This PR detects 32-bit JVMs and otherwise defaults to 64-bit.
See https://lists.apache.org/thread/5v5gb40tj3t4y06qtzxhjncowtm290t1
=> build.xml and run.xml: fixed detection of 64 bit architecture for Java 9+ (on Windows)

ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/RepositoryUpdater.java, java/junit.ui/src/org/netbeans/modules/junit/ui/actions/TestClassInfoTask.java
This is an attempt to fix the performance problem found while trying to open and index larger mx based project (GraalVM's Truffle). Because of an EmbeddingIndexer registered for the `text/x-java` mime type (`TestMethodFinderImpl`), thousands of the `javac` compiler instances are created to index the project sources (one instance per source root via `JavaCustomIndexer` and instance per source/indexable via `RepositoryUpdater.indexEmbeddings`.
This change tries to parse all sources/indexables under a source root as a group while running EmbeddedIndexers. Is saves thousands of the `javac` instances (only two instances per source root are created - one via `JavaCustomIndexer`, the second via `RepositoryUpdater.indexEmbeddings`) and approximately 20% of indexing time for the Truffle mx …
=> Parse Indexables under a source root as a group while running EmbeddedIndexers

java/maven/src/org/netbeans/modules/maven/NbMavenProjectImpl.java, java/maven/src/org/netbeans/modules/maven/classpath/RuntimeClassPathImpl.java, java/maven/src/org/netbeans/modules/maven/classpath/TestRuntimeClassPathImpl.java
I found the cause for #3526  : the implementation was changed in [bd4fd0e](https://github.com/apache/netbeans/commit/bd4fd0e4f6f323c458869ca4d77f6efd8b24f012#diff-d217c6a1644bb679cd1327c9fb77e539735b405f6874f62760a7522bda248172R54) -- the delegated-to implementation behaves differently depending on if the configured directories exist.
I fixed the `getSourceRoots` impl to always return URIs that end with "/". I found out that there's an API method `FileUtilities.convertStringToUri` which behaves this way which is not sometimes (always ?) preferred. As it is just before RCs, I don't want to add another API method, so I left a note in the code instead & will keep the issue for myself to finish after NB13 release is done to avoid different content in `delivery` and `master`.
- Maybe I can …
=> #3526: Retain traling / for non-existing directories.

java/java.project.ui/src/org/netbeans/modules/java/project/ui/ExtensionAndImplementationVisualPanel.java
workaround for #3511 lets trade a big bug against a small bug to improve the situation :)
commit msg:
- this is not a clean fix, it only improves the situation by making the
wizzard actually usable
- logic should not use Class.forName since it doesn't know anything
about the opened projects or used JDKs
- proper fix would either require calling ElementHandle.resolve off
EDT and getting CompiltaionInfo from somewhere or to add modifiers
to ElementHandle itself which would be a fairly large change
=> [#3511] workaround for extends/implements panel not showing any results.

php/php.dbgp/src/org/netbeans/modules/php/dbgp/DebugSession.java, php/php.dbgp/src/org/netbeans/modules/php/dbgp/SessionManager.java
- https://issues.apache.org/jira/browse/NETBEANS-6177
- Related to NETBEANS-5080
- Use the `canceled` field instead of `detachRequest.set(true)` because
the stop command is not sent in `sendStopCommand()` if `detacheRequest` is `true`
=> [NETBEANS-6177] Fix an issue the stop command is not sent

ide/libs.jaxb/external/binaries-list, ide/libs.jaxb/external/jaxb-2.3.5-xjc-license.txt, ide/libs.jaxb/external/jaxb-impl-2.3.5-license.txt, ide/libs.jaxb/nbproject/project.properties, ide/libs.jaxb/src/org/netbeans/libs/jaxb/Bundle.properties, ide/libs.jaxb/src/org/netbeans/libs/jaxb/jaxb.xml
Library notes:
- Bug fixes and improvements
- Tests fixes
- Updated dependencies
- Code cleanup
- Remove use of soon to be deleted Java APIs. See [PR-1463](https://github.com/eclipse-ee4j/jaxb-ri/pull/1463/files)
Testing:
- Verify successfull execution of unit tests for modules `/ide/libs.jaxb` & `/ide/xml.jaxb.api`
- Verify successfull execution of `ant verify-libs-and-licenses`
- Successfully create project that bind WSDL to Java with JAXB as per [NetBeans Documentation](https://web.archive.org/web/20201028123508/https://netbeans.org/kb/74/websvc/jaxb.html)(Used web.archive.org)
- Verify that the files generated used the Eclipse implementation of JAXB
[JAXB Web Page](https://projects.eclipse.org/projects/ee4j.jaxb-impl)
[Release …
=> [NETBEANS-6410] - Upgrade JAXB from 2.3.3 to 2.3.5

extide/gradle/src/org/netbeans/modules/gradle/GradleProjectProblemProvider.java, extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java, extide/gradle/src/org/netbeans/modules/gradle/layer.xml, extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleProjectLoaderImpl.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java, ide/projectui/src/org/netbeans/modules/project/ui/problems/BrokenReferencesCustomizer.form, ide/projectui/src/org/netbeans/modules/project/ui/problems/BrokenReferencesCustomizer.java, java/maven/src/org/netbeans/modules/maven/layer.xml
I have noticed that an exception thrown from Gradle script execution is slightly mis-presented
- a notification is fired, project is marked as having errors
- the "Project Problems" dialog does not appear (sometimes)
- "Do priming build" fixable problem appears - but can't fix anything as the script is broken
- The **real** problem does not appear in the "Project problems" dialog
The notification itself is mangled: part of the text is duplicated (see the picture). 
I have tried to change that. I added some exception stack processing to ignore / reorder the information; the resulting notification is visible here:
In addition, I have change the condition for replacing loaded projects, so that 'problematic' project instance is retained - then the project infrastructure starts to work …
=> Improve Gradle projects problem reporting.

nbbuild/antsrc/org/netbeans/nbbuild/Arch.java
There is too many occurrences of `[arch] Resolved to embedded DTD` in javadoc build log. Information value of this line is low, so removing to make log more concise and readable.
=> Remove unnecessary log entry from javadoc build

apisupport/apisupport.wizards/src/org/netbeans/modules/apisupport/project/ui/wizard/javahint/NewJavaHintIterator.java
New "Java Hint" Wizzard added test dependencies to the pom which did not exist (`org-netbeans-modules-parsing-nb` and `org-netbeans-modules-projectapi-nb`).
PR changes it to `org-netbeans-modules-parsing-api` and `org-netbeans-modules-projectapi`.
=> Hint wizzard module dependency fix.

enterprise/cloud.oracle/nbproject/project.xml, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/CompartmentNode.java, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/DatabaseNode.java, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/DownloadWalletAction.java, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/DownloadWalletDialog.java, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCIManager.java, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OpenServiceConsoleAction.java, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OracleCloudWizardIterator.java, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/TenancyInstance.java, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/TenancyNode.java, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/items/DatabaseItem.java, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/items/OCIItem.java, enterprise/cloud.oracle/test/unit/src/org/netbeans/modules/cloud/oracle/DownloadWalletDialogTest.java, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/cloud-cookies.contextValues, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml, java/java.lsp.server/nbproject/project.properties, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceUIContext.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/NotifyDescriptorAdapter.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/UIContext.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/ui/AbstractDialogDisplayerTest.java, java/java.lsp.server/vscode/package.json, platform/openide.dialogs/apichanges.xml, platform/openide.dialogs/manifest.mf, platform/openide.dialogs/nbproject/org-openide-dialogs.sig, platform/openide.dialogs/src/org/openide/NotifyDescriptor.java
Download DB wallet action is available in vscode. `NotifyDescriptor.InputLine` is displayed in vscode as QuickInput. `NotifyDescriptor.PasswordLine` displays password input dialog.
=> Download wallet

.github/PULL_REQUEST_TEMPLATE.md
Add a pull request template with confirmation of submission terms and guidance.
Following on from @matthiasblaesing comments on easing the process for including code from new contributors, and making sure there's no need to get confirmation related to ASL section 5, could add it as text in the template.  It shows up as plain text in the submission box, so (unlike Airflow) I've removed most of the markdown.  Text could be shorter. Thoughts?
Will look similar to ...
Our contribution guidelines could do with a look, but that can happen next.
EDIT : Following comments and wording elsewhere, text updated from the image to be -
```
---
- are all your own work, and …
```
=> Add a pull request template with confirmation of submission terms

apisupport/apisupport.wizards/src/org/netbeans/modules/apisupport/project/ui/wizard/action/GUIRegistrationPanel.java, enterprise/api.web.webmodule/src/org/netbeans/modules/web/api/webmodule/WebModule.java, enterprise/j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/customizer/AppClientProjectProperties.java, enterprise/j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/wsclient/AppClientProjectWebServicesClientSupport.java, enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/client/AppClientProxy.java, enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/common/ComponentBeanMultiple.java, enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/common/DescriptionBeanMultiple.java, enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/common/xmlutils/XMLJ2eeUtils.java, enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/MultiTargetChooserPanel.java, enterprise/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/EjbJarWebServicesClientSupport.java, enterprise/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/EjbJarWebServicesSupport.java, enterprise/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/Utils.java, enterprise/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/ui/customizer/CustomizerLibraries.java, enterprise/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/ui/customizer/EjbJarProjectProperties.java, enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/utils/StringPrefixTree.java, enterprise/web.freeform/src/org/netbeans/modules/web/freeform/WebModules.java, enterprise/web.freeform/src/org/netbeans/modules/web/freeform/WebProjectGenerator.java, enterprise/web.freeform/src/org/netbeans/modules/web/freeform/ui/NewWebFreeformProjectWizardIterator.java, groovy/groovy.support/src/org/netbeans/modules/groovy/support/actions/singlefilerun/JPDAStart.java, harness/o.n.insane/src/org/netbeans/insane/impl/InsaneEngine.java, java/ant.debugger/src/org/netbeans/modules/ant/debugger/AntDebugger.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/dd/PersistenceMetadata.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/CCPaintComponent.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/JPACodeCompletionProvider.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/entitygenerator/CMPMappingModel.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/entitygenerator/DbSchemaEjbGenerator.java, java/maven.grammar/src/org/netbeans/modules/maven/grammar/effpom/LocationAwareMavenXpp3Writer.java, java/websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/support/SourceGroupSupport.java, platform/core.multiview/src/org/netbeans/core/multiview/MultiViewTopComponentLookup.java, platform/openide.util/src/org/openide/util/TopologicalSortException.java
Remove warnings related to raw type Iterator
```
[repeat] /home/bwalker/src/netbeans/ide/jellytools.ide/src/org/netbeans/jellytools/EditorOperator.java:687: warning:
[rawtypes] found raw type: Iterator [repeat] Iterator annotations = (Iterator) getAnnotationsMethod.invoke(lineAnnotations,
(Object[]) null); [repeat] ^ [repeat] missing type arguments for generic class Iterator<E> [repeat] where E is a type-variable:
[repeat] E extends Object declared in interface Iterator
```
---
- are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for …
=> Cleanup warnings related to raw type Iterator..

ide/csl.api/src/org/netbeans/modules/csl/navigation/ElementNode.java, ide/css.editor/src/org/netbeans/modules/css/editor/module/main/TopLevelStructureItem.java, ide/css.prep/src/org/netbeans/modules/css/prep/editor/CPCategoryStructureItem.java, ide/css.prep/src/org/netbeans/modules/css/prep/editor/CPCssEditorModule.java
The contract for StructureItem#getElementHandle is not always honored and implementors return `null`.
This causes NullPointer Exceptions in `ElementNode` which relies on it being present.
This changesets adds a guard to prevent invalid implementations to raise exceptions and fixes the CSS
code to provide the required `ElementHandle` implementations.
=> [#3593] Fix csl elementhandle

extide/gradle/src/org/netbeans/modules/gradle/nodes/SubProjectsNode.java
This one prepares the code getting ```null``` from ```ProjectUtils.getContainedProjects()```
---
=> [#3590] Prevent suspicious NPE forn Gradle SubProjectsNode

java/java.j2semodule/src/org/netbeans/modules/java/j2semodule/ui/customizer/Bundle.properties, java/java.j2seproject/src/org/netbeans/modules/java/j2seproject/ui/customizer/Bundle.properties, java/java.source/src/org/netbeans/modules/java/source/JBrowseModule.java, java/maven/src/org/netbeans/modules/maven/customizer/Bundle.properties
when nb-javac is uninstalled by the user and NB is started on a JDK < 17 this dialog will show up:
However, pressing install did nothing since the module name was wrong (!). This fixes it.
PR is based on delivery branch. I think we should add this even if there won't be another rc.
how to test:
1) start NB, load java cluster
2) uninstall nb-javac
3) start again on JDK 8, dialog should show up
4) install nb-javac via dalog, restart -> everything should be working again (no dialog)
=> fixed wrong nb-javac module name so that it can be installed.

.github/ISSUE_TEMPLATE/netbeans_bug_report.yml
Currently checkboxes in issue templates are converted to issue tasks. Since most of the checkboxes are not actual tasks this PR changes those to use comboboxes instead.
I left the accept code of conduct since it might make sense as a task.
In the future, GitHub may fix this or provide a better alternative.
https://github.com/github/feedback/discussions/4319
https://github.com/github/feedback/discussions/4318
https://github.com/github/feedback/discussions/5197
https://github.com/github/feedback/discussions/5238
=> Use combobox vs checkbox on issue template to avoid to issue tasks

java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/UIDefaultsIconMetadata.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/URITranslator.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/LspTreeViewServiceImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeItem.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeNodeRegistry.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeNodeRegistryImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeViewProvider.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/GetResourceParams.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/ResourceData.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/TreeItemData.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/TreeViewService.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/explorer/ProjectViewTest.java, java/java.lsp.server/vscode/src/explorer.ts, java/java.lsp.server/vscode/src/protocol.ts
Originally, the TreeView in (vscode) LSP client fetched node information and it got icon resource bits encoded in data: URI. To make the payload smaller, **both** the LSP client **and** server implemented a cache: server sent only the entire icon data only the 1st time with an unique id, and sent only that id afterwards.
This PR only sends image URI, and lets the client to ask, if necessary, for the resource bits. The client may substitute the images from its local resources and never ask the server.
Icons that provide their resource URLs are served by reading that URL's contents and base64 encoding to the LSP protocol response. Icons without their own URL (typically from L&Fs) are still painted on a virtual surface, converted to PNG. To avoid situation where the client receives an URI, …
=> Support icon resource fetch on LSP protocol, multiple content types.

cpplite/cpplite.debugger/nbproject/project.xml, cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPLiteDebugger.java, cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPLiteDebuggerConfig.java, cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/api/Debugger.java, cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/ni/NIDebuggerProviderImpl.java, cpplite/cpplite.debugger/test/unit/src/org/netbeans/modules/cpplite/debugger/AbstractDebugTest.java, ide/nativeimage.api/manifest.mf, ide/nativeimage.api/src/org/netbeans/modules/nativeimage/api/debug/NIDebugger.java, ide/nativeimage.api/src/org/netbeans/modules/nativeimage/api/debug/StartDebugParameters.java, ide/nativeimage.api/src/org/netbeans/modules/nativeimage/spi/debug/NIDebuggerProvider.java, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/NbAttachRequestHandler.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java, java/java.nativeimage.debugger/nbproject/project.xml, java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/actions/NIAttachCustomizer.java, java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/api/NIDebugRunner.java, java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/displayer/JavaVariablesDisplayer.java
In order to be able to retrieve runtime type information from native image, we must not set "print objects" GDB setting to "on". When it's on, we get some memory access issues from GDB.
To be able to turn it off for native image debugging (we want to have it on for C/C++), we need to add `displayObjects` flag into `StartDebugParameters`. We need to have it for both launch and attach, thus I've added `processId` as well and deprecated `attach` method.
Retrieval of runtime type information is added into `JavaVariablesDisplayer` and some additional checks are added to prevent from exceptions.
=> Native Image debugger does not set print objects on. Checks added to prevent from exceptions.

extide/gradle/apichanges.xml, extide/gradle/src/org/netbeans/modules/gradle/api/execute/Bundle.properties, extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleCommandLine.java, extide/gradle/src/org/netbeans/modules/gradle/execute/GradleCliCompletionProvider.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/api/execute/GradleCommandLineTest.java
Updated GradleCommandLine to support options according to Gradle 7.4
Even if it not nice regarding binary compatibility, I has to arrange the enums in alphabetic order, in order not to get mixed up when working on them.
Also Gradle options which expecting parameters are shown in the code completion. Those options which expect well defined values are stored in the parameter enum. Later on I plan to expand the code completion to use them as well.
=> Updated Gradle CLI option support.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeViewProvider.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/explorer/TreeViewProviderTest.java
The PR fixes `TreeNodeProvider.getNodeId()` call, which was supposed to find (or create) node LSP ID. The original code chained CompletableStages endlessly, eventually runnin OOM. The code was also not updated sufficiently as the rest of code evolved. Since `holdChildren` is now supposed to contain entries for all nodes known to the client, the fix will create these records for all nodes up to the root.
=> Fixed endless CompletionStage chaining.

java/java.lsp.server/vscode/src/runConfiguration.ts
Fixed an issue with environment variables containing the '=' character in their values. Now only the first appearance of '=' is used as a separator identifying variable name and value.
=> Fixed processing env variables with '=' in value

java/gradle.java/apichanges.xml, java/gradle.java/src/org/netbeans/modules/gradle/java/api/output/Location.java, java/gradle.java/src/org/netbeans/modules/gradle/java/api/output/LocationOpener.java, java/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/api/output/LocationTest.java, java/gradle.test/nbproject/project.xml, java/gradle.test/src/org/netbeans/modules/gradle/test/ui/nodes/GradleJUnitNodeOpener.java, java/gradle.test/src/org/netbeans/modules/gradle/test/ui/nodes/GradleTestMethodNode.java
This PR is part of the fixes needed for https://issues.apache.org/jira/browse/NETBEANS-6041
This is a fix for gradle projects, but since it's also broken for MAVEN (and possible standard netbeans projects) might need to be refactored to a different common module to fix it everywhere at once. Not sure what would be the best place.
=> Bugfix: Go To source broken for nested classes.

ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/FindComponentModules.java
This is the wrong use of the Enumeration interface..
[repeat] /home/bwalker/src/netbeans/ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/FindComponentModules.java:204: warning: [rawtypes] found raw type: Enumeration
[repeat]             Enumeration en = new StringTokenizer (value, ","); // NOI18N
[repeat]             ^
[repeat]   missing type arguments for generic class Enumeration<E>
[repeat]     E extends Object declared in interface Enumeration
---
- are contributed solely under the terms and conditions of the Apache License 2.0 …
=> Fix the wrong use of Enumeration interface

cnd/cnd.api.project/nbproject/project.xml, cnd/cnd.lsp/build.xml, cnd/cnd.lsp/manifest.mf, cnd/cnd.lsp/nbproject/project.properties, cnd/cnd.lsp/nbproject/project.xml, cnd/cnd.lsp/src/org/netbeans/modules/cnd/lsp/compilationdb/ClangCDBGenerationCause.java, cnd/cnd.lsp/src/org/netbeans/modules/cnd/lsp/compilationdb/ClangCDBGenerationTask.java, cnd/cnd.lsp/src/org/netbeans/modules/cnd/lsp/compilationdb/ClangCDBSupport.java, cnd/cnd.lsp/src/org/netbeans/modules/cnd/lsp/compilationdb/CommandObjectBuilder.java, cnd/cnd.lsp/src/org/netbeans/modules/cnd/lsp/makeproject/LSPMakeProjectLookupProvider.java, cnd/cnd.lsp/src/org/netbeans/modules/cnd/lsp/resources/Bundle.properties, cnd/cnd.makeproject/nbproject/project.xml, cnd/cnd.toolchain/nbproject/project.xml, ide/dlight.nativeexecution/nbproject/project.xml, nbbuild/cluster.properties
Automatically generate compile_commands.json for make based projects.
Makefile based projects generate now a compile_commands.json compilation database with the proper project configuration, as defined in https://clang.llvm.org/docs/JSONCompilationDatabase.html this is needed for both clangd anc ccls LSP servers. 
A specific MakeProjectLookupProvider adds this feature to all make projects, background tasks run on demand, after a coalescing period, and for small projects this runs in < 100ms. on my box.
=> [cnd] 3.1 makeproject compile_commands.json

java/java.lsp.server/nbcode/integration/nbproject/project.xml, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractDialogDisplayer.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/NotifyDescriptorAdapter.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/ui/AbstractDialogDisplayerTest.java, platform/core.windows/nbproject/project.xml, platform/core.windows/src/org/netbeans/core/windows/services/DialogDisplayerImpl.java, platform/core.windows/test/unit/src/org/netbeans/core/windows/services/DialogDisplayerImplTest.java, platform/openide.dialogs/apichanges.xml, platform/openide.dialogs/manifest.mf, platform/openide.dialogs/nbproject/project.properties, platform/openide.dialogs/src/org/openide/DialogDisplayer.java, platform/openide.dialogs/test/unit/src/org/openide/DialogDisplayerTest.java
`DialogDisplayer` API allows to wait for dialog's close when using `notify` method but that wasted a thread to wait for the `notify` method to return. And all the goodies that `CompletableFuture` API can't be used, while this is a perfect example of a Future.
So this PR adds 
```
public <T extends NotifyDescriptor> CompletableFuture<T> notifyCompletion(final T descriptor) {
```
that runs similar to `notifyLater`, but returns a Future that the continuation can chain after. There are important differences, hopefully described in the javadoc:
- the value is the `NotifyDescriptor` subclass itself. This is because for example `NotifyDescriptor.InputLine` has additional getters that are typically processed in the completion handler. This allows to pass NotifyDescriptors from one step to another …
=> Support CompletableFuture in DialogDisplayer

ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java
Adds some extra synchronized blocks around those non thread-safe maps.
=> LSPBindings synchronization fix

platform/core.windows/src/org/netbeans/core/windows/view/ui/CloseButtonTabbedPane.java, platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/Startup.java, platform/openide.awt/src/org/openide/awt/CloseButtonFactory.java, profiler/lib.profiler.ui/src/org/netbeans/lib/profiler/ui/UIUtils.java
When running NetBeans with the Windows LAF on Windows 11 and Java 17, parts of the LAF revert to an older look. See screenshot below.
This is due to the "os.name" system property being checked for the value "Windows 10" in various places. With Java 17 and Windows 11, this property can now have the value "Windows 11". This PR goes through each occurrence of "Windows 10" and also permits "Windows 11" in these cases.
=> [NETBEANS-6468] Fix Windows LAF on Windows 11 and Java 17

java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/models/VariableMirrorTranslator.java
I initially started cleaning up VariableMirrorTranslator.java as part of
mass deprecation cleanup work I am doing.
The changes for handling the autobox/unbox of the floating-point class turned
into a general cleanup.
- updated autobox/unbox
- using multi-catch now
- using strings in switch
- update a couple of places should be using diamond operator
---
Please make sure (eg. `git log`) that all commits have a valid name and email address for you in the Author …
=> update VariableMirrorTranslator to bring it up to standards

profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofInstanceValue.java
Cleaned up the deprecated use of old constructors. The compiler/VM will now autobox this into a proper
class. So this change removes warnings like this:
[repeat] /home/bwalker/src/netbeans/profiler/lib.profiler/src/org/netbeans/lib/profiler/heap/HprofInstanceValue.java:93: warning: [deprecation] Byte(byte) in Byte has been deprecated
[repeat]                 return new Byte(bt);
[repeat]                        ^
Also, added a couple of override annotations since I was here..
---
- are contributed solely under the terms and conditions of the Apache License 2.0 (see section 5 of the license for …
=> Cleanup deprecated constructor use

ide/api.lsp/apichanges.xml, ide/api.lsp/src/org/netbeans/api/lsp/StructureElement.java, ide/api.lsp/src/org/netbeans/modules/lsp/StructureElementAccessor.java, ide/api.lsp/src/org/netbeans/spi/lsp/StructureProvider.java, ide/api.lsp/test/unit/src/org/netbeans/api/lsp/StructureElementTest.java, ide/csl.api/src/org/netbeans/modules/csl/core/LanguageRegistrationProcessor.java, ide/csl.api/src/org/netbeans/modules/csl/navigation/GsfStructureProvider.java, java/java.editor/src/org/netbeans/modules/editor/java/JavaStructureProvider.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
This is the outlineview implementation not only for Groovy files, but for all GSF languages that are/will be enabled in the Vs Code extension. At the moment it is for Groovy files and YAML files that have `application` or `bootstrap` prefix.
The implementation requires adding two interfaces to the LSP API. Clients can implement and register a `StructureProvider` into `MimeLookup` for a given mimetype. `StructureProvider` provides a list of top symbols to be displayed in the outline view. The symbol structure is composed of `StrctureElements`. 
StructureElements are then translated into `DocumentSymbol`s on the VSCode API side, which are displayed in the outline view and also in Go to a symbol (CTRL+SHIFT+O by default). `DocumentSymbol`  has two methods `getName()` and `getDetail()`, which …
=> [NETBEANS-6425] Provide outline view for Groovy file in VSCode.

platform/openide.loaders/src/org/openide/loaders/FolderInstance.java
In the GraalVM debugging tests (`java/debugger.jpda.truffle`) there was often a Cyclic reference issue from `FolderInstance`.
It turned out, that there was not really any cyclic reference, but as the field `waitFor` was not marked as volatile, the code sometimes did not see the new value updated by the creation task.
By marking the fields as `volatile` we assure that their updated values are seen by other threads.
=> [NETBEANS-6458] A bogus Cyclic Reference issue is resolved by marking fields as volatile.

php/php.editor/src/org/netbeans/modules/php/editor/parser/astnodes/StaticStatement.java, php/php.editor/src/org/netbeans/modules/php/editor/verification/PHP81UnhandledError.java
- https://issues.apache.org/jira/browse/NETBEANS-5599
- RFC:https://wiki.php.net/rfc/new_in_initializers
- Fix PHP81UnhandledError
PHP 8.1
PHP 8.0
=> [NETBEANS-5599] PHP 8.1 Support: New in initializers (Part 4)

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/DebugManagerHandler.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/RemoteServices.java, java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/TruffleDebugManager.java
In Truffle debugger we call Truffle API from an unnamed module. In order to be able to call Truffle APIs we need to export the Truffle packages to our module. We used `TruffleJDKServices.exportTo()`, but that class was recently removed from GraalVM.
We suspend at `Truffle.getRuntime()` (impl in `TruffleDebugManager`) and call `Module.addExports(...)` with the packages we are using (impl in `RemoteServices`).
=> Export the Truffle packages explicitly, since TruffleJDKServices class was removed.

.github/workflows/native-binary-build-lib.profiler.yml
About 4 months ago GitHub updated the windows-latest image to include the Windows 11 SDK which broke the "Profiler native binary build" workflow.
GitHub has also changed windows-latest to use the windows-2022 image.
The MR changes the build to use VS 2022 with the Windows 10 SDK.
Other potential fix could be to modify the rc file. see https://bugs.python.org/issue45220
---
Please make sure (eg. `git log`) that all commits have a valid name and email address …
=> Fix Windows profiler.lib workflow by using Windows10SDK.20348

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java, extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java, extide/gradle/src/org/netbeans/modules/gradle/cache/ProjectInfoDiskCache.java
Following suggestion in [NETBEANS-5846](https://issues.apache.org/jira/browse/NETBEANS-5846). The ProjectInfoBuilder in `gradle-tooling` was changed so it does not produce `unresolved_problems` if the project uses `javaPlatform` plugin w/ dependencies enabled. 
The 2nd commit is a bugfix - during testing, I used `Reload Project` action and the project did not degrade to the new (broken) state after change in buildscript + reload. My fault, the `force` parameter to loadProject was not used at all.
=> Ignore dependencies for BOM-like projects.

platform/o.n.core/nbproject/project.properties, platform/o.n.core/src/org/netbeans/core/actions/AboutAction.java, platform/o.n.core/src/org/netbeans/core/ui/ProductInformationPanel.form, platform/o.n.core/src/org/netbeans/core/ui/ProductInformationPanel.java
before:
after:
- layout tweaks
- some code cleanup / language level upgrade
context:
inspired by a discussion on NB slack.
The two text panels are in scroll areas which makes it a bit difficult to compute their size for the window. (the point of a scroll area is to not care about the dimensions of its content).
The lower panel has predictable content, so I disabled the vertical scrollbar and set the horizontal scrollbar to show-always so that it is part of the layout computation. Height is now set to default, since it can size itself now.
The upper panel had fixed size, it still has, it just lost around 50px in height. Btw should we add a github link there?
Rest are minor cleanups in the involved areas.
=> about window update

ide/lsp.client/apichanges.xml, ide/lsp.client/nbproject/project.properties, ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java, ide/lsp.client/src/org/netbeans/modules/lsp/client/spi/MultiMimeLanguageServerProvider.java
Some LSP servers can handle files with different mime-types within the same project. 
For instance, "clangd", "ccls" and "apple/source-kit" are able to handle "text/x-c", "text/x-cpp" and others. C++ projects may include simple C files within the same project. 
This adds a new SPI interface "MultiMimeLanguageServerProvider" that returns a set of mime-types handled by the LSP server. 
The commit registers/deregisters all these mime-types at once. Otherwise the same LSP server may be started (restarted?)  several times for different mime types ( [in this loop](https://github.com/apache/netbeans/blob/76be2da4de40da05cd9f6c978d1e29bc16f99c1f/ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java#L270)) possibly losing some previous state or causing multiple `initialize` requests …
=> ide/lsp.client + MultiMimeLanguageServerProvider

ide/projectui/src/org/netbeans/modules/project/ui/problems/BrokenReferencesImpl.java, ide/projectuiapi/apichanges.xml, ide/projectuiapi/nbproject/project.properties, ide/projectuiapi/src/org/netbeans/api/project/ui/ProjectProblems.java, ide/projectuiapi/src/org/netbeans/spi/project/ui/ProjectProblemsImplementation.java, java/java.lsp.server/nbcode/integration/nbproject/project.xml, java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/LspBrokenReferencesImpl.java, java/java.lsp.server/nbproject/project.properties, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/project/BrokenReferencesImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/project/BrokenReferencesModel.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/project/ProjectAlertPresenter.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractLspBrokenReferences.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/project/LspBrokenReferencesImplTest.java
Project problems are presented in a rich UI dialog in NB, but that's not suitable for LSP protocol that only allows for limited dialogs or quickpicks. Instead of a rich-interaction view, this PR replaces (just for the LSP !!) the process by a series of dialogs.
- Errors are presented all at once, with some limit (~10). If there are more errors, they're displayed as soon as the user closes/confirms earlier messages.
- Fixable problems are presented one by one: each confirmation offers the possibility to fix rest of the issues without asking
- If an error occurs during a fix (the resolution is not "resolved"), the err message is printed, and the user is asked to cancel or continue with fixes
- If a new unfixable problem appears during the process, the error is displayed before the next …
=> Alternative ProjectProblems presenter for LSP server.

.github/workflows/cv.yml, .github/workflows/ensure-jdk8.yml, .github/workflows/javadoc.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/php.yml, .github/workflows/windows.yml
The Windows Github workflow occasionaly fails on timeout, and as @JaroslavTulach  experiments indicated, the path expression `**/external/binaries-list` is too broad and it the filesystem search seems to take ages on Windows, Bill knows why.
The search can be narrowed as we do not have `binaries-list` on 3rd and lower levels (now). I made the change to all workflows, so the computed hash allows to share the binaries.
=> Do not search unnecessarily deep.

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletDialog.java
We need to keep db username and schema in uppercase for Oracle Autonomous DB
=> Keep database username in upper case

.travis.yml, nbbuild/build.xml
travis fails to restart old jobs of already integrated commits, for example:
```
fatal: reference is not a tree: 49e167edc46e335e1587ba22749650c5617f9954
The command "git checkout -qf 49e167edc46e335e1587ba22749650c5617f9954" failed and exited with 128 during .
```
setting `--depth` to 50 should improve the situation a bit (I hope) without having to clone the entire repo.
I also added some java version info printout to ant.
=> increase git clone depth so that we can restart older jobs post merge.

.github/workflows/linux-upstream-jdk.yml, ide/schema2beans/src/org/netbeans/modules/schema2beansdev/gen/JavaUtil.java
it turns out that the enterprise cluster was the last cluster with build problems on JDK 17. Java cluster was fixed back in #3278 and gradle #3326. 
@matthiasblaesing must have fixed the javascript cluster without telling anyone :)
everything builds locally, lets see if CI agrees.
this fixes the following build error:
```
[repeat] Note: generating beans in org.netbeans.modules.j2ee.deployment.impl.gen.nbd
[repeat] Note: parsing: file:///mnt/ram/netbeans/enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/plugins/api/netbeans-deployment.dtd
[repeat] /mnt/ram/netbeans/enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/gen/nbd/package-info.java:28: error: Failed to process
[repeat] package org.netbeans.modules.j2ee.deployment.impl.gen.nbd;
[repeat] ^
[repeat] …
```
=> fix enterprise cluster build on JDK 17 + add upstream-JDK build job.

ide/api.lsp/apichanges.xml, ide/api.lsp/manifest.mf, ide/api.lsp/src/org/netbeans/api/lsp/CallHierarchyEntry.java, ide/api.lsp/src/org/netbeans/api/lsp/Range.java, ide/api.lsp/src/org/netbeans/api/lsp/StructureElement.java, ide/api.lsp/src/org/netbeans/modules/lsp/StructureElementAccessor.java, ide/api.lsp/src/org/netbeans/spi/lsp/CallHierarchyProvider.java, ide/api.lsp/src/org/netbeans/spi/lsp/StructureProvider.java, java/java.editor/nbproject/project.xml, java/java.editor/src/org/netbeans/modules/editor/java/JavaStructureProvider.java, java/java.lsp.server/nbproject/project.xml, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.sourceui/apichanges.xml, java/java.sourceui/nbproject/project.properties, java/java.sourceui/nbproject/project.xml, java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementHeaders.java, java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementOpen.java, java/java.sourceui/src/org/netbeans/modules/java/source/ui/ElementOpenAccessor.java, java/java.sourceui/src/org/netbeans/modules/java/source/ui/LspElementUtils.java, java/java.sourceui/test/unit/data/structureElement/Test.java, java/java.sourceui/test/unit/src/org/netbeans/api/java/source/ui/ElementHeadersTest.java, java/refactoring.java/nbproject/project.xml, java/refactoring.java/src/org/netbeans/modules/refactoring/java/callhierarchy/CallHierarchyTasks.java, java/refactoring.java/src/org/netbeans/modules/refactoring/java/callhierarchy/CallOccurrence.java, java/refactoring.java/src/org/netbeans/modules/refactoring/java/callhierarchy/LspCallHierarchyProvider.java
This PR adds support for `textDocument/prepareCallHierarchy`, `callHierarchy/incomingCalls` and `callHierarchy/outgoingCalls` messages (see [LSP Protocol Spec 3.16](https://microsoft.github.io/language-server-protocol/specification#textDocument_prepareCallHierarchy) ).
I decided to **reuse** `StructureElement` invented as a part of Outline support: elements reported by the Call Hierarchy have exactly the same meaning, plus the `uri`, which is implicit in the Outline. I have added `file` property to `StructureElement` and relevant `StructureProvider.Builder` method.
In order to share code between Java Editor module (that implements Outline) and Java Refactoring module (which implements the Call Hierarchy, but does not export it through any API), I've introduced helper methods for LSP into …
=> Support for Call Hierarchy for LSP

webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/index/JsIndexer.java, webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/navigation/OccurrencesSupport.java, webcommon/javascript2.editor/test/unit/data/testfiles/indexer/SelfreferencingFunction.js, webcommon/javascript2.editor/test/unit/data/testfiles/indexer/SelfreferencingFunction.js.indexed, webcommon/javascript2.editor/test/unit/data/testfiles/indexer/SelfreferencingObject.js, webcommon/javascript2.editor/test/unit/data/testfiles/indexer/SelfreferencingObject.js.indexed, webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/JsTestBase.java, webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/index/RecursiveStructuresTest.java
JS structures, that reference themselves can cause unlimited recursion
in several places. In this changeset the JsIndexer and
OccurrencesSupport are modified, so that recursive structures can be
scanned without causing a StackOverflowError.
Closes: #3669
=> Improve handling of recursive JS structures

platform/api.search/src/org/netbeans/modules/search/BasicSearchForm.java
fixes #3752
This was difficult to find since the symptoms were fairly misleading.
For some reason the click event only disappeared when the find button was clicked, while cancel worked reliably with a single click. But there was nothing special about the find button beside it being the default action / already focused.
see https://bugs.openjdk.java.net/browse/JDK-4530952
=> workaround due to old JDK bug (see JDK-4530952).

java/maven/src/org/netbeans/modules/maven/execute/cmd/ShellConstructor.java
In the "bin" folder of "mvnd-0.7.1-windows-amd64" (latest current release), the list of files is as follows:
```
├── mvnd-bash-completion.bash
├── mvnd-sync.exe
├── mvnd.cmd
├── mvnd.exe
└── mvnd.sh
```
I take the liberty of adding the suffix ".cmd" when detecting under windows only
=> Fix maven daemon detection on windows platform

.github/ISSUE_TEMPLATE/netbeans_bug_report.yml
=> Add Apache NetBeans Snap Package as an option to GitHub Bug report

ide/bcpg/external/bcpg-jdk15on-1.70-license.txt, ide/bcpg/external/binaries-list, ide/bcpg/nbproject/project.properties, ide/bcpg/nbproject/project.xml, ide/bcpkix/external/bcpkix-jdk15on-1.70-license.txt, ide/bcpkix/external/binaries-list, ide/bcpkix/nbproject/project.properties, ide/bcpkix/nbproject/project.xml, ide/bcprov/external/bcprov-jdk15on-1.70-license.txt, ide/bcprov/external/binaries-list, ide/bcprov/nbproject/project.properties, ide/bcutil/build.xml, ide/bcutil/external/bcutil-jdk15on-1.70-license.txt, ide/bcutil/external/binaries-list, ide/bcutil/manifest.mf, ide/bcutil/nbproject/project.properties, ide/bcutil/nbproject/project.xml, nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps, nbbuild/cluster.properties
Library Notes:
- Many bug fixes and improvements
- Upgrade `bcprov`, `bcpg` and `bcpkix`
- Add a new module `ide/bcutil` due to a refactoring in version 1.69
- Remove entry in ignored-overlaps file
[Web Page](https://bouncycastle.org/latest_releases.html)
[Releases Notes](https://bouncycastle.org/releasenotes.html)
- Full build done 
- Checked the files had been downloaded and placed at `/netbeans/ide/modules/bcprov.jar`, `/netbeans/ide/modules/bcpg.jar`, `/netbeans/ide/modules/bcpkix.jar` and `/netbeans/ide/modules/bcutil.jar`
- Started NetBeans and ensure the log didn't have any ERROR or new WARNINGS 
- Checked that the Module-Specification-Version is increased in the starting log. `bcprov [1.70 1.70]`, `bcpg [1.68 1.70]`, `bcpkix [1.70 1.70]` and …
=> [NETBEANS-4665] - Upgrade Bouncy Castle from 1.68 to 1.70

platform/core.ui/src/org/netbeans/core/ui/options/general/AdvancedProxyPanel.form, platform/core.ui/src/org/netbeans/core/ui/options/general/AdvancedProxyPanel.java, platform/core.ui/src/org/netbeans/core/ui/options/general/Bundle.properties
Adding a note in the Advanced Proxy Options to warn users of JDK >= 8u111, because Basic auth disables HTTPS tunneling from this on. See #3748 for details.
Users are redirected to https://netbeans.apache.org/wiki/ProxyBasicAuth for more information.
New dialog looks like this (design window):
Labels also fill horizontally (previous dialog didn't).
=> #3748 Note for Advanced Proxy Options

ide/api.debugger/src/org/netbeans/api/debugger/Properties.java, ide/html.lexer/src/org/netbeans/lib/html/lexer/HtmlLexer.java, ide/javascript2.debug/src/org/netbeans/modules/javascript2/debug/sources/SourceURLMapper.java, ide/schema2beans/src/org/netbeans/modules/schema2beans/Common.java, ide/schema2beans/src/org/netbeans/modules/schema2beans/GraphManager.java, java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/testapps/EvaluatorApp.java, java/j2ee.persistence/test/unit/src/org/netbeans/modules/db/test/jdbcstub/JDBCStubUtil.java, java/j2ee.persistence/test/unit/src/org/netbeans/test/stub/api/Stub.java, nb/o.n.upgrader/src/org/netbeans/upgrade/systemoptions/SerParser.java, platform/openide.explorer/src/org/openide/explorer/propertysheet/IndexedPropertyEditor.java, platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java, platform/openide.windows/src/org/openide/windows/TopComponent.java, websvccommon/websvc.saas.codegen/src/org/netbeans/modules/websvc/saas/codegen/model/ParameterInfo.java
It is more efficient to allow the VM to manage the auto-boxing of certain primitives than it is to invoke the
object constructor.
This change cleans up Byte & Short for this.
Tests have been left untouched because we expressly want to handle the boxing in each particular test.
---
If you're a first time contributor, see the Contributing guidelines …
=> cleanup Byte & Short object constructors

java/maven.embedder/nbproject/project.xml, java/maven.hints/nbproject/project.properties, java/maven.hints/nbproject/project.xml, java/maven.hints/src/org/netbeans/modules/maven/hints/pom/MavenFileHintsTask.java, java/maven.hints/src/org/netbeans/modules/maven/hints/pom/MavenPOMParser.java, java/maven.hints/src/org/netbeans/modules/maven/hints/pom/MavenResult.java, java/maven.hints/src/org/netbeans/modules/maven/hints/pom/MavenSelectionHintsTask.java, java/maven.hints/src/org/netbeans/modules/maven/hints/pom/PomModelUtils.java, java/maven.hints/src/org/netbeans/modules/maven/hints/pom/StatusProvider.java, java/maven.hints/src/org/netbeans/modules/maven/hints/pom/TaskListBridge.java, java/maven.hints/test/unit/src/org/netbeans/modules/maven/hints/pom/StatusProviderTest.java, java/maven.hints/test/unit/src/org/netbeans/modules/maven/hints/pom/pom-with-warnings.xml
Originally I was trying to bridge project problems to LSP. During the course I have realized that Maven's errors, underlined in the editor, are provided by `UpToDateStatusProvider` implementation - this one is in charge or reporting start/stop computations in annotation's gutter.
The Provider however monitored **on-disk file changes**, so potential errors were only reported after file save, not (as usual) when a change to the opened document has been made by the user. This approach bypasses alll the machinery of Parsing API which is more suitable for tracking document changes and/or caret/selection in the live document. In addition, this approach wouldn't work in the LSP client scenario at all.
The StatusProvider implementation was broken anyway as for example …
=> Maven error/warnings refactored to use Parsing API.

java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBClassReader.java, java/lib.nbjavac/test/unit/src/org/netbeans/lib/nbjavac/services/NBClassReaderTest.java
javac normally refuses to load classfiles that are too new (unlike old nb-javac). Classfile versions change fairly frequently, but javac can often load the newer classfiles anyway. So let's try to load them, as did nb-javac. (It will be a bit slower to read the too-new classfile, but I think that is mostly fine.)
Based on a report from here:
https://lists.apache.org/thread/gtv4nnhvjtzqrk8zmsojj70blw0n18yv
=> Handle classfiles with too new versions.

extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleDaemon.java
This is a fix for #3801. Moved two constants from public to private as they shall be not used elsewhere and were not part of the public API.
=> Escape backslash in Gradle tooling jar path on Windows

extide/gradle/src/org/netbeans/modules/gradle/output/GradleProcessorFactory.java
Well it seems earlier releases use: ```Use '--warning-mode all'``` while current ones use: ```You can use '--warning-mode all'``` term.
=> Fix Gradle --warning-mode all action to work with any Gradle release

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/GroovyIndexer.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/CaretLocation.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/CompletionItem.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/util/CompletionContext.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/TypesCompletion.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/resources/layer.xml, groovy/groovy.editor/test/unit/data/testfiles/Hello.groovy.indexed, groovy/groovy.editor/test/unit/data/testfiles/completion/import/staticImportCompletion/StaticImportCompletion.groovy.testStaticImportCompletion.completion, groovy/groovy.editor/test/unit/data/testfiles/completion/transformations/singleton3/Singleton3.groovy.testSingleton3_withoutPrefix.completion, java/java.source.base/src/org/netbeans/modules/java/source/JavaSourceUtilImpl.java, java/java.source.base/src/org/netbeans/modules/java/source/parsing/ForwardingInferableJavaFileObject.java, java/java.source.base/src/org/netbeans/modules/java/source/parsing/ForwardingPrefetchableJavaFileObject.java, java/java.source.base/src/org/netbeans/modules/java/source/parsing/MultiReleaseJarFileObject.java, java/java.source.base/src/org/netbeans/modules/java/source/usages/VirtualSourceProviderQuery.java, java/java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/FileObjectsTest.java
This will turn back on indexing of Groovy files in Java. This means that Groovy classes can now be offered in java source files.  The Groovy file is used to create virtual Java source code that is indexed and stored in the java index. This will not only enable indexing, but features like code completion, hyperlinks, goto navigation should also work. 
More fixes were needed to get this working again. There are also a few fixes that improve the current staff, such as:
- static fields and methods are offered as fields and methods in import statements code completion - they were previously offered as classes in code completion. 
- correcting types of constructors that are strored in Groovy Index
- JavaElementHandles now are created with the fully qualifed names, there were created only with …
=> [NETBEANS-4826] Fixing java indexing in Groovy

.travis.yml
lets give this a try to make job 13 more reliable
1. identify unreliable tests
2. isolate them into their own job (easier restartable without having to run well behaving tests multiple times)
3. maybe use `travis_retry`
- - -
logs from a different PR where i had to restart job 13 four times in a row:
```
https://app.travis-ci.com/github/apache/netbeans/jobs/563140526
org.netbeans.modules.java.lsp.server.explorer.ProjectViewTest
failed: testOnceExistedDeletedItemInfo
org.netbeans.modules.java.lsp.server.project.LspBrokenReferencesImplTest
failed: testIgnoredErrorsTimeout
org.netbeans.modules.java.source.parsing.PartialReparseTest
failed: testIntroduceParseError2
---
https://app.travis-ci.com/github/apache/netbeans/jobs/563138079
org.netbeans.modules.java.lsp.server.explorer.ProjectViewTest …
```
=> exile job for unreliable tests.

java/java.editor.base/src/org/netbeans/modules/java/editor/base/imports/UnusedImports.java, java/java.editor.base/test/unit/src/org/netbeans/modules/java/editor/base/semantic/UnusedImportsTest.java
Fixes #3731 
Import usage is not detected, as the UnusedImports visitor does not descend into the module declaration (IIRC there was a change at some point, before it was included in getTypeDecls, I think).
=> [3731] Fixing unused import handling for module-infos.

java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java, java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementOpen.java, java/java.sourceui/src/org/netbeans/modules/java/source/ui/LspElementUtils.java
- TreePathHandles cannot be created for PackageElements. Code in `LspElementUtils` should respect this fact.
- `VanillaCompileWorker.fallbackCopyExistingClassFiles(...)` should be limited to class files only to prevent subsequent errors thrown from `BinaryAnalyser`
=> Minor bug fixes.

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/items/OCIItem.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/NodeActionsProvider.java, java/java.lsp.server/test/unit/src/META-INF/generated-layer.xml, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/explorer/NodeActionsProviderTest.java, java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/explorer/TestInfo.java
Adding possibility to invoke arbitrary action from vscode. Any action registered in `java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml` can be called as a vscode command:
`vscode.commands.executeCommand('nbls:<Category>:<actionId>', <context>);`. Context will be converted to Action type defined in layer.
=> Invoke arbitrary action from vscode

ide/extexecution.base/src/org/netbeans/api/extexecution/base/BaseExecutionService.java, java/maven/src/org/netbeans/modules/maven/execute/CommandLineOutputHandler.java
With JDK 18 the default charset for java was changed. Before this
change, the default charset (exposed as the system property
file.encoding) was platform specific. After the change the default
charset was unified to UTF-8 on all platforms.
Code that interacts with native APIs can use the system property
native.encoding to query the platform encoding and use that. And related
to this the same is true for applications interacting with the system
console.
The primarly affected platform is windows, as both mac OS and Linux
already default to UTF-8 as file encoding.
In this PR two areas are covered:
- General execution (using "External Execution API"): The module already
allows users to specify the encoding to use. It used the default
enconding as a fallback, if none was specified. This …
=> Fix console encoding on JDK 18 (Maven + general execution)

java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Add entry to the `OFFICIAL_JAVADOC` Map for Java 19
- https://download.java.net/java/early_access/jdk19/docs/api/
Change Java 18 to GA
- https://docs.oracle.com/en/java/javase/18/docs/api/
=> [NETBEANS-6411] - Add javadoc for JDK 19 early access and JDK 18 GA

ide/db.core/src/org/netbeans/modules/db/sql/history/SQLHistoryManager.java
It was observed, that sometimes the sql history was lost and it is
assumed, that writing the new history began (emptying the file as the
first step) and was not completed. By using a temporary file, the file
is either written completely or not. It is assumed, that a move
operation inside the same directory is atomic on all OSes.
=> SQL History loss: Reimplement atomatic saving by writing to tempfile and moving to target

nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java
When downloading external binaries, save any `IOException` for the `cause` parameter of the `BuildException`. Otherwise, the root cause of the build failure is always `null`.
=> Save cause of download error for BuildException

nbbuild/jms-config/desktop.flags
Include exports to can execute macOs 'Show In Finder' action in jdk17.
=> [NETBEANS-6329] Tools > Show In Finder don't works on JDK 17

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyParser.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyVirtualSourceProvider.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/GroovyIndexingTask.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/SimpleTransformationCustomizer.java, groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/utils/GroovyUtils.java
GroovyVirtualSourceProvider should run GroovyParser in 'indexing' mode. Otherwise, the Spock transformations are omitted leaving generated stub classes in a state not compilable by Java (e.g. generated virtual Java sources contain spaces in method names, etc).
=> GroovyVirtualSourceProvider should run GroovyParser in 'indexing' mode.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBSetEnvCommand.java
Fixing typo in the names of db environment variables
=> Fixing typo in db env command

enterprise/cloud.oracle/licenseinfo.xml, enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletAction.java, enterprise/cloud.oracle/test/unit/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletActionTest.java, enterprise/cloud.oracle/test/unit/src/org/netbeans/modules/cloud/oracle/actions/tnsnames.ora
In case the connection name is not known before the DB Wallet is downloaded, parse wallet's `tnsnames.ora` and take one from there.
=> Handle the case when the connection name is not known before wallet download

java/java.source.base/src/org/netbeans/modules/java/source/parsing/VanillaPartialReparser.java
It was observed, that NetBeans can create an excessive number of source
dump files in situations, where the partial reparse verifier bails out.
The VanillaPartialReparser already suppresses dumping of source files
in case of exceptions if assertions are not enabled. The same logic is
now applied to the activation of VerifyPartialReparse.
VerifyPartialReparse has no side effects and thus can be disabled if
dumping should be turned off.
=> [#3728] Only enable VerifyPartialReparse if assertions are enabled

.github/workflows/main.yml
PR tests some optimizations / improvements.
**use Zstandard compression for pipeline artifacts.**
- faster compression (multithreaded) and extraction compared to gz
- smaller artifact footprint (with `-9` setting, seems to be the sweet spot in my experience from other deployments)
- all github nodes support it [out of the box](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software)
- cumulative performance improvement due to the nature of the pipeline
Local test using 2 threads to simulate a gh node. Tested in a ramdisk. The actual code uses `-T0` to be forward compatible.
```bash 
time tar -czf /tmp/build.tar.gz --exclude ".git" .
real    1m12,641s
user    1m18,657s
sys     0m3,167s
time tar -I 'zstd -9 -T2' -cf /tmp/build.tar.zst …
```
=> ci pipeline improvements

ide/api.debugger/src/org/netbeans/api/debugger/Properties.java, ide/css.lib/src/org/netbeans/modules/css/lib/api/properties/TokenAcceptor.java, ide/db.dataview/src/org/netbeans/modules/db/dataview/util/DBReadWriteHelper.java, ide/schema2beans/src/org/netbeans/modules/schema2beans/Common.java, ide/schema2beans/src/org/netbeans/modules/schema2beans/GraphManager.java, java/classfile/src/org/netbeans/modules/classfile/CPFloatInfo.java, java/performance/benchmarks/src/org/netbeans/performance/benchmarks/XMLReporter.java, java/performance/sparrow/src/org/netbeans/performance/impl/logparsing/GcLog.java, java/performance/sparrow/src/org/netbeans/performance/spi/AveragedNameValueLogElement.java, nb/o.n.upgrader/src/org/netbeans/upgrade/systemoptions/SerParser.java, platform/o.n.swing.tabcontrol/demosrc/org/netbeans/swing/tabcontrol/demo/TestFrame.java, platform/openide.explorer/src/org/openide/explorer/propertysheet/IndexedPropertyEditor.java, platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java, platform/openide.options/src/org/openide/text/PrintSettings.java, profiler/lib.profiler.ui/src/org/netbeans/lib/profiler/ui/cpu/CCTDisplay.java, profiler/lib.profiler.ui/src/org/netbeans/lib/profiler/ui/cpu/DiffCCTDisplay.java, profiler/lib.profiler.ui/src/org/netbeans/lib/profiler/ui/cpu/DiffFlatProfilePanel.java, profiler/lib.profiler.ui/src/org/netbeans/lib/profiler/ui/cpu/FlatProfilePanel.java, profiler/lib.profiler.ui/src/org/netbeans/lib/profiler/ui/cpu/ReverseCallGraphPanel.java, profiler/lib.profiler.ui/src/org/netbeans/lib/profiler/ui/cpu/SubtreeCallGraphPanel.java, websvccommon/websvc.saas.codegen/src/org/netbeans/modules/websvc/saas/codegen/model/ParameterInfo.java
As of Java 9, the VM can do a better job of handling the conversion from a float primitive to a Float Object or vice versa.
This is an extension of the work done in #2498.
No tests have been touched as those expressly need to manage the conversion.
Lastly, these changes are project wide and not module specific.
---
If you're a first time …
=> Cleanup the use of Float primitive wrapper.

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java, extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NeedOnlineModeException.java, extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NetBeansToolingPlugin.java, extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java, extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleArtifactStore.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java
The idea in #3375 to check the global Artifact store was good in general, BUT ...
it turned out that when the project is loading in FULL_ONLINE mode (implies no --offline switch), the NBTooling plugin [will **not** report back](https://github.com/apache/netbeans/blob/master/extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java#L514) any javadocs or sources even though they may exist in the local `~/.gradle` jar cache. OK, after that the project is saved without any such artifacts, and the artifact store is updated with this imprecise info: no sources / javadocs would be registered (so eventually sources/javadocs maps can be completely empty). Consider, for example, if the `var/cache` in userdir is cleared, but the gradle …
=> Relax serialized project cache checks

enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/api/web/DDProvider.java, enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/multiview/DDMultiViewDataObject.java, extide/gradle/src/org/netbeans/modules/gradle/cache/AbstractDiskCache.java, ide/bugtracking/src/org/netbeans/modules/bugtracking/RepositoryImpl.java, ide/xml.multiview/src/org/netbeans/modules/xml/multiview/XmlMultiViewDataObject.java, ide/xml.tax/src/org/netbeans/modules/xml/tax/cookies/TreeEditorCookieImpl.java, ide/xml/src/org/netbeans/modules/xml/DTDDataObject.java, ide/xml/src/org/netbeans/modules/xml/XMLDataObject.java, ide/xml/src/org/netbeans/modules/xml/text/TextEditorSupport.java, java/ant.debugger/src/org/netbeans/modules/ant/debugger/DebuggerAntLogger.java, java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/db/DBMetaDataProvider.java, java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintsParser.java, java/java.sourceui/src/org/netbeans/modules/java/source/ui/OpenProjectFastIndex.java, platform/openide.compat/src/org/openide/util/WeakListener.java, platform/openide.filesystems/src/org/openide/filesystems/Repository.java, platform/sampler/src/org/netbeans/modules/sampler/SamplesOutputStream.java, websvccommon/websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/wsdl/impl/WsdlModelerFactory.java
Cleanup raw type warnings related to WeakReference.
[repeat] /home/bwalker/src/netbeans/platform/openide.compat/src/org/openide/util/WeakListener.java:921: warning: [rawtypes] found raw type: WeakReference
[repeat]     private static final class ListenerReference extends WeakReference implements Runnable {
[repeat]                                                          ^
[repeat]   missing type arguments for generic class WeakReference<T>
[repeat]     T extends Object declared in class WeakReference
[repeat] /home/bwalker/src/netbeans/platform/openide.compat/src/org/openide/util/WeakListener.java:922: warning: [rawtypes] found raw type: Class
[repeat]         private static Class lastClass;
[repeat]                        ^
[repeat]   missing type …
=> Cleanup raw type warnings related to WeakReference.

java/java.lsp.server/nbcode/nbproject/platform.properties
This is a very simple change - just removing `ide/defaults` module from NBLS distribution. The module contains shortcuts and color definitions, which are not needed at all in the headless case. But those definitions reference actual actions that might not be included and they print exceptions to log in various situations where the registrations are lazy-loaded.
=> Remove IDE defaults from NBLS distribution.

java/java.source/src/org/netbeans/modules/java/classfile/AttachSourcePanel.form, java/java.source/src/org/netbeans/modules/java/classfile/AttachSourcePanel.java, java/java.source/src/org/netbeans/modules/java/classfile/Bundle.properties, java/java.source/src/org/netbeans/modules/java/classfile/CodeGenerator.java, java/java.source/src/org/netbeans/modules/java/classfile/SideBarFactoryImpl.java, java/java.source/test/unit/src/org/netbeans/modules/java/classfile/CodeGeneratorTest.java
While working with scala libraries I found it misleading that the original source is assumed to be `.java`. The source name is usually encoded in the `.class` file and this PR extracts it, when available:
Seeing the `IR.scala` name can help the developer locate the right file on disk.
=> Extract and display original file name from disassembled .class

extide/gradle/src/org/netbeans/modules/gradle/execute/navigator/TasksPanel.java
The shared variable `currentP` can be sometimes turned to `null` when a worker is already planned (but did not execute, or is executing) to the RP. 
The PR should pass the `currentP` to the worker task, and the task checks if its view of what is `currentP` is still accurate before executing.
=> Sync fixes: currentP can be seen as null by workers.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/TestProgressHandler.java, java/java.lsp.server/vscode/src/testAdapter.ts
Support for expanding Spock tests marked with `@Unrolled` annotation in VSCode Test Explorer.
=> Expand unrolled spock tests.

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java, java/java.sourceui/apichanges.xml, java/java.sourceui/nbproject/project.properties, java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementHeaders.java, java/java.sourceui/src/org/netbeans/modules/java/source/ui/LspElementUtils.java, java/refactoring.java/nbproject/project.xml, java/refactoring.java/src/org/netbeans/modules/refactoring/java/callhierarchy/LspCallHierarchyProvider.java
Call hierarchy implementation for LSP throws an exception:
```
at org.netbeans.modules.refactoring.java.callhierarchy.CallHierarchyTasks$CallersTask.runTask(CallHierarchyTasks.java:313)
[catch] at org.netbeans.modules.refactoring.java.callhierarchy.CallHierarchyTasks$CallTaskBase.run(CallHierarchyTasks.java:288)
at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```
on a trivial source:
```
package org.yourcompany.yourproject;
public class Locations {
private void m1() {
m2();
}
private void m2() {
m3();
}
private …
```
=> Support invocation expressions in LSP Call Hierarchy; bugfixes

java/java.lsp.server/vscode/package.json
The regexps were too strict: if NBLS was started in dark L&F it serves icons with `_dark` suffix (it has to be probably fixed in IconUtilities - the base URI should not contain these decorations). But it's sufficient now to just not specify the icon extension as the regexp matches all suffixes.
=> Replace _dark and svg icon variant in VSCode

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java, extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java, extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleArtifactStore.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java, extide/gradle/test/unit/src/org/netbeans/modules/gradle/NbGradleProjectImplTest.java
The goal of this PR is to ensure that sample project (`micronaut-core` was used) is loaded through Gradle daemon just for the first time and second time it is opened is loaded solely from the cache, provided the buildscripts did not change.
In fact currently the project loads each time because of several issues - explanations are done inline in the diff. Please review carefully. Overview:
- race condition in project load. 2nd opinion of fix strategy is needed here.
- excluded more configuration, useless from the (current state of the) IDE - we have only rudimentary support for Kotlin
- artifacts files fetched recursively, similar to modules, to populate `jvm_resolved_artifacts`
- excluded abstract modules that only serve as variant selectors
- artifact cache logic fixes
I've added a …
=> Fix project load caching

php/php.code.analysis/src/org/netbeans/modules/php/analysis/ImportantFilesImpl.java, php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/PHPStan.java
This change adds `phpstan.dist.neon` to Important files.
PHPStan 1.4.7 added `phpstan.dist.neon` as configuration file.
https://github.com/phpstan/phpstan/releases/tag/1.4.7
---
=> PHPStan alternative configuration file

java/java.platform/src/org/netbeans/modules/java/platform/classpath/PlatformClassPathProvider.java
The source path currently contains directories for all modules, and the compiler is confused and reads wrong `module-info.java`. As an attempt to fix this, lets try to filter the source path to contain only the one appropriate source root, and lets see how it works.
=> [3911] Filter source roots to avoids clashes between module-info files.

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
It seems that `getResolvedVariant()` can be sometimes null in the case of resolved component - need to check for null here. Gradle sources (serializer) assume that getExternalVariant() is never null (as it is Optional).
The fix is conservative = if no resolved variant -> cannot check for externality -> pass on as a dependency.
=> Fixing potential NPE.

java/java.editor/src/org/netbeans/modules/editor/java/AutoImport.java, java/java.editor/test/unit/src/org/netbeans/modules/editor/java/JavaCodeTemplateProcessorTest.java, java/java.source.base/src/org/netbeans/api/java/source/TypeUtilities.java, java/java.source.base/test/unit/src/org/netbeans/api/java/source/TypeUtilitiesTest.java
An attempt to fix:
https://github.com/apache/netbeans/issues/3803
Printing/handling of captured type which contain type variables feels weird, this is trying to improve that, although I am not sure what (if anything) will be broken by it.
---
=> [3803]Fixing printing of type names for captured types with type variables.

ide/csl.api/src/org/netbeans/modules/csl/spi/GsfUtilities.java
Usually the GSF Languages use `sanitizing` source code to get some reasonable output from parsers. This means that the source is parsed and if there is not usable result, then the edited code is somehow change and parsed again. When the second attempt doesn't returns anything useful, then is used different sanitization and again parsed. 
A sanitization needs to know, where the last change was made, which is usually taken from caret position. In NetBeans this position is taken form opened JTextComponent. In the VSCode case, the components are not opened and caret position is set to -1. Then the edited source is not sanitized correctly. 
This fix is trying to take the possition from SourceModificationEvent.
=> Taking caret offset from SourceModificationEvent.

java/java.lsp.server/nbproject/project.properties, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/LspTreeViewServiceImpl.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/PathFinder.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/ProjectExplorer.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/FindPathParams.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/TreeViewService.java, java/java.lsp.server/vscode/package.json, java/java.lsp.server/vscode/src/explorer.ts, java/java.lsp.server/vscode/src/extension.ts, java/java.lsp.server/vscode/src/protocol.ts
This PR adds a new message client > NBLS to the TreeView LSP protocol: find path from a certain root to some data => tuple of node ids. It is now only implemented for Projects view, which delegates to `PathFinder`s of the individual projects to do the searching job.
The vscode client uses this message to find a path in its Projects tree view in order to **reveal** the position of the current editor. This PR adds automatic synchronization (default: on), a setting to manage it (`netbeans.revealActiveInProjects`) true / false and an explicit command `java.select.editor.projects` to reveal the position manually - can be bound to some keyboard shortcut.
=> [vscode] Project View synchronizes with the active editor.

java/java.sourceui/src/org/netbeans/modules/java/source/ui/LspElementUtils.java, java/refactoring.java/src/org/netbeans/modules/refactoring/java/callhierarchy/CallHierarchyTasks.java, java/refactoring.java/src/org/netbeans/modules/refactoring/java/callhierarchy/LspCallHierarchyProvider.java
This PR adds necessary checks to avoid NPE. Also CompilationController phase is advanced so the level required by later queries. There's one [functional change](https://github.com/apache/netbeans/pull/3979/files#diff-aedca9ee0932ddf7ad79f4c605251d11739cc4feb43a6fac994cfbefb1515ef4R294) - the hierarchy must be build with `true` for incoming (CALLER) and false for outgoing (CALLEE) hierearchies.
Fixes #3967.
=> 3967: Avoid NPEs, assure compilation phase.

platform/libs.flatlaf/external/binaries-list, platform/libs.flatlaf/external/flatlaf-2.1-license.txt, platform/libs.flatlaf/nbproject/project.properties, platform/libs.flatlaf/nbproject/project.xml
Update FlatLaf to v2.1: https://github.com/JFormDesigner/FlatLaf/releases/tag/2.1
This release significantly improves the usability of submenus. It makes it much easier to move the mouse into a submenu without the risk that the submenu is hidden.
Previously, you have to move the mouse on the **red** path, otherwise the submenu will be hidden.
Now, you can move the mouse on the **green** path, over other menu items.
=> Update FlatLaf from 2.0.1 to 2.1

platform/openide.util/test/unit/src/org/openide/util/BaseUtilitiesTest.java
[improved tests for BaseUtilities.toFile & BaseUtitities.toURI](https://github.com/apache/netbeans/commit/6649d1f5fadff535595676e784eca06ac69e7e9d)
split "testFileURI" method into multiple seperated methods
added tests checking whether exception are thrown properly
removed "testFieURI"
=> improved tests for BaseUtilities.toFile & BaseUtitities.toURI

java/debugger.jpda.ui/nbproject/project.properties, java/debugger.jpda.ui/nbproject/project.xml, java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/models/CallStackActionsProvider.java, java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/models/DebuggingActionsProvider.java
Often, when debugging, I hit a breakpoint, but I'd like to know what is going to happen later, when the method call returns. Stepping out, is an option, but not really pleasant when there is a deep stack in between top place and the desired frame. NetBeans already supports _method breakpoint_ - just placing it is a huge pain. This PR simplifies that by adding _Add breakpoint..._ action to each `CallStackFrame`:
One the action is invoked a classical method breakpoint dialog is shown, but with pre-filled class and method names:
all one needs to do is to fill for example condition `n == 4` and press OK. When the execution continues, it stops in the desired frame.
This is particularly useful when debugging application without a source code, or written in a different language than Java.
=> Action to create a method breakpoint on a stackframe

.github/workflows/main.yml
testing...
looks like it worked
I force pushed while this was running:
https://github.com/apache/netbeans/actions/runs/2097239880
which got canceled and the next run started:
https://github.com/apache/netbeans/actions/runs/2097326632
possible risks:
- the new run will remain queued while the old is being canceled, it might not be able to kill all jobs right away
- you will get a mail :)
=> cancel previous CI run on repeated PR update.

apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/ui/customizer/CustomizerSources.form, apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/ui/customizer/CustomizerSources.java, apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/ui/customizer/SingleModuleProperties.java
The Ant APISupport UI only showed a hard-coded list of possible Java source levels for platform modules. This was a complaint raised by someone on users@. This is a quick fix to show levels up to that of the selected Java platform. (I couldn't see an API to get the supported levels directly? Would be useful).
=> Show source levels of Java platform in Ant APISupport UI.

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java, extide/gradle/src/org/netbeans/modules/gradle/GradleReport.java, extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java
My intention was to fix this notification, by adding an appropriate toString() method to GradleReport. Though it seems the project where I've got this was generating an NPE in LegacyProjectLoader. Which root cause was that, the recently introduced method call of getExternalVariant() was added only Gradle 6.8
=> Fix GradleReport Notification and potential NPE on Gradle earlier, than 6.8

java/java.source.base/src/org/netbeans/modules/java/source/NoJavacHelper.java, java/java.source/src/org/netbeans/modules/java/source/JBrowseModule.java
NetBeans 14 expects javac 18 which means we have to increment the version for the javac checks too.
=> version bump: require javac 18.

extide/gradle/src/org/netbeans/modules/gradle/GradleProjectConnection.java, extide/gradle/src/org/netbeans/modules/gradle/actions/ProjectActionMappingProviderImpl.java, extide/gradle/src/org/netbeans/modules/gradle/nodes/SubProjectsNode.java, java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/AbstractGradleClassPathImpl.java, java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImpl.java, java/gradle.java/src/org/netbeans/modules/gradle/java/nodes/BootCPNodeFactory.java, java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleCompilerOptionsQuery.java, java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceForBinary.java, java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceLevelImpl.java
As I saw some WeakListener detachment warnings in the IDE log coming from the Gradle modules, I've decided to have a look on them.
There were to types of issues:
1. No source object were given, so the detachment of the listener would not happen. That kind of Ok.
2. The NbGradleProjectImpl was passed as source instead of its NbGradlePorject so the removal could not happened.
The changes here should be trivial.
=> Fix WeakListener usage in Gradle modules

platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/AbstractViewTabDisplayerUI.java, platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/BasicScrollingTabDisplayerUI.java
=> Using the size of the tabs as minimum size.

java/refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/MoveTransformer.java, java/refactoring.java/test/unit/src/org/netbeans/modules/refactoring/java/test/RenamePackageTest.java
When a package is renamed, reference to it in the `opens` directive is not renamed - fixed. See:
https://github.com/apache/netbeans/issues/3921
=> [3921] Correctly handling opens directive in package rename.

java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
one fails, the other errors. Lets see if disabling the two would allow the rest to pass.
so that we can have a green delivery/master until the issue is resolved.
=> disable failing tests until resolved.

java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java, java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementJavadoc.java
Attempting to fix javadoc computation when there's not package clause. Should fix the `java.lsp.server`'s `ServerTest`.
=> Fixing ElementJavadoc for files without package clause.

apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardPanelVisual.java
- use dev snapshot as fallback instead of RELEASE90
- sort the version list properly, newest first
- filter out non-apache releases
second commit is the usual language lvl cleanup, first commit has the fixes.
=> new nb module project wizard improvements.

nbbuild/rat-exclusions.txt
netbeans-license job show issue for  files in ISSUE_TEMPLATE folder
https://github.com/apache/netbeans/tree/master/.github/ISSUE_TEMPLATE
We can ignore by merging this PR.
=> ignore ISSUE_TEMPLATE for rat

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java, java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/project/ProjectAlertPresenter.java
The messages are reported through LSP request that does not support html or markdown, html tags should be stripped.
=> Strip HTML tags from project problem messages

java/java.lsp.server/nbcode/nbproject/platform.properties
On startup, NBLS logs the following exception:
```
rg.osgi.framework.BundleException: The bundle "com.jcraft.jsch_0.1.72 [161]" could not be resolved. Reason: Missing Constraint: Require-Bundle: libs.c.kohlschutter.junixsocket; bundle-version="0.0.0"org.osgi.framework.BundleException: The bundle "com.jcraft.jsch_0.1.72 [161]" could not be resolved. Reason: Missing Constraint: Require-Bundle: libs.c.kohlschutter.junixsocket; bundle-version="0.0.0" at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolverError(AbstractBundle.java:1332) at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolutionFailureException(AbstractBundle.java:1316) at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:323) at …
```
=> Add necessary dependencies for com.jcraft.jsch

java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java
Bumped into the following, while the IDE tried to index the Gradle project:
```
java.lang.ClassCastException: class com.sun.tools.javac.code.Type$UnknownType cannot be cast to class com.sun.tools.javac.code.Type$ClassType (com.sun.tools.javac.code.Type$UnknownType and com.sun.tools.javac.code.Type$ClassType are in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @29bfa8a1)
at org.netbeans.modules.java.source.indexing.VanillaCompileWorker$3.visitClass(VanillaCompileWorker.java:694)
at org.netbeans.modules.java.source.indexing.VanillaCompileWorker$3.visitClass(VanillaCompileWorker.java:535)
at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
at …
```
=> Prevent Type.Unknown to be cast to ClassType in VanilaCompileWorker

ide/db/src/org/netbeans/modules/db/explorer/dlg/NewConnectionPanel.java, ide/db/src/org/netbeans/modules/db/util/Bundle.properties, ide/db/src/org/netbeans/modules/db/util/DriverListUtil.java, ide/db/src/org/netbeans/modules/db/util/JdbcUrl.java, ide/db/test/unit/src/org/netbeans/modules/db/util/DriverListUtilTest.java
Add support for Amazon Athena and Amazon Redshift connections in the IDE's database connection wizard.
Also ensure that the sample JDBC URL is properly shown when the user changes the URL type from the dropdown.
=> Add Athena/Redshift to Add Connection wizard

platform/sampler/nbproject/project.properties, platform/sampler/nbproject/project.xml, platform/sampler/src/org/netbeans/modules/sampler/InternalSampler.java, platform/sampler/src/org/netbeans/modules/sampler/SamplesOutputStream.java, platform/sampler/src/org/netbeans/modules/sampler/SelfSampleVFS.java, platform/sampler/test/unit/src/org/netbeans/modules/sampler/SamplerTest.java
We are trying to use [sampler module in our application](https://github.com/enso-org/enso/pull/3389), but we realized it has a lot of unnecessary dependencies. Ideally we just use the `org-netbeans-modules-sampler.jar` on its own - should in most cases work until one calls into `InternalSampler` - we don't.
However even if one uses `InternalSampler` there are some obsoleted dependencies that make the module [too heavyweight](http://wiki.apidesign.org/wiki/HeavyWeight). This PR clears them:
- using just simpler progress API
- using `FileObject.getLookup()`
- avoiding dialogs in favor of "exception like" report
=> Sampler module has a lot of obsolete dependencies

ide/libs.truffleapi/nbproject/project.xml, platform/core.network/src/org/netbeans/core/network/proxy/NbProxySelector.java
It seems we missed some API changes in truffle and are not exporting a required API package. Because of that, when NB starts on JDK11 _and_ in an environment that provides `http://wpad/wpad.dat`, the following exception is printed at startup:
```
WARNING [org.netbeans.core.network.proxy.ProxyAutoConfig]: There was a catastrophic error with the PAC script downloaded from http://wpad/wpad.dat. Will use dummy instead. Error was : 
org.graalvm.polyglot.PolyglotException: java.lang.NoClassDefFoundError: com/oracle/truffle/api/exception/AbstractTruffleException while loading com.oracle.truffle.regex.RegexSyntaxException; see http://wiki.netbeans.org/DevFaqTroubleshootClassNotFound
at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:250)
at …
```
=> Proxy selector fixes

java/libs.nbjavacapi/manifest.mf
=> Adjust spec version to differ from Apache NetBeans 14 for java/libs.nbjavac
