ide/lib.terminalemulator/src/org/netbeans/lib/terminalemulator/Line.java
ide/lib.terminalemulator/src/org/netbeans/lib/terminalemulator/MyFontMetrics.java
ide/lib.terminalemulator/src/org/netbeans/lib/terminalemulator/Sel.java
ide/lib.terminalemulator/src/org/netbeans/lib/terminalemulator/Term.java

Partial fix for incorrect HiDPI handling in terminal. This patch fixes only cursor position, not text selection.

[NETBEANS-819] partial fix for cursor. Text selection does't work

---

php/php.refactoring/src/org/netbeans/modules/refactoring/php/findusages/PhpWhereUsedQueryPlugin.java

https://issues.apache.org/jira/browse/NETBEANS-5048
Allows to cancel Find Usages action in PHP editor.

[NETBEANS-5048] PHP - cancel Find Usages action

---

nbbuild/cluster.properties

I am not even sure what the cluster.properties does, but since I want my #2357 to be in the next distribution, I guess this is what I have to do?!

[NETBEANS-5054] include web.bootsfaces in cluster.properties #2357

---

php/php.dbgp/src/org/netbeans/modules/php/dbgp/packets/RequestedUrlEvalCommand.java

https://issues.apache.org/jira/browse/NETBEANS-4217
Adds port to URL displayed in Requested URL output.

[NETBEANS-4217] Display port number in requested URL in PHP Debugger

---

.github/workflows/main.yml
php/php.dbgp/src/org/netbeans/modules/php/dbgp/Bundle.properties
php/php.dbgp/src/org/netbeans/modules/php/dbgp/ConnectionErrMessage.form
php/php.dbgp/src/org/netbeans/modules/php/dbgp/ConnectionErrMessage.java
php/php.project/src/org/netbeans/modules/php/project/ui/options/PhpOptions.java

- https://issues.apache.org/jira/browse/NETBEANS-5060
- https://xdebug.org/docs/upgrade_guide
- Improve the connection error message panel
- Change the default debugging port from 9000 to 9003

[NETBEANS-5060] Add information for Xdebug 3 to the ConnectionErrMessage panel

---

enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/completion/Bundle.properties
enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/completion/JsfCompletionItem.java

The JSF tag attribute help now shows the default value, if available.

[NETBEANS-5057] Improved support for JSF composite components

---

ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/CustomIndexerImpl.java

As noted by @junichi11 in #2324. Sorry for trouble!

Removing debug output.

---

platform/openide.explorer/apichanges.xml
platform/openide.explorer/nbproject/project.properties
platform/openide.explorer/src/org/openide/explorer/view/TreeView.java

Well, I'd never thought I'd contribute to the openide.explorer API. Though here is a trivial one. That would help me resolve some UI glitches on the Gradle Navigator.

[NETBEANS-5146] Add ScrollOnExpand property to TreeView

---

java/java.editor/src/org/netbeans/modules/java/editor/codegen/DelegateMethodGenerator.java
java/java.editor/src/org/netbeans/modules/java/editor/codegen/EqualsHashCodeGenerator.java
java/java.editor/src/org/netbeans/modules/java/editor/codegen/LoggerGenerator.java
java/java.editor/src/org/netbeans/modules/java/editor/codegen/ToStringGenerator.java
java/java.lsp.server/nbproject/project.xml
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/CodeGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ConstructorGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/DelegateMethodGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/EqualsHashCodeGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/GetterSetterGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ImplementOverrideMethodGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/LoggerGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeClientWrapper.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeLanguageClient.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/QuickPickItem.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ShowInputBoxParams.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ShowQuickPickParams.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ToStringGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.lsp.server/vscode/package-lock.json
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts
java/java.lsp.server/vscode/src/protocol.ts

Following actions are provided:
- Generate Constructor
- Generate Getters/Setters
- Generate equals() and hashCode()
- Generate toString()
- Generate Delegate Methods
- Generate Override/Implement Method
- Generate Logger

Existing CodeGenerators exposed as CodeActions via LSP.

---

java/javadoc/src/org/netbeans/modules/javadoc/hints/Analyzer.java
java/javadoc/test/unit/src/org/netbeans/modules/javadoc/hints/Analyzer2Test.java

https://issues.apache.org/jira/browse/NETBEANS-5034

[NETBEANS-5034] fix wrong javadoc error hint

---

ide/selenium2/src/org/netbeans/modules/selenium2/api/Selenium2Support.java
java/selenium2.maven/src/org/netbeans/modules/selenium2/maven/Selenium2MavenSupportImpl.java

see https://issues.apache.org/jira/projects/NETBEANS/issues/NETBEANS-5122

[NETBEANS-5122] fix problem when selecting selenium test framework immediately modifies pom.xml

---

extide/gradle/apichanges.xml
extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java
extide/gradle/src/org/netbeans/modules/gradle/cache/AbstractDiskCache.java
extide/gradle/src/org/netbeans/modules/gradle/options/GradleExperimentalSettings.java
extide/gradle/src/org/netbeans/modules/gradle/options/SettingsPanel.java
extide/gradle/src/org/netbeans/modules/gradle/spi/GradleSettings.java
extide/gradle/test/unit/src/org/netbeans/modules/gradle/AbstractGradleProjectTestCase.java

And deprecate experimental settings.

[NETBEANS-5206] Enable LazyOpen on Gradle Projects

---

webcommon/javascript.nodejs/src/org/netbeans/modules/javascript/nodejs/ui/resources/npm.svg

https://issues.apache.org/jira/browse/NETBEANS-4092
Changed size of image in npm.svg to match npm.png size.

[NETBEANS-4092] Fix npm logo size

---

extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java

Well this is not a fix for the issue, just helps to discover the circumstances.

[NETBEANS-5197] Add gradle user home on distribution manager toString()

---

java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceExpressionBasedMethodFix.java
java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceFieldFix.java
java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceFixBase.java
java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceMethodFix.java
java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceVariableFix.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.lsp.server/vscode/src/extension.ts

On proper selection, the following CodeActions should appear:
- Introduce Variable...
- Introduce Constant...
- Introduce Field...
- Introduce Method...

Make IntroduceElement fixes available as LSP CodeActions.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java

Refresh hints in VSCode editor.

[NETBEANS-4996] Refresh hints in VSCode editor.

---

java/java.editor/src/org/netbeans/modules/editor/java/GoToSupport.java
java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/queries/DefaultSourceLevelQueryImpl.java
java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/queries/SourceJavadocAttacherUtil.java
java/java.lsp.server/nbproject/project.xml
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java

Go to definition modified to download missing sources if necessary.

LSP: Go to definition enhanced with possible sources download

---

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleAccess.java

The issue that we fix here hurts some debugger actions when Truffle is loaded.
It's necessary to assure that the breakpoint event interceptor is removed as soon as it's not needed, event if it wasn't used.

Be sure to remove breakpoint event interceptor, when it wasn't used.

---

java/java.hints/src/org/netbeans/modules/java/hints/errors/CreateClassFix.java
java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceExpressionBasedMethodFix.java
java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceFieldFix.java
java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceMethodFix.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.source.base/src/org/netbeans/api/java/source/TreeMaker.java

- [GR-28621] Introduce Field & Constant replaces all occurrences in all classes in single .java file
- [GR-28623]  IllegalStateException thrown from CreateOuterClassFix

LSP codeAction fixes.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

Backport of https://github.com/apache/netbeans/pull/2657

[NETBEANS-5229] Fixing mapping of jar:file URI to cache and back; disabling ErrorDescriptions in cases when they should be disabled.

---

platform/o.n.swing.laf.flatlaf/manifest.mf
platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties

[NETBEANS-3428] FlatLaf: fix selection background color in output view

---

groovy/gradle/manifest.mf
groovy/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java

[NETBEANS-4722] Add JAVA_HOME to Gradle build environment variables

---

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/impl/TruffleEvaluator.java
java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/JPDADebuggerImpl.java
java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/JavaEvaluator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java

Corrections of Truffle evaluations through LSP.

Fix of tooltip and evaluations of Truffle languages through LSP.

---

nbbuild/binaries-default-properties.xml
nbbuild/default-properties.xml
nbbuild/installer/infra/build/build.sh
nbi/engine/build.xml
nbi/engine/external/applemenu-external-desktop-classes-8.2-license.txt
nbi/engine/external/binaries-list
nbi/engine/src/org/netbeans/installer/utils/system/launchers/impl/CommonLauncher.java
nbi/engine/src/org/netbeans/installer/wizard/containers/InitializeMacJDK8.java
nbi/engine/src/org/netbeans/installer/wizard/containers/InitializeMacJDK9.java
nbi/engine/src/org/netbeans/installer/wizard/containers/SwingFrameContainer.java

This is a backport of #2211. It seems after all Jenkins needs this to build the release artifacts.

[NETBEANS-3342] Fix Netbeans Installer on macOS to work with Java 8 and 11+

---

php/php.phpdoc/manifest.mf
php/php.phpdoc/nbproject/project.xml
php/php.phpdoc/src/org/netbeans/modules/php/phpdoc/PhpDocScript.java
php/php.phpdoc/src/org/netbeans/modules/php/phpdoc/PhpDocumentorProvider.java
php/php.phpdoc/src/org/netbeans/modules/php/phpdoc/ui/PhpDocPreferences.java
php/php.phpdoc/src/org/netbeans/modules/php/phpdoc/ui/PhpDocPreferencesValidator.java
php/php.phpdoc/src/org/netbeans/modules/php/phpdoc/ui/customizer/Bundle.properties
php/php.phpdoc/src/org/netbeans/modules/php/phpdoc/ui/customizer/PhpDocPanel.form
php/php.phpdoc/src/org/netbeans/modules/php/phpdoc/ui/customizer/PhpDocPanel.java

https://issues.apache.org/jira/browse/NETBEANS-5244
- Add settings for an XML configuration file
- Add parameters (`--config /path/to/configuration/file.xml`)

[NETBEANS-5244] Add the project settings for XML configuration of phpDocumentor

---

php/php.project/manifest.mf
php/php.project/nbproject/project.xml
php/php.project/src/org/netbeans/modules/php/project/ui/PhpVersionStatusLineElementProvider.java

https://issues.apache.org/jira/browse/NETBEANS-5245
- Show a PHP Version of project properties on the status bar
- We click a specific version number of the version list, we can change the PHP Version to it without opening a project properties dialog

[NETBEANS-5245] Show and change the PHP Version of project properties on the status bar

---

java/java.lsp.server/build.xml

Adding `--baseImagesUrl` option to the extension's build script.

Fix broken links to images in the extension's readme.

---

java/java.lsp.server/vscode/src/extension.ts

Language Server should be restarted whenever an extension providing its part (e.g. nbjavac) is installed/uninstalled.

Restart NBLS when an extension providing some NB cluster is installed/uninstalled.

---

ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/FoldManagerImpl.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandler.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

Reorganizing LSP client background tasks, so that the tasks are run even if the server is restarted.

 Adding folding range via LSP support, both client and server.

---

ide/gsf.testrunner.ui/nbproject/project.xml
ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/api/TestMethodController.java
ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/api/TestMethodDebuggerProvider.java
ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/api/TestMethodRunnerProvider.java
java/java.lsp.server/nbcode/nbproject/platform.properties
java/java.lsp.server/nbproject/project.xml
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchRequestHandler.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/vscode/src/extension.ts
java/java.testrunner.ui/nbproject/project.properties
java/java.testrunner.ui/nbproject/project.xml
java/java.testrunner.ui/src/org/netbeans/modules/java/testrunner/ui/ComputeTestMethodsImpl.java
java/java.testrunner.ui/src/org/netbeans/modules/java/testrunner/ui/spi/ComputeTestMethods.java
java/junit.ui/nbproject/project.xml
java/junit.ui/src/org/netbeans/modules/junit/ui/actions/TestClassInfoTask.java
java/junit.ui/src/org/netbeans/modules/junit/ui/actions/TestSingleMethodSupport.java
java/testng.ui/nbproject/project.xml
java/testng.ui/src/org/netbeans/modules/testng/ui/actions/TestClassInfoTask.java

In cooperation with @jlahoda we propose pre-computation of test methods and code lens annotations in VSCode allowing to easily Run/Debug test methods and main methods.

LSP code lens for running tests and main methods.

---

ide/projectui/src/org/netbeans/modules/project/ui/problems/BrokenReferencesCustomizer.java
ide/projectui/src/org/netbeans/modules/project/ui/problems/BrokenReferencesImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractLspStatusDisplayer.java

This PR aims to solve issues with newly opened projects in headless environment  (required by LSP server). Project problems UI demand an interactive GUI, which can be partly handled by `DialogDisplayer` implementation for headless env. In an absence of better interaction with the user, all reported problems that can be fixed are attempted to be fixed. Results are reported using StatusDisplayer.

Project problems are resolved in headless environment.

---

nb/welcome/src/org/netbeans/modules/welcome/resources/Bundle.properties
platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties

https://issues.apache.org/jira/browse/NETBEANS-5268
I would like to suggest some small colour changes in the Welcome Screen.
Please refer to the issue link above and the discussion in #1826 for details.

[NETBEANS-5268] Alter Welcome Screen colours for readability

---

ide/notifications/src/org/netbeans/modules/notifications/center/NotificationCenterTopComponent.java

Similar fix as PR #2642, but for details view in notifications window.
https://issues.apache.org/jira/browse/NETBEANS-5026

[NETBEANS-5026] Fix wheel/trackpad scrolling in notifications details window

---

cpplite/cpplite.debugger/external/binaries-list
cpplite/cpplite.debugger/external/cpplite-mi-f8f8250283be-license.txt
cpplite/cpplite.debugger/nbproject/project.properties
cpplite/cpplite.debugger/nbproject/project.xml
nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java
nbbuild/binaries-default-properties.xml
nbbuild/build.xml
platform/core.multitabs/src/org/netbeans/core/multitabs/impl/DocumentSwitcherTable.java

Sync delivery to release123 for beta1.

Sync delivery to release123 for beta1

---

cpplite/cpplite.debugger/external/binaries-list
cpplite/cpplite.debugger/external/cpplite-mi-f8f8250283be-license.txt
cpplite/cpplite.debugger/nbproject/project.properties
cpplite/cpplite.debugger/nbproject/project.xml
nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java
nbbuild/binaries-default-properties.xml
nbbuild/build.xml
platform/core.multitabs/src/org/netbeans/core/multitabs/impl/DocumentSwitcherTable.java

Sync delivery to master post beta 1

Sync delivery to master post beta 1

---

ide/html.editor/src/org/netbeans/modules/html/editor/api/completion/HtmlCompletionItem.java
ide/web.common.ui/src/org/netbeans/modules/web/common/ui/api/FileReferenceCompletion.java

https://issues.apache.org/jira/browse/NETBEANS-5301
- Fixes color of elements in code completion.
- Fixes color of directories in code completion.
- Simplifies code for completion item coloring.

[NETBEANS-5301] Fixed readability of HTML code completion items

---

java/java.editor/src/org/netbeans/modules/editor/java/GoToSupport.java
java/java.editor/src/org/netbeans/modules/java/editor/overridden/ComputeOverriders.java
java/java.hints/src/org/netbeans/modules/java/hints/errors/ImplementAllAbstractMethods.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ConstructorGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts
java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementOpen.java

- [GR-28591] Add generate constructor quick fix.
- [GR-28597] Add implement all abstract methods refactoring.
- [GR-28313] Adding keyboad shortcut for Source Actions.
- [GR-28647] Improve navigating to declaration or implementation.

LSP CodeActions enhancements.

---

platform/autoupdate.services/src/org/netbeans/spi/autoupdate/KeyStoreProvider.java

Small typo in javadoc comments for KeyStoreProvider.

Small typo in javadoc comments for KeyStoreProvider.

---

extide/gradle/netbeans-gradle-tooling/build.gradle
extide/gradle/netbeans-gradle-tooling/src/test/data/multi/build.gradle
extide/gradle/netbeans-gradle-tooling/src/test/data/simple-with-tests/build.gradle
extide/gradle/netbeans-gradle-tooling/src/test/data/unresolvable/build.gradle
extide/gradle/src/org/netbeans/modules/gradle/newproject/multi-root.gradle.template
extide/gradle/src/org/netbeans/modules/gradle/newproject/single-build.gradle.template

A reflection to: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

[NETBEANS-5336] Replace jcenter() to mavenCentral() in Gradle Projects

---

extide/gradle/src/org/netbeans/modules/gradle/GradleModuleFileCache21.java
extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProject.java
extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java
extide/gradle/src/org/netbeans/modules/gradle/api/GradleConfiguration.java
extide/gradle/src/org/netbeans/modules/gradle/api/GradleDependency.java

This one just prevents the IAE from happening on composite projects. I need a testcase and find out how to handle the dependency issues.

[NETBEANS-5161] Prevent IAE when resolving composite project dependencies

---

platform/o.n.core/src/org/netbeans/core/ui/Bundle.properties

https://issues.apache.org/jira/browse/NETBEANS-419

[NETBEANS-419] Fixed grammar in About dialog

---

nb/ide.branding/o.n.core/src/org/netbeans/core/Bundle_nb.properties

https://issues.apache.org/jira/browse/NETBEANS-5338
Link points to same URL as menu action Help > Report Issue.

[NETBEANS-5338] Updated link to issue reporting

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchRequestHandler.java

There is a delay between a message is sent to a LSP client that a project Run/Debug action termianted. I've checked the project layer, and it seems that Out/Err streams are closed / flushed before the callback is called. Also Maven implementation seems to finish the output gathering task before declaring the execution complete and so seems Gradle.
So that would allow for a "strawman" fix - just remove the delay. Please review - anyone who remembers why the delay was introduced in the original LSP client implementation. Thanks.

Removing delay after launch Project action terminates.

---

java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java

Fixing nb-javac tests failing due to bug in CasualDiff.

Fixing failing nb-javac tests.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java

Completing the merge of https://github.com/apache/netbeans/pull/2770/commits/cf30670c24d446134b12f32efa21a21ab0896fe0 into the master.

Completing the merge of delivery to master.

---

java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.lsp.server/vscode/src/testAdapter.ts

- Fixing bug in updaing the list of discovered tests.
- Fixing fails in ServerTest

[GR-29499] Fixing bug in updaing the list of discovered tests.

---

java/java.lsp.server/vscode/BUILD.md

Documenting VSNetBeans extension build.

Updates to better document the build of VSCode.

---

nbbuild/packaging/netbeans-dev_snap/snap/snapcraft.yaml
nbbuild/packaging/netbeans_snap/snap/snapcraft.yaml

Trivial, I'm going to merge this one without review.

Use GitHub to get netbeansrelease.json at Snap builds

---

extide/gradle/src/org/netbeans/modules/gradle/nodes/BuildScriptsNode.java
extide/gradle/src/org/netbeans/modules/gradle/queries/ProjectContainerProviderImpl.java

Trivial change. I'm going to merge this one as some of the CI successfully runs on it. I have a setup for #2747 Where I can investigate why the project detection fails and probably fix that part as well.

[NETBEANS-5484] Handle NPE when the project Gradle project discovery fails

---

java/java.j2seplatform/apichanges.xml
java/java.j2seplatform/arch.xml
java/java.j2seplatform/manifest.mf
java/java.j2seplatform/nbproject/project.xml
nbbuild/build.properties

foojay has a nice plugin in development which cannot call java.j2seplatform APIs without being a friend.
This PR adds the plugin to the friend list.

Makes java.j2seplatform API / SPI public

---

.gitattributes

Added support for Windows shell scripts (`.bat` and `.cmd`) 
Added support for Linux/MacOS shell scripts (`.sh`)

Update .gitattributes - support for shell scripts

---

java/java.lsp.server/vscode/CHANGELOG.md
java/java.lsp.server/vscode/README.md
java/java.lsp.server/vscode/package.json

LSP: Readme, changelog, and version modified for 12.4 Beta.

LSP: Readme, changelog, and version modified for 12.4 Beta.

---

cnd/cnd.remote/tools/Makefile
cnd/cnd.remote/tools/rfs_controller.c

[NETBEANS-5485][CND] cnd-rfs compile fix

---

dlight/remotefs.versioning.api/nbproject/project.xml
dlight/remotefs.versioning.api/src/org/netbeans/modules/remotefs/versioning/api/Scrambler.java
dlight/remotefs.versioning.api/test/unit/src/org/netbeans/modules/remotefs/versioning/api/ScramblerTest.java

A clean-room implementation of Scrambler.java, which is missing in the 4th Oracle Donation to the ASF.

[NETBEANS-4662][CND] Missing Scrambler.java

---

java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertSwitchToRuleSwitchTest.java
java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
java/java.source.base/test/unit/src/org/netbeans/api/java/source/gen/SwitchRuleFormattingTest.java

Fixed Formatting issues for the Hint SwitchToSwitchExpression and added test cases for the same.

[NETBEANS:4447]:Fixed NullPointerException while computing switch expression 

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/vscode/src/testAdapter.ts
java/maven.junit/src/org/netbeans/modules/maven/junit/JUnitOutputListenerProvider.java

Fixing the following problems:
- Test results are not shown on the first run
- Test explorer does not show errors in test initialization
- Tests in multi-projects are not initially loaded

Test Explorer fixes.

---

php/php.code.analysis/src/org/netbeans/modules/php/analysis/ImportantFilesImpl.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/CodingStandardsFixer.java

https://issues.apache.org/jira/browse/NETBEANS-5577
Added configuration files `.php-cs-fixer.php` and `.php-cs-fixer.dist.php` to Important files.
Reference:
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/UPGRADE-v3.md
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5607

[NETBEANS-5577] Add PHP-CS-Fixer 3.x configuration files

---

extide/gradle/apichanges.xml
extide/gradle/manifest.mf
extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java
extide/gradle/src/org/netbeans/modules/gradle/options/SettingsPanel.java

Well this one displays the locally available distributions in The Gradle Options page if for some reason we can't get the online information.

[NETBEANS-5398] Fix NPE on Gradle settings when no network connection

---

java/java.disco/src/org/netbeans/modules/java/disco/Client.java

Fixed an issue related to correct support of maintained versions in the disco api plugin

Quickfix for disco api plugin

---

nbbuild/antsrc/org/netbeans/nbbuild/ParseProjectXml.java

I had troubles identifying modules that depend on a library I wanted to exclude from the platform. I'd like to improve reporting when the build fails because of a dependency that is excluded from the target platform. Just prints a more verbose message.
It's possible to enable DEBUG log level, but that's much much more hairy.

Print dependency path for modules excluded from platform.

---

cnd/cnd.modelimpl/external/open-fortran-parser-0.7.1.2-license.txt
dlight/dlight.remote.impl/external/binaries-list
dlight/dlight.remote.impl/external/fs_server-1.0-license.txt
nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
nbbuild/licenses/BSD-llvm
nbbuild/licenses/EPL-v10-open-fortran-parser

```
ant -Dcluster.config=cnd verify-libs-and-licenses
```
shows no problems now.

[CND] verify-libs-and-licenses

---

java/java.editor/src/org/netbeans/modules/java/editor/overridden/ElementDescription.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts
java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementOpen.java

- Source Actions keyboard shortcut added.
- Go to Super Implementation keyboard shortcut added .
- Go to Super Implementation minor fixes.

LSP: Code navigation fixes

---

ide/gsf.codecoverage/src/org/netbeans/modules/gsf/codecoverage/CoverageReportTopComponent.java

Refactor call to update stats
and check if null before try to update

[NETBEANS-5528] Fix NPE in CoverageReportTopComponent as summary may be null

---

ide/api.lsp/apichanges.xml
ide/api.lsp/manifest.mf
ide/api.lsp/nbproject/project.properties
ide/api.lsp/src/org/netbeans/api/lsp/HyperlinkLocation.java
ide/api.lsp/src/org/netbeans/spi/lsp/HyperlinkTypeDefLocationProvider.java
java/java.editor/nbproject/project.xml
java/java.editor/src/org/netbeans/modules/editor/java/GoToSupport.java
java/java.editor/src/org/netbeans/modules/java/editor/hyperlink/JavaHyperlinkProvider.java
java/java.lsp.server/nbproject/project.xml
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

Adding implementation for `textDocument/typeDefinition` LSP requests.

LSP: Go to Type Definition added.

---

java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionCollector.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.sourceui/nbproject/project.xml
java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementOpen.java
java/java.sourceui/src/org/netbeans/modules/java/source/ui/JavaTypeProvider.java

- Types from project dependencies added to response to the `workspace/symbol` LSP request
- ServerTest fixed to follow recent changes in Language Server implmentation

LSP: "Go to Type" should open also types in project dependencies.

---

extide/gradle/netbeans-gradle-tooling/src/main/groovy/org/netbeans/modules/gradle/tooling/NetBeansToolingPlugin.java
extide/gradle/src/org/netbeans/modules/gradle/GradleProjectErrorNotifications.java
extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java

Well it not just fix the <br/>-s slipping into the Gradle Project Problem Dialog, but also makes some errors more in a more readable form.

[NETBEANS-5668] Fix slipping <br/>-s in the Project Problem Dialog

---

cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPLiteDebugger.java
cpplite/cpplite.debugger/test/unit/src/org/netbeans/modules/cpplite/debugger/AbstractDebugTest.java
cpplite/cpplite.debugger/test/unit/src/org/netbeans/modules/cpplite/debugger/BreakpointsTest.java
cpplite/cpplite.debugger/test/unit/src/org/netbeans/modules/cpplite/debugger/ExitTest.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java

Assure that we notify the finish of the debug/run session through LSP.

[NETBEANS-5693] Assure that debugger session finishes when native image application exits.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/vscode/src/test/suite/extension.test.ts

Adding the following LSP commands:
- `java.get.project.source.roots`
- `java.get.project.classpath`
- `java.get.project.packages`

LSP: Get project source roots, classpath, and packages commands added.

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/MicronautConfigUtilities.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionCollector.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionItem.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionTask.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautHoverProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/hyperlink/MicronautConfigHyperlinkProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/hyperlink/MicronautJavaHyperlinkProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/BasePropertiesVisual.form
enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/BasePropertiesVisual.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/Bundle.properties
enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/MicronautLaunchService.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/newproject/MicronautProjectWizardIterator.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/refactor/MicronautRefactoringFactory.java
java/java.lsp.server/nbcode/nbproject/platform.properties
java/java.lsp.server/vscode/src/extension.ts

* Code completion for Yaml should work in all Micronaut config files.
* Micronaut config support should work for Java properties files too.
* Go to Source navigation should work also for Micronaut configuration property groups. 
* Allow users to select test framework while creating Micronaut projects.

Micronaut configuration completion and navigation improvements

---

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/hints/AddImportStatementHint.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/hints/ImplementAllAbstractMethodsHint.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/hints/MakeClassAbstractHint.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/hints/RemoveUnusedImportHint.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/imports/ImportHelper.java
ide/api.lsp/apichanges.xml
ide/api.lsp/manifest.mf
ide/api.lsp/src/org/netbeans/spi/lsp/ErrorProvider.java
ide/csl.api/nbproject/project.properties
ide/csl.api/nbproject/project.xml
ide/csl.api/src/org/netbeans/modules/csl/api/EditList.java
ide/csl.api/src/org/netbeans/modules/csl/core/ApiAccessor.java
ide/csl.api/src/org/netbeans/modules/csl/core/LanguageRegistrationProcessor.java
ide/csl.api/src/org/netbeans/modules/csl/hints/GsfErrorProvider.java
java/java.hints/nbproject/project.xml
java/java.hints/src/org/netbeans/modules/java/hints/infrastructure/JavaErrorProvider.java
java/java.lsp.server/nbcode/integration/release/config/Preferences/org/netbeans/modules/java/hints/default/org.netbeans.modules.java.hints.StaticImport.properties
java/java.lsp.server/nbproject/project.xml
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/vscode/package-lock.json
java/java.lsp.server/vscode/package.json

- ErrorProvider implementation for GSF languages added
- Groovy hints foixed to work over LSP

LSP: Groovy diagnostic handling.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java

Github decided to ignore my comment to https://github.com/apache/netbeans/pull/3006
This is how I see that PR:
Apparently, Github ignores my comments and does not show it to others, maybe just because I did not start a "Review". Apparently, comments have no value without a review and are blocked from others.

Removing unused findEnabledTarget() method.

---

java/java.lsp.server/nbcode/nbproject/platform.properties
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/LspTemplateUI.java
java/java.lsp.server/vscode/package.json

Declare `oncommand:java.workspace.newproject` as an activation point for the extension.

Make sure Java: New Project... is always active

---

groovy/groovy.support/src/org/netbeans/modules/groovy/support/Bundle.properties
groovy/groovy.support/src/org/netbeans/modules/groovy/support/resources/Groovy.html
groovy/groovy.support/src/org/netbeans/modules/groovy/support/resources/layer.xml
groovy/groovy.support/src/org/netbeans/modules/groovy/support/wizard/impl/GroovyJUnitTestWizard.java
java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml

LSP: Minor fixes of Groovy templates.

LSP: Minor fixes of Groovy templates.

---

groovy/groovy.editor/nbproject/project.xml
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/FindTypeUtils.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/PathFinderVisitor.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/java/ElementDeclaration.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/language/GroovyDeclarationFinder.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/occurrences/TypeVisitor.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/occurrences/VariableScopeVisitor.java
groovy/groovy.editor/test/unit/data/testfiles/declarationfinder/Imports.groovy
groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/GroovyDeclarationFinderTest.java
groovy/groovy.support/nbproject/project.xml
groovy/groovy.support/src/org/netbeans/modules/groovy/support/actions/GroovyComputeTestMethods.java
groovy/libs.groovy/nbproject/project.xml
ide/csl.api/src/org/netbeans/modules/csl/core/LanguageRegistrationProcessor.java
ide/csl.api/src/org/netbeans/modules/csl/editor/completion/GsfCompletionProvider.java
ide/csl.api/src/org/netbeans/modules/csl/editor/completion/GsfHoverProvider.java
ide/csl.api/src/org/netbeans/modules/csl/editor/hyperlink/GoToSupport.java
ide/csl.api/src/org/netbeans/modules/csl/editor/hyperlink/GsfHyperlinkProvider.java
ide/gsf.testrunner.ui/apichanges.xml
ide/gsf.testrunner.ui/manifest.mf
ide/gsf.testrunner.ui/nbproject/project.xml
ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/api/TestMethodController.java
ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/spi/ComputeTestMethods.java
java/java.lsp.server/nbcode/nbproject/platform.properties
java/java.lsp.server/nbproject/project.xml
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/junit.ui/manifest.mf
java/junit.ui/nbproject/project.xml
java/junit.ui/src/org/netbeans/modules/junit/ui/actions/TestClassInfoTask.java

* LSP: Groovy Spock test methods finder implemented
* LSP: Hover and go to declaration implementated for Groovy

LSP: Hover, go to declaration, and code lens implementation for Groovy

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/breakpoints/GroovyBreakpointFactory.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/breakpoints/NbBreakpoint.java
java/java.lsp.server/vscode/package.json

Groovy is added as a debugger language and breakpoints language. We handle the creation of groovy line breakpoints.

Ability to add breakpoints into Groovy sources.

---

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/FindTypeUtils.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/PathFinderVisitor.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/language/GroovyDeclarationFinder.java
groovy/groovy.editor/test/unit/data/testfiles/declarationfinder/Annotations.groovy
groovy/groovy.editor/test/unit/data/testfiles/declarationfinder/a/Annotation.java
groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/GroovyDeclarationFinderTest.java

Go to declaration should work for annotations in Groovy sources.

Groovy: Go to declaration should work for annotations.

---

groovy/groovy.support/src/org/netbeans/modules/groovy/support/actions/GroovyComputeTestMethods.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java

Spock test methods found based on "org.spockframework.runtime.model.FeatureMetadata" annotation presence.

LSP: spock test discovery improvements

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchDelegate.java
java/java.lsp.server/vscode/CHANGELOG.md
java/java.lsp.server/vscode/src/test/suite/extension.test.ts

Changelog update before 12.4.301 release.

---

platform/libs.flatlaf/external/binaries-list
platform/libs.flatlaf/external/flatlaf-1.4-license.txt
platform/libs.flatlaf/nbproject/project.properties
platform/libs.flatlaf/nbproject/project.xml

This PR updates FlatLaf to latest version.
A lot of minor improvements and fixes have been made:
https://github.com/JFormDesigner/FlatLaf/releases

Update FlatLaf from 1.1.2 to 1.4

---

extide/gradle/src/org/netbeans/modules/gradle/actions/ActionToTaskUtils.java
java/java.lsp.server/vscode/src/test/runTest.ts

Regression in "run all tests" action fixed.

LSP: Run all tests action fixed in Gradle projects.

---

php/php.phpunit/src/org/netbeans/modules/php/phpunit/ui/options/Bundle.properties
php/php.phpunit/src/org/netbeans/modules/php/phpunit/ui/options/PhpUnitOptionsPanel.form
php/php.phpunit/src/org/netbeans/modules/php/phpunit/ui/options/PhpUnitOptionsPanel.java

https://issues.apache.org/jira/browse/NETBEANS-5678
- The original PHPUnit skeleton generator has been abandoned
The forked repo: https://github.com/VitexSoftware/phpunit-skeleton-generator

[NETBEANS-5678] Use the URL of the forked repository of the Skeleton Generator

---

enterprise/payara.common/src/org/netbeans/modules/payara/common/wizards/AddServerLocationPanel.java
enterprise/payara.common/src/org/netbeans/modules/payara/common/wizards/AddServerLocationVisualPanel.form
enterprise/payara.common/src/org/netbeans/modules/payara/common/wizards/AddServerLocationVisualPanel.java
enterprise/payara.common/src/org/netbeans/modules/payara/common/wizards/Bundle.properties
enterprise/payara.common/src/org/netbeans/modules/payara/common/wizards/Retriever.java
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/Bundle.properties
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/MicroProjectWizardIterator.java
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/PayaraMicroPanel.form
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/PayaraMicroPanel.java
enterprise/payara.tooling/nbproject/project.xml
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/data/PayaraPlatformVersion.java
java/maven.indexer/nbproject/project.xml
java/maven/src/org/netbeans/modules/maven/newproject/ArchetypeWizardUtils.java

This is a bug fix to return the empty list of the Payara Server version in case maven central repository not accessible from the private network.
Issue reported here: https://github.com/apache/netbeans/pull/2409#issuecomment-867782698
Issue caused by: https://github.com/apache/netbeans/pull/2409

Fixes fetching the Payara Server list in private network

---

groovy/groovy.support/src/org/netbeans/modules/groovy/support/actions/GroovyComputeTestMethods.java
java/gradle.test/src/org/netbeans/modules/gradle/test/GradleTestProgressListener.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/TestProgressHandler.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/vscode/src/testAdapter.ts
java/maven/src/org/netbeans/modules/maven/ActionProviderImpl.java
java/maven/src/org/netbeans/modules/maven/queries/MavenTestForSourceImpl.java
java/maven/test/unit/src/org/netbeans/modules/maven/newproject/simplewizard/SimpleWizardHandlerTest.java

Support for running Spock tests and display results in Test Explorer via LSP added.

LSP: Support for running Spock tests and display results.

---

java/java.mx.project/nbproject/project.xml
java/java.mx.project/src/org/netbeans/modules/java/mx/project/Compliance.java
java/java.mx.project/src/org/netbeans/modules/java/mx/project/Jdks.java
java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteClassPathProvider.java
java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteEnvEdit.java
java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteFactory.java
java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteLogicalView.java
java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteProject.java
java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteSources.java
java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/ComplianceTest.java

Using proper JDK based on `compliance` of each source root. Looks like all classes are in
```
ls graal/compiler/mxbuild/*/bin -d
```
e.g. the previous usage of subDir was incorrect.

Proper JDK & location of the binary classes in mx projects

---

java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceConstantFix.java
java/java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceFieldFix.java
java/java.lsp.server/nbcode/integration/release/config/Editors/text/x-java/Preferences/org-netbeans-modules-editor-settings-CustomPreferences.xml

Trying o fix the following problems:
- The constant is placed below the method, in Java constants typically appear at the top of the class first according to most code style standards
- The constant is not in fact a constant since it is not final

LSP: Multiple problems with introduce constant fixed.

---

java/java.disco/src/org/netbeans/modules/java/disco/FoojayPlatformInstall.java

Branding fix for Disco API as requested by @geertjanw

Fix branding reference to Foojay.io Disco API.

---

php/php.dbgp/src/org/netbeans/modules/php/dbgp/ConnectionErrMessage.form
php/php.dbgp/src/org/netbeans/modules/php/dbgp/ConnectionErrMessage.java

https://issues.apache.org/jira/browse/NETBEANS-5533
- The old wiki is available no longer (http://wiki.netbeans.org/HowToConfigureXDebug)

[NETBEANS-5533] Remove the URL of the old wiki

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java

Backporting https://github.com/apache/netbeans/pull/3082 to 12.5, if it's not too late...
The fix is quite simple and safe.

Use RequestProcessor to fix SecurityException:setContextClassLoader.

---

groovy/groovy.support/src/org/netbeans/modules/groovy/support/actions/GroovyComputeTestMethods.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/vscode/src/testAdapter.ts
java/junit.ui/src/org/netbeans/modules/junit/ui/actions/TestClassInfoTask.java

Test results should be displayed for MX projects.

LSP: Show test results for MX projects.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ExtractSuperclassOrInterfaceRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/MoveRefactoring.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

Extract Superclass and Extract Interface refactorings available via LSP.

LSP: Extract Superclass and Extract Interface refactorings added.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/CodeRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ExtractSuperclassOrInterfaceRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/MoveRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/PullUpRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/PushDownRefactoring.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

Pull Up and Push Down refactorings should be available via LSP.

LSP: Pull Up and Push Down refactorings added.

---

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleAccess.java
java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleEval.java
java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/breakpoints/TruffleLineBreakpoint.java
java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/breakpoints/impl/HitBreakpointInfo.java
java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/breakpoints/impl/TruffleBreakpointOutput.java
java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/breakpoints/impl/TruffleBreakpointsHandler.java
java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/breakpoints/impl/TruffleBreakpointsRegistry.java
java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/console/DebuggerOutput.java
java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/expr/InvocationExceptionTranslated.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/breakpoints/NbBreakpoint.java

The logging text is implemented for Truffle breakpoints, some corrections are applied to Java breakpoints and expression evaluation in the logging text.

Proper handling of LSP logging breakpoints.

---

java/api.maven/test/unit/src/org/netbeans/api/maven/MavenActionsTest.java

Just trying to execute `MavenActionsTest` test in CI environment, as it fails on CI and not locally. Trying to find out what's wrong.

Improve wait condition for the test: both Lookup and configurations must change.

---

ide/csl.api/src/org/netbeans/modules/csl/editor/codetemplates/GsfCodeTemplateFilter.java
ide/editor.codetemplates/apichanges.xml
ide/editor.codetemplates/nbproject/project.properties
ide/editor.codetemplates/nbproject/project.xml
ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/AbbrevDetection.java
ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/CodeTemplateCompletionProvider.java
ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/CodeTemplateManagerOperation.java
ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/SurroundWithFix.java
ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/spi/CodeTemplateFilter.java
java/java.editor/src/org/netbeans/modules/editor/java/JavaCodeTemplateFilter.java
java/java.editor/src/org/netbeans/modules/editor/java/Utilities.java
java/java.editor/src/org/netbeans/modules/java/editor/resources/DefaultAbbrevs.xml
java/java.lsp.server/nbproject/project.xml
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ExtractSuperclassOrInterfaceRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/MoveRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/PullUpRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/PushDownRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/SurroundWithHint.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

Surround With refactorings available via LSP.

LSP: Surround With refactorings implemented.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ChangeMethodParametersRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/CodeActionsProvider.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

ChangeMethodParameters refactoring available via LSP.

LSP: ChangeMethodParameters refactoring added.

---

ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/FoldManagerImpl.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/NavigatorPanelImpl.java

In the last few weeks I noticed two issues in the LSP Client code. One is located in the way background tasks
are queue. From my analysis identical background tasks can be schedules multiple times and executed quickly
ater one another, causing performance issues. The second is error reporting from the fold manager complaining
about being provided with identical folds multiple times.
Please refer to the individual commit messages for more information.

LSP Client Improvements (Foldmanager, Performance)

---

enterprise/j2ee.dd.webservice/src/org/netbeans/modules/j2ee/dd/impl/webservices/WebServicesProxy.java
enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/application/ApplicationProxy.java
enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/client/AppClientProxy.java
enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/common/ComponentBeanMultiple.java
enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/ejb/EjbJarProxy.java
enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/web/WebAppProxy.java
enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/app/EarDataObject.java
enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/multiview/EjbJarMultiViewDataObject.java
enterprise/web.jsf/src/org/netbeans/modules/web/jsf/api/ConfigurationUtils.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/lexer/GroovyLexer.java
ide/db.sql.visualeditor/src/org/netbeans/modules/db/sql/visualeditor/querybuilder/QueryBuilder.java
ide/db.sql.visualeditor/src/org/netbeans/modules/db/sql/visualeditor/querybuilder/QueryModel.java
ide/db.sql.visualeditor/src/org/netbeans/modules/db/sql/visualeditor/querymodel/QueryNode.java
ide/jellytools.ide/src/org/netbeans/jellytools/EditorOperator.java
java/ant.debugger/src/org/netbeans/modules/ant/debugger/Utils.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/JPACodeCompletionProvider.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/entitygenerator/DbSchemaEjbGenerator.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/fromdb/DBSchemaFileList.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/fromdb/JavaPersistenceGenerator.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/fromdb/TableClosure.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/variables/ViewModel.java
java/maven.grammar/src/org/netbeans/modules/maven/grammar/MavenProjectGrammar.java
java/xml.tools.java/src/org/netbeans/modules/xml/tools/java/generator/SAXGeneratorSupport.java
javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/completion/beans/FxBean.java
platform/openide.explorer/src/org/netbeans/modules/openide/explorer/ExternalDragAndDrop.java

Cleanup a bunch of warnings related to ArrayList..
[repeat] /home/bwalker/src/netbeans/java/java.hints.ui/src/org/netbeans/modules/java/hints/analysis/AnalyzerImpl.java:98: warning: [rawtypes] found raw type: ArrayList
[repeat]         List todo = new ArrayList();
[repeat]                         ^
[repeat]   missing type arguments for generic class ArrayList<E>
[repeat]     E extends Object declared in class ArrayList

[NETBEANS-6045] - cleanup ArrayList warnings

---

platform/libs.jna.platform/external/binaries-list
platform/libs.jna.platform/external/jna-platform-5.9.0-license.txt
platform/libs.jna.platform/nbproject/org-netbeans-libs-jna-platform.sig
platform/libs.jna.platform/nbproject/project.properties
platform/libs.jna.platform/nbproject/project.xml
platform/libs.jna/external/binaries-list
platform/libs.jna/external/jna-5.9.0-license.txt
platform/libs.jna/nbproject/org-netbeans-libs-jna.sig
platform/libs.jna/nbproject/project.properties
platform/libs.jna/nbproject/project.xml

sigtest data was regenerated and checked. The changes to the interfaces
in the platform are ok:
- additions to the interfaces just expose additional native methods
- incompatible changes are fixes for functions that were broken hard
before the change and thus are either already broken or were not
used

Update JNA and JNA platform to 5.9.0

---

ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/ResultBar.java

A follow-up on https://github.com/apache/netbeans/pull/3201 which also fixes HiDPI scaling issues in the "Test Results" progress bar.
Before/after screenshots:
:

[NETBEANS-4198] Fix anti-aliasing and HiDPI scaling in the Test Results progress bar.

---

ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/RepositoryUpdater.java
java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/SdkSuiteTest.java

Invalidate existing Sources after reindexing.

An attempt to fix unstable test for java.mx.projects

---

ide/git/src/org/netbeans/modules/git/ui/history/SearchHistoryAction.java

It was limited to files, now it works on folders/projects too.

git show history should show results without having to press search

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/ni/NILocationVisualizer.java

Lines without the executable locations are shaded during native image debugging.
When a whole method was missing in the native image, its content was correctly shaded, but not the method header. This change makes sure that the method header itself (the method tree, not just the method body) is shaded as well.

Shade whole methods which are not included in the native image.

---

java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/displayer/JavaVariablesDisplayer.java

In GraalVM native image debugging, parsing of String from the native image data is corrected for JDK 9+

Correct the parsing of String values in native image.

---

extide/gradle/src/org/netbeans/modules/gradle/GradleJavaCompatProblemsProvider.java
extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java

[NETBEANS-6004] Give info when the IDE's Java is not compatible with Gradle

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ChangeMethodParametersRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/CodeActionsProvider.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ConstructorGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/DelegateMethodGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/EqualsHashCodeGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ExtractSuperclassOrInterfaceRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/GetterSetterGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ImplementOverrideMethodGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/LoggerGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/MoveRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/OrganizeImportsCodeAction.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/PullUpRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/PushDownRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/SurroundWithHint.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ToStringGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts

- Organize imports action added
- Basic options added
- Organize imports on save added

LSP: Organize imports action added.

---

php/php.editor/src/org/netbeans/modules/php/editor/resources/layer.xml
php/php.editor/src/org/netbeans/modules/php/editor/verification/ConvertVisibilitySuggestion.java
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/verification/ConvertVisibilitySuggestionTest.java

https://issues.apache.org/jira/browse/NETBEANS-6217
- Convert from SuggestionRule to HintRule
Options:

[NETBEANS-6217] Allow Convert Visibility Suggestion to be disabled

---

ide/csl.api/src/org/netbeans/modules/csl/editor/overridden/Bundle.properties
php/php.editor/src/org/netbeans/modules/php/editor/csl/OverridingMethodsImpl.java
php/php.editor/src/org/netbeans/modules/php/editor/elements/IndexQueryImpl.java
php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/csl/OverridingMethodsOverriddenTest/overriding/overridden/overridden_01.pass
php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/csl/OverridingMethodsOverridingTest/overriding/overriding/overriding_01.pass
php/php.editor/test/unit/data/testfiles/overriding/overridden/ChildClass1.php
php/php.editor/test/unit/data/testfiles/overriding/overridden/ChildClass2.php
php/php.editor/test/unit/data/testfiles/overriding/overridden/overridden_01.php
php/php.editor/test/unit/data/testfiles/overriding/overriding/ParentClass.php
php/php.editor/test/unit/data/testfiles/overriding/overriding/overriding_01.php
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/OverridingMethodsImplTestBase.java
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/OverridingMethodsOverriddenTest.java
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/OverridingMethodsOverridingTest.java

https://issues.apache.org/jira/browse/NETBEANS-2472

[NETBEANS-2472] Mark overriding/overridden constants and properties as annotations

---

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NetBeansExplodedWarPlugin.java
extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NetBeansRunSinglePlugin.java

Well, these are just some quick catches. I've missed these during the review.

Fixed some lost-in-translation issues with Gradle Tooling

---

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/CompilationUnit.java
groovy/groovy.editor/test/unit/data/testfiles/completion/issueNETBEANS6218/my/pkg/MainClass.groovy
groovy/groovy.editor/test/unit/data/testfiles/completion/issueNETBEANS6218/my/pkg/MainClass.groovy.testCompletionInMain.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/issueNETBEANS6218/my/pkg/app/ClassA.groovy
groovy/groovy.editor/test/unit/data/testfiles/completion/issueNETBEANS6218/my/pkg/app/ClassA.groovy.testCompletionInClassA.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/issueNETBEANS6218/my/pkg/impl/ClassB.groovy
groovy/groovy.editor/test/unit/data/testfiles/completion/issueNETBEANS6218/my/pkg/impl/ClassB.groovy.testCompletionInClassB.completion
groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/IssueNETBEANS6218.java

[NETBEANS-6218] An infinite loop may occur when parsing Groovy sources

---

extide/gradle/test/unit/src/org/netbeans/modules/gradle/queries/InfoTest.java

I've accidentally missed these test from  #3307

[NETBEANS-5783] Testcase checking Gradle ProjectInfo never return null

---

php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptions.java

https://issues.apache.org/jira/browse/NETBEANS-6239
Added PHPStan rule level 9.
Announcement: https://phpstan.org/blog/phpstan-1-0-released#level-9

[NETBEANS-6239] Add PHPStan rule level 9

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionTask.java

Check for `@Repository` annotation fixed.

Micronaut Data Finder completion check for @Repository annotation fixed.

---

groovy/groovy.support/nbproject/project.properties
groovy/groovy.support/nbproject/project.xml
groovy/groovy.support/src/org/netbeans/modules/groovy/support/actions/singlefilerun/JPDAStart.java
groovy/groovy.support/src/org/netbeans/modules/groovy/support/actions/singlefilerun/SingleGroovySourceRunActionProvider.java

This is attempt to run a Groovy script without a project. It implements Run File action that runs the scrip through java. For execution is used Groovy that is inside NB and is used by parsing files in editor.
A Groovy file is basically with this command:
`${default_java_platform} -cp .:${path_to_groovy_binaries} groovy.ui.GroovyMain ${file}`
`defuault_java_patform` is taken from `JavaPlatformManager`
`path_to_groovy_binaries` is where `org-netbeans-modules-libs-groovy.jar` is installed
Groovy script is not run directly, but as parameter of `groovy.ui.GroovyMain` class execution

[NETBEANS-6253] Posibility to run single Groovy Script

---

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/language/GroovyDeclarationFinder.java

This fix doesn't cover all cases, but at least in the simple cases it works.

[NETBEANS-6291] Navigation to fields sometimes doesn't work in Groovy

---

java/j2ee.persistence/nbproject/project.xml
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/CCParser.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/ETCompletionContextResolver.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/JPACodeCompletionProvider.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/JPACompletionItem.java
java/java.lsp.server/nbcode/nbproject/platform.properties

Completion for SQL queries for repository annotations should be available via LSP.

LSP: Provide completion for SQL queries for repository annotations.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/vscode/src/testAdapter.ts

- GR-35759: Tests aren't updated when a project opens.
- GR-34404: Click Run for several tests one by one in gutter and it gets inconsistent
- GR-35195: Multiline assertions not formatted correctly in test UI

LSP: Couple of Text Explorer fixes.

---

ide/css.editor/external/binaries-list
ide/css.editor/external/css3-spec-howtocreate.txt
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/Bundle.properties
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/DefaultCssEditorModule.java
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/properties/alignment.properties
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/properties/backgrounds_and_borders.properties
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/properties/flexible_box_layout.properties
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/properties/fragmentation.properties
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/properties/multi-column_layout.properties
ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/module/main/AlignmentModuleTest.java
ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/module/main/FlexibleBoxLayoutModuleTest.java
ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/module/main/MultiColumnLayoutTest.java
ide/css.lib/src/org/netbeans/modules/css/lib/Css3.g
ide/css.lib/src/org/netbeans/modules/css/lib/Css3Lexer.java
ide/css.lib/src/org/netbeans/modules/css/lib/Css3Parser.java
ide/css.lib/src/org/netbeans/modules/css/lib/api/properties/PropertyCategory.java
ide/css.lib/test/unit/src/org/netbeans/modules/css/lib/Css3ParserScssTest.java

- support namespaced SCSS variables 
- support CSS Box Alignment module
- improve CSS Fragmentation module

CSS Parser Fixes

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java

Never remove imports on save when the code isn't bug free.

LSP: Never remove imports on save when the code isn't bug free.

---

nbbuild/antsrc/org/netbeans/nbbuild/RatReportTask.java

Since the module directories were moved from the toplevel into
per-cluster folders, alls RAT violations were reported in the
"not cluster" cluster.

Fix cluster splitting of RAT errors

---

java/java.lsp.server/vscode/src/testAdapter.ts

Show Debug Console while running tests to display possible compilation errors.

VSCode: Show Debug Console while running tests.

---

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/inference/TypeInferenceVisitor.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/occurrences/TypeVisitor.java
groovy/groovy.editor/test/unit/data/testfiles/completion/variables/fields1/Fields1.groovy
groovy/groovy.editor/test/unit/data/testfiles/completion/variables/fields1/Fields1.groovy.testFields1_1.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/variables/fields1/Fields1.groovy.testFields1_2.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/variables/fields1/Fields1.groovy.testFields1_3.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/variables/fields1/Fields1.groovy.testFields1_4.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/variables/fields1/Fields1.groovy.testFields1_5.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/variables/fields1/Fields1.groovy.testFields1_6.completion
groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/VariablesCCTest.java

This fixing resolving types of fields.

[NETBEANS-6361] Code completion for class fields doesn't work.

---

java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionCollector.java

Fixing broken code completion for super constructor call.

LSP: Fixed broken code completion for super constructor call.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ChangeMethodParametersRefactoring.java

Change method parameters should refactor access modifier and reflect static methods.

LSP: Change method parameters should refactor access modifier.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ChangeMethodParametersRefactoring.java

LSP: Change method parameters should refactor access modifier

LSP: Change method parameters should refactor access modifier. (#3442)

---

java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/JavaPluginUtils.java
java/refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/PushDownTransformer.java

Couple of modifications to fix errors currently printed to log from ServerTest.

LSP: Modified to fix errors currently printed to log from ServerTest.

---

nbbuild/antsrc/org/netbeans/nbbuild/ReleaseJsonProperties.java
nbbuild/javadoctools/jsonhelp.xsl

attempt to make apidoc generation according to a flag instead of url.
remove apidoc prior to 8.2 link
will need to recommit on the previous release branch.

Use boolean flag to create apidoc menu

---

ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/CodeTemplateCompletionProvider.java
java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionCollector.java
java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionItem.java

- LSP: Wrong caret position after expanding sout template.
- Automatic cast is missing enclosing class.

Minor bugs in code completion fixed.

---

java/java.hints/src/org/netbeans/modules/java/hints/OrganizeImports.java

[#3494] Organize Imports inspection is not record aware.

---

php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion.java
php/php.editor/src/org/netbeans/modules/php/editor/elements/IndexQueryImpl.java
php/php.editor/test/unit/data/testfiles/completion/lib/gh3486/gh3486.php
php/php.editor/test/unit/data/testfiles/completion/lib/gh3486/gh3486.php.testGH3486_01.completion
php/php.editor/test/unit/data/testfiles/completion/lib/test207345/bar.php.testUseCase1.completion
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionGH3486Test.java

Fix code completion for parent's trait #3486

---

extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java

I've noticed that when Gradle is executed to configure project & report its properties, the resulting Quality of the project information is still the aimed value - whatever it was. IMHO the info quality should reflect the real state: either FULL_ONLINE if online mode was requested explicitly; or FULL, if the project could be configured without online access (and settings require or permit that).

Report real FULL/FULL_ONLINE quality after load.

---

java/java.lsp.server/vscode/BUILD.md

The current `BUILD.md` info is a bit out of date. Rewording, updating, etc.

Making build information a bit more up to date

---

nbbuild/antsrc/org/netbeans/nbbuild/ReleaseJsonProperties.java
nbbuild/javadoctools/jsonhelp.xsl

This will remove the link to the vsix apidoc and NetBeans 8.2. Will do several PR and merge them w/o all to be reviewed.

#3443 to release90 apidoc

---

enterprise/javaee.wildfly/licenseinfo.xml
enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/javaee_7.xsd
enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/jboss-common_6_0_1.xsd
enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/jboss-common_8_1.xsd
enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/jboss-web_14_1.xsd
enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/jboss-web_7_3_1.xsd
enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/jsp_2_2.xsd
enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/resources/web-common_4_0.xsd

Hi @matthiasblaesing  this PR is a cherrypick of a change you did on release122 to the release120 branch.
This intention is to be able to be able to build NetBeans and the apidoc on the ci-build to resync all documentation.
I will do the same on release121 that is broken too, if this one is ok.

Ensure javaee.wildfly is offline buildable to release120

---

enterprise/cloud.oracle/nbproject/project.xml
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/CompartmentNode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/DatabaseNode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/DownloadWalletAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/DownloadWalletDialog.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCIManager.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OpenServiceConsoleAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OracleCloudWizardIterator.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/TenancyInstance.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/TenancyNode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/items/DatabaseItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/items/OCIItem.java
enterprise/cloud.oracle/test/unit/src/org/netbeans/modules/cloud/oracle/DownloadWalletDialogTest.java
java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/cloud-cookies.contextValues
java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml
java/java.lsp.server/nbproject/project.properties
java/java.lsp.server/nbproject/project.xml
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceUIContext.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/NotifyDescriptorAdapter.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/UIContext.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/ui/AbstractDialogDisplayerTest.java
java/java.lsp.server/vscode/package.json
platform/openide.dialogs/apichanges.xml
platform/openide.dialogs/manifest.mf
platform/openide.dialogs/nbproject/org-openide-dialogs.sig
platform/openide.dialogs/src/org/openide/NotifyDescriptor.java

WIP: Download wallet

---

java/java.lsp.server/nbcode/branding/modules/org-netbeans-modules-cloud-oracle.jar/org/netbeans/modules/cloud/oracle/resources/compartment.svg
java/java.lsp.server/nbcode/branding/modules/org-netbeans-modules-cloud-oracle.jar/org/netbeans/modules/cloud/oracle/resources/database.svg

Adding vscode version of OCI explorer icons.

Adding vscode icons for OCI explorer

---

php/php.editor/src/org/netbeans/modules/php/editor/csl/FoldingScanner.java
php/php.editor/src/org/netbeans/modules/php/editor/csl/PHPFoldingProvider.java
php/php.editor/test/unit/data/testfiles/attributeSyntax_01.php.folds
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/FoldingTest.java

- https://issues.apache.org/jira/browse/NETBEANS-6438
- Add code folding for attributes

[NETBEANS-6438] Add code folding for PHP attributes

---

enterprise/cloud.oracle/arch.xml
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/Bundle.properties
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/CompartmentNode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCIManager.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OracleCloudWizardIterator.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/TenancyNode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AbstractPasswordPanel.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/Bundle.properties
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/CreateAutonomousDBAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/CreateAutonomousDBDialog.form
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/CreateAutonomousDBDialog.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletDialog.form
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletDialog.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/items/CompartmentItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/items/OCIItem.java
enterprise/cloud.oracle/test/unit/src/org/netbeans/modules/cloud/oracle/actions/AbstractPasswordPanelTest.java
java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/cloud-cookies.contextValues
java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml
java/java.lsp.server/vscode/package.json

Adding action for creating a new Autonomous Database in Oracle Cloud. The action is available in NetBeans and VSCode.

Adding Create Autonomous Database Action/Command

---

.asf.yaml

update github tags.

---

javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/completion/beans/FxBean.java
javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/completion/impl/ClassCompleter.java
javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/spi/FXMLOpener.java
javafx/javafx2.project/src/org/netbeans/modules/javafx2/project/ui/RuntimeComboBox.java
javafx/javafx2.scenebuilder/src/org/netbeans/modules/javafx2/scenebuilder/SceneBuilderFXMLOpener.java
javafx/javafx2.scenebuilder/src/org/netbeans/modules/javafx2/scenebuilder/Settings.java
javafx/javafx2.scenebuilder/src/org/netbeans/modules/javafx2/scenebuilder/impl/SBHomeFactory.java
javafx/javafx2.scenebuilder/src/org/netbeans/modules/javafx2/scenebuilder/options/GrowingComboBox.java
javafx/javafx2.scenebuilder/src/org/netbeans/modules/javafx2/scenebuilder/options/SBOptionsPanel.java
javafx/javafx2.scenebuilder/src/org/netbeans/modules/javafx2/scenebuilder/options/SBOptionsPanelController.java

This replaces patterns such as "final public" with "public final" to bring the modifiers in the standard order for the projects in the javafx folder.
See: https://rules.sonarsource.com/java/RSPEC-1124
---

Use the blessed modifier order in projects located in javafx projects

---

apisupport/apisupport.project/src/org/netbeans/modules/apisupport/project/spi/BrandingModel.java
apisupport/apisupport.project/src/org/netbeans/modules/apisupport/project/ui/branding/BasicBrandingPanel.form
apisupport/apisupport.project/src/org/netbeans/modules/apisupport/project/ui/branding/BasicBrandingPanel.java
apisupport/apisupport.project/src/org/netbeans/modules/apisupport/project/ui/branding/Bundle.properties

I've changed the UI in order to allow the larger icons.

Larger icon sizes missing in platform branding UI #3544

---

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/util/CompletionContext.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/MethodCompletion.java
groovy/groovy.editor/test/unit/data/testfiles/completion/closures/insideClosure1/InsideClosure1.groovy.testInsideClosure1_1.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/closures/insideClosure1/InsideClosure1.groovy.testInsideClosure1_2.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/closures/insideClosure1/InsideClosure1.groovy.testInsideClosure1_3.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/closures/insideClosure1/InsideClosure1.groovy.testInsideClosure1_5.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/closures/insideClosure1/InsideClosure1.groovy.testInsideClosure1_6.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/closures/insideClosure1/InsideClosure1.groovy.testInsideClosure1_7.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/method/completionNoDot2/CompletionNoDot2.groovy
groovy/groovy.editor/test/unit/data/testfiles/completion/method/completionNoDot2/CompletionNoDot2.groovy.testCompletionNoDot2_1.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/method/completionNoDot2/CompletionNoDot2.groovy.testCompletionNoDot2_2.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/method/completionNoDot2/CompletionNoDot2.groovy.testCompletionNoDot2_3.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/method/completionNoDot2/CompletionNoDot2.groovy.testCompletionNoDot2_4.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/method/completionNoDot2/CompletionNoDot2.groovy.testCompletionNoDot2_5.completion
groovy/groovy.editor/test/unit/data/testfiles/completion/method/completionNoDot2/CompletionNoDot2.groovy.testCompletionNoDot2_6.completion
groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/completion/MethodCCTest.java

With this fix the cc offers methods and fields from the class (where cc is invoke) without using `this.`.

[NETBEANS-6463] Code completion doesn't offer methods from the same class

---

java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/ClassPathProviderImpl.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/Condition.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/ConditionAPIHacks.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintLexer.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintRegistry.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintTokenId.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintsParser.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintsWorker.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/EmbeddingProviderImpl.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/Hacks.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/MethodInvocationContext.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/PatternConvertorImpl.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/Utilities.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/test/EditorTestPerformer.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/test/HighlightsLayerFactoryImpl.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/test/TestLexer.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/test/TestLocatorImpl.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/test/TestParser.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/test/TestPerformer.java
java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/test/TestTokenId.java
java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintRegistryTest.java
java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintsParserTest.java
java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/EmbeddingProviderImplTest.java
java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/MethodInvocationContextTest.java
java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/conditionapi/ContextTest.java
java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/debugging/EvaluationSpanTaskTest.java
java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/idebinding/HintsTaskTest.java
java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/test/TestParserTest.java
java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java

first commit is a general language level upgrade (to 8) of the declarative hints module (diamonds, multicatch, overrides, lamdas, collections, ARM-blocks, minor refactorings, warning removal etc)
second commit makes rule conditions more robust.
- catches and logs the exception with information helpful to see which rule/condition causes problems
- this should make it also more robust since one broken rule won't affect processing of other rules

[jackpot] more robust condition handling + code renovations

---

.github/ISSUE_TEMPLATE/netbeans_bug_report.yml

- version number bumps
- set PR combo to required, otherwise nobody will ever use it

gh issue template update post NB 13 release.

---

enterprise/micronaut/nbproject/project.xml
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionCollector.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionTask.java
ide/db.sql.editor/nbproject/project.properties
ide/db.sql.editor/nbproject/project.xml
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/ETCompletionContextResolver.java
java/java.lsp.server/nbcode/nbproject/platform.properties

SQL completion for Micronaut Query annotations added in addition to the existing JPQL completion.

SQL completion for Query annotations added.

---

platform/api.search/src/org/netbeans/modules/search/BasicSearchForm.java

fixes #3737 
I can't remember why I added that line :(

fix for #3737: BasicSearchForm should not select first entry by default.

---

enterprise/glassfish.eecommon/src/org/netbeans/modules/glassfish/eecommon/api/DomainEditor.java
enterprise/j2ee.dd.webservice/src/org/netbeans/modules/j2ee/dd/impl/commonws/ComponentBeanMultiple.java
enterprise/j2ee.dd.webservice/src/org/netbeans/modules/j2ee/dd/impl/commonws/DescriptionBeanMultiple.java
enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/common/ComponentBeanMultiple.java
enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/multiview/EjbJarMultiViewDataObject.java
enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/multiview/EntityHelper.java
enterprise/payara.eecommon/src/org/netbeans/modules/payara/eecommon/api/DomainEditor.java
enterprise/web.beans/src/org/netbeans/modules/web/beans/completion/CCPaintComponent.java
ide/api.debugger/src/org/netbeans/api/debugger/DebuggerManager.java
ide/api.debugger/src/org/netbeans/api/debugger/Properties.java
ide/xml.catalog.ui/src/org/netbeans/modules/xml/catalog/user/UserXMLCatalog.java
ide/xml.tax/src/org/netbeans/modules/xml/tax/beans/editor/TreeNodeFilterCustomEditor.java
java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/SchemaElementImpl.java
java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/TableElementImpl.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/CCPaintComponent.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/entitygenerator/CMPMappingModel.java
platform/api.templates/src/org/netbeans/api/templates/FileBuilder.java
platform/openide.compat/src/org/openide/explorer/ExplorerActions.java
platform/openide.filesystems/src/org/openide/filesystems/DefaultAttributes.java

These changes strictly reduce HashMap warning messages like the following:
[repeat] /home/bwalker/src/netbeans/platform/core.netigso/src/org/netbeans/core/netigso/Netigso.java:121: warning: [rawtypes] found raw type: HashMap
[repeat]             Map configMap = new HashMap();
[repeat]                                 ^
[repeat]   missing type arguments for generic class HashMap<K,V>
[repeat]   where K,V are type-variables:
[repeat]     K extends Object declared in class HashMap
[repeat]     V extends Object declared in class HashMap
---
- are contributed solely under the terms and conditions …

Simple changes to reduce warning messages.

---

ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/HyperlinkProviderImpl.java

#3761 HyperlinkProviderImpl readLock for TokenHierarchy.get

---

.github/workflows/cv.yml
.github/workflows/ensure-jdk8.yml
.github/workflows/javadoc.yml
.github/workflows/linux-upstream-jdk.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/php.yml
.github/workflows/windows.yml
README.md
php/.gitattributes
php/php.atoum/test/unit/src/org/netbeans/modules/php/atoum/coverage/CloverLogParserTest.java
php/php.phpunit/test/unit/src/org/netbeans/modules/php/phpunit/coverage/PhpUnitCoverageLogParserTest.java

- Only run PHP workflows when there are changes in the PHP cluster.
- Move Windows PHP tests to PHP workflow
- Fix and/or disable PHP test on Windows 
---

Fix on PHP tests on Windows

---

extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java
extide/gradle/src/org/netbeans/modules/gradle/spi/GradleFiles.java
extide/gradle/test/unit/src/org/netbeans/modules/gradle/spi/GradleFilesTest.java

This one is a more complete fix for #3663.
@maerevoet-wim I hope you don't mind if I'd preffer this PR over yours.

Prepare the code that GradleFiles.getFile() can return null

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/CodeActionsProvider.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/MoveRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ui/MoveClass.html
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ui/MoveMembers.html
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ui/refactoring.css
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

Move refactoring rewritten to the WebView based UI.

LSP: WebView based UI for Move refactoring.

---

enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/FetchLogPiped.java
enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/multiview/CmpFieldsNode.java
enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/multiview/EntityAndSessionHelper.java
enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/multiview/EntityHelper.java
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/admin/ProcessIOParser.java
enterprise/websvc.manager/src/org/netbeans/modules/websvc/manager/ui/TestWebServiceMethodDlg.java
ide/xml.core/src/org/netbeans/modules/xml/dtd/grammar/DTDGrammar.java
ide/xml.multiview/src/org/netbeans/modules/xml/multiview/SectionNode.java
java/ant.debugger/src/org/netbeans/modules/ant/debugger/AntDebugger.java
java/ant.debugger/src/org/netbeans/modules/ant/debugger/IOManager.java
java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/IndexElementImpl.java
java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/MetaDataUtil.java
java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/SchemaElementImpl.java
java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/TableElementImpl.java
java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/ViewDependency.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/api/entity/generator/EntitiesFromDBGenerator.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/editor/completion/db/Schema.java
java/java.hints.ui/src/org/netbeans/modules/java/hints/spiimpl/refactoring/InspectAndRefactorPanel.java
platform/openide.execution.compat8/nbproject/project.properties
platform/openide.execution.compat8/src/org/openide/execution/NbClassPathCompat.java
webcommon/html.knockout/src/org/netbeans/modules/html/knockout/KOJsEmbeddingProviderPlugin.java

[repeat] /home/bwalker/src/netbeans/java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/SchemaElementImpl.java:316: warning: [rawtypes] found raw type: LinkedList
[repeat]         LinkedList result = new LinkedList<>();
[repeat]         ^
[repeat]   missing type arguments for generic class LinkedList<E>
There are a few remaining ones that I did not touch. These are related to the methods being public and requiring changes or instances where
I would have to do major code work.
---
- are contributed solely under the terms and conditions of the Apache …

Cleanup a lot of warnings that deal with LinkedList raw types.

---

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java

When loading more complex projects like [`micronaut-test`](https://github.com/micronaut-projects/micronaut-test), NetBeans IDE reports a number of 'unresolvable artifact' errors:
Indeed, even the commandline gradle produces them:
```
$ ./gradlew dependencies
[...]
testCodeCoverageReportExecutionData - Supplies JaCoCo coverage data to the testCodeCoverageReport.  External library dependencies may appear as resolution failures, but this is expected behavior.
+--- project :test-core
|    +--- io.micronaut:micronaut-inject FAILED
|    +--- io.micronaut:micronaut-runtime FAILED
|    +--- io.micronaut:micronaut-bom:3.3.4
```
... but note the comment at the top of the configuration.
We can exclude configurations from loading entirely, but it seems that the 'unresolvable' problems appear in …

Avoid spurious errors when loading projects.

---

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/completion/SpockUtils.java

Fixing NPE in SpockUtils

---

extide/gradle/src/org/netbeans/modules/gradle/nodes/SubProjectsNode.java

Fix #3861. Let's keep the Gradle Sub-Project nodes in order.

Order Gradle sub-projects Nodes

---

enterprise/performance.scripting/test/qa-functional/src/org/netbeans/performance/languages/actions/CountingSecurityManager.java
java/performance.java/test/qa-functional/src/org/netbeans/performance/j2se/actions/CountingSecurityManager.java
java/performance/test/unit/src/org/netbeans/performance/scalability/CountingSecurityManager.java

Fix a defect (thought that might be easier to digest because it's not really a "bug") with declaring a Map.Entry
in the Performance Test Utility CountingSecurityManager.java.
---

cleanup improper declaration in CountingSecurityManager.java

---

java/java.lsp.server/vscode/package-lock.json

Security vulnerability reported for the `minimist` dependent library fixed.

Security vulnerability in dependent library fixed.

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletAction.java

Fix how db connection name is handled

Fix add db connection

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/MicronautConfigProperties.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/MicronautConfigValidator.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionCollector.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionTask.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/hyperlink/MicronautConfigHyperlinkProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/refactor/MicronautRefactoringFactory.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/layer.xml
ide/csl.api/src/org/netbeans/modules/csl/hints/GsfErrorProvider.java
ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlParser.java
ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlSection.java
ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlStructureItem.java

- Navigation to custom properties declared via @Property annotation added.

Support for Micronaut configuration enhanced.

---

platform/janitor/src/org/netbeans/modules/janitor/Janitor.java

This is a small enhancement in the Janitor code, so it offers abandoned cache directories for removal.
Especially useful for those who has the Snap package installed, as the cache directories are no longer picked up since 12.5 the user dir is in ```${SNAP_USER_DATA}``` and the cache is in ```${SNAP_USER_COMMON}/${SNAP_REVISION}```. As SNAP_USER_COMMON is not cleaned up by the snap infrastructure, cache dirs can pile up there.

Janitor shall remove abandoned cache dirs

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBAddConnection.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/LspTemplateUI.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ChangeMethodParametersRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ExtractSuperclassOrInterfaceRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/MoveRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/PullUpRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/PushDownRefactoring.java
java/refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/ExtractSuperclassRefactoringPlugin.java

- Inconsistence between marking name method and invoking actions fixed

NBLS: Refactorings bug fixes.

---

enterprise/micronaut/nbproject/project.xml
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/Bundle.properties
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautController.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/Controller.html
enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/layer.xml

Create Micronaut Controller class added to New from Template.

Micronaut Controller class added to New from Template.

---

groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/language/GroovyDeclarationFinder.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/utils/GroovyUtils.java
groovy/groovy.editor/test/unit/data/testfiles/declarationfinder/a/Declaration4.groovy
groovy/groovy.editor/test/unit/data/testfiles/declarationfinder/a/TestBuilder.java
groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/GroovyDeclarationFinderTest.java

This adds resolving type of dynamic variable in declaration finder.

Fix resolving possible type of a dynamic variable in DeclarationFinder

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionTask.java

A possible fix for #3799. Please check!

Prevent possible NPE at MicronautDataCompletionTask

---

java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/displayer/JavaVariablesDisplayer.java

Debug information of GraalVM EE native image is suited for GDB 7.11.1. Array inspection is made possible on that GDB version as well as correct String representation. The strings need to be read differently from the recent GDB, because the variable expression path is not provided and thus we can not read the memory from that path.

Corrected array and String inspection for various versions of GDB.

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/CreateAutonomousDBDialog.java

Update wording in create ADB action

Updating text in Create ADB action

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBAddConnection.java

Adding simple JDBC URL templates into Add DB connection command.

Jdbc url templates in the Add DB Connection command

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ui/MoveMembers.html
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ui/refactoring.css
java/java.sourceui/src/org/netbeans/modules/java/source/ui/LspElementUtils.java
java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBClassReader.java

- Do not log by default errors from fallback handling of another errors
- Do not produce CodeActions for cached diagnostics - crating a fix for a diagnostic that is no more valid (while diagnostic re-computation is still progress after a source modification) could lead to nasty errors reported

LSP: Minor bug fixes

---

java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/UnusedDetector.java

Just seen an NPE in UnusedDetector while coding in a recent build. Have not checked the root cause though the getResources() call in line 321 is allowed to return ```null``` in some not, necessarily, ideal cases.
The Exception, I've encountered with:
```
java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because "res" is null
at org.netbeans.modules.java.editor.base.semantic.UnusedDetector.isUnusedInPkg(UnusedDetector.java:322)
at org.netbeans.modules.java.editor.base.semantic.UnusedDetector.findUnused(UnusedDetector.java:131)
at org.netbeans.modules.java.editor.base.semantic.SemanticHighlighterBase.process(SemanticHighlighterBase.java:185)
at org.netbeans.modules.java.editor.semantic.SemanticHighlighter.process(SemanticHighlighter.java:56)
at …
```

Fix possible NPE in Java Editor UnusedDetector

---

java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/UnusedDetector.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

Sync #4105 to master. cc @mbien - feel free to merge.

Sync #4015 from delivery to master

---

groovy/groovy.support/src/org/netbeans/modules/groovy/support/debug/GroovySmartStepping.java
java/api.debugger.jpda/src/org/netbeans/spi/debugger/jpda/SmartSteppingCallback.java
java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/SmartSteppingImpl.java
java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/actions/JPDAMethodChooserFactoryUIImpl.java
java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/JPDADebuggerImpl.java
java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/JPDAStepImpl.java
java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/actions/SmartSteppingFilterImpl.java
java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/actions/SmartSteppingFilterWrapper.java
java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/actions/StepActionProvider.java
java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/actions/StepIntoNextMethod.java

Smart-stepping changed to have a unique instance of `SmartSteppingFilter` per the ongoing step. Javadoc is improved accordingly.
Smart stepping is implemented for Groovy - `GroovySmartStepping`.

Smart stepping implemented for Groovy. SmartSteppingFilterWrapper introduced as a step-specific filter.

---

ide/lsp.client/src/org/netbeans/modules/lsp/client/Utils.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/LanguageClientImpl.java

Please see individual commits for details.

Improvements for LSP Client

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionTask.java

Micronaut Data finder completion should work in a case when the corresponding entity is Java record (not a class).

Micronaut Data finder completion should work for record entities.

---

apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardPanelVisual.java

second merge of already reviewed #4007 due to post-merge modifications of the delivery branch

new nb module project wizard improvements (merge v2)

---

php/php.project/src/org/netbeans/modules/php/project/ui/wizards/NewFileWizardIterator.java

https://github.com/apache/netbeans/issues/4099
This is a hack!
Normally, We can't get a path of a created file.

Prevent being created unexpected folders #4099

---

groovy/groovy.editor/apichanges.xml
groovy/groovy.editor/manifest.mf
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/lexer/LexUtilities.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/language/GroovyFormatter.java
java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/OptionsExportModel.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts
java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java

LSP: `Format Document` and `Format Selection` actions implemented.
The implementation can read formatting settings exported form NetBeans.

LSP: Format Document and Format Selection actions implemented.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/TestProgressHandler.java
java/java.lsp.server/vscode/src/testAdapter.ts
java/java.source.base/src/org/netbeans/api/java/source/DocTreePathHandle.java
java/javadoc/src/org/netbeans/modules/javadoc/hints/GenerateJavadocCollector.java

- Spock Unroll support should handle multiple tests with the same name correctly.
- Errors thrown when typing an empty Javadoc comment for a method with params fixed.

Minor bug fixes.

---

java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java

MavenIndexer dropped the caching of the allGroups and rootGroups
properties in the index:
https://github.com/apache/maven-indexer/commit/c231db602b5cea9ed20eba617de5a5a846ef5faa
After the index is loaded there are two options:
a) rebuild the groups list from the index
b) cache the group list after indexing
NetBeans expects the index to be readily be available and thus option
a is not an option (rebuilding the group list runs over the full index
and is in the minute range). As there are only a few entrypoints that
modify the index caching the group list looks like a viable option.
Closes: #4102

Fix maven groupId completion

---

java/maven/src/org/netbeans/modules/maven/execute/defaultActionMappings.xml
platform/sampler/src/org/netbeans/modules/sampler/InternalSampler.java
platform/sampler/src/org/netbeans/modules/sampler/Sampler.java

Sorry this is for beeing safe as build cannot occurs yet

Sync delivery to master after 14-rc5

---

platform/openide.util.lookup/src/org/openide/util/lookup/implspi/ActiveQueue.java

What happens is:
* `ActiveQueue.Impl::removeSuper` invokes `ReferenceQueue::remove` with argument 0
* `ReferenceQueue::remove` was recently changed: before `remove()` delegated to `remove(0)`, but now the dependency is inverted and it's `remove(0)` that delegates to `remove()` instead
* `ActiveQueue.Impl` overrides `remove` and unconditionally throws `InterruptedException`
* `ActiveQueue.Daemon` [invokes](https://github.com/apache/netbeans/blame/master/platform/openide.util.lookup/src/org/openide/util/lookup/implspi/ActiveQueue.java#L115) `ActiveQueue.Impl::removeSuper` within an infinite loop, [catches](https://github.com/apache/netbeans/blame/master/platform/openide.util.lookup/src/org/openide/util/lookup/implspi/ActiveQueue.java#L134) the `InterruptedException` thrown by …

Avoid dependency on ReferenceQueue internals

---

java/maven/src/org/netbeans/modules/maven/newproject/TemplateUtils.java
java/maven/src/org/netbeans/modules/maven/newproject/idenative/IDENativeMavenWizardIterator.java
java/maven/src/org/netbeans/modules/maven/newproject/idenative/IDENativeTemplateHandler.java
java/maven/src/org/netbeans/modules/maven/newproject/idenative/PomJavaNativeMWI.java

hotfix for #3809 
- Creates a maven template with a `<packaing>pom</packaging>` pom.xml

JavaWithMaven / POM Project

---

.github/workflows/release-drafter.yml

workflow trigger button should appear here once merged:
https://github.com/apache/netbeans/actions/workflows/release-drafter.yml

set release drafter workflow to manual activation.

---

java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.lsp.server/vscode/src/extension.ts

Two minor fixes:
- code completion for annotations nested in regular classes (e.g. `@NbBundle|.Messages`).
- `symbol` LSP call implementation modified to follow recent changes n VSCode.

Minor fixes.

---

.travis.yml
java/java.lsp.server/build.xml
java/java.lsp.server/vscode/package-lock.json
java/java.lsp.server/vscode/package.json
nbbuild/misc/prepare-bundles/src/main/java/org/netbeans/prepare/bundles/PrepareBundles.java

Adding [External Java Code Formatters for NetBeans](https://plugins.netbeans.apache.org/catalogue/?id=15) module into [NBLS](https://marketplace.visualstudio.com/items?itemName=ASF.apache-netbeans-java).

External Code Formatters added into NBLS.

---

extide/o.apache.tools.ant.module/src-bridge/org/apache/tools/ant/module/bridge/impl/ForkedJavaOverride.java

These two together improve a test case of 10000 lines of 2890
characters from taking an estimated 25 minutes to run to taking 5
seconds:
Change to use matches() rather than find() for the stack checking
regex, which runs very slowly on long lines.
Use buffered reads rather than single byte reads.
Other changes:
Use an ExecutorService to start and manage threads.
Remove references to deprecated ThreadDeath exception.
Move critical section to isolated functions.
Split non-processing and processing stream handlers
into separate classes.
Fix some logic errors introduced from / and requiring ancient
'hot fixes'.
---
- are all your own work, and you have the right …

Improve output window performance for ant java tasks #4141.

---

java/maven/src/org/netbeans/modules/maven/options/MavenCommandSettings.java

This is a bug fix release, tested by successfully created a maven project from archetype.
Release Notes:
https://lists.apache.org/thread/nyk326z3l3k163d949z2n7hr332744ko

Update maven-archetype-plugin from 3.1.2 to 3.2.1

---

php/php.editor/src/org/netbeans/modules/php/editor/model/impl/ModelVisitor.java
php/php.editor/test/unit/data/testfiles/gotodeclaration/testArrowFunctions/testArrowFunctions.php
php/php.editor/test/unit/data/testfiles/markoccurences/testArrowFunctions/testArrowFunctions.php
php/php.editor/test/unit/data/testfiles/testArrowFunctions.php.testArrowFunctions_GH4209_01a.occurrences
php/php.editor/test/unit/data/testfiles/testArrowFunctions.php.testArrowFunctions_GH4209_01b.occurrences
php/php.editor/test/unit/data/testfiles/testArrowFunctions.php.testArrowFunctions_GH4209_01c.occurrences
php/php.editor/test/unit/data/testfiles/testArrowFunctions.php.testArrowFunctions_GH4209_01d.occurrences
php/php.editor/test/unit/data/testfiles/testArrowFunctions.php.testArrowFunctions_GH4209_01e.occurrences
php/php.editor/test/unit/data/testfiles/testArrowFunctions.php.testArrowFunctions_GH4209_02a.occurrences
php/php.editor/test/unit/data/testfiles/testArrowFunctions.php.testArrowFunctions_GH4209_02b.occurrences
php/php.editor/test/unit/data/testfiles/testArrowFunctions.php.testArrowFunctions_GH4209_03a.occurrences
php/php.editor/test/unit/data/testfiles/testArrowFunctions.php.testArrowFunctions_GH4209_03b.occurrences
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/GotoDeclarationPHP74Test.java
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/OccurrencesFinderImplPHP74Test.java

- https://github.com/apache/netbeans/issues/4209
- Fix the scope for the variable in the arrow function

Fix variable highlighting in arrow function #4209

---

java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/conditionapi/Matcher.java
java/java.hints/src/org/netbeans/modules/java/hints/errors/Utilities.java
java/java.hints/src/org/netbeans/modules/java/hints/infrastructure/ErrorHintsProvider.java
java/java.hints/src/org/netbeans/modules/java/hints/suggestions/Bundle.properties
java/java.hints/src/org/netbeans/modules/java/hints/suggestions/Tiny.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/suggestions/Bundle_test.properties
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/suggestions/TinyTest.java

Hint for inlining redundant variables added.

Inline redundant variable hint added.

---

java/java.lsp.server/vscode/package.json

- Remove extension Preview label
- Change display name according to community discussion

Remove Preview label

---

ide/git/src/org/netbeans/modules/git/GitModuleConfig.java
ide/git/src/org/netbeans/modules/git/options/Bundle.properties
ide/git/src/org/netbeans/modules/git/options/GitOptionsPanel.form
ide/git/src/org/netbeans/modules/git/options/GitOptionsPanel.java
ide/git/src/org/netbeans/modules/git/options/GitOptionsPanelController.java
ide/git/src/org/netbeans/modules/git/ui/branch/CreateBranch.java
ide/git/src/org/netbeans/modules/git/ui/checkout/AbstractCheckoutRevision.java
ide/git/src/org/netbeans/modules/git/utils/GitUtils.java
ide/git/src/org/netbeans/modules/git/utils/JGitUtils.java

Hi! I've made an option for git that implements the feature from issue #3980.

Git: replace invalid characters in branch name

---

java/java.lsp.server/vscode/package.json

I forgot to changethe userdir's default value in `package.json`; code uses default value fallback, but I missed this declarative one.

Default value of userdir set to local.

---

apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/universe/ClusterUtils.java

`ProjectNav > some-module-suite > properties > Libraries`
when `<module-suite-dir>/nbproject/platform.properties`
has `cluster.path=... <maven-nbm-dir>/target/nbm/clusters/extra`
This fix prevents a hung dialog (cancel terminates it).
It also makes it simpler to incorporate a maven based
nbm into an existing module suite as an external cluster.
Note that specifying a maven nbm project in cluster.path currently works for running the suite. It's just this dialog that hangs.

Avoid NPE in ant module suite's "Project Properties" dialog.

---

apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardIterator.java
apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardPanelVisual.form
apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardPanelVisual.java

- don't add osgi flag if it was not checked (followup on #4007)
- upgrade nbm-plugin version in nb app project wizard (fixes #4316)
(nbm project did already upgrade it correctly)
- minor cleanup
reviewer note: check ignore whitespace since there was a large section on the wrong indentation level

nb project wizard fixes

---

ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/RepositoryUpdater.java

While analysing this it was found, that the GsfParserFactory#createParser
returned null as the parser for snapshots. Looking deeper, showed, that
the #createParser method was invoked with snapshots of differing mimetypes.
This works, but is a violation of the contract in ParserFactory#createParser:
> It is guaranteed that all snapshots in the collection will be
> of the same mime type and it will be the mime type, which this factory
> was registered for (ie. in MimeLookup)
If the snapshots are inconsistent, parsing still works, but its performance
suffers. To fix this the call to ParserManager#parse in RepositoryUpdater
is split. The scanned sources are grouped by their mimepath and each group
is individually passed.
The observed improvements are:
Indexing Variant 1 (tour-of-heroes) …

Invoke indexer in RepositoryUpdater grouped by mimepath of file

---

java/java.source.base/src/org/netbeans/modules/java/source/JavadocHelper.java

Attempt to fix errors in Javadoc links where the module name is missing from the URL.
Not sure if we need to try a reverse fallback without the module name on exception?

Fix missing module name in Javadoc URLs for Show Javadoc, etc.

---

platform/o.n.core/nbproject/project.properties

See https://github.com/apache/netbeans/issues/4211 for details

Disable flaky ValidateLayerConsistencyTest

---

api.htmlui/apichanges.xml
api.htmlui/arch.xml
api.templates/apichanges.xml
api.templates/arch.xml
maven/arch.xml
nbbuild/antsrc/org/netbeans/nbbuild/CheckLinks.java
nbbuild/build.properties
openide.awt/arch.xml
openide.explorer/arch.xml
openide.filesystems/arch.xml
openide.modules/arch.xml
openide.nodes/arch.xml
openide.util.lookup/arch.xml
openide.windows/arch.xml

same concept as #4397 but for release 90. Cannot cherry pick

fix apidoc release90 broken links

---

platform/libs.jna.platform/external/binaries-list
platform/libs.jna.platform/external/jna-platform-5.12.1-license.txt
platform/libs.jna.platform/manifest.mf
platform/libs.jna.platform/nbproject/project.properties
platform/libs.jna.platform/nbproject/project.xml
platform/libs.jna/external/binaries-list
platform/libs.jna/external/jna-5.12.1-license.txt
platform/libs.jna/manifest.mf
platform/libs.jna/nbproject/project.properties
platform/libs.jna/nbproject/project.xml

Update JNA and JNA-platform to 5.12.1

---

java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts

Cloud explorer in NBLS should be hidden with Java support switched off.

LSP: Cloud explorer should be hidden with Java support switched off.

---

ide/css.editor/src/org/netbeans/modules/css/editor/module/main/Bundle.properties
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/DefaultCssEditorModule.java
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/properties/default_module.properties
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/properties/positioning.properties
ide/css.lib/src/org/netbeans/modules/css/lib/api/properties/PropertyCategory.java

Hello! In this PR I tried to implement `position:sticky` from issue #4305, and also make a correct help for this property from the css3 specification.

CSS: Implemented position:sticky

---

java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java

based on delivery
- conflictsWithLocal is called in a loop and recomputes methodsIn
on each iteration which scales very badly (quadratic complexity)
- we can simply extract this part out of the loop
- see #4500 for graphs, benchmark and more detail

#4500 static imported methods slow down auto completion

---

ide/languages.yaml/src/org/netbeans/modules/languages/yaml/preferences.xml

Well two space indented YAML is kind of trendy now in the world of everything is yaml.

Change YAML indent to 2 spaces by default

---

java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteProject.java

"--add-modules ALL-MODULE-PATH" set when compiling MX projects.

Set "--add-modules ALL-MODULE-PATH" when compiling MX project.

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/ProjectVulnerability.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/VulnerabilityWorker.java
java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleDependencyResult.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java

* project display name is sanitized - certain characters are disallowed by OCI
* gradle dependencies threw NPE for projects without build.gradle

Vulnerability audit fixes

---

java/languages.antlr/src/org/netbeans/modules/languages/antlr/v3/Antlr3ParserResult.java
java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4ParserResult.java

Yes, it seems some things are still lurking. Let's start to patch them.

Fix possible NPE while editing ANTLR Grammar

---

java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts

Changes the default value of 'reveal in project explorer' settings

Reveal things in project explorer by default.

---

extide/gradle/src/org/netbeans/modules/gradle/customizer/BuildActionsCustomizer.java

Fix npe from gradle build actions dialog

---

enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ui/wizard/archetype/Bundle.properties

Full build done
Verify successful creation of the project
Deploy and  run successfully

Update Maven archetype version for Jakarta EE 9.1

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBAddConnection.java

In some cases empty jdbc password makes sense, so we should allow it. 
---

Allow empty jdbc password

---

platform/libs.flatlaf/external/binaries-list
platform/libs.flatlaf/external/flatlaf-2.5-license.txt
platform/libs.flatlaf/manifest.mf
platform/libs.flatlaf/nbproject/project.properties
platform/libs.flatlaf/nbproject/project.xml
platform/libs.flatlaf/src/org/netbeans/libs/flatlaf/Installer.java
platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/Installer.java

Replacement for #4696 fixing the merge conflict (I didn't want to force push directly to the PR).

Update FlatLaf from 2.4 to 2.5

---

java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/MoveClassPanel.java
java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/MoveMembersPanel.java

Move to phase RESOLVED before accessing elements in MoveMemberPanel and MoveClassPanel. Think this should fix #4708
cc/ @mbien - same conclusion?

Fix MoveMemberPanel and MoveClassPanel (GH4708)

---

java/maven/src/org/netbeans/modules/maven/classpath/ClassPathProviderImpl.java

Rebase of @timboudreau #4868 onto delivery.  Would like to get into rc3 so needs to merge soon.  Didn't want to force push to Tim's branch without OK.

Fix maven classpath listening

---

extide/gradle.dists/nbproject/project.properties
extide/gradle.editor/nbproject/project.properties
java/gradle.kit/nbproject/project.xml

As far as I've tested, this one fixes the issue.
It could be that for NB 17 these modules should be moved out of extide...

Switched gradle.dist and gradle.editor module to regular. Fixes #4866

---

ide/db.mysql/external/binaries-list
ide/db.mysql/external/mysql-connector-j-8.0.31-license.txt
ide/db.mysql/nbproject/project.properties
nbbuild/licenses/GPL-mysql-connector

https://github.com/apache/netbeans/pull/4817#issuecomment-1307814317

db.mysql: Bump connector/j version to prevent unittest failures ran against newer mysql server

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TestClassGenerator.java

Adding `Create JUnit test class` code action to NBLS.

LSP: Create test class code action added.

---

ide/css.editor/src/org/netbeans/modules/css/editor/module/main/BrowserSupportModule.java
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/DefaultCssEditorModule.java
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/ExtCssEditorModule.java
ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/module/main/properties/PropertiesATest.java

Lookup CSS properties case-insensitive

---

java/java.source/src/org/netbeans/modules/java/ui/Bundle.properties

Trivial fix for a misplaced closing brace.
---

#5023: Formatting preferences for Java contains bad sample code

---

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java

#5014  Cherry picked from master for NB17.

Fixed some Gradle introspection problems wit pre-6.1 Gradle Versions

---

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java

#5022 cherry-picked from master

Fix Gradle/broken task dependency and serialization

---

java/gradle.java/src/org/netbeans/modules/gradle/java/output/LookupProviders.java

#4984 Cherry picked from master for NB17.

[#4865] Register JDPA and Java Compiler Output on Project level

---

extide/gradle/src/org/netbeans/modules/gradle/GradleJavaCompatProblemsProvider.java
extide/gradle/src/org/netbeans/modules/gradle/GradleProjectConnection.java
extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java
extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
extide/gradle/src/org/netbeans/modules/gradle/spi/execute/package-info.java

#4985 Cherry picked from master.

Use Project Dictated JVM for Gradle Discovery

---

java/java.lsp.server/vscode/CHANGELOG.md

VSNetBeans Changelog.md updated for 16.0 patch release - 16u1.

VSNetBeans changelog update for 16u1

---

java/gradle.java/src/org/netbeans/modules/gradle/java/execute/LookupProviders.java

Cherry-picked from master: #5053

Make Java Platform available on non-java Gradle Projects

---

extide/gradle/manifest.mf
java/gradle.java/nbproject/project.properties

This is just an administrative PR updating the versions of the affected modules for NB16u1.

Upgrade version numbers for the affected modules

---

extide/gradle/manifest.mf
extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/GradleInternalAdapter.java
extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
extide/gradle/src/org/netbeans/modules/gradle/GradleJavaCompatProblemsProvider.java
extide/gradle/src/org/netbeans/modules/gradle/GradleProjectConnection.java
extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java
extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java
extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
extide/gradle/src/org/netbeans/modules/gradle/spi/execute/package-info.java
extide/gradle/test/unit/src/org/netbeans/modules/gradle/api/GradleBaseProjectTest.java
java/gradle.java/nbproject/project.properties
java/gradle.java/src/org/netbeans/modules/gradle/java/execute/LookupProviders.java
java/gradle.java/src/org/netbeans/modules/gradle/java/output/JavaCompilerProcessorFactory.java
java/gradle.java/src/org/netbeans/modules/gradle/java/output/LookupProviders.java

This is a collector PR from delivery to release160

Delivery to release160 for NetBeans 16u1

---

java/java.source.base/src/org/netbeans/api/java/source/GeneratorUtilities.java

Fix organize imports to not add record from same package

---

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java

#5124 cherry-picked from master.

Fixing project loading issues with micronaut complex project.

---

java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertToARMTest.java
java/libs.javacapi/external/binaries-list
java/libs.javacapi/external/nb-javac-jdk-19.0.1-ga-license.txt
java/libs.javacapi/nbproject/project.xml
java/libs.nbjavacapi/external/binaries-list
java/libs.nbjavacapi/external/nb-javac-jdk-19.0.1-ga-license.txt
java/libs.nbjavacapi/nbproject/project.properties
java/libs.nbjavacapi/nbproject/project.xml
java/spi.java.hints/test/unit/src/org/netbeans/modules/java/hints/spiimpl/UtilitiesTest.java
java/spi.java.hints/test/unit/src/org/netbeans/spi/java/hints/JavaFixUtilitiesTest.java
nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps

Updating nb-javac library to version 19.0.1

Update to nb-javac-19.0.1.

---

platform/openide.util/test/unit/src/org/openide/util/TaskTest.java

rewritten 2 tests of org.openide.util.TaskTest into more readable form
refactored one
removed tests obsoleted by https://github.com/apache/netbeans/pull/4112

rewritten 2 tests of org.openide.util.TaskTest into more readable form

---

java/java.hints/src/org/netbeans/modules/java/hints/control/RemoveUnnecessary.java

NPE fix when statement list is null, addAll fails.
fixes #5177

fix NPE in RemoveUnnecessary class when case statement list is null.

---

NOTICE
nbbuild/notice-stub.txt

Update copyright year in NOTICE and notice-stub to 2023.

Update NOTICE and notice-stub year to 2023.

---

harness/libs.nbi.ant/stub/ext/engine/src/org/mycompany/installer/wizard/components/panels/PreInstallSummaryPanel.java
nbbuild/installer/engine/src/org/netbeans/installer/wizard/components/panels/netbeans/NbPreInstallSummaryPanel.java
nbi/engine/src/org/netbeans/installer/utils/StringUtils.java

Removed unused StringBuffer object without any side effects.

Removed StringUtils unused object creation

---

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NetBeansRunSinglePlugin.java

Made runSingle Gradle task work on Gradle 8.0

---

extide/gradle/src/org/netbeans/modules/gradle/GradleJavaCompatProblemsProvider.java

Fix Java version detection in GradleJavaCompatProblemProvider

---

.github/ISSUE_TEMPLATE/netbeans_bug_report.yml

Update issue report form for Apache NetBeans 17 release candidates.

Update issue report form for Apache NetBeans 17 release candidates.

---

php/php.editor/src/org/netbeans/modules/php/editor/model/impl/MethodScopeImpl.java

In PHP method names are case insensitive.
Method isMagic() did not work for methods __callStatic, __toString and __debugInfo. Method isConstructor() should compare whole string even though this is already guarded by isMagic().

Fixed detection of magic methods

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddADBAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletDialog.java

Use NotifyDescriptor.ComposedInput for Add ADB command. It improves usability of multi step input.

Use NotifyDescriptor.ComposedInput for Add ADB command

---

.github/workflows/main.yml

test-summary v2.1 fixes:
- https://github.com/test-summary/action/issues/9
- deprecation warning in the log
INFRA ticket:
https://issues.apache.org/jira/browse/INFRA-24145

bump test-summary action to v2.x

---

java/maven/src/org/netbeans/modules/maven/execute/MavenProxySupport.java

Trivial ... forgot to change some wording when I copied gradle > maven proxy support.

Fixed copypaste leftovers.

---

nbbuild/antsrc/org/netbeans/nbbuild/ModuleDependencies.java
nbbuild/installer/engine/src/org/netbeans/installer/utils/applications/GlassFishUtils.java
nbbuild/installer/engine/src/org/netbeans/installer/wizard/components/sequences/netbeans/NbMainSequence.java
nbbuild/installer/test/test/org/netbeans/test/installer/TestData.java
nbbuild/installer/test/test/org/netbeans/test/installer/Utils.java
nbbuild/test/unit/src/org/netbeans/nbbuild/TestBase.java

Changed boxing/autoboxing with Integer()/valueOf()/intValue() to raw int values or parseInt(some string)

nbbuild dir: removed unessesary old forms of Integer type

---

webcommon/html.knockout/src/org/netbeans/modules/html/knockout/KODataBindContext.java

Fixed incorrect regexp usage in KODataBindContext

---

java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintsParser.java

Adding system path into the classpath info when parsing custom conditions in a hint file. Avoid failures while constructing custom scopes.

---

enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/action/HomeMethodGenerator.java
enterprise/web.core/src/org/netbeans/modules/web/wizards/targetpanel/providers/JSFTargetPanelProvider.java
enterprise/web.core/src/org/netbeans/modules/web/wizards/targetpanel/providers/TagTargetPanelProvider.java
enterprise/web.core/src/org/netbeans/modules/web/wizards/targetpanel/providers/XmlOptionPanelManager.java
enterprise/websvc.saas.codegen.j2ee/src/org/netbeans/modules/websvc/saas/codegen/j2ee/support/J2eeUtil.java
nb/o.n.upgrader/src/org/netbeans/upgrade/systemoptions/ColorProcessor.java
nb/o.n.upgrader/src/org/netbeans/upgrade/systemoptions/FileProcessor.java
nb/o.n.upgrader/src/org/netbeans/upgrade/systemoptions/HostPropertyProcessor.java
nb/o.n.upgrader/src/org/netbeans/upgrade/systemoptions/NbClassPathProcessor.java
nb/o.n.upgrader/src/org/netbeans/upgrade/systemoptions/URLProcessor.java
nb/welcome/src/org/netbeans/modules/welcome/content/RSSFeed.java
nbbuild/antsrc/org/netbeans/nbbuild/LocMakeNBM.java
platform/api.visual/src/org/netbeans/modules/visual/anchor/DefaultAnchorShapeResolver.java
platform/api.visual/src/org/netbeans/modules/visual/graph/layout/hierarchicalsupport/LayeredGraph.java
platform/masterfs/src/org/netbeans/modules/masterfs/ProvidedExtensionsProxy.java
platform/o.n.swing.tabcontrol/demosrc/org/netbeans/swing/tabcontrol/demo/TestFrame.java
platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/DefaultTabDataModel.java
platform/openide.filesystems/src/org/openide/filesystems/AbstractFolder.java
platform/print/src/org/netbeans/modules/print/ui/Preview.java
profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/details/jdk/image/ImageDetailProvider.java
profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/ui/ReferencesBrowserControllerUI.java
webcommon/javascript2.jquery/src/org/netbeans/modules/javascript2/jquery/editor/JQueryCodeCompletion.java
webcommon/javascript2.requirejs/src/org/netbeans/modules/javascript2/requirejs/editor/RequireJSCodeCompletion.java

To effictive use of memory and for clean code.

Removed creating of unused objects

---

extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleDaemon.java
java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/ActionProviderImpl.java
nbbuild/antsrc/org/netbeans/nbbuild/extlibs/CheckEmbeddedBinaries.java
nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ExclusionsFromLicenseInfo.java
nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ReportFromLicenseinfo.java
platform/autoupdate.ui/src/org/netbeans/modules/autoupdate/ui/Utilities.java

Some resources was in uncloused condition.

Streams from java.nio.file.Files have to be closed

---

php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/ASTPHP5ParserTest/parser/php80/treatNamespacedNamesAsSingleToken_02a.pass
php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/ASTPHP5ParserTest/parser/php80/treatNamespacedNamesAsSingleToken_02b.pass
php/php.editor/test/unit/data/testfiles/parser/php80/treatNamespacedNamesAsSingleToken_02a.php
php/php.editor/test/unit/data/testfiles/parser/php80/treatNamespacedNamesAsSingleToken_02b.php

Corrected a typo in the php parser tests.

PHP: Corrected a typo in the php parser tests

---

java/java.lsp.server/vscode/src/nbcode.ts
platform/o.n.bootstrap/src/org/netbeans/MainImpl.java

Temporary to make master work with NBLS until platform launchers are updated; see #5350

Temporary fix: Support extra cluster directories.

---

java/java.lsp.server/vscode/package.json

Fixed typos in DB welcome view

---

ide/db/src/org/netbeans/modules/db/explorer/ConnectionList.java
java/java.lsp.server/vscode/src/extension.ts

The vscode "Database" view queried NBLS for the default DB just on startup, then it retained the connection node's ID, and only allowed vscode > NBLS change propagation. We need - for example when defining a new DB - that the NBLS's default connection is reflected back in the vscode. That will help if no connection is present and a new (first) one is defined that becomes the default. May also help in cases when other command(s) redefine the default connection internally.
I've changed DB module since there was a bug in that it offered the 1st connection as a default if none was specifically set - but was willing to change the default 'on the fly' if a new connection appeared, so the default could shift unexpectedly. Case when there's a preferred connection name stored, but the definition …

Vscode ext should update default connection

---

java/java.lsp.server/vscode/src/extension.ts

Sometimes it is necessary to `executeCommand` a NBLS-provided command. Although vscode may properly activate the NBLS extension (provided the command is in the activation patterns), but the NBLS-originated commands actually register only after the `Initialization` response returns to the vscode - that is asynchronously and **after** extension activation completes (as far as vscode is aware).
We do not **want** now to wait for the initialization as NBLS (now) tries to open projects from workspace before it completes the initialization. That takes too long and NBLS windows do not even appear in the UI during that time. The proper approach would be to make the NBLS startup very lightweight - then the standard `vscode.commands.executeCommand()` will properly activate & wait - and work.
But …

Provide a waitable command that completes after NBLS fully starts & registers server-provided commands

---

ide/db/src/org/netbeans/modules/db/util/PropertyEditorPanel.form
ide/db/src/org/netbeans/modules/db/util/PropertyEditorPanel.java
ide/spi.navigator/src/org/netbeans/modules/navigator/NavigatorTC.java
platform/openide.explorer/src/org/openide/explorer/propertysheet/MarginViewportUI.java
platform/openide.util.ui/src/org/openide/util/actions/SystemAction.java

Four small UI improvements (3 cosmetic + one focus handling adjustment), in various areas:
* Fix missing anti-aliasing for the Property Sheet's 'No Properties' message.
* Avoid the Navigator TopComponent itself grabbing focus when the user presses Tab from a focused component within the Navigator.
* Have SystemAction handle SVG icons properly.
* Make separator lines visible in the Database Explorer's 'connection properties' JTable.

Four small UI improvements, in various areas

---

php/php.editor/src/org/netbeans/modules/php/editor/model/impl/OccurenceBuilder.java
php/php.editor/test/unit/data/testfiles/gotodeclaration/testIssueGH5371/testIssueGH5371.php
php/php.editor/test/unit/data/testfiles/markoccurences/testIssueGH5371/testIssueGH5371.php
php/php.editor/test/unit/data/testfiles/testIssueGH5371.php.testIssueGH5371_01a.occurrences
php/php.editor/test/unit/data/testfiles/testIssueGH5371.php.testIssueGH5371_01b.occurrences
php/php.editor/test/unit/data/testfiles/testIssueGH5371.php.testIssueGH5371_01c.occurrences
php/php.editor/test/unit/data/testfiles/testIssueGH5371.php.testIssueGH5371_02a.occurrences
php/php.editor/test/unit/data/testfiles/testIssueGH5371.php.testIssueGH5371_02b.occurrences
php/php.editor/test/unit/data/testfiles/testIssueGH5371.php.testIssueGH5371_02c.occurrences
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/GotoDeclarationGH5371Test.java
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/OccurrencesFinderImplGH5371Test.java

- https://github.com/apache/netbeans/issues/5371
- Also check interfaces

Fix GotoDeclaration feature for `instanceof` interface #5371

---

java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java
java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorkerTest.java

[NETBEANS-5260] Binding patterns are valid even in absence of MatchException.

---

php/php.editor/src/org/netbeans/modules/php/editor/typinghooks/PhpTypedTextInterceptor.java
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/typinghooks/PhpTypedTextInterceptorTest.java

- https://github.com/apache/netbeans/issues/5707
- Fix the deprecated methods

Fix an issue that whitespace cannot be added #5707

---

enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/admin/AdminFactory.java
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/ConfigBuilderProvider.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/admin/AdminFactoryTest.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersionTest.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/utils/EnumUtilsTest.java

Library Notes:
- This is mainly a maintenance release that contains bug fixes and updates of various components.
- Verify successful execution of unit tests for modules glassfish.common, glassfish.javaee, glassfish.tooling and glassfish.eecommon
- Successfully register GlassFish 7.0.3, create a web app and verify that it works.
[Release Notes](https://github.com/eclipse-ee4j/glassfish/releases/tag/7.0.3)

Add support for GlassFish 7.0.3

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCIManager.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCIProfile.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCITenancyProvider.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/RunFileADMAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/compartment/CompartmentNode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/devops/BuildPipelineNode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/devops/BuildRunItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/devops/CreateBuildRunAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/devops/RepositoryItem.java

Imports cleanup in `cloud.oracle` module.

Imports cleanup

---

java/java.lsp.server/vscode/CHANGELOG.md

Updating changelog for 17.0.301

VSNetBeans changelog update for 17.0.301

---

platform/api.visual/src/org/netbeans/modules/visual/layout/ConnectionWidgetLayout.java
platform/api.visual/test/unit/src/org/netbeans/modules/visual/layout/ConnectionWidgetLayoutTest.java

A colleague of mine found an AOBE in visual library. We have a quick fix with some test around. Hopefully next time he willl contribute by himself 🤭.

connection layout AOBE fix

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBSetEnvCommand.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/AttachConfigurationCompletion.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/AttachConfigurations.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ProjectConfigurationCompletion.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.lsp.server/vscode/CHANGELOG.md
java/java.lsp.server/vscode/README.md
java/java.lsp.server/vscode/package-lock.json
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts
java/java.lsp.server/vscode/src/launchConfigurations.ts
java/java.lsp.server/vscode/src/runConfiguration.ts
java/java.lsp.server/vscode/src/test/suite/extension.test.ts

Renaming Java 8+ VS Code debug configuration to Java+.

VSCode: Renaming Java 8+ debug configuration to Java+.

---

platform/libs.flatlaf/external/binaries-list
platform/libs.flatlaf/external/flatlaf-3.1-license.txt
platform/libs.flatlaf/manifest.mf
platform/libs.flatlaf/nbproject/project.properties
platform/libs.flatlaf/nbproject/project.xml

Update FlatLaf to v3.1
Changes: https://github.com/JFormDesigner/FlatLaf/releases/tag/3.1

Update FlatLaf from 3.0 to 3.1

---

platform/core.ui/src/org/netbeans/core/ui/sysopen/SystemOpenAction.java

Closes #5327 
Hi! first timer here!
I implemented this solution that opens the system file explorer using Desktop.getDesktop().open(directory); instruction

[NETBEANS-5327] Added the option to open the selected file or directory in the system file explorer

---

nbbuild/antsrc/org/netbeans/nbbuild/GitBranchHash.java

Updated the GitBranchHash task to also search the `.git/packed-refs` file - noticed my local build was no longer picking up the hash and version.
Also tidied up some of the code and variable names to make this a little clearer.
Should be safe for delivery.

Update metabuild GitBranchHash task to handle packed refs.

---

ide/languages.hcl/src/org/netbeans/modules/languages/hcl/BasicHCLLexer.java
ide/languages.hcl/src/org/netbeans/modules/languages/hcl/terraform/TerraformHCLLexer.java

Trivial fix for these two missed tokens.

HCL Lexer shall recognize * and / as operator

---

.github/workflows/main.yml

the default value 
https://github.com/apache/netbeans/blob/613087a5e020e52021d6b45ea7813a08af5aa33e/nbbuild/build.xml#L153
is currently 404ing and causing the build to fail. This gives us the opportunity to check if the $OPTS are set everywhere (spoiler: they weren't :)).

make sure metabuild.jsonurl is set everywhere

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/vscode/src/extension.ts
java/java.lsp.server/vscode/src/testAdapter.ts

Stacktraces displayed in VSCode test explorer should allow for click navigation to corresponding source locations.

VSCode: Stacktraces in test exceptions should be clickable.

---

enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/admin/AdminFactory.java
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/ConfigBuilderProvider.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/admin/AdminFactoryTest.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersionTest.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/utils/EnumUtilsTest.java

Library Notes:
- This is mainly a maintenance release that contains bug fixes and updates of various components.
- Bump the GlassFish version in some tests
- Verify successful execution of unit tests for modules `glassfish.common`, `glassfish.javaee`, `glassfish.tooling` and `glassfish.eecommon`
- Successfully register GlassFish 7.0.5, create a web app and verify that it works.
[Release Notes](https://github.com/eclipse-ee4j/glassfish/releases/tag/7.0.5)

Add support for GlassFish 7.0.5

---

ide/css.editor/src/org/netbeans/modules/css/editor/module/main/DefaultCssEditorModule.java
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/properties/other.properties
ide/css.editor/src/org/netbeans/modules/css/editor/module/main/properties/text.properties
ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/module/main/StandardPropertiesHelpResolverTest.java

Add 'user-select' css property.
I've left out 'contain' value since it's mostly not supported.
See bug #5829
Also see https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

add user-select css property

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBAddConnection.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBCommandProvider.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBConnectionProvider.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/htmlui/WebView.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ImplementAllAbstractMethodsAction.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeClientCapabilities.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/QuickOpen.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/SurroundWithHint.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TestClassGenerator.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ChangeMethodParametersRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ExtractSuperclassOrInterfaceRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/MoveRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/PullUpRefactoring.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/PushDownRefactoring.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/dbConfigurationProvider.ts
java/java.lsp.server/vscode/src/extension.ts
java/java.lsp.server/vscode/src/launchConfigurations.ts
java/java.lsp.server/vscode/src/test/suite/extension.test.ts
java/java.lsp.server/vscode/src/test/suite/testutils.ts
java/java.lsp.server/vscode/src/testAdapter.ts
java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/CodeLensProviderImpl.java

Adding support for changing the prefix of code names of commands and configuration options from on the client extension.
---

Prefixing all code names of commands with 'nbls'.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBConnectionProvider.java

When I try to Run Main or Run Project in VS Code, using the NB extension, it fails. It seems the reason is that if there's no DB connection, DBConnectionProvider will fail, due to `conn.getDatabaseURL()`, which deferences `null`.
---
If you're a committer, …

Attempting to avoid a crash when running a project/file when there's no DB connection.

---

java/java.lsp.server/vscode/src/propertiesView/controlTypes.ts
java/java.lsp.server/vscode/src/propertiesView/propertiesHtmlBuilder.ts
java/java.lsp.server/vscode/src/propertiesView/propertiesView.ts
java/java.lsp.server/vscode/src/propertiesView/script.ts
java/java.lsp.server/vscode/src/typesUtil.ts

Fixing license in recently added sources

Fix license vscode

---

enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/InitialServerFileDistributor.java

Fixes https://github.com/apache/netbeans/issues/4927.
The strategy is to compute child module names based on the JAR and WAR files in the root directory of the exploded EAR instead of relying on the names computed from the Maven project configuration. Then the existing JAR and WAR files are not copied to the deployment package and exploded directories are created with names matching the existing JAR and WAR files. 
If there is any inconsistency (e.g. number of child modules detected from the exploded EAR is different to child modules detected from Maven project), the old behavior based on Maven configuration is preferred, just in case.
It's also possible to force the old behavior based on Maven configuration by setting the system property `glassfish.javaee..childModuleSource=mavenProject` …

[NETBEANS-4927] Maven EAR project fails to deploy on an app server

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolSearcher.java
java/java.lsp.server/vscode/src/extension.ts

Filtering Micronaut symbols by query prefix.
Added command to retrieve Micronaut symbols from other extensions.

Filtering symbols by query prefix.

---

java/maven/test/unit/src/org/netbeans/modules/maven/ModuleInfoSupportTest.java

25347dfe7f75e540d751f06b541320dc6c5511ce introduces a new unittest, that proved to be unstable in CI/CD pipeline. The failure can be reproduced after several tries. Adding 
workDir.getFileSystem().refresh(true);
seems to fix the issue. Hypothesis:
The new module files are written outside the filesystem infrastructure of NetBeans and the cache of the javac integration does not pick up the module files created by the javac-Tool.
Apart from the fix, style of the code was improved.

Fix unstable unittest org.netbeans.modules.maven.ModuleInfoSupportTest

---

java/form/test/qa-functional/src/org/netbeans/qa/form/VisualDevelopmentUtil.java

VisualDevelopmentUtil should close streams

---

enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/util/WildFlyProperties.java

Bugfix: Added ability to find `jakarta` related jars for wildfly server instances

---

ide/api.lsp/apichanges.xml
java/spi.java.hints/apichanges.xml

Hi,
just small fixes to apidoc to avoid 404 on documentation.

apidoc fixes for NB19

---

enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ui/wizard/archetype/Bundle.properties

Fix for #4552.
Fixes for building the new project with Java 17.
See https://github.com/juneau001/jakartaee10-archetype/pull/2 for more details.

Update Jakarta EE 10 archetype for a new project

---

rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Reference.Cargo.DottedName.toml
rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Reference.Cargo.toml
rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Test.Cargo.DottedName.toml
rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Test.Cargo.LiteralMultilineString.toml
rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Test.Cargo.LiteralString.toml
rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Test.Cargo.MultilineString.toml
rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Test.Cargo.String.toml

Adding licenses to rust.project test data files.

rust.project test data licenses

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/LspTreeViewServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeNodeRegistry.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeNodeRegistryImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeViewProvider.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/NodeChangeType.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/NodeChangedParams.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/NodeChangesParams.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/TreeViewService.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/explorer/TreeViewProviderTest.java
java/java.lsp.server/vscode/src/explorer.ts
java/java.lsp.server/vscode/src/extension.ts
java/java.lsp.server/vscode/src/propertiesView/propertiesView.ts
java/java.lsp.server/vscode/src/protocol.ts

LSP `TreeNodeListener` can now register to receive events generated by NBLS:
- node destroy
- node change
- node properties change
- node children change

Vscode ts listener can subscribe for NLS node event changes.

---

java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/Bundle.properties

Clarify Java Platform Manager UI.

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautStructureProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolFinder.java
java/java.editor/src/org/netbeans/modules/editor/java/JavaStructureProvider.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java

Command added to return all symbols within an opened document.

LSP: Command to get document symbols added.

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautStructureProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolFinder.java

Micronaut symbols should provide both expanded and selection ranges. Allows to place code lens in VS Code to proper positions.

LSP: Micronaut symbols position fixed.

---

php/php.dbgp/src/org/netbeans/modules/php/dbgp/ui/DbgpLineBreakpointCustomizerPanel.java

Improved validation when creating a line breakpoint:
- added check that the specified file is a php source file
https://github.com/apache/netbeans/assets/9607501/f31a0185-9989-4c36-9742-c76fced3ae81
- added check that the specified line number is less than the maximum line number in the file
https://github.com/apache/netbeans/assets/9607501/f04f5aae-09f7-40fa-a947-efd8e4021c3f
Focused on the implementation in https://github.com/apache/netbeans/blob/master/java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/breakpoints/LineBreakpointPanel.java

PHP: Improved validation when creating a line breakpoint

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolFinder.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/explorer/ProjectViewTest.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/progress/TestProgressHandlerTest.java

Couple of minor bugs fixed in finding Micronaut endpoints:
-  do not add client endpoints from tests
- add endpoints with default URI
- LSP server test should not fail on telemetry events

LSP: Micronaut endpoints finder fixes.

---

.github/ISSUE_TEMPLATE/netbeans_bug_report.yml

Apache NetBeans 19 current version

---

java/java.lsp.server/vscode/CHANGELOG.md

Changelog.md update for VSNetBeans 19.0.301
1. LSP improvements and fixes
2. Micronaut fixes
3. JDK21

Changelog.md document what changed compared to 19.0.0

---

ide/api.lsp/apichanges.xml
ide/api.lsp/manifest.mf
ide/api.lsp/src/org/netbeans/api/lsp/SignatureInformation.java
ide/api.lsp/src/org/netbeans/modules/lsp/SignatureInformationAccessor.java
ide/api.lsp/src/org/netbeans/spi/lsp/SignatureInformationCollector.java
ide/api.lsp/test/unit/src/org/netbeans/api/lsp/SignatureInformationTest.java
java/java.completion/nbproject/project.properties
java/java.completion/src/org/netbeans/modules/java/completion/JavaTooltipTask.java
java/java.editor/nbproject/project.xml
java/java.editor/src/org/netbeans/modules/editor/java/JavaSignatureInformationCollector.java
java/java.editor/src/org/netbeans/modules/editor/java/MethodParamsTipPaintComponent.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

The [signature help](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_signatureHelp) LSP requests implemented.

LPS: SignatureHelp implemented.

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddADBAction.java

Steps to reproduce:
1. Click Add Oracle Autonomous DB: (1/3)
2. Select the OCI profile (multiple defined on my system): (2/4)
3. Select Compartment: (3/5)
4. Click Back: (2/6)
5. Select a different Compartment: (3/7)
6. Click Back: (2/8)
7. etc.
Estimated number of inputs fixed in AddADBAction.

Fixed increasing number of steps

---

ide/extbrowser/src/org/netbeans/modules/extbrowser/MicrosoftEdgeBrowser.java

https://issues.apache.org/jira/browse/NETBEANS-4997
Solution is taken from https://stackoverflow.com/a/62452956

[NETBEANS-4997] use edge chromium syntax for opening URLs in Edge

---

apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/MavenNbModuleImpl.java
apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardPanel.java

NB module project wizard should not use snapshot versions.

---

.github/workflows/main.yml

noticed that they weren't active... luckily they are all green when tested locally and they seem to be stable.
-> lets activate them

CI: Enable java.editor.base tests.

---

nb/o.n.upgrader/src/org/netbeans/upgrade/AutoUpgrade.java
nbbuild/antsrc/org/netbeans/nbbuild/ReleaseJsonProperties.java

Address #6135 by limiting auto-upgrade importing of settings to latest 3 versions.  Does not stop manual importing of settings from earlier versions.
Have tested this ignores 8.2 and 13, but suggests more recent.

Limit auto-import to recent versions

---

java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java

followup to #6078
Originally used a CHM+`computeIfAbsent` but I optimized the map away since the method is rarely called and the bottle neck would be likely the IO code before the computation anyway -> cache would go down in the noise.
tests aren't hooked into CI and they don't run on JDK 11+, I might fix that later.

Compute JavaDoc URLs lazily

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautEntity.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautRepository.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/Utils.java

Test that project was created with database support before creating repository and entity classes from template.

Do not create repository and entity classes from template

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddDbConnectionToVault.java

Adding check for empty password when storing DB connection info to OCI Vault. This can happen when user doesn't select Remember Password for that connection

Ask for DB password when creating OCI Vault

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/db/Bundle.properties
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/ClassesSelectorPanel.form
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/ClassesSelectorPanel.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautController.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautRepository.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/Controller.html

While creating Micronaut Controllers from template, user is provided with an option to base the newly created controllers on selected Data Repository interfaces.

Allow for creating Micronaut Controllers based on Data Repository interfaces

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/MicronautConfigUtilities.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigDocumentation.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionCollector.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionTask.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautExpressionLanguageCompletion.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautExpressionLanguageHoverProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/expression/ExpressionTree.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/expression/MicronautExpressionLanguageParser.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/expression/MicronautExpressionLanguageUtilities.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/hyperlink/MicronautConfigHyperlinkProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/hyperlink/MicronautExpressionHyperlinkProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/mexp.tmLanguage.json

- Navigation from Micronaut Expression Language to Java elemements
- Documentation displayed when hovering over Java elements in Micronaut Expression Language

Micronaut Expression Language: Goto Declaration and Hover implementation

---

java/java.lsp.server/vscode/src/propertiesView/propertiesView.ts

Fixed command prefix for database properties access.

Fix old command prefix.

---

java/java.editor/src/org/netbeans/modules/editor/java/JavaBracesMatcher.java
java/java.editor/test/unit/src/org/netbeans/modules/editor/java/JavaBracesMatcherTest.java

some if-blocks got overlooked when this feature was updated.
fixes #4489

Fix multiline String brace matching.

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautEntity.java

Couple of small improvements:
- `@Serdeable` annotation added to generated entities
- `java.sql.Date` is used instead of `java.util.Date` in generated entities
- correct column name should be used in many-to-one relationships

@Serdeable annotation added to generated entities.

---

enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/RestUtils.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/client/ClientJavaSourceHelper.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/client/JaxRsGenerationStrategy.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/codegen/Constants.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/codegen/EntityResourcesGenerator.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/codegen/GenericResourceGenerator.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/codegen/RestFacadeMethod.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/codegen/RestMethod.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/codegen/SpringEntityResourcesGenerator.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/codegen/model/EntityClassInfo.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/codegen/model/SourceModeler.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/codegen/resources/GenericResource.template
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/support/JavaSourceHelper.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/wizard/Util.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/wizard/fromdb/EjbFacadeGenerator.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/wizard/fromdb/Operation.java
enterprise/websvc.restapi/src/org/netbeans/modules/websvc/rest/model/api/RestConstants.java
enterprise/websvc.restapi/src/org/netbeans/modules/websvc/rest/model/impl/RestApplicationsImpl.java
enterprise/websvc.restapi/src/org/netbeans/modules/websvc/rest/model/impl/RestServicesImpl.java
enterprise/websvc.restapi/src/org/netbeans/modules/websvc/rest/model/impl/Utils.java
enterprise/websvc.restapi/src/org/netbeans/modules/websvc/rest/spi/RestSupport.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/action/GenerationOptions.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/fromdb/EntityClassesPanel.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/fromdb/JavaPersistenceGenerator.java

Activates WebService Node integration into the project view:
And fixes generation at least for these wizards (manually tested):
- RESTful Java Client
- RESTful Web Services from Entity Classes
- RESTful Web Services from Database
- RESTful Web Services from Pattern

Improve code REST code generation/integration in JavaEE 9+ environments (jakarta namespace change)

---

webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/JsLanguage.java

The description of issues 214978 and 223050 was manually checked and behavior seems to be identical between master and this version.
Unittests were run and did not regress.
Closes: #6734

JS: Enable contiouus completion of JS private members of classes (# prefixed)

---

enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/wizards/Bundle.properties
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/ConfigBuilderProvider.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/admin/AdminFactoryTest.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersionTest.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/utils/EnumUtilsTest.java

GlassFish Notes:
- 11 bug fixes
- 18 component updates
- Project refactoring and maintenance of some modules
- Verify successful execution of `ant -Dcluster.config=release commit-validation`
- Verify successful execution of unit tests for modules `glassfish.common`, `glassfish.javaee`, `glassfish.tooling` and `glassfish.eecommon`
- Successfully register GlassFish 7.0.10, create a web app and verify that it works.
[Release Notes](https://github.com/eclipse-ee4j/glassfish/releases/tag/7.0.10)

Add support for GlassFish 7.0.10

---

enterprise/cloud.oracle/nbproject/project.xml
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddDbConnectionToVault.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/devops/DevopsProjectService.java
enterprise/cloud.oracle/test/unit/src/org/netbeans/modules/cloud/oracle/actions/AddDbConnectionToVaultTest.java
java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/LspDevopsConfigFinder.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/LspServerState.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/vscode/BUILD.md

The command for storing DB connection details into OCI Vault is now enhanced to also update OKE ConfigMap with the Vault OCID.

Update OKE ConfigMap with Vault details

---

.github/ISSUE_TEMPLATE/netbeans_bug_report.yml

It is sometimes difficult to figure out what the user was doing when the issue happened, lets try to ask more questions / make the repo field mandatory.

Issue template: make how-to-reproduce mandatory, add component field

---

ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/LanguageClientImpl.java

There are two problems in the LSP client code that prevent it from working with rust-analyzer, these are fixed here.
The core set of changes is more or less:
- handle `null` being returned from `codeAction`
- Send `initialized` event after we got `initServer` reply
The rest is nicer formatting and integration with logging for the JSON stream.

LSP Improvement

---

ide/tasklist.ui/src/org/netbeans/modules/tasklist/ui/TaskListModel.java

With JDK21 validation of removeIndexInterval and addIndexInterval methods was improved. This reveals an issue in the table model change events, that are published by the TaskListModel. For example it was observed, that the startRow and endRow indices were issued in the wrong order.
This results in:
```
java.lang.IndexOutOfBoundsException: index or length is negative
at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:656)
at java.desktop/javax.swing.JTable.tableRowsInserted(JTable.java:4539)
at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4475)
at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:302)
at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTa …
```

TaskList Model issues broken table model change events (breaks on JDK21+)

---

enterprise/micronaut/nbproject/project.xml
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionCollector.java
enterprise/micronaut/test/unit/src/org/netbeans/modules/micronaut/completion/MicronautExpressionLanguageCompletionTestBase.java
ide/api.lsp/apichanges.xml
ide/api.lsp/manifest.mf
ide/api.lsp/src/org/netbeans/api/lsp/Completion.java
ide/api.lsp/src/org/netbeans/modules/lsp/CompletionAccessor.java
ide/api.lsp/src/org/netbeans/spi/lsp/CompletionCollector.java
java/java.editor/nbproject/project.xml
java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionCollector.java
java/java.lsp.server/nbproject/project.xml
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

Using [CompletionItemLabelDetails](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemLabelDetails) to achieve a better rendering of completion items in VSCode.

LSP: Using labelDetails in CompletionItems

---

java/java.lsp.server/vscode/CHANGELOG.md

Update VSNetBeans CHANGELOG.MD for VSNetBeans 20.0.301 release.

Changelog update for VSNetBeans 20.0.301

---

NOTICE
nbbuild/notice-stub.txt

Update the notice copyright year.

Update NOTICE and notice-stub to 2024.

---

java/java.lsp.server/vscode/src/extension.ts

The 'save' instruction should be fixed to work on documents, rather than (open) editors. On Windows, the URI sent by LSP server differs from the representation in vsode. vscode uses lowercase drive letters for some reason.

Work on documents, not on editors. Translate URIs on Windows

---

java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/syntaxes/java-st-injection.json
java/java.lsp.server/vscode/syntaxes/java.tmLanguage.json

Java TextMate grammar updated to recent version.

VSCode: Java TextMate grammar updated.

---

java/java.lsp.server/nbcode/nbproject/platform.properties

This should fix master after https://github.com/apache/netbeans/commit/5a459334cdd299a6e95c5f13ef21d5afb355cebe.

Including org.netbeans.modules.editor.tools.storage, as it is a required dependency as of recently.

---

java/java.lsp.server/vscode/CHANGELOG.md
java/java.lsp.server/vscode/README.md

Added badges into VSNetBeans README.MD and added 21.0.0 into CHANGELOG.MD. A little late for 21.0.0 unfortunately but these are just doc changes so can go into next build of 21.0.0

README and CHANGELOG update

---

enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/wizards/Bundle.properties
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/ConfigBuilderProvider.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/admin/AdminFactoryTest.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersionTest.java
enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/utils/EnumUtilsTest.java

NetBeans GlassFish module notes:
- Add support for GlassFish version 7.0.12
- Verify successful execution of unit tests for modules `glassfish.common`, `glassfish.javaee`, `glassfish.tooling`, and `glassfish.eecommon`
- Successfully register GlassFish 7.0.12, create a web app and verify that it works.
[Release Notes](https://github.com/eclipse-ee4j/glassfish/releases/tag/7.0.12)

Add support for GlassFish 7.0.12

---

php/php.project/external/binaries-list
php/php.project/external/phpsigfiles-1.7-license.txt
php/php.project/external/phpsigfiles-1.7-notice.txt
php/php.project/nbproject/project.properties

PHP Documentation: Date: 22 Feb 2024
phpsigfiles-1.7
Fix https://github.com/apache/netbeans/issues/6358

Regenerate PHP signature files

---

enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/ide/ui/WildflyPluginUtils.java

This is a fix for [6997](https://github.com/apache/netbeans/issues/6997)
With wildfly 31 the location of the MANIFEST.MF has changed. It's now in wildfly-feature-pack-product-conf-31.0.0.Final.jar
I created a method to extract the Manifest Attributes from the jar file.  Otherwise it ready the MANIFEST.MF as before.

Adding support for Wildfly 31

---

enterprise/web.core.syntax/src/org/netbeans/modules/web/core/syntax/JSPProcessor.java
enterprise/web.core.syntax/src/org/netbeans/modules/web/core/syntax/JspSyntaxSupport.java
enterprise/web.core.syntax/src/org/netbeans/modules/web/core/syntax/SimplifiedJspServlet.java
enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/el/FaceletsELPlugin.java

Enable code completion in JSF and JSP pages in Jakarta based projects

---

enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/jpa/dao/AppServerValidationPanel.java
enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/jpa/dao/EjbFacadeWizardIterator.java
enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/jpa/dao/EjbFacadeWizardPanel2.java
enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ui/logicalview/ejb/action/AbstractAddMethodStrategy.java
enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ui/logicalview/ejb/action/AddBusinessMethodStrategy.java
enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ui/logicalview/ejb/action/AddCreateMethodStrategy.java
enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ui/logicalview/ejb/action/AddFinderMethodStrategy.java
enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ui/logicalview/ejb/action/AddHomeMethodStrategy.java
enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ui/logicalview/ejb/action/AddSelectMethodStrategy.java
enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ui/logicalview/ejb/shared/ComponentMethodModel.java
enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ui/logicalview/ejb/shared/MethodNode.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/spi/entitymanagergenerator/ContainerManagedJTAInjectableInWeb.java
java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/spi/entitymanagergenerator/EntityManagerGenerationStrategySupport.java

Fix detection of support for generation session beans from entity classes and support jakarta package names

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionCollector.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionTask.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/expression/MicronautExpressionLanguageParser.java

Code completion for parameters of repository finder methods added.

Micronaut: Code completion for repository finder methods enhanced.

---

ide/parsing.api/apichanges.xml
ide/parsing.api/src/org/netbeans/modules/parsing/api/ParserManager.java
ide/parsing.api/src/org/netbeans/modules/parsing/api/ResultProcessor.java
ide/parsing.api/test/unit/src/org/netbeans/modules/parsing/api/SourceTest.java

Not the most groundbreaking change in NB, just allows the Parser result processing to use more modern syntax.

Made Parsing API a bit more Functional

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionCollector.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionTask.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/Utils.java

Code completion for Micronaut repository finder methods improved. Searching a finder method name for the general [query pattern](https://micronaut-projects.github.io/micronaut-data/latest/guide/#querying), code completion tries to provide the necessary methods parameters.

Micronaut: Code completion for repository finder methods improved.

---

java/java.lsp.server/vscode/src/extension.ts

Language server startup simplified.

LSP: Simplified server startup.

---

platform/api.visual/apichanges.xml
platform/api.visual/arch.xml
platform/api.visual/examples-readme.txt
platform/api.visual/src/org/netbeans/api/visual/widget/Widget.java
platform/api.visual/src/org/netbeans/api/visual/widget/doc-files/documentation.html

Sometimes assertion on scene validate may occurs, Trying to link to the actual site to be more helpful.
Fixing also link to ML and repository.
Fix to the site are in this PR https://github.com/apache/netbeans-antora-site/pull/19

link visual api to effective site

---

platform/core.windows/src/org/netbeans/core/windows/services/NbPresenter.java

The layout on many warning/error dialogs looks a bit broken right now when a short message is displayed, while looking serviceable with larger content (#6575 for screenshots).
the reason for that is because the JOptionPane does not compute its minimum size properly as can be seen in the debug snapshot:
if we set it to a more reasonable value (min size ~ icon size), small dialogs look much nicer:
larger dialogs still look as expected:
Looking at the code, it appears as if something similar has been attempted before for the basic metal LAFs, but wasn't updated for custom LAFs.
testing:
- don't have any project open
- `profile -> insert profiling point`

Tweak JOptionPane minimum size.

---

.github/ISSUE_TEMPLATE/config.yml
README.md
enterprise/j2ee.dd/doc/ddapi_architecture.html
ide/editor.fold/arch.xml
ide/editor.lib2/src/org/netbeans/spi/editor/highlighting/package.html
ide/lexer/src/org/netbeans/api/lexer/TokenId.java
ide/projectui/arch.xml
ide/versioning.core/arch.xml
ide/versioning/arch.xml
java/java.j2seplatform/arch.xml
java/java.j2seproject/arch.xml
platform/o.n.bootstrap/arch.xml
platform/o.n.bootstrap/src/org/netbeans/CLIHandler.java
platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/LFCustoms.java
platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/Startup.java
platform/openide.actions/apichanges.xml
platform/openide.modules/src/org/openide/modules/doc-files/api.html
platform/openide.util.ui/src/org/openide/util/actions/CallbackSystemAction.java
platform/openide.windows/apichanges.xml
platform/openide.windows/arch.xml
platform/openide.windows/src/org/openide/windows/TopComponentGroup.java
platform/openide.windows/src/org/openide/windows/doc-files/api.html

Url fixes as pointed out in  comment of #7224

clean url fixes

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautExpressionLanguageCompletion.java
enterprise/micronaut/test/unit/src/org/netbeans/modules/micronaut/completion/MicronautExpressionLanguageCompletionTestBase.java

Make sure the project's indexing finishes before starting the completion tests. All completion tests share a single project.

Micronaut: Making code completion tests more stable.

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionCollector.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautDataCompletionTask.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautController.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautDataEndpointGenerator.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautEndpointTestGenerator.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/Utils.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolFinder.java
java/java.lsp.server/vscode/src/extension.ts

Endpoint method generator for non-db based controllers added. It is available either via code completion or as a source action.

Micronaut: Endpoint method generator for non-db based controllers added.

---

php/php.editor/src/org/netbeans/modules/php/editor/codegen/SemiAttribute.java

- https://github.com/apache/netbeans/issues/7170
- Add a `null` check

Prevent NPE #7170

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddDbConnectionToVault.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/AddNewAssetCommand.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/AddSuggestedItemAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/CloudAssets.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/DependencyUtils.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/Step.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/Steps.java

- The command for storing DB connection detail to the OCI Vault now also updates project dependencies. 
- Remove duplicates in multistep dialogs implementation.

Update dependencies for OCI Vault integration and clean up multistep dialogs

---

enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/facelets/FaceletsLibrarySupport.java

To parse JSF libraries in an (more or less) isolated environment, the JSF library parsing is done with a special context class loader in place.
However as part of the preparation of the parsing process also maven embedded is used to fetch the JSF reference implementation(s).
For a subset of users this exception was oberserved:
```
SEVERE [org.openide.util.Exceptions]
java.lang.ClassCastException: class org.apache.commons.logging.impl.LogFactoryImpl cannot be cast to class org.apache.commons.logging.LogFactory (org.apache.commons.logging.impl.LogFactoryImpl is in unnamed module of loader org.netbeans.modules.web.jsf.editor.facelets.FaceletsLibrarySupport$3 @473436a0; org.apache.commons.logging.LogFactory is in unnamed module of loader org.netbeans.modules.netbinox.NetbinoxLoader @1f369488) …
```

Run maven embedder with the "normal" NetBeans environment not special context class loader

---

ide/notifications/src/org/netbeans/modules/notifications/FlashingIcon.java

This patch, in combination with https://github.com/apache/netbeans/pull/7463, makes the notification bubble in the status bar look sharp on Retina/HiDPI screens.

Make the status bar Notification bubble sharp on HiDPI/Retina screens

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautStructureProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolErrorProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolFinder.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolSearcher.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/vscode/src/extension.ts

Endpoint and Bean symbols originating from libraries should be provided in addition to those originating in project sources.

Micronaut: Provide Endpoint and Bean symbols originating from libraries.

---

extide/gradle/src/org/netbeans/modules/gradle/execute/AbstractGradleExecutor.java

Fixed non working RepeatExecution action for Gradle projects.

Implement repeatExecution for GradleItem

---

java/maven/src/org/netbeans/modules/maven/queries/RepositoryMavenCPProvider.java

Gradle generated POM files does not contain `compileOnly(...)` dependencies supported by gradle and therefore cannot be used to provide complete compile classpath for the given file.
Better to fallback to `DefaultClassPathProvider` in such case.

Do not provide compile classpath for repository artifacts with POM files generated by Gradle.

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautEntity.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java

* Prevent duplicates in workspace symbols
* `No database support libraries found` error message changed to `No Micronaut Data support libraries found`

Micronaut: minor bugs fixed.

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolFinder.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolSearcher.java

When scanning for Micronaut symbols, classpaths should be computed for the particular source roots, not the project folder.

Micronaut: Use correct classpath when scanning for Micronaut symbols.

---

.github/workflows/main.yml
apisupport/timers/nbproject/project.properties
apisupport/timers/test/unit/src/org/netbeans/modules/timers/ObjectListRendererTest.java
platform/lib.uihandler/nbproject/project.properties
platform/lib.uihandler/src/org/netbeans/lib/uihandler/LogFormatter.java
platform/lib.uihandler/src/org/netbeans/lib/uihandler/LogRecords.java
platform/lib.uihandler/test/unit/src/org/netbeans/lib/uihandler/LogFormatterTest.java
platform/lib.uihandler/test/unit/src/org/netbeans/lib/uihandlerserver/LogRecordsTest.java
platform/netbinox/test/unit/src/org/netbeans/modules/netbinox/BundleURLConnectionTest.java
platform/openide.nodes/src/org/openide/nodes/Children.java
platform/openide.text/test/unit/src/org/openide/text/NotifyModifiedTest.java
platform/openide.util.ui/test/unit/src/org/openide/xml/XMLUtil2Test.java

Fixed remaining platform/apisupport tests on JDK11+

---

java/java.source/nbproject/project.properties
java/java.source/src/org/netbeans/modules/java/Bundle.properties
java/java.source/src/org/netbeans/modules/java/JavaNode.java

- will now display the class-file version and the preview flag in the file properties table
- little cleanup in the touched file
(last entry)

Add class-file format to the file properties sheet

---

platform/api.dashboard/src/org/netbeans/modules/dashboard/DashboardPanel.java
platform/api.dashboard/src/org/netbeans/modules/dashboard/WidgetPanel.java

Hopefully fixes occasional visual glitches seen with dynamic dashboard widgets such as recent projects and recent files. Revalidates and repaints the whole panel when widget elements change.

Ensure visible dashboard widget repainted when elements changed.

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/DependenciesAnalyzer.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/SuggestedItem.java
enterprise/cloud.oracle/test/unit/src/org/netbeans/modules/cloud/oracle/assets/CloudAssetsTest.java

Showing users that container repository can be added to Cloud Assets View and giving them easier way to do that.

Adding container repository from Cloud Assets View

---

platform/libs.flatlaf/external/binaries-list
platform/libs.flatlaf/external/flatlaf-3.5.1-license.txt
platform/libs.flatlaf/manifest.mf
platform/libs.flatlaf/nbproject/project.properties
platform/libs.flatlaf/nbproject/project.xml

bugfix release, see
https://github.com/JFormDesigner/FlatLaf/releases/tag/3.5.1

Update FlatLaf from 3.5 to 3.5.1

---

java/java.lsp.server/vscode/CHANGELOG.md
java/java.lsp.server/vscode/README.md

VSNetBeans 23.0.0 README.MD and CHANGELOG.MD updates for upcoming release.

VSNetBeans 23.0 release changelog and README upd.

---

java/java.lsp.server/vscode/src/extension.ts
java/java.lsp.server/vscode/src/panels/RunImageGuidePanel.ts
java/java.lsp.server/vscode/webviews/run-image-guide.handlebars
java/java.lsp.server/vscode/webviews/ssh-guide.handlebars

Guides now include instructions how to install Docker on Compute instance, and how to change key file permissions in order to avoid errors

Instuctions to install Docker and to change key file permissions

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/CreateContainerRepository.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/CreateContainerRepositoryCommand.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/CreateResourceCommand.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/OCIItemCreator.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/AddNewAssetCommand.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/AddSuggestedItemAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/requests/ContainerRepositoryRequest.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/requests/OCIItemCreationDetails.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/steps/ItemCreationDecisionStep.java

Add new Cloud Assets command and Add Suggested Item action will now offer to create new container repository

Create container repository command

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddADBAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/steps/DatabaseConnectionStep.java

Adding an option to register a new database in a list of available db connections.

Adding option to register a new database in a list of available db connections

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/hints/MicronautConfigErrorProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolSearcher.java

Warnings should be created for the Micronaut config properties with unset values.

Micronaut: Report warnings for properties in config files with unset values.

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/hints/MicronautConfigErrorProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolSearcher.java
ide/parsing.indexing/apichanges.xml
ide/parsing.indexing/nbproject/project.properties
ide/parsing.indexing/src/org/netbeans/modules/parsing/spi/indexing/ErrorsCache.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ErrorsNotifier.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java

LSP server should notify its client to publish diagnostics collected on project scan.

LSP: Push diagnostics collected on project indexing.

---

.github/workflows/dependency-checks.yml
.github/workflows/main.yml

and minor version bump elsewhere
EA builds disappear at some point.

CI: switch JDK 23 from ea to ga

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/OCIPropertiesProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautEntity.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractApplyEditsImplementation.java
java/java.lsp.server/vscode/src/extension.ts

Fix saving of modified MN dependencies
Accept file:/ as well as file:/// for save
Properly complete OCIPropertiesProvider command

Fix saving of modified MN deps, fix OCI props provider, accept file:/ as well as file:/// for save

---

.github/ISSUE_TEMPLATE/netbeans_bug_report.yml

Update issue template post NB23 release

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/AddNewAssetCommand.java

Correcting order of steps when adding Oracle Autonomous Database, so the project is properly resolved.

Fix adding dependencies for ADB

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddDbConnectionToVault.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/ConfigMapUploader.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/AddNewAssetCommand.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/DependencyUtils.java

Add missing dependency on micronaut-jdbc-hikari for Oracle ADB.

Add all necesary dependencies for ADB

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/ImageBuilderCommand.java
java/java.lsp.server/vscode/package.json

Adding and option to build Native Image docker image

Adding a build native docker option

---

nbbuild/javadoctools/disallowed-links.xml

Just a trivial fix to allow this page in apidoc

allow reference for maven page

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/hints/MicronautConfigErrorProvider.java
ide/csl.api/src/org/netbeans/modules/csl/core/TLIndexerFactory.java
ide/parsing.indexing/apichanges.xml
ide/parsing.indexing/nbproject/project.properties
ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/errors/TaskCache.java
ide/parsing.indexing/src/org/netbeans/modules/parsing/spi/indexing/ErrorsCache.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ErrorsNotifier.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.source.base/src/org/netbeans/modules/java/source/indexing/JavaCustomIndexer.java
java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java

An attempt to speed up publishing diagnostics collected on project scan by directly publishing data from caches.

LSP: Speed up publish diagnostics on project scan.

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/commands/MicronautGetBuildPropertiesCommand.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautEndpointRequestProvider.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/db/Utils.java
enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolFinder.java
java/java.lsp.server/vscode/src/extension.ts

Adding support for
- obtaining values of Micronaut build properties.
- navigation to Micronaut serverless endpoints.
Fixing couple of command names

Micronaut support: minor enhancements.

---

java/java.lsp.server/vscode/CHANGELOG.md

Updated Changelog.md for upcoming VSNetBeans 23.9.9

VSNetBeans 23.9.9 changelog update

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/KubernetesUtils.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/RunInClusterAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/SetClusterNamespaceAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/SetReferenceNameAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/compute/ClusterItem.java
java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/LspAssetsDecorationProvider.java
java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts

Adding an action to enable namespace switching on a Kubernetes cluster node in the Cloud Assets window.

Adding action for switching of a namespace on k8s cluster

---

enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/ide/ui/WildflyPluginUtils.java

See issue #7521
WildflyPluginUtils.java - Added an entry for EAP_8_0 and mapped it to WILDFLY_26_0_0
WildflyJ2eePlatformFactory.java - Added an entry for EAP_8_0 to map it to WILDFLY_PROFILES and version 26
---
If you're a committer, please label the PR …

Fix JBoss 8 Startup detection

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/ConfigMapUploader.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DevOpsProjectConfigMapUploader.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/ConfigMapProvider.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/CreateConfigCommand.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/RunInClusterAction.java
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts

Before running `RunInClusterAction`, CloudAssets properties will be uploaded to ConfigMap

Create ConfigMap before running the app

---

nbbuild/javadoctools/disallowed-links.xml

accept a bit more of maven mini guide as anchor was not allowed

Update disallowed-links.xml for apidoc check

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCINode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/bucket/BucketItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/compute/ClusterItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/compute/ComputeInstanceItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/database/DatabaseItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/items/OCIItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/vault/KeyItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/vault/KeyNode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/vault/SecretItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/vault/SecretNode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/vault/VaultItem.java
java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/LspAssetsDecorationProvider.java
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/extension.ts

Adding a new command to open resource in OCI console

Open in OCI Console command

---

enterprise/cloud.oracle/arch.xml
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddADBAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletDialog.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/OpenServiceConsoleAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/AddNewAssetCommand.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/AddSuggestedItemAction.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/CloudAssets.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/DependenciesAnalyzer.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/PropertiesGenerator.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/SuggestedItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/database/DatabaseNode.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/policy/PolicyGenerator.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/resources/layer.xml
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/steps/DatabaseConnectionStep.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/steps/ItemTypeStep.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/steps/SuggestedStep.java
enterprise/cloud.oracle/test/unit/src/org/netbeans/modules/cloud/oracle/assets/CloudAssetsTest.java

This PR aligns the database path with other resource names by ensuring they are all in singular form. This change enhances consistency across resource naming conventions, improving clarity and uniformity throughout the project.

Align the database path with the other resource names, ensuring all are in singular form.

---

platform/libs.flatlaf/external/binaries-list
platform/libs.flatlaf/external/flatlaf-3.5.2-license.txt
platform/libs.flatlaf/manifest.mf
platform/libs.flatlaf/nbproject/project.properties
platform/libs.flatlaf/nbproject/project.xml

~bigfix~ bugfix release, see https://github.com/JFormDesigner/FlatLaf/releases/tag/3.5.2

Update FlatLaf from 3.5.1 to 3.5.2

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/CloudAssets.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/IntegrationCommands.java

Two command for integration of Cloud Assets with other VS Code extensions

VSCode integration commands

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/ConfigMapUploader.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/assets/CreateConfigCommand.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/developer/ContainerRepositoryItem.java
enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/developer/ContainerTagItem.java
java/java.lsp.server/vscode/src/extension.ts

Fix and improvement how docker image is executed in the OCI Compute Instance.

Fix how docker image is executed in the OCI Compute Instance

---

platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/TabControlButtonFactory.java

Tabcontrol: Use NbBundle to fetch correct translation

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/hints/MicronautConfigErrorProvider.java
ide/csl.api/src/org/netbeans/modules/csl/core/TLIndexerFactory.java
ide/parsing.indexing/apichanges.xml
ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/errors/TaskCache.java
ide/parsing.indexing/src/org/netbeans/modules/parsing/spi/indexing/ErrorsCache.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ErrorsNotifier.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
java/java.source.base/src/org/netbeans/modules/java/source/indexing/JavaCustomIndexer.java
java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java
java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorkerTest.java

Sync delivery to master handling the merge conflicts while keeping all commits from delivery intact (just in case we need further changes)
Fix for #8003 Alternative to #8006 using the process used other times this has been necessary, eg. #6656 
@mbien please verify contents.

Sync delivery to master after 24-rc5 (merge conflict resolved)

---

java/java.source.base/test/unit/src/org/netbeans/api/java/source/GeneratorUtilitiesTest.java
java/java.source.base/test/unit/src/org/netbeans/api/java/source/TreeUtilitiesTest.java
java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBJavacTrees.java

Consider this code, with a code completion invocation:
```
package test;
public class Test {
private void test(Runnable r) {
test(() -> {
new Base<Void, Void>() {
//code completion here
};
});
}
}
class Base<T1, T2> {
public T1 test(T1 p) {}
}
```
invoke the code completion at the marked place, and select the "test(Void p) - override" option. Nothing will happen, nothing will added to the source code.
The reason is this:
- there is an (API) `Scope` taken at the place of the cursor. The `Scope`'s `Env<AttrContext>` has a `returnResult` filled, and this `returnResult` has a `checkContext` that throws exceptions. This is part of method overload resolution in javac.
- the code completion will delegate to `GeneratorUtilities.createOverridingMethod`, attempting to create the method.
- …

Ensure AttrContext.returnResult's checkContext is set to Check.basicHandler in javac's Scopes, to avoid it throwing exceptions.

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeClientWrapper.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeLanguageClient.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/OutputMessage.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractLspInputOutputProvider.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/TestCodeLanguageClient.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/explorer/ProjectViewTest.java
java/java.lsp.server/vscode/src/extension.ts
java/java.lsp.server/vscode/src/protocol.ts

All outputs were written to the Apache Netbeans Language Server channel. This meant that even build logs were written there and mixed together with netbeans log messages. Now a new channel will be created for new LspIO.

Create new output channel for every LspIO

---

.github/ISSUE_TEMPLATE/netbeans_bug_report.yml

Update issue template post NB24 release

---

.asf.yaml

dependabot task is failing and it wasn't used anyway -> lets disable it
https://github.com/apache/netbeans/actions/workflows/dependabot/dependabot-updates?query=branch%3Amaster

Disable dependabot

---

webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/navigation/JsonOccurrencesFinder.java
webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/navigation/OccurrencesFinderImpl.java

Prevent NPE

---

enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/steps/TenancyStep.java

Correct region code should be displayed while selecting OCI Profile in Cloud Assets.

OCI Cloud Assets: Select OCI Profile should display correct region code.

---

.asf.yaml

Add petrovic-d as collaborator for NetBeans project
https://github.com/apache/netbeans/issues?q=is%3Apr+author%3Apetrovic-d

Add petrovic-d as collaborator for Apache/NetBeans

---

enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/micronaut-actions-maven.xml

`Run in Continuous Mode` action should build and listen for changes in dependencies of the selected Micronaut projects.

Micronaut: Run in Continuous Mode should build/listen for changes in dependencies of the selected project

---

java/form/src/org/netbeans/modules/form/resources/templates/Dialogs/Application_java
java/form/src/org/netbeans/modules/form/resources/templates/Dialogs/OkCancelDialog_java
java/form/src/org/netbeans/modules/form/resources/templates/SwingForms/JDialog_java
java/form/src/org/netbeans/modules/form/resources/templates/SwingForms/JFrame_java

Improwe Swing GUI templates: 
Use multicatch in LookAndFeel initialization code.
Replace new Runnable() ... with lambda call
---

Improve Swing Templates

---

groovy/gradle.groovy/src/org/netbeans/modules/gradle/groovy/Bundle.properties

typo
---
<details open>
1. [x] Was this PR [correctly …

Fix typo in Groovy with Gradle project category

---

java/java.lsp.server/vscode/src/extension.ts

Fix error when verifying JDK

---

ide/csl.api/src/org/netbeans/modules/csl/editor/semantic/SemanticHighlighter.java
webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/JsSemanticAnalyzer.java

Prevent NPE in SemanticHighlighter and fix JsSemanticAnalyser

---

.asf.yaml

- explicitly disable linear history

Attempt 2 to repair asf repo config (get merge button back)

---

.asf.yaml

main purpose is to trigger the repo parser again since asf infra fixed the stuck settings for us.

Update .asf.yaml doc

---

ide/spi.palette/src/org/netbeans/spi/palette/PaletteVisibility.java
ide/subversion/src/org/netbeans/modules/subversion/ui/repository/RepositoryConnection.java
ide/tasklist.todo/src/org/netbeans/modules/tasklist/todo/settings/ToDoCustomizer.java
ide/tasklist.ui/src/org/netbeans/modules/tasklist/filter/TaskGroupCondition.java
ide/tasklist.ui/src/org/netbeans/modules/tasklist/filter/TypesPanel.java
ide/xml/src/org/netbeans/modules/xml/wizard/impl/ExternalReferenceDataNode.java
ide/xml/src/org/netbeans/modules/xml/wizard/impl/SchemaPanel.java
java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/models/DebuggingTableModel.java
java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/testapps/EvaluatorApp.java
java/form/src/org/netbeans/modules/form/FormDesigner.java
java/maven.checkstyle/src/org/netbeans/modules/maven/format/checkstyle/ModuleConvertor.java

project wide except tests.
skipped `org.openide.util.WeakSet` ~since I believe I found a bug there, needs separate treatment if confirmed.~ no bug but I updated it in https://github.com/apache/netbeans/pull/8380
part of https://github.com/apache/netbeans/issues/8257

Replace Boolean constructor usage.

---

harness/apisupport.harness/build.xml
java/lib.jshell.agent/nbproject/project.properties
java/maven/build.xml
nbbuild/templates/common.xml
platform/libs.asm/external/asm-9.8-license.txt
platform/libs.asm/external/binaries-list
platform/libs.asm/nbproject/project.properties
platform/libs.asm/nbproject/project.xml

- minor bugfixes (https://asm.ow2.io/versions.html)
- Java 25 opcodes
compared the changes with the last update https://github.com/apache/netbeans/pull/7886

Update ASM from 9.7.1 to 9.8

---

profiler/profiler.nbimpl/src/org/netbeans/modules/profiler/nbimpl/providers/JavaProfilerSourceImpl.java

solves issue #8388
See issue. 
Tiny change.

NPE in profiler during code scan on start and or opening existing (netbeans) project

---

apisupport/maven.apisupport/test/unit/src/org/netbeans/modules/maven/apisupport/NBMNativeMWITest.java
java/maven/src/org/netbeans/modules/maven/options/MavenVersionSettings.java

Bump MavenVersionSettings fallback versions for NB26.

---

enterprise/web.jsf/src/org/netbeans/modules/web/jsf/dialogs/BrowseFolders.java

Current behavior (can be tested with New File -> JavaServer Faces -> Facelets Template Client -> Next -> Browse):
With the PR applied:
---
<details open>
If you're a committer, please label the PR …

JSF File Chooser: order nodes alphabetically

---

enterprise/web.primefaces/nbproject/project.properties
enterprise/web.primefaces/src/org/netbeans/modules/web/primefaces/PrimeFacesTagFeatureProvider.java

- handle new namespaces
- added PFE components
- added missing components
---
<details open>
If you're a committer, please label the PR before pressing "Create pull request" so that the right test …

Improve PrimeFacesTagFeatureProvider

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java
java/maven/src/org/netbeans/modules/maven/execute/MavenCommandLineExecutor.java

During investigation of #8681, it turned out that during the test execution Maven build is **run twice in parallel over the same project directory**. Maven itself does not lock out itself in such case and one maven will hapilly delete or update a JAR while another maven tries to use it or generate classes while other maven tries to read them - leading to all kinds of mysterious errors, as I've noted in comments to #8681.
This bug is also 'reachable' by users of VSNetbeans extension: just try to Debug the applicaiton before the priming build completes. In most cases the parallel builds won't interefere that much, but in an unlucky case one of them or both fail with various errors.
This PR changes behaviour of DAP protocol implementation in NetBeans Language Server so that if a Language …

DAP server waits on its sibling LSP to prime projects. DAP reports it is done only afer projects are readable

---

java/java.file.launcher/src/org/netbeans/modules/java/file/launcher/actions/SingleJavaSourceRunActionProvider.java

To unify run behaviour for all the three types of projects (Maven/Gradle/Standalone)
Changes: 
Changed the task name of single source projects to match that of maven or gradle. This task name is used to push output into right path [here](https://github.com/apache/netbeans/blob/1cd73c7ae099815df04dd869a94d2ff845248c14/java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractLspInputOutputProvider.java#L188-L191)
---
<details open>
- are contributed solely under the terms and conditions of the Apache License 2.0 (see …

Task name corrected in single source run

---

java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
java/java.source.base/test/unit/src/org/netbeans/api/java/source/gen/SwitchTest.java

Prevents a crash when rewriting switch with pattern case labels.
Not sure if this should go to NB27 - feel free to change to master.
closes https://github.com/apache/netbeans/issues/8296
---
<details open>
If you're a first time contributor, see the Contributing guidelines for more …

[GITHUB-8296] Adding support for PatternCaseLabel

---

java/java.hints/src/org/netbeans/modules/java/hints/errors/AddParameterOrLocalFix.java
java/java.hints/src/org/netbeans/modules/java/hints/errors/Bundle.properties
java/java.hints/src/org/netbeans/modules/java/hints/errors/CreateElement.java
java/java.hints/src/org/netbeans/modules/java/hints/errors/CreateElementUtilities.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/AddParameterOrLocalFixTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/CreateElementTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/CreateMethodTest.java
java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
java/java.source.base/test/unit/src/org/netbeans/api/java/source/gen/ForLoopTest.java

Fixing several problems related to "create element" fixes (like "Add local variable"):
- consider code:
```
for (it = Set.of().iterator()) {}
```
currently, there's a fix that offers to add a local variable, but adds it above the `for`. This PR adds `Create for init variable`, which adds the variable to the for init.
- correct detection of target types for switch expressions (`yield` or `case` directly).
- fix for: [NETBEANS-4304](https://issues.apache.org/jira/browse/NETBEANS-4304) / https://github.com/mbien/nb-reprorepo/blob/master/tinybugs/src/main/java/fixed/in28/bugs/createmethod/CreateMethodWrongReturnType.java
---
<details open>
By opening a pull request you confirm that, unless …

Fixing problems related to create element fixes.

---

java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/SemanticHighlighterBase.java
java/java.editor.base/test/unit/src/org/netbeans/modules/java/editor/base/semantic/DetectorTest.java

closes https://github.com/apache/netbeans/issues/8475
---
<details open>
1. [x] …

Fixing highlighting for cases - needs to reset token index after searchig for 'when'

---

ide/defaults/src/org/netbeans/modules/defaults/BlueTheme-Java-fontsColors.xml
ide/defaults/src/org/netbeans/modules/defaults/CityLights-Java-fontsColors.xml
ide/defaults/src/org/netbeans/modules/defaults/CityLights-fontsColorsDefaults.xml
ide/defaults/src/org/netbeans/modules/defaults/NetBeans55-Java-fontsColors.xml
ide/defaults/src/org/netbeans/modules/defaults/NetBeans55-fontsColorsDefaults.xml
ide/defaults/src/org/netbeans/modules/defaults/NetBeansEarth-Java-fontsColors.xml
ide/textmate.lexer/src/org/netbeans/modules/textmate/lexer/resources/fontsColors.xml
java/java.editor/src/org/netbeans/modules/java/editor/resources/fontsColors.xml
platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/fontscolors/FlatLafDark-Java-tokenColorings.xml

I have started to use `record`s a lot recently, and am always irritated when their declarations are not colored like other types. The semantic parsing support seemed to be there, and the highlighting type was even defined, it was just not bound to anything.
Before:
After:
---
<details open>
If you're a first time contributor, …

Define `mod-record-declaration` in Java editor themes

---

enterprise/tomcat5/src/org/netbeans/modules/tomcat5/deploy/TomcatManager.java
enterprise/tomcat5/src/org/netbeans/modules/tomcat5/optional/StartTomcat.java
enterprise/tomcat5/src/org/netbeans/modules/tomcat5/util/Utils.java

The first time I start a Tomcat instance after opening netbeans, I get this annoying popup:
This PR fixes the issue by passing the correct credentials when testing the connection to the Tomcat manager.
NB: the issue happens only when the Tomcat Server header is empty, so by default on Tomcat 8.5+
---
<details open>
Please make sure (eg. `git log`) that all commits have a valid name and email address …

Avoid triggering the authentication popup when starting Tomcat instance

---

java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/GradleSourcesImpl.java

Fix for #5986 
Original code expects only Scala code as Gatling tests, but actuallly it maybe also Java, Kotlin and Groovy.
Fixed minor typos
---
<details open>
If you're a committer, please label …

Fix Gradle Gatling Project loading error

---

java/java.api.common/src/org/netbeans/modules/java/api/common/queries/ModuleInfoAccessibilityQueryImpl.java
java/java.api.common/test/unit/src/org/netbeans/modules/java/api/common/queries/ModuleInfoAccessibilityQueryImplTest.java
java/java.api.common/test/unit/src/org/netbeans/modules/java/api/common/queries/UnitTestsCompilerOptionsQueryImplTest.java
java/java.source.base/src/org/netbeans/modules/java/source/JavaSourceUtilImpl.java
java/java.source.base/test/unit/src/org/netbeans/modules/java/source/JavaSourceUtilImplTest.java

When getting the module definition from a `module-info.java` file, use `getModule` rather than scanning through `getTypeDecls`. 
In the compiler API, the latter used to work up until JDK16, then it was changed for subsequent releases, so that the module object is no longer considered a type declaration. See discussion in #8560.
Tests included (there were no tests for this previously). I have not squashed them so it's possible to see the tests run without the fix. Please advise.
Fixes #8560 
Fixes #8614
---
<details open>
- are contributed solely under the terms and …

Fix getting package export status in a modular project

---

platform/openide.util.lookup/src/META-INF/gradle/incremental.annotation.processors

ServiceProverProcessor behaves in a way compatible with this Gradle feature. Large gradle projects using the Processor will see a large performance boost in build time after the initial build.
This has been tested in an old fork of just the lookup/service annotation and processor code and we are looking to provide the change back to the source.
I can certainly attempt to provide some form of test, but an admittedly rough search of the code did not show many Gradle based tests from which I could base the style of the test on. If a test is required, some guidance there would be appreciated.
---
<details open>
By opening a pull request you confirm that, unless explicitly stated otherwise, the …

Indicate support for Gradle's incremental annotation processing.

---

extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java

In Gradle 9, `FileCollectionDependency` no longer implements the `SelfResolvingDependency` interface that provided `resolve()` and its peers.  Those methods on FileCollectionDependency were marked deprecated for removal in Gradle 8.7.  For reference, `resolve()` returned a `Set<File>`.
`FileCollectionDependency` has had a `getFiles()` method since Gradle 3.3 that returns a `FileCollection`, and that interface implements `Iterable<File>`.  So instead of adding all of a collection to a set we will iterate over the files and individually add them to the set.  This should work for all versions of Gradle 3.3 through 9.0.0.
fixes #8761 
---
<details open>
By opening a pull request you confirm that, …

Fix Gradle 9 FileCollectionDependency in netbeans-gradle-tooling

---

enterprise/web.el/src/org/netbeans/modules/web/el/completion/ELCodeCompletionHandler.java
enterprise/web.el/src/org/netbeans/modules/web/el/completion/ELRawObjectPropertyCompletionItem.java

Before:
After:
---
<details open>
1. [x] Was this PR [correctly …

Add class to EL raw object completion

---

ide/css.prep/src/org/netbeans/modules/css/prep/editor/CPCompletionItem.java
ide/css.prep/src/org/netbeans/modules/css/prep/editor/CPStructureItem.java

Before:
After:
---
<details open>
1. [x] Was this PR [correctly …

SCSS: Improve Navigator and Completion readability with dark theme

---

contrib/j2ee.weblogic9/src/org/netbeans/modules/j2ee/weblogic9/j2ee/Bundle.properties

Fix typo (UNKNOWN_SEVER_LIBRARY_NAME  missing 'R') in weblogic property key that is used with correct spelling in https://github.com/apache/netbeans/blob/b0c7c7c7fa054c1e0be12f7e1af61fc3b441eaec/contrib/j2ee.weblogic9/src/org/netbeans/modules/j2ee/weblogic9/j2ee/WLJ2eePlatformFactory.java#L712
---
<details open>
If you're a …

Fix typo in weblogic property key

---

java/maven/src/org/netbeans/modules/maven/nodes/DependencyNode.java

To reproduce:
1. create a java maven project
2. add jakarta.servlet-api as a dependency, the version is not important
3. from the project tab, expand the "Dependecies" node
4. Right click the jakarta.servlet-api node and click "Download Javadoc"
5. Open the node, open a package and right click a .class file
6. Choose "Show Javadoc" from the context menu
A toast notification will appear, stating the no javadoc was found.
I'm not sure if the way I chose is the right one, but it works: not to reinvent the wheel, this PR uses [JavadocHelper](https://github.com/apache/netbeans/blob/master/java/java.source.base/src/org/netbeans/modules/java/source/JavadocHelper.java) via [SourceUtils](https://github.com/apache/netbeans/blob/master/java/java.source.base/src/org/netbeans/api/java/source/SourceUtil …

Fix "Show Javadoc" menu item for classes inside modular maven dependecies

---

.github/workflows/main.yml

module has now tests since https://github.com/apache/netbeans/pull/8879

add java/gradle.test to CI
