apache/netbeans

defaults/src/org/netbeans/modules/defaults/NetBeans55-SQL-fontsColors.xml

- checked Rat report; unrecognized license headers manually changed

[NETBEANS-54] Module Review defaults

---

db.mysql/src/org/netbeans/modules/db/mysql/resources/create-sample.sql
db.mysql/src/org/netbeans/modules/db/mysql/resources/create-travel.sql
db.mysql/src/org/netbeans/modules/db/mysql/resources/create-vir.sql

- checked Rat report; unrecognized license headers manually changed,
ignored manifest.mf and *.form (see central problems)

[NETBEANS-54] Module Review db.mysql

---

openide.filesystems.nb/test/unit/src/org/netbeans/modules/openide/filesystems/mime-resolver-filechooser.xml
openide.filesystems/src/org/openide/filesystems/doc-files/resolverDocumentation.html
openide.filesystems/test/unit/src/META-INF/upgrade/FileObject.test
openide.filesystems/test/unit/src/META-INF/upgrade/FileUtil.test
openide.filesystems/test/unit/src/org/netbeans/modules/openide/filesystems/declmime/code-fs.xml
openide.filesystems/test/unit/src/org/netbeans/modules/openide/filesystems/declmime/data-fs.xml
openide.filesystems/test/unit/src/org/netbeans/modules/openide/filesystems/declmime/mime-resolver-rule.xml
openide.filesystems/test/unit/src/org/openide/filesystems/data/Attributes.xml
openide.filesystems/test/unit/src/org/openide/filesystems/test-layer-1.xml
openide.filesystems/test/unit/src/org/openide/filesystems/test-layer-2.xml
openide.filesystems/test/unit/src/org/openide/filesystems/test-layer-attribs.xml

* openide.filesystems
* openide.filesystems.nb
* openide.filesystems.compat8 (no change)

[NETBEANS-54] Module Review openide.filesystems.*

---

bugzilla/src/org/netbeans/modules/bugzilla/repository/BugzillaRepository.java

- checked Rat report: update the license header in BugzillaRepository.java

[NETBEANS-54] Module Review bugzilla

---

api.debugger/src/org/netbeans/api/debugger/package.html
api.debugger/src/org/netbeans/spi/debugger/package.html

- checked Rat report: update license header in two package.html

[NETBEANS-54] Module Review api.debugger

---

docker.editor/src/org/netbeans/modules/docker/editor/resources/Dockerfile

- checked Rat report; manually updated license header in Dockerfile

[NETBEANS-54] Module review docker.editor

---

parsing.api/arch.xml

- No external binaries.
- Updated licenses in arch.xml
- No additional problems found.

[NETBEANS-54] Module Review parsing.api

---

j2ee.core.utilities/test/unit/data/JavaApp/nbproject/project.xml
j2ee.eclipselinkmodelgen/src/org/netbeans/modules/j2ee/eclipselinkmodelgen/layer.xml

- checked Rat report, added license header to project.xml, other headers looked ok.  Ignored problems to be resolved centrally.
- skimmed module and did not see any other issues

[NETBEANS-54] Module Review j2ee.core.utilities

---

editor.completion/apichanges.xml
editor.completion/src/org/netbeans/modules/editor/completion/Bundle.properties

- No external libraries.
- Updated licenses in apichanges.xml and a Bundle.properties file as per rat report.
- Tests passing. No additional problems found.

[NETBEANS-54] Module Review editor.completion

---

team.commons/src/org/netbeans/modules/team/commons/resources/package-info.java

- checked Rat report: update the license header in package-info.java. ignore manifest.mf

[NETBEANS-54] Module Review team.commons

---

terminal/README.attributes
terminal/README.close_semantics

- checked Rat report: add the license header in README.*. ignore manifest.mf

[NETBEANS-54] Module Review terminal

---

libs.jsch.agentproxy/external/binaries-list
libs.jsch.agentproxy/external/jsch.agentproxy.core-0.0.7-notice.txt
libs.jsch.agentproxy/external/jsch.agentproxy.pageant-0.0.7-notice.txt
libs.jsch.agentproxy/external/jsch.agentproxy.sshagent-0.0.7-notice.txt
libs.jsch.agentproxy/external/jsch.agentproxy.usocket-jna-0.0.7-notice.txt

- Updated external/binaries-list with maven coordinates.
- Added 4 notice.txt files.
- The rest of the files have proper Apache licenses.

[NETBEANS-54] Module Review libs.jsch.agentproxy

---

nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java

Some modules not only load plain artifacts from maven, but also need
additional parts. In maven the primary artifact can be accompanied by
additional files, that have the same base name, but are seperated by
a classifier (javadoc and sources for example).
What is more it is possible to publish artifacts with different
extensions than "jar".
This commit introduces support for this. The format for maven
coordinates is expanded from:
group:artifact:version
to
group:artifact:version:classifier@extension
Both classifier and extension are optional and the default for extension
is "jar", so this change is compatible.
The format follows the short version of gradle dependencies:
https://docs.gradle.org/4.2.1/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html
Section "External dependencies" …

Add support for specifying classifier and extension for maven binaries

---

j2ee.metadata.model.support/test/unit/src/org/netbeans/modules/j2ee/metadata/model/api/support/annotation/Table.javax

- checked Rat report, added license header on Table.javax which unfortunately also changed whitespace...hope is okay, other files looked ok. Ignored problems to be resolved centrally.
- skimmed module and did not see any other issues

[NETBEANS-54] Module Review j2ee.metadata.model.support

---

libs.lucene/external/binaries-list
libs.lucene/external/lucene-core-3.5.0-notice.txt

- Added lucene notice file from https://github.com/apache/lucene-solr/blob/releases/lucene-solr/3.5.0/lucene/NOTICE.txt
- Added the maven coordinates.
- No other issues found.

[NETBEANS-54] Module Review libs.lucene

---

refactoring.api/src/META-INF/netbeans/translate.names

- checked Rat report: update the license header in translate.names

[NETBEANS-54] Module Review refactoring.api

---

maven.model/test/unit/src/profiles.xml
maven.model/test/unit/src/settings.xml

- license added:
- test case settings.xml and profiles.xml

[NETBEANS-54] Module Review maven.model

---

lib.terminalemulator/ReleaseNotes.ivan.txt
lib.terminalemulator/doc-files/keyboard
lib.terminalemulator/doc-files/sequences
lib.terminalemulator/examples/README
lib.terminalemulator/examples/TermApp/release/nbterm
lib.terminalemulator/examples/TermApp/release/nbterm64
lib.terminalemulator/examples/TermExample/make_filter.awk
lib.terminalemulator/examples/TermTester/nbproject/project.properties
lib.terminalemulator/examples/buildtool/README
lib.terminalemulator/examples/buildtool/buildtool
lib.terminalemulator/examples/lib.richexecution/maintainers.properties
lib.terminalemulator/examples/lib.richexecution/process_start.cat
lib.terminalemulator/examples/telnet/README
lib.terminalemulator/examples/telnet/telnet
lib.terminalemulator/src/org/netbeans/lib/terminalemulator/support/Bundle.properties

- Added Apache license to different files.
- genfiles.properties, build-impl.xml and manifest.mf files to be handled centrally.

[NETBEANS-54] Module Review lib.terminalemulator

---

hibernate/src/org/netbeans/modules/hibernate/hqleditor/ui/Bundle.properties
hibernate/src/org/netbeans/modules/hibernate/resources/HibernateConfig.xml
hibernate/src/org/netbeans/modules/hibernate/resources/HibernateMapping.xml
hibernate/src/org/netbeans/modules/hibernate/resources/HibernateReveng.xml
hibernate/src/org/netbeans/modules/hibernate/resources/HibernateUtil.javax
nbbuild/build.xml

- Update the license header in Bundle.properties (a missing change in #82)
- Exclude template files from rat

[NETBEANS-54] Module Review hibernate

---

nbbuild/build.xml

Exclude module-info.java.template from rat

[NETBEANS-54] Module Review java.j2semodule

---

o.n.bootstrap/launcher/unix/nbexec

NETBEANS-87 - incorrect warning displayed

---

keyring.fallback/nbproject/project.xml

Adding insane dependency for the failing tests in FallbackProviderTest.java and MasterPasswordEncryptionTest.java in keyring.fallback

adding insane dependency for tests in keyring.fallback

---

web.browser.api/src/org/netbeans/modules/web/browser/ui/resources/webpreview.wsmode

Added license header for webpreview.wsmode

[NETBEANS-54] Module Review web.browser.api

---

o.apache.commons.io/external/binaries-list

Added maven coordinate for external resource commons-io-1.4.jar

[NETBEANS-54] Module Review o.apache.commons.io

---

nbbuild/build.xml

Exclude `"queries/test/unit/src/org/netbeans/api/queries/data/*"` from rat

[NETBEANS-54] Module Review queries

---

.travis.yml
README.md

- Add the license header to README.md and .travis.yml
We can add the license header to these. Or should we add these to rat exclusions?

[NETBEANS-54] Module Review root files

---

updatecenters/src/org/netbeans/modules/updatecenters/resources/mf-layer.xml

Update the license header in mf-layer.xml

[NETBEANS-54] Module Review updatecenters

---

autoupdate.services/test/unit/src/org/netbeans/modules/autoupdate/services/NbmsInDownloadedTabTest.java
autoupdate.services/test/unit/src/org/netbeans/modules/autoupdate/services/NewClustersRebootTestDisabled.java
autoupdate.services/test/unit/src/org/netbeans/modules/autoupdate/services/UpdateDisabledModuleTestDisabled.java

Disabled the failing tests as these depend upon the test nbm files removed during Apache code donation

disabled failing tests

---

refactoring.java/test/unit/src/org/netbeans/modules/refactoring/java/test/resources/Class.java.template
refactoring.java/test/unit/src/org/netbeans/modules/refactoring/java/test/resources/license-default.txt

Add license to freemarker files:
- Class.java.template
- license-default.txt

[NETBEANS-54] Module Review refactoring.java

---

o.apache.commons.logging/external/binaries-list
o.apache.commons.logging/external/commons-logging-1.1.1-notice.txt

Added maven coordinate for external resource commons-logging-1.1.1.jar
Hash is changed as per the jar present in maven repository

 [NETBEANS-54] Module Review o.apache.commons.logging

---

editor/demosrc/README
nbbuild/build.xml

- Added test files to rat exclusion list.
- Added a license to a README file.

[NETBEANS-54] Module Review editor (rat exclusions)

---

o.eclipse.equinox.common/external/binaries-list
o.eclipse.equinox.common/nbproject/project.properties
o.eclipse.equinox.common/nbproject/project.xml

- Added maven coordinates for the external binary.

[NETBEANS-54] Module Review o.eclipse.equinox.common

---

o.eclipse.equinox.app/external/binaries-list
o.eclipse.equinox.app/nbproject/project.properties
o.eclipse.equinox.app/nbproject/project.xml

- Added maven coordinates for the external binary.

[NETBEANS-54] Module Review o.eclipse.equinox.app

---

nbbuild/antsrc/org/netbeans/nbbuild/RatReportTask.java

tested manualy seems to work on both operating system

NETBEANS-127 use path to relativize file to root folder instead of regexp

---

apisupport.ant/src/org/netbeans/modules/apisupport/project/ui/wizard/LibraryStartVisualPanel.java
core.startup/src/org/netbeans/core/startup/CoreBridge.java
core.startup/test/unit/src/org/netbeans/core/startup/CoreBridgeTest.java
o.n.bootstrap/src/org/netbeans/StandardModuleData.java
updatecenters/src/org/netbeans/modules/updatecenters/resources/Bundle.properties
updatecenters/src/org/netbeans/modules/updatecenters/resources/mf-layer.xml

As you may know the development in http://hg.netbeans.org repositories continued even after Sat Apr 22 (the day when Apache donation files were synced for the last time). The development wasn't very active, but there was some.
I've made four commits since then. I'd like to backport them to Apache NetBeans repository as they fix real issues found in NetBeans. Please consider accepting my pull request.

Backport of jtulach's fixes made after Apr 22, 2017

---

api.templates/test/unit/src/org/netbeans/modules/templates/utf8.xml
nbbuild/build.xml

- Remove the license header from utf8.xml because unit tests fail.
- Exclude utf8.xml from rat.

[NETBEANS-54] Module Review api.templates

---

.travis.yml

Run verify libs and licenses and rat for platform for pull requests

---

api.intent/manifest.mf
core.startup/src/org/netbeans/core/startup/ModuleLifecycleManager.java
dlight.nativeexecution/src/org/netbeans/modules/nativeexecution/support/Win32APISupport.java
keyring.impl/src/org/netbeans/modules/keyring/gnome/GnomeKeyringLibrary.java
lib.profiler/src/org/netbeans/lib/profiler/heap/ClassDump.java
lib.profiler/src/org/netbeans/lib/profiler/heap/HprofArrayValue.java
lib.profiler/src/org/netbeans/lib/profiler/heap/HprofHeap.java
libs.jna.platform/external/binaries-list
libs.jna.platform/external/jna-platform-4.4.0-license.txt
libs.jna.platform/manifest.mf
libs.jna.platform/nbproject/project.properties
libs.jna.platform/nbproject/project.xml
libs.jna/external/binaries-list
libs.jna/external/jna-4.4.0-license.txt
libs.jna/manifest.mf
libs.jna/nbproject/project.properties
libs.jna/nbproject/project.xml
libs.jna/src/org/netbeans/libs/jna/Installer.java
openide.explorer/src/org/openide/explorer/view/CustomPopupFactory.java
profiler.oql/nbproject/project.xml
profiler.oql/src/org/netbeans/modules/profiler/oql/engine/api/impl/ReachableObjects.java
profiler.oql/src/org/netbeans/modules/profiler/oql/engine/api/impl/Snapshot.java
profiler.oql/src/org/netbeans/modules/profiler/oql/engine/api/impl/hat.js

This is a batch commit of changes for NetBeans 9 done during legal review of sources already being reviewed and donated. These changes were not part of original donation and contain important fixes for Apache NetBeans to work on/with JDK9.

Backport of thurka's fixes made after Apr 22, 2017

---

java.hints/src/org/netbeans/modules/java/hints/bugs/NPECheck.java
java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/NPECheckTest.java

https://netbeans.org/bugzilla/show_bug.cgi?id=271823

Fix 271823 False positive of "Non-null method returns null"

---

java.hints/src/org/netbeans/modules/java/hints/introduce/Flow.java
java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/UnusedAssignmentOrBranchTest.java

Fixes https://netbeans.org/bugzilla/show_bug.cgi?id=271736

Handle implicitly static interface field declarations

---

lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBJavadocMemberEnter.java

Fixes https://netbeans.org/bugzilla/show_bug.cgi?id=271772

Fix NullPointerException at com.sun.source.util.TreePath.<init>

---

java.hints/src/org/netbeans/modules/java/hints/suggestions/CreateSubclass.java
java.hints/test/unit/src/org/netbeans/modules/java/hints/suggestions/CreateSubclassTest.java

- "Create Subclass" would think that the caret was out of range in cases like:
```java
public/*{*/ class Te^st { }
```
(where ^ represents the caret position)
- Don't offer to create a subclass if there is a compile-time error on the class. Fixes part of https://netbeans.org/bugzilla/show_bug.cgi?id=222487

Two fixes for the "Create Subclass" suggestion

---

editor.lib2/src/org/netbeans/api/editor/caret/EditorCaret.java

https://netbeans.org/bugzilla/show_bug.cgi?id=269262
I reported this issue one year ago. Then I attached a patch. Unfortunately, it is not applied yet.
This is a fatal problem for IME users. So, I hope that this is reviewed and merged before NetBeans 9.0 is released.
Thanks.

#269262 - [Regression] The editor screen is not scrolled with a keyboard after Japanese strings are input using IME

---

java.hints/src/org/netbeans/modules/java/hints/introduce/IntroduceFieldFix.java
java.hints/test/unit/src/org/netbeans/modules/java/hints/introduce/IntroduceHintTest.java

Fixes https://netbeans.org/bugzilla/show_bug.cgi?id=270296

Fix ClassCastException: com.sun.tools.javac.tree.JCTree$JCCase cannot be cast to com.sun.source.tree.BlockTree

---

debugger.jpda.ui/nbproject/project.xml
debugger.jpda/src/org/netbeans/modules/debugger/jpda/JPDADebuggerImpl.java
debugger.jpda/src/org/netbeans/modules/debugger/jpda/models/AbstractVariable.java
debugger.jpda/src/org/netbeans/modules/debugger/jpda/models/CallStackFrameImpl.java
debugger.jpda/src/org/netbeans/modules/debugger/jpda/models/ObjectTranslation.java

I've made these commits since Apache donation. I'd like to backport them to Apache NetBeans repository as they fix real issues found in NetBeans. Please consider accepting my pull request.

Backport of mentlicher's changes done after donation.

---

README.md

I've just tried to fix a failing test and found I don't have enough history. Thus I wanted to include @emilianbold's one. However finding the right commit IDs, especially for:
```bash
$ git replace 6daa72c98 32042637
```
isn't particularly easy. Thus I decided to put the How-To into `README.md`, so I can find it next time I need it.

Instructions to connect NetBeans repository with Emilian's conversion

---

java.api.common/manifest.mf
java.api.common/nbproject/project.xml
team.commons/src/org/netbeans/modules/bugtracking/commons/UndoRedoSupport.java
versioning.util/src/org/netbeans/modules/versioning/util/UndoRedoSupport.java

Tho changes:
1. fix class cast exception (see NetBeans bug #257738)
2. add CND module friend to java editor to fix compile error on JDK-9

Integrate CND team changes in platform

---

.gitignore

ant build-nbms generate file under nbbuild/nbms thoose file should I guess not be versionned

ignore build artifacts nbbuild/nbms 

---

libs.git/src/org/netbeans/libs/git/jgit/commands/LogCommand.java

If one needs Apache as well as pre-Apache history, one shall follow the [readme advice](https://github.com/apache/incubator-netbeans/blob/9.0-beta-rc2/README.md) and use `git replace` command to connect the two histories. Then one can use regular command line `git` commands and search both histories.
However the NetBeans IDE was showing just the recent Apache history so far. This PR is trying to fix that (at least in a search history component). Now, if you select a file (I tried `build.xml` in root of the sources) and choose *Git->Show history*, you shall see all the commits as the command line `git log build.xml` would show.
We probably need changes like this in other places as well. I want to encourage everyone to contribute. Not much `(j)git` knowledge is needed (I don't have much …

Support git replace in search history window

---

javadoc/src/org/netbeans/modules/javadoc/highlighting/Highlighting.java

Wrapping version increment in synchronized(this) block is causing deadlocks. I don't think such wrapping is necessary. Enough to use `volatile` for such diagnostic value. Right, Bečoune?
Another possible fix (that I tried) is to _not_ fire changes under the `rootTokenList` lock. However that is a bigger change, possibly changing semantics. Right, Mílo? Thus I decided to go with the safer fix in the Javadoc module.

Deadlock in lexing

---

debugger.jpda/src/org/netbeans/modules/debugger/jpda/actions/StartActionProvider.java

debugging  of RoboVM/MobiVM applications with NetBeans will work again after this change (https://github.com/MobiVM/robovm/issues/254), but we need to wait longer for debugger to successfully start (or print warning if the start fails).

wait longer for debugger to successfully start

---

api.htmlui/src/org/netbeans/modules/htmlui/NbBrowsers.java
api.htmlui/src/org/netbeans/modules/htmlui/css/wizard-win.css

Change fort to tahoma and align radiobuttons with label

CSS changes to improve HTML ui LAF on Windows

---

nbbuild/antsrc/org/netbeans/nbbuild/HgId.java

Changed to search for ".git/HEAD" instead of ".hg/dirstate"

[NETBEANS-451] search for git revision instead of mercurial one.

---

java.hints/src/org/netbeans/modules/java/hints/suggestions/Tiny.java
java.hints/test/unit/src/org/netbeans/modules/java/hints/suggestions/TinyTest.java
java.source.base/apichanges.xml
java.source.base/nbproject/project.properties
java.source.base/src/org/netbeans/api/java/source/TreeUtilities.java

* Split into declaration and assignment issue
* Add review comment
* Add space after var keyword
* Add Jan comments
* Add missing imports
* Add JavaTokenId enum
* Add anonymous method test case
* Add anonymous method test case
* add method in utilities class
* add method in utilities class
* add review request comment
* add review request comment
* Add api in apichanges.xml

Split into declaration and assignment issue for var type (#453)

---

ide.branding/o.n.core/src/org/netbeans/core/Bundle_nb.properties
uihandler/src/org/netbeans/modules/uihandler/UIHandler.java

1. Updated URL in the exception report message - https://issues.apache.org/jira/projects/NETBEANS/issues
2. Review and Report Problem button opens https://issues.apache.org/jira/projects/NETBEANS,
as suggested by Geertjan.

[NETBEANS-491] Fix issue reporting

---

editor/src/org/netbeans/modules/editor/NbEditorToolBar.java
openide.awt/src/org/openide/awt/Actions.java

The Editor already contains support for action hiding feature in popup menus. Let's enhance editor toolbars as well.

Allow action hiding in toolbars

---

maven/src/org/netbeans/modules/maven/queries/ShadePluginDetector.java

Originally posted in [bug #208411](https://netbeans.org/bugzilla/show_bug.cgi?id=208411) but never evaluated: just a minor code simplification.

Silly use of Boolean

---

db/src/org/netbeans/modules/db/util/Bundle.properties
db/src/org/netbeans/modules/db/util/DriverListUtil.java
db/test/unit/src/org/netbeans/modules/db/util/DriverListUtilTest.java

See https://issues.apache.org/jira/browse/NETBEANS-673

[NETBEANS-673] Add support for MariaDB JDBC driver in Add Connection wizard

---

java.completion/nbproject/project.properties
java.completion/test/unit/src/org/netbeans/modules/java/completion/CompletionTestBase.java
java.editor/test/unit/src/org/netbeans/modules/java/editor/completion/CompletionTestBase.java
java.hints/test/unit/src/org/netbeans/modules/java/hints/infrastructure/ErrorHintsTestBase.java
java.j2seproject/nbproject/project.xml
java.j2seproject/src/org/netbeans/modules/java/j2seproject/J2SEActionProvider.java
java.preprocessorbridge/nbproject/project.properties
java.preprocessorbridge/src/org/netbeans/modules/java/preprocessorbridge/spi/CompileOnSaveAction.java
java.source.base/nbproject/project.xml
java.source.base/src/org/netbeans/modules/java/source/indexing/COSSynchronizingIndexer.java
java.source.base/src/org/netbeans/modules/java/source/indexing/CacheAttributesTransaction.java
java.source.base/src/org/netbeans/modules/java/source/indexing/JavaBinaryIndexer.java
java.source.base/src/org/netbeans/modules/java/source/indexing/JavaCustomIndexer.java
java.source.base/src/org/netbeans/modules/java/source/indexing/TransactionContext.java
java.source.base/src/org/netbeans/modules/java/source/usages/BuildArtifactMapperImpl.java
java.source.base/src/org/netbeans/modules/java/source/usages/ClassIndexEventsTransaction.java
java.source.base/test/unit/src/org/netbeans/api/java/source/TestUtilities.java
java.source.base/test/unit/src/org/netbeans/api/java/source/gen/ImportAnalysis2Test.java
java.source.base/test/unit/src/org/netbeans/modules/java/source/ClassIndexTestCase.java
java.source.base/test/unit/src/org/netbeans/modules/java/source/ModuleNamesTest.java
java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/CompileWorkerTestBase.java
java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/JavaBinaryIndexerTest.java
java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/ClasspathInfoTest.java
java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/ModuleOraculumTest.java
java.source.base/test/unit/src/org/netbeans/modules/java/source/usages/PersistentClassIndexScopesTest.java
java.source.base/test/unit/src/org/netbeans/modules/java/source/usages/SourceAnalyzerTest.java
javafx2.editor/nbproject/project.properties
javafx2.editor/test/unit/src/org/netbeans/modules/javafx2/editor/FXMLCompletionTestBase.java

COS Synchronization in J2SEProject is delayed to the end of the initial scan.

COS Synchronization is performed at the end of initial scan.

---

refactoring.api/src/org/netbeans/modules/refactoring/spi/impl/ParametersPanel.form
refactoring.api/src/org/netbeans/modules/refactoring/spi/impl/ParametersPanel.java

Remove synchronization flags in refactoring dialog as discussed here: https://issues.apache.org/jira/browse/NETBEANS-373

[NETBEANS-373] Removing synchronization from refactoring dialog.

---

lib.profiler/src/org/netbeans/lib/profiler/server/ProfilerInterface.java

WeakPairMap has been moved to java.lang from java.lang.reflect in Java 10

Naive fix for Java 10 as WeakPairMap

---

lib.profiler/src/org/netbeans/lib/profiler/results/jdbc/JdbcGraphBuilder.java

This is a small non intrusive fix to the multiple class loader problem described in the issue.

[NETBEANS-620] Profiling SQL queries doesn't work under JDK 10

---

editor.lib2/src/org/netbeans/modules/editor/lib2/highlighting/HighlightingManager.java

See https://issues.apache.org/jira/browse/NETBEANS-713 and the earlier report at https://netbeans.org/bugzilla/show_bug.cgi?id=248664 , and the previous discussion on https://github.com/emilianbold/netbeans-releases/pull/5 (an old pull request from before the incubator-netbeans repo was up and running).

[NETBEANS-713] Have HighlightingManager properly respond to changes in excludes/includes client property.

---

spi.editor.hints/apichanges.xml
spi.editor.hints/nbproject/project.properties
spi.editor.hints/src/org/netbeans/modules/editor/hints/AnnotationHolder.java
spi.editor.hints/src/org/netbeans/modules/editor/hints/FixAction.java
spi.editor.hints/src/org/netbeans/modules/editor/hints/HintsUI.java
spi.editor.hints/src/org/netbeans/modules/editor/hints/ParseErrorAnnotation.java
spi.editor.hints/src/org/netbeans/spi/editor/hints/ErrorDescription.java
spi.editor.hints/src/org/netbeans/spi/editor/hints/ErrorDescriptionFactory.java
spi.editor.hints/test/unit/src/org/netbeans/modules/editor/hints/AnnotationHolderTest.java

Bringing #554 to `release90` branch as well.

Bringing Editor Hints SPI up-to-date in release90 branch

---

maven/src/org/netbeans/modules/maven/customizer/SourcesPanel.java

Prevent java.lang.IllegalArgumentException.
https://issues.apache.org/jira/browse/NETBEANS-785

[NETBEANS-785] java.lang.IllegalArgumentException

---

maven/src/org/netbeans/modules/maven/customizer/SourcesPanel.java

This change is already merged into the master branch(#545). It's related to #495. So we should merge this into the release90 branch as well.

[NETBEANS-785] java.lang.IllegalArgumentException for release90 branch

---

bugzilla.exceptionreporter/src/org/netbeans/modules/bugzilla/exceptionreporter/Bundle.properties
bugzilla.exceptionreporter/src/org/netbeans/modules/bugzilla/exceptionreporter/ReportNBIssueAction.java

This ui currently points to bug infra on netbeans.org and fails on submit task.  We should redirect user to Apache JIRA.

NETBEANS-716 Help-Report Issue should navigate to JIRA link in browser

---

apisupport.ant/src/org/netbeans/modules/apisupport/project/universe/ModuleList.java
nbbuild/antsrc/org/netbeans/nbbuild/GetModuleName.java
nbbuild/antsrc/org/netbeans/nbbuild/InsertModuleAllTargets.java
nbbuild/antsrc/org/netbeans/nbbuild/ModuleListParser.java
nbbuild/antsrc/org/netbeans/nbbuild/ResolveList.java
nbbuild/antsrc/org/netbeans/nbbuild/SetCluster.java
nbbuild/build.xml
nbbuild/default.xml

The infrastructure to allow modules to be in nested clusters. Supports current source structure, as well as the layout of sources as reshuffled in #536.
CC @tzezula , @thurka

Allow modules to be located in cluster.dir/cnb structure

---

apisupport.ant/src/org/netbeans/modules/apisupport/project/universe/ModuleList.java

Backport of #564 for release 9.0.
It is important to make sure we have a (released) IDE that can work with sources from the [netbeans repository](https://github.com/apache/incubator-netbeans/) after #536. To achieve that I suggest to backport this apisupport part of #564 - if we have it the 9.0 version able to open the sources we can apply #536 whenever we want.
As the technical change in #564 has already been review, I am asking more for a blessing from release co-ordinators. Please approve.

Allow 9.0 version recognize nested clusters module layout

---

java.api.common/src/org/netbeans/modules/java/api/common/classpath/ModuleClassPaths.java
java.api.common/test/unit/src/org/netbeans/modules/java/api/common/classpath/ModuleClassPathsTest.java
java.source.base/src/org/netbeans/modules/java/source/indexing/APTUtils.java
java.source.base/src/org/netbeans/modules/java/source/parsing/JavacParser.java
java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/JavacParserTest.java

Backporting #552 by @jlahoda  to 9.0 branch.

Backport of NETBEANS-817

---

apisupport.harness/release/suite.xml

Now creating an intermediate sh file to invoke the executable so resulting apps will sign properly

[NETBEANS-438] Cannot Sign Platform app due to symlink

---

java.hints/src/org/netbeans/modules/java/hints/errors/ConvertInvalidVarToExplicitArrayType.java
java.hints/src/org/netbeans/modules/java/hints/errors/Utilities.java
java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertVarToExplicitType.java
java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/ConvertInvalidVarToExplicitArrayTypeTest.java
java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertVarToExplicitTypeTest.java

This was open issue from #509.

[NETBEANS-774] Disable var hint for anonymous type

---

ide.branding/core.startup/src/org/netbeans/core/startup/Bundle_nb.properties

Updates colors to better fit in with the new branding.

[NETBEANS-956] Fix location of progress bar and progress text on splash screen.

---

java.hints/src/org/netbeans/modules/java/hints/errors/ConvertInvalidVarToExplicitArrayType.java
java.hints/src/org/netbeans/modules/java/hints/errors/Utilities.java
java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertVarToExplicitType.java
java.hints/src/org/netbeans/modules/java/hints/resources/layer.xml
java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/ConvertInvalidVarToExplicitArrayTypeTest.java
java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertVarToExplicitTypeTest.java
java.lexer/src/org/netbeans/lib/java/lexer/JavaLexer.java
java.lexer/test/unit/src/org/netbeans/lib/java/lexer/JavaLexerBatchTest.java
java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
java.source.base/test/unit/src/org/netbeans/api/java/source/SourceUtilsTestUtil.java
java.source.base/test/unit/src/org/netbeans/api/java/source/gen/InvalidVarToExplicitArrayConversionTest.java
java.source.base/test/unit/src/org/netbeans/api/java/source/gen/VarTypeTest.java
java.source.base/test/unit/src/org/netbeans/modules/java/source/save/FormatingTest.java

Below merged PRs of apache:master were cherry-picked for merging into release90 branch
[NETBEANS-777] : https://github.com/apache/incubator-netbeans/pull/551
[NETBEANS-481] : https://github.com/apache/incubator-netbeans/pull/519
[NETBEANS-774] : https://github.com/apache/incubator-netbeans/pull/563
[NETBEANS-778] : https://github.com/apache/incubator-netbeans/pull/568

Backport/cherry-pick LVTI fixes for [NETBEANS-777],[NETBEANS-481],[NETBEANS-774],[NETBEANS-778] to release90 Branch

---

nbbuild/licenses/Apache-2.0-ant
nbbuild/licenses/Apache-2.0-smack
o.apache.xml.resolver/build.xml

@emilianbold this should be the last batch of changes needed for
binary dependencies. Could you please have a look?

Update licenses + notices (4)

---

openide.loaders/src/org/openide/loaders/TemplateWizard2.java
openide.loaders/test/unit/src/org/openide/loaders/TemplateWizardTest.java

I've added a simple mechanism that attempts to track original DataObject using relative files. If the tracking breaks, the java.io.File is converted back to DataFolder when necessary.

[NETBEANS-975] Wizard properly reports items created on configuration FS

---

refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/MoveClassTransformer.java

Couldn't reproduce this issue with MoveClassTest, hence no test.

NETBEANS-892: Fix updation of unrelated files during refactor

---

o.n.core/src/org/netbeans/core/ui/Bundle.properties

Updating About box text on release90 with Incubation message.

[NETBEANS-851] Updating About box text on release90 with Incubation message.

---

javascript2.editor/src/org/netbeans/modules/javascript2/editor/parser/SanitizingParser.java
javascript2.editor/test/unit/data/testfiles/formatter/issue268488/bower.json
javascript2.editor/test/unit/data/testfiles/formatter/issue268488/bower.json.formatted
javascript2.editor/test/unit/data/testfiles/formatter/issue268488/package.json
javascript2.editor/test/unit/data/testfiles/formatter/issue268488/package.json.formatted
javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/formatter/Issue268488Test.java

Merging  fix for https://netbeans.org/bugzilla/show_bug.cgi?id=268488 from https://hg.netbeans.org/jet-main into apache:2ndDonation branch

donation2_merge: #268488 : Fixing formatting for bower.json and package.json files

---

javascript2.editor/src/org/netbeans/modules/javascript2/editor/JsStructureScanner.java
javascript2.editor/test/unit/data/testfiles/coloring/czechChars.js.folds
javascript2.editor/test/unit/data/testfiles/structure/issue240529.js
javascript2.editor/test/unit/data/testfiles/structure/issue240529.js.folds
javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/JsStructureScannerTest.java

Merging fix for https://netbeans.org/bugzilla/show_bug.cgi?id=240529 from https://hg.netbeans.org/jet-main into apache:2ndDonation branch

donation2_merge:#240529: Fixing folding of empty {}

---

javascript2.editor/src/org/netbeans/modules/javascript2/editor/JsTypedBreakInterceptor.java
javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/JsTypedBreakInterceptorTest.java

Merging fix for https://netbeans.org/bugzilla/show_bug.cgi?id=215318 from https://hg.netbeans.org/jet-main into apache:2ndDonation branch

donation2_merge:#215318: Fixing the auto comment population

---

welcome/src/org/netbeans/modules/welcome/resources/community.url
welcome/src/org/netbeans/modules/welcome/resources/whatsnew.url

https://issues.apache.org/jira/browse/NETBEANS-1028

[NETBEANS-1028] Replace old URLs on Start Page

---

lexer.nbbridge/nbproject/project.properties
lexer.nbbridge/src/org/netbeans/modules/lexer/nbbridge/MimeLookupLanguageProvider.java

This fix was merged after branching for Donation 2 happened.

#268649-NPE at JsStructureScanner.folds while opening .js file

---

java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertToVarHint.java
java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertVarToExplicitType.java

Replace the repetitive code for error check in Hint with TreeUtilities.hasError() API method
Apache Jira path: https://issues.apache.org/jira/browse/NETBEANS-1108

[NETBEANS-1108] Replace the repetitive code for error check in Hint module

---

php.atoum/licenseinfo.xml
php.atoum/src/org/netbeans/modules/php/atoum/ui/customizer/Bundle.properties
php.atoum/test/unit/src/org/netbeans/modules/php/atoum/coverage/CloverLogParserTest.java

- Change the license header of Bundle.properties
- Add licenseinfo.xml
- Fix a unit test because the license headers are changed, then the line counts are changed

[NETBEANS-1074] Module Review php.atoum

---

php.codeception/src/org/netbeans/modules/php/codeception/ui/Bundle.properties

[NETBEANS-1074] Module Review php.codeception

---

php.doctrine2/licenseinfo.xml
php.doctrine2/src/org/netbeans/modules/php/doctrine2/ui/wizards/Bundle.properties
php.doctrine2/test/unit/src/org/netbeans/modules/php/doctrine2/annotations/orm/parser/DiscriminatorColumnLineParserTest.java

- Change the license headers
- Add the licenseinfo.xml

[NETBEANS-1074] Module Review php.doctrine2

---

php.nette.tester/licenseinfo.xml

[NETBEANS-1074] Module Review php.nette.tester

---

php.latte/licenseinfo.xml

[NETBEANS-1074] Module Review php.latte

---

refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/MoveMembersTransformer.java
refactoring.java/test/unit/src/org/netbeans/modules/refactoring/java/test/MoveBase.java
refactoring.java/test/unit/src/org/netbeans/modules/refactoring/java/test/MoveMethodTest.java

[NETBEANS-1043]:Fixed updation of method-reference upon refactor move of method

---

php.samples/licence.txt
php.samples/licenseinfo.xml
php.samples/samples_src/Calculator-Codeception/nbproject/private/private.xml
php.samples/samples_src/Calculator-PHPUnit/nbproject/private/private.xml
php.samples/samples_src/Calculator-atoum/nbproject/private/private.xml
php.samples/samples_src/TodoList/config/config.ini
php.samples/samples_src/TodoList/db/sqlite.sql

- Add the license headers to private.xml files
- Remove .keep
- Change the license headers of sqlite.sql and license.txt
- Add json files to the licenseinfo.xml because the json does not support comments

[NETBEANS-1074] Module Review php.samples

---

php.smarty/licenseinfo.xml
php.smarty/src/org/netbeans/modules/php/smarty/resources/Bundle.properties

- Change the license header of Bundle.properties
- Add template files to the licenseinfo.xml

[NETBEANS-1074] Module Review php.smarty

---

php.twig/licenseinfo.xml
php.twig/src/org/netbeans/modules/php/twig/resources/Bundle.properties

- Change the license header of Bundle.properties
- Add the licenseinfo.xml

[NETBEANS-1074] Module Review php.twig

---

selenium2.php/licenseinfo.xml

[NETBEANS-1074] Module Review selenium2.php

---

spellchecker.bindings.php/nbproject/project.properties

[NETBEANS-1074] Module Review spellchecker.bindings.php

---

j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/customizer/CustomizerSources.java
j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/resources/application-client-1.4.xml
j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/resources/application-client-5.xml
j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/resources/application-client-6.xml
j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/resources/application-client-7.xml

no external library
checked Rat report: changed license headers of five file
skimmed through the module, did not notice additional problems

[NETBEANS-1074] Module Review j2ee.clientproject

---

hibernateweb/src/org/netbeans/modules/hibernateweb/framework/HibernateConfigurationPanel.form

no external library
checked Rat report: change license headers of one file
skimmed through the module, did not notice additional problems

[NETBEANS-1074] Module Review hibernateweb

---

j2ee.clientproject/licenseinfo.xml
j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/resources/application-client-1.4.xml
j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/resources/application-client-5.xml
j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/resources/application-client-6.xml
j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/resources/application-client-7.xml

As adviced by @junichi11 
https://github.com/apache/incubator-netbeans/pull/691#issuecomment-413210522
Removed License headers from templates and added licenseinfo.xml

[NETBEANS-1074] Module Review j2ee.clientproject - fix pr691

---

j2ee.common/licenseinfo.xml

no external library
checked Rat report: 
added 18 template files to licenseinfo.xml
skimmed through the module, did not notice additional problems

[NETBEANS-1074] Module Review j2ee.common

---

web.client.samples/licenseinfo.xml

[NETBEANS-1074] Module Review web.client.samples

---

languages.neon/licenseinfo.xml
php.latte/licenseinfo.xml
php.smarty/licenseinfo.xml
php.twig/licenseinfo.xml

- Change the comment type for example files to GUI_USABILITY

[NETBEANS-1074] Fix licenseinfo.xml files

---

php.phpunit/licenseinfo.xml
php.phpunit/src/org/netbeans/modules/php/phpunit/ui/Bundle.properties

- Change the license headers of Bundle.properties and PHPUnitConfiguration.xml
- Add PHPUnitBootstrap.php to the licenseinfo.xml

[NETBEANS-1074] Module Review php.phpunit

---

php.phing/src/org/netbeans/modules/php/phing/ui/options/Bundle.properties
php.phing/src/org/netbeans/modules/php/phing/ui/resources/build.xml

- Change the license headers of Bundle.properties and build.xml

[NETBEANS-1074] Module Review php.phing

---

j2ee.ejbjarproject/licenseinfo.xml

ejb-jar-2.1.xml file is referenced by EjbJarProjectGenerator.java via layer.xml
So, assuming the files being used as templates, added to licenseinfo.xml

[NETBEANS-1074] Module Review j2ee.ejbjarproject

---

j2ee.api.ejbmodule/licenseinfo.xml

added four graphic files to licenseinfo.xml

[NETBEANS-1074] Module Review j2ee.api.ejbmodule

---

javaee.project/licenseinfo.xml

added eight graphic files to licenseinfo.xml

[NETBEANS-1074] Module Review javaee.project

---

j2ee.genericserver/licenseinfo.xml

added one gif to licenseinfo.xml

[NETBEANS-1074] Module Review j2ee.genericserver

---

groovy.kit/release/VERSION.txt

- Add the license header to VERSION.txt

[NETBEANS-1074] Module Review groovy.kit

---

groovy.gsp/licenseinfo.xml

- Change the license header of GspTempalte.gsp
- GspExample is an example file, so add it to the licenseinfo.xml

[NETBEANS-1074] Module Review groovy.gsp

---

javascript.gulp/licenseinfo.xml

- gulpfile.js is a template file

[NETBEANS-1074] Module Review javascript.gulp

---

javascript.grunt/licenseinfo.xml

- Gruntfile.js is a template file

[NETBEANS-1074] Module Review javascript.grunt

---

javascript.bower/licenseinfo.xml

- Add .bowerrc and bower.json to licenseinfo.xml because they don't support comments

[NETBEANS-1074] Module Review javascript.bower

---

groovy.support/licenseinfo.xml
groovy.support/src/META-INF.debugger.BreakpointsView/org.netbeans.spi.viewmodel.NodeActionsProviderFilter
groovy.support/src/META-INF.debugger/org.netbeans.api.debugger.LazyDebuggerManagerListener
groovy.support/src/META-INF.debugger/org.netbeans.modules.groovy.support.debug.GroovyBreakpointAnnotationListener
groovy.support/src/org/netbeans/modules/groovy/support/options/Bundle.properties
groovy.support/src/org/netbeans/modules/groovy/support/resources/GroovyClass.groovy
groovy.support/src/org/netbeans/modules/groovy/support/resources/GroovyJUnit3Test.groovy
groovy.support/src/org/netbeans/modules/groovy/support/resources/GroovyJUnitTest.groovy
groovy.support/src/org/netbeans/modules/groovy/support/resources/GroovyScript.groovy

- Change the license headers of template files and Bundle.properties
- Add the license headers to META-INF.debugger* files

[NETBEANS-1074] Module Review groovy.support

---

groovy.samples/sample_src/GroovyJavaDemo/src/demo/DisplayProvider.groovy
groovy.samples/sample_src/NBProjectGenerators/src/generators/NetBeansModule.groovy
groovy.samples/sample_src/NBProjectGenerators/src/generators/NetBeansPlatform.groovy
nbbuild/rat-exclusions.txt

- Add the license headers to .groovy files
- Exclude groovy-build.xml from rat

[NETBEANS-1074] Module Review groovy.samples

---

libs.javacup/external/binaries-list
nbbuild/licenses/JavaCUP

- Add the license header to binaries-list
java-cup-11a.jar(JavaCUP-LICENSE)
http://www2.cs.tum.edu/projects/cup/licence.php
Is this license OK?

[NETBEANS-1074] Module Review libs.javacup

---

javascript2.model/src/org/netbeans/modules/javascript2/model/JsWithObjectImpl.java
javascript2.model/test/unit/data/testfiles/model/anonymousFunction.js.model

Relicensed leftover standard old NB license to Apache2. Fixed tests.

[NETBEANS-1074] Module Review javascript2.model

---

maven.jaxws/licenseinfo.xml
maven.jaxws/src/org/netbeans/modules/maven/jaxws/nodes/ServiceNode.java
maven.jaxws/src/org/netbeans/modules/maven/jaxws/wizards/Bundle.properties

- Changed licenses in two files
- Added licenseinfo.xml for graphic files

[NETBEANS-1074] maven.jaxws Module Review 2nd Donation

---

javascript2.react/src/org/netbeans/modules/javascript2/react/resources/jsxtemplate.jsx

[NETBEANS-1074] Module Review javascript2.react

---

web.jsf.icefaces/licenseinfo.xml

added 1 template file to licenseinfo.xml

[NETBEANS-1074] Module Review web.jsf.icefaces

---

javascript2.knockout/licenseinfo.xml
nbbuild/rat-exclusions.txt

The model files do not seem to support comments, do not contain any license; rat exclusion added. Filed [NETBEANS-1155](https://issues.apache.org/jira/browse/NETBEANS-1155)

[NETBEANS-1074] Module Review javascript2.knockout

---

javascript2.jquery/.gitignore
javascript2.jquery/build.xml
javascript2.jquery/external/binaries-list
javascript2.jquery/external/jquery-api-1.10-license.txt
nbbuild/licenses/MIT-jquery

Just added license to external list to satisfy rat.

[NETBEANS-1074] Module Review javascript2.jquery

---

web.freeform/licenseinfo.xml

No external library
Checked Rat report: everything has been relicensed to Apache
Add licenseinfor file with media and template

[NETBEANS-1074] Module Review web.freeform

---

web.debug/licenseinfo.xml

No external library
Checked Rat report: everything has been relicensed to Apache
Add licenseinfor file with media

[NETBEANS-1074] Module Review web.debug

---

javascript.jstestdriver/licenseinfo.xml

- Change the license header of jsTestDriver.conf
- Add the licenseinfo.xml

[NETBEANS-1074] Module Review javascript.jstestdriver

---

web.jsf.richfaces/licenseinfo.xml

added 1 template file to licenseinfo.xml

[NETBEANS-1074] Module Review web.jsf.richfaces

---

web.kit/release/VERSION.txt

added license headers to 1 files

[NETBEANS-1074] Module Review web.kit

---

web.clientproject/licenseinfo.xml

added 14 graphic files to licenseinfo.xml

[NETBEANS-1074] Module Review web.clientproject

---

websvc.saas.codegen.j2ee/licenseinfo.xml
websvc.saas.codegen.j2ee/src/org/netbeans/modules/websvc/saas/codegen/j2ee/Bundle.properties

changed license headers in 1 files
added 5 template file to licenseinfo.xml

[NETBEANS-1074] Module Review websvc.saas.codegen.j2ee

---

websocket/src/org/netbeans/modules/websocket/Bundle.properties
websocket/src/org/netbeans/modules/websocket/editor/Bundle.properties
websocket/src/org/netbeans/modules/websocket/wizard/Bundle.properties

changed license headers in 3 files

[NETBEANS-1074] Module Review websocket

---

web.project/licenseinfo.xml

added 4 graphic files to licenseinfo.xml

[NETBEANS-1074] Module Review web.project

---

web.jsf.navigation/.project
web.jsf.navigation/installinks
web.jsf.navigation/src/org/netbeans/modules/web/jsf/navigation/graph/actions/Bundle.properties
web.jsf.navigation/test/unit/src/org/netbeans/modules/web/jsf/navigation/TestJSFApp/web/welcomeJSF.jsp

added license headers to 2 files
changed license headers in 2 files

[NETBEANS-1074] Module Review web.jsf.navigation

---

web.webkit.tooling/licenseinfo.xml

added 1 graphic file to licenseinfo.xml

[NETBEANS-1074] Module Review web.webkit.tooling

---

web.inspect/licenseinfo.xml

added 8 graphic files to licenseinfo.xml

[NETBEANS-1074] Module Review web.inspect

---

web.clientproject.api/licenseinfo.xml

added 12 graphic files to licenseinfo.xml

[NETBEANS-1074] Module Review web.clientproject.api

---

web.core/external/binaries-list
web.core/licenseinfo.xml
web.core/src/org/netbeans/modules/web/core/resources/web-jsptaglibrary_1_1.dtd
web.core/src/org/netbeans/modules/web/core/resources/web-jsptaglibrary_1_2.dtd

Checked the rat-report.txt file, are these files ok with Apache License :
glassfish-license.txt
w3c-license.txt
Add the license header for binaries-list
Could not find maven replacement for the binaries-list (several DTD glassfish files)
Add the licenseinfo.xml

[NETBEANS-1074] Module Review web.core

---

tomcat5/licenseinfo.xml
tomcat5/src/org/netbeans/modules/tomcat5/resources/tomcat5_context.dtd
tomcat5/src/org/netbeans/modules/tomcat5/resources/tomcat5_server.dtd

added license headers to 3 dtd files
added 4 graphic files to licenseinfo.xml

[NETBEANS-1074] Module Review tomcat5

---

libs.nashorn/external/binaries-list
libs.nashorn/external/com.oracle.js.parser-ba7a8bc42268-license.txt
libs.nashorn/nbproject/project.properties
libs.nashorn/nbproject/project.xml

Just added license to binaries-list

[NETBEANS-1074] Module Review libs.nashorn

---

javascript.nodejs/licenseinfo.xml
javascript.nodejs/samples_src/MessagesAngular/nbproject/private/private.properties
javascript.nodejs/samples_src/MessagesExpress/nbproject/private/private.properties
javascript.nodejs/samples_src/MessagesExpress/views/error.jade
javascript.nodejs/samples_src/MessagesExpress/views/index.jade
javascript.nodejs/samples_src/MessagesExpress/views/layout.jade
javascript.nodejs/samples_src/MessagesKnockout/nbproject/private/private.properties
javascript.nodejs/src/org/netbeans/modules/javascript/nodejs/ui/Bundle.properties

- Change the license headers of *.jade files and Bundle.properties
- Add the license headers to private.properties
- json files don't support comments, so add them to the licenseinfo.xml

[NETBEANS-1074] Module Review javascript.nodejs

---

websvc.design/licenseinfo.xml

added 13 graphic files to licenseinfo.xml

[NETBEANS-1074]Module Review websvc.design

---

spring.webmvc/licenseinfo.xml

added 8 template files to licenseinfo.xml

[NETBEANS-1074]Module Review spring.webmvc

---

j2ee.ejbcore/l10n.list
j2ee.ejbcore/licenseinfo.xml
j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ui/EJBPreferences.java

- Added license to l10n.list
- Changed license of EJBPreferences.java
- Added graphic files and template files to licenseinfo.xml

[NETBEANS-1074] Module Review j2ee.ejbcore

---

j2ee.earproject/l10n.list
j2ee.earproject/licenseinfo.xml

- Added license to l10n.list
- Added licenseinfo.xml for graphic files

[NETBEANS-1074] Module Review j2ee.earproject

---

websvc.restapi/licenseinfo.xml
websvc.restapi/src/org/netbeans/modules/websvc/rest/resources/Bundle.properties
websvc.restapi/src/org/netbeans/modules/websvc/rest/spi/Bundle.properties
websvc.restapi/src/org/netbeans/modules/websvc/rest/spi/resources/test-resbeans.html
websvc.restapi/src/org/netbeans/modules/websvc/rest/spi/resources/test-services.html

changed license headers in 2 files
added license headers to 2 files
added 25 graphic files to licenseinfo.xml

[NETBEANS-1074] Module Review websvc.restapi

---

languages.ini/licenseinfo.xml

- Add EmptyINI.ini to the licenseinfo.xml because it is a template file
- Add IniExample.ini to the licenseinfo.xml because it is an example file
- Add skeleton.netbeans to the licenseinfo.xml because it does not support comments

[NETBEANS-1074] Module Review languages.ini

---

cordova.platforms.android/licenseinfo.xml

added 4 graphic file to licenseinfo.xml

[NETBEANS-1074] Module Review cordova.platforms.android

---

selenium2.webclient/src/org/netbeans/modules/selenium2/webclient/ui/customizer/Bundle.properties

Changed license header of src/org/netbeans/modules/selenium2/webclient/ui/customizer/Bundle.properties

[NETBEANS-1074] Module Review selenium2.webclient

---

selenium2.webclient.mocha/licenseinfo.xml

Added src/org/netbeans/modules/selenium2/webclient/mocha/wizard/SeleneseMochaTest.js.template to licenseinfo.xml file

[NETBEANS-1074] Module Review selenium2.webclient.mocha

---

cordova/CordovaMapsSample/www/index.html
cordova/CordovaMapsSample/www/readme.md
cordova/cordovaprojectupdate/test/org/netbeans/modules/cordova/updatetask/AndroidManifest.xml
cordova/cordovaprojectupdate/test/org/netbeans/modules/cordova/updatetask/Info-plist.xml
cordova/cordovaprojectupdate/test/org/netbeans/modules/cordova/updatetask/config.xml
cordova/cordovaprojectupdate/test/org/netbeans/modules/cordova/updatetask/dev_config.xml
cordova/licenseinfo.xml
cordova/src/org/netbeans/modules/cordova/empty.properties
cordova/src/org/netbeans/modules/cordova/mapplugins.properties
cordova/src/org/netbeans/modules/cordova/plugins.properties

- Added/Changed license to/of 9 files
- Added graphic files to licenseinfo.xml

[NETBEANS-1074] Module Review cordova

---

j2ee.ddloaders/licenseinfo.xml
j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/multiview/ui/AddEjbReferenceForm.form
j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/web/multiview/Bundle.properties
j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/web/resources/xml.xsd

- Changed license of a file
- Added license to a file
- Added graphic files to licenseinfo.xml
The Rat Report mentioned a .form file in this module, but there are multiple .form files across multiple modules without licenses. Also, it is mentioned [here](https://cwiki.apache.org/confluence/display/NETBEANS/List+of+Modules+to+Review) that .form license is one of the problems to be solved centrally. So, I have not added license to the .form file. Please correct me if I am wrong.

[NETBEANS-1074] Module Review j2ee.ddloaders

---

glassfish.tooling/licenseinfo.xml
glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/GlassFish.properties-dist
glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/GlassFishHttp.properties-dist
glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/GlassFishRest.properties-dist
glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/Java.properties-dist
glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/admin/response/list-jdbc-resources.xml
glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/admin/response/version.xml
glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersionTest.java

- No external libraries
- Checked Rat report:  everything now licensed to Apache
- Skimmed module...no additional problems found

[NETBEANS-1074] Module review glassfish.tooling

---

.gitignore

Correcting .gitignore paths for moved modules

[NETBEANS-1175] Move websvccommon cluster - task 5

---

html.ojet/src/org/netbeans/modules/html/ojet/ui/resources/EmptyJETModule-html
html.ojet/src/org/netbeans/modules/html/ojet/ui/resources/EmptyJETModule-js
html.ojet/src/org/netbeans/modules/html/ojet/ui/resources/KnockoutJETModule-html
html.ojet/src/org/netbeans/modules/html/ojet/ui/resources/KnockoutJETModule-js

4 template files escaped automatic relicensing from original SUN/Oracle.

Module Review html.ojet

---

libs.amazon/external/binaries-list
websvc.metro.lib/external/binaries-list
websvc.metro.lib/external/metro-2.0-license.txt
websvc.metro.lib/manifest.mf
websvc.metro.lib/nbproject/project.properties
websvc.metro.lib/src/org/netbeans/modules/websvc/metro/lib/metro.xml

[NETBEANS-1074] module review websvc.metro.lib

---

web.jsf12/external/binaries-list
web.jsf12/external/jsf-api-1.2_05-license.txt
web.jsf12/nbproject/project.properties
web.jsf12/nbproject/project.xml

Add license in binary-list
update license in jsf-1.2-license.txt

[NETBEANS-1074] Module Review web.jsf12

---

php/php.editor/build.xml

- Comment out or remove unused code
- Remove trailing spaces

Fix generated lexers of php.editor automatically via ant task

---

java/java.hints/test/unit/src/org/netbeans/modules/java/hints/suggestions/Bundle_test.properties
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/suggestions/LambdaTest.java

Update the test cases for var parameter list in lambda expression.

[NETBEANS-860] Hints:Test cases for var lambda support

---

apisupport/apisupport.ant/test/unit/src/org/netbeans/modules/apisupport/project/ProjectXMLManagerTest.java
apisupport/apisupport.ant/test/unit/src/org/netbeans/modules/apisupport/project/universe/TestModuleDependencyTest.java
j2ee.ant/nbproject/project.xml
j2eeapis/external/binaries-list
j2eeapis/external/deployment-api-1.2-rev-1-license.txt
j2eeapis/nbproject/project.properties
j2eeapis/nbproject/project.xml

Had replace external resource : jsr88javax.jar with deployment-api-1.2-rev-1.jar . Exact version not found , had used nearest available version.
link : https://mvnrepository.com/artifact/javax.enterprise.deploy/deployment-api/1.2-rev-1

[NETBEANS-1074] Module Review j2eeapis

---

java/ant.browsetask/build.xml
java/ant.browsetask/nbproject/project.properties
websvccommon/websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/WadlSaas.java
websvccommon/websvc.saas.api/src/org/netbeans/modules/websvc/saas/model/WadlSaasMethod.java

towards jdk 11 compilation
remove not needed javaee package import
bump source version to 1.6

jdk11 build minor fix

---

java/java.hints/manifest.mf
java/java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertToVarHint.java
java/java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertVarToExplicitType.java
java/java.hints/src/org/netbeans/modules/java/hints/suggestions/ExpandEnhancedForLoop.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertToVarHintTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertVarToExplicitTypeTest.java
java/java.source.base/src/org/netbeans/api/java/source/TreeUtilities.java

In cases of enhanced for loops : 
`for (String s : stringArray) {
// Nothing
}`
Hint to change "String" s to "var" and vice versa in appropriate cases would be available.
The hints are available for primitive types as well.

[NETBEANS-1075]-Adding var hints for enhanced-for-loop

---

README.md
nbbuild/cluster.properties

https://issues.apache.org/jira/browse/NETBEANS-1233
- Include php into the release
- Update README.md

[NETBEANS-1233] cluster.properties updates for PHP cluster

---

java/java.openjdk.project/build.xml
java/java.openjdk.project/nbproject/project.xml
java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/ActionProviderImpl.java
java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/ClassPathProviderImpl.java
java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/ModuleDescription.java
java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/SourceLevelQueryImpl.java
java/java.openjdk.project/test/unit/src/org/netbeans/modules/java/openjdk/project/SourceLevelQueryImplTest.java
java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBAttr.java

(If approved, I'll merged myself; please don't squash.)

Various improvements to make the OpenJDK project work better.

---

java/java.source.base/src/org/netbeans/modules/java/source/ElementUtils.java

Navigation is broken as the Interface class Element is not getting resolved as it is getting found in unnamed module and also in the named module. Ignoring the result found in unnamed module.

[NETBEANS-263] navigate to impl icon not shown for interface

---

ide/editor.lib/src/org/netbeans/editor/PopupManager.java
ide/editor.lib/src/org/netbeans/editor/ext/ToolTipSupport.java

See https://issues.apache.org/jira/browse/NETBEANS-403

[NETBEANS-403] Avoid scrolling to end of file if End is pressed while popup is open.

---

nbbuild/build.xml

Current java version: 11.0.1 
The current pattern matches 1**1.0.1**

Fix the invalid java version pattern

---

php/php.symfony2/src/org/netbeans/modules/php/symfony2/SymfonyPhpModuleExtender.java
php/php.symfony2/src/org/netbeans/modules/php/symfony2/ui/wizards/Bundle.properties
php/php.symfony2/src/org/netbeans/modules/php/symfony2/ui/wizards/NewProjectConfigurationPanel.form
php/php.symfony2/src/org/netbeans/modules/php/symfony2/ui/wizards/NewProjectConfigurationPanel.java

https://issues.apache.org/jira/browse/NETBEANS-1443
- Always install the latest LTS version because We can't install the latest stable version using the installer any longer
- Remove the LTS Checkbox of NewProjectConfigurationPanel

[NETBEANS-1443] Error creating Symfony project

---

php/php.code.analysis/src/org/netbeans/modules/php/analysis/PHPStanAnalyzerImpl.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/PHPStanParams.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/PHPStan.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptions.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptionsValidator.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/ValidatorPHPStanParameter.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/PHPStanLevelListCellRenderer.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/Bundle.properties
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/PHPStanCustomizerPanel.form
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/PHPStanCustomizerPanel.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/Bundle.properties
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/PHPStanOptionsPanel.form
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/PHPStanOptionsPanel.java

Cherry-picking PHPStan changes

---

php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/CodeSnifferCustomizerPanel.java

https://issues.apache.org/jira/browse/NETBEANS-1550
- Clear errors when the enabled checkbox is unchecked

[NETBEANS-1550] Cannot set custom configuration of the inspection feature

---

php/php.code.analysis/src/org/netbeans/modules/php/analysis/parsers/PHPStanReportParser.java
php/php.code.analysis/test/unit/data/phpstan/phpstan-log-with-other-output.xml
php/php.code.analysis/test/unit/data/phpstan/phpstan-log.xml

https://issues.apache.org/jira/browse/NETBEANS-1507
My results were not normal because probably, my configuration was bad, sorry.
- Add a log
- Handle current file path properly (File names are relative paths from the chosen directory)

[NETBEANS-1507] PHPStan empty inspector Window

---

php/php.code.analysis/src/org/netbeans/modules/php/analysis/PHPStanAnalyzerImpl.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/PHPStan.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptions.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/PHPStanLevelListCellRenderer.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/PHPStanCustomizerPanel.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/PHPStanOptionsPanel.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/util/AnalysisUtils.java

- Add "max" to the level combo box because users need not change it even if new level values added in the future
- Introduce constants for min and max levels

Improve PHPStan level

---

webcommon/cordova/src/org/netbeans/modules/cordova/CordovaPerformer.java
webcommon/cordova/src/org/netbeans/modules/cordova/options/MobilePlatformsPanel.java
webcommon/cordova/src/org/netbeans/modules/cordova/project/CordovaPanel.java
webcommon/cordova/src/org/netbeans/modules/cordova/wizard/CordovaProjectExtender.java
webcommon/cordova/test/unit/src/org/netbeans/modules/web/clientproject/cordova/AndroidPlatformTest.java

[NETBEANS-1342] Hide the panel for iOS in the Mobile Platforms Options

---

javafx/javafx2.samples/src/org/netbeans/modules/javafx2/samples/Bundle.properties

https://issues.apache.org/jira/browse/NETBEANS-1343

[NETBEANS-1343] Message about JavaFX in JDK 11+

---

webcommon/javascript2.editor/test/unit/data/testfiles/coloring/issue233298_3.js
webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/navigation/GoToDeclarationTest.java
webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/api/ModelUtils.java

Added checks to prevent StackOverflowError on opening some .js files.

[NETBEANS-1438] : stackoverflowerror opening .js files

---

php/php.editor/src/org/netbeans/modules/php/editor/model/impl/ModelVisitor.java
php/php.editor/test/unit/data/testfiles/completion/lib/_base/varTypeComment.php.testVarTypeCommentVariable02.completion
php/php.editor/test/unit/data/testfiles/completion/lib/nb1576/nb1576.php
php/php.editor/test/unit/data/testfiles/completion/lib/nb1576/nb1576.php.testNb1576_01.completion
php/php.editor/test/unit/data/testfiles/completion/lib/nb1576/nb1576.php.testNb1576_02.completion
php/php.editor/test/unit/data/testfiles/completion/lib/nb1576/nb1576.php.testNb1576_03.completion
php/php.editor/test/unit/data/testfiles/completion/lib/nb1576/nb1576.php.testNb1576_04.completion
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionNb1576Test.java

https://issues.apache.org/jira/browse/NETBEANS-1576
- Add vardoc info instead of current assignment info

[NETBEANS-1576] PHP autocompletion partially broken

---

nb/updatecenters/src/org/netbeans/modules/updatecenters/resources/Bundle.properties

So that builds from master see modules in the Plugin Portal for NB 10.0.

Using Plugin Portal for NetBeans 10.0 in master.

---

enterprise/j2ee.kit/test/qa-functional/src/org/netbeans/test/j2ee/Bundle.properties

- Added license header to Bundle.properties
- Scanned remaining files and headers looked good
- Ignored test files as to not change headers...tests fail without adding any license headers to test files so left alone

[NETBEANS-1074] Review j2ee.kit

---

ide/refactoring.api/src/org/netbeans/modules/refactoring/spi/impl/RefactoringPanel.java

https://issues.apache.org/jira/browse/NETBEANS-1729
Refactoring... dialog does not close sometimes.
- Call dispose()

[NETBEANS-1729] Refactoring dialog does not close

---

nbbuild/build.properties
nbbuild/javadoctools/build.xml
nbbuild/javadoctools/export2allclasses.xsl
nbbuild/javadoctools/export2allmodules.xsl
nbbuild/javadoctools/export2apichanges-atom.xsl
nbbuild/javadoctools/export2apichanges.xsl
nbbuild/javadoctools/export2branding.xsl
nbbuild/javadoctools/export2html.xsl
nbbuild/javadoctools/export2layer.xsl
nbbuild/javadoctools/export2property.xsl
nbbuild/javadoctools/export2usecases.xsl

Hi, @lkishalmi the apidoc branding for release100. done the same way as for release 90

Release100 apidocbranding

---

nbbuild/build.properties
nbbuild/javadoctools/build.xml
nbbuild/javadoctools/export2allclasses.xsl
nbbuild/javadoctools/export2allmodules.xsl
nbbuild/javadoctools/export2apichanges-atom.xsl
nbbuild/javadoctools/export2apichanges.xsl
nbbuild/javadoctools/export2branding.xsl
nbbuild/javadoctools/export2html.xsl
nbbuild/javadoctools/export2layer.xsl
nbbuild/javadoctools/export2property.xsl
nbbuild/javadoctools/export2usecases.xsl

Update index file and last release date to get javadoc main pages and api changes with accurate date

Release90 apidocbranding

---

platform/autoupdate.ui/src/org/netbeans/modules/autoupdate/ui/actions/AutoupdateSettings.java

Fix minor typos

---

platform/openide.explorer/src/org/netbeans/modules/openide/explorer/ExplorerActionsImpl.java

As described in NETBEANS-1834, `ExplorerActionsImpl` uses a background thread to determine the enabled state of its actions. This changes `ExplorerActionsImpl.BaseAction` to use an `AtomicInteger` to synchronize access to the `toEnable` flag and ensure actions are enabled appropriately.

[NETBEANS-1834] Fix possible race condition enabling actions in explorer

---

nbbuild/javadoctools/javadoc-generic.css

I'm not sure that diff matters as it's copy paste from a css to another
'DejaVu Sans' is not present in apidoc resource but it will default to Arial.

[NETBEANS-1987] use javadoc css from jdk8 for apidoc

---

ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/Utils.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/CodeActions.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/CompletionProviderImpl.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/HyperlinkProviderImpl.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/LanguageClientImpl.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/NavigatorPanelImpl.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandler.java

Various improvements to the Language Server Protocol client.

Lsp.client.improvements1

---

groovy/gradle/src/org/netbeans/modules/gradle/customizer/GradleCustomizerProvider.java

o Followup Unlodable vs. Unloadable

[NETBEANS-2001] - Typos in Gradle dialogs

---

ide/core.ide/src/org/netbeans/core/ide/resources/Debugging.xml
ide/core.ide/src/org/netbeans/core/ide/resources/Standard.xml
ide/git/src/org/netbeans/modules/git/git-layer.xml

Integrating the Git Toolbar plugin into the main Git module.
Please do not squash, as I marked the author of the first commit the same as the original Git Toolbar author.

[NETBEANS-2024] Integrating Git Toolbar

---

java/maven/src/org/netbeans/modules/maven/actions/scm/ui/CheckoutUI.java

Details specified at https://issues.apache.org/jira/browse/NETBEANS-2148

[NETBEANS-2148] Maven dependency Check Out action is failing with "The goal you specified requires a project to execute ..."

---

java/maven/src/org/netbeans/modules/maven/newproject/idenative/quickstart.html

Highlight the fact that the Maven/Java Application project template should be the first to use.

[NETBEANS-2047] Maven/Java project template should be preferred

---

enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java

Did everything, except pointing to the Eclipse Licence, hope @peedeeboy or someone will take a look at this. Simply followed @peedeeboy's excellent steps in https://issues.apache.org/jira/browse/NETBEANS-2130, which works great.

[NETBEANS-2130] Add support to download/install/register GlassFish 5.1

---

platform/core.netigso/src/org/netbeans/core/netigso/Netigso.java
platform/core.netigso/src/org/netbeans/core/netigso/NetigsoLoader.java
platform/core.netigso/test/unit/src/org/netbeans/core/netigso/NetigsoLoaderOSGiFragmentTest.java

See https://issues.apache.org/jira/browse/NETBEANS-1774 for details.

NETBEANS-1774 Use fragment host instead of fragment bundle for class loading in Netigso

---

groovy/gradle/netbeans-gradle-tooling/src/main/groovy/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.groovy
groovy/gradle/src/org/netbeans/modules/gradle/GradleProjectCache.java
groovy/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProject.java
groovy/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java
groovy/gradle/src/org/netbeans/modules/gradle/nodes/SubProjectsNode.java
groovy/gradle/src/org/netbeans/modules/gradle/queries/Info.java

This patch works best if applied after #1150.

[NETBEANS-2179] Fixed sub-project serialization and display name improvements.

---

nb/updatecenters/src/org/netbeans/modules/updatecenters/resources/Bundle.properties
nb/updatecenters/src/org/netbeans/modules/updatecenters/resources/mf-layer.xml

This is one PR against release110 branch containing @jkovalsky recommended changes.
Please confirm that this is what we need!

[NETBEANS-2246] Adjusted the update center URL-s

---

nbbuild/build.properties

for the javadoc dev to calculate apichange

Changing the date for apichange calculation

---

nbbuild/javadoctools/export2apichanges.xsl
nbbuild/javadoctools/export2html.xsl

this is for finishing the apidoc site

Add link from dev javadoc to new released apidoc 11

---

apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/ui/customizer/SingleModuleProperties.java

https://issues.apache.org/jira/browse/NETBEANS-2389

[NETBEANS-2389] Missing source level 11 and 12 in a NetBeans module project

---

groovy/gradle/src/org/netbeans/modules/gradle/nodes/SubProjectsNode.java

[NETBEANS-2399] Make sub Project node as a Tree based on the paths on

---

DISCLAIMER
README.md
nbbuild/build.xml
nbbuild/templates/projectized.xml

- Remove "incubator"
- Fix the Travis CI and the Jenkins build links
- Remove DISCLAIMER

Remove incubator parts

---

platform/openide.awt/src/org/openide/awt/Actions.java

https://issues.apache.org/jira/browse/NETBEANS-1792
Fixed "Behavior of BooleanStateAction has changed" issue

[NETBEANS-1792] Behavior of BooleanStateAction has changed

---

platform/openide.util/arch.xml
platform/openide.util/src/org/openide/util/CharSequences.java
platform/openide.util/test/unit/src/org/openide/util/CharSequencesTest.java
platform/openide.util/test/unit/src/org/openide/util/CharSequencesTest.xml

Now, when NetBeans JARs are at Maven Central, I decided to tweet about
usefullib provided by @netbeans
once a week. This week I'd like to react to [this tweet](https://twitter.com/maneo/status/1128618970825875457#xd_co_f=YjAxNGM0YmEtOTdlMC00NGY0LWEzNzgtNDA1Nzc0YWNiYzBj~) by showing the goodies of `CharSequences`.
Before I do it, I'd like to improve the Javadoc a bit. Thanks in advance for your support.

Documenting CharSequences class

---

groovy/gradle/src/org/netbeans/modules/gradle/GradleAuxiliaryPropertiesImpl.java

The prefix had been changed as other part of the plugin expects.
It was changed during the donation process when the custom action become properties, later on the used property prefixes became independent, but the change of this property name broke a few things, most visibly the license header support.
This PR reintroduce the "netbeans." prefix, while handle the data already saved with the wrong prefix as a fallback.

[NETBEANS-2288] Fixed Auxialiary properties to use 'netbeans.' prefix

---

php/php.phpunit/release/phpunit/NetBeansSuite.php
php/php.phpunit/src/org/netbeans/modules/php/phpunit/commands/PhpUnit.java

Due to the latest restrictive changes in PHPUnit, NetBeans integration stopped working. This change fixes these problems by passing files to be tested in an environment variable.

[NETBEANS-2573] Pass files to test in env variable

---

php/php.phpunit/src/org/netbeans/modules/php/phpunit/run/PhpUnitLogParser.java
php/php.phpunit/test/unit/data/phpunit-log-netbeans1851.xml
php/php.phpunit/test/unit/src/org/netbeans/modules/php/phpunit/run/PhpUnitLogParserTest.java

https://issues.apache.org/jira/browse/NETBEANS-1851
- stacktrace may be empty

 [NETBEANS-1851] PHPUnit java.lang.AssertionError: At least 2 lines must be found (message + stacktrace)

---

README.md

In Windows you must install MSYS to have available the command "make"

Clarify installation of MingW in Windows

---

groovy/gradle.java/nbproject/project.xml
groovy/gradle.java/src/org/netbeans/modules/gradle/java/SourceGroupResourceWatchList.java
groovy/gradle.java/src/org/netbeans/modules/gradle/java/classpath/AbstractGradleClassPathImpl.java
groovy/gradle.java/src/org/netbeans/modules/gradle/java/classpath/BootClassPathImpl.java
groovy/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImpl.java
groovy/gradle.java/src/org/netbeans/modules/gradle/java/output/JavaCompilerProcessorFactory.java
java/java.api.common/nbproject/project.xml

I've tried to mimic the magic what Maven does (without all the functional bells and whistles). I feel some classpath definitions redundant however. As far as I could test it works and does not break existing classpath implementations.
Yes, unit-tests are missing.
@geertjanw, @jlahoda  feel free add more reviewers if you know someone more knowledgeable.

[NETBEANS-2004] Initial support for modular java project in Gradle

---

java/maven.coverage/src/org/netbeans/modules/maven/coverage/MavenCoverageProvider.java

For details see https://lists.apache.org/thread.html/bcfc0d73fc215c8f329033a312c0d3d11f8b370453f76e2c91cc184b@%3Cdev.netbeans.apache.org%3E

[NETBEANS-2652] JaCoCo Maven integration is broken in NB 11.0

---

.travis.yml

It seems Oracle JDK 8 got unsupported by Travis.

Try to swicth Travis to Open JDK

---

nb/updatecenters/src/org/netbeans/modules/updatecenters/resources/Bundle.properties
nb/updatecenters/src/org/netbeans/modules/updatecenters/resources/mf-layer.xml

Add back Third Party Libraries plugin center.

Add back Third Party Libraries plugin center.

---

enterprise/payara.common/manifest.mf
enterprise/payara.common/nbproject/project.xml
enterprise/payara.eecommon/nbproject/project.properties
enterprise/payara.eecommon/nbproject/project.xml
enterprise/payara.eecommon/src/org/netbeans/modules/payara/eecommon/dd/loader/PayaraDescriptorDataObject.java
enterprise/payara.jakartaee/manifest.mf
enterprise/payara.jakartaee/nbproject/project.xml
enterprise/payara.jakartaee/src/org/netbeans/modules/payara/jakartaee/Hk2JavaEEPlatformImpl.java
enterprise/payara.jakartaee/src/org/netbeans/modules/payara/jakartaee/Hk2JaxWsStack.java
enterprise/payara.micro/manifest.mf
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/layer.xml
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/BaseWizardIterator.java
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/MicroProjectWizardIterator.java
enterprise/payara.tooling/manifest.mf

Depends on https://github.com/apache/netbeans/pull/1298

NP-20 Payara modules improvement

---

groovy/gradle.java/nbproject/project.xml
groovy/gradle.java/src/org/netbeans/modules/gradle/java/output/JavaCompilerProcessorFactory.java
groovy/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/output/JavaCompilerProcessorFactoryTest.java
groovy/gradle/src/org/netbeans/modules/gradle/api/output/OutputListeners.java
groovy/gradle/src/org/netbeans/modules/gradle/output/GradleProcessorFactory.java
groovy/gradle/test/unit/src/org/netbeans/modules/gradle/api/output/OutputDisplayerMock.java
groovy/gradle/test/unit/src/org/netbeans/modules/gradle/output/GradleProcessorFactoryTest.java

Added some unit tests for Gradle Output processors.

[NETBEANS-2753] Fixed NPE on Java Stacktrace processing.

---

groovy/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java
groovy/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java

A safe thing to be included in 11.1.

[NETBEANS-2792] Close IO only when all registered Gradle Action Hook finished.

---

.travis.yml
enterprise/libs.elimpl/nbproject/org-netbeans-libs-elimpl.sig
enterprise/libs.elimpl/nbproject/project.properties
java/java.api.common/nbproject/org-netbeans-modules-java-api-common.sig
java/java.api.common/src/org/netbeans/modules/java/api/common/SingleJavaSourceRunActionProvider.java

As reported by @neilcsmith-net, the `ant gen-sigtests-release` is currently broken. Here are my changes that shall fix it. Plus I've included the check into Travis job, so next time we hopefully avoid problems like this.

[NETBEANS-2700] Let `ant gen-sigtests-release` pass!

---

nb/ide.branding/release-toplevel/README.html

https://issues.apache.org/jira/browse/NETBEANS-2845

[NETBEANS-2845] Update URLs of README.html

---

webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/parser/SanitizingParser.java
webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/parser/JsonParserTest.java

https://issues.apache.org/jira/browse/NETBEANS-2881
This exception occurs when a json file is empty.

[NETBEANS-2881] Prevent java.lang.StringIndexOutOfBoundsException

---

apisupport/maven.apisupport/nbproject/project.properties
apisupport/maven.apisupport/nbproject/project.xml
apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/MavenNbModuleImpl.java
apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NBMNativeMWI.java
apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardPanelVisual.java
apisupport/maven.apisupport/test/unit/src/org/netbeans/modules/maven/apisupport/NBMNativeMWITest.java

Add test and remove former repository (oracle) from the maven apisupport

NETBEANS-2883 Remove link to bits.netbeans.org/maven2 + test

---

php/php.api.phpmodule/manifest.mf
php/php.api.phpmodule/src/org/netbeans/modules/php/api/PhpVersion.java
php/php.editor/nbproject/project.properties
php/php.editor/nbproject/project.xml
php/php.editor/src/org/netbeans/modules/php/editor/codegen/CGSInfo.java
php/php.editor/src/org/netbeans/modules/php/editor/model/impl/Type.java
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesConstructor/testTypedPropertiesConstructor.php
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesConstructor/testTypedPropertiesConstructor.php.testTypedPropertiesConstructor_PHP56.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesConstructor/testTypedPropertiesConstructor.php.testTypedPropertiesConstructor_PHP70.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesConstructor/testTypedPropertiesConstructor.php.testTypedPropertiesConstructor_PHP71.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesConstructor/testTypedPropertiesConstructor.php.testTypedPropertiesConstructor_PHP74.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesGetter/testTypedPropertiesGetter.php
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesGetter/testTypedPropertiesGetter.php.testTypedPropertiesGetter_PHP56.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesGetter/testTypedPropertiesGetter.php.testTypedPropertiesGetter_PHP70.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesGetter/testTypedPropertiesGetter.php.testTypedPropertiesGetter_PHP71.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesGetter/testTypedPropertiesGetter.php.testTypedPropertiesGetter_PHP74.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesSetter/testTypedPropertiesSetter.php
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesSetter/testTypedPropertiesSetter.php.testTypedPropertiesSetter_PHP56.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesSetter/testTypedPropertiesSetter.php.testTypedPropertiesSetter_PHP70.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesSetter/testTypedPropertiesSetter.php.testTypedPropertiesSetter_PHP71.codegen
php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesSetter/testTypedPropertiesSetter.php.testTypedPropertiesSetter_PHP74.codegen
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/codegen/SelectedPropertyMethodsCreatorTest.java

https://issues.apache.org/jira/browse/NETBEANS-53
- Add types of properties to parameter and return types of constructor, getter,or setter
- php/php.editor/src/org/netbeans/modules/php/editor/codegen/CGSInfo.java
- php/php.editor/src/org/netbeans/modules/php/editor/model/impl/Type.java
Other than those, unit test files.

[NETBEANS-53] Improve constructor getter setter code generation

---

ide/schema2beans/src/org/netbeans/modules/schema2beansdev/BeanClass.java

* Fixing the returned value.
Jira: https://issues.apache.org/jira/browse/NETBEANS-2975

[NETBEANS-2975]: Schema2Beans shouldn't return 'null' for primitive types.

---

php/php.editor/src/org/netbeans/modules/php/editor/model/ModelUtils.java
php/php.editor/src/org/netbeans/modules/php/editor/model/impl/ModelVisitor.java
php/php.editor/src/org/netbeans/modules/php/editor/model/impl/VariousUtils.java
php/php.editor/test/unit/data/testfiles/completion/lib/nb2992/nb2992.php
php/php.editor/test/unit/data/testfiles/completion/lib/nb2992/nb2992.php.testNb2992_01.completion
php/php.editor/test/unit/data/testfiles/completion/lib/nb2992/nb2992.php.testNb2992_02.completion
php/php.editor/test/unit/data/testfiles/completion/lib/nb2992/nb2992.php.testNb2992_03.completion
php/php.editor/test/unit/data/testfiles/completion/lib/tests247082/issue247082.php.testForKeywords.completion
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionNb2992Test.java

https://issues.apache.org/jira/browse/NETBEANS-2992
- Change the current scope when `$this` is used in anonymous functions

[NETBEANS-2992] Code completion does not work well inside Closures

---

java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/LogicalViewProviderImpl.java

Select in Projects (Ctrl-Shift-1) does not work properly for tests in OpenJDK projects. This is because there is no target node finder for the test nodes - this patch fixes that by doing the same thing java.project.ui is doing.

Fixing Select in Projects for OpenJDK project tests.

---

php/php.editor/src/org/netbeans/modules/php/editor/model/impl/VariousUtils.java
php/php.editor/test/unit/data/testfiles/completion/lib/nb501/nb501.php
php/php.editor/test/unit/data/testfiles/completion/lib/nb501/nb501.php.testNb501_01.completion
php/php.editor/test/unit/data/testfiles/completion/lib/nb501/nb501.php.testNb501_02.completion
php/php.editor/test/unit/data/testfiles/completion/lib/nb501/nb501.php.testNb501_03a.completion
php/php.editor/test/unit/data/testfiles/completion/lib/nb501/nb501.php.testNb501_03b.completion
php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionNb501Test.java

https://issues.apache.org/jira/browse/NETBEANS-501
- Restore the current token sequence offset to the clone expression end offset when `clone` keyword is found

[NETBEANS-501] Support (clone $object)->method() in PHP

---

ide/subversion/src/org/netbeans/modules/subversion/ui/update/ResolveConflictsExecutor.java

Updated ResolveConflictsExecutor in Subversion using Git as a reference.

NETBEANS-544: Merge conflicts resolver doesn't recognize "|||||||" conflict markers

---

websvccommon/websvc.saas.api/test/unit/src/org/netbeans/modules/websvc/saas/util/FakeSaas.xml
websvccommon/websvc.saas.api/test/unit/src/org/netbeans/modules/websvc/saas/util/SaasUtilTest.java
websvccommon/websvc.saas.api/test/unit/src/org/netbeans/modules/websvc/saas/util/testwadl.xml

Fix SaasUtilTest test in websvc.saas.api module.
Command to run this test:
```bash
ant -f websvccommon/websvc.saas.api -Dtest.type=unit -Dtest.includes=org/netbeans/modules/websvc/saas/util/SaasUtilTest.java test-single
```

Fix SaasUtilTest test in websvc.saas.api module

---

.travis.yml
ide/versioning.ui/nbproject/project.xml
ide/versioning.ui/test/unit/src/org/netbeans/modules/versioning/ui/history/VCSCoreSPIHistoryTest.java
ide/versioning.ui/test/unit/src/org/netbeans/modules/versioning/ui/history/VCSSPIHistoryTest.java

Fix tests in ide/versioning.ui module

Fix tests in ide/versioning.ui module

---

enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/plugin/Constants.java
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/plugin/MicroPluginWizardDescriptor.java
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/plugin/resources/pom.xml.ftl
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/Bundle.properties
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/MicroProjectWizardIterator.java
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/PayaraMicroPanel.form
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/PayaraMicroPanel.java

Signed-off-by: Gaurav Gupta <gaurav.gupta.jc@gmail.com>

NP-50 Upgrade Payara Micro Maven plugin to 1.0.6 and custom contextRoot support

---

java/java.editor/src/org/netbeans/modules/java/editor/codegen/Bundle.properties
java/java.editor/src/org/netbeans/modules/java/editor/codegen/ToStringGenerator.java
java/java.editor/src/org/netbeans/modules/java/editor/codegen/ui/ToStringPanel.java
java/java.editor/test/unit/src/org/netbeans/modules/java/editor/codegen/ToStringGeneratorTest.java

https://issues.apache.org/jira/browse/NETBEANS-2653
As the same as current behavior, "+" operator is used by default.

[NETBEANS-2653] Generate toString() with StringBuilder

---

groovy/gradle.java/src/org/netbeans/modules/gradle/java/classpath/GradleSourcesImpl.java

[NETBEANS-2925](https://issues.apache.org/jira/browse/NETBEANS-2925)
Well, I need some advice here. Returning mixed on the contents of build dir is probably not the best thing to do. Shall I initiate a different package view with different filter for generated sources instead?

[NETBEANS-2925] Possible solution to not to filter out sources from the buildDir

---

nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java

When a binary fails the hash check a BuildException is raised and the
build process is directly terminated. With this change, all binaries are
checked and all failures are reported. If one download fails, a
BuildException is raised after trying to download all binaries.

Report all failed binaries for DownloadBinaries task

---

groovy/gradle/manifest.mf
groovy/gradle/src/org/netbeans/modules/gradle/api/execute/GradleCommandLine.java
groovy/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
groovy/gradle/src/org/netbeans/modules/gradle/spi/GradleFiles.java

Take over #1425 as it seems to be abandoned, in order to be released in 11.2.

[NETBEANS-3041] Support passing JVM Arguments to Gradle Daemon

---

java/java.hints/src/org/netbeans/modules/java/hints/errors/Utilities.java
java/java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertSwitchToRuleSwitch.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertSwitchToRuleSwitchTest.java

Convert to switch expression for following scenario (return case):
Actual Code:
void test(Object o1, Object o2, Object o3, int n) {
String result;
switch(n) { 
case 1: 
result = (String) o1;
break; 
case 2: 
result = (String) o2;
break; 
default: 
result = (String) o3;
break; 
}
System.out.println(result);
} 
After Fix with hints Hint : 'Convert to switch expression'
void test(Object o1, Object o2, Object o3, int n) {
String result;
result = (String)( switch (n){ 
case 1 -> o1; 
case 2 -> o2; 
default -> o3; }
);
System.out.println(result);
}

[NETBEANS-2349] Convert switch typecast case to switch expression

---

nbbuild/antsrc/org/netbeans/nbbuild/ReleaseJsonProperties.java

Fix for using URL directly + typo + information display

 use URL information direct from JSON + verbose

---

nbbuild/antsrc/org/netbeans/nbbuild/ReleaseJsonProperties.java
nbbuild/build.xml

this is order fix for build to get git in the right order.

fix build order for git properties + json correction

---

apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardIterator.java

Archetypes need to reflect the 4.3 changes too.
Need to wait for vote. 
Note sure on how to simplify the workflow yet.

NETBEANS-3185 use last maven-nbm-plugin

---

java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java
java/java.completion/test/unit/data/goldenfiles/org/netbeans/modules/java/completion/JavaCompletionTaskTest/1.8/GenericMethodInvocation1.pass
java/java.completion/test/unit/data/goldenfiles/org/netbeans/modules/java/completion/JavaCompletionTaskTest/1.8/GenericMethodInvocation2.pass
java/java.completion/test/unit/data/org/netbeans/modules/java/completion/data/GenericMethodInvocation.java
java/java.completion/test/unit/src/org/netbeans/modules/java/completion/JavaCompletionTaskAdvancedTest.java

Basically, for type variables, use their bounds for smart type computation. (That's the idea at least.)

Improving Java code completion behavior in presence of type variables.

---

.travis.yml
nbbuild/travis/hide-logs.sh

Change Travis config to run tests for platform modules.

[TRAVIS] Run tests for platform modules

---

ergonomics/ide.ergonomics/java.properties
ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/ConfigurationPanel.form
ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/ConfigurationPanel.java
ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/FeatureInfo.java
ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/FindComponentModules.java
ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/FoDUpdateUnitProvider.java
ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/ModulesInstaller.java

add upper limit for recommended modules
changing configuration panel ui to show recommended and required installs, because otherwise nbjavac will be installed automatically.

[NETBEANS-2439] Java Frontend Application cannot be activated on JDK11

---

groovy/gradle.java/src/org/netbeans/modules/gradle/java/output/JDPAProcessorFactory.java

It shut down the debugee when the NetBeans debugger session is closed..

[NETBEANS-2950] A possible solution to avoid debug loop with Gradle projects

---

ide/db.drivers/external/binaries-list
ide/db.drivers/external/postgresql-42.2.8-license.txt
ide/db.drivers/nbproject/project.properties
ide/db.drivers/src/org/netbeans/modules/db/drivers/Bundle.properties
ide/db.drivers/src/org/netbeans/modules/db/drivers/PostgreSQLDriver.xml
ide/db.drivers/src/org/netbeans/modules/db/drivers/postgresql.xml

Update postgresql driver to newer version

[NETBEANS-3397] Updating to postgresql 42.2.8

---

groovy/gradle.test/src/org/netbeans/modules/gradle/test/GradleTestProgressListener.java

Thanks to Gradle 6.0 Tooling it is possible to route the test outputs back to the IDE. As far as I tested it works with projects using Gradle version prior 6.0 as well.

[NETBEANS-2555] Display test output while running tests.

---

java/java.source.base/src/org/netbeans/modules/java/source/parsing/CachingArchiveClassLoader.java

See [NETBEANS-3387](https://issues.apache.org/jira/browse/NETBEANS-3387) for the description.

[NETBEANS-3387] classes loaded from scanned path should get CodeSource.location

---

groovy/gradle/src/org/netbeans/modules/gradle/actions/ReloadAction.java

Added a simple action to reload Gradle Projects from its context Menu.

[NETBEANS-2960] Added Reload Project action for Gradle

---

.travis.yml

Run ergonomic module tests in a separate build job.

[TRAVIS] Test ergonomics modules

---

ide/html.lexer/manifest.mf
ide/html.lexer/src/org/netbeans/lib/html/lexer/HtmlLexer.java
php/php.smarty/test/unit/data/testfiles/parserErrors/testParserNETBEANS3335_01.tpl
php/php.smarty/test/unit/data/testfiles/parserErrors/testParserNETBEANS3335_01.tpl.errors
php/php.smarty/test/unit/data/testfiles/parserErrors/testParserNETBEANS3335_02.tpl
php/php.smarty/test/unit/data/testfiles/parserErrors/testParserNETBEANS3335_02.tpl.errors
php/php.smarty/test/unit/src/org/netbeans/modules/php/smarty/editor/parser/TplParserErrorsTest.java

As requested in #1617 this is a straight backport of the patches
to the release112 branch. For details about the changeset please
see the original PR, the only additional change is the bump of
the spec version.

Backport of PR #1617

---

nbbuild/templates/common.xml

assumption of being in root were false. fixing delta in path

NETBEANS-3290 fix common xml

---

harness/apisupport.harness/manifest.mf
nbbuild/templates/common.xml

Any comments @jlahoda / @geertjanw on shipping updates to the platform harness via NBM update?

Backport NETBEANS-3290 fix to 11.2 release branch.

---

platform/o.n.swing.laf.dark/src/org/netbeans/swing/laf/dark/Installer.java

Well, only the LaF registration remains. The removed code would be useful for other LaF support.

[NETBEANS-3432] Removed the auto activation code from Dark LaF Support

---

.travis.yml

Run tests for webcommon modules in a Travis job.
It's based in this pull request: https://github.com/apache/netbeans/pull/1598

[TRAVIS] Run tests for webcommon modules

---

ide/lsp.client/nbproject/project.xml
ide/lsp.client/src/org/netbeans/modules/lsp/client/Utils.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandler.java
ide/lsp.client/test/unit/src/org/netbeans/modules/lsp/client/UtilsTest.java

So that pressing Enter or '}' does something meaningful.

Adding default indent capabilities while typing for the LSP client.

---

java/java.editor/src/org/netbeans/modules/editor/java/JavaKit.java
java/java.editor/src/org/netbeans/modules/editor/java/TypingCompletion.java
java/java.editor/test/unit/src/org/netbeans/modules/editor/java/TypingCompletionUnitTest.java

[NETBEANS-3202] Fix issue in Text Block

[NETBEANS-3202] Fix issue in Text Block

---

.travis.yml

Add Travis job to test if source compiles the full project with OpenJDK11.

[TRAVIS] Compile all modules with OpenJDK11

---

ide/languages.yaml/src/org/netbeans/modules/languages/yaml/layer.xml

[NETBEANS-3545] Add Tabs and Indents customization for Yaml files.

---

harness/o.n.insane/nbproject/project.properties
harness/o.n.insane/src/org/netbeans/insane/impl/SmallObjectMap.java
harness/o.n.insane/src/org/netbeans/insane/impl/SmallObjectMap2.java
harness/o.n.insane/test/unit/src/org/netbeans/insane/impl/InsaneEngineTest.java
harness/o.n.insane/test/unit/src/org/netbeans/insane/impl/LiveEngineTest.java
harness/o.n.insane/test/unit/src/org/netbeans/insane/impl/RootTest.java
harness/o.n.insane/test/unit/src/org/netbeans/insane/impl/SmallObjectMap2Test.java
harness/o.n.insane/test/unit/src/org/netbeans/insane/impl/SmallObjectMapTest.java
harness/o.n.insane/test/unit/src/org/netbeans/insane/impl/UtilsTest.java

Add some unit tests in insane module

Insane module, add unit tests

---

.travis.yml

- Add Travis job to check if source compiles the full project with OpenJDK8.

[TRAVIS] Compile all modules with OpenJDK8

---

ide/languages.yaml/nbproject/project.properties
ide/languages.yaml/src/org/netbeans/modules/languages/yaml/BlueTheme-fontsColors.xml
ide/languages.yaml/src/org/netbeans/modules/languages/yaml/Bundle.properties
ide/languages.yaml/src/org/netbeans/modules/languages/yaml/FontAndColors.xml
ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlExample.yaml
ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlLexer.java
ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlParser.java
ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlTokenId.java
ide/languages.yaml/test/unit/data/testfiles/input4.yaml.txt
ide/languages.yaml/test/unit/data/testfiles/input4.yaml.txt.tokens.txt
ide/languages.yaml/test/unit/src/org/netbeans/modules/languages/yaml/YamlLexerTest.java

[NETBEANS-3553] Add Mustache Support for Yaml

---

.travis.yml

Add retry for platform/masterfs tests that fail randomly.

[TRAVIS] Add retry for platform/masterfs tests

---

.travis.yml

Add retry for  ide/bugtracking tests that fail randomly.

[TRAVIS] Add retry for ide/bugtracking tests

---

.travis.yml
ide/notifications/nbproject/project.properties
ide/notifications/test/unit/src/org/netbeans/modules/notifications/center/NotificationCenterManagerTest.java

Run tests for ide/notifications module

[TRAVIS] Run tests for ide/notifications module

---

.travis.yml

Add Travis job to run some tests of php cluster modules

[TRAVIS] Add Travis job to run php tests

---

.travis.yml

Enable platform/core.osgi tests in Travis config

[TRAVIS] Enable platform/core.osgi tests

---

.travis.yml
harness/jellytools.platform/nbproject/project.properties
harness/jellytools.platform/test/qa-functional/src/org/netbeans/jellytools/BundleTest.java
harness/nbjunit/test/unit/src/org/netbeans/junit/internal/NbModuleLogHandlerTest.java

Redefine jellytools stable tests to enable in Travis config

Redefine jellytools stable tests

---

java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/SemanticHighlighterBase.java
java/java.editor.base/test/unit/src/org/netbeans/modules/java/editor/base/semantic/DetectorTest.java

[NETBEANS-3218] Add inline hint support for literals used in constructors

---

.travis.yml

[TRAVIS] Run LSP client tests

---

enterprise/payara.tooling/nbproject/org-netbeans-modules-payara-tooling.sig
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/data/JDKVersion.java
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/data/StartupArgsEntity.java
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/ServerTasks.java
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/parser/JvmConfigReader.java
enterprise/payara.tooling/test/unit/src/org/netbeans/modules/payara/tooling/data/JDKVersionTest.java

Signed-off-by: Gaurav Gupta <gaurav.gupta.jc@gmail.com>

[NETBEANS-3573] Unable to start the Payara server due to JDK version NumberFormatException

---

enterprise/payara.common/nbproject/org-netbeans-modules-payara-common.sig
enterprise/payara.common/src/org/netbeans/modules/payara/common/Bundle.properties
enterprise/payara.common/src/org/netbeans/modules/payara/common/ServerDetails.java
enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/VersionRepository.java
enterprise/payara.tooling/nbproject/org-netbeans-modules-payara-tooling.sig
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/admin/AdminFactory.java
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/data/PayaraVersion.java

Signed-off-by: Gaurav Gupta <gaurav.gupta.jc@gmail.com>

[NETBEANS-3584] Payara Platform 5.194/5.201 support in Apache NetBeans IDE

---

.travis.yml

Tests for ide/db modules fails randomly. Add travis retry command.

[TRAVIS] Retry for ide/db module

---

webcommon/extbrowser.chrome/src/org/netbeans/modules/extbrowser/chrome/ChromeBrowserImpl.java

The call to toRealPath ensures, that symlinks are resolved. It was
observed, that chrome on macOS reports the file url with symlinks
resolved, so align with that.
Closes: #1577

[NETBEANS-3249] Chrome connector connection with NetBeans

---

groovy/gradle/src/org/netbeans/modules/gradle/GradleDistributionManager.java
groovy/gradle/src/org/netbeans/modules/gradle/options/SettingsPanel.form
groovy/gradle/src/org/netbeans/modules/gradle/options/SettingsPanel.java

Also removed some rawtype warnings from the Settings panel.

[NETBEANS-3633] Use HTTPS to download Gradle Version information

---

.travis.yml

Refactor Travis config for verify libs and licenses job.

[TRAVIS] Refactor verify licenses job

---

ide/xml.text/src/org/netbeans/modules/xml/text/resources/XMLExampleIndent
ide/xml.text/src/org/netbeans/modules/xml/text/resources/mf-layer.xml
nbbuild/rat-exclusions.txt

[NETBEANS-3638] Add Indenting options for XML

---

.travis.yml
nbbuild/travis/scripting.sh

[TRAVIS] Refactor GRAALVM tests

---

.travis.yml
platform/core.windows/test/unit/src/org/netbeans/core/windows/InvokeWhenUIReadInHeadlessModeTest.java
platform/core.windows/test/unit/src/org/netbeans/core/windows/awt/ValidateLayerMenuTest.java
platform/core.windows/test/unit/src/org/netbeans/core/windows/awt/ValidateLayerToolbarTest.java

Enable platform/core.windows tests

[TRAVIS] Enable platform/core.windows tests

---

.travis.yml

Refactor Travis config for sigtest job.

[TRAVIS] Refactor config for sigtests job

---

java/java.source/src/org/netbeans/modules/java/ui/FmtImports.form
java/java.source/src/org/netbeans/modules/java/ui/FmtImports.java

Simple fix using gui editor. Used IndentationPanel as example. Details in bug report.

[NETBEANS-3673] Fix int spinner sizes in options dialog format:imports.

---

.travis.yml

Enable tests for ide/xml.wsdl.model module

[TRAVIS] Enable tests for ide/xml.wsdl.model module

---

.travis.yml
java/api.maven/nbproject/project.properties
java/api.maven/src/org/netbeans/api/maven/archetype/Archetype.java
java/dbschema/nbproject/project.properties
java/hudson.maven/nbproject/project.properties

Change Travis config to add more java modules in the Travis job.

[TRAVIS] Run tests for some java modules

---

platform/core.network/src/org/netbeans/core/network/utils/LocalAddressUtils.java
platform/core.network/test/unit/src/org/netbeans/core/network/utils/HostnameUtilsTest.java
platform/core.network/test/unit/src/org/netbeans/core/network/utils/LocalAddressUtilsTest.java
platform/core.network/test/unit/src/org/netbeans/core/network/utils/hname/linux/HostnameUtilsLinuxTest.java
platform/core.network/test/unit/src/org/netbeans/core/network/utils/hname/unix/HostnameUtilsUnixTest.java

Test hostname methods in platform/core.network module

Tests in core network module

---

java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/SemanticHighlighterBase.java
java/java.editor.base/test/unit/src/org/netbeans/modules/java/editor/base/semantic/DetectorTest.java

Waiting for #1559 getting merged.

[NETBEANS-3268] Add hints for variables and method return parameters

---

groovy/gradle.java/src/org/netbeans/modules/gradle/java/queries/OpenGradleProjectForBinary.java

I've started a poll on the dev maillist if I need to implement a switch for this or not.

[NETBEANS-3115] Resolve third-party source against open Gradle projects.

---

nb/autoupdate.pluginimporter/build.xml
nb/autoupdate.pluginimporter/nbproject/project.properties
nb/autoupdate.pluginimporter/nbproject/project.xml
nb/autoupdate.pluginimporter/src/org/netbeans/modules/autoupdate/pluginimporter/Bundle.properties
nb/autoupdate.pluginimporter/src/org/netbeans/modules/autoupdate/pluginimporter/Installer.java
nb/autoupdate.pluginimporter/test/unit/src/org/netbeans/modules/autoupdate/pluginimporter/InstallerTest.java
nb/o.n.upgrader/build.xml
nb/o.n.upgrader/nbproject/project.properties
nb/o.n.upgrader/src/org/netbeans/upgrade/AutoUpgrade.java
nb/o.n.upgrader/src/org/netbeans/upgrade/Bundle.properties

not intended for beta1; just to show one option for the branding.

Branding for upgrader and autoupdate

---

platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
platform/openide.explorer/src/org/openide/explorer/propertysheet/SheetTable.java

This PR fixes the missing vertical lines in right column of PropSheet.

[NETBEANS-3428] FlatLaf: fixed missing vertical lines in PropSheet

---

ide/versioning.util/src/org/netbeans/modules/turbo/Turbo.java

Fix typo in Turbo.java comments

---

.travis.yml

Refactor config to run gen-sigtests-release for platform cluster.

[TRAVIS] Refactor config gen-sigtests-release for platform

---

.travis.yml
nb/ide.branding/nbproject/project.properties
nb/ide.branding/test/unit/src/org/netbeans/modules/ide/branding/RealPacEngineTest.java

Add Travis job for test nb modules

[TRAVIS] Test nb modules

---

.travis.yml

Enable tests for ide/bugtracking.bridge module.

[TRAVIS] Enable ide/bugtracking.bridge tests

---

.travis.yml
javafx/javafx2.editor/nbproject/project.properties

Add Travis job to run tests for JavaFX modules.

[TRAVIS] Run JavaFX tests

---

enterprise/j2ee.common/nbproject/project.xml
ide/utilities/nbproject/project.xml
java/dbschema/nbproject/project.xml
java/j2ee.persistence/nbproject/project.xml
java/maven.embedder/nbproject/project.xml
java/maven.model/nbproject/project.xml

Replacement of PR https://github.com/apache/netbeans/pull/1405 with only friend request commits.
And creating the separate PR for Public API/SPI request.

JEDDICT-322 Add Jeddict modules to friend-packages 

---

enterprise/servletjspapi/build.xml
enterprise/web.beans/src/org/netbeans/modules/web/beans/impl/model/EnableBeansFilter.java
enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/facelets/libdefs/core.xml
enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/facelets/libdefs/html.xml
enterprise/web.jsf.editor/src/org/netbeans/modules/web/jsf/editor/facelets/mojarra/ConfigManager.java
enterprise/web.jsf/licenseinfo.xml
enterprise/web.jsf/src/org/netbeans/modules/web/jsf/JSFCatalog.java
enterprise/web.jsf/src/org/netbeans/modules/web/jsf/impl/facesmodel/JSFConfigModelImpl.java
enterprise/web.jsf/src/org/netbeans/modules/web/jsf/impl/facesmodel/JSFConfigQNames.java
enterprise/web.jsf/src/org/netbeans/modules/web/jsf/resources/web-facelettaglibrary_2_3.xsd
enterprise/web.jsf/src/org/netbeans/modules/web/jsf/resources/web-faces-mime-resolver.xml
enterprise/web.jsf20/external/binaries-list
enterprise/web.jsf20/external/javax.faces-2.3.9-license.txt
enterprise/web.jsf20/nbproject/org-netbeans-modules-web-jsf20.sig
enterprise/web.jsf20/nbproject/project.properties
enterprise/web.jsf20/src/org/netbeans/modules/web/jsf20/Bundle.properties
enterprise/web.jsf20/src/org/netbeans/modules/web/jsf20/jsf20.xml

- Updated files to add support for JSF 2.3.9
- Provides changes to web.beans to enable the injection of Faces resources

NETBEANS-84: Support for JSF 2.3; CDI Changes for JSF Artifact Injection

---

groovy/gradle.java/src/org/netbeans/modules/gradle/java/queries/OpenGradleProjectForBinary.java

Hi Eric, this shall be in 11.3-beta2.

[NETBEANS-3115] Patch possible NPE on not fully loaded Gradle projects.

---

extra/libs.javafx.linux/external/javafx-linux-13-license.txt
extra/libs.javafx.macosx/external/javafx-mac-13-license.txt
extra/libs.javafx.win/external/javafx-win-13-license.txt
java/libs.javacapi/external/nb-javac-13-api-license.txt
java/libs.javacimpl/external/nb-javac-13-impl-license.txt
java/libs.jshell.compile/external/jshell-9-license.txt
nbbuild/external/langtools-9-license.txt
nbbuild/external/sigtest-maven-plugin-1.2-license.txt
nbbuild/licenses/GPL-2-CP
platform/javahelp/external/jhall-2.0_05-license.txt
platform/libs.javafx/external/lib-javafx-13.03-beta-license.txt

Should be the same as this: https://hg.netbeans.org/main/nb-java-x/file/tip/LICENSE

Updating GPL-2 license

---

platform/progress.ui/src/org/netbeans/modules/progress/ui/AbstractWindowRunner.java

Details with screenshots here: https://issues.apache.org/jira/browse/NETBEANS-3729
Tested with FlatLaf, Windows, Nimbus and Metal LAFs.

[NETBEANS-3729] FlatLaf: fix cut off label in progress dialog

---

groovy/libs.groovy/src/org/netbeans/modules/libs/groovy/groovy-all.xml

Make groovy-all.xml parseable.

---

java/java.api.common/src/org/netbeans/modules/java/api/common/singlesourcefile/Description.html
java/java.api.common/src/org/netbeans/modules/java/api/common/singlesourcefile/File.java.template
java/java.api.common/src/org/netbeans/modules/java/api/common/singlesourcefile/package-info.java

Allows creating stand alone java file in favorites window

[NETBEANS-3587] Allows creating stand alone java file in favorites window

---

java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java

Fix formatting of record with no args. e.g 
**Input** :  public 
record 
Test3(
){
}
**Output before fix**
public record Test3(
){
}
**Output after fix**
public record Test3(){
}

NETBEANS-3604 Supports for Records (JEP 359) in JDK-14

---

java/java.source.base/src/org/netbeans/modules/java/source/parsing/ParameterNameProviderImpl.java

I've accidentally bumped into this one and found a reproducible test case, so I've tried to fix it.
Well it is a real naive fix, cacthing and handlinng ConcurrentModificationException. Maybe the affected hash map could be a concurrent one, then that could be better, or we could dig up the root cause why the concurrency modifications happen at first place. I leave that to @jlahoda 
However this patch seems to work and harmless. We have 5 issues in JIRA related to this one, so if it is not too late let put it into 11.3 (beta2 or rc1)

[NETBEANS-3286] Naive fix for CME in Call Hierarchy

---

java/java.hints/src/org/netbeans/modules/java/hints/errors/ImplementAllAbstractMethods.java
java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java

https://issues.apache.org/jira/browse/NETBEANS-3702

[NETBEANS-3702 : Fixed hint 'implements all abstract method' for record interfaces]

---

platform/openide.loaders/src/org/openide/awt/Toolbar.java

[NETBEANS-3737] FlatLaf: fix cramped Toolbar icons

---

java/libs.springframework/src/org/netbeans/libs/springframework/spring-framework300.xml
java/libs.springframework/src/org/netbeans/libs/springframework/spring-framework400.xml
java/libs.springframework/src/org/netbeans/libs/springframework/spring-framework500.xml

fix for missing dependencies  in springframework

NETBEANS-3777 Use pom type instead of jar for bom artefacts

---

java/java.source.base/src/org/netbeans/modules/java/source/save/PositionEstimator.java

https://issues.apache.org/jira/browse/NETBEANS-3786
This issue occurs only when there is no any other import statement present

[NETBEANS-3786] : Fixed position of hint (add import) for record (jdk14). 

---

java/java.hints/src/org/netbeans/modules/java/hints/jdk/AnnotationProcessors.java

Well, I had no ways to test this one, just followed common sense.

[NETBEANS-3804] Fix NPE in AnnotationProdessor hint

---

groovy/gradle.java/src/org/netbeans/modules/gradle/java/newproject/SimpleApplicationProjectWizard.java
groovy/gradle.java/src/org/netbeans/modules/gradle/java/newproject/SimpleLibraryProjectWizard.java
groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/newproject/ServerSelectionPanelVisual.java
groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/newproject/WebApplicationProjectWizard.java

This one is just a minor update that removes deprecation warnings from newly generated Gradle projects.

[NETBEANS-3818] Gradle Projects Generation Update

---

groovy/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImpl.java
groovy/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleBinaryForSource.java

Quite trivial can be included in 11.3 if there is some time. I was discovering these issues while I was working on NetBeans build using Gradle.

[NETBEANS-3867] Fix NPE-s for some rare cases on Gradle projects

---

.travis.yml

Run `groovy/groovy.gsp` module and `groovy/groovy.support` module tests in Travis config

[TRAVIS] Groovy modules tests

---

apisupport/apisupport.project/src/org/netbeans/modules/apisupport/project/ui/branding/InternationalizationResourceBundleBrandingPanel.java
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/admin/RunnerRestFetchLogData.java
enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/support/SourceGroupSupport.java
ide/editor.deprecated.pre65formatting/src/org/netbeans/editor/ext/ExtFormatter.java
ide/editor.deprecated.pre65formatting/src/org/netbeans/editor/ext/FormatTokenPositionSupport.java
ide/editor.fold.nbui/src/org/netbeans/modules/editor/fold/ui/CaretFoldExpanderImpl.java
ide/spi.debugger.ui/src/org/netbeans/modules/debugger/ui/views/ViewModelListener.java
ide/target.iterator/nbproject/project.properties
ide/target.iterator/src/org/netbeans/modules/target/iterator/api/BrowseFolders.java
ide/xml.catalog.ui/src/org/netbeans/modules/xml/catalog/CatalogMounterModel.java
java/ant.debugger/src/org/netbeans/modules/ant/debugger/breakpoints/PersistenceManager.java
java/dbschema/src/org/netbeans/modules/dbschema/DBMemoryCollection.java
java/dbschema/src/org/netbeans/modules/dbschema/TableElement.java
java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/DBElementsCollection.java
java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/SchemaElementImpl.java
java/java.freeform/src/org/netbeans/modules/java/freeform/JavaProjectGenerator.java
java/java.hints.ui/src/org/netbeans/modules/java/hints/spiimpl/refactoring/InspectAndRefactorPanel.java
java/jshell.support/src/org/netbeans/modules/jshell/project/JShellOptions2.java
java/websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/support/SourceGroupSupport.java
javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/actions/ControllerGenerator.java
javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/completion/beans/FxBean.java
platform/core.multitabs/src/org/netbeans/core/multitabs/impl/TabLayoutManager.java
platform/core.multiview/src/org/netbeans/core/multiview/MultiViewPeer.java
platform/core.startup/src/org/netbeans/core/startup/layers/SessionManager.java
profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/model/HeapWalkerNode.java
webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java

This change cleans up the following warning..
[repeat] /home/bwalker/src/netbeans/webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java:1454: warning: [rawtypes] found raw type: ArrayList
[repeat]             private List<VarNode> declaredVars = new ArrayList();
[repeat]                                                      ^
[repeat]   missing type arguments for generic class ArrayList<E>
[repeat]     E extends Object declared in class ArrayList

[NETBEANS-3807] - cleanup ArrayList rawtype warnings..

---

java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/text/TextDocumentServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/ServerTest.java

Ensuring that 'newText' in TextEdit is non-null.

---

webcommon/javascript.cdnjs/src/org/netbeans/modules/javascript/cdnjs/LibraryCustomizer.java
webcommon/javascript.cdnjs/src/org/netbeans/modules/javascript/cdnjs/LibraryProvider.java
webcommon/javascript.cdnjs/src/org/netbeans/modules/javascript/cdnjs/ui/SearchPanel.java
webcommon/javascript.cdnjs/src/org/netbeans/modules/javascript/cdnjs/ui/SelectionPanel.java
webcommon/javascript.cdnjs/test/unit/src/org/netbeans/modules/javascript/cdnjs/LibraryProviderTest.java

The seach API of CDNJS returned the available version in the past. This
is no longer the case and the versions need to be fetch independently.

[NETBEANS-2183] Workaround change in CDNJS search API

---

platform/openide.awt/src/org/openide/awt/HtmlLabelUI.java
platform/openide.awt/src/org/openide/awt/HtmlRenderer.java
platform/openide.awt/src/org/openide/awt/HtmlRendererImpl.java
platform/openide.awt/src/org/openide/awt/PropertyMonitor.java
platform/openide.awt/test/unit/src/org/openide/awt/HtmlRendererTest.java

As the author or #1447 (@timboudreau) is unresponsive we either need to
drop or fix the PR. Instead of dropping it, I rebased it onto master and added
the missing NOI18N markers.
@junichi11 @neilcsmith-net could you have a look if it is mergeable in this
form?
@timboudreau maybe you could find some time to check if you agree with
this update.
Closes: #1447

Fix HtmlRenderer.createLabel()

---

.travis.yml

Fix macOS job using homebrew openjdk11 version.

[TRAVIS] Fix macOS job

---

.travis.yml

Add ide modules in Travis config

[TRAVIS] Add ide modules in Travis config

---

ide/db.drivers/external/binaries-list
ide/db.drivers/external/postgresql-42.2.10-license.txt
ide/db.drivers/manifest.mf
ide/db.drivers/nbproject/project.properties
ide/db.drivers/src/org/netbeans/modules/db/drivers/Bundle.properties
ide/db.drivers/src/org/netbeans/modules/db/drivers/PostgreSQLDriver.xml
ide/db.drivers/src/org/netbeans/modules/db/drivers/postgresql.xml

Notes:
- Support for large update counts (JDBC 4.2)
- 23 Bug Fixes
- 9 New Features
[JDBC PostgreSQL Web Page](https://jdbc.postgresql.org/)
[Release Notes](https://github.com/pgjdbc/pgjdbc/blob/master/CHANGELOG.md)

[NETBEANS-3907] - Update JDBC PostgreSQL from 42.2.8 to 42.2.10

---

.travis.yml

Add more webcommon modules in Travis config

[TRAVIS] Add more webcommon modules in Travis config

---

java/java.project.ui/nbproject/project.xml
java/java.project.ui/src/org/netbeans/spi/java/project/support/ui/CreateClassAndCopy.java

This PR supports copying raw java text from anywhere(inside or outside of Netbeans) and pasting directly to a package to create a new class automatically. Copied text should have a valid syntax and should start with a **public class** followed by class name.

[NETBEANS-3986] Creating New Class On Pasting Class Text

---

ide/notifications/src/org/netbeans/modules/notifications/Bundle.properties

Add module long description for notifications module

Notifications module long description

---

java/maven/src/org/netbeans/modules/maven/newproject/MavenWizardIterator.java

See [archetypes project](https://github.com/errael/javafx-maven-archetypes) for documentation and details. The maven artifact referenced from this PR is in maven central (stating the obvious?).

[NETBEANS-3730] Use NewProject JavaFX archetypes tailored for NetBeans

---

java/maven/src/org/netbeans/modules/maven/execute/MavenCommandLineExecutor.java

default to true if lookup impossible to get.

NETBEANS-4028 NETBEANS-3738 better check of null case

---

platform/libs.flatlaf/external/binaries-list
platform/libs.flatlaf/external/flatlaf-0.28-license.txt
platform/libs.flatlaf/nbproject/project.properties
platform/libs.flatlaf/nbproject/project.xml

FlatLaf 0.27 change log:
https://github.com/JFormDesigner/FlatLaf/releases/tag/0.27
FlatLaf 0.28 change log:
https://github.com/JFormDesigner/FlatLaf/releases/tag/0.28

[NETBEANS-3428] Update FlatLaf from 0.26 to 0.28

---

platform/core.windows/src/org/netbeans/core/windows/options/LafPanel.java

see [NETBEANS-3942](https://issues.apache.org/jira/browse/NETBEANS-3942?focusedCommentId=17061871&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17061871) for details

[NETBEANS-3942] FlatLaf: fix editor annotations when switching LaF and switching color profile too on restart

---

platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java

fix for https://issues.apache.org/jira/browse/NETBEANS-3879
and https://issues.apache.org/jira/browse/NETBEANS-3943

[NETBEANS-3879] FlatLaf: fix Ctrl+PAGE_UP and Ctrl+PAGE_DOWN

---

platform/api.search/src/org/netbeans/modules/search/ui/ResultsOutlineCellRenderer.java

https://issues.apache.org/jira/browse/NETBEANS-3941
tested also with FlatLaf Light, Windows, Nimbus, Metal, Dark Metal and Dark Nimbus LaFs

[NETBEANS-3941] FlatLaf dark: fixed text color of additional columns in "Search Results" view

---

java/maven/src/org/netbeans/modules/maven/newproject/MavenWizardIterator.java

The culmination of #2037 and #2036

Update JavaFX archetypes for recent JavaFX/maven PRs #2036,#2037

---

.travis.yml

Add more java modules to run tests in Travis config

[TRAVIS] Add java modules

---

ide/projectuiapi/src/org/netbeans/modules/project/uiapi/DefaultProjectOperationsImplementation.java

[NETBEANS-4119] Prevent NPE on Closing DefaultProjectOperationDialog

---

.travis.yml

Retry webcommon javascript2.jquery module

[TRAVIS] Retry webcommon javascript2.jquery module

---

java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/ClassPathProviderImpl.java

Without this, the OpenJDK tests do not see classes added in the OpenJDK sources, but rather the runtime platform classes (this is particularly problem for classes for java.base).
Erik, it would be awesome if this could be considered for 12.0.

Use current platform for OpenJDK tests

---

platform/core.multitabs/src/org/netbeans/core/multitabs/impl/TabDataRenderer.java
platform/core.multitabs/src/org/netbeans/core/multitabs/impl/TabTableUI.java
platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties

Addition to PR #1865.
Adds the missing hover effect to multi-tabs for FlatLaf.
Other LaFs are not changed. Tested with Metal, Nimbus and Windows LaF.

[NETBEANS-3428] FlatLaf: hover in multi-tabs

---

java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/WhereUsedPanel.form
java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/WhereUsedPanel.java

https://issues.apache.org/jira/browse/NETBEANS-3881

[NETBEANS-3881] FlatLaf: "Find Usages" dialog: fixed warning overlaps Scope combobox

---

ide/options.editor/nbproject/project.xml
ide/options.editor/src/org/netbeans/modules/options/colors/ColorModel.java
platform/core.windows/apichanges.xml
platform/core.windows/manifest.mf
platform/core.windows/nbproject/project.xml
platform/core.windows/src/org/netbeans/core/windows/options/LafPanel.java
platform/core.windows/src/org/netbeans/core/windows/options/spi/PreferredColorProfileSupport.java

A non-hack implementation of #2031

[NETBEANS-4039] Added SPI for Preferred Color Profile Changes

---

.travis.yml

Enable Travis cache https://docs.travis-ci.com/user/caching/

[TRAVIS] Enable Travis cache

---

.travis.yml

Add travis_retry for `java/refactoring.java` module that fails randomly

[Travis] Retry java/refactoring.java module tests

---

.travis.yml
enterprise/websvc.websvcapi/nbproject/project.properties
enterprise/websvc.wsstackapi/nbproject/project.properties

Run tests for enterprise modules.
- enterprise/websvc.websvcapi
- enterprise/websvc.wsstackapi

[TRAVIS] Run tests for enterprise modules

---

java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertTextBlockToStringTest.java
java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java

If a TextBlock was present in a function call, previous hint does not converts it to String. This PR is to fix (and test)that bug.

[NETBEANS-3311] Convert TextBlock to String, Function call parameter fix

---

platform/core.output2/test/unit/src/org/netbeans/core/output2/LifecycleTest.java

test NbIOProvider.resetIO(io) as used by api.io InputOutput.reset()

---

java/java.hints/src/org/netbeans/modules/java/hints/errors/DifferentCaseKindsFix.java
java/java.hints/src/org/netbeans/modules/java/hints/errors/Utilities.java
java/java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertSwitchToRuleSwitch.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/DifferentCaseKindsFixTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertSwitchToRuleSwitchTest.java

Code Modifications of Hints and their tests related to Switch Expressions, As Switch Expressions finalised in JDK14,

[NETBEANS-4283]:Code Modifications related to finalisation of Switch Expressions in JDK14

---

ergonomics/ide.ergonomics/nbproject/project.properties
ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/ConfigurationPanel.java
ergonomics/ide.ergonomics/test/unit/src/org/netbeans/modules/ide/ergonomics/fod/ConfigurationPanelTest.java
ergonomics/ide.ergonomics/test/unit/src/org/netbeans/modules/ide/ergonomics/fod/TestBundle.properties
ergonomics/ide.ergonomics/test/unit/src/org/netbeans/modules/ide/ergonomics/fod/TestBundle2.properties

Fix feature dialog: https://issues.apache.org/jira/browse/NETBEANS-4029

[NETBEANS-4029] Fix feature dialog

---

.travis.yml
ide/xml.schema.completion/nbproject/project.properties

Change Travis config to run ide/xml.schema.completion module tests

[TRAVIS] Run xml.schema.completion tests

---

apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/AddOSGiParamToNbmPluginConfiguration.java
apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/MavenNbModuleImpl.java
apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NBMNativeMWI.java
apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NetBeansRunParamsIDEChecker.java
apisupport/maven.apisupport/test/unit/src/org/netbeans/modules/maven/apisupport/NBMNativeMWITest.java

Query the maven repository to get the latest version of nbm-maven-plugin. If this fails for some reason it will use the hard coded version.

[NETBEANSINFRA-6] Dynamically get the latest nbm-maven-plugin version

---

ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlLexer.java
ide/languages.yaml/test/unit/data/testfiles/issue_NETBEANS-4370_1.yaml.txt
ide/languages.yaml/test/unit/data/testfiles/issue_NETBEANS-4370_1.yaml.txt.tokens.txt
ide/languages.yaml/test/unit/data/testfiles/issue_NETBEANS-4370_2.yaml.txt
ide/languages.yaml/test/unit/data/testfiles/issue_NETBEANS-4370_2.yaml.txt.tokens.txt
ide/languages.yaml/test/unit/src/org/netbeans/modules/languages/yaml/YamlLexerTest.java

I think this one would be a candidate for 12.0.1 patch release, if we would have that.

[NETBEANS-4370] Fix Yaml Lexer in-mustache EOF fails

---

.github/workflows/main.yml
platform/core.network/test/unit/src/org/netbeans/core/network/utils/hname/win/HostnameUtilsWinTest.java

Use GitHub actions to build and run tests in Windows.
https://lists.apache.org/thread.html/rc3a7ad290b004557c69d8cac7f5bd4825ca3d230b626641a8565164b%40%3Cdev.netbeans.apache.org%3E

Continuous build in Windows

---

platform/openide.awt/src/org/openide/awt/NotificationCategoryFactory.java
platform/openide.awt/test/unit/src/org/openide/awt/NotificationCategoryFactoryTest.java
platform/openide.awt/test/unit/src/org/openide/awt/NotificationDisplayerTest.java
platform/openide.awt/test/unit/src/org/openide/awt/SimpleNotificationDisplayerTest.java
platform/openide.awt/test/unit/src/org/openide/awt/TestBundle.properties

Add test for SimpleNotificationDisplayer implementation and resolve some warnings.

Test SimpleNotificationDisplayer implementation

---

ide/notifications/src/org/netbeans/modules/notifications/filter/CategoryFilter.java
ide/notifications/src/org/netbeans/modules/notifications/filter/FilterRepository.java
ide/notifications/src/org/netbeans/modules/notifications/filter/NotificationFilter.java
ide/notifications/test/unit/src/org/netbeans/modules/notifications/NotificationSettingsTest.java
ide/notifications/test/unit/src/org/netbeans/modules/notifications/StatusLineElementTest.java
ide/notifications/test/unit/src/org/netbeans/modules/notifications/filter/FilterRepositoryTest.java
ide/notifications/test/unit/src/org/netbeans/modules/notifications/filter/NotificationFilterTest.java
ide/notifications/test/unit/src/org/netbeans/modules/notifications/filter/TestPreferences.java
ide/notifications/test/unit/src/org/netbeans/modules/notifications/filter/TitleFilterTest.java
ide/notifications/test/unit/src/org/netbeans/modules/notifications/filter/UtilTest.java

Add tests in notifications module

Add tests in notifications module

---

php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/CodeSnifferOptionsPanel.java

GitHub page contains more installation options and issue tracker.
https://issues.apache.org/jira/browse/NETBEANS-4338

[NETBEANS-4338] Code Sniffer - updated link to homepage

---

java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertTextBlockToStringTest.java

Convert TextBlock to String, Function call parameter fix test case fix

[NETBEANS-3311] Convert TextBlock to String, Test Case Fix

---

harness/apisupport.harness/build.xml
java/lib.jshell.agent/nbproject/project.properties
nbbuild/templates/common.xml
platform/libs.asm/external/asm-8.0.1-license.txt
platform/libs.asm/external/binaries-list
platform/libs.asm/manifest.mf
platform/libs.asm/nbproject/project.properties
platform/libs.asm/nbproject/project.xml

Notes:
- New V15 constant
- Experimental support for PermittedSubtypes and RecordComponent
- Bug fixes (317885): SKIP_DEBUG now skips MethodParameters attributes
- Java 14 support (RecordComponent)
- Bug fixes (317896): Performance degradation when using dynamic constants as a static paramet to another InDy/ConDy
- Bug fixes (317898): ASM 8 does not support writing of empty records
[ASM Web Page](https://asm.ow2.io/index.html)
[Release Notes](https://asm.ow2.io/versions.html)

[NETBEANS-4310] - Update asm from 7.2 to 8.0.1

---

.github/workflows/main.yml
nbbuild/build.xml
nbbuild/test/unit/src/org/netbeans/nbbuild/TestBase.java

Use a GitHub action to run Netbeans Build System (Ant Tasks) tests.

Test Netbeans build system (Ant Tasks)

---

php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocNoDocMethod.html
php/php.editor/test/unit/data/testfiles/completion/documentation/issue215408.php.testIssue215408.html

https://issues.apache.org/jira/browse/NETBEANS-3413
Fixes code completion tests.

[NETBEANS-3413] Implicit inheritance of PHPDoc descriptions - fixed tests

---

platform/masterfs.nio2/nbproject/project.properties
platform/masterfs.nio2/src/org/netbeans/modules/masterfs/watcher/nio2/NioNotifier.java

[NETBEANS-2790] Do not throw ClosedWatchServiceException on Shutdown.

---

.travis.yml
php/languages.neon/test/unit/data/testfiles/actions/toggleComment/toggle_01.neon
php/languages.neon/test/unit/data/testfiles/actions/toggleComment/toggle_01.neon.toggleComment
php/languages.neon/test/unit/data/testfiles/actions/toggleComment/toggle_02.neon
php/languages.neon/test/unit/data/testfiles/actions/toggleComment/toggle_02.neon.toggleComment
php/languages.neon/test/unit/data/testfiles/actions/toggleComment/toggle_03.neon
php/languages.neon/test/unit/data/testfiles/actions/toggleComment/toggle_03.neon.toggleComment
php/languages.neon/test/unit/data/testfiles/actions/toggleComment/toggle_04.neon
php/languages.neon/test/unit/data/testfiles/actions/toggleComment/toggle_04.neon.toggleComment
php/languages.neon/test/unit/src/org/netbeans/modules/languages/neon/actions/ToggleCommentActionTest.java

Test data were created from scratch
Enabled tests in Travis CI

Fix tests for Neon language

---

.github/workflows/main.yml

List of tested modules is based on Travis configuration.
Commented tests are failing everywhere or fail only on Windows.

Added tests for PHP modules in Windows build

---

ide/html.editor/src/org/netbeans/modules/html/editor/completion/AttrValuesCompletion.java
ide/html.editor/src/org/netbeans/modules/html/editor/embedding/JsEmbeddingProvider.java
ide/html.editor/test/unit/src/org/netbeans/modules/html/editor/embedding/JsEmbeddingProviderTest.java
webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/embedding/JsEmbeddingProvider.java

https://issues.apache.org/jira/browse/NETBEANS-4434

[NETBEANS-4434] Code Completion doesn't work when script type attribute value is "module"

---

.github/workflows/main.yml
php/php.dbgp/test/unit/src/org/netbeans/modules/php/dbgp/DebuggerTest.java
php/php.dbgp/test/unit/src/org/netbeans/modules/php/dbgp/URIMapperTest.java

https://issues.apache.org/jira/browse/NETBEANS-4487
- Fixed mapper tests.
- Disabled always failing part of debugger test.
- Enabled tests in Github Actions.

[NETBEANS-4487] Fixed tests for PHP Debugger on Windows

---

.github/workflows/main.yml
.travis.yml
php/php.symfony/test/unit/data/symfony-commands.xml
php/php.symfony/test/unit/src/org/netbeans/modules/php/symfony/commands/SymfonyCommandsXmlParserTest.java

https://issues.apache.org/jira/browse/NETBEANS-4498
- Added file `symfony-commands.xml`.
- Updated test.
- Enabled tests in Travis and Github Actions.

[NETBEANS-4498] Fixed unit tests for Symfony

---

java/java.source.base/src/org/netbeans/api/java/source/TreeMaker.java
java/java.source.base/src/org/netbeans/modules/java/source/TreeShims.java

https://issues.apache.org/jira/browse/NETBEANS-4400

[NETBEANS-4400] Added support for renaming RECORD name using refactoring

---

.github/workflows/main.yml
.travis.yml
ide/csl.api/test/unit/src/org/netbeans/modules/csl/api/test/CslTestBase.java
php/php.latte/test/unit/data/testfiles/indent/testRealFile_01.latte
php/php.latte/test/unit/data/testfiles/indent/testRealFile_01.latte.formatted
php/php.latte/test/unit/data/testfiles/indent/testRealFile_02.latte
php/php.latte/test/unit/data/testfiles/indent/testRealFile_02.latte.formatted
php/php.latte/test/unit/data/testfiles/indent/testRealFile_03.latte
php/php.latte/test/unit/data/testfiles/indent/testRealFile_03.latte.formatted
php/php.latte/test/unit/data/testfiles/indent/testRealFile_04.latte
php/php.latte/test/unit/data/testfiles/indent/testRealFile_04.latte.formatted
php/php.latte/test/unit/src/org/netbeans/modules/php/latte/indent/LatteIndenterTestBase.java
php/php.latte/test/unit/src/org/netbeans/modules/php/latte/parser/LatteParserErrorTest.java

https://issues.apache.org/jira/browse/NETBEANS-4486
- Deleted tests related to files removed during donation from Oracle.
- Deleted unused files.
- Added real-life files to indentation tests (see #751 and #720).
- testRealFile_01.latte
- Source: https://github.com/obrejla/Eciovni/blob/master/src/Eciovni.latte
- License: New BSD License https://github.com/obrejla/Eciovni/blob/master/license.txt
- testRealFile_02.latte was recreated
- testRealFile_03.latte
- Source: https://github.com/obrejla/Pollie/blob/master/OndrejBrejla/Pollie/PollieForm.latte
- License: New BSD License https://github.com/obrejla/Pollie/blob/master/license.txt
- testRealFile_04.latte
- Source: https://github.com/obrejla/Pollie/blob/master/OndrejBrejla/Pollie/PollieLink.latte
- License: New BSD License …

[NETBEANS-4486] Fixed unit tests for Latte Templates

---

.github/workflows/main.yml
.travis.yml
php/php.smarty/test/unit/src/org/netbeans/modules/php/smarty/editor/completion/TplCompletionQueryTest.java

https://issues.apache.org/jira/browse/NETBEANS-4501
- Updated code completion tests - definition data were not donated.
- Enabled tests in Travis and Github Actions.

[NETBEANS-4501] Fixed tests for Smarty Framework

---

.github/workflows/main.yml
php/php.code.analysis/test/unit/data/phpstan/phpstan-log-netbeans-3022-without-workdir.xml
php/php.code.analysis/test/unit/src/org/netbeans/modules/php/analysis/parsers/PHPStanReportParserTest.java

https://issues.apache.org/jira/browse/NETBEANS-4478
Paths in log file have to be system-dependent for tests to work as
expected.

[NETBEANS-4478] Fixed tests for PHP Code analysis on Windows

---

apisupport/apisupport.wizards/src/org/netbeans/modules/apisupport/project/ui/wizard/action/DataModel.java

It seems the ActionReferenceModel needs to be public after all. I do not know why that worked for me before that in #2154

[NETBEANS-4438] Fix new action wizard

---

.github/workflows/main.yml
.travis.yml

https://issues.apache.org/jira/browse/NETBEANS-4487
Moved PHP tests on Linux from Travis to GitHub Actions.

[NETBEANS-4487] Move PHP tests on Linux to GitHub Actions

---

platform/openide.util.lookup/manifest.mf
platform/openide.util.lookup/src/org/openide/util/lookup/implspi/ActiveQueue.java
platform/openide.util.lookup/test/unit/src/org/openide/util/lookup/implspi/ActiveQueueWithSecurityManagerTest.java
platform/openide.util/manifest.mf
platform/openide.util/src/org/openide/util/TimedSoftReference.java
platform/openide.util/test/unit/src/org/openide/util/NbBundleWithSecurityManager.properties
platform/openide.util/test/unit/src/org/openide/util/NbBundleWithSecurityManagerTest.java

Backport of #2196 to release 12.0.x branch.

Make Lookup & NbBundle usable in a sandbox

---

nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ConfigureProxy.java

Backporting #2210 to release 12.0.x branch.

Make configureproxy idenpotent when invoked multiple times

---

java/gradle.test/src/org/netbeans/modules/gradle/test/GradleTestcase.java

[NETBEANS-4528] Setting classname for GradleTestcase

---

README.md

Add GitHub actions budge in the README file

GitHub actions badge

---

php/php.code.analysis/src/org/netbeans/modules/php/analysis/MessDetectorAnalyzerImpl.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/MessDetectorParams.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/MessDetector.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptions.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/Bundle.properties
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/MessDetectorCustomizerPanel.form
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/MessDetectorCustomizerPanel.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/Bundle.properties
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/MessDetectorOptionsPanel.form
php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/MessDetectorOptionsPanel.java

https://issues.apache.org/jira/browse/NETBEANS-4340
Added CLI options to PHP Mess Detector configuration.
Before:
After:

[NETBEANS-4340] Added PHP Mess Detector options configuration

---

php/php.code.analysis/src/org/netbeans/modules/php/analysis/ImportantFilesImpl.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/CodeSniffer.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/CodingStandardsFixer.java
php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/PHPStan.java

https://issues.apache.org/jira/browse/NETBEANS-4571
Added standard configuration files of PHP static analysis tools to Important Files.

[NETBEANS-4571] Show PHP Static Analysis configuration files in Important Files

---

extide/gradle/apichanges.xml
extide/gradle/manifest.mf
extide/gradle/nbproject/org-netbeans-modules-gradle.sig
extide/gradle/nbproject/project.xml
extide/gradle/src/org/netbeans/modules/gradle/GradleProjectProblemProvider.java
extide/gradle/src/org/netbeans/modules/gradle/api/execute/RunUtils.java
extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
extide/gradle/src/org/netbeans/modules/gradle/spi/execute/GradleJavaPlatformProvider.java
java/gradle.java/nbproject/project.xml
java/gradle.java/src/org/netbeans/modules/gradle/java/GradleJavaDebuggerImpl.java
java/gradle.java/src/org/netbeans/modules/gradle/java/GradleJavaProjectProblemProvider.java
java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/AbstractGradleScriptClassPath.java
java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/BootClassPathImpl.java
java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ScriptClassPathProvider.java
java/gradle.java/src/org/netbeans/modules/gradle/java/customizer/CompileOptionsPanel.java
java/gradle.java/src/org/netbeans/modules/gradle/java/execute/GradleJavaPlatformProviderImpl.java
java/gradle.java/src/org/netbeans/modules/gradle/java/execute/JavaRunUtils.java
java/gradle.java/src/org/netbeans/modules/gradle/java/nodes/BootCPNodeFactory.java
java/gradle.kit/nbproject/project.xml

Well, this one shall fix the java.platform dependency issue for #2252. Unfortunately it means that the API compatibility is broken. Please review this and point at the weak spots!

Removed java.platform dependency from the Gradle Projects module

---

ide/html.editor/src/org/netbeans/modules/html/editor/HtmlCodeTemplateFilter.java
ide/html.editor/src/org/netbeans/modules/html/editor/resources/codetemplates.xml
ide/html.editor/src/org/netbeans/modules/html/editor/resources/layer.xml

https://issues.apache.org/jira/browse/NETBEANS-4576
I added new templates. They may not be preferred by someone. (Maybe, preferred templates depends on users.) However, users can edit them.
If we should not add new templates(added by me), I'll just revert them. Thanks!

[NETBEANS-4576] Support for code template completion for HTML

---

ide/html.lexer/src/org/netbeans/api/html/lexer/HTMLTokenId.java

https://issues.apache.org/jira/browse/NETBEANS-4621
- This is related to the https://issues.apache.org/jira/browse/NETBEANS-4434

[NETBEANS-4621] Color highlighting is not correct when script type attribute value is "module"

---

java/gradle.java/src/org/netbeans/modules/gradle/java/queries/FileBuiltQueryImpl.java
java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceForBinary.java

Well @jlahoda please check these. My test project is OpenJFX with this change it seems the main inter sub-project dependencies started to work. Though during the indexing there are some assertions and NPE-s thrown.
It seems I still need to make the test sourceset dependencies work.

[NETBEANS-4636] Make FileBuilt and SourceForBinary work with Modular Gradle Java Projects

---

java/java.editor/src/org/netbeans/modules/editor/java/GoToSupport.java
java/java.hints/src/org/netbeans/modules/java/hints/errors/AddParameterOrLocalFix.java
java/java.hints/src/org/netbeans/modules/java/hints/errors/CreateElement.java
java/java.hints/src/org/netbeans/modules/java/hints/errors/ImportClass.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/AddParameterOrLocalFixTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/CreateElementTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/infrastructure/ErrorHintsTestBase.java
java/java.lsp.server/build.xml
java/java.lsp.server/nbproject/project.xml
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Server.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/text/TextDocumentServiceImpl.java
java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/ServerTest.java
java/java.lsp.server/vscode/package-lock.json
java/java.lsp.server/vscode/package.json
java/java.lsp.server/vscode/src/VerifyJDK14.java
java/java.lsp.server/vscode/src/extension.ts
java/java.sourceui/manifest.mf
java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementOpen.java

-proper start/end positions for definition lookup
-fixing problems with zip file caches
-waiting for shutdown command, instead of looping forever after starting the server
-fixes "Add new variable" and "Add import" should work
-JDK 14 is a requirement for the server (does not work well on JDK 11)
-improvements to code completion

Improvements to the Java LSP Server

---

php/php.editor/src/org/netbeans/modules/php/editor/csl/InstantRenamerImpl.java

https://issues.apache.org/jira/browse/NETBEANS-4604
Adds ability to rename private constant without displaying Rename dialog.

[NETBEANS-4604] PHP - instant rename of private constant

---

nbbuild/antsrc/org/netbeans/nbbuild/MakeUpdateDesc.java

Make updates.xml reference the DTDs from netbeans.apache.org

---

java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/DebianJavaPlatformDetector.java
java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/SdkManJavaPlatformDetector.java
java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/resources/layer.xml

Just make the life a bit easier...

[NETBEANS-4735] Detect JDK-s installed with SDKMan and Debian

---

enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/resources/Bundle.properties
enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/resources/spring-webmvc-3.0.xml

Currently is:
Spring Web MVC 3.2.7
Should be:
Spring Web MVC 3.2.18
- Checked the files:

[NETBEANS-4776] - Fix Spring Web MVC 3.2.x wrong version

---

cnd/cnd.discovery/src/org/netbeans/modules/cnd/discovery/layer.xml
cnd/cnd.makeproject/samples_src/freeway/arrow_left.bitmap
cnd/cnd.makeproject/samples_src/freeway/arrow_over.bitmap
cnd/cnd.makeproject/samples_src/freeway/arrow_right.bitmap
cnd/cnd.makeproject/samples_src/freeway/arrow_up.bitmap
cnd/cnd.makeproject/samples_src/freeway/traffic.icon
cnd/cnd.makeproject/samples_src/freeway/traffic.mask
cnd/cnd.makeproject/samples_src/hello/bar.f
cnd/cnd.makeproject/samples_src/hello/foo.f
cnd/cnd.makeproject/samples_src/helloqt/HelloForm.cpp
cnd/cnd.makeproject/samples_src/helloqt/newmain.cpp
cnd/cnd.makeproject/samples_src/lexyacc/token.l
cnd/cnd.makeproject/samples_src/lexyacc/token.y
cnd/cnd.makeproject/samples_src/sample.cookbook.txt
cnd/cnd.toolchain/src/org/netbeans/modules/cnd/toolchain/resources/toolchaindefinition/GNU_debugger.xml
contrib/cnd.diagnostics.clank/nbproject/project.xml

Updated the copyright in the XML files.
Updated the copyright in the C,C++ files.
Updated the copyright in the .h files.

[NETBEANS-4744] - update RAT license exceptions

---

contrib/groovy.grailsproject/test/unit/data/projects/completion/ivysettings.xml
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/GlassFishV3.xml
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/GlassFishV4.xml
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/GlassFishV4_1.xml
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/GlassFishV5.xml
enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/GlassFishV5_1_0.xml
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/config/PayaraV3.xml
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/config/PayaraV4.xml
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/config/PayaraV5.xml
enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/config/PayaraV5_192.xml
ide/o.apache.xml.resolver/external/README-xml-resolver-1.2-netbeans.patch
java/maven.indexer/external/indexer-core-6.0.0-license.txt
java/maven.indexer/test/unit/src/org/netbeans/modules/maven/indexer/api/RepositoryPreferencesTest.java
java/maven.model/test/unit/src/sample.pom
java/maven/src/org/netbeans/modules/maven/api/ModelUtils.java
java/maven/test/unit/src/org/netbeans/modules/maven/api/ModelUtilsTest.java
java/maven/test/unit/src/org/netbeans/modules/maven/classpath/CPExtenderTest.java
nbbuild/antsrc/org/netbeans/nbbuild/ParseProjectXml.java

This is just a simple search and replace in the whole project, may fix some tests/ functionalities.

Switch http://repo1.maven.org to HTTPS

---

java/java.editor/test/unit/src/org/netbeans/modules/java/editor/imports/ComputeImportsTest.java
java/java.source.base/src/org/netbeans/api/java/source/ElementHandle.java
java/java.source.base/src/org/netbeans/api/java/source/GeneratorUtilities.java
java/java.source.base/src/org/netbeans/modules/java/source/usages/DocumentUtil.java

https://issues.apache.org/jira/browse/NETBEANS-4062

[NETBEANS-4062] Fixed issue : import RECORD from other package hint

---

java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java
java/java.completion/test/unit/data/goldenfiles/org/netbeans/modules/java/completion/JavaCompletionTaskTest/1.8/recordVariableSuggestion.pass
java/java.completion/test/unit/data/org/netbeans/modules/java/completion/data/Records.java
java/java.completion/test/unit/src/org/netbeans/modules/java/completion/JavaCompletionTask114FeaturesTest.java

https://issues.apache.org/jira/browse/NETBEANS-4805

[NETBEANS-4805] Fixed Naming suggestions of Record variable/identifier

---

nbbuild/antsrc/org/netbeans/nbbuild/CustomJavac.java

Reverts apache/netbeans#2371
This one actually depends on the code in #2337 CI is failing. reverting the merge.

Revert "Fixing nbjdk.home behavior broken by #2337 "

---

enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/resources/Bundle.properties
enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/resources/spring-webmvc-5.0.xml

[NETBEANS-4820] - Fix Spring Web MVC 5.2.9 integration

---

extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java
extide/gradle/src/org/netbeans/modules/gradle/options/SettingsPanel.java

Added hashCode() and equals() mathod to GradleDistribution

[NETBEANS-4823] Fixed CCE in Gradle Options Dialog.

---

cpplite/cpplite.kit/release/VERSION.txt
enterprise/j2ee.kit/nbproject/project.xml
enterprise/javaee.api/src/org/netbeans/modules/javaee/api/javaee-endorsed-api-6.0.xml
enterprise/payara.eecommon/src/org/netbeans/modules/payara/eecommon/dd/loader/PayaraDescriptorDataObject.java
groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/resources/layer.xml
ide/gsf.testrunner/src/org/netbeans/modules/gsf/testrunner/TestCreatorProviderProcessor.java
java/java.project.ui/src/org/netbeans/modules/java/project/ui/NewJavaFileWizardIterator.java
nbbuild/cluster.properties
platform/core.startup/src/org/netbeans/core/startup/ConsistencyVerifier.java
platform/o.n.core/test/qa-functional/src/org/netbeans/core/validation/ValidateLayerConsistencyTest.java
platform/o.n.core/test/qa-functional/src/org/netbeans/core/validation/ValidateModulesTest.java
platform/o.n.core/test/qa-functional/src/org/netbeans/core/validation/ValidateNbinstTest.java
platform/openide.filesystems/src/org/openide/filesystems/Ordering.java
platform/openide.filesystems/test/unit/src/org/openide/filesystems/OrderingTest.java
webcommon/javascript2.jquery/test/unit/src/org/netbeans/modules/javascript2/jquery/JQueryCodeCompletionSelectorsTest.java

This PR collects several code improvements for both tests and the implementation itself. The goal is to make `commit-validation` work again. For easier review separated from 'simple' order change / label fixes which are coming in a subsequent PR.
See explanation comments inline.

commit-validation fixes: code improvements

---

java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
java/java.source.base/test/unit/src/org/netbeans/modules/java/source/save/FormatingTest.java

https://issues.apache.org/jira/browse/NETBEANS-4682

[NETBEANS-4682] : Fixed Record Formatting issue with use of annotation

---

.github/workflows/main.yml
.travis.yml
enterprise/web.core/build.xml
extide/gradle/build.xml
ide/editor.settings.storage/arch.xml
ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/fontscolors/ColoringStorage.java
ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/fontscolors/EditorFontsColors-1_2.dtd
ide/editor.settings.storage/test/unit/src/org/netbeans/modules/editor/settings/storage/fonts-and-colors-6.xml
ide/xml.retriever/test/unit/src/org/netbeans/modules/xml/retriever/catalog/impl/CatalogModelImplTest.java
nbbuild/installer/components/products/nb-all/src/org/netbeans/installer/products/nb/all/Bundle.properties
platform/core.network/test/unit/src/org/netbeans/core/network/proxy/pac/PacEngineTest.java

Apache gitbox web is more than flaky lately causing many jobs fail when retrieving the netbeansrelease.json.
What about to use it's github mirror in our Travis CI tests?

Use GitHub for netbeansrelease.json in Travis

---

.github/workflows/main.yml
.travis.yml
platform/o.n.core/test/qa-functional/src/org/netbeans/core/validation/ValidateLayerConsistencyTest.java

Finally ... all necessary changes should be in.

Enable commit-validation

---

ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/ParagraphViewChildren.java
java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/SemanticHighlighterBase.java
java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/TokenList.java
java/java.editor.base/test/unit/src/org/netbeans/modules/java/editor/base/semantic/DetectorTest.java

Adds types after method invocation for chained method invocations.
See:

Show types for chained method invocations.

---

java/gradle.java/src/org/netbeans/modules/gradle/java/api/output/LocationOpener.java

[NETBEANS-4842] Bugfix: 'Go To Source' broken with JUnit5 and Gradle

---

.github/workflows/main.yml
platform/applemenu/src/org/netbeans/modules/applemenu/layer.xml

Run `commit-validation` as part of MacOS build in github actions.

Run commit-validation on apple.

---

java/java.completion/src/org/netbeans/modules/java/completion/JavaDocumentationTask.java

https://issues.apache.org/jira/browse/NETBEANS-4864

[NETBEANS-4864] - Fixed JavaDoc listing for class-type RECORD on auto completion

---

extide/gradle/apichanges.xml
extide/gradle/src/org/netbeans/modules/gradle/BulkModelRetriever.java
extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectFactory.java
extide/gradle/src/org/netbeans/modules/gradle/nodes/BuildScriptsNode.java
extide/gradle/src/org/netbeans/modules/gradle/nodes/SubProjectsNode.java
extide/gradle/src/org/netbeans/modules/gradle/queries/Info.java
extide/gradle/src/org/netbeans/modules/gradle/spi/GradleFiles.java
extide/gradle/test/unit/src/org/netbeans/modules/gradle/NbGradleProjectFactoryTest.java
extide/gradle/test/unit/src/org/netbeans/modules/gradle/spi/GradleFilesTest.java

It looks like something like this:

[NETBEANS-2644] Gradle buildSrc projects are recognized and displayed in the Build Scripts node

---

ide/spi.debugger.ui/apichanges.xml
ide/spi.debugger.ui/manifest.mf
ide/spi.debugger.ui/src/org/netbeans/spi/debugger/ui/DebuggingView.java
java/debugger.jpda.truffle/nbproject/project.xml
java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/models/DebuggingTruffleTreeModel.java
java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/models/DebuggingViewTruffleSupport.java
java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/models/TruffleDVFrame.java
java/debugger.jpda.ui/nbproject/project.xml
java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/debugging/DebuggingViewSupportImpl.java
java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/debugging/JPDADVFrame.java
java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/debugging/JPDADVThread.java

`DebuggingView` extended with API for frames.

Representation of frames in DebuggingView API.

---

java/java.hints/test/unit/src/org/netbeans/modules/java/hints/AssignResultToVariableTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/HideFieldByVarTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/CreateMethodTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/ErrorHintsTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/VarCompDeclarationTest.java
java/java.hints/test/unit/src/org/netbeans/modules/java/hints/introduce/IntroduceHintTest.java

https://issues.apache.org/jira/browse/NETBEANS-4836

[NETBEANS-4836] - Added @RandomlyFailure annotation to timeout and mostly failure test cases of java.hints module

---

platform/core.ui/src/org/netbeans/core/ui/options/filetypes/IgnoredFilesPreferences.java
platform/masterfs/src/org/netbeans/modules/masterfs/GlobalVisibilityQueryImpl.java

Revert "NETBEANS-4893 - Added node_modules and bower_components to the option"

---

platform/o.n.swing.outline/src/org/netbeans/swing/etable/ETableHeader.java

Reverts apache/netbeans#2435
Please file a new PR with this change, that would fix the email requirements. Also it would be nice if the new PR would be one commit only.

Revert "NETBEANS-4533 : Netbeans 4533 chinese char problem table header"

---

platform/openide.filesystems/src/org/openide/filesystems/JarArchiveRootProvider.java
platform/openide.filesystems/test/unit/src/org/openide/filesystems/IsArchiveFileTest.java

Well, this one will be required to javafx internal classpath resolution to work.

[NETBEANS-4895] Improve archive detection of a non-existent file.

---

java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/breakpoints/impl/TruffleBreakpointsHandler.java
java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/JPDATruffleAccessor.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/breakpoints/NbBreakpoint.java
java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/breakpoints/NbBreakpointsRequestHandler.java

* Validation of breakpoints in the VS Code extension.
* Validation and location update of Truffle breakpoints.

Validation and update of breakpoints

---

java/java.project.ui/src/org/netbeans/spi/java/project/support/ui/CreateJavaClassFileFromClipboard.java
java/java.project.ui/src/org/netbeans/spi/java/project/support/ui/PackageViewChildren.java
java/java.project.ui/test/unit/src/org/netbeans/spi/java/project/support/ui/PackageViewTest.java

https://issues.apache.org/jira/browse/NETBEANS-3986

[NETBEANS-3986] Create new Class/Interface/Enum when copy-paste raw text

---

extide/gradle/src/org/netbeans/modules/gradle/nodes/BuildScriptsNode.java
extide/gradle/src/org/netbeans/modules/gradle/nodes/GradleProjectNode.java
extide/gradle/src/org/netbeans/modules/gradle/spi/GradleFiles.java
extide/gradle/test/unit/src/org/netbeans/modules/gradle/nodes/BuildScriptsNodeTest.java

Also added unit test for the Build Scripts node.

[NETBEANS-4900] Added back the node for settings.gradle

---

platform/openide.filesystems.nb/arch.xml
platform/openide.filesystems.nb/nbproject/project.properties

This module only contains the apichanges.xml file and it doesn't show a description in the [Netbeans APIs overview.](https://bits.netbeans.org/12.1/javadoc/)

Add arch.xml for platform/openide.filesystems.nb module

---

ide/editor.breadcrumbs/nbproject/project.xml
ide/lsp.client/manifest.mf
ide/lsp.client/nbproject/project.xml
ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/Utils.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/BreadcrumbsImpl.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandler.java
ide/lsp.client/src/org/netbeans/modules/lsp/client/layer.xml

(This is an LSP-only client change.)

Adding breadcrumbs for LSP languages.

---

java/maven/src/org/netbeans/modules/maven/runjar/RunJarPrereqChecker.java
java/maven/test/unit/src/org/netbeans/modules/maven/runjar/RunJarPrereqCheckerTest.java

Before asking the user, we try to read main class configuration, or property from pom.xml.

Read mainClass configuration or property. 

---

java/java.editor/src/org/netbeans/modules/editor/java/JavaCodeTemplateFilter.java
java/java.editor/test/unit/src/org/netbeans/modules/editor/java/JavaCodeTemplateProcessorTest.java

Solve the problem of code templates not working in loops in the Java editor.
See issue: https://issues.apache.org/jira/browse/NETBEANS-3588

[NETBEANS-3588] Code Templates not working in Java Editor in for loops

---

java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/JPDATruffleAccessor.java

Breakpoints into GraalVM scripts are submitted through a call into `JPDATruffleAccessor`, which uses Truffle debugger APIs to install the breakpoint. It does not need to notify about breakpoint resolution synchronously, as it returns the breakpoint object resolved already, when it occurs synchronously. The `breakpointResolvedAccess` is for asynchronous resolution only.

Prevent from a deadlock between debugger and debuggee when breakpoint is resolved right during it's submission.

---

java/gradle.htmlui/nbproject/project.xml
java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/GradleArchetype.java
java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/HtmlJavaApplicationProjectWizard.java
java/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/layer.xml
java/gradle.htmlui/test/unit/src/org/netbeans/modules/gradle/htmlui/CreateArchetypeTest.java

Well, I've made the template copy straight. It loads all three projects (root, web, desktop) also the Demo.java into the editor.

[NETBEANS-4938] Fixed Gradle Java Frontend Application generation

---

extide/gradle/src/org/netbeans/modules/gradle/newproject/ProjectAttributesPanelVisual.java

[NETBEANS-4944] Create New Gradle Projects with Wrapper by Default

---

java/gradle.java/src/org/netbeans/modules/gradle/java/customizer/Bundle.properties
java/gradle.java/src/org/netbeans/modules/gradle/java/customizer/CompileOptionsPanel.form
java/gradle.java/src/org/netbeans/modules/gradle/java/customizer/CompileOptionsPanel.java

Well, this is a trivial change, it should have happened by NetBeans 11.0

[NETBEANS-4916] Removed Non-Inplemented COS Settings from Gradle Project UI

---

ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandler.java

I've accidentally broken than in https://github.com/apache/netbeans/commit/a171d50fc5946b7bf79149ff07573d27485f34a1 - the registrations were accidentally dropped.

Fixing registration of Mark occurences and Breadcrumbs for lsp.client.

---

java/java.lsp.server/vscode/src/nbcode.ts

Sváťa has just asked: where can I find `messages.log`? The answer is `$HOME/.config/Code/User/globalStorage/jlahoda.apache-netbeans-java/userdir/var/log/messages.log` but the problem is - the log isn't there!
Turns out I have deleted the `--userdir` option in one of the refactorings. This PR fixes that.

Where is the NbCode userdir?

---

.travis.yml
ide/xml.schema.completion/nbproject/project.properties
ide/xml.schema.completion/nbproject/project.xml
ide/xml.schema.completion/src/org/netbeans/modules/xml/schema/completion/RuntimeCatalogModel.java
ide/xml.schema.completion/src/org/netbeans/modules/xml/schema/completion/util/CompletionContextImpl.java
ide/xml.schema.completion/test/unit/src/org/netbeans/modules/xml/schema/completion/CatalogAbstractElementTest.java
ide/xml.schema.completion/test/unit/src/org/netbeans/modules/xml/schema/completion/resources/CatalogAbstractElementChild.xsd
ide/xml.schema.completion/test/unit/src/org/netbeans/modules/xml/schema/completion/resources/CatalogAbstractElementCompletion.xml
ide/xml.schema.completion/test/unit/src/org/netbeans/modules/xml/schema/completion/resources/CatalogAbstractElementParent.xsd
ide/xml.schema.completion/test/unit/src/org/netbeans/modules/xml/schema/completion/resources/CompletionContext.xml
ide/xml.schema.completion/test/unit/src/org/netbeans/modules/xml/schema/completion/util/CompletionContextImplTest.java

Please see individual commits for explanations.

Bugfix xml schema completion (Fix catalog handling and tests)

---

groovy/groovy.support/src/org/netbeans/modules/groovy/support/api/GroovySources.java
java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/GradleSourcesImpl.java
java/gradle.java/src/org/netbeans/modules/gradle/java/nodes/SourcesNodeFactory.java

I still have to check if this one works well with Maven as well. Are we going to support Ant based Groovy projects any more?

[NETBEANS-4975] Every Groovy SG is a Java SG, but not every Java SG is a Groovy SG
