apache/netbeans

- editor.lib/src/org/netbeans/editor/BaseKit.java
- checked Rat report: modified license header in src/org/netbeans/editor/BaseKit.java
> [NETBEANS-54] Module Review editor.lib

- editor.lib2/src/org/netbeans/api/editor/caret/package.html
- No external libraries.
- checked Rat report: modified license header in src/org/netbeans/api/editor/caret/package.html
> [NETBEANS-54] Module Review editor.lib2

- bugtracking/apichanges.xml
- bugtracking/test/unit/src/org/netbeans/modules/bugtracking/TestIssue.java
- bugtracking/test/unit/src/org/netbeans/modules/bugtracking/TestQuery.java
- checked Rat report: update license header in apichanges.xml, TestIssue.java, and TestQuery. ignore *.form and org-netbeans-modules-bugtracking.sig
> [NETBEANS-54] Module Review bugtracking

- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/ConformingNamespacesDocument.xml
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/DTD.dtd
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/Entity.ent
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/InvalidDTD.dtd
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/InvalidDocument.xml
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/InvalidEntity.ent
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/NamespacesDocument.xml
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/ValidDocument.xml
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/ValidNamespacesDocument.xml
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/WellformedDocument.xml
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/XMLSchema.xsd
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/doc.dtd
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/doc.xml
- api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/data/doc2xhtml.xsl
- checked Rat report: add the license header to test/unit/src/org/netbeans/spi/xml/cookies/data/*, ignore org-netbeans-api-xml-ui.sig
> [NETBEANS-54] Module Review api.xml.ui

- db.sql.visualeditor/external/binaries-list
- external library javacc is only used at build time and is not
distributed with netbeans
- modified binaries-list to point to maven coordinates
- checked Rat report; missing headers added, ignored *.form 
(see central problems)
> [NETBEANS-54] Module Review db.sql.visualeditor

- nbbuild/build.xml
Now excluding the following automatically generated files from the rat report:
- **/nbproject/build-impl.xml
- **/nbproject/jfx-impl.xml
- **/nbproject/genfiles.properties
> Updating the rat exclusion list

- api.xml/test/unit/src/org/netbeans/api/xml/parsers/data/Entity.dtd
- api.xml/test/unit/src/org/netbeans/api/xml/parsers/data/RelativeTest.dtd
- checked Rat report: add the license header in two *.dtd. ignore three package-list[1] files, org-netbeans-api-xml.sig
- A unit test fails even if the license header is not added. (ClassNotFoundException: org.apache.crimson.parser.XMLReaderImpl)
[1] http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#JSWOR663
> [NETBEANS-54] Module Review api.xml

- derby/etc/sample.sql
- external binary is binary form of etc/sample.sql (not on maven)
- checked Rat report; missing header added to etc/sample.sql, ignored
binaries-list and *.form files (see central problems)
- replacing the bundled binary is tracked by [NETBEANS-74]
> [NETBEANS-54] Module Review derby

- lexer.nbbridge/test/unit/src/org/netbeans/modules/lexer/nbbridge/test/testLayer.xml
- No external libraries.
- One test failed: org.netbeans.modules.lexer.nbbridge.test.MimeLookupLanguageProv
- Added license to a single layer.xml test file (not strictly required).
> [NETBEANS-54] Module Review lexer.nbbridge

- libs.antlr3.runtime/external/binaries-list
* Updated external/binaries-list with Maven coordinates for antlr3 runtime (BSD)
* No other problems found.
> [NETBEANS-54] Module Review libs.antlr3.runtime

- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/fonts-and-colors-2.xml
- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/fonts-and-colors-3.xml
- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/fonts-and-colors-4.xml
- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/fonts-and-colors-5.xml
- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/fonts-and-colors-all-languages.xml
- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/fonts-and-colors.xml
- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/key-bindings.xml
- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/preferences.xml
- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/preferences/preferences-all-languages.xml
- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/preferences/preferences-testA-1.xml
- editor.settings.lib/test/unit/src/org/netbeans/modules/editor/settings/storage/preferences/preferences-testA-2.xml
- checked Rat report and found 11 XML files that don't have any license info defined on them. Added the license text on to them .
- After adding the text , Recompiled the code and ran the rat report again and Made sure that these files are fixed in the rat report .
- skimmed through the module, did not notice any additional problems
> [NETBEANS-54] Module Review editor.settings.lib - Added Apache License

- editor.errorstripe/src/org/netbeans/modules/editor/errorstripe/resources/layer.xml
- editor.errorstripe/test/unit/src/org/netbeans/modules/editor/errorstripe/test-layer.xml
- No external binaries.
- Updated licenses in two layer.xml files.
- Two unit tests failed: org.netbeans.modules.editor.errorstripe.AnnotationViewDataImplTest org.netbeans.modules.editor.errorstripe.AnnotationViewTest
- No additional problems found.
> [NETBEANS-54] Module Review editor.errorstripe

- csl.api/src/org/netbeans/modules/csl/editor/semantic/Bundle.properties
- checked Rat report: update the license header in csl.api/src/org/netbeans/modules/csl/editor/semantic/Bundle.properties. ignore manifest.mf and *.txt
> [NETBEANS-54] Module Review csl.api

- project.libraries/src/org/netbeans/api/project/libraries/package.html
- checked Rat report: update the license header in package.html. ignore uispec.txt, org-netbeans-modules-project-libraries.sig, and manifest.mf
> [NETBEANS-54] Module Review project.libraries

- libs.antlr4.runtime/external/binaries-list
- Updated maven coordinates for antlr 4.5.3 (BSD)
- No other problems found.
> [NETBEANS-54] Module Review libs.antlr4.runtime

- libs.bytelist/external/binaries-list
- Updated Maven coordinates for jruby's bytelist 0.1 (LGPL 2.1)
> [NETBEANS-54] Module Review libs.bytelist

- libs.ini4j/external/binaries-list
- Updated maven coordinates for ini4j 0.5.1 (Apache 2)
- All license headers are correct.
> [NETBEANS-54] Module Review libs.ini4j

- hibernate/src/org/netbeans/modules/hibernate/hqleditor/HQLEditorController.java
- hibernate/src/org/netbeans/modules/hibernate/refactoring/HibernateRefactoringUtil.java
- hibernate/src/org/netbeans/modules/hibernate/resources/HibernateUtil.javax
- hibernate/test/unit/src/org/netbeans/modules/hibernate/completion/resources/Person.hbm.xml
- hibernate/test/unit/src/org/netbeans/modules/hibernate/completion/resources/hibernate.cfg.xml
- hibernate/test/unit/src/org/netbeans/modules/hibernate/hyperlink/resources/Person.hbm.xml
- hibernate/test/unit/src/org/netbeans/modules/hibernate/hyperlink/resources/hibernate.cfg.xml
- external binary contains DTDs for Hibernate 3.0 configuration files
- changed license headers for files reported by Rat
- replacing the bundled binary is tracked by https://issues.apache.org/jira/browse/NETBEANS-79
> [NETBEANS-54] Module Review hibernate

- j2ee.metadata/apichanges.xml
- j2ee.metadata/test/unit/data/projects/JavaApplication1/nbproject/project.xml
- checked Rat report, added license header on apichanges.xml and changed header on /test/unit/data/projects/JavaApplication1/nbproject/project.xml from Oracle to Apache, others looked ok. Ignored problems to be resolved centrally.
- skimmed module and did not see any other issues
> [NETBEANS-54] Module Review j2ee.metadata

- .gitignore
- .travis.yml
- spring.beans/nbproject/project.xml
- spring.beans/test/unit/src/org/netbeans/modules/spring/api/beans/model/CommonAnnotationTestCase.java
- websvc.saas.api/nbproject/project.xml
- websvc.saas.codegen/nbproject/project.xml
I've noticed that there are some modules with too wide test dependencies. Such modules cannot be compiled. I am adding the test compilation (not execution for now) into `.travis.yml` to make sure we always have compilable tests.
I'll fix the modules with non-compilable tests to compile.
> Not all tests can be compiled right now. Compile them as part of travis run.

- o.apache.ws.commons.util/external/binaries-list
- Updated maven coordinates for Apache WS Commons Util (Apache 2.0)
- No notice found at http://svn.apache.org/viewvc/webservices/commons/trunk/modules/util/
- No other licensing issues found (manifest.mf to be handled centrally)
> [NETBEANS-54] Module Review o.apache.ws.commons.util

- libs.cglib/external/binaries-list
- libs.cglib/external/cglib-2.2-notice.txt
- Updated maven coordinates for the external binary.
- Added cglib-2.2 license from https://github.com/cglib/cglib
> [NETBEANS-54] Module Review libs.cglib

- o.eclipse.jgit/external/binaries-list
- o.eclipse.jgit/nbproject/project.properties
- o.eclipse.jgit/nbproject/project.xml
Had to change from using a jar called:
org.eclipse.jgit-3.6.2.201501210735-r-nosignature.jar to
org.eclipse.jgit-3.6.2.201501210735-r.jar
Since the previous one wasnt in maven.  NO NOTICE file added - Not sure it needs one since its under EDL - see https://github.com/eclipse/jgit/tree/v3.6.2.201501210735-r
> [NETBEANS-54] Module Review o.eclipse.jgit

- o.eclipse.jgit.java7/external/binaries-list
- o.eclipse.jgit.java7/nbproject/project.properties
- o.eclipse.jgit.java7/nbproject/project.xml
Had to change from using a jar called:
org.eclipse.jgit.java7-3.6.2.201501210735-r-nosignature.jar to
org.eclipse.jgit.java7-3.6.2.201501210735-r.jar
Since the previous one wasn't in maven.  NO NOTICE file added - Not sure it needs one since its under EDL - see https://github.com/eclipse/jgit/tree/v3.6.2.201501210735-r
> [NETBEANS-54] Module Review org.eclipse.jgit.java7

- o.apache.xmlrpc/external/binaries-list
- Added three entries in binaries-list with Maven coordinates for Apache XMLRPC 3.0 files (Apache 2.0)
- No notice files found at https://svn.apache.org/repos/asf/webservices/archive/xmlrpc/tags/XMLRPC_3_0/
> [NETBEANS-54] Module Review o.apache.xmlrpc

- libs.jvyamlb/external/binaries-list
- libs.jvyamlb/external/jvyamlb-0.2.6-license.txt
- libs.jvyamlb/nbproject/project.properties
- libs.jvyamlb/nbproject/project.xml
- Version 0.2.7 is not available in maven.central
- Downgraded to 0.2.6 to see how it behaves in travis build
- See issue #82 https://issues.apache.org/jira/browse/NETBEANS-82
> [NETBEANS-54] Module Review libs.jvyamlb

- extexecution.process/external/binaries-list
- Updated coordinates for libpam4j from Maven central (MIT)
- winp binary (MIT) in this directory is a patched version from the one in Maven. Added maven coordinates as a comment in binaries-list.
- libpam4j (MIT) is not available in Maven central, the homepage was hosted in kenai, now gone.
- Unit tests passing.
> [NETBEANS-54] Module Review extexecution.process

- dlight.nativeexecution/external/exechlp-1.0-license.txt
- dlight.nativeexecution/tools/buildall.sh
- dlight.nativeexecution/tools/killall/make/Makefile.gmake
- dlight.nativeexecution/tools/killall/make/Makefile.make
- dlight.nativeexecution/tools/killall/make/line
- dlight.nativeexecution/tools/pty/.hgignore
- dlight.nativeexecution/tools/pty/make/Makefile.gmake
- dlight.nativeexecution/tools/pty/make/Makefile.make
- dlight.nativeexecution/tools/pty/make/line
- dlight.nativeexecution/tools/unbuffer/make/Makefile.gmake
- dlight.nativeexecution/tools/unbuffer/make/Makefile.make
- dlight.nativeexecution/tools/unbuffer/make/line
- The external/exechlp-1.0.zip binary is generated by the scripts and code in tools/
- So I'm assuming this is an Apache 2.0 license as well.
- Added license headers to makefiles and different scripts
- No other licensing headers required.
- Test org.netbeans.modules.nativeexecution.api.util.ConnectionManagerTest failed in my box.
> [NETBEANS-54] Module Review dlight.nativeexecution

- autoupdate.services/test/unit/src/org/netbeans/modules/autoupdate/services/VerifyFileTestDisabled.java
Renamed TestFile VerifyFileTest to VerifyFileTestDisabled to exclude it from TestSuite run as it is dependent on resource foo.jks deleted during Apache Code Donation . We can't comment out only the failing test methods as test class should have at least one test method and in this case all test methods have issues.
> Renamed VerifyFileTest class  to exclude it from TestSuite run as it depends on deleted resource

- maven.embedder/external/binaries-list
- maven.embedder/external/jdom-1.0-notice.txt
- binaries-list updated to use maven coords
- added notice for jdom license (please double check)
- did not add notice for maven-dependency-tree (already apache licensed)
> [NETBEANS-54] Module Review maven.embedder

- nbbuild/nbproject/project.xml
- nbbuild/test/unit/src/org/netbeans/nbbuild/CheckLicenseAnt.xml
- nbbuild/test/unit/src/org/netbeans/nbbuild/CheckLicenseHtmlExample.xml
- nbbuild/test/unit/src/org/netbeans/nbbuild/CheckLicensePropertiesExample.properties
- nbbuild/test/unit/src/org/netbeans/nbbuild/CheckLicenseTest.java
- nbbuild/test/unit/src/org/netbeans/nbbuild/CheckLicenseXmlExample.xml
- nbbuild/test/unit/src/org/netbeans/nbbuild/ModuleListParserTest.java
- nbbuild/test/unit/src/org/netbeans/nbbuild/extlibs/DownloadBinariesTest.java
As indicated in the comment to PR #130 (cache external binaries
also for downloads from maven central) [1] the change to the
Netbeans Build System done in [2] and the changes to license headers
caused unittests in nbbuild to fail. These changesets fix this.
[1] https://github.com/apache/incubator-netbeans/pull/130#issuecomment-336243405
[2] https://github.com/matthiasblaesing/incubator-netbeans/commit/5c773910524b785e35c5b45d73c5ac42534669d3
> Fix unittests for Netbeans Build system

- nbbuild/javadoctools/template.xml
Note that the `useexternalfile` attribute has been on the Ant `javadoc-exec-files` target (see line 298) for at least the last 10 years, but for some reason it wasn't on the `javadoc-exec-packages` target. Now fixed.
Description for `useexternalfile` attribute is [here](https://ant.apache.org/manual/Tasks/javadoc.html).
> [NETBEANS-94] Cannot build NB Javadocs on Windows

- .gitignore
- debugger.jpda.ui/test/qa-functional/data/debugTestProject/src/examples/advanced/README.txt
- checked Rat report: add the license header to genfiles.properties and README.txt
> [NETBEANS-54] Module Review debugger.jpda.ui

- net.java.html.boot.fx/external/binaries-list
- net.java.html.boot.fx/nbproject/project.properties
- net.java.html.boot.script/external/binaries-list
- net.java.html.boot.script/nbproject/project.properties
- net.java.html.boot/external/binaries-list
- net.java.html.boot/nbproject/project.properties
- net.java.html.geo/external/binaries-list
- net.java.html.geo/nbproject/project.properties
- net.java.html.json/external/binaries-list
- net.java.html.json/nbproject/project.properties
- net.java.html.sound/external/binaries-list
- net.java.html.sound/nbproject/project.properties
- net.java.html/external/binaries-list
- net.java.html/nbproject/project.properties
- o.n.html.ko4j/external/binaries-list
- o.n.html.ko4j/nbproject/project.properties
- o.n.html.xhr4j/external/binaries-list
- o.n.html.xhr4j/nbproject/project.properties
Updating the Maven co-ordinates of HTML/Java API to point to recently released 1.5 bits. The 1.5 bits are licensed under Apache license - e.g. NetBeans Platform will remove dependency on old `CDDL` version and replace it with proper Apache one.
> Using HTML/Java 1.5 release bits

- swing.validation/arch.xml
- swing.validation/external/ValidationAPI-license.txt
- swing.validation/nbproject/project.properties
Project includes `ValidationAPI.jar` (CDDL licensed), originally hosted on Kenai, now GitHub.
Changed dead references to Kenai to their equivalent GitHub coordinates.
Note:  Even if the `ValidationAPI.jar`  file is using the `org.netbeans`  package namespace it is not part of the grant, as far as I can tell. Therefore it is still CDDL licensed.
Should anyone want to recreate the binary from source: The binary uses Kenai SVN commit no as the version number. Since the project was transferred to GitHub with full commit history, it is possible to find the equivalent point in time in GitHub, namely end-of-day Nov 17, 2011. The URL is noted in `ValidationAPI-license.txt` file.
> [NETBEANS-54] Module Review swing.validation

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java
Currently for maven external dependencies, the build is downloading them from the internet each time it is missing in the checkout. The proposal here is to cache them in the $HOME/.hgexternalbinaries, as other binaries are cached.
(Jarda proposed caching them directly in .m2, but it is not clear what structures Maven expects there, so seems safer to cache just in .hgexternalbinaries.)
> Cache external binaries downloaded from maven in NetBeans' cache.

- libs.osgi/build.xml
- libs.osgi/external/binaries-list
- libs.osgi/external/osgi-5.0-license.txt
Maven central does not hold the original netbeans artifact 
osgi.cmpn-4.2, but a superset of that: 
<dependency>
<groupId>org.osgi</groupId>
<artifactId>org.osgi.compendium</artifactId>
<version>4.2.0</version>
</dependency>
That artifact holds not only the compiled binaries, but also the
java sources in a subfolder "OSGI-OPT". To get the original netbeans
file, the jar is repacked and the folder is stripped. The resulting
zip is not identical to the original binary, but the difference is
in the zip structure, after expanding the original contents and the
new file are identical.
This PR is a followup for #104 which introduced a maven coordinate,
that can't be satisfied from maven central.
There are newer osgi compendium jar on maven central and it looks
as if at least 4.3.1 would also …
> [NETBEANS-54] Module Review libs.osgi (followup)

- openide.util/src/org/openide/util/EditableProperties.java
- openide.util/test/unit/src/org/openide/util/EditablePropertiesTest.java
- project.ant/test/unit/src/org/netbeans/spi/project/support/ant/data/build-impl.xsl
- project.ant/test/unit/src/org/netbeans/spi/project/support/ant/data/build.xsl
- project.ant/test/unit/src/org/netbeans/spi/project/support/ant/data/build2.xsl
- project.ant/test/unit/src/org/netbeans/spi/project/support/ant/data/extension1.xml
- project.ant/test/unit/src/org/netbeans/spi/project/support/ant/data/global.properties
- project.ant/test/unit/src/org/netbeans/spi/project/support/ant/data/private.properties
- project.ant/test/unit/src/org/netbeans/spi/project/support/ant/data/private.xml
- project.ant/test/unit/src/org/netbeans/spi/project/support/ant/data/project-modified.xml
The first commit updates the file in project.ant with the correct
license headers. There are two main changesets:
- the first changeset adds the headers
- the second changeset fixes the failing unittests in project.ant which
show a problem in openide.util.
> Module review project ant

- nbbuild/antsrc/org/netbeans/nbbuild/RatReportTask.java
The RatReportTask is checking that external binaries are downloaded using maven coordinates. While In principle that check is not bad, I'd like to remove it. There's a couple reasons for that:
1. I don't think it is a hard-error at this time to download binaries not using maven coordinates.
2. we have the ant verify-libs-and-licenses working again (for platform at least). This is checking consistency between the license files, binaries and nbbuild/licenses. If at some point it should become a hard error to not download from maven, then verify-libs-and-licenses seems like a better place to do the check.
3. I think it would be cleaner if RatReportTask would just convert the rat report to junit test files, and not do any checks itself.
The main driving force behind this patch is that I am …
> Disabling check for maven coordinates in RatReportTask.

- o.eclipse.core.runtime/external/binaries-list
- o.eclipse.core.runtime/nbproject/project.properties
- o.eclipse.core.runtime/nbproject/project.xml
- Added maven coordinates for the binary. 
- No other licensing issues found (but for manifest.mf, to be handled centrally).
>  [NETBEANS-54] Module Review o.eclipse.core.runtime

- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/3_2/html32.dtd
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/3_2/lat1.ent
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_0/HTMLlat1.ent
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_0/HTMLspecial.ent
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_0/HTMLsymbol.ent
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_0/frameset.dtd
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_0/loose.dtd
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_0/strict.dtd
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_01/HTMLlat1.ent
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_01/HTMLspecial.ent
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_01/HTMLsymbol.ent
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_01/frameset.dtd
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_01/loose.dtd
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/4_01/strict.dtd
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/xhtml/xhtml-lat1.ent
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/xhtml/xhtml-special.ent
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/xhtml/xhtml-symbol.ent
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/xhtml/xhtml1-frameset.dtd
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/xhtml/xhtml1-strict.dtd
- html.editor/src/org/netbeans/modules/html/editor/resources/DTDs/xhtml/xhtml1-transitional.dtd
- html.editor/src/org/netbeans/modules/html/editor/resources/layer.xml
- nbbuild/build.xml
The DTDs and entity definitions were removed when netbeans was donated
to the apache foundation. The biggest part of the change adds verbatim
copies of the orignal files. As the DTDs did not hold a license, the
information is added to the files.
The other changes:
- layer.xml: Uncomment disabled integration section for DTDs
- build.xml: Ensure the ISO license of the entity definitions
is recognised
It is assumed, that these files fall under the
https://www.apache.org/legal/resolved.html#category-b
definition of:
> For small amounts of source that is directly consumed by the ASF product
> at runtime in source form, and for which that source is unmodified and
> unlikely to be changed anyway (say, by virtue of being specified by a
> standard), inclusion of appropriately labeled source is …
> [NETBEANS-114] Reintegrate HTML 3.2-XHTML 1.0 DTDs and entity definitions

- nbbuild/build.xml
- welcome/src/org/netbeans/modules/welcome/resources/layer.xml
- welcome/src/org/netbeans/modules/welcome/resources/rss-0_91.dtd
This change undoes the removal of the DTD file done by Oracle as preparation for the donation. The change fixes NETBEANS-112.
It is assumed that Oracle removed the file from the donation as it wasn't theirs to donate.
See:
http://hg.netbeans.org/releases/rev/66633aaa2811
http://hg.netbeans.org/releases/rev/00ff3249694f
**About license for DTD file:**
Netscape transferred the RSS 0.91 specification to the RSS Advisory Board in January 2008. From their website I cannot figure out what the license is for the 0.91 DTD file, but newer versions of the RSS spec seem to be published under the _Creative Commons Attribution/Share Alike 2.0_ license. However, this conclusion cannot be made for the 0.91 spec. No license header has thus been added to the DTD file, only a note about from where it has …
> [NETBEANS-112] Re-integrate DTD for RSS 0.91 feed

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/VerifyLibsAndLicenses.java
Hopefully will avoid false reports in verify-libs-and-licenses when the default encoding is not UTF-8.
> Ensuring license texts are read using UTF-8 encoding.

- javahelp/external/jhall-2.0_05-license.txt
- javahelp/manifest.mf
- javahelp/nbproject/project.properties
- javahelp/nbproject/project.xml
- javahelp/src/org/netbeans/modules/javahelp/HelpCtxProcessor.java
- javahelp/src/org/netbeans/modules/javahelp/HelpSetProcessor.java
This avoids the runtime dependency on JavaHelp (compile-time dependency remains). Help is not working as a result. Can be partially workarounded by saying:
--cp:a <path-to-jhall.jar>
on command line, but there are still bugs with that (as JavaHelp is loaded by a classloader that does not see NetBeans classes).
> Not copying the JavaHelp library into the binary.

- o.n.upgrader/src/org/netbeans/upgrade/systemoptions/systemoptionsimport
Add the license header to systemoptionsimport.
This file is used in `o.n.upgrader/src/org/netbeans/upgrade/systemoptions/Importer.java` (see the following). I think that it can be added the license header because it is used as a properties file. 
https://github.com/apache/incubator-netbeans/blob/7fd9f79a84d02b6122a4089b9b65fc7f8ca3dcb7/o.n.upgrader/src/org/netbeans/upgrade/systemoptions/Importer.java#L33
https://github.com/apache/incubator-netbeans/blob/7fd9f79a84d02b6122a4089b9b65fc7f8ca3dcb7/o.n.upgrader/src/org/netbeans/upgrade/systemoptions/Importer.java#L85-L94
> [NETBEANS-54] Module Review o.n.upgrader

- db.dataview/src/org/netbeans/modules/db/dataview/table/ResultSetJXTable.java
- db.dataview/src/org/netbeans/modules/db/dataview/table/ResultSetTableCellEditor.java
There are two issues:
- the BooleanCellRenderer used in the ResultSetJXTable should not be used
directly, but only via the ResultSetCellRenderer. The ResultSetCellRenderer
adds special handling to correctly show NULL values (and so protects the
BooleanCellRenderer from NULL values)
- The ResultSetTableCellEditor assumes, that if the input element is a
JCheckBox, the value is either NULL or a Boolean. This is not correct,
as empty string can be come in as a default value.
The solution is to check the type of the value only if the value is
a Boolean, it is used to set the current value.
The issue was introduced in #234
> [NETBEANS-68] Fix NULL handling after fix in 1d362fa77521762a9af99792620414086b868f76

- apisupport.harness/release/etc/app.conf
Explicit max and min heap size settings removed.
This file (changed in this PR) is the default `.conf` file your application will get when you create an application on top of NetBeans Platform.
See [NETBEANS-149](https://issues.apache.org/jira/browse/NETBEANS-149) for details.
> [NETBEANS-149] Max heap size removed

- .gitattributes
Adds a `.gitattributes` file to the repo. 
The purpose of the file is to ensure that we'll never get files into the repo with wrong line endings, at least for those file types explicitly mentioned in the `.gitattributes` file. These settings will override the user's own git settings.
It is deliberate that the file uses a whitelist, i.e. it only lists the file types where there's 100% certainty that they should always use Unix-style line endings. For file types _not_ explicitly mentioned in the `.gitattributes` file, git's behaviour will be as today.
> Add .gitattributes file to repo

- apisupport.ant/src/org/netbeans/modules/apisupport/project/resources/license-apache20-netbeans.txt
- Don't change "/*" to "/**".
see #282
> Fix the license header template for NetBeans modules

- libs.javacapi/external/binaries-list
- libs.javacimpl/external/binaries-list
Merging the new nb-javac built from the latest JDK9 sources.
> Merging recent changes in JDK9 javac into nb-javac.

- core.startup/src/org/netbeans/core/startup/Bundle.properties
- core.windows/src/org/netbeans/core/windows/view/ui/Bundle.properties
- ide.branding/core.startup/src/org/netbeans/core/startup/Bundle_nb.properties
- ide.branding/core.windows/src/org/netbeans/core/windows/view/ui/Bundle_nb.properties
The product name, i.e. 'NetBeans Platform' or 'NetBeans IDE', is changed to reflect the new Apache home, in a couple of locations. This is done to distinguish the product from the pre-Apache era.
These changes are expected to be permanent. As for any actual release, such release will be expected to brand these variables, e.g. insert the word "(incubating)" for releases done while in Apache incubating phase, etc. This is similar to the existing release process prior to NB9.
It doesn't make sense to change every occurrence of "NetBeans Platform" or "NetBeans IDE". It only makes sense in the most prominent locations, IMO. The ones I've chosen are outlined below.  There are a few other locations where I think it makes sense to change as well, but they are all related to the IDE's Installer, …
> [NETBEANS-71] Change product name

- nbbuild/build.xml
The test data of `autoupdate.services` did not get captured by the general exclude rule.
> added test data of autoupdate.services to rat exclude list

- jshell.support/test/unit/src/org/netbeans/modules/jshell/support/ContentParserTest.java
- jshell.support/test/unit/src/org/netbeans/modules/jshell/support/reploutput.txt
- jshell.support/test/unit/src/org/netbeans/modules/jshell/support/reploutput_golden.txt
- lib.jshell.agent/nbproject/project.properties
- libs.jshell.compile/external/binaries-list
- libs.jshell.compile/external/jshell-9-license.txt
- libs.jshell.compile/nbproject/project.xml
- nbbuild/build.xml
Incidentally, I was working on NETBEANS-191 while in parallel matthiasblaesing authored 2be2f4c62f814f02593cc04ae73ebc4fa7655fc7. I didn't sync mo fork timely, so I didn't notice the change before I started to generated the PR; sorry.
I've decided to merge the changes - licenses can be added to test data at expense of a small change to the test class. Less exceptions for rat checks.
The second part is the jar rename + license file update to include versions, to satisfy verify libs ant task.
> Javashell fixes

- nbbuild/javadoctools/template.xml
Two minor changes to Javadoc build. Not worthy of a JIRA issue, I thought.
The copyright notice at the footer of Javadoc is changed from Oracle to ASF. The new footer resembles what e.g. Apache Tomcat project uses. Here's how it will look now (enlarged):
Look at http://bits.netbeans.org/dev/javadoc/ for what it used to look like.
When links to standard JDK classes is used in the NB javadocs it will now point to JDK8 rather than JDK7. This means that links to classes/methods that have debuted in Java 8 will now actually work.
> Javadoc build changes

- nbbuild/cluster.properties
- subversion/nbproject/project.xml
- subversion/src/org/netbeans/modules/subversion/client/SvnClientFactory.java
- subversion/src/org/netbeans/modules/subversion/options/SvnOptionsController.java
Seems that SvnKit is under a license that does not match Apache requirements(?), so disabling the module here. There are other ways the IDE can work with subversion. Unfortunately, svnkit had some advantages, but hopefully we can work even without it.
> Excluding svnkit

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
Added some entries to "ignored-overlaps"
- javacc-3.2 (used at compile time in db.sql.visualeditor)
- commons-lang-2.6 (used by maven.embedder and o.apache.commons.lang,
both functionally different).
> Verify libs and licenses - duplicated binaries

- libs.bytelist/external/binaries-list
- libs.bytelist/external/jcodings-1.0.18-license.txt
- libs.bytelist/nbproject/project.properties
- libs.bytelist/nbproject/project.xml
- nbbuild/licenses/MIT-nocopyright
This solves issue #216
https://issues.apache.org/jira/browse/NETBEANS-216
We recently upgraded libs.bytelist to bytelist v1.0.15 due to unclear
licenses in previous versions. It seems bytelist v1.0.15 requires
jcodings v 1.0.18 (MIT), as per [1].
This adds the jcodings dependency. This is licensed as MIT, but
the license has not a copyright notice, so I added a MIT-COPYRIGHT in
nbbuild/licenses.
[1]
https://github.com/jruby/bytelist/blob/bytelist-1.0.15/pom.xml
[2]
https://raw.githubusercontent.com/jruby/jcodings/jcodings-1.0.18/LICENSE.txt
> Missing dependency in libs.bytelist

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/CreateLicenseSummary.java
- nbbuild/notice-stub.txt
- o.apache.commons.codec/external/commons-codec-1.3-notice.txt
- o.apache.commons.httpclient/external/commons-httpclient-3.1-notice.txt
- o.apache.commons.io/external/commons-io-1.4-notice.txt
- o.apache.commons.lang/external/commons-lang-2.6-notice.txt
- o.apache.commons.logging/external/commons-logging-1.1.1-notice.txt
- Added some missing notice files for some modules.
- Updated nbbuild/notice-stub.txt "preamble" to acknowledge previous copyright notices in the codebase.
- Updated build.xml and created CreateNoticeFile.java ant task to create the NOTICE file.
The NOTICE file depends on the build as follows:
- For source builds (binaryBuild="false") only the "preamble" and any "[module]/**notice.txt" are included in the NOTICE file.
- For binary builds (binaryBuild="true") the preamble, any "[module]/**notice.txt" and any "[module]/external/**notice.txt" files are included.
The list of modules to include depends on "nb.clusters.list" (if present) or "cluster.config.${cluster.config}.list". See "CreateNoticeFile.java" for the exact algorithm.
This task has to be reviewed. It seems to be working properly …
> NOTICE file

- libs.osgi/nbproject/project.properties
- libs.osgi/nbproject/project.xml
The changes introduced by commits 0f103bbcec20 and a1d379d1a118 were not complete. While the osgi.cmpn-4.2.jar was put into the distribution, the update_tracking information (made from manifest) had no such entry.  Applications built on top of the platform then lack the osgi.cmpn-4.2.jar (referenced from manifest) and fail on startup.
With this change, the osgi.cmpn-4.2.jar will disappear from platform/modules/ext, and org.osgi.compendium-4.2.0.jar will be distributed (and used bcs of change in project.xml propagated to MANIFEST).
> Updated references to osgi.cmpn-4.2.jar in project files, followup to NETBEANS-105

- schema2beans/src/org/netbeans/modules/schema2beansdev/xmlschema.xsd
- xml.catalog/src/org/netbeans/modules/xml/catalog/resources/Transform.xsd
These were removed in:
http://hg.netbeans.org/releases/rev/905ace65e3d3?revcount=1500
and there is no reason not to ship them (there are other w3c licensed files already in the repository)
> Readd removed XSD Schemata for XSLT and XML Schema

- nbbuild/javadoctools/apichanges.xsl
This PR add a possibility to link apichanges issue to Apache JIRA instance.
Assuming that jira instance for NetBeans will contains NETBEANS to check for difference with bugzilla issues.
if former issues are migrated to Apache JIRA the triage must be removed.
> NETBEANS-192 support jira issue in apichanges

- o.apache.xml.resolver/src/org/apache/xml/resolver/etc/catalog.dtd
- o.apache.xml.resolver/src/org/apache/xml/resolver/etc/catalog.rng
- o.apache.xml.resolver/src/org/apache/xml/resolver/etc/catalog.xsd
- xml.catalog/test/unit/src/org/netbeans/modules/xml/catalog/CatalogEntityResolverTest.java
When the o.apache.xml.resolver patching mechanism was reworked, the
grammar files were dropped, as they are not part of the o.apache.xml.resolver
sources.
This changeset readds them in the netbeans module itself.
> Readd missing XML catalogs in o.apache.xml.resolver

- jshell.support/src/org/netbeans/modules/jshell/env/JShellEnvironment.java
- jshell.support/src/org/netbeans/modules/jshell/j2se/JShellStartupExtender.java
- jshell.support/src/org/netbeans/modules/jshell/maven/MavenShellLauncher.java
- jshell.support/src/org/netbeans/modules/jshell/project/ShellProjectUtils.java
- jshell.support/src/org/netbeans/modules/jshell/support/ShellSession.java
The two methods ShellProjectUtils#launchVMOptions and compilerPathOptions
both return NULL if the project the JShell integration is invoked in
is not a modular project or does not export any modules.
The callers interate directly on the return value and for this case this
leads to a NullPointerException. The other methods of ShellProjectUtils
return an empty Collection and not NULL, this adjusts the behaviour of
the two methods launchVMOptions and compilerPathOptions to also return
an empty collection instead of NULL.
> [NETBEANS-194] Don't return NULL from ShellProjectUtils#launchVMOptions and compilerPathOptions

- java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java
- java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorkerTest.java
(This fixes just this single bug in the vanilla javac indexing, so more are likely to come in the future.)
> [NETBEANS-234] Fixing handling of broken generics in fields.

- updatecenters/src/org/netbeans/modules/updatecenters/resources/Bundle.properties
The temporary AUC on lahoda.info is not needed anymore.
> Restoring original update center.

- projectui/src/org/netbeans/modules/project/ui/groups/GroupOptionProcessor.java
Should be self-explanatory. Tested manually on a simple case with a couple of groups
```sh
ant tryme -Dtryme.arg.open='--open-group "…ID or name or substring…"'
```
since I could find no automated test for this comparable to `OpenCLITest`.
> Permit CLI --open-group to accept a substring of a group name as a convenience

- project.ant/src/org/netbeans/spi/project/support/ant/GlobFileBuiltQuery.java
@tstupka’s translation of `ErrorManager` in [98441f1](http://hg.netbeans.org/main/rev/98441f10031df437bfbae8a391e74aaeacb33933) was a bit off, resulting in log noise like
```
INFO [org.netbeans.spi.project.support.ant.GlobFileBuiltQuery]: out of date (target: 0 vs. source: 1,514,920,750,000): GFBQ.StatusImpl[/tmp/JavaApplication1/src/javaapplication1/C.java@df5b8838:6eeb6792 -> /tmp/JavaApplication1/build/classes/javaapplication1/C.class]
INFO [org.netbeans.spi.project.support.ant.GlobFileBuiltQuery]: isBuilt: false from GFBQ.StatusImpl[/tmp/JavaApplication1/src/javaapplication1/C.java@df5b8838:6eeb6792 -> /tmp/JavaApplication1/build/classes/javaapplication1/C.class]
```
Confusingly, `INFORMATIONAL` maps to different JUL levels depending on whether or not a throwable is included. (Seems …
> GlobFileBuiltQuery was logging things at INFO that were not meant to be

- xml.text/src/org/netbeans/modules/xml/text/completion/XMLCompletionQuery.java
- xml.text/test/unit/src/org/netbeans/modules/xml/text/completion/XMLCompletionQueryTest.java
- xml.text/test/unit/src/org/netbeans/modules/xml/text/completion/res/docResourceUnclosed.html
When the XMLCompletionQuery has to complete values (element content),
it also detects if the closing tag should be appended.
This decision is based on the the check if a matching closing tag is
found behind the input position.
The position is indirectly communicated by the TokenSequence passed to
the XMLCompletionQuery#shouldCloseTagLocked method. But before the
offset was queried, the token position was modified (movePrevious calls)
and so the wrong position was used for the check.
> [NETBEANS-250] Code-complete corrupts pom.xml when updating dependency version

- nbbuild/build.xml
`ant update` target is still calling `finish-build` in its body. Returning the `finish-build` target back and making it delegate to platform or nb one - depending on the build of platform or IDE.
> ant update was broken

- maven/src/org/netbeans/modules/maven/nodes/DependenciesNode.java
Avoid following error: java.lang.NoClassDefFoundError: com/sun/source/tree/DirectiveTree
at org.netbeans.modules.maven.nodes.DependenciesNode$DependenciesSet.<init>(:183)
at org.netbeans.modules.maven.nodes.DependenciesNodeFactory$NList.<init>(:57)
at org.netbeans.modules.maven.nodes.DependenciesNodeFactory.createNodes(:44)
at org.netbeans.spi.project.ui.support.NodeFactorySupport$DelegateChildren$1.run(:174)
> Making Maven projects usable without properly installed Java support.

- diff/test/unit/src/org/netbeans/modules/diff/builtin/provider/DiffTestFile1a.txt
- diff/test/unit/src/org/netbeans/modules/diff/builtin/provider/DiffTestFile1b.txt
- diff/test/unit/src/org/netbeans/modules/diff/builtin/provider/DiffTestFile1d.txt
Removing accidentally omitted ancient license on a test data to avoid confusion. Some how the ancient Sun Public License has escaped relicesing to CDDL (and GPLwCPex then), and thus it also escaped change of the license to Apache. Fixing it now.
> Removing ancient header from test data.

- core.netigso/src/org/netbeans/core/netigso/Netigso.java
- core.netigso/test/unit/src/org/netbeans/core/netigso/NetigsoLogTest.java
- core.netigso/test/unit/src/org/netbeans/core/netigso/NetigsoTest.java
The default log setting for Felix was to too verbose. On start the Felix printed lines like:
```log
DEBUG: WIRE: [124.0] osgi.wiring.package; (osgi.wiring.package=javax.annotation.processing) -> [0] 
DEBUG: WIRE: [124.0] osgi.wiring.package; (osgi.wiring.package=javax.lang.model) -> [0]
DEBUG: WIRE: [124.0] osgi.wiring.package; (osgi.wiring.package=javax.lang.model.element) -> [0] 
DEBUG: WIRE: [124.0] osgi.wiring.package; (osgi.wiring.package=javax.lang.model.type) -> [0] 
DEBUG: WIRE: [124.0] osgi.wiring.package; (osgi.wiring.package=javax.lang.model.util) -> [0] 
DEBUG: WIRE: [124.0] osgi.wiring.package; (osgi.wiring.package=javax.tools) -> [0]
```
this output is only printed by Felix when debug log level is on:
```java
boolean debugLog = m_felix.getLogger().getLogLevel() >= …
```
> Use logger level for felix.

- jshell.support/src/org/netbeans/lib/nbjshell/LaunchJDIAgent.java
- jshell.support/src/org/netbeans/modules/jshell/tool/JShellLauncher.java
I focused on how standard jshell vs. NB wrapper initiates the JDI to the jshell machine. It seems that JDK implementation explicitly obtains loopack address and passes it to JdiInitiator - so I did the same.
Note - **the feature works OK on Linux**, so I was not able to get JShell to fail. **Mac users should try** to clone this repo/branch, rebuilt jshell.support module and try it.
> NETBEANS-133: Use explicit loopback address instead of autoselect

- maven.graph/src/org/netbeans/modules/maven/graph/DependencyGraphTopComponent.java
- maven.graph/src/org/netbeans/modules/maven/graph/GraphConstructor.java
The GraphConstructor visitor adds nodes / creates Widgets when the traversal is leaving root node - at the end of the visiting process. Also scene initialization includes adding layers (= widgets) to the scene, which should be done in EDT as well.
I have moved the widget creation into EDT, so the visitor is first applied to the graph, and then in EDT cached data is translated into nodes/widgets.
> NETBEANS-324: Maven graph widgets created in EDT

- editor.htmlui/build.xml
- editor.htmlui/manifest.mf
- editor.htmlui/nbproject/project.properties
- editor.htmlui/nbproject/project.xml
- editor.htmlui/src/org/netbeans/modules/editor/htmlui/Bundle.properties
- editor.htmlui/src/org/netbeans/modules/editor/htmlui/JSEmbeddingProvider.java
- editor.htmlui/src/org/netbeans/modules/editor/htmlui/JSNI2JavaScriptBody.java
- editor.htmlui/test/unit/src/org/netbeans/modules/editor/htmlui/JSNI2JavaScriptBodyTest.java
- nbbuild/cluster.properties
My attempt to address [#206](https://issues.apache.org/jira/browse/NETBEANS-206):
* offer hints for convert JSNI syntax (courtesy of @jlahoda)
* render JavaScript syntax inside of `@JavaScriptBody`'s `body` string (courtesy of @tzezula)
> Supporting HTML/Java API/UI constructs in the editor

- debugger.jpda.projects/nbproject/project.xml
- debugger.jpda.projects/src/org/netbeans/modules/debugger/jpda/projects/ScanLocalVars.java
- debugger.jpda.projects/test/unit/src/org/netbeans/modules/debugger/jpda/projects/CodeSnippetCompilerTest.java
- java.source.base/src/org/netbeans/modules/java/source/JavaSourceUtilImpl.java
- java.source.base/src/org/netbeans/modules/java/source/indexing/APTUtils.java
- java.source.base/test/unit/src/org/netbeans/modules/java/source/JavaSourceUtilImplTest.java
-passing an URI to the created (memory) FileObject when compiling a class using JavaSourceUtilImpl to prevent exceptions
-improving type detection for watches (don't using Trees.getElement(...).getReturnType() and alike, but rather Trees.getTypeMirror(...), as the latter has generics instantiated, etc.)
(I'll ask tzezula and mentlicher to take a look as well.)
> [NETBEANS-253] Fixing watches with lambdas.

- applemenu/src/org/netbeans/modules/applemenu/NbApplicationAdapterJDK8.java
- applemenu/src/org/netbeans/modules/applemenu/NbApplicationAdapterJDK9.java
Fixes bug that prevents NetBeans from quitting on macOS if the user previously canceled a quit
Multiple issue about how pressing Cancel on the macOS 'Quit NetBeans' menu prevents the users from even quitting.
> https://netbeans.org/bugzilla/show_bug.cgi?id=268549
> https://netbeans.org/bugzilla/show_bug.cgi?id=271946
> https://netbeans.org/bugzilla/show_bug.cgi?id=269724
> (probably) https://netbeans.org/bugzilla/show_bug.cgi?id=247690
Brought to my attention by Marco Rossi on the users@ mailing list.
It's a workaround but it has low impact. We could also call all the time `response.cancelQuit()` since it might not impact anything when a `System.exit` arrives but it seems odd to call it all the time.
Awaiting feedback.
> Fixes bug that prevents NetBeans from quitting on macOS

- lib.profiler/build.xml
We have a problem. The first build of NetBeans produces wrong NBM files & also wrong content of `update_tracking` directory. To simulate that run (with pre-built NetBeans) following command:
```bash
lib.profiler$ rm -rf *; git checkout -f .; ant nbm; unzip -v build/org-netbeans-lib-profiler.nbm
```
then the resulting NBM files has just **49** entries! If you run the `nbm` target once again, you get more than hundred.
This PR is fixing that. Even when running on a clean `lib.profiler` directory, it generates NBM with enough files:
```bash
Archive:  build/org-netbeans-lib-profiler.nbm
Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
0  Stored        0   0% 2018-02-06 22:57 00000000  META-INF/
105  Defl:N       93 …
```
> Initial NBM of lib.profiler shall contain all libraries.

- netbinox/external/M20140115-0800.patch
- netbinox/external/binaries-list
- netbinox/external/org.eclipse.osgi_3.9.1.v20140110-1610-license.txt
- netbinox/external/rebuild-equinox.sh
- netbinox/nbproject/project.properties
- netbinox/nbproject/project.xml
- netbinox/test/unit/src/org/netbeans/modules/netbinox/CountingSecurityManager.java
Providing exact steps used to rebuild the Equinox JAR and renaming it to stress the fact it has been modified. Addresses bug https://issues.apache.org/jira/browse/LEGAL-361
> Providing exact steps used to rebuild the Equinox JAR

- editor.lib2/nbproject/project.xml
- editor.lib2/src/org/netbeans/modules/editor/lib2/EditorActionRegistrationProcessor.java
- editor.lib2/test/unit/src/org/netbeans/modules/editor/lib2/testactionsregistration/EditorActionRegistrationTest.java
Simple fix, slightly less simple test. The toolbar registration was placed into wrong folder, so the editor did not pick the action up at all.
> NETBEANS-357: corrected the target folder for toolbar link for action

- maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
This exception is raised from the maven-indexer.
maven-indexer supported two formats:
- legacy/zip: zipped lucene (v2.3) index files
- gz: maven-indexer specific file format
The legacy format is no longer supported and when the indexer
encounters old index files it raises this exception.
To integrate with the existing error handling the exception
is wrapped as an IOException.
> [270357] IllegalArgumentException raised by maven-indexer

- editor.htmlui/src/org/netbeans/modules/editor/htmlui/JSEmbeddingProvider.java
The coloring of JavaScript inside of Java strings wasn't visible due to another `text/x-java-string` embedding taking over the JavaScript one. Removing it, if present.
> Make sure the JavaScript coloring prevails inside of Java strings

- README.md
Add TravisCI and Apache Jenkins build badges to README.md.
Example: 
* TravisCI:
* [![Build Status](https://travis-ci.org/apache/incubator-netbeans.svg?branch=master)](https://travis-ci.org/apache/incubator-netbeans)
* Apache Jenkins: 
* Linux: [![Build Status](https://builds.apache.org/job/incubator-netbeans-linux/badge/icon)](https://builds.apache.org/job/incubator-netbeans-linux/)
* Windows: [![Build Status](https://builds.apache.org/job/incubator-netbeans-windows/badge/icon)](https://builds.apache.org/job/incubator-netbeans-windows/)
> Add build badges to README.md

- parsing.indexing/build.xml
- parsing.indexing/test/unit/src/org/netbeans/modules/parsing/impl/indexing/RepositoryUpdaterTest.java
- parsing.nb/build.xml
- parsing.nb/test/unit/src/org/netbeans/modules/parsing/nb/RepositoryUpdaterEventTest.java
[NETBEANS-139] Create archive sample to fix the RepositoryUpdaterEventTest test on parsing.nb module.
It is the same issue that this: https://github.com/apache/incubator-netbeans/commit/d74705dffc65ae259178fb7f859fc4e8da57a5bb
I use this command to run test: ```ant -f parsing.nb -Dtest.type=unit -Dcontinue.after.failing.tests=true -Dtest.includes=org/netbeans/modules/parsing/nb/RepositoryUpdaterEventTest.java test-single```
> [NETBEANS-139] Create archive sample to fix RepositoryUpdaterEventTest.

- java.source.base/test/unit/src/org/netbeans/modules/java/source/PostFlowAnalysisTest.java
- java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/JavacParserTest.java
- java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/MRJARCachingFileManagerTest.java
- java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/MRJARModuleFileManagerTest.java
- libs.javacapi/external/binaries-list
- libs.javacimpl/external/binaries-list
Fix for following errors with merged nb-java-x jars (https://hg.netbeans.org/main/nb-java-x) in JDK18_3 branch:
1.test225887sl17 : org.netbeans.modules.java.source.PostFlowAnalysisTest
2.updated checksum in binaries-list for nb-java-x jars.
(https://hg.netbeans.org/main/nb-java-x)
3. Enum error of Source.java 
java.lang.NoSuchFieldError: JDK1_9, JDK1_8 and JDK1_7
Use SourceLevelUtils.java in place of Source.java class.
For more details: https://confluence.oraclecorp.com/confluence/pages/viewpage.action?pageId=606328162
> [JDK18_3] nb-javac-x jars change and test case issue fixes

- openide.util.ui/src/org/openide/util/ImageUtilities.java
- openide.util.ui/test/unit/src/org/openide/util/ImageUtilitiesTest.java
I was getting NPE recently and this would be the general fix.
> More robustness when resource name of loadImageIcon is null

- java.lexer/src/org/netbeans/lib/java/lexer/JavaLexer.java
The default jdk version in JavaLexer is set as 9, but var keyword check requires min version 10. The runtime jdk version is not available via inputAttributes, hence default version value is getting used here.
Working on passing runtime jdk version via inputAttributes in another transaction and will merge separately.
> JDK18_3 : var shows without syntax highligting in jdk10

- junit.ant.ui/test/unit/src/org/netbeans/modules/junit/ant/ui/AntJUnitManagerProviderTest.java
[NETBEANS-408](https://issues.apache.org/jira/browse/NETBEANS-408) Fix AntJUnitManagerProviderTest test at junit.ant.ui module.
The AntJUnitManagerProviderTest unit test at Ant Junit UI module fails when execute because it is a prototype and call fail method.
```
AntJUnitManagerProvider instance = new AntJUnitManagerProvider();
instance.registerNodeFactory();
// TODO review the generated test code and remove the default call to fail.
fail("The test case is a prototype.");
```
I use this command to run test: ```ant -f junit.ant.ui -Dtest.type=unit -Dtest.includes=org/netbeans/modules/junit/ant/ui/AntJUnitManagerProviderTest.java test-single```
> [NETBEANS-408] Fix AntJUnitManagerProviderTest test at junit.ant.ui module.

- spi.java.hints/apichanges.xml
- spi.java.hints/nbproject/project.properties
- spi.java.hints/src/org/netbeans/spi/java/hints/JavaFixUtilities.java
- spi.java.hints/test/unit/src/org/netbeans/spi/java/hints/JavaFixUtilitiesTest.java
This utility method determines whether a Tree can be used in places
where a Primary is required (for instance, as the receiver expression of
a method invocation).
> Add the JavaFixUtilities.isPrimary() utility API

- api.progress/nbproject/project.properties
- api.progress/src/org/netbeans/api/progress/BaseProgressUtils.java
- api.progress/src/org/netbeans/api/progress/ProgressHandle.java
- api.progress/src/org/netbeans/api/progress/aggregate/AggregateProgressHandle.java
- apisupport.ant/src/org/netbeans/modules/apisupport/project/universe/PlatformLayersCacheManager.java
- diff/src/org/netbeans/modules/diff/DiffAction.java
- diff/src/org/netbeans/modules/diff/PatchAction.java
- diff/src/org/netbeans/modules/diff/builtin/DiffPresenter.java
- image/nbproject/project.properties
- image/src/org/netbeans/modules/image/ImageViewer.java
`ProgressHandle` and `AggregateProgressHandle` fit very well with try-with-resources so we only need to implement `AutoCloseable`.
The usual style is:
```java
ProgressHandle handle = ProgressHandle.createHandle(displayName);
try{
handle.start();
...
} finally{
handle.finish();
}
```
With try-with-resources it becomes:
```java
try (ProgressHandle handle = ProgressHandle.createHandle(displayName)) {
handle.start();
...
}
```
> Makes ProgressHandle and AggregateProgressHandle AutoCloseable

- nbbuild/jdk.xml
As mentioned in bug, tools.jar is not available in JDK 9, 10, hence jdk.home is getting set to fallback value ${java.home.parent} and thus gets incorrectly set to parent folder of java.home. Changing this value to java.home fixes the issue. Verified in Windows+Linux. Is this fallback value used in any other usecase?
> [NETBEANS 363] Fix fallback jdkhome

- java.editor/src/org/netbeans/modules/editor/java/JavaKit.java
- java.lexer/nbproject/project.properties
- java.lexer/src/org/netbeans/lib/java/lexer/JavaLexer.java
- java.lexer/test/unit/src/org/netbeans/lib/java/lexer/JavaLexerBatchTest.java
- java.source.base/src/org/netbeans/modules/java/source/parsing/AbstractSourceFileObject.java
SourceLevel is not passed to JavaLexer, hence version is set to default, which is the latest version supported. So version always set to 10.  Fixed by passing version as inputAttribute to JavaLexer.
> [NETBEANS 470] Var shows as keyword in jdk8, 9

- debugger.jpda/src/org/netbeans/modules/debugger/jpda/expr/EvaluatorVisitor.java
I am getting `NullPointerException` quite frequently when debugging my [Bck2Brwsr VM](http://github.com/jtulach/bck2brwsr). This change makes the code more robust.
> Shielding against NPE when debugging Nashorn scripts

- core.ui/src/org/netbeans/core/ui/sysopen/SystemOpenAction.java
Selecting multiple nodes and choosing this action resulted in an exception because the default RequestProcessor was used
> SystemOpenAction should use its own RequestProcessor

- javahelp/src/org/netbeans/modules/javahelp/resources/layer.xml
Disabling the QuickSearchProvider for JavaHelp so that the Quick Search text field continues to work for all other QuickSearchProviders, just not for JavaHelp (until JavaHelp is included at some point in the future).
> [NETBEANS-492] disable QuickSearchProvider for JavaHelp

- openide.filesystems/src/org/openide/filesystems/annotations/LayerBuilder.java
FileSystem implementation supports methodValue attribute for methods, which take Map as a parameter, but the LayerBuilder did not.
> Enable creation using methods with Map parameter

- java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertToDiamondBulkHint.java
- java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertToDiamondBulkHintTest.java
Fix hint 'Use diamond inference'  is disabled for var type  variable initialization.
var list = new ArrayList<String>();
> netbeans-480: ConvertToDiamondBulkHint disabled for var type variable initialization

- java.source.base/src/org/netbeans/modules/java/source/parsing/JavacParser.java
The "--should-stop:at=" javac option has been changed to "--should-stop=at=" in JDK11, adjusting to format that should work both before and after the change.
> Adjusting should-stop parameter to javac to recent changes.

- apisupport.ant/src/org/netbeans/modules/apisupport/project/queries/SubprojectProviderImpl.java
The `api.common.annotations` module was listed at its own subproject. Preventing similar issues by removing the `project` from the subproject `s` set before returning it.
Fixes [NETBEANS-517](https://issues.apache.org/jira/browse/NETBEANS-517) bug.
> #517: Prevent a project to be a subproject of itself

- csl.api/src/org/netbeans/modules/csl/core/GsfDataObject.java
- csl.api/test/unit/src/org/netbeans/modules/csl/core/GsfDataObjectTest.java
- html/src/org/netbeans/modules/html/HtmlDataObject.java
- html/test/unit/src/org/netbeans/modules/html/HtmlDataObjectTest.java
- xml.multiview/src/org/netbeans/modules/xml/multiview/XmlMultiViewDataObject.java
- xml.multiview/test/unit/src/org/netbeans/modules/xml/multiview/test/XmlMultiViewEditorTest.java
The overriden setModified() removes save cookie if the "modified" status is false. The trouble is, that if during invocation of listeners, ..., some cod manages to get the object un-modified again for some reason. Then the cookie is not removed since (local) modified variable no longer corresponds the isModified() result.
The object reports isModifed() == false, but has saveCookie, which enables actions etc.
I'd need the change in JS DataObject, but I put it to other DataObjects that I found overriding setModified too.
> Better consistency between SaveCookie presence and modified status

- lib.profiler/build.xml
- nbbuild/templates/projectized.xml
- o.apache.xml.resolver/build.xml
The apache-resolver needs to compile and patch external JAR to produce the resolver JAR that should go to `modules/ext`. The current build sequence fills in` release.files.extra` property before that, so the JAR is missing from update tracking information. Consequently, applications built on NetBeans platform will not pick the resolver JAR from NB platform during the build and will be broken.
This effect happens just if the NB platform is built from clean sources. Once sources are patched and the build runs again, the patched jar is already in place when release.files.extra is computed and the resulting platform contains correct update tracking info.
The proposed change adds an overridable target to nb module build, which can be overriden in module's build.xml to do additional processing …
> Allow to postprocess downloaded binaries

- utilities/src/org/netbeans/modules/utilities/netbeans-kb.url
Docs aren't on netbeans.apache.org yet, but the page on netbeans.apache.org explains that, so pointing to the new correct location is probably a good thing already.
> [NETBEANS-656] Switch docs URL from netbeans.org to netbeans.apache.org.

- maven/arch.xml
- maven/src/org/netbeans/modules/maven/execute/AbstractOutputHandler.java
Fix for [bug #270005](https://netbeans.org/bugzilla/show_bug.cgi?id=270005). I have been running with this patch for over a year.
> #270005: increase the default indexing sleep delay during builds to 15s, and make it configurable

- openide.nodes/src/org/netbeans/modules/openide/nodes/NodesAnnotationProcessor.java
- openide.nodes/test/unit/src/org/netbeans/modules/openide/nodes/CustomData.java
- openide.nodes/test/unit/src/org/netbeans/modules/openide/nodes/PEAnnotationProcessorTest.java
- openide.nodes/test/unit/src/org/netbeans/modules/openide/nodes/TestPropertyEditor.java
I found out that when `targetType` is an inner class, the generated layer registration uses `.` as delimiter between outer and inner class simple names.
> Fix @PropertyEditorRegistration to work with inner classes

- core.windows/src/org/netbeans/core/windows/view/ui/CloseButtonTabbedPane.java
See https://issues.apache.org/jira/browse/NETBEANS-712 ; a screenshot before and after is attached there. Also reported earlier on Bugzilla https://netbeans.org/bugzilla/show_bug.cgi?id=251441 . See also the prior discussion on https://github.com/emilianbold/netbeans-releases/pull/4 (an old pull request from before the incubator-netbeans repo was up and running).
> [NETBEANS-712] Improve label/button alignment in output pane header on Aqua

- git/src/org/netbeans/modules/git/ui/diff/MultiDiffPanel.java
Minor UI panel background problem on macOS:
After the fix:
Will commit immediately, created PR just to attach these screenshots for historical reference.
> Sets backgroud color on all the separator panels

- git/src/org/netbeans/modules/git/ui/diff/MultiDiffPanel.form
- git/src/org/netbeans/modules/git/ui/diff/MultiDiffPanel.java
The Git Diff window uses a lot of vertical space while displays have more horizontal space.
This is particularly annoying because any vertical space taken by some other component is not usable by the lines of source code being diffed.
This PR moves the 'tree selection panel' into the toolbar thereby adding some 2 more lines of code.
> Moves the Git Diff window tree selection panel into the toolbar

- spi.viewmodel/src/org/netbeans/modules/viewmodel/TreeModelNode.java
This is an old bug reported here https://netbeans.org/bugzilla/show_bug.cgi?id=258373 that still exists.
> Calls the model with a correct object and not the newly created tooltip

- ide.branding/uihandler/src/org/netbeans/modules/uihandler/Bundle_nb.properties
- uihandler/src/org/netbeans/modules/uihandler/UIHandler.java
Removed change done in #471 to invoke JIRA url in browser on Review and Report Problem button click. Framework already supports disabling issue reporting via ERROR_URL page.
> [NETBEANS-491] use framework support to disable error reporting

- uihandler/src/org/netbeans/modules/uihandler/Installer.java
Also reduced the height of dialog as there was some empty space between text displayed and buttons below.
> [NETBEANS-491] hide progress bar from Report Problem dialog

- form/src/org/netbeans/modules/form/layoutsupport/griddesigner/GridDesigner.java
Fixes the following compile issue under Java 9. Should be fine under 1.8 and other.
```java
src/org/netbeans/modules/form/layoutsupport/griddesigner/GridDesigner.java:267: error: method get in class SystemAction cannot be applied to given types;
ContextAwareAction undoRedoAction = SystemAction.get(undo ? org.openide.actions.UndoAction.class : org.openide.actions.RedoAction.class);
^
required: Class<T>
found: undo ? org[...]class
reason: inference variable T has incompatible equality constraints RedoAction,UndoAction
where T is a type-variable:
T extends SystemAction declared in method <T>get(Class<T>)
```
> form: Fix compile error under Java 9, method cannot be applied to types

- java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertToVarHint.java
- java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertToVarHintTest.java
Replaced TreeUtilities.attributeTree with specific Tree.kind checks. Added tests for the usecases fixed, i.e. cases where convert to var hint should not be shown: lambda, array initializer. Hint should show for diamond operator type initializer, and type matches capture type of initializer.
> [NETBEANS-694] : Support convert to var for diamond operator and other fixes

- maven/manifest.mf
- maven/src/org/netbeans/modules/maven/output/TestOutputListenerProvider.java
This patch was already submitted (and IIRC, accepted) in the netbeans.org hg repo, but was applied after the Apache contribution snapshot was made.  Output window stack links for test results have been broken for some time when using multi-module projects with newer versions of Maven.  I've run with these patches for 9 months and observed no problems as a result.
> Fix maven output window links for newer versions of Maven

- spi.editor.hints/apichanges.xml
- spi.editor.hints/nbproject/project.properties
- spi.editor.hints/src/org/netbeans/modules/editor/hints/AnnotationHolder.java
- spi.editor.hints/src/org/netbeans/modules/editor/hints/FixAction.java
- spi.editor.hints/src/org/netbeans/modules/editor/hints/HintsUI.java
- spi.editor.hints/src/org/netbeans/modules/editor/hints/ParseErrorAnnotation.java
- spi.editor.hints/src/org/netbeans/spi/editor/hints/ErrorDescription.java
- spi.editor.hints/src/org/netbeans/spi/editor/hints/ErrorDescriptionFactory.java
- spi.editor.hints/test/unit/src/org/netbeans/modules/editor/hints/AnnotationHolderTest.java
Two API changes were developed by Maria since the 1st donation. This pull request back ports them to give us a chance to use proper versioning (#553) for the `spi.editor.hints` module and make sure the 8.2 and dev modules using `spi.editor.hints` can work with upcoming Apache NetBeans 9.0.
This change should be merged to both - `master` as well as `release90` - branches.
> Bringing Editor Hints SPI up-to-date

- libs.ini4j/external/ini4j-0.5.1-notice.txt
The ini4j distribution on netbeans is missing the notice file. The contents
was extracted from the subversion tag for ini4j version 0.5.1:
https://sourceforge.net/p/ini4j/code/HEAD/tree/tags/ini4j-0.5.1/NOTICE.txt
The ALv2 license was removed, as it is not considered to be part of the
"attribution" notice. The product name was added as a header to make
the notice attributable in the merged NOTICE file.
> [NETBEANS-829] Add notice file for ini4j

- java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertToVarHint.java
- java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertToVarHintTest.java
- java.source.base/apichanges.xml
- java.source.base/nbproject/project.properties
- java.source.base/src/org/netbeans/api/java/source/TreeUtilities.java
- java.source.base/test/unit/src/org/netbeans/api/java/source/TreeUtilitiesTest.java
Jira Id: https://issues.apache.org/jira/browse/NETBEANS-764
For compound variable declaration (e.g.,int i =10, j=20; )
There are two 'Convert to var type' hints displayed , selecting any will convert the declaration at the current cursor position. 
To prevent this from happening ConvertToVar hint will be disabled for compound variable declaration.
> [NETBEANS-764] JDK10-LVTI: Skip ConvertToVar hint for compound variable declaration

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/CreateLicenseSummary.java
- nbbuild/build.xml
- nbbuild/notice-stub.txt
While looking into NETBEANS-827 it was found, that the NOTICE file is
difficult to read, as no clear sections were visible.
This adjust the output as such, that:
- the primary header is separated from the following entries by
two empty lines
- all imported entries are normalized, so that multiple empty lines
are collapsed into one empty line
- all imported entries are separated from each other by two empty
lines
To illustrate here are the pre- and post picture:
[notice-pre.txt](https://github.com/apache/incubator-netbeans/files/2040691/notice-pre.txt)
[notice-post.txt](https://github.com/apache/incubator-netbeans/files/2040690/notice-post.txt)
I tried to see what NETBEANS-827 is about and at first I did not even find the entry. The corresponding entry is:
> Apache Commons Net
> Copyright …
> Optimize readability of the NOTICE file

- java.api.common/src/org/netbeans/modules/java/api/common/classpath/ModuleClassPaths.java
- java.api.common/test/unit/src/org/netbeans/modules/java/api/common/classpath/ModuleClassPathsTest.java
- java.source.base/src/org/netbeans/modules/java/source/indexing/APTUtils.java
- java.source.base/src/org/netbeans/modules/java/source/parsing/JavacParser.java
- java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/JavacParserTest.java
-accepting duplicate ClassPath entries with module-infos
-filtering out options that don't match the validated source level
Fixing two problems with the given project - with JDK 10 platform, the sources ClassPath in ModuleClassPaths.ModuleInfoClassPathImplementation has a duplicated entry, leading to having the module-info.java twice in the list of files to which the listener should be added, leading to the reported exception. Proposed fix is to use LinkedHashSet to avoid the duplication. Having duplicated entries in the CP may not be nice, but I suspect it is not reasonable to try to force a constraint that the entries must not be duplicated.
With platform <JDK 10/9, there are multiple problems, but the biggest one is that there are additional compiler options, like --add-reads …
> [NETBEANS-817] Preventing exceptions when opening project:

- nbbuild/packaging/snap/gui/netbeans.desktop
- nbbuild/packaging/snap/snapcraft.yaml
Changed Snap package descriptors for NetBeans 9.0 release. 
I've decided not to include release quality specifier in these files as snap has it's own revision handling and and the branding is going to include the necessary things. So this way is just one less thing to worry about.
BTW this PR shall go to release90 only.
> Snap changes for 9.0

- libs.jaxb/external/jaxb-2.2.5-2-jaxb-license.txt
- libs.jaxb/external/jaxb-2.2.5-2-jaxb1-license.txt
- libs.jaxb/external/jaxb-2.2.5-2-xjc-license.txt
- nbbuild/licenses/CDDL-1.1-BSD-MIT-jaxb1-xjc
- nbbuild/licenses/CDDL-1.1-MIT-jaxb-xjc
The license infos were extracted/retrieved from the sources of the
originating projects. JAXB1 and XJC are both missing the license
references.
> [NETBEANS-830][NETBEANS-831] Fix license info for jaxb implementation

- nbbuild/build.xml
I am trying to use NetBeans with [GraalVM](http://graalvm.org). Right now executing the Ant script doesn't work:
```bash
incubator-netbeans$ JAVA_HOME=~/bin/graalvm-1.0.0-rc1/ ant tryme -Dtryme.arg.netbeans.close=-J-Dnetbeans.close=true
```
with following patch the IDE starts and shutdowns without an error on GraalVM 1.0.0rc1 as well as official JDK8. CC @woess
> Modify the JavaScript script to work with GraalVM 1.0.0-rc1

- o.n.core/src/org/netbeans/core/GuiRunLevel.java
Applied @JaroslavTulach patch which schedules termination in headless mode. The code, which usually checks for "netbeans.close" property is run from within `WindowManager.invokeWhenUIReady`, so it executes only after the main window becomes visible. That is never in headless mode.
> NETBEANS-951: terminate application in headless mode

- openide.nodes/src/org/openide/nodes/BeanNode.java
- xml.tax/src/org/netbeans/modules/xml/tax/beans/Lib.java
This change has been done in order to avoid compile time warnings.
> added unbound generic type argument to Class in BeanNode and Lib

- java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
- java.source.base/test/unit/src/org/netbeans/modules/java/source/save/FormatingTest.java
Jira Id : https://issues.apache.org/jira/browse/NETBEANS-778
Issue details:
Before Formatting:
{                 final[extra space ]int[extra space ] i[extra space ] = 0;   
final[extra space ]var[extra space ]v[extra space ]  = 0; 
}
After Formatting (ALT+SHIFT+F):
{      final int i = 0;    
final[extra space ]var[extra space ]v [extra space ] = 0; 
}
> [NetBeans-778] Formatting issue with var declaration statement

- java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
- java.source.base/test/unit/src/org/netbeans/api/java/source/gen/MultiCatchTest.java
- refactoring.java/test/unit/src/org/netbeans/modules/refactoring/java/test/MoveClassTest.java
Fixed the two compilation issues after refactor : 
catch (RuntimeException | AssertionError e){
getting converted to
catch (RuntimeException | AssertionErrore){
and
doStuff(item-> item.substring(20));
getting converted to
doStuff(String item-> item.substring(20));
(Lambda issue is reproducible in IDE but not with move test below, as param type is coming as ERROR. Need to investigate this.)
> [NETBEANS-892] Fix lambda expr and multi catch rewrite issues

- javadoc/nbproject/project.properties
- javadoc/src/org/netbeans/modules/javadoc/highlighting/Highlighting.java
- javadoc/test/unit/src/org/netbeans/modules/javadoc/highlighting/HighlightingTest.java
I added unit tests.
https://issues.apache.org/jira/browse/NETBEANS-791
> [NETBEANS-791] Highlights for the top line of JavaDoc are done on every line.

- core.windows/src/org/netbeans/core/windows/documentgroup/GroupsManager.java
see description of NETBEANS-1049. The change avoids copying for non-persistable components, or just for components which do not have their `.settings` file for some reason.
> NETBEANS-1049: prevent NPE on unpersistable components

- o.n.core/src/org/netbeans/core/ui/ProductInformationPanel.java
See `NETBEANs-1048` for description. I've simply moved the caret to the beginning of the text to force editbox to display the text start.
> NETBEANS-1048: display start of product info in about box

- openide.loaders/src/org/openide/loaders/TemplateWizard1.java
In the branch for shadow, the name is localized through the DataNode, so the final value is seen immediately and can be fixed for the `DataShadowFilterNode`. But for "normal" nodes, the node may resolve the localized name later, in background and change it. It will fire events which the `DataShadowFilterNode` will happily forward, but `getDisplayName` need to delegate to the filer node so that the current value is returned to the caller.
> NETBEANS-998: update display name when DelayedNode resolves it

- debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/models/JPDAAsynchronousModel.java
Viewing variable in debugger was causing  AWT Event Queue exception as AWT thread was being used.
Code is modified to make async call for  population of short-description
Jira Link:  https://issues.apache.org/jira/browse/NETBEANS-974
Was not able to add relevant TestCases as in debugger.jdpa.ui module existing test cases are not working
Below Jira was raised for that
https://issues.apache.org/jira/browse/NETBEANS-1027
> [NETBEANS-974] Fix for AWT Event Queue exception on viewing variable value is debug mode

- java.hints/src/org/netbeans/modules/java/hints/bugs/NPECheck.java
- java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/NPECheckTest.java
Jira Id : https://issues.apache.org/jira/browse/NETBEANS-1019
Issues: False positive of "Null Pointer Dereference" when passing a lambda with a null possible result to a non-null argument
private void func(@NonNull Function<Object, Object> func){
}
@CheckForNull
private Object foo(){
return null;
}
private void bar(){
func(item->foo());//false positive
}
> [NetBeans-1019]False positive of "Null Pointer Dereference" when passing a lambda with a null possible result to a non-null argument

- lib.profiler.common/src/org/netbeans/lib/profiler/common/integration/IntegrationUtils.java
Jdk10 as remote target seems not to be supported when profiling in netbeans9
> [NETBEANS-953] Profiling jdk10 remote target missing conditional branch

- subversion/src/org/netbeans/modules/subversion/client/cli/commands/VersionCommand.java
- subversion/test/unit/src/org/netbeans/modules/subversion/client/cli/commands/VersionCommandTest.java
- subversion/test/unit/src/rg/netbeans/modules/subversion/client/cli/commands/VersionCommandTest.java
So comparing verion numbers would be based on numbers, not strings.
I.e. its now possible to determine if 1.2.2 and 1.2.123 have same MAJOR.MINOR version.
Fixes [NETBEANS-771](https://issues.apache.org/jira/browse/NETBEANS-771).
NETBEANS-771 caused by version.indexOf("1.1") > -1 
it was fine for svn 1.9, but is broken since 1.10, as 1.10 is treated as 1.1. That is motivation behind actual parsing of string to version container.
> Adds Version parsing to svn output.

- java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
The formatting change was introduced by the change to support reformatting
module declarations via mercurial changeset 4cbf6ecb92bc
http://hg.netbeans.org/main-golden/rev/4cbf6ecb92bc
The change in Reformatter.Pretty.visitCompilationUnit(CompilationUnitTree, Void)
was then conditionalized to only be applied to non-modules 
(git commit: 53ee08901ff0e4c2706b4050a54bc4672ab7994b)
https://github.com/apache/incubator-netbeans/commit/53ee08901ff0e4c2706b4050a54bc4672ab7994b
That changeset left the regression for the general formatting in place
and removed the original use case for modules (for module declarations
the extra empty line is not introduced).
This changeset changes the situation back to the state before 4cbf6ecb92bc.
> [NETBEANS-369] Code-complete outputs unwanted newline characters

- xml.text/src/org/netbeans/modules/xml/text/completion/XMLResultItem.java
- xml.text/test/unit/src/org/netbeans/modules/xml/text/completion/ValueResultItemTest.java
- xml.text/test/unit/src/org/netbeans/modules/xml/text/completion/res/ValueReplacement.golden.xml
- xml.text/test/unit/src/org/netbeans/modules/xml/text/completion/res/ValueReplacement.xml
#isRemovingAvailableLocked can only be true, if the scan of the remaining
tokens all report to be removable.
This is not the intention at the use site. The question, is whether
deletes in the current token are expected and so only the current token
needs to be checked.
> [NETBEANS-1083] Fix value replacement in POM editing

- options.api/src/org/netbeans/modules/options/OptionsPanel.java
There is a (strange) registration for VK_LEFT and VK_RIGHT in OptionsPanel. I haven't found a way to trigger the registration from a Swing component - neither in the NetBeans IDE nor products build on top of it.
It makes little sense to bind such lowlevel arrow keys to such high-level task. Thus this change proposes Ctrl-Tab and Ctrl-Shift-Tab instead for switching the categories.
With this change I can easily switch categories in the IDE as well as eliminate the switching on left/right arrow press in a JFXPanel - an issue that motivated this change.
> Left/Right arrows are too generic for switching tabs.

- groovy.editor/licenseinfo.xml
- groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/temporary/README.txt
- Add the license header to README.txt
- FontsAndColorsPreview.groovy is an example file, so add it to the licenseinfo.xml
- 13 unit tests fail
> [NETBEANS-1074] Module Review groovy.editor

- libs.groovy/external/binaries-list
- libs.groovy/external/groovy-all-2.4.5-notice.txt
- nbbuild/licenses/Apache-2.0-groovy
- Add the license header and maven coordinate to binaries-list
- Add the groovy-all-2.4.5-notice.txt
- Add the Apache-2.0-groovy license file to nbbuild/licenses
- Fix the groovy-all-2.4.5-license.txt
License: https://github.com/apache/groovy/blob/master/LICENSE
Notice: https://github.com/apache/groovy/blob/master/NOTICE
cc: @brunoflavio-com
> [NETBEANS-1074] Module Review libs.groovy

- javascript2.nodejs/external/binaries-list
- javascript2.nodejs/test/qa-functional/data/SimpleNode/src/cc/cc1.js
- javascript2.nodejs/test/qa-functional/data/SimpleNode/src/cc/cc2.js
- javascript2.nodejs/test/qa-functional/data/SimpleNode/src/cc/cc4.js
- javascript2.nodejs/test/qa-functional/data/SimpleNode/src/cc/foo.js
- javascript2.nodejs/test/qa-functional/data/SimpleNode/src/core/mymod.js
- javascript2.nodejs/test/qa-functional/data/SimpleNode/src/folder/arr.js
- javascript2.nodejs/test/qa-functional/data/SimpleNode/src/folder/arrRef.js
- javascript2.nodejs/test/qa-functional/data/SimpleNode/src/folder/newjavascript.js
- javascript2.nodejs/test/unit/data/TestNavigation/public_html/index.html
- javascript2.nodejs/test/unit/data/TestNavigation/public_html/js/issue247565/folder/literalRef247565.js
- javascript2.nodejs/test/unit/data/TestNavigation/public_html/js/issue250329/s1.js
- javascript2.nodejs/test/unit/data/TestNavigation/public_html/js/issue250329/s2.js
- javascript2.nodejs/test/unit/data/TestNavigation/public_html/js/issue250329/s3.js
- javascript2.nodejs/test/unit/src/org/netbeans/modules/javascript2/nodejs/editor/NodeJsDeclarationFinderTest.java
Added a few missing licenses, replaced default license stubs in test data with Apache2 license.
> [NETBEANS-1074] Module Review javascript2.nodejs

- j2eeserver/licenseinfo.xml
- j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/server-string.dtd
- j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/target-module.dtd
added 2 templates and 23 graphic files to licenseinfo.xml
> [NETBEANS-1074] Module Review j2eeserver

- web.core.syntax/external/binaries-list
- web.core.syntax/l10n.list
- web.core.syntax/licenseinfo.xml
Checked the rat-report.txt file, don't know what to do with these files:
- cddl_11_license.txt
- struts-tags_apache20_license.txt
Add the license header for binaries-list and l10n.list
Could not find maven replacement for the binaries-list (old html references)
Add the licenseinfo.xml 
Skimmed through module, I see in the test folder there are src and data ones. The src one, the files have the license. In the data folder there are several examples and no license.
> [NETBEANS-1074] Module Review web.core.syntax

- glassfish.eecommon/test/unit/src/org/netbeans/modules/glassfish/eecommon/api/FindJspServletHelperTest.java
-no external library
-checked Rat report: everything has been relicensed to Apache, as this commit adds header to a java file that was missing header
-skimmed through module, did not notice additional problems
> [NETBEANS-1074] Module Review glassfish.eecommon

- java/maven/src/org/netbeans/modules/maven/options/MavenCommandSettings.java
The fix of [BZ #271110](https://netbeans.org/bugzilla/show_bug.cgi?id=271110) was pushed to Mercurial by @tstupka a couple months before the initial code donation, but apparently was never ported to Git. I am very disturbed that at least two months’ worth of commit history seems to have been discarded. What else was lost?
> Issue #271110 - Attempt to pass -DarchetypeRepository to 3.x maven-archetype-plugin

- php.editor/.gitignore
- php.editor/build.xml
- php.editor/external/Mpdf-7.1.5-license.txt
- php.editor/external/TextSearchQuery-1.28-license.txt
- php.editor/external/binaries-list
- php.editor/test/unit/data/testfiles/actions/testImportData/libs/nette.min.php
- php.editor/test/unit/data/testfiles/formatting/html/html01.php
- php.editor/test/unit/data/testfiles/formatting/html/html01.php.formatted
- php.editor/test/unit/data/testfiles/formatting/html/html02.php
- php.editor/test/unit/data/testfiles/formatting/html/html02.php.formatted
- php.editor/test/unit/data/testfiles/formatting/html/html03.php
- php.editor/test/unit/data/testfiles/formatting/html/html03.php.formatted
- php.editor/test/unit/data/testfiles/formatting/html/html04.php
- php.editor/test/unit/data/testfiles/formatting/html/html04.php.formatted
- php.editor/test/unit/data/testfiles/verification/testEmptyStatementHint.php
- php.editor/test/unit/src/org/netbeans/modules/php/editor/actions/ImportDataCreatorTest.java
- php.editor/test/unit/src/org/netbeans/modules/php/editor/indent/PHPFormatterHtmlTest.java
- php.editor/test/unit/src/org/netbeans/modules/php/editor/parser/ASTPHP5ParserTest.java
- php.editor/test/unit/src/org/netbeans/modules/php/editor/parser/ParserPerformanceTest.java
- php.editor/test/unit/src/org/netbeans/modules/php/editor/verification/HintsTest.java
https://issues.apache.org/jira/browse/NETBEANS-1151
Enable unit tests of php.editor again: see #720
- nette.min.php: New BSD License https://github.com/nette/nette/blob/master/license.md
- testEmptyStatementHint.php: New BSD License https://github.com/nette/nette/blob/master/license.md
- performance.php: Simple Machines License (SMF 1.0 and 1.1) https://www.simplemachines.org/about/smf/license.php
- TextSearchQuery.php: GPL v2 https://sourceforge.net/p/phpwiki/code/HEAD/tree/trunk/LICENSE
- html04.php: Recreate it
html04.php is related to this issue: https://netbeans.org/bugzilla/show_bug.cgi?id=175229, we should also fix html01, 02. 03.php.
I'm not sure whether we can include performance.php.
TextSearchQuery.php is GPL, so download as external binaries?
> [NETBEANS-1151] Fix unit test files of php.editor

- java/libs.javacapi/external/binaries-list
- java/libs.javacimpl/external/binaries-list
Updated with nb-javac jars synced with JDK 11 code.
Test results are in corresponding jira bug.
> [NETBEANS-803] Uptake nb-javac 11 jars for java tests runtime

- selenium2.webclient.protractor/licenseinfo.xml
- selenium2.webclient.protractor/src/org/netbeans/modules/selenium2/webclient/protractor/wizard/protractor.conf.js
- Changed license header of protractor.conf.js
- Added a template file to licenseinfo.xml
In the old protractor.conf.js ([here](https://github.com/apache/incubator-netbeans/blob/master/selenium2.webclient.protractor/src/org/netbeans/modules/selenium2/webclient/protractor/wizard/protractor.conf.js)), we have the license under a `<#-- ... -->`, but in a .js file, comments are added using `/** ... */`, so, I have added the license with the latter syntax. Please correct me if I am wrong.
> [NETBEANS-1074] Module Review selenium2.webclient.protractor

- glassfish.javaee/licenseinfo.xml
- glassfish.javaee/test/qa-functional/src/org/netbeans/modules/glassfish/javaee/test/ServerResourceProperties.java
- No External Libary
- Checked Rat report: everything has now been relicensed to Apache, as this commit channges header to java file that was licensed to Oracle
- Skimmed through module...no additional problems found
- Added licenseinfo.xml
> [NETBEANS-1074] Module review glassfish.javaee

- libs.plist/external/binaries-list
- libs.plist/external/dd-plist-1.3-license.txt
- libs.plist/manifest.mf
- libs.plist/nbproject/project.properties
- nbbuild/licenses/MIT-dd-plist
- nbbuild/licenses/names.properties
- Add the license header to binaries-list
- Add maven coordinate (Change the version from 1.1-SNAPSHOT to 1.3)
- Add MIT-dd-plist to nbbuild/licenses
I've added [version 1.3](https://search.maven.org/artifact/com.googlecode.plist/dd-plist/1.3/jar) instead of 1.1-SNAPSHOT because version 1.1 does not exist in the maven central. (The latest version is 1.21)
> [NETBEANS-1074] Module Review libs.plist

- platform/core.execution/src/org/netbeans/core/execution/SecMan.java
Fine tuning of #790. Shown dialogs were associated with a warning. By returning `true` from the `checkTopLevelWindow` method of `SecMan` instance, the warning disappears.
> Trust every shown dialog

- java/java.source.base/src/org/netbeans/modules/java/source/parsing/JavacParser.java
Apache NetBeans 9.0 provides **Java Frontend Application** which can be deployed to desktop, Android, iOS and also Web. When compiling for web, only a subset of JDK8 APIs is available. To make sure the IDE and the runtime agree on the same classes, it is useful to configure compiler plugin like this:
```xml
<maven.compiler.source>1.8</maven.compiler.source>
<maven.compiler.target>1.8</maven.compiler.target>
</properties>
<build>
<plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.8.0</version>
<configuration>
<compilerArguments>
<bootclasspath>netbeans.ignore.jdk.bootclasspath</bootclasspath>
</compilerArguments>
</configuration>
</plugin>
```
Then `rt.jar` is ignored and only libraries from dependencies are placed on …
> Enable source=1.8 for Java Frontend Web Application

- libs.glassfish_logging/external/binaries-list
- libs.glassfish_logging/external/commons-logging-1.0.4-license.txt
- libs.glassfish_logging/external/glassfish-logging-2.0-license.txt
- libs.glassfish_logging/external/logging-api-1.0.4-license.txt
- libs.glassfish_logging/nbproject/project.properties
- libs.glassfish_logging/nbproject/project.xml
- Added license header to binaries-list
- Repaired license.txt
- Scanned module and no other issues found
> [NETBEANS-1074] Module Review libs.glassfish_logging

- platform/autoupdate.services/src/org/netbeans/modules/autoupdate/updateprovider/AutoupdateCatalogParser.java
- platform/core.startup/nbproject/project.xml
- platform/o.n.bootstrap/manifest.mf
- platform/o.n.bootstrap/src/org/netbeans/Module.java
- platform/o.n.bootstrap/src/org/netbeans/ModuleManager.java
- platform/o.n.bootstrap/src/org/netbeans/Util.java
- platform/o.n.bootstrap/test/unit/data/jars/fragment-module.mf
- platform/o.n.bootstrap/test/unit/data/jars/fragment-module/org/foo/FragmentContent.java
- platform/o.n.bootstrap/test/unit/data/jars/host-module.mf
- platform/o.n.bootstrap/test/unit/data/jars/host-module/org/foo/Something.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/ModuleManagerTest.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/SetupHid.java
Inspired by #715 change with additional tests provided.
Originally the branch should only add tests, but as it showed up, some corner cases were not handled (I think) still well.
I wanted to cover 3 cases: 
1. the user enables a module which is a fragment; which should imply enabling the host module as well. 2.  if the user enables the hosting module which just happens to have some fragments around, all those will be enabled and injected (if dependencies are satisfied)
3. if a fragment is enabled, but its host module is **already loaded and live**, the fragment cannot (reliably) join the constructed classloader. Exception should be thrown.
- I found a place in `AutoupdateCatalogParser` where the `needsRestart` condition is probably wrong: if the module is a fragment, then the restart is …
> [NETBEANS-1147] Better enablement of fragment modules.

- ide/mercurial/src/org/netbeans/modules/mercurial/ui/annotate/AnnotateAction.java
- ide/mercurial/test/unit/src/org/netbeans/modules/mercurial/ui/annotate/AnnotateActionTest.java
In PR #508 it was suggested to modify the regular expression used to parse the
output of the mercurial annotate command. While testing it was identified, that
more corner cases need to be covered.
This PR supersedes the referenced PR with a further modified regexp. It also
adds an analysis/description for the format and supplies unittests.
Closes: #508
> [NETBEANS-643] Mercurial Annotate fails on file with spaces and leading dots

- platform/core.windows/src/org/netbeans/core/windows/view/ui/AutoHidingMenuBar.java
- platform/core.windows/src/org/netbeans/core/windows/view/ui/MainWindow.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/view/ui/AutoHidingMenuBarManualTest.java
Hide the menu bar in full screen mode, but allow it to be shown again automatically if the user moves the mouse to the top of the screen, or invokes a menu keyboard mnemonic. This is already the default behavior on MacOS, but not on other OSes.
Simply hiding menu bar would be a one-line change in o.n.core.windows.view.ui.MainWindow--however a fair bit of logic is needed to make the menu bar properly appear and disappear on demand. The related logic is in the separate file AutoHidingMenuBar.java. I've done quite thorough manual testing of this on Windows 10 and Ubuntu 18, including in a multi-monitor setup, in the full NetBeans IDE as well as in my NetBeans Platform application.
See https://issues.apache.org/jira/browse/NETBEANS-731 .
> [NETBEANS-731] Hide (and auto-show) menu bar in full screen mode

- webcommon/html.ojet/src/org/netbeans/modules/html/ojet/ui/wizard/NewProjectWizardIterator.java
I propose to hide the three Oracle JET project templates (one empty project template and two sample projects) for the moment, so that they're not shown, but the code will still be available, and then to fix them over time, if needed at all, i.e., the ojet-cli is more effective anyway.
> [NETBEANS-1239] Hide outdated ojet project templates

- webcommon/cordova.platforms.ios/licenseinfo.xml
- webcommon/cordova.platforms.ios/test/unit/src/org/netbeans/modules/cordova/platforms/ios/disconnected.xml
- webcommon/cordova.platforms.ios/test/unit/src/org/netbeans/modules/cordova/platforms/ios/jsoncommand.xml
- webcommon/cordova.platforms.ios/test/unit/src/org/netbeans/modules/cordova/platforms/ios/listing.xml
- webcommon/cordova.platforms.ios/test/unit/src/org/netbeans/modules/cordova/platforms/ios/toback.xml
- webcommon/cordova.platforms.ios/test/unit/src/org/netbeans/modules/cordova/platforms/ios/tofront.xml
- webcommon/html.knockout/src/org/netbeans/modules/html/knockout/api/KODataBindTokenId.java
Reliensed the leftover file.
Cordova test data files reported by RAT are apache2, since they were donated as part of the codebase, but since the files are request/response data, I would rather not put licenses directly in them (although any sane XML parser should accept that).
> Relicensed leftover file, excluded cordova testing data

- ide/editor.lib/src/org/netbeans/editor/BaseKit.java
- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/ParagraphViewChildren.java
See https://issues.apache.org/jira/browse/NETBEANS-980 .
This pull request can be reviewed/merged independently of that for NETBEANS-977, which deals with the specific word breaking policy ( https://github.com/apache/incubator-netbeans/pull/598 ).
> [NETBEANS-980] Fix Home/End/Up/Down actions in line-wrapped editor

- nb/welcome/src/org/netbeans/modules/welcome/resources/whatsnew.url
The Welcome screen's What's New link point to netbeans.org, could point here instead:
https://netbeans.apache.org/download/index.html
> [NETBEANS-1242] What's New link

- nb/welcome/src/org/netbeans/modules/welcome/resources/community.url
On the Welcome Screen, the Community link points here:
https://netbeans.org/community/index.html?utm_source=netbeans&utm_campaign=welcomepage
...should maybe point here instead:
https://netbeans.apache.org/community/index.html
> [NETBEANS-1243] Community link

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
- nbbuild/cluster.properties
Webcommon cluster has been reviewed and separated into its cluster directory, the next step is to include it in the Apache Netbeans release
> Include webcommon into the release

- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/windows8/Windows8LFCustoms.java
Remove excessive spacing between menu items, which appeared going from Java 8 to Java 9. See screeshots in the JIRA ticket and attached here.
The spacing appeared during the fix for JDK-8067346; it should be safe to set top/bottom margins to zero, however, like they were before. (See http://hg.openjdk.java.net/jdk10/master/annotate/be620a591379/src/java.desktop/share/classes/com/sun/java/swing/plaf/windows/WindowsLookAndFeel.java )
> [NETBEANS-1249] Remove excessive spacing between menu items (Windows)

- platform/core.windows/src/org/netbeans/core/windows/WindowManagerImpl.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/InvokeWhenUIReadInHeadlessModeTest.java
- platform/o.n.core/src/org/netbeans/core/IDESettings.java
Make sure `invokeWhenUIReady` runnables are eventually invoked even in headless mode.
Tests that run in `NbSuiteModule` mode and use parsing never finish. The problem is that parsing is delayed until the main window is shown using `WindowManager.getDefault().invokeWhenUIReady`. However the tests are executed with `gui(false)` option and thus the main window is never shown, which implies the parsing never starts.
This change detects the headless mode and if so, invokes the provided `Runnable` implementations immediately (via `EventQueue.invokeLater`).
> Make invokeWhenUIReady work in headless mode

- php/php.editor/src/org/netbeans/modules/php/editor/verification/PHP73UnhandledError.java
https://issues.apache.org/jira/projects/NETBEANS/issues/NETBEANS-1285
- Check whether the token id is tag end for Heredoc and Nowdoc because LexUtilities.findPreviousToken() may return the last token
> [NETBEANS-1285] Fix an incorrect error

- ide/editor.lib2/src/org/netbeans/api/editor/caret/EditorCaret.java
- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/CharSequenceCharacterIterator.java
- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/DocumentViewOp.java
- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/HighlightsViewUtils.java
- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/WrapInfo.java
- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/WrapInfoUpdater.java
- ide/editor.lib2/test/unit/src/org/netbeans/modules/editor/lib2/view/AdjustBreakOffsetToWordTest.java
Improve text layout for the NetBeans editor's "word wrap" feature. This makes the word wrap behavior more in line with that of other editors, and makes wrapped text more readable. See detailed description and before/after screenshot (also attached here) at https://issues.apache.org/jira/browse/NETBEANS-977 .
> [NETBEANS-977] Improve text layout in word wrap mode.

- java/java.completion/test/unit/src/org/netbeans/modules/java/completion/JavaCompletionTask111FeaturesTest.java
The bug is  fixed in nb-javac repository and will be available with new nb-javac plugin for jdk-11
> [NETBEANS-1224]: Added Test Cases for the issue

- nbbuild/javadoctools/javadoc.css
- nbbuild/javadoctools/template.xml
Instead of adding the timestamp to all HTML files we add it to the ".footnote" CSS class (in javadoc.css).
This makes it easier to add the generated javadoc to a git repository (as planned in NETBEANS-1176) because files that only change because of a timestamp won't generate a commit.
> [NETBEANS-1318] Javadoc timestamp in CSS instead of all HTML files

- platform/o.n.swing.plaf/external/smoothscrollpane-notice.txt
- platform/o.n.swing.plaf/licenseinfo.xml
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/Startup.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/util/SmoothScrollPaneUI.java
This commit fixes the bug described at https://issues.apache.org/jira/browse/NETBEANS-49 .
On Windows, scrolling with a trackpad or mouse wheel would previously scroll many lines
at a time if the user had a larger-than-default scroll speed setting in the Windows control
panel. This patch allows scrolling to happen in smaller increments, while maintaining the
desired scroll speed (average number of lines scrolled per distance moved on the trackpad
or mouse wheel).
This commit adapts a patch originally written by Pavel Fatin, for IntelliJ, to NetBeans. See
http://mail.openjdk.java.net/pipermail/awt-dev/2017-January/012507.html . I'll need some
guidance on how to properly credit and include this external code here. In particular, how
do I make sure that the external project's NOTICE file …
> [NETBEANS-49] Avoid large scroll pane jumps on Windows

- enterprise/web.jsf.editor/build.xml
- enterprise/web.jsf.editor/external/binaries-list
- enterprise/web.jsf.editor/external/generated-jsf-api-docs-2.0-license.txt
- enterprise/web.jsf.editor/external/javax.faces-api-2.0-javadoc-license.txt
- enterprise/web.jsf.editor/licenseinfo.xml
- enterprise/web.jsf.editor/nbproject/project.properties
- Mavenization of jsf-api-docs.zip to javax.faces-api-2.0-javadoc.jar
- Added CDDL-1.1 license for javax.faces-api-2.0-javadoc.jar instead of CDDL-GPL-CP2
- Added licenseinfo.xml file for graphic files
> [NETBEANS-1074] Module Review web.jsf.editor

- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/ClassPathProviderImpl.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/LogicalViewProviderImpl.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/ModuleDescription.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/SourcesImpl.java
- java/java.openjdk.project/test/unit/src/org/netbeans/modules/java/openjdk/jtreg/ClassPathProviderImplTest.java
-handling of external.lib.roots in TEST.ROOT,
-using tree view for tests,
-avoiding search for modules in (any) tests.
> Fixes for the OpenJDK project:

- platform/core.output2/src/org/netbeans/core/output2/ExtPlainView.java
- platform/core.output2/src/org/netbeans/core/output2/options/OutputOptions.java
Remove ExtPlainView methods viewToModel() & modelToView() and use those from parent.
> [NETBEANS-1252] Fix shifted cursor in output window with GDK_SCALE=2

- php/php.code.analysis/src/org/netbeans/modules/php/analysis/PHPStanAnalyzerImpl.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/PHPStanParams.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/PHPStan.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptions.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptionsValidator.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/ValidatorPHPStanParameter.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/Bundle.properties
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/PHPStanCustomizerPanel.form
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/PHPStanCustomizerPanel.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/Bundle.properties
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/PHPStanOptionsPanel.form
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/PHPStanOptionsPanel.java
https://issues.apache.org/jira/browse/NETBEANS-1463
- Add --memory-limit option
- Add validations in the PHPStanCustomizerPanel
We should also add this to the release100 branch because there is no workaround if the user would like to use `--memory-limit` option.
> [NETBEANS-1463] PHPStan memory-limit

- webcommon/cordova/src/org/netbeans/modules/cordova/CordovaPerformer.java
- webcommon/cordova/src/org/netbeans/modules/cordova/options/MobilePlatformsPanel.java
- webcommon/cordova/src/org/netbeans/modules/cordova/project/CordovaPanel.java
- webcommon/cordova/src/org/netbeans/modules/cordova/wizard/CordovaProjectExtender.java
- webcommon/cordova/test/unit/src/org/netbeans/modules/web/clientproject/cordova/AndroidPlatformTest.java
https://issues.apache.org/jira/browse/NETBEANS-1342
Just hide the panel because the cordova.platforms.ios module is not available (see #856)
> [NETBEANS-1342] Hide the panel for iOS in the Mobile Platforms Options

- java/java.api.common/src/org/netbeans/modules/java/api/common/project/ui/EditRootAction.java
Well this is the proper fix for NETBEANS-1419. This does not need to be cherry picked as assertions are only enabled on non-release branch.
> [NETBEANS-1419] Fix assertion error on Java Projects when Edit JDK from popup menu.

- platform/o.n.bootstrap/src/org/netbeans/ModuleManager.java
- platform/o.n.bootstrap/test/unit/data/jars/fragment-module-missing-token.mf
- platform/o.n.bootstrap/test/unit/data/jars/fragment-module-missing-token/org/foo2/FragmentContent.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/ModuleManagerTest.java
This pull request fixes regressions against netbeans 9.0 introduced by #847 (NETBEANS-1147).
Broken use case:
Multiple eager OS specific fragments (Linux, MacOS, Windows) not working any more.
Main problem was a thrown AssertionError in case of an eager fragment with unsatisfied required token. 
For details see related issue: NETBEANS-1481.
> [NETBEANS-1481] Fix handling of eager module fragments (regression netbeans 9.0)

- ide/csl.api/test/unit/src/org/netbeans/modules/csl/api/test/CslTestBase.java
- php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion163432Test.java
- Fix `php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion163432Test.java`
- Fix `CslTestBase.checkCompletion()` method because unit tests may not fail when the `fail()` method is calld in `UserTask.run()` i.e. Don't call the `assertDescriptionMatches` method in the `UserTask.run` method. 
- Remove `@` from the prefix if the context is `EXPRESSION`
@tzezula Is the change for `CslTestBase` OK?
> Fix the unit test for CC in php.editor

- ide/dlight.nativeexecution/release/bin/nativeexecution/hostinfo.sh
The sed call in line 119 of hostinfo.sh does not correctly handle
backslashes in the escape sequence. The call to sed fails with:
sed: -e expression #1, char 6: unterminated `s' command
and the variable USER_D is set to the empty string.
> [NETBEANS-1727] Native Execution does not correctly sanitize username for temp directory

- nbbuild/packaging/snap/gui/netbeans.desktop
- nbbuild/packaging/snap/snapcraft.yaml
As we can provide convenience binary in form of a Snap package for Linux, the descriptor shall not mention "NetBeans IDE" but "Apache NetBeans IDE (incubating)". 
It has also marked as stable, so it can be distributed in latest/stable channel on snapcraft.io.
> [NETBEANS-1372] Snap Descriptor 

- ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/api/TestMethodNode.java
- ide/gsf.testrunner/src/org/netbeans/modules/gsf/testrunner/api/Testcase.java
- java/junit.ui/nbproject/project.properties
- java/junit.ui/src/org/netbeans/modules/junit/ui/actions/TestClassInfoTask.java
- java/junit/src/org/netbeans/modules/junit/api/JUnitTestcase.java
- java/maven.junit/src/org/netbeans/modules/maven/junit/JUnitOutputListenerProvider.java
See https://issues.apache.org/jira/browse/NETBEANS-1663.
I bumped the Java version for junit.ui to 8, let me know if this isn't okay.
If anyone has suggestions for how to test this automatically, please let me know. I tested this by hand on a project with `@ParameterizedTest` tests, as well as a mix of JUnit 5 and 4 regular `@Test` tests.
> NETBEANS-1663: Better support for JUnit 5 ParameterizedTest

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/CreateLicenseSummary.java
The current logging of `CreateLicenseSummary` task is too verbose. It steals focus during build with `F11` in the IDE. The output window output stops at 
```
init:
/incubator-netbeans/platform/libs.felix/build/classes/META-INF/LICENSE: written
All tests passed
```
message and doesn't scroll down. That is annoying as to see `BUILD SUCCESSFUL` or first real error one has to scroll down.
I guess we don't need to see the message at all, right @matthiasblaesing?
> Making CreateLicenseSummary logging less aggressive

- platform/core.windows/src/org/netbeans/core/windows/view/ui/AutoHidingMenuBar.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/view/ui/AutoHidingMenuBarManualTestApp.java
This avoids a "No runnable methods" error while running tests in the core.windows package, due to the AutoHidingMenuBarManualTest class having a name that ends with "Test" but no test methods in it. The class in question is kept around for manual testing purposes only, and is not intended to be run automatically. See https://github.com/apache/incubator-netbeans/pull/1060 .
> [NETBEANS-731] Rename AutoHidingMenuBarManualTest to fix test failure

- platform/o.n.bootstrap/test/unit/src/org/netbeans/SetupHid.java
- platform/o.n.core/nbproject/project.properties
Removing require.nb.javac=true, using -source/-target 8 instead of 6.
> Improving ability of o.n.core tests to pass on JDK 11.

- README.md
- harness/apisupport.harness/build.xml
- nbbuild/build.xml
- platform/o.n.bootstrap/build.xml
Added the possibility to build the Launchers instead of relaying on "third party" uploads. It can be enabled by adding -Ddo.build.windows.launchers=true to the ant command line.
I did my tests on Ubuntu, though I could not test the resulted binaries, so please test.
If someone'd know the software requirements on Windows, please share.
If you find this Ok and working, I'd reconfigure our buildjob to produce the Windows binaries this way.
> [NETBEANS-1145] Make Windows Launchers part of the build process.

- ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/FodDataObjectFactory.java
- ergonomics/ide.ergonomics/test/unit/src/org/netbeans/modules/ide/ergonomics/fod/FodDataObjectLineSetTest.java
I am trying to demo [Graal.js Maven demo](https://github.com/graalvm/graal-js-jdk11-maven-demo) debugging in NetBeans 10. However, if you want your breakpoint to stop in `.js` script, the *HTML5* support must have already been enabled. That's unfortunate. Making sure requesting `Line.Set` enables the support automatically.
CC @entlicher
> LineCookie.getLineSet() can enable disabled features

- nbbuild/templates/projectized.xml
I got a warning message saying:
[copy] Warning: Could not find file /root/NetBeansProjects/incubator-netbeans/usersguide/javahelp/org/netbeans/modules/usersguide/ide.css to copy.
Solution: changing the path of ide.css file in the template file nbbuild/templates/projectized.xml
from <copy tofile="${build.javahelp.dir}/org/netbeans/modules/usersguide/ide.css"
file="${nb_all}/usersguide/javahelp/org/netbeans/modules/usersguide/ide.css"
failonerror="false"/>
to 
<copy tofile="${build.javahelp.dir}/org/netbeans/modules/usersguide/ide.css"
file="${nb_all}/ide/usersguide/javahelp/org/netbeans/modules/usersguide/ide.css"
failonerror="false"/>
> Update projectized.xml to find the ide.css

- enterprise/j2ee.weblogic9/external/binaries-list
- enterprise/j2ee.weblogic9/src/org/netbeans/modules/j2ee/weblogic9/dd/jms1031/package-info.java
- enterprise/websvc.wsitmodelext/external/binaries-list
- enterprise/websvc.wsitmodelext/test/unit/src/org/netbeans/modules/websvc/wsitmodelext/resources/policy.xml
Clean up the licensing issues in Rat report: [https://builds.apache.org/job/incubator-netbeans-license/lastCompletedBuild/testReport/(root)/Cluster_%20not%20cluster/_module_enterprise_has_4_unapproved_license_s_/]
Note: j2ee.weblogic9 and websvc.wsitmodelext modules plan to remove from the release of the 'enterprise' cluster
> [NETBEANS-1074] : module review j2ee.weblogic9 and websvc.wsitmodelext

- java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/MarkOccurrencesHighlighterBase.java
- java/java.editor/src/org/netbeans/modules/java/editor/rename/InstantRenamePerformer.java
- java/java.hints/src/org/netbeans/modules/java/hints/bugs/InfiniteRecursion.java
- java/java.hints/src/org/netbeans/modules/java/hints/bugs/NPECheck.java
- java/java.hints/src/org/netbeans/modules/java/hints/control/RemoveUnnecessary.java
- java/java.hints/src/org/netbeans/modules/java/hints/introduce/Flow.java
- java/java.hints/src/org/netbeans/modules/java/hints/introduce/ScanStatement.java
- java/java.source.base/apichanges.xml
- java/java.source.base/nbproject/org-netbeans-modules-java-source-base.sig
- java/java.source.base/nbproject/project.properties
- java/java.source.base/src/org/netbeans/api/java/source/TreeUtilities.java
- java/refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/RenameTransformer.java
- java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/InstantRefactoringUIImpl.java
- java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/RenameRefactoringUI.java
In JDK 12, when we try to return a value with a break statement, (for example in a switch statement), for eg. 
`
String str = switch(i) {
case 1 :
System.out.println("one");
break "one";
default :
System.out.println("def");
break "def";
};
`
Currently, BreakTree extends from StatementTree, which means that the break statement cannot be used to assign a variable, but with the advent of JDK 12, break statement can be used to assign values to variables as mentioned above.
Now, BreakTree cannot be cast as an Expression Tree, and because of this Statement Tree is expected wherever getBreakContinueTarget is being called from.
> [NETBEANS-1728] fix for Exception encountered when break returns value

- groovy/gradle/src/org/netbeans/modules/gradle/GradleDaemon.java
- groovy/gradle/src/org/netbeans/modules/gradle/GradleDistributionManager.java
- groovy/gradle/src/org/netbeans/modules/gradle/GradleProjectCache.java
- groovy/gradle/src/org/netbeans/modules/gradle/Installer.java
- groovy/gradle/src/org/netbeans/modules/gradle/api/execute/RunUtils.java
- groovy/gradle/src/org/netbeans/modules/gradle/classpath/AbstractGradleScriptClassPath.java
- groovy/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
- groovy/gradle/src/org/netbeans/modules/gradle/options/GradleDistributionManager.java
- groovy/gradle/src/org/netbeans/modules/gradle/options/GradleOptionsController.java
- groovy/gradle/src/org/netbeans/modules/gradle/options/SettingsPanel.java
- groovy/gradle/src/org/netbeans/modules/gradle/queries/GradleSourceForBinary.java
- groovy/gradle/src/org/netbeans/modules/gradle/spi/GradleSettings.java
Well this set of patches makes Gradle project evaluation work on Java 11 even when the Gradle wrapper is below this version, by silently ignore the wrapper specified distribution for loading the project.
Also it contains the refactor of the GradleDistributionManager making it a real class instead of a bunch of utility functions. Now it takes the gradle user home to create one. Though, right now the plugin does not support switching between gradle user home directories, this refactor is one step further to that support.
Removed the automatic install of Gradle from the startup.
Filed leaking private internals through GradleSettings as getVersion() returned a module private NbGradleVersion type.
> [NETBEANS-1970] Gradle projects are not loading on java 11

- groovy/gradle/src/org/netbeans/modules/gradle/GradleDistributionManager.java
GradleDistributionManager.java is using System.getProperty("java.version") to detect JDK version, but that property may be e.g. "13-internal", and then Integer.parseInt throws an exception.
I'd like to propose to use java.specification.version, which should be an easier to handle number:
jshell> System.getProperty("java.version")
$1 ==> "13-internal"
jshell> System.getProperty("java.specification.version")
$2 ==> "13"
> Using java.specification.version to read the version of the JDK.

- ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java
- ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/TextDocumentSyncServerCapabilityHandler.java
-following TextDocumentSyncKind requestes
-sending client configuration also when connecting to a server manually
-prevent NPE when closing IDE when a server is configured manually
> Some more fixes for the Language Server Protocol client:

- ide/libs.graalsdk/external/binaries-list
- ide/libs.graalsdk/external/graal-sdk-1.0.0-license.txt
- ide/libs.graalsdk/nbproject/project.properties
- ide/libs.graalsdk/nbproject/project.xml
- ide/libs.graalsdk/test/unit/src/org/netbeans/libs/graalsdk/GraalEnginesTest.java
- nbbuild/travis/scripting.sh
- webcommon/libs.graaljs/external/binaries-list
- webcommon/libs.graaljs/external/js-1.0.0-license.txt
- webcommon/libs.graaljs/nbproject/project.properties
- webcommon/libs.graaljs/nbproject/project.xml
- webcommon/libs.truffleapi/external/binaries-list
- webcommon/libs.truffleapi/external/truffle-api-1.0.0-license.txt
- webcommon/libs.truffleapi/nbproject/project.properties
- webcommon/libs.truffleapi/nbproject/project.xml
Essential fixes to make NetBeans work with Graal.js got into RC12 - hence we can update the dependencies and uncomment the test on GraalVM RC12. Once these updates are in the work on #1092 can continue, as the RC12 version of Graal.js fixes the flaw discovered by @jlahoda.
> Updating Graal.js and co. to RC12

- java/maven.coverage/src/org/netbeans/modules/maven/coverage/MavenCoverageProvider.java
Adding additional check for plugin executions if the JaCoCo outputDirectory is customised within an execution
> [NETBEANS-1768] CodeCoverage doesn't work when custom outputDirectory is used in a PluginExecution

- platform/masterfs/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/FileObjectFactory.java
- platform/masterfs/test/unit/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/FileObjSymlinkTest.java
However, this may be not the right solution to solve the burning CPU on broken symlinks, I think there is no harm to include this one till the FS masters come up with the right solution.
I've opened https://issues.apache.org/jira/browse/NETBEANS-1845 for tracking that.
> [NETBEANS-168] Simple least intrustive patch prevent IDE to burn CPU on broken symlinks.

- java/java.hints/src/org/netbeans/modules/java/hints/errors/VarCompDeclaration.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/errors/VarCompDeclarationTest.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/infrastructure/ErrorHintsTestBase.java
The PR fixed the following test cases failures after changes in position of trees in compound var declaration:
[junit] Testcase: testVarCompoundDeclaration1(org.netbeans.api.java.source.gen.VarCompoundDeclarationTest): FAILED
[junit] Testcase: testVarCompoundDeclaration2(org.netbeans.api.java.source.gen.VarCompoundDeclarationTest): FAILED
[junit] Testcase: testVarCompoundDeclaration3(org.netbeans.api.java.source.gen.VarCompoundDeclarationTest): FAILED
[junit] Testcase: testVarCompoundDeclaration4(org.netbeans.api.java.source.gen.VarCompoundDeclarationTest): FAILED
[junit] Testcase: testCase1(org.netbeans.modules.java.hints.errors.VarCompDeclarationTest): FAILED
[junit] Testcase: testCase2(org.netbeans.modules.java.hints.errors.VarCompDeclarationTest): FAILED
[junit] Testcase: …
> [NETBEANS-1251] nb-javac 11 testcase failure : Compound var declaration

- groovy/gradle.persistence/nbproject/project.xml
- groovy/gradle.persistence/src/org/netbeans/modules/gradle/persistence/GradlePersistenceProvider.java
- groovy/gradle.persistence/src/org/netbeans/modules/gradle/persistence/PersistenceLocationProviderImpl.java
- groovy/gradle.persistence/src/org/netbeans/modules/gradle/persistence/PersistenceScopeImpl.java
- groovy/gradle.persistence/src/org/netbeans/modules/gradle/persistence/PersistenceScopeProviderImpl.java
The module we are depending on is org.netbeans.modules.j2ee.persistenceapi has a version 1.40.0 it has the include implementation version checkbox ticked in and its implementation version is 1.
Shall I mark the dependency as 1.40.0.1 instead?
Telling the truth I could not reproduce the CNFE locally, but I just have one project where I can test this an it works there.
The other part of the commit is just Maven -> Gradle renames.
> [NETBEANS-2121] Updated dependency version on our Java EE support modules.

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/CreateLicenseSummary.java
- nbbuild/build.xml
According to [NETBEANS-1995](https://issues.apache.org/jira/browse/NETBEANS-1995) report the `LICENSE` file contains references to files from `extra` cluster. However that one isn't included in the final ZIP. As such there is no need to include those files in the NOTICE file.
Adjusting the build tasks and scripts to exclude `extra/**` files.
> [NETBEANS-1995] Exclude extra cluster when generating LICENSE file

- ergonomics/ide.ergonomics/enterprise.properties
Tried @JaroslavTulach instructions in https://issues.apache.org/jira/browse/NETBEANS-2125, and it works, so here it is.
> [NETBEANS-2125] Enable Oracle JS Parser to be installed with Java EE

- enterprise/glassfish.common/manifest.mf
- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/wizards/AddServerLocationVisualPanel.form
- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/wizards/AddServerLocationVisualPanel.java
- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
What this pull request does in a nutshell
---------------------------------------------
Expands on #1141 by:
- Removing the JOptionDialog to select a version of GlassFish to download, and moving that functionality to the JPanel in the Wizard
- Amending the ServerDetails enums to include a URL to the appropriate license (Oracle / EF) for each GlassFish version supported
- Button to open license now checks selected version of GlassFish and opens browser pointing to correct license from ServerDetails
- Fixes a tiny typo in #1141 (typo was probably actually copied from my instructions in Jira!)
API Changes
--------------
org.netbeans.modules.glassfish.common.ServerDetails now has a new public method, getLicenseUrl() that returns the URL for a given version of GlassFish
I have incremented the …
> [NETBEANS-2182] Display correct licence (Oracle / Eclipse Foundation) depending on version of GlassFish to download

- platform/openide.explorer/src/org/openide/explorer/ExplorerManager.java
Use correct index variable when copying validated nodes; this was originally
reported by me in 2015, original issue is at
https://netbeans.org/bugzilla/show_bug.cgi?id=257181
> Fix ExplorerManager#setSelectedNodes()

- ide/subversion/src/org/netbeans/modules/subversion/client/cli/commands/VersionCommand.java
If dev version of the SVN client is used together with Netbeans, many operations over SVN versioned projects fail because of NumberFormatException.
> [NETBEANS-1936] Removing the SVN client version suffix before parsing the number

- enterprise/javaee7.api/src/org/netbeans/modules/javaee7/api/javaee-endorsed-api-7.0.xml
Version 1 of the library grammar did not support properties. The addition
of the information about maven dependencies broke loading of the library
definition.
> [NETBEANS-2126] Use correct grammar for javaee-endorsed-api-7.0.xml

- groovy/gradle/src/org/netbeans/modules/gradle/GradleProjectCache.java
- groovy/gradle/src/org/netbeans/modules/gradle/NbGradleProjectFactory.java
- groovy/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java
- groovy/gradle/src/org/netbeans/modules/gradle/api/GradleProjects.java
- groovy/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
- groovy/gradle/src/org/netbeans/modules/gradle/spi/GradleFiles.java
Not a complete solution on NETBEANS-2009 Gradle sub-project detection, but allows to load sub-projects when the root project is loaded in the IDE. The complete solution would require some architectural changes which could go into NetBeans 12.0.
> [NETBEANS-2009] Improve Gradle sub-project Detection

- platform/core.windows/src/org/netbeans/core/windows/options/LafPanel.java
Added a way to enable in process LaF changes.
Just add -J-Dnb.laf.norestart=true to the netbeans launch options to test it.
> [NETBEANS-1402] Added nb.laf.norestart system property to prevent restart on LaF changes

- harness/apisupport.harness/windows-launcher-src/app.exe.manifest
- nb/ide.launcher/windows/netbeans.exe.manifest
- nb/ide.launcher/windows/netbeans64.exe.manifest
- nb/ide.launcher/windows/version.h
- platform/o.n.bootstrap/launcher/windows/nbexec.exe.manifest
- platform/o.n.bootstrap/launcher/windows/version.h
Well in the unlikely event of releasing a 11.0-vc5 it could be useful to have a Windows Launcher version update as well.
> [NETBEANS-2303] Update version number on Windows Launchers

- platform/core.network/src/org/netbeans/core/network/utils/LocalAddressUtils.java
Simple typo but with devastating effect: `&` should have been `&&`. This caused an NPE when NetBeans was used with a VPN connection. 
This fixes [NETBEANS-1775](https://issues.apache.org/jira/browse/NETBEANS-1775).
> [NETBEANS-1775] Fix for NPE

- platform/api.htmlui/src/org/netbeans/modules/htmlui/NbBrowsers.java
@sdedic reported an exception when `--laf com.sun.java.swing.plaf.motif.MotifLookAndFeel` is used. Then:
```
java.io.IOException: Could not connect to URL nbres:/org/netbeans/modules/htmlui/css/wizard-CDE/Motif.css. No such resource was found. 
at org.netbeans.core.startup.NbResourceStreamHandler$Connection.connect(NbResourceStreamHandler.java:118) 
at com.sun.webkit.network.URLLoader.sendRequest(URLLoader.java:368) [catch] 
at com.sun.webkit.network.URLLoader.doRun(URLLoader.java:164) 
at com.sun.webkit.network.URLLoader.lambda$run$98(URLLoader.java:129) 
at java.security.AccessController.doPrivileged(Native Method) 
at com.sun.webkit.network.URLLoader.run(URLLoader.java:128) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at …
```
> Only load the custom CSS when the LaF is one of the recognized ones

- groovy/gradle/manifest.mf
I used this OpenIDE-Module-Requires: cnb.org.netbeans.modules.groovy.kit before integrating the plugin into the main. Though I had to remove it during the Groovy <-> Gradle dependency change when the Groovy feature was depending on Gradle. Now this has been changed, so adding this glue shall help in some cases when the Gradle kit is enabled without the Groovy kit.
> [NETBEANS-2378] Tighten the Groovy more to the Gralde plugin

- platform/o.n.swing.tabcontrol/manifest.mf
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/ButtonPopupSwitcher.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/DocumentSwitcherTable.java
The attached patch fixes two rare but irritating NPEs from the popup switcher: If enough files are open that the popup switcher has two columns, but there is an odd number of files open, then the final item in the right column of the table has no item - but the code assumed it would always be non-null, so hovering or clicking the close button area on that spot generates a NullPointerException.
> Popupswitcher npe fixes

- README.md
`uihandler/arch.xml` was moved in 3dfe01225c66a7b6438801621b4d111f946e64b5 and thus the instructions from `README.md` no longer work out of the box
> uihandler/arch.xml → platform/uihandler/arch.xml

- java/java.api.common/src/org/netbeans/modules/java/api/common/project/ActionProviderSupport.java
Well a null check would be trivial to place there, however the JavaSource.create() method can return null an it is called at least 779 places all over the IDE. Almost none of them being guarded against the case when it returns null.
Instead of null, shan't we return some dummy instance?
> [NETBEANS-2466] Guard JavaSource.create() result against possible NPE.

- ide/options.editor/src/org/netbeans/modules/options/colors/SyntaxColoringPanel.java
In the Options Dialog, the Panel "Fonts & Colors" and there the subpanel
Syntax Pane relies on undocumented ActionEvent#getModifiers behavior.
The currently choosen language is only updated when:
- the new language is acknowledged with a space/enter keypress
- or choosen with a left mouse click
Two problems:
1. The language in the combobox and the currently select language can
drift apart. (use only cursor keys to change selection)
2. On Ubuntu Linux (OpenJDK 1.8u191) it was observed, that the
undocumented behaviour, the action handler relied on, was not
present.
Both problems are solved by using the default behaviour of the JComboBox:
Everytime the selection changes and action event is fired, regardless
of the source of the selection change.
> [NETBEANS-2274] Remove special casing of JComboBox handling in language chooser

- groovy/gradle/src/org/netbeans/modules/gradle/GradleDataObject.java
This fixes the startup message:
> WARNING [org.openide.filesystems.Ordering]: Not all children in Services/MIMEResolver/ marked with the position attribute: [org-netbeans-modules-gradle-GradleDataObject-Extension.xml], but some are: [org-openide-loaders-DataLoaderPool$InstanceLoaderSystem-Extension.xml, org-netbeans-core-startup-layers-SystemFileSystem-Extension.xml, org-netbeans-modules-java-JavaDataObject-Extension.xml, [...]
> Add position info to gradle extension registration

- java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java
- java/java.hints/src/org/netbeans/modules/java/hints/errors/DifferentCaseKindsFix.java
- java/java.hints/src/org/netbeans/modules/java/hints/errors/Utilities.java
- java/java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertSwitchToRuleSwitch.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertSwitchToRuleSwitchTest.java
- java/java.source.base/src/org/netbeans/api/java/source/WorkingCopy.java
- java/java.source.base/src/org/netbeans/modules/java/source/TreeShims.java
- java/java.source.base/src/org/netbeans/modules/java/source/pretty/VeryPretty.java
- java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
- java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
- java/java.source.base/src/org/netbeans/modules/java/source/save/Reindenter.java
- java/java.source.base/test/unit/src/org/netbeans/api/java/source/gen/SwitchExpressionTest.java
- java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java
Convert old switch statement to switch expression in following case:
Old code:  (Assign same variable in every case with one statement)
int x = 5;
String s = "foo";
switch (x)
{ case 1: s = "bar";break; case 2: s = "baz";break; default: s = "zuq";break; }
After fix:
int x = 5;
String s = switch (x)
{ case 1 -> "bar"; case 2 -> "baz"; default -> "zuq"; }
;
> [NETBEANS-2349] Convert switch to switch expression

- ide/utilities/src/org/netbeans/modules/openfile/RecentFileAction.java
- ide/utilities/src/org/netbeans/modules/openfile/RecentFiles.java
- update menuItems under RecentFileAction via a RecentFiles property change listener, rather than popup menu listener
> NETBEANS-888 Open Recent file not working

- nbbuild/packaging/snap/gui/netbeans.desktop
- nbbuild/packaging/snap/snapcraft.yaml
Well, i did not give up on having a "rolling" release for testing from the master branch. It needs a different snap package name: netbeans-dev, so it could be private or public but hidden from the store (those who knew the name would be able to install it). Right now the package is being kept private.
So having these files in place and: https://builds.apache.org/job/netbeans-snap-weekly-master
We could have an auto updated test version from master by every Saturday morning. (Unfortunately Linux only)
> [NETBEANS-2119] Let the netbeans-dev Snapcraft package happen

- README.md
Point to https://builds.apache.org/job/netbeans-linux, not https://builds.apache.org/job/incubator-netbeans-linux.
> Updating README to point to point to job

- php/php.editor/nbproject/project.properties
- php/php.editor/nbproject/project.xml
- webcommon/javascript2.editor/nbproject/project.properties
https://issues.apache.org/jira/browse/NETBEANS-2437
- Fix nashorn.prepend and bootclasspath.prepend of project.properties
I've fixed the project.properties. However, `org.netbeans.modules.php.editor.js.JsFormatterEmbeddedTest` fail yet. Other than that, tests passed.
(Once I've installed Oracle JS Parser Implementation manually, `JsFormatterEmbeddedTest` passed. i.e. Ran the module then installed the plugin)
Do you have any ideas?
<details>
<summary>Warning</summary>
```
Warning - could not install some modules:
org.netbeans.libs.nashorn - No module providing the capability com.oracle.js.parser.implementation could be found.
org.netbeans.modules.javascript2.doc - The module org.netbeans.libs.nashorn would also need to be installed.
org.netbeans.modules.javascript2.model - The module …
```
> [NETBEANS-2437] Unit tests of php.editor fail

- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/source/Source.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/source/SourceFilesCache.java
Separate Truffle source caches between multiple runs of the JPDA debugger.
When debugging Truffle script that is changing (after restarting the debugee process), the debugger doesn't reflect the code change and shows always the previous code.
This fix addresses that by using different SourceFilesCache per each debugging session. CC @entlicher
> Separate Truffle source caches between multiple debugging sessions.

- platform/libs.felix/manifest.mf
export org.apache.felix.resolver.reason; partially related to NETBEANS-1638
as far as the most recent comments by Markus Sunela are concerned.
> [NETBEANS-1638] export org.apache.felix.resolver.reason 

- webcommon/javascript2.jade/src/org/netbeans/modules/javascript2/jade/editor/JadeCodeCompletion.java
- webcommon/javascript2.jade/test/unit/src/org/netbeans/modules/javascript2/jade/editor/JadeAutoCompletionTest.java
*What this PR does*
Enables auto-completion pop-up when typing in a Jade template file
*Files Changed*
* webcommon/javascript2.jade/src/org/netbeans/modules/javascript2/jade/editor/JadeCodeCompletion.java
getAutoQuery() method updated to check that typed text is not null, is greater than length of 0 and does not have whitespace at the end (because the dialog popping up after a space, tab or newline would be annoying).  If these criteria are met, code completion dialog will pop up
* webcommon/javascript2.jade/test/unit/src/org/netbeans/modules/javascript2/jade/editor/JadeAutoCompletionTest.java
Tests that the code completion pop-up is only activated if the correct criteria are met (i.e. one or more characters are typed, and the final character isn't a whitespace character)
> [NETBEANS-39] Fix for no code completion in Jade files while typing

- harness/apisupport.harness/release/etc/app.conf
- harness/apisupport.harness/release/launchers/app.sh
#573 removed the variable `default_mac_userdir` from the app.conf, but the shell script was still using that variable which results in incorrect userdir. It also should check for the old variable in case the RCP app was build with a custom app.conf that has the old variable.
* Remove extra " in app.conf 
* Check for old `default_mac_userdir` variable in case RCP has a custom app.conf with old settings; otherwise use `default_userdir`
> [NETBEANS-2361] Fix app.conf and launcher on macOS after changes in #573

- groovy/gradle/nbproject/project.xml
- groovy/gradle/src/org/netbeans/modules/gradle/NbGradleProjectFactory.java
- groovy/gradle/test/unit/src/org/netbeans/modules/gradle/NbGradleProjectFactoryTest.java
Try NetBeans 11 and do: New project -> Java with Maven -> Java Frontend Application -> ... -> Run on iOS devices + Use Multi OS Engine (needs Mac). Then create the project...
Nested `client-moe` project is recognized as Gradle, while it is a nested Maven project. The IDE gets totally confused by that.
This fix mitigates the situation by preferring Maven over Gradle, if parent folder is also Maven, but not Gradle. Is it OK this way, @lkishalmi?
> Java with Maven -> Java Frontend App + MOE is broken since Gradle support introduced

- groovy/gradle.htmlui/nbproject/project.properties
- groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/GradleArchetype.java
- groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/app_build.gradle.fmk
- groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/desktop_build.gradle.fmk
- groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/root_build.gradle.fmk
- groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/settings.gradle.fmk
- groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/web_build.gradle.fmk
- groovy/gradle.htmlui/test/unit/src/org/netbeans/modules/gradle/htmlui/CreateArchetypeTest.java
- groovy/gradle/arch.xml
- groovy/gradle/src/org/netbeans/modules/gradle/ActionProviderImpl.java
- platform/api.htmlui/src/org/netbeans/api/htmlui/HTMLComponent.java
The HTML UI wizard needs some improvements to be considered stable.
- people reported problems with `app` subproject - let's comment it out for forthcoming release
- let's add a test to verify the generated project really builds - needs API for synchronous build execution
- using "Run" doesn't work first time, only second time
CC @lkishalmi , @neilcsmith-net
> Polishing Gradle HTML UI

- enterprise/cloud.amazon/src/org/netbeans/modules/cloud/amazon/ui/serverplugin/Bundle.properties
*What this PR does*
Fixes an exception preventing the Server wizard panel being displayed for AWS Elastic Beanstalk servers
*Root cause*
In the file `/enterprise/cloud.amazon/src/org/netbeans/modules/cloud/amazon/ui/serverplugin/Bundle.properties` there are the following entries:
```
AmazonJ2EEServerWizardComponent.envFullURLLabel.text=\ \
AmazonJ2EEServerWizardComponent.containerLabel.text=Container Type:
```
Having a \ as the last character on the `AmazonJ2EEServerWizardComponent.envFullURLLabel.text=\ \` entry causes Java to consider the text on the following line as part of the value of the AmazonJ2EEServerWizardComponent.envFullURLLabel.text property.
Hence the AmazonJ2EEServerWizardComponent.containerLabel.text property can't be found when the Server Wizard tries to render
*Files …
> [NETBEANS-2306] Fix for missing resource AmazonJ2EEServerWizardComponent.containerLabel.text

- java/maven/build.xml
[NETBEANS-2639](https://issues.apache.org/jira/browse/NETBEANS-2639)
The bundled Maven is [built to Java 7](https://github.com/apache/maven/blob/maven-3.3.9/pom.xml#L46-L47) so we cannot build the spy module against Java 8 as https://github.com/apache/netbeans/pull/1144 did—it will not link. Same for the [current release](https://github.com/apache/maven/blob/maven-3.6.1/pom.xml#L50-L51). Java 5 is too old for JDK 11 javac, which only supports 6 and later, so we can choose 6 or 7.
> [NETBEANS-2639] Compile mavensrc to Java 7, not 8

- ide/editor.breadcrumbs/src/org/netbeans/modules/editor/breadcrumbs/BreadCrumbComponent.java
- java/java.source/src/org/netbeans/modules/java/ui/Icons.java
- java/jshell.support/src/org/netbeans/modules/jshell/editor/CommandCompletionProvider.java
- platform/core.windows/src/org/netbeans/core/windows/view/EditorView.java
- platform/core.windows/src/org/netbeans/core/windows/view/ui/TabbedHandler.java
- platform/core.windows/src/org/netbeans/core/windows/view/ui/slides/TabbedSlideAdapter.java
- platform/core.windows/src/org/netbeans/core/windows/view/ui/tabcontrol/AbstractTabbedImpl.java
- platform/core.windows/src/org/netbeans/core/windows/view/ui/toolbars/DnDSupport.java
- platform/core.windows/src/org/netbeans/core/windows/view/ui/toolbars/ToolbarRow.java
- platform/openide.explorer/src/org/openide/explorer/view/NodeRenderDataProvider.java
- platform/openide.util.ui/src/org/openide/util/CachedHiDPIIcon.java
- platform/openide.util.ui/src/org/openide/util/FilteredIcon.java
- platform/openide.util.ui/src/org/openide/util/ImageUtilities.java
- platform/openide.util.ui/src/org/openide/util/VectorIcon.java
- platform/openide.util.ui/test/unit/src/org/openide/util/ImageUtilitiesTest.java
This PR contains most of the changes that are needed to make ImageUtilities work with HiDPI icons. No publicly visible API changes are needed; the old javax.swing.Icon interface is actually well-suited for providing scalable graphics. The main challenge is to ensure that conversions between javax.swing.Icon and java.awt.Image, which are frequent throughout the NetBeans codebase, always retain the underlying scalable Icon instance.
The main motivation for this PR is to enable SVG icon support, which I will contribute in a separate PR. There's an added bonus, though: With all icon painting now centralized through ImageUtilities.ToolTipImage.paintIcon, we can add some rendering tweaks that make existing low-resolution icons look slightly better on HiDPI displays. See the attached …
> [NETBEANS-2614,NETBEANS-1586] Improve icon scaling on HiDPI displays, and prepare ImageUtilities for HiDPI icons

- nbbuild/antsrc/org/netbeans/nbbuild/ModuleSelector.java
I have essentially swapped two pieces of code: the *explicit* information from NB installation (`update_tracking/*.xml`) takes precedence.
Original behaviour:
- if a file that *just happens* to be an OSGi bundle (or NB module) is present anywhere, it's filtered according to excluded modules
- filters out also `mave/lib` contents, which is not managed by NB module system, but contains libraries supporting embedded maven
New behaviour:
- the Platform defines what module the file belongs to. Maven libraries, although OSGi bundles themselves, will be attributed to maven embedder module
- if not defined, and the file contains NB module or OSGi bundle manifest, it will be recognized as a module itself
> [NETBEANS-2577] Prevent Maven libraries from being exluded

- nb/updatecenters/src/org/netbeans/modules/updatecenters/resources/Bundle.properties
- nb/updatecenters/src/org/netbeans/modules/updatecenters/resources/mf-layer.xml
NetBeans daily builds contain obsolete and no longer working update centres. This pull request attempts to resolve the problems by removing the useless UCs and leaving just two: one for modules from the latest standard distribution and one for modules from the latest plugin portal version.
More details in #[NETBEANS-2657](https://issues.apache.org/jira/browse/NETBEANS-2657)
> [NETBEANS-2657] - Removing obsolete update centers from daily builds

- java/java.hints/src/org/netbeans/modules/java/hints/resources/jdk11.properties
- java/java.hints/src/org/netbeans/modules/java/hints/resources/layer.xml
Removed Configurations for JDK5, 7. Renamed JDK 10 config as JDK11. No new hints were added for JDK 11 hence no config was added but since it's LTS release, it's better to support config for JDK 11.
> NETBEANS-2656 remove old JDK migrators under Inspect and Transform

- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/windows8/DPISafeBorder.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/windows8/Windows8LFCustoms.java
This patch improves the appearance of various main window borders under fractional HiDPI scaling factors (e.g. 150%). This applies only on Windows for now. See https://issues.apache.org/jira/browse/NETBEANS-2646 .
This PR does not depend on any of the other HiDPI-related PRs.
See the attached screenshots (view at 100% scaling).
> [NETBEANS-2646] Improve tabcontrol border appearance (HiDPI)

- ide/api.debugger/manifest.mf
- ide/api.debugger/src/org/netbeans/api/debugger/DebuggerInfo.java
- java/api.debugger.jpda/apichanges.xml
- java/api.debugger.jpda/manifest.mf
- java/api.debugger.jpda/nbproject/project.properties
- java/api.debugger.jpda/nbproject/project.xml
- java/api.debugger.jpda/src/org/netbeans/api/debugger/jpda/ListeningDICookie.java
- java/api.debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/StartListeningTest.java
- java/debugger.jpda/nbproject/project.xml
- java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/ListeningDICookieTest.java
It's possible to create a JPDA connection listener on a random port via standard API.
> Listening on random port made possible with ListeningDICookie.create(-1)

- java/java.source.base/src/org/netbeans/modules/java/source/indexing/APTUtils.java
Fixed a livelock in `APTUtils` reported by @JaroslavTulach happening for huge number of dependent projects (GraalVM J2SE Projects). See [stack.txt](https://github.com/apache/netbeans/files/3301837/stack.txt).
> Fixed livelock in APTUtils happening for huge number of dependent prjs.

- java/java.project/apichanges.xml
- java/java.project/manifest.mf
- java/java.project/src/org/netbeans/spi/java/project/support/ProjectPlatform.java
The mx project are not Ant based, they do not have `PropertyEvaluator`.
Added a new `ProjectPlatform.forProject` method for non Ant based projects.
> Added support for per-project platform for mx projects.

- nbbuild/packaging/snap/gui/netbeans.desktop
- nbbuild/packaging/snap/snapcraft.yaml
These changes are required to be able to release NetBeans 11.1 as a Snap package.
> [NETBEANS-2688] Update the Snap descriptors for 11.1

- java/java.source.base/src/org/netbeans/api/java/source/TypeUtilities.java
- java/java.source.base/test/unit/src/org/netbeans/api/java/source/TypeUtilitiesTest.java
Consider this code:
---
public class TestVar {
var v = get();
}
private static <Z extends C & I> Z get() {
return null;
}
public static class C {}
public static interface I {}
}
---
Now, press Ctrl and hover over the "v" in "var v = get();". There will be a tooltip saying "<unknown>", which is wrong. The type of the variable is an intersection type, and the type printer does not know how to print it. With this patch, the printed type will be "TestVar.C & TestVar.I".
> When printing types, print intersection types properly.

- java/java.hints/src/org/netbeans/modules/java/hints/errors/Utilities.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertSwitchToRuleSwitchTest.java
…fault case without break
The PR is bug fix for PR#1193 (https://issues.apache.org/jira/browse/NETBEANS-2349) which is part of NB-11.1 release
Convert old switch statement to switch expression in following case:
Old code:  (Assign same variable in every case with one statement)
int x = 5;
String str = "foo";
switch (str)
{ case 1: str = "bar";break; case 2: str = "baz";break; default: str = "zuq" }
expected fix:
int x = 5;
String s = switch (str)
{ case 1 -> "bar"; case 2 -> "baz"; default -> "zuq"; }
But the hint is disabled in above scenario.
> [NETBEANS-2745]:Fixed Convert Switch to Switch-Expression hint for default case without break

- webcommon/libs.graaljs/nbproject/project.xml
- webcommon/libs.graaljs/test/unit/src/org/netbeans/libs/graaljs/GraalJSTest.java
- webcommon/libs.truffleapi/manifest.mf
- webcommon/libs.truffleapi/nbproject/project.xml
@lbruun reported that the PAC proxy configuration is broken after my #1092. Alas, it is. The problem isn't in the code, but in the packaging. One NetBeans wrapper module forget to export new API package `com.oracle.truffle.api.library`.
The fix exports the package and enhances the tests to verify that the `GraalVM:js` is capable to execute JavaScript even inside of the NetBeans Runtime Container with all the ClassLoader checks being on. 
Sorry for the trouble.
> [NETBEANS-2764] NoClassDefFoundError: com/oracle/truffle/api/library/Library

- groovy/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceForRepository.java
While this not entirely fix the issue, placing the Project based Source for binary query (position 100) in front of this one allows the heuristics finding source/javadoc jars work when these jars are inside of a Gradle project.
I think this is pretty safe to be included into 11.1
> [NETBEANS-2755] Corrected the position of Source for Binary Query for Gradle Repositories.

- nbbuild/installer/engine/src/org/netbeans/installer/wizard/components/panels/netbeans/NbPreInstallSummaryPanel.java
Show Check for Updates in Windows and Linux Installer wizards -
> add check-for-updates chkbox in install wizard

- nb/welcome/src/org/netbeans/modules/welcome/ui/BottomBar.java
Just noticed that we have an Apache Incubator logo in the BottomBar of the Start Page.  This just comments out and adds the vertical padding to the Apache logo, pending a decision post-NB11.1 what we want there.
> Comment out Apache Incubator logo on Start Page.

- enterprise/j2ee.kit/nbproject/project.xml
It seems that ergonomics is not triggering enabling of the Payara Micro module and ends up in some sort of loop in the wizard iterator.  This adds the Payara Micro module as a dependency in j2ee.kit.  It seems to fix the issue, but I'm not sure it's the right approach to this problem?  PR against release branch for now in case we want to use this in NB 11.1 and fix differently in master.  Can re-roll against master if required.
> Add Payara Micro dependency in j2ee.kit

- javafx/javafx2.kit/nbproject/project.xml
- javafx/openjfx.samples/nbproject/project.properties
- nbbuild/cluster.properties
Add OpenJFX samples module to JavaFX cluster, and add as dependency to javafx2.kit to enable via ergonomics.  Again against release branch - review and add to master post-release when plugin centers for dev are fixed.
> Get OpenJFX samples working in release branch.

- java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/tree/FolderTreeElement.java
Well, the potential bug is in line 119, assigning wrong starting index for the array copy.
Just rewrote the part using collections and for safety and better readability.
It can be easily triggered by Gradle projects as they have can many source groups.
Already reported as: NETBEANS-2354, NETBEANS-2630 as well.
While I feel this as safe to be included in 11.1, the decision is in @neilcsmith-net hands, as this is quite late.
> [NETBEANS-2794] Fix possible ArrayOutOfBoundException when during refactoring.

- groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/desktop_build.gradle.fmk
- groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/root_build.gradle.fmk
- groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/web_build.gradle.fmk
While testing the NetBeans 11.1 vc1 it turned out that Gradle Frontend Application project cannot be executed on JDK11, only on JDK8. The workaround is to run the IDE on JDK8, or change the project's JDK to JDK8, but given that many users use newer JDKs, having the support only on JDK8 would cause a lot of confusion when trying this new great NetBeans feature!
If possible, let's backport this to 11.1 next voting candidate (if any). CCing @neilcsmith-net , @lkishalmi 
The steps to reproduce the error are:
* start NetBeans 11.1 vc1 with an empty user directory and on JDK11: `/netbeans-11.1-vc1/bin/netbeans --userdir /tmp/ud11 --jdkhome /jdk-11`
* New Project/Java with Gradle/Java Frontend Application
* Download and Activate - installs NbJavac and JavaFX wrapper modules
* Generate the …
> Let Gradle Frontend Application run on JDK11

- .travis.yml
- ide/api.xml/test/unit/src/org/netbeans/api/xml/parsers/SAXEntityParserTest.java
Fix SAXEntityParserTest test class in api.xml module.
```
Testcase: testParse(org.netbeans.api.xml.parsers.SAXEntityParserTest):	Caused an ERROR
SAX2 driver class org.apache.crimson.parser.XMLReaderImpl not found
org.xml.sax.SAXException: SAX2 driver class org.apache.crimson.parser.XMLReaderImpl not found
java.lang.ClassNotFoundException: org.apache.crimson.parser.XMLReaderImpl
at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:230)
at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:221)
at org.netbeans.api.xml.parsers.SAXEntityParserTest.testParse(SAXEntityParserTest.java:60)
at org.netbeans.junit.NbTestCase.access$200(NbTestCase.java:77)
at org.netbeans.junit.NbTestCase$2.doSomething(NbTestCase.java:460)
at …
```
> Fix SAXEntityParserTest test class in api.xml module

- platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java
The current field
```map```
https://github.com/apache/netbeans/blob/master/platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java#L112
is typically protected by synchronization on ```this```, e.g., 
https://github.com/apache/netbeans/blob/master/platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java#L386
https://github.com/apache/netbeans/blob/master/platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java#L390
https://github.com/apache/netbeans/blob/master/platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java#L426
For a total of 16 locations.
However, in these two places, ```map``` is not protected by synchronization:
https://github.com/apache/netbeans/blob/master/platform/openide.filesystems/src/org/openide/filesystem …
> HashMap is not thread safe. Field map is typically synchronized by this. However, in two places, field map is not protected with synchronized.

- platform/core.windows/src/org/netbeans/core/windows/services/NbPresenter.java
In the NB Dialog API, the JOptionPane is wrapped on a JPanel and the buttons moved on another panel. This leads to UI issues when the Look & Feel defines a special border for JOptionPane. The goal of this change is to retrieve the border defined by the L&F and apply it at the content pane level. Doing that we reduce inconsistencies between dialogs opened through the Java APIs or through the Netbeans APIs.
> [NETBEANS-2667] Manage JOptionPane border

- java/maven/src/org/netbeans/modules/maven/nodes/DependenciesNode.java
This PR fixes [NETBEANS-2783](https://issues.apache.org/jira/browse/NETBEANS-2783).
One liner, no side effects introduced as far I can tell. Tested also with a maven modular project under JDK-11.
> [NETBEANS-2783] Fix missing dependencies nodes in Project view when editing POM file

- ide/api.java.classpath/test/unit/src/org/netbeans/api/java/classpath/ClassPathTest.java
Fix ClassPathTest in ide/api.java.classpath module.
Command to run this test.
```bash
ant -f ide/api.java.classpath -Dtest.type=unit -Dcontinue.after.failing.tests=true -Dtest.includes=org/netbeans/api/java/classpath/ClassPathTest.java test-single
```
> Fix ClassPathTest in ide/api.java.classpath module

- platform/masterfs.macosx/src/org/netbeans/modules/masterfs/watcher/macosx/OSXNotifier.java
- platform/masterfs.nio2/src/org/netbeans/modules/masterfs/watcher/nio2/NioNotifier.java
- platform/masterfs.windows/src/org/netbeans/modules/masterfs/watcher/windows/WindowsNotifier.java
Well, this change makes the existing NIO2 based file notifier implementation in fornt of the platform dependent ones (Positions: Windows: 100, MacOS: 300, Linux: 500)
However this is trivial change, I feel a bit late for 11.1, so I propose to merge it into master after the 11.1 is out.
If it works we can get rid of the platform specific implementations in NB 12.0
> [NETBEANS-2785] Move NIO2 File Watcher implementation into the front.

- nb/updatecenters/src/org/netbeans/modules/updatecenters/resources/Bundle.properties
- nb/updatecenters/src/org/netbeans/modules/updatecenters/resources/mf-layer.xml
- Change master branch UC links to match standard format for server-side redirecting / release templating
- Re-add special nbres based 3rd-party UC (OpenJFX only?)
- Re-add 8.2 centre while still required in releases
As discussed in a wider PR that @ebarboni is working on, the idea is that these links will follow a standard form where `/dev/` is replaced by version (eg. `/11.1/`) automatically in the build process.
Actual targets are currently managed in the `.htaccess` at https://github.com/apache/netbeans-website/blob/master/netbeans.apache.org/src/content/.htaccess#L10
Redirects are set to match 11.1  for testing at present, although the redirect for `/nb/updates/dev/` should perhaps be `https://builds.apache.org/job/netbeans-linux/lastSuccessfulBuild/artifact/nbbuild/nbms/`?
We might …
> Fix update centre links in master

- ide/css.lib/src/org/netbeans/modules/css/lib/nbparser/CssParser.java
- ide/css.lib/src/org/netbeans/modules/css/lib/nbparser/ProgressingFailedException.java
- ide/css.lib/src/org/netbeans/modules/css/lib/nbparser/ProgressingTokenStream.java
The references issue found cases, where the CSS grammar lead to
an inifite backtracking loop. This patch works around that limitation
by requireing that the parsing progresses.
The implementation counts the read calls issued without progressing
through the stream. If the read count withouth progress exceeds
10.000.000 reads, parsing is stopped.
The number was found experimentally - it needs to be large enough to
handle real world cases and low enough that progress happens early
enough.
> [NETBEANS-1872] Prevent backtracking loops in CSS Parser

- php/php.editor/src/org/netbeans/modules/php/editor/indent/FormatVisitor.java
- php/php.editor/src/org/netbeans/modules/php/editor/lexer/LexUtilities.java
- php/php.editor/src/org/netbeans/modules/php/editor/lexer/PHPTokenId.java
- php/php.editor/test/unit/data/testfiles/formatting/netbeans1047.php
- php/php.editor/test/unit/data/testfiles/formatting/netbeans1047.php.formatted
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/indent/PHPFormatterTest.java
https://issues.apache.org/jira/browse/NETBEANS-1047
Related to https://netbeans.org/bugzilla/show_bug.cgi?id=240274
> [NETBEANS-1047] Don't add whitespace to a wrong place when textual operators are used

- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/PHPStanCustomizerPanel.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/PHPStanOptionsPanel.java
https://issues.apache.org/jira/browse/NETBEANS-2974
- Allow empty level option to use a level of a configuration file
If the level is empty, it is not added to parameters.
https://github.com/apache/netbeans/blob/16aad9d2d289c748084b89959b3aef6c312b8133/php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/PHPStan.java#L175-L183
> [NETBEANS-2974] PHPStan - make level optional

- php/php.editor/src/org/netbeans/modules/php/editor/indent/FormatVisitor.java
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2971_01.php
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2971_01.php.formatted
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2971_02.php
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2971_02.php.formatted
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/indent/PHPFormatterSpacesTest.java
https://issues.apache.org/jira/browse/NETBEANS-2971
When Within Parentheses - Method / Function Declaration is checked:
```php
$annon = function ($test) use ($lexicalVar) {
return $test . $lexicalVar;
}
```
before
```php
$annon = function ($test) use ($lexicalVar) {
return $test . $lexicalVar;
}
```
after
```php
$annon = function ( $test ) use ( $lexicalVar ) {
return $test . $lexicalVar;
}
```
> [NETBEANS-2971] Missing spaces in anonymous function declaration

- platform/core.network/src/org/netbeans/core/network/proxy/ProxyAutoConfig.java
Fix NPE if PAC cannot be resolved, e.g. UnknownHostException if the proxy pac url is configured but not reachable.
> Fix NPE if PAC cannot be resolved

- enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/javaee_8.xsd
Finally I found out when the build of `enterprise/j2ee.dd` fails behind corporate proxy. It needlessly accesses network to download `xml.xsd` which is available locally. Here in presented change seems to fix the problem.
> Avoid accessing network by j2ee.dd build

- php/php.api.phpmodule/manifest.mf
- php/php.api.phpmodule/src/org/netbeans/modules/php/api/PhpVersion.java
- php/php.editor/nbproject/project.properties
- php/php.editor/nbproject/project.xml
- php/php.editor/src/org/netbeans/modules/php/editor/codegen/SinglePropertyMethodCreator.java
- php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesSetter/testTypedPropertiesSetter.php.testTypedPropertiesSetter_PHP70Fluent.codegen
- php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesSetter/testTypedPropertiesSetter.php.testTypedPropertiesSetter_PHP71.codegen
- php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesSetter/testTypedPropertiesSetter.php.testTypedPropertiesSetter_PHP71Fluent.codegen
- php/php.editor/test/unit/data/testfiles/codegen/testTypedPropertiesSetter/testTypedPropertiesSetter.php.testTypedPropertiesSetter_PHP74.codegen
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/codegen/SelectedPropertyMethodsCreatorTest.java
https://issues.apache.org/jira/browse/NETBEANS-2993
- Add void return type when fluent is disabled
```php
public function setFoo(?string $foo): void {
$this->foo = $foo;
}
```
> [NETBEANS-2993] PHP 7.1: Add void return type to generated setter

- php/php.editor/src/org/netbeans/modules/php/editor/indent/FormatVisitor.java
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2994_01.php
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2994_01.php.formatted
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2994_02.php
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2994_02.php.formatted
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/indent/PHPFormatterSpacesTest.java
- Didn't fix curly brace array access cases (e.g. `++$test{0}`) because it is hardly used and it is deprecated since PHP 7.4
- If we fix the above case, we have to consider the following case:
```php
function test() {
// something
}
++$test{0};
```
Example:
```php
$test++;
$test   ++;
$testArray[1]++;
$testArray[1]   ++;
test()[2]++;
test()[2]  ++;
++$test;
++   $test;
++  $testArray[1];
++test()[2];
++   test()[2];
```
Before:
```php
$test++;
$test ++;
$testArray[1] ++;
$testArray[1] ++;
test()[2] ++;
test()[2] ++;
++$test;
++$test;
++$testArray[1];
++test()[2];
++test()[2];
```
After:
```php
$test++;
$test++;
$testArray[1]++;
$testArray[1]++;
test()[2]++;
test()[2]++;
++$test;
++$test;
++$testArray[1];
++test()[2];
++test()[2];
```
> [NETBEANS-2994] PHP - formatting of unary operators adds extra space

- .travis.yml
- ide/db.metadata.model/nbproject/project.properties
- ide/db.metadata.model/test/unit/src/org/netbeans/modules/db/metadata/model/jdbc/JDBCMetadataMySQLTest.java
Fix MetadataElementHandleTest and JDBCMetadataDerbyTest tests in ide/db.metadata.model module.
Commands for run the tests:
```bash
ant -f ide/db.metadata.model -Dtest.type=unit -Dtest.includes=org/netbeans/modules/db/metadata/model/api/MetadataElementHandleTest.java test-single
```
```bash
ant -f ide/db.metadata.model -Dtest.type=unit -Dtest.includes=org/netbeans/modules/db/metadata/model/jdbc/JDBCMetadataDerbyTest.java test-single
```
> Fix derby database tests in ide/db.metadata.model module.

- .travis.yml
- ide/db/test/unit/src/org/netbeans/modules/db/explorer/DbDriverManagerTest.java
- ide/db/test/unit/src/org/netbeans/modules/db/explorer/dlg/AddConnectionWizardTest.java
- ide/db/test/unit/src/org/netbeans/modules/db/test/DBTestBase.java
> Fix tests in ide/db module

- ide/db.mysql/test/unit/src/org/netbeans/modules/db/mysql/test/TestBase.java
Fix tests in ide/db.mysql module, tests are disable if class `com.mysql.jdbc.Driver` isn't available in the classpath.
> Fix tests in ide/db.mysql module

- php/php.editor/src/org/netbeans/modules/php/editor/indent/FormatVisitor.java
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2149_01.php
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2149_01.php.formatted
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2149_02.php
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2149_02.php.formatted
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2149_03.php
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2149_03.php.formatted
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2149_04.php
- php/php.editor/test/unit/data/testfiles/formatting/spaces/netbeans2149_04.php.formatted
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/indent/PHPFormatterSpacesTest.java
https://issues.apache.org/jira/browse/NETBEANS-2149
- Don't add `WHITESPACE_[BEFORE|AFTER]_ASSIGN_OP` to `==` and `===`
Example:
```php
$a=$b==$c;
$a=$b===$c;
```
Before:
```php
$a=$b== $c;
$a=$b=== $c;
```
After:
```php
$a=$b == $c;
$a=$b === $c;
```
> [NETBEANS-2149] Space-Formatting of == and === in PHP does not match "Binary Operators"

- .travis.yml
- ide/editor.structure/nbproject/project.xml
- ide/editor.structure/src/org/netbeans/modules/editor/structure/api/DocumentModel.java
- ide/editor.structure/test/unit/src/org/netbeans/modules/editor/structure/api/DocumentModelTest.java
Fix tests for ide/editor.structure module
- Remove assert in `DocumentModel.java` that brokes the tests.
- Add insane module is a test dependency.
- Change deprecated code.
> Fix tests for ide/editor.structure module

- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/ColorUtil.java
- platform/openide.awt/src/org/openide/awt/HtmlLabelUI.java
- platform/openide.awt/src/org/openide/awt/HtmlRenderer.java
Having spent a bunch of time on antialiasing settings lately, I ran across a couple of cases where the code to set them up can result in grayscale antialiasing settings clobbering the ones set correctly either by the JDK from the OS, or via, e.g. `-J-Dawt.useSystemAAFontSettings=lcd_hrgb`
> Fix a few cases where rendering hints were handled incorrectly

- harness/o.n.insane/src/org/netbeans/insane/impl/LiveEngine.java
- harness/o.n.insane/src/org/netbeans/insane/live/Path.java
Things that I bumped into while investigating https://github.com/jenkinsci/bom/pull/77. I actually have a [laundry list of INSANE issues to fix](https://github.com/jenkinsci/jenkins-test-harness/blob/e10ad3fe19a3c8a722400217d64162a03d97ac77/src/main/java/org/jvnet/hudson/test/MemoryAssert.java), but one thing at a time.
> INSANE bugs

- java/java.source.base/src/org/netbeans/modules/java/source/pretty/ImportAnalysis2.java
Trivial patch preventing NPE. The result of this method is already checked for null, so returning that would be fine.
> [NETBEANS-2980] Fix potential NPE on ImportAnalysis2.getPackage()

- java/java.hints/src/org/netbeans/modules/java/hints/Braces.java
- java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/save/FormatingTest.java
Extraneous braces will also be removed according to user preference
See previous PR which I was unable to update for context:
https://github.com/apache/netbeans/pull/173
> [NETBEANS-97] Don't add braces around try/synchronized blocks when reformatting

- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/MissingRefOutputHint.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/TagParser.java
- java/java.openjdk.project/test/unit/src/org/netbeans/modules/java/openjdk/jtreg/MissingRefOutputHintTest.java
A new hint for jtreg tests, used in the OpenJDK projects.
> Adding hint for missing /ref in @compile jtreg tags.

- enterprise/cloud.amazon/src/org/netbeans/modules/cloud/amazon/AmazonServerInstanceImplementation.java
- enterprise/cloud.amazon/src/org/netbeans/modules/cloud/amazon/serverplugin/AmazonJ2EEServerInstanceImplementation.java
- enterprise/j2eeserver/nbproject/project.properties
- enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/devmodules/api/ServerManager.java
- enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/bridge/BridgingServerInstance.java
- enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/ui/wizard/AddServerInstanceWizard.java
- enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/ui/wizard/Bundle.properties
- enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/ui/wizard/ServerChooserPanel.java
- enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/ui/wizard/ServerChooserVisual.form
- enterprise/j2eeserver/src/org/netbeans/modules/j2ee/deployment/impl/ui/wizard/ServerChooserVisual.java
- enterprise/javaee.project/src/org/netbeans/modules/javaee/project/api/ant/ui/wizard/Bundle.properties
- enterprise/payara.eecommon/nbproject/project.xml
- enterprise/payara.micro/nbproject/project.xml
- ide/server/nbproject/project.xml
- ide/server/src/org/netbeans/api/server/ServerInstance.java
- ide/server/src/org/netbeans/modules/server/ui/wizard/AddServerInstanceWizard.java
- ide/server/src/org/netbeans/spi/server/ServerInstanceImplementation.java
- ide/server/test/unit/src/org/netbeans/modules/server/test/MockInstanceImplementation.java
Reverted the previous PR https://github.com/apache/netbeans/pull/1347 which causes unavailability of `org.netbeans.modules.cloud.amazon.ui.serverplugin.AmazonJ2EEServerWizardComponent` during maven web application creation.
And filtered the server entries with different URI fragment based on unique J2eePlatformFactory e.g [gfv3ee6, gfv5ee8] & [pfv3ee6, pfv4ee7, pfvee8].
> [NETBEANS-2775] Fix duplicate server entries by filtering using PlatformFactory

- .gitattributes
`text` was misspelled as `test`. The impact has been that git hasn't enforced any particular line-ending style for files of type .xsd. It will do so now, similar to other text type files.
> Fixed typo in gitattributes file

- platform/openide.filesystems/src/org/openide/filesystems/FileUtil.java
My intention was to improve the 40s search for ArchiveRootProviders shown at [NETBEANS-2940](https://issues.apache.org/jira/browse/NETBEANS-2940?focusedCommentId=16905420&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16905420)
I'm not sure if this change good/safe enough. I'd ask the reporter to try this out first.
As far as I've checked it worked.
> [NETBEANS-2940] Cache ArchiveRootProviders

- php/php.project/src/org/netbeans/modules/php/project/connections/sync/diff/DiffPanel.java
https://issues.apache.org/jira/browse/NETBEANS-2722
The text "Take over local changes" it's unclear. Changed into "Upload local changes"
The default diff window size is too small. Changed to 1024x768 (Just to be conservative... but it's still too small for me).
The diff window size should be improved implementing the persistance of the resized window size to let any user set whatever he wants.
> [NETBEANS-2722] Upload button text and def. window size

- apisupport/apisupport.project/src/org/netbeans/modules/apisupport/project/layers/LayerNode.java
- groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyVirtualSourceProvider.java
- ide/db.mysql/src/org/netbeans/modules/db/mysql/impl/InstallationManager.java
- ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/storage/ui/CodeTemplatesModel.java
- ide/image/src/org/netbeans/modules/image/ImageViewer.java
- ide/xml/src/org/netbeans/modules/xml/sync/DataObjectSyncSupport.java
- java/java.freeform/src/org/netbeans/modules/java/freeform/Classpaths.java
- java/java.freeform/src/org/netbeans/modules/java/freeform/JavaActions.java
- java/java.freeform/src/org/netbeans/modules/java/freeform/JavaFreeformFileBuiltQuery.java
- java/java.freeform/src/org/netbeans/modules/java/freeform/JavaProjectGenerator.java
- platform/core.startup/src/org/netbeans/core/startup/layers/BinaryCacheManager.java
- platform/openide.filesystems/src/org/openide/filesystems/FileUtil.java
- platform/openide.filesystems/src/org/openide/filesystems/JarFileSystem.java
- platform/openide.filesystems/src/org/openide/filesystems/MemoryFileSystem.java
- platform/openide.filesystems/src/org/openide/filesystems/Repository.java
- platform/openide.loaders/src/org/openide/loaders/DataNode.java
- websvccommon/websvc.saas.ui/src/org/netbeans/modules/websvc/saas/ui/nodes/WsdlMethodNode.java
I've tried to reduce the amount of iterator raw type warnings that are emitted..
Here is an example of what I'm trying to fix.
```
[repeat] /home/bwalker/netbeans/enterprise/websvc.manager/src/org/netbeans/modules/websvc/manager/model/WebServiceGroup.java:102: warning: [rawtypes] found raw type: Iterator
[repeat]             Iterator iter = listeners.iterator();
[repeat]             ^
[repeat]   missing type arguments for generic class Iterator<E>
[repeat]     E extends Object declared in interface Iterator
```
> [NETBEANS-3075] - reduce number of warning w/ raw type iterator

- groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/completion/CompletionItem.java
- java/java.source/src/org/netbeans/modules/java/ui/Icons.java
Most probably the regression was caused by [NETBEANS-2614](https://issues.apache.org/jira/browse/NETBEANS-2614).
This is a potentially harmless way to avoid class cast exception as for some reason Groovy editor requests ImageIcon-s
> [NETBEANS-3072] Use actual ImageIcons as code completion actually like.

- apisupport/apisupport.project/nbproject/project.properties
- groovy/gradle.java/nbproject/project.properties
- groovy/gradle.java/nbproject/project.xml
- groovy/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/classpath/GradleSourcesImplTest.java
- platform/openide.util.ui/nbproject/project.properties
- platform/openide.util/nbproject/project.properties
This is actually a unittest for NETBEANS-2925. Separated as it affects other modules with javac.source upgrade 1.6 -> 1.8
Also it needs to interact with Gradle which might fail, and is so requires more plumbing.
> [NETBEANS-3076] Try to create unit-test with Gradle Projects

- ide/editor.lib/src/org/netbeans/editor/BaseKit.java
- ide/editor.lib2/apichanges.xml
- ide/editor.lib2/nbproject/project.properties
- ide/editor.lib2/src/org/netbeans/spi/editor/typinghooks/TypedTextInterceptor.java
- java/java.editor/nbproject/project.xml
- java/java.editor/src/org/netbeans/modules/editor/java/TypingCompletion.java
- java/java.editor/src/org/netbeans/modules/java/editor/imports/ClipboardHandler.java
- java/java.editor/test/unit/src/org/netbeans/modules/editor/java/TypingCompletionUnitTest.java
- java/java.lexer/apichanges.xml
- java/java.lexer/src/org/netbeans/lib/java/lexer/JavaLexer.java
- java/java.lexer/test/unit/src/org/netbeans/lib/java/lexer/JavaLexerBatchTest.java
- java/java.source.base/src/org/netbeans/api/java/source/SourceUtils.java
- java/java.source.base/src/org/netbeans/modules/java/source/pretty/VeryPretty.java
Avoiding SourceUtils.isTextBlockSupported API. Some features seem to make sense even if text blocks are not enabled - e.g. having a text block already in the code, then lexing it as a text block seems fine. Type-completing code in such a way that the text block would be created is (probably) not fine when text blocks are created.
Also, fixing a problem in PHP with indenting the typed text, by introducing a special API method that preforms the indent, and leaving the existing methods work as before.
> [NETBEANS-3085] Improving text block handling.

- nbi/engine/native/cleaner/windows/src/main.c
Currently the Windows NBI cleaner process fails to delete files/folders if they have the read-only attribute set. With this change the cleaner will - in such case - attempt to remove the read-only attribute before proceeding to delete the file/folder.
I've deliberately not squashed as each commit is a story of its own.
>  [NETBEANS-3094] NBI cleaner process must attempt to remove read-only files too

- groovy/gradle.java/apichanges.xml
- groovy/gradle.java/manifest.mf
- groovy/gradle.java/nbproject/project.xml
- groovy/gradle.java/src/org/netbeans/modules/gradle/java/api/GradleJavaProjectBuilder.java
- groovy/gradle.java/src/org/netbeans/modules/gradle/java/api/GradleJavaSourceSet.java
- groovy/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleCompilerOptionsQuery.java
- groovy/gradle/netbeans-gradle-tooling/src/main/groovy/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.groovy
- groovy/gradle/src/org/netbeans/modules/gradle/GradleProjectCache.java
As far as I could test this one works. I'd add more tests later on Gradle Projects after #1483 gets merged.
> [NETBEANS-2941] Allow the IDE to see the compiler options in Gradle Projects

- php/php.editor/src/org/netbeans/modules/php/editor/indent/FormatVisitor.java
- php/php.editor/test/unit/data/testfiles/formatting/broken/netbeans3103_parent_01.php
- php/php.editor/test/unit/data/testfiles/formatting/broken/netbeans3103_parent_01.php.formatted
- php/php.editor/test/unit/data/testfiles/formatting/broken/netbeans3103_parent_02.php
- php/php.editor/test/unit/data/testfiles/formatting/broken/netbeans3103_parent_02.php.formatted
- php/php.editor/test/unit/data/testfiles/formatting/broken/netbeans3103_self_01.php
- php/php.editor/test/unit/data/testfiles/formatting/broken/netbeans3103_self_01.php.formatted
- php/php.editor/test/unit/data/testfiles/formatting/broken/netbeans3103_self_02.php
- php/php.editor/test/unit/data/testfiles/formatting/broken/netbeans3103_self_02.php.formatted
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/indent/PHPFormatterBrokenTest.java
https://issues.apache.org/jira/browse/NETBEANS-3103
This issue is related to #1314 .
- The parser ignores "::" because example code is incorrect syntax
- Check whether the token behind self or parent is "::" in the FormatVisitor
Example code:
```php
<?php
class ClassName {
// ^ is the caret position
// select "self::" or "parent::" in CC list
// i.e. private const CONSTANT = self::;
private const CONSTANT = ^;
}
```
Before:
```php
<?php
class ClassName {
private const CONSTANT = self
::;
}
```
After:
```php
<?php
class ClassName {
private const CONSTANT = self::;
}
```
> [NETBEANS-3103] Formatting is broken with class constant code completion(self::)

- groovy/groovy.support/src/org/netbeans/modules/groovy/support/Bundle.properties
- groovy/groovy.support/src/org/netbeans/modules/groovy/support/options/Bundle.properties
- groovy/groovy.support/src/org/netbeans/modules/groovy/support/options/SupportPanel.java
Changed the old URL to a new one:  https://groovy.apache.org/download.html
Jira Ticket: https://issues.apache.org/jira/projects/NETBEANS/issues/NETBEANS-2788
> [NETBEANS-2788] The link provided for downloading Groovy is obsolete

- platform/core.startup/src/org/netbeans/core/startup/Splash.java
Avoids random null pointer exception.
`
java.lang.NullPointerExceptionjava.lang.NullPointerException at org.netbeans.core.startup.Splash$SplashPainter$1.run(Splash.java:521) at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) at java.awt.EventQueue.access$500(EventQueue.java:97) at java.awt.EventQueue$3.run(EventQueue.java:709) at java.awt.EventQueue$3.run(EventQueue.java:703) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) at …
> [NETBEANS-3095] avoid null pointer exception in SplashPainter

- php/php.editor/src/org/netbeans/modules/php/editor/model/impl/ModelVisitor.java
- php/php.editor/test/unit/data/testfiles/gotodeclaration/testNb3108/testNb3108.php
- php/php.editor/test/unit/data/testfiles/markoccurences/testNb3108/testNb3108.php
- php/php.editor/test/unit/data/testfiles/testNb3108.php.testNb3108_01a.occurrences
- php/php.editor/test/unit/data/testfiles/testNb3108.php.testNb3108_01b.occurrences
- php/php.editor/test/unit/data/testfiles/testNb3108.php.testNb3108_02a.occurrences
- php/php.editor/test/unit/data/testfiles/testNb3108.php.testNb3108_02b.occurrences
- php/php.editor/test/unit/data/testfiles/testNb3108.php.testNb3108_03a.occurrences
- php/php.editor/test/unit/data/testfiles/testNb3108.php.testNb3108_03b.occurrences
- php/php.editor/test/unit/data/testfiles/testNb3108.php.testNb3108_03c.occurrences
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/GotoDeclarationNb3108Test.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/OccurrencesFinderImplNb3108Test.java
https://issues.apache.org/jira/browse/NETBEANS-3108
- Just check `StaticFieldAccess` and `FieldAccess` in the `ModelVisitor`
> [NETBEANS-3108] PHP: Some features(e.g. Go to declaration) do not work after "new"

- nbbuild/antsrc/org/netbeans/nbbuild/ParseGitBranch.java
Update ParseGitBranch to assume master if more than one line of info returned from git branch. This happens in case of Travis CI tests, and is currently breaking them.  Commented out old code for now - should review again later.
> Fix Ant errors caused by ParseGitBranch task (Travis issue, etc.)

- platform/openide.filesystems/src/org/openide/filesystems/FileUtil.java
This is a followup to commit:
290420cfff1a "[NETBEANS-2940] Cache ArchiveRootProviders"
The issue is:
archiveRootProviders.compareAndSet(null, res)
returns true, when the set was successful. In this case, the 
LookupListener needs to registered, that invalidates the cache list of
ArchiveRootProviders. In the original commit, this logic was inverted,
so the LookupListener was not installed and the cache never invalidated.
In addition the archiveRootProviderCache was made volatile to prevent
wrong caching across threads.
> [NETBEANS-2940] Invalidate cacheed ArchiveRootProviders on change

- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Java 13 was released yesterday and the javadoc needs to be changed to use the new URL instead of the early-access URL.
> [NETBEANS-3113] - Use released Java 13 GA Javadoc

- nbbuild/templates/common.xml
This should fix build for NetBeansTLP-master
Path were using flat structure instead cluster structure
> fix path for xml validation

- nbbuild/packaging/netbeans_snap/snap/snapcraft.yaml
This is just make the release buildable with recent snapcraft.
> Make newer snapcraft happy adding parse-info tag.

- ide/diff/src/org/netbeans/modules/diff/DiffAction.java
- ide/diff/src/org/netbeans/modules/diff/EditorBufferSelectorPanel.java
Diff file chooser converts editor FileObjects to java.io.File for selection.
In this process files with remote sources (rfs:/) become null.
This fix checks if selected file is not a disk file, providing alternate
means to retrieve the FileObject
This bug and fix is not related to C++ module; except that it manifests there.
> [NETBEANS-3040] Diff to feature does not work for Remote files in C/C++

- nbbuild/default.xml
Set buildnumber to "${metabuild.RawVersion}-${metabuild.hash}" if both values have been computed to ensure consistency across builds of the same sources.
> Set buildnumber from metabuild info (branch and hash)

- nbbuild/antsrc/org/netbeans/nbbuild/GitBranchHash.java
- nbbuild/build.xml
I noticed while doing the buildnumber PR that the HgId task almost does what we need as a fallback to get branch and hash from .git folder.  I think this covers the cases where head isn't detached, and it's only needed for local checkout builds now anyway.
> Parse metabuild branch and hash from .git folder as fallback

- README.md
Add a brief note about the JAVA_HOME and ANT_HOME environment variables
to the build instructions on the Web site and the GitHub repository. See
the following message on the mailing list for details:
Re: Building NetBeans 11.1 from source fails with compile errors
https://mail-archives.apache.org/mod_mbox/netbeans-dev/201910.mbox/%3C26c1f141-b021-4473-059f-41ec0b5e3613%40status6.com%3E
Fixes #3209
> [NETBEANS-3209] Add JAVA_HOME and ANT_HOME note

- .travis.yml
Change Travis config to retry mysql tests that fails randomly when run in Travis environment.
Use [travis_retry](https://docs.travis-ci.com/user/common-build-problems/#travis_retry) command to retry the tests.
> Retry mysql tests in Travis config

- apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/MavenNbModuleImpl.java
This is last part of fix for NETBEANS-3185.  It's to use the 4.3 version of plugin
As vote is in progress it's not yet available.
> NETBEANS-3185 use last maven-nbm-plugin

- groovy/gradle.htmlui/src/org/netbeans/modules/gradle/htmlui/resources/src_main_webapp_pages_index.html.fmk
In order to make the Java Frontend Application Gradle project type more attractive, it would be better to make it less HTML-like, and more component like. Using Material CSS is a simple way to do it. 
Hopefully @geertjanw finds the new UI more attractive to shoot a video about the excellent support NetBeans provide when it comes to *JavaFX light* developement. @neilcsmith-net, can we get it into 11.2? It is just a simple HTML change, no code is affected. Thank you.
CCing @lkishalmi
> Use Material CSS to make the example look nicer

- ide/db/build.xml
- ide/xml.tax/build.xml
Always specify javac.target to allow compilation on JDK11+ and execution on JDK8. Once I compiled NetBeans with JDK11:
```
nbbuild$ ant build -Dnbjdk.home=/jdk11
```
but then I wanted to compile again with JDK8
```
nbbuild$ ant build -Dnbjdk.home=/jdk8
```
it failed with "Incompatible class file error". In general we have to specify `target="${javac.target}"` to prevent JDK11+ to use too modern bytecode formats. This PR contains two places where the missing `target` was causing problems in my case.
> Always specify javac.target

- extra/nbjavac.api/release/modules/ext/nb-javac-13-api.jar.external
- extra/nbjavac.impl/release/modules/ext/nb-javac-13-impl.jar.external
- java/libs.javacapi/external/binaries-list
- java/libs.javacimpl/external/binaries-list
[NETBEANS-3164]:Fixed issue in Text-Block
> [NETBEANS-3164]:Fixed issue in Text-Block

- php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/CodeSniffer.java
https://issues.apache.org/jira/browse/NETBEANS-3243
If `/path/to/phpcs --standard=/path/to/ruleset.xml -s` is set to the path of Code Sniffer, `--standard` parameter is added twice.
```
"/usr/bin/php" "/path/to/phpcs" "--standard=/path/to/ruleset.xml" "-s" "--standard=MySource" "--report=xml" "--extensions=phtml,php,php4,php5,php3,phpt,inc" "--encoding=UTF-8" "/path/to/target.php"
```
If the path have that parameter, just use only it.
```
"/usr/bin/php" "/path/to/phpcs" "--standard=/path/to/ruleset.xml" "-s" "--report=xml" "--extensions=phtml,php,php4,php5,php3,phpt,inc" "--encoding=UTF-8" "/path/to/target.php"
```
> [NETBEANS-3243] Prioritize "--standard" parameter of the path of Code Sniffer

- php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/PHPStan.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/parsers/PHPStanReportParser.java
- php/php.code.analysis/test/unit/data/phpstan/PHPStanSupport/netbeans3022/Test1.php
- php/php.code.analysis/test/unit/data/phpstan/PHPStanSupport/netbeans3022/Test2.php
- php/php.code.analysis/test/unit/data/phpstan/phpstan-log-netbeans-3022-win.xml
- php/php.code.analysis/test/unit/data/phpstan/phpstan-log-netbeans-3022-without-workdir.xml
- php/php.code.analysis/test/unit/data/phpstan/phpstan-log-netbeans-3022.xml
- php/php.code.analysis/test/unit/src/org/netbeans/modules/php/analysis/parsers/PHPStanReportParserTest.java
https://issues.apache.org/jira/browse/NETBEANS-3002
- The file name value can be null
e.g.
```xml
<file>
<error severity="error" message="Ignored error pattern #TEST# was not matched in reported errors." />
</file>
```
So, in this case, just ignore the error.
- There is a difference in file name value between the old version and the new version
e.g. Inspect the following app directory (myproject is the working directory)
- myproject/app/Test1.php
- myproject/app/Test2.php
old version: the relative path from target directory
```xml
<file name="Test1.php">
<error line="13" column="1" severity="error" message="Binary operation &quot;+&quot; between string and 2 results in an error." />
</file>
<file name="Test2.php">
<error line="9" column="1" severity="error" message="Anonymous function …
```
> [NETBEANS-3002] NullPointerExceptions during PHPStan inspection

- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibility.php
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityAbstractClass.php
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityAbstractClass.php.testConvertVisibilitySuggestionAbstractClassFix_01.fixed
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityAbstractClass.php.testConvertVisibilitySuggestionAbstractClassFix_02.fixed
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityAbstractClass.php.testConvertVisibilitySuggestionAbstractClassFix_03.fixed
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityAbstractClass.php.testConvertVisibilitySuggestionAbstractClassFix_04.fixed
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityAbstractClass.php.testConvertVisibilitySuggestionAbstractClassFix_05.fixed
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityAbstractClass.php.testConvertVisibilitySuggestionAbstractClassFix_06.fixed
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityInterface.php
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityInterface.php.testConvertVisibilitySuggestionInterfaceFix_01.fixed
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityInterface.php.testConvertVisibilitySuggestionInterfaceFix_02.fixed
- php/php.editor/test/unit/data/testfiles/verification/ConvertVisibilitySuggestion/testConvertVisibilityInterface.php.testConvertVisibilitySuggestionInterfaceFix_03.fixed
- Fix typo of abstract class name
- Fix the interface name of test data because there is the same name in testImplementAbstractMethodsHint.php (from InterfaceName to VisibilityInterface)
So, two unit tests failed in `HintsTest`, sorry.
> Fix unit tests for ConvertVisibilitySuggestion

- .travis.yml
Move the check-line-endings script and the verification of the RAT report to run in a separate build job.
> [TRAVIS] Move check-line-endings script and RAT report

- platform/core.osgi/nbproject/project.properties
- platform/core.osgi/src/org/netbeans/core/osgi/OSGiClassLoader.java
- platform/core.osgi/test/unit/src/org/netbeans/core/osgi/ActivatorTest.java
Fix org.osgi.framework.BundleException when run `org.netbeans.core.osgi.ActivatorTest.testClassPathExtensions` test method.
```
Unable to resolve custom [8](R 8.0): missing requirement [custom [8](R 8.0)] osgi.wiring.bundle; (&(osgi.wiring.bundle=org.netbeans.libs.jna)(bundle-version>=100.0.0)(!(bundle-version>=200.0.0))) Unresolved requirements: [[custom [8](R 8.0)] osgi.wiring.bundle; (&(osgi.wiring.bundle=org.netbeans.libs.jna)(bundle-version>=100.0.0)(!(bundle-version>=200.0.0)))]
```
> Fix org.osgi.framework.BundleException when run core/osgi/ActivatorTest

- java/java.sourceui/src/org/netbeans/modules/java/source/ui/AsyncJavaSymbolDescriptor.java
tzezula reported that the Navigate/Go to Symbol feature does not work properly for Java:
-the entries in the list are missing the icon
-pressing Enter does not jump to the actual entry
I believe the reason is that ElementUtils.getTypeElementByBinaryName is called on an javac instance, that is not sufficiently initialized (since JDK 9, javac must be initialized a little bit more that before to work). This is particularly problem since this feature uses the javac internal directly. The proposed patch is to force the proper initialization. There are multiple ways to do that, but JavacTask.getElements().getTypeElement("java.lang.Object") feels like the cleanest. (Alternative would be "jt.ensureEntered()", but that is yet another call to an javac internal method, while getTypeElement is …
> Must ensure javac is initialized before attempting any lookups.

- java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorkerTest.java
-improving handling of type parameters with unresolvable bounds
-improving handling of duplicate classes
-improving handling of methods with bodies in annotations
(We could target this to 11.2, but probably better to not do unnecessary changes there. This prevents some crashes during indexing without nb-javac. CC @neilcsmith-net anyway.)
> Some more fixes to vanilla indexing:

- platform/o.n.bootstrap/src/org/netbeans/JarClassLoader.java
It seems that JarFile was moved to NIO. A missing file is thus not reported as a
`java.io.FileNotFoundException`, but a `java.nio.file.NoSuchFileException`. By catching
both, we are independent of this implementation detail (assuming people stop
reinventing the wheel).
The stacktrace for the error:
```
WARNUNG: problems with /home/matthias/src/netbeans/platform/o.n.bootstrap/build/test/unit/work/o.n.A/wcpe/install/platform/modules/ext/non-existent.jar
java.nio.file.NoSuchFileException: /home/matthias/src/netbeans/platform/o.n.bootstrap/build/test/unit/work/o.n.A/wcpe/install/platform/modules/ext/non-existent.jar
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at …
```
> JarClassLoader needs to catch NoSuchFileException in addition to FileNotFoundException

- java/java.platform.ui/src/org/netbeans/api/java/platform/PlatformsCustomizer.java
- java/maven/src/org/netbeans/modules/maven/NbMavenProjectImpl.java
- java/maven/src/org/netbeans/modules/maven/api/NbMavenProject.java
- java/maven/src/org/netbeans/modules/maven/classpath/AbstractBootPathImpl.java
- java/maven/src/org/netbeans/modules/maven/classpath/BootClassPathImpl.java
- java/maven/src/org/netbeans/modules/maven/options/Bundle.properties
- java/maven/src/org/netbeans/modules/maven/options/MavenSettings.java
- java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.form
- java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.java
I am running NetBeans on JDK13 (to benefit from the great work Oracle guys put into `javac` in JDK13 and its co-operation with NetBeans).
However I don't want to develop my own code on such bleeding edge platform. I usually want my Maven projects to compile on JDK8, sometimes on JDK11. Never on JDK13.
There is a way to select non-default JDK per Maven project, but I'd like to do that for all projects at once. This PR solves it - it allows one to specify "Default JDK" in Maven settings and that one is then used for each Maven project without specifically selected JDK.
> Default JDK for Maven projects

- platform/o.n.bootstrap/test/unit/src/org/netbeans/ProxyClassLoaderNB11PackageAnnotationsTest.java
@borisheithecker please have a look at this - the new Unittest ProxyClassLoaderNB11PackageAnnotationsTest fails on JDK 8 (found by #1597). I update the unittest and with this change I get:
JDK8 without Fix: Test passes
JDK11 without Fix: Test fails
JDK8 with Fix: Test passes
JDK11 with Fix: Test passes
This is IMHO the expected outcome. Does that look sane to you?
> Fix unittest ProxyClassLoaderNB11PackageAnnotationsTest

- php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion.java
- php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCompletionItem.java
- php/php.editor/src/org/netbeans/modules/php/editor/model/ModelUtils.java
- php/php.editor/test/unit/data/testfiles/completion/lib/_base/issue153707.php.testIssue153707_01.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb1855/nb1855.php
- php/php.editor/test/unit/data/testfiles/completion/lib/nb1855/nb1855.php.testCompleteAccessPrefixInClassConst_01.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb1855/nb1855.php.testCompleteAccessPrefixInClassConst_02.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb1855/nb1855.php.testCompleteAccessPrefixInTrait_01.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb1855/nb1855.php.testCompleteAccessPrefixInTrait_02.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb1855/nb1855.php.testCompleteAccessPrefixInTrait_03.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb1855/nb1855.php.testCompleteAccessPrefix_01.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb1855/nb1855.php.testCompleteAccessPrefix_02.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb1855/nb1855.php.testCompleteAccessPrefix_03.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/php70/base/anonymousClass03.php.testAnonymousClass03a.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/php74/testArrowFunctions/arrowFunctions.php.testArrowFunctions_21b.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/php74/testArrowFunctionsInMethod/arrowFunctionsInMethod.php.testArrowFunctionsInMethod_01a.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/php74/testArrowFunctionsInMethodWithError/arrowFunctionsInMethodWithError.php.testArrowFunctionsInMethodWithError_01a.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/php74/testArrowFunctionsInMethodWithError/arrowFunctionsInMethodWithError.php.testArrowFunctionsInMethodWithError_02a.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInClassConst/spreadOperatorInClassConst.php.testSpreadOperatorInClassConst_00.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInClassConst/spreadOperatorInClassConst.php.testSpreadOperatorInClassConst_01.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInClassConst/spreadOperatorInClassConst.php.testSpreadOperatorInClassConst_04.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInClassConst/spreadOperatorInClassConst.php.testSpreadOperatorInClassConst_07.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/php74/testSpreadOperatorInClassConst/spreadOperatorInClassConst.php.testSpreadOperatorInClassConst_11.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/tests247082/issue247082.php.testForKeywords.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/tests257088/issue257088.php.testClassKeywords.completion
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionNb1855Test.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionTest.java
https://issues.apache.org/jira/browse/NETBEANS-1855
e.g.
```php
class MyClass {
public test() {
code// CC here : $this->codeCompletion() is added
}
private codeCompletion() {}
}
```
> [NETBEANS-1855] Autocomplete for property and method without $this->

- ide/html.lexer/src/org/netbeans/lib/html/lexer/HtmlLexer.java
- php/php.smarty/test/unit/data/testfiles/parserErrors/testParserNETBEANS3335_01.tpl
- php/php.smarty/test/unit/data/testfiles/parserErrors/testParserNETBEANS3335_01.tpl.errors
- php/php.smarty/test/unit/data/testfiles/parserErrors/testParserNETBEANS3335_02.tpl
- php/php.smarty/test/unit/data/testfiles/parserErrors/testParserNETBEANS3335_02.tpl.errors
- php/php.smarty/test/unit/src/org/netbeans/modules/php/smarty/editor/parser/TplParserErrorsTest.java
After the update of the HTML lexer to support HTML5 style attributes,
new states in the lexer can be reached. Instead of bailing out with a
NullPointerException in HtmlLexer#equals, report comparisons with NULL
as false.
> [NETBEANS-3335] Enhance robustness of HTML Lexer

- nbbuild/build.xml
OracleLabs engineers have problems building NetBeans due to the new download from `metabuild.jsonurl` - it helps if we set the proxy up first. Here is my change for your consideration.
Let's see whether the Travis builds are OK and then we could integrate.
> Configure proxy before trying to download release.json from its URL

- groovy/gradle.javaee/src/org/netbeans/modules/gradle/javaee/web/WebProjectBrowserProvider.java
Previously the GradleJavaEEProjectSettings has only been registered in the project lookup if that had the war plugin loaded. Loosing that plugin from the project could result that some listeners on the JavaEE project preferences would not be removed.
Adding the settings to all Gradle project probably won't really hurt as it is only used by the JavaEE functionality when installed.
> [NETBEANS-3276] Let GradleJavaEEProjectSettings be always registered.

- nbbuild/build.xml
The Netbeans project no longer uses Mercurial as it's primary source code control system. It's now all managed in a Git repo. Therefore, we no longer need to carry around the technical debt in build.xml..
For example, the clean target  has the following
`     <try-else first="-hg-clean" second="-real-clean"/>`
Yet, "-hg-clean" has the following fail and never will get executed..
`    <fail message="Not running in a Mercurial checkout."> `
So it can safely be removed..
Before
```
....
[releasejson] Branding computed info: metabuild.logcli=-J-Dnetbeans.logger.console=true -J-ea
clean:
-hg-clean:
[try-else] /tmp/netbeans/nbbuild/build.xml:1343: Not running in a Mercurial checkout.
[try-else] Target -hg-clean failed, falling back to -real-clean
-jdk-pre-preinit:
-jdk-preinit:
...
```
After …
> [NETBEAN-3230] - remove hg-clean target from build.xml

- ide/db.metadata.model/apichanges.xml
- ide/db.metadata.model/manifest.mf
- ide/db.metadata.model/nbproject/project.xml
Github issue: https://github.com/jeddict/jeddict/issues/322
Friend API of the Apache NetBeans Platform used by Jeddict modules:
| NetBeans Module name | NetBeans Module location | APIs | Used by Jeddict modules | Requirement |  Why access needed? |
| --- | --- | --- | --- | --- | --------- |
| org.netbeans.modules:org-netbeans-modules-db-metadata-model | netbeans\ide\db.metadata.model | org.netbeans.modules.db.metadata.model.api |  io.github.jeddict.jpa.modeler, io.github.jeddict.db.modeler | public-packages | To visualize Tree-Structured tables from Services > Database in Jeddict modeler |
> JEDDICT-322 org.netbeans.modules.db.metadata.model convert friend to public packages

- ergonomics/ide.ergonomics/enterprise.properties
- ergonomics/ide.ergonomics/webcommon.properties
Minor edit.
Since NetBeans has a proper Javascript Parser, no need for the ergonomic messages about the old Oracle JSParser.
> Removes old LBL_Ergonomics_Extra_Required message about Javascript parser

- groovy/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImpl.java
- groovy/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/AbstractGradleJavaTestCase.java
- groovy/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImplTest.java
- groovy/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/classpath/GradleSourcesImplTest.java
Fixing a copy and paste bug introduced in the Java modular classpath rewrite in 11.1
> [NETBEANS-2983] Gradre returns CompileCP instead of RuntimeCP on non-modular projects

- contrib/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/WildflyDeploymentFactory.java
- harness/apisupport.harness/build.xml
- java/lib.jshell.agent/agentsrc/org/netbeans/lib/jshell/agent/NbJShellAgent.java
- java/lib.jshell.agent/nbproject/project.properties
- nbbuild/templates/common.xml
- platform/core.startup/src/org/netbeans/core/startup/Asm.java
- platform/libs.asm/external/asm-7.2-license.txt
- platform/libs.asm/external/binaries-list
- platform/libs.asm/nbproject/project.properties
- platform/libs.asm/nbproject/project.xml
-Upgrade asm-all-5.0.1 version to asm-7.2
-Add constructor parameter to use ASMv7 API
`ClassNode theClass = new ClassNode(Opcodes.ASM7);`
If you don't set the ASM version API it will use the default version from the jar:
- asm-all-5.0.1.jar = Opcodes.ASM5
- asm-6.1.jar = Opcodes.ASM6
- asm-7.2.jar = Opcodes.ASM7
-Visit @ConstructorDelegate parameters as array. (by sdedic)
> [NETBEANS-3346] - Upgrade asm-all-5.0.1 version to asm-7.2

- .travis.yml
Current Travis configuration doesn't run the tests for the ide modules only does a build of the source code.
It's the same problem that @matthiasblaesing found when he try to add tests in webcommon cluster: https://github.com/apache/netbeans/pull/1451
> [TRAVIS] Fix Travis config when run tests for ide modules

- java/libs.javacapi/external/binaries-list
- java/libs.javacimpl/external/binaries-list
- nb/updatecenters/extras/nbjavac.api/manifest.mf
- nb/updatecenters/extras/nbjavac.api/release/modules/ext/nb-javac-13-api.jar.external
- nb/updatecenters/extras/nbjavac.impl/manifest.mf
- nb/updatecenters/extras/nbjavac.impl/release/modules/ext/nb-javac-13-impl.jar.external
Changes fix for refactoring rename of java methods.
https://issues.apache.org/jira/browse/NETBEANS-3257
nb-javac jars are oracle signed now.
https://github.com/apache/netbeans/pull/1589
this PR got accidentally closed while renaming branch and there is no option to reopen it.
> [NETBEANS-3257]: Fixed issue on refactoring rename of java method

- ide/bcpg/external/bcpg-jdk15on-1.64-license.txt
- ide/bcpg/external/binaries-list
- ide/bcpg/nbproject/project.properties
- ide/bcpg/nbproject/project.xml
- ide/bcprov/external/bcprov-jdk15on-1.64-license.txt
- ide/bcprov/external/binaries-list
- ide/bcprov/nbproject/project.properties
- ide/bcprov/nbproject/project.xml
Notes:
This release is primarily a security release to fix a regression in the ASN.1 
library that was introduced in 1.63 ([CVE-2019-17359](https://nvd.nist.gov/vuln/detail/CVE-2019-17359))
[Bouncycastle Web Page](https://bouncycastle.org/latest_releases.html)
[Bouncycastle Releases Notes](https://bouncycastle.org/releasenotes.html)
> [NETBEANS-3438] - Upgrade bouncycastle from 1.63 to 1.64

- ide/db.dataview/external/binaries-list
- ide/db.dataview/external/h2-1.4.200-license.txt
- ide/db.dataview/nbproject/project.properties
Notes:
- Several Bug fixes and improvements
- Use OpenJDK instead of OracleJDK
- Add support for Java 11 to test suite
[H2 database Web Page](https://h2database.com/html/main.html)
[H2 database Release Notes](https://h2database.com/html/changelog.html)
> [NETBEANS-3443] - Upgrade h2 database from 1.4.196 to 1.4.200

- ide/libs.commons_compress/external/binaries-list
- ide/libs.commons_compress/external/commons-compress-1.19-license.txt
- ide/libs.commons_compress/external/commons-compress-1.19-notice.txt
- ide/libs.commons_compress/nbproject/project.properties
- ide/libs.commons_compress/nbproject/project.xml
- ide/libs.commons_compress/src/org/netbeans/libs/commons_compress/Bundle.properties
- ide/libs.commons_compress/src/org/netbeans/libs/commons_compress/mf-layer.xml
Notes:
- Add support for lz4, Brotli, Zstandard and DEFLATE64 archives.
- Requires Java 7
- Convert all tests to JUnit4
- 79 Bug fixes
- 17 New Features
- 53 Improvements
[Apache Commons Compress Web Page](https://commons.apache.org/proper/commons-compress/index.html)
[Apache Commons Compress Release Notes](https://issues.apache.org/jira/projects/COMPRESS?selectedItem=com.atlassian.jira.jira-projects-plugin:release-page&status=released)
> [NETBEANS-3441] - Upgrade apache compress from 1.8.1 to 1.19

- ide/editor.settings.storage/apichanges.xml
- ide/editor.settings.storage/arch.xml
- ide/editor.settings.storage/nbproject/project.properties
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/EditorLocatorFactory.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/EditorSettingsImpl.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/MimeTypesTracker.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/NbUtils.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/ProfilesTracker.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/SettingsProvider.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/api/FontColorSettingsFactory.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/api/KeyBindingSettingsFactory.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/fontscolors/ColoringStorage.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/fontscolors/CompositeFCS.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/fontscolors/EditorFontsColors-1_2.dtd
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/fontscolors/FontColorSettingsImpl.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/keybindings/KeyBindingSettingsImpl.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/keybindings/KeyMapsStorage.java
- ide/editor.settings.storage/src/org/netbeans/modules/editor/settings/storage/layer.xml
- ide/editor.settings.storage/test/unit/src/org/netbeans/modules/editor/settings/storage/FontColorSettingsImplTest.java
- ide/editor.settings.storage/test/unit/src/org/netbeans/modules/editor/settings/storage/fonts-and-colors-6.xml
- ide/editor.settings.storage/test/unit/src/org/netbeans/modules/editor/settings/storage/test-layer.xml
This one contains a new DTD which probably have to be installed on netbeans.apache.org/dtds/ as well.
It might help for #1652 in the future.
> [NETBEANS-3440] Allow to define a palette for fontcolors XML Schema.

- enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ear/model/ApplicationMetadataModelImpl.java
There are compiler warnings about rawtype usage with a SimpleFuture like the following
```
[nb-javac] .../enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ear/model/ApplicationMetadataModelImpl.java:110: warning: [rawtypes] found raw type: SimpleFuture
[nb-javac]         return new SimpleFuture(runReadAction(action));
[nb-javac]                    ^
[nb-javac]   missing type arguments for generic class SimpleFuture<R>
[nb-javac]   where R is a type-variable:
[nb-javac]     R extends Object declared in class SimpleFuture
```
> [NETBEANS-3462] Fixed compiler warnings concerning rawtypes SimpleFuture

- platform/options.api/src/org/netbeans/modules/options/OptionsPanel.java
Simple fix for Options dialog categories button colors.
Uses existing colors from UI defaults.
So this should also work fine with other FlatLaf themes.
The magnifier left to the quick search field is hard to see, but this should be fixed with a SVG icon.
> [NETBEANS-3428] FlatLaf: Fixed colors of categories buttons in Options dialog

- webcommon/web.javascript.debugger/src/org/netbeans/modules/web/javascript/debugger/locals/VariablesTreeExpansionModel.java
There are compiler warnings about rawtype usage with a WeakSet like the following
```
[repeat] .../webcommon/web.javascript.debugger/src/org/netbeans/modules/web/javascript/debugger/locals/VariablesTreeExpansionModel.java:47: warning: [rawtypes] found raw type: WeakSet
[repeat]     private Set expandedNodes = new WeakSet();
[repeat]                                     ^
[repeat]   missing type arguments for generic class WeakSet<E>
[repeat]     E extends Object declared in class WeakSet
```
> [NETBEANS-3464] Fixed compiler warnings concerning rawtypes WeakSet

- ide/versioning.util/src/org/netbeans/modules/versioning/history/AbstractSummaryView.java
I was working on my usual code cleanup when I encountered a bug in the method AbstractSummaryView() in AbstractSummaryView.java..
Notice the following code was not type-casting correctly..
```
-                if (selection.length == 1) {
-                    if (selection[0] instanceof ShowAllEventsItem) {
-                        showRemainingFiles(((ShowAllEventsItem) selection[0]).getParent(), true);
-                    } else if (selection[0] instanceof ShowLessEventsItem) {
-                        showRemainingFiles(((ShowAllEventsItem) selection[0]).getParent(), false);
-                    } else if (selection[0] instanceof MoreRevisionsItem) {
```
Specifically, an instance of ShowLessEventsItem should be properly cast..
`+ …
> [NETBEANS-3518] - fix bug in AbstractSummaryView.java

- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/utils/StringPrefixTree.java
- enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/utils/StringPrefixTree.java
- ide/ide.kit/nbproject/project.properties
- ide/ide.kit/test/qa-functional/src/org/netbeans/test/ide/BlacklistedClassesHandlerSingleton.java
- ide/jellytools.ide/nbproject/project.properties
- ide/jellytools.ide/test/qa-functional/src/org/netbeans/jellytools/CollectBundleKeys.java
- ide/spi.debugger.ui/test/unit/src/org/netbeans/api/debugger/LookupTest.java
- webcommon/javascript2.requirejs/src/org/netbeans/modules/javascript2/requirejs/ui/RequireJsPanel.java
There are compiler warnings about rawtype usage with a TreeMap like the following
```
[nb-javac] ..../ide/spi.debugger.ui/test/unit/src/org/netbeans/api/debugger/LookupTest.java:62: warning: [rawtypes] found raw type: TreeMap
[nb-javac]         TreeMap treeMapInstance2 = new TreeMap();
[nb-javac]                                        ^
[nb-javac]   missing type arguments for generic class TreeMap<K,V>
[nb-javac]   where K,V are type-variables:
[nb-javac]     K extends Object declared in class TreeMap
[nb-javac]     V extends Object declared in class TreeMap
```
> [NETBEANS-3460] Fixed compiler warnings concerning rawtypes TreeMap

- ide/extexecution.process.jdk9/src/org/netbeans/modules/extexecution/process/jdk9/ProcessesImpl.java
There are compiler warnings about rawtype usage with a Stream like the following
```
[repeat] /Users/martin/Repositories/git/netbeans/ide/extexecution.process.jdk9/src/org/netbeans/modules/extexecution/process/jdk9/ProcessesImpl.java:77: warning: [rawtypes] found raw type: Stream
[repeat]             try (Stream s = (Stream) PROCESS_HANDLE_DESCENDANTS.invoke(handle, (Object[]) null)) {
[repeat]                  ^
[repeat]   missing type arguments for generic class Stream<T>
[repeat]     T extends Object declared in interface Stream
```
> [NETBEANS-3450] Fixed compiler warnings concerning rawtypes Stream

- ide/db/test/unit/src/org/netbeans/modules/db/explorer/DbDriverManagerTest.java
- ide/xml.core/src/org/netbeans/modules/xml/api/model/GrammarQueryManager.java
- ide/xml.text.obsolete90/src/org/netbeans/modules/xml/text/syntax/XMLSyntaxSupport.java
- platform/autoupdate.services/test/unit/src/org/netbeans/modules/autoupdate/services/UpdateManagerImplTest.java
- platform/masterfs/test/unit/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/FileObjectFactorySizeTest.java
- platform/masterfs/test/unit/src/org/netbeans/modules/masterfs/filebasedfs/fileobjects/LockForFileTest.java
- platform/openide.actions/src/org/openide/actions/MoveUpAction.java
- platform/openide.awt/src/org/openide/awt/ContextAction.java
- platform/openide.awt/test/unit/src/org/netbeans/modules/openide/openide/awt/StatefulActionProcessorTest.java
- platform/openide.compat/nbproject/project.properties
- platform/openide.compat/src/org/openide/explorer/ExplorerPanel.java
- platform/openide.compat/src/org/openide/util/WeakListener.java
- platform/openide.filesystems/src/org/openide/filesystems/AbstractFolder.java
- platform/openide.filesystems/src/org/openide/filesystems/MemoryFileSystem.java
- platform/openide.filesystems/src/org/openide/filesystems/XMLFileSystem.java
- platform/openide.nodes/nbproject/project.properties
- platform/openide.nodes/src/org/openide/nodes/BeanChildren.java
- platform/openide.nodes/src/org/openide/nodes/EntrySupportDefault.java
- platform/openide.nodes/test/unit/src/org/openide/nodes/ChildrenKeysTest.java
- platform/openide.text/nbproject/project.properties
- platform/openide.text/src/org/openide/text/CloneableEditorSupport.java
- platform/openide.util/test/unit/src/org/openide/util/RequestProcessorTest.java
There are compiler warnings about rawtype usage with a Reference like the following
[nb-javac] .../platform/openide.util.ui/test/unit/src/org/openide/util/actions/CallbackSystemActionTest.java:102: warning: [rawtypes] found raw type: Reference
[nb-javac]         Reference actionref = new WeakReference(systemaction);
[nb-javac]         ^
[nb-javac]   missing type arguments for generic class Reference<T>
[nb-javac]   where T is a type-variable:
[nb-javac]     T extends Object declared in class Reference
> [NETBEANS-3454] Fixed compiler warnings concerning rawtypes Reference

- java/java.source.ant/src/org/netbeans/modules/java/source/ant/ProjectRunnerImpl.java
- java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java
There are compiler warnings about rawtype usage with a Iterable like the following
```
[repeat] .../java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java:197: warning: [rawtypes] found raw type: Iterable
[repeat]     public static <E> Iterable<E> checkedIterableByFilter(final Iterable raw, final Class<E> type, final boolean strict) {
[repeat]                                                                 ^
[repeat]   missing type arguments for generic class Iterable<T>
[repeat]     T extends Object declared in interface Iterable
```
> [NETBEANS-3451] Fixed compiler warnings concerning rawtypes Iterable

- platform/openide.awt/src/org/openide/awt/ContextAction.java
There are compiler warnings about rawtype usage with a Performer like the following
```
[repeat] .../platform/openide.awt/src/org/openide/awt/ContextAction.java:461: warning: [rawtypes] found raw type: Performer
[repeat]                 Performer l = (Performer)obj;
[repeat]                 ^
[repeat]   missing type arguments for generic class Performer<Data>
[repeat]   where Data is a type-variable:
[repeat]     Data extends Object declared in class Performer
```
> [NETBEANS-3458] Fixed compiler warnings concerning rawtypes Performer

- ide/xml/test/unit/src/org/netbeans/modules/xml/XMLDataObjectMimeTypeTest.java
There are compiler warnings about rawtype usage with Action like the following
```
[nb-javac] .../ide/xml/test/unit/src/org/netbeans/modules/xml/XMLDataObjectMimeTypeTest.java:79: warning: [rawtypes] found raw type: Action
[nb-javac]         Mutex.EVENT.readAccess(new Mutex.Action() {
[nb-javac]                                         ^
[nb-javac]   missing type arguments for generic class Action<T>
[nb-javac]   where T is a type-variable:
[nb-javac]     T extends Object declared in interface Action
```
> [NETBEANS-3510] Fixed compiler warnings concerning rawtypes Action

- platform/core.output2/nbproject/project.properties
- platform/core.output2/src/org/netbeans/core/output2/FindDialogPanel.form
- platform/core.output2/src/org/netbeans/core/output2/FindDialogPanel.java
- platform/core.output2/src/org/netbeans/core/output2/options/LinkStyleModel.java
- platform/core.output2/src/org/netbeans/core/output2/options/OutputSettingsPanel.form
- platform/core.output2/src/org/netbeans/core/output2/options/OutputSettingsPanel.java
- platform/core.output2/test/unit/src/org/netbeans/core/output2/LifecycleTest.java
- platform/core.output2/test/unit/src/org/netbeans/core/output2/NbIOTest.java
- platform/core.output2/test/unit/src/org/netbeans/core/output2/OutputTabTest.java
* cast,
* deprecation,
* rawtypes and
* unchecked.
> [NETBEANS-3519] Corrected compiler warnings in Output Window project

- ide/xml.multiview/nbproject/project.properties
- ide/xml.multiview/src/org/netbeans/modules/xml/multiview/ui/SectionContainer.java
- ide/xml.multiview/src/org/netbeans/modules/xml/multiview/ui/SectionView.java
There are compiler warnings about rawtype usage with AbstractList like the following
```
[repeat] .../ide/xml.multiview/src/org/netbeans/modules/xml/multiview/ui/SectionView.java:206: warning: [rawtypes] found raw type: AbstractList
[repeat]         java.util.AbstractList removedPanels = new java.util.ArrayList();
[repeat]                  ^
[repeat]   missing type arguments for generic class AbstractList<E>
[repeat]     E extends Object declared in class AbstractList
```
> [NETBEANS-3509] Fixed compiler warnings concerning rawtypes AbstractList

- platform/core.startup/nbproject/project.properties
- platform/core.startup/src/org/netbeans/core/startup/TopLogging.java
- platform/core.startup/src/org/netbeans/core/startup/TopThreadGroup.java
- platform/openide.util.lookup/src/org/openide/util/Lookup.java
- platform/openide.util.lookup/test/unit/src/org/openide/util/lookup/SampleLookupUsages.java
There has been a deadlock in OracleLabs IGV:
```
"On Start/Stop" #46 daemon prio=1 os_prio=0 tid=0x00007fa5f89a3000 nid=0xa2d6 in Object.wait() [0x00007fa79aa84000]
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:502)
at org.openide.util.Task.waitFinished(Task.java:110)
- locked <0x000000058398da88> (a org.openide.util.RequestProcessor$Task)
at org.openide.util.RequestProcessor$Task.waitFinished(RequestProcessor.java:1672)
at org.openide.loaders.FolderInstance.waitFinished(FolderInstance.java:307)
at org.openide.loaders.FolderLookup$ProxyLkp.beforeLookup(FolderLookup.java:398)
at org.openide.util.lookup.ProxyLookup.beforeLookup(ProxyLookup.java:184)
at …
```
> Avoid lookup query in logging which may lead to deadlocks

- nbbuild/javadoctools/apichanges.xsl
Now that we have a static snapshot of former NetBeans BugZilla hosted on Apache infrastructure it looks like a good idea to update links everywhere. For example in JavaDoc templates.
> Updating BugZilla URLs from old Oracle infra to the new ASF one

- .travis.yml
Change Travis config to test enterprise modules
> [TRAVIS] Test enterprise modules

- nbbuild/jdk.xml
I was seeing "Warning: nbjdk.active=... or nbjdk.home=... is an invalid Java platform" warnings when building NB on Windows. The reason was that the build script was not finding the `jmod` executable in the JDK. This simple patch makes sure to look for it using the .exe suffix, using the same mechanism as it currently uses for `javac` et al.
> Use .exe suffix when looking for jmod on Windows

- ide/editor.settings/nbproject/project.properties
- ide/editor.settings/src/org/netbeans/api/editor/settings/AttributesUtilities.java
- ide/editor.settings/src/org/netbeans/api/editor/settings/FontColorSettings.java
- ide/editor.settings/src/org/netbeans/api/editor/settings/MultiKeyBinding.java
- ide/editor.settings/src/org/netbeans/modules/editor/settings/AttrSet.java
- ide/editor.settings/test/unit/src/org/netbeans/modules/editor/settings/AttrSetTesting.java
- ide/editor.settings/test/unit/src/org/netbeans/modules/editor/settings/SimpleWeakSetTesting.java
* cast,
* dep-ann,
* rawtypes and
* unchecked.
> [NETBEANS-3532] Corrected compiler warnings in Editor Settings project

- ide/bugtracking.commons/src/org/netbeans/modules/bugtracking/issuetable/IssueNode.java
- ide/image/src/org/netbeans/modules/image/ImageDataObject.java
- websvccommon/websvc.saas.ui/src/org/netbeans/modules/websvc/saas/ui/nodes/WsdlPortNode.java
- websvccommon/websvc.saas.ui/src/org/netbeans/modules/websvc/saas/ui/nodes/WsdlSaasNode.java
There are compiler warnings about rawtype usage with a ReadOnly like the following
```
[repeat] .../websvccommon/websvc.saas.ui/src/org/netbeans/modules/websvc/saas/ui/nodes/WsdlPortNode.java:127: warning: [rawtypes] found raw type: ReadOnly
[repeat]         ss.put( new PropertySupport.ReadOnly( "URL", // NOI18N
[repeat]                                    ^
[repeat]   missing type arguments for generic class ReadOnly<T>
[repeat]     T extends Object declared in class ReadOnly
```
> [NETBEANS-3502] Fixed compiler warnings concerning rawtypes ReadOnly

- platform/openide.explorer/test/unit/src/org/openide/explorer/propertysheet/EnumPropertyEditorTest.java
There are compiler warnings about rawtype usage with a ReadWrite like the following
```
[nb-javac] .../platform/openide.explorer/test/unit/src/org/openide/explorer/propertysheet/EnumPropertyEditorTest.java:81: warning: [rawtypes] found raw type: ReadWrite
[nb-javac]     private static class EProp extends PropertySupport.ReadWrite {
[nb-javac]                                                       ^
[nb-javac]   missing type arguments for generic class ReadWrite<T>
[nb-javac]   where T is a type-variable:
[nb-javac]     T extends Object declared in class ReadWrite
```
> [NETBEANS-3465] Fixed compiler warnings concerning rawtypes ReadWrite

- java/junit.ant.ui/nbproject/project.properties
- java/junit.ant.ui/src/org/netbeans/modules/junit/ant/ui/JUnitProjectOpenedHook.java
There are compiler warnings about rawtype usage with a FutureTask like the following
```
[nb-javac] .../java/junit.ant.ui/src/org/netbeans/modules/junit/ant/ui/JUnitProjectOpenedHook.java:225: warning: [rawtypes] found raw type: FutureTask
[nb-javac]             RunnableFuture<ProjectProblemsProvider.Result> f = new FutureTask(new Runnable() {
[nb-javac]                                                                    ^
[nb-javac]   missing type arguments for generic class FutureTask<V>
[nb-javac]   where V is a type-variable:
[nb-javac]     V extends Object declared in class FutureTask
```
> [NETBEANS-3461] Fixed compiler warnings concerning rawtypes FutureTask

- ide/html.parser/test/unit/src/org/netbeans/modules/html/parser/model/GenerateElementsIndex.java
- java/spi.java.hints/src/org/netbeans/modules/java/hints/providers/code/FSWrapper.java
There are compiler warnings about rawtype usage with a Enum like the following
```
[nb-javac] .../ide/html.parser/test/unit/src/org/netbeans/modules/html/parser/model/GenerateElementsIndex.java:749: warning: [rawtypes] found raw type: Enum
[nb-javac]             for (Iterator<? extends Enum> i = enumCollection.iterator(); i.hasNext();) {
[nb-javac]                                     ^
[nb-javac]   missing type arguments for generic class Enum<E>
[nb-javac]   where E is a type-variable:
[nb-javac]     E extends Enum<E> declared in class Enum
```
> [NETBEANS-3477] Fixed compiler warnings concerning rawtypes Enum

- java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/SemanticHighlighterBase.java
- webcommon/javascript2.knockout/src/org/netbeans/modules/javascript2/knockout/model/KnockoutExportInterceptor.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/api/IndexedElement.java
There are compiler warnings about rawtype usage with a EnumSet like the following
```
[repeat] .../webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/api/IndexedElement.java:393: warning: [rawtypes] found raw type: EnumSet
[repeat]             EnumSet result = EnumSet.noneOf(Modifier.class);
[repeat]             ^
[repeat]   missing type arguments for generic class EnumSet<E>
[repeat]     E extends Enum<E> declared in class EnumSet
```
> [NETBEANS-3478] Fixed compiler warnings concerning rawtypes EnumSet

- ide/xml.text.obsolete90/src/org/netbeans/modules/xml/text/syntax/XMLSyntaxSupport.java
- java/java.examples/nbproject/project.properties
- java/java.examples/src/org/netbeans/modules/java/examples/J2SESampleProjectGenerator.java
- java/xml.tools.java/nbproject/project.properties
- java/xml.tools.java/src/org/netbeans/modules/xml/tools/java/generator/SAXBindingsParser.java
- php/php.samples/src/org/netbeans/modules/php/samples/PHPSamplesWizardIterator.java
- profiler/profiler.oql/src/org/netbeans/modules/profiler/oql/engine/api/impl/OQLEngineImpl.java
- webcommon/javascript2.lexer/src/org/netbeans/modules/javascript2/lexer/NbLexerCharStream.java
There are compiler warnings about rawtype usage with a Stack like the following
```
[repeat] .../profiler/profiler.oql/src/org/netbeans/modules/profiler/oql/engine/api/impl/OQLEngineImpl.java:245: warning: [rawtypes] found raw type: Stack
[repeat]                 Stack toInspect = new Stack();
[repeat]                                       ^
[repeat]   missing type arguments for generic class Stack<E>
[repeat]     E extends Object declared in class Stack
```
> [NETBEANS-3466] Fixed compiler warnings concerning rawtypes Stack

- ide/api.xml.ui/nbproject/project.properties
- ide/api.xml.ui/src/org/netbeans/api/xml/cookies/CookieMessage.java
- ide/api.xml.ui/src/org/netbeans/spi/xml/cookies/SharedXMLSupport.java
- ide/api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/SharedXMLSupportTest.java
- ide/api.xml.ui/test/unit/src/org/netbeans/spi/xml/cookies/TransformableSupportTest.java
* rawtypes,
* static and
* unchecked.
> [NETBEANS-3535] Corrected compiler warnings in XML Tools API UI project

- java/classfile/nbproject/project.properties
- java/classfile/test/unit/src/org/netbeans/modules/classfile/ParamNameTest.java
- java/classfile/test/unit/src/regression/datafiles/test91098.java
> [NETBEANS-3534] Corrected compiler warnings in Classfile Reader project

- php/php.codeception/src/org/netbeans/modules/php/codeception/run/CodeceptionLogParser.java
- php/php.codeception/test/unit/data/codeception-log-warning-phpunit-suite.xml
- php/php.codeception/test/unit/src/org/netbeans/modules/php/codeception/run/CodeceptionLogParserTest.java
Marks test with warning in log as failed.
> [NETBEANS-3560] Codeception - warning in log does not mark test as failed

- enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/data/JDKVersion.java
- enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/ServerTasks.java
- enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/parser/JvmConfigReader.java
The code changes only affect Payara related code. It is a feature to support vendor specific JVM options in Payara Server.
> NETBEANS-3547 Support vendor specific JVM options in Payara Server

- ide/api.java.classpath/src/org/netbeans/api/java/classpath/ClassLoaderSupport.java
- ide/api.java.classpath/src/org/netbeans/api/java/queries/BinaryForSourceQuery.java
- ide/api.java.classpath/src/org/netbeans/modules/java/classpath/ClassPathAccessor.java
- ide/api.java.classpath/test/unit/src/org/netbeans/api/java/classpath/ClassPathTest.java
- ide/api.java.classpath/test/unit/src/org/netbeans/api/java/queries/BinaryForSourceQueryTest.java
- ide/api.java.classpath/test/unit/src/org/netbeans/api/java/queries/SourceForBinaryQueryTest.java
> [NETBEANS-3533] Corrected compiler warnings in Classpath APIs project

- platform/core.network/src/org/netbeans/core/network/utils/LocalAddressUtils.java
There are compiler warnings about rawtype usage with a Callable like the following
```
[repeat] .../platform/core.network/src/org/netbeans/core/network/utils/LocalAddressUtils.java:103: warning: [rawtypes] found raw type: Callable
[repeat]     private static final Callable<InetAddress> C1 = new Callable(){
[repeat]                                                         ^
[repeat]   missing type arguments for generic class Callable<V>
[repeat]   where V is a type-variable:
[repeat]     V extends Object declared in interface Callable
```
> [NETBEANS-3489] Fixed compiler warnings concerning rawtypes Callable

- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/BasicTask.java
- enterprise/payara.common/src/org/netbeans/modules/payara/common/BasicTask.java
There are compiler warnings about rawtype usage with a BasicTask like the following
```
[repeat] .../enterprise/payara.common/src/org/netbeans/modules/payara/common/BasicTask.java:235: warning: [rawtypes] found raw type: BasicTask
[repeat]         protected StateChange(final BasicTask task, final TaskState result,
[repeat]                                     ^
[repeat]   missing type arguments for generic class BasicTask<V>
[repeat]   where V is a type-variable:
[repeat]     V extends Object declared in class BasicTask
```
> [NETBEANS-3488] Fixed compiler warnings concerning rawtypes BasicTask

- platform/api.search/nbproject/project.properties
- platform/api.search/src/org/netbeans/modules/search/GraphicalSearchListener.java
- platform/api.search/src/org/netbeans/modules/search/ReplaceTask.java
- platform/api.search/src/org/netbeans/modules/search/ui/FileObjectPropertySet.java
- platform/api.search/test/unit/src/org/netbeans/api/search/SearchHistoryTest.java
- platform/api.search/test/unit/src/org/netbeans/api/search/ui/SearchPatternControllerTest.java
- platform/api.search/test/unit/src/org/netbeans/modules/search/matcher/BufferedCharSequenceTest.java
- platform/api.search/test/unit/src/org/netbeans/modules/search/matcher/SearchPerformanceComparator.form
- platform/api.search/test/unit/src/org/netbeans/modules/search/matcher/SearchPerformanceComparator.java
- platform/api.search/test/unit/src/org/netbeans/spi/search/SearchScopeDefinitionTest.java
* deprecation,
* rawtypes and
* unchecked.
> [NETBEANS-3564] Corrected compiler warnings in Search API

- platform/o.n.bootstrap/nbproject/project.properties
- platform/o.n.bootstrap/src/org/netbeans/FixedModule.java
- platform/o.n.bootstrap/src/org/netbeans/JarClassLoader.java
- platform/o.n.bootstrap/src/org/netbeans/Module.java
- platform/o.n.bootstrap/src/org/netbeans/ModuleInstaller.java
- platform/o.n.bootstrap/src/org/netbeans/ModuleManager.java
- platform/o.n.bootstrap/src/org/netbeans/NbInstrumentation.java
- platform/o.n.bootstrap/src/org/netbeans/NetigsoHandle.java
- platform/o.n.bootstrap/src/org/netbeans/NetigsoModule.java
- platform/o.n.bootstrap/src/org/netbeans/PatchByteCode.java
- platform/o.n.bootstrap/src/org/netbeans/ProxyClassLoader.java
- platform/o.n.bootstrap/src/org/netbeans/Stamps.java
- platform/o.n.bootstrap/src/org/netbeans/TopSecurityManager.java
- platform/o.n.bootstrap/src/org/netbeans/Util.java
- platform/o.n.bootstrap/test/unit/src/org/fakepkg/FakeHandler.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/CountingSecurityManager.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/ModuleFactoryAlienTest.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/ModuleFactoryTest.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/ModuleManagerTest.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/PatchByteCodeTest.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/ProxyClassLoaderNB11PackageAnnotationsTest.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/ProxyClassLoaderTest.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/ProxyClassPackagesTest.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/ProxyURLStreamHandlerFactoryTest.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/SetupHid.java
* deprecation,
* rawtypes and
* unchecked.
As all compiler warning in this project could be fixed / suppressed when appropriate the flag `-Werror` was added to build property `javac.compilerargs`.
> [NETBEANS-3559] Corrected compiler warnings in Bootstrap project.

- java/maven/src/org/netbeans/modules/maven/modelcache/MavenProjectCache.java
- java/maven/test/unit/src/org/netbeans/modules/maven/NbMavenProjectImplTest.java
Amends #1209 to better handle reactor builds where a `.mvn/` might be present at the root but we want to interpret a profile in a module. Not perfect but better than nothing.
> Look for .mvn/maven.config in parent directories as well

- platform/o.apache.commons.io/external/binaries-list
- platform/o.apache.commons.io/external/commons-io-2.6-license.txt
- platform/o.apache.commons.io/external/commons-io-2.6-notice.txt
- platform/o.apache.commons.io/manifest.mf
- platform/o.apache.commons.io/nbproject/project.properties
- platform/o.apache.commons.io/nbproject/project.xml
Notes:
- Requires JDK 1.7 or later
- Compatibility with Java 9 module system
- Many fixed bugs
- Improved performance
- Deprecate `Charsets Charset` constants in favor of Java 7's `java.nio.charset.StandardCharsets`
- All `closeQuietly` overloads in `org.apache.commons.io.IOUtils` have been deprecated. Use the `try-with-resources` statement or handle suppressed exceptions manually.
- The class `org.apache.commons.io.FileSystemUtils` has been deprecated. Use equivalent methods in `java.nio.file.FileStore instead`.
[Apache Commons-IO Web Page](https://commons.apache.org/proper/commons-io/)
[Apache Commons-IO Release Notes](https://commons.apache.org/proper/commons-io/upgradeto2_6.html)
> [NETBEANS-3551] - Upgrade Apache Commons-IO from 1.4 to 2.6

- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-0.22-license.txt
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
This PR updates FlatLaf to 0.22, which includes following fixes/improvements for NetBeans:
- Changed ProgressBar styling to reduce height so that it fits better into the NB status bar.
Here is a full list of changes: https://github.com/JFormDesigner/FlatLaf/releases/tag/0.22
> [NETBEANS-3428] Update FlatLaf from 0.21 to 0.22

- groovy/gradle.java/src/org/netbeans/modules/gradle/java/JavaActionProvider.java
- groovy/gradle.java/src/org/netbeans/modules/gradle/java/action-mapping.xml
Enabling following actions on groovy files to support execution of spock tests in gradle projects:
- Test Package
- Test File / Debug Test File
- Run Focused Test Method / Debug Focused Test Method
Fix handling of spock test methods containing spaces.
> [NETBEANS-3595] Enable actions to execute spock tests

- java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java
- java/java.source.base/test/unit/src/org/netbeans/api/java/source/SourceUtilsTestUtil.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/CompileWorkerTestBase.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorkerTest.java
- java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBEnter.java
- java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBJavaCompiler.java
This increases stability of indexing without nb-javac when there are errors in the source code - in particular when some classes are missing. Before, this lead to more exceptions/broken caches.
> More stabilization of the vanilla javac indexer.

- enterprise/web.monitor/external/binaries-list
- enterprise/web.monitor/external/servlet-api-6.0.53-license.txt
- enterprise/web.monitor/manifest.mf
- enterprise/web.monitor/nbproject/project.properties
Notes:
- Several bug fixes
- Fix 34 security vulnerabilities
- Improved performance
- Tomcat 6 has now reached end of life
[Apache Tomcat 6 Release Notes](https://tomcat.apache.org/tomcat-6.0-doc/changelog.html)
> [NETBEANS-3603] - Upgrade 'web.monitor' (tomcat:servlet-api) from 6.0.13 to 6.0.53

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/fontscolors/FlatLafDark-INI-tokenColorings.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/fontscolors/FlatLafDark-Properties-tokenColorings.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/fontscolors/FlatLafDark-annotations.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/layer.xml
Tweaked mostly debug breakpoints colors and properties files colors.
Added token colorings for INI files.
This is a followup PR to #1768.
Before:
After:
Color scheme of properties files is visually equivalent, I have only made cleanups to the definition.
> Other tweaks to FlatDark color profile.

- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Spec:
https://openjdk.java.net/projects/jdk/15/spec/
Javadoc:
https://download.java.net/java/early_access/jdk15/docs/api/
> [NETBEANS-3623] - Add javadoc for JDK 15 early access

- webcommon/extbrowser.chrome/src/org/netbeans/modules/extbrowser/plugins/chrome/ChromiumManagerAccessor.java
The problem results in netbeans not being able to find the installed plugin and
thus not loading the debugging support for HTML5/JS projects.
> Ubuntu installs Chromium as a snap and the config directory is moved

- enterprise/websvc.rest/external/binaries-list
- enterprise/websvc.rest/external/jersey-core-1.18.6-license.txt
- enterprise/websvc.rest/manifest.mf
- enterprise/websvc.rest/nbproject/project.properties
- enterprise/websvc.rest/nbproject/project.xml
Notes:
- Several bug fixes
- Many improvements
- Version 1.19+ has [breaking changes](https://github.com/jersey/jersey-1.x/releases?after=post-1.12)
[Jersey-core web page](https://eclipse-ee4j.github.io/jersey/)
> [NETBEANS-3628] - Upgrade jersey-core from 1.5 to 1.18.6

- java/spi.java.hints/external/binaries-list
- java/spi.java.hints/external/byte-buddy-1.10.6-license.txt
- java/spi.java.hints/nbproject/project.properties
- java/spi.java.hints/nbproject/project.xml
Notes:
- Update to ASM 7.2
- Java 14 compatibility
- Add experimental support for Java 15.
- Reduce byte code level to Java 5
- Several performance improvements
- Several bug fixes
- Security  improvements
- Remove Lombok and add methods using Byte Buddy plugin
[Byte Buddy Web Page](http://bytebuddy.net)
[Byte Buddy Release Notes](https://github.com/raphw/byte-buddy/blob/master/release-notes.md)
> [NETBEANS-3629] - Upgrade Byte Buddy from 1.7.9 to 1.10.6

- contrib/cordova.platforms.ios/nbproject/project.xml
- webcommon/libs.plist/external/binaries-list
- webcommon/libs.plist/external/dd-plist-1.23-license.txt
- webcommon/libs.plist/manifest.mf
- webcommon/libs.plist/nbproject/project.properties
Notes:
- More specific exceptions depending on the exact error
- Many performance improvements
- Several bug fixes
- Requires JDK 1.6 or later
[dd-plist Web Page](https://github.com/3breadt/dd-plist)
[dd-plist Release Notes](https://github.com/3breadt/dd-plist/releases)
> [NETBEANS-3632] - Upgrade dd-plist from 1.3 to 1.23

- ide/c.google.gson/external/binaries-list
- ide/c.google.gson/external/gson-2.8.4-license.txt
- ide/c.google.gson/nbproject/project.properties
- ide/c.google.gson/nbproject/project.xml
Notes:
- New Features
- Numerous other bugfixes
- Version 2.8.5 has a backward incompatible change
[Gson Web Page](https://github.com/google/gson)
[Gson Release Notes](https://github.com/google/gson/blob/master/CHANGELOG.md)
> [NETBEANS-3631] - Upgrade Gson from 2.7 to 2.8.4

- enterprise/libs.commons_fileupload/external/binaries-list
- enterprise/libs.commons_fileupload/external/commons-fileupload-1.3-notice.txt
- enterprise/libs.commons_fileupload/external/commons-fileupload-1.4-license.txt
- enterprise/libs.commons_fileupload/external/commons-fileupload-1.4-notice.txt
- enterprise/libs.commons_fileupload/manifest.mf
- enterprise/libs.commons_fileupload/nbproject/project.properties
- enterprise/libs.commons_fileupload/src/org/netbeans/libs/commons_fileupload/Bundle.properties
Notes:
- Requires Java 6 or later
- Performance Improvement in MultipartStream
- Many bug fixes
- Security fixes:
- CVE-2014-0050
- CVE-2016-3092
[Apache commons-fileupload Web Page](https://commons.apache.org/proper/commons-fileupload/)
[Apache commons-fileupload Release Notes](https://dist.apache.org/repos/dist/release/commons/fileupload/RELEASE-NOTES.txt)
> [NETBEANS-3602] - Upgrade Apache commons-fileupload from 1.3 to 1.4

- ide/web.browser.api/src/org/netbeans/modules/web/browser/api/BrowserUISupport.java
- platform/openide.awt/apichanges.xml
- platform/openide.awt/src/org/openide/awt/DropDownButtonFactory.java
- platform/openide.awt/src/org/openide/awt/IconWithArrow.java
- platform/openide.util.ui/src/org/openide/util/CachedHiDPIIcon.java
- platform/openide.util.ui/src/org/openide/util/spi/SVGLoader.java
- webcommon/web.clientproject.api/src/org/netbeans/modules/web/clientproject/browser/ActiveBrowserAction.java
Ensure that the HiDPI icon scaling improvements made in NETBEANS-2614 (https://github.com/apache/netbeans/pull/1273) applies to the browser icon. See before/after screenshots.
API change: This adds a public method in DropDownButtonFactory to make the dropdown arrow icon available to other modules.
Also add some missing "since" annotations in the openide.util.ui module.
> [NETBEANS-3593] Make toolbar browser icon take advantage of improved HiDPI scaling.

- platform/core.windows/src/org/netbeans/core/windows/view/dnd/DragAndDropFeedbackVisualizer.java
- platform/core.windows/src/org/netbeans/core/windows/view/dnd/TopComponentDragSupport.java
- platform/core.windows/src/org/netbeans/core/windows/view/dnd/WindowDnDManager.java
- platform/core.windows/src/org/netbeans/core/windows/view/ui/toolbars/DnDSupport.java
On Windows, on displays that have a HiDPI scaling set (e.g. 150% or 200%), drag-and-drop to reposition editors and modes in the NetBeans window system does not work properly. See https://issues.apache.org/jira/browse/NETBEANS-2954 .
This appears to be due to a JDK bug, where java.awt.dnd.DragSourceEvent.getLocation() returns the wrong screen coordinate when HiDPI displays are involved. The workaround is to use MouseInfo.getPointerInfo() instead--that one works correctly.
Both MouseInfo and DragSourceEvent get their coordinates from a call to the "GetCursorPos" Windows API function. The latter returns device coordinates rather than logical coordinates for DPI-aware applications (including java.exe and the netbeans launcher since https://github.com/apache/netbeans/pull/883 ).
But in the …
> [NETBEANS-2954] Fix broken tab dragging on HiDPI displays (Windows)

- .travis.yml
- platform/core.network/src/org/netbeans/core/network/utils/IpAddressUtils.java
- platform/core.network/src/org/netbeans/core/network/utils/LocalAddressUtils.java
Currently, tests fails because the `LocalAddressUtils.getMostLikelyLocalInetAddresses()` - when executed by Travis - returns "127.0.0.1" which means the code was not able to determine the local host's IP.
This PR fixes this problem by improving local IP address discovery:
An additional method is added to the multiple ways of finding own host's IP: **UDP Socket**. In some environments (e.g. Travis) this addition will be able to find the IP where the other methods fail. However, discovering the IP of the local host remains an imprecise discipline.
Also, the `getMostLikelyLocalInetAddresses()` method is now more precise about filtering out loopback addresses potentially returned by one of the underlying methods. Returning the loopback address from this method should really, really be a last …
> [NETBEANS-3652] PAC: myIpAddress() returns "127.0.0.1" when executed in Travis env

- java/classfile/nbproject/project.properties
- platform/o.n.bootstrap/nbproject/project.properties
The two commits: 
- [NETBEANS-3559 Corrected compiler warnings in Bootstrap project.](https://github.com/apache/netbeans/commit/1f0916ad1a923)
- [NETBEANS-3534 Corrected compiler warnings in Classfile Reader project](https://github.com/apache/netbeans/commit/0eb938809158b7515b404d834966768e7a3e63c0)
introduced the `-Werror` javac argument. The argument causes the build to fail on JDK9+:
```
-do-compile:
[nb-javac] Compiling 40 source files to /home/matthias/src/netbeans/platform/o.n.bootstrap/build/classes
[repeat] warning: [options] bootstrap class path not set in conjunction with -source 8
[repeat] error: warnings found and -Werror specified
[repeat] error: warnings found and -Werror specified
[repeat] error: warnings found and -Werror specified
[repeat] error: warnings found and …
```
> Building on JDK9+ failes caused by -Werror

- platform/core.network/src/org/netbeans/core/network/utils/LocalAddressUtils.java
The problem is located in IpAddressUtils#removeLoopback. The method
expects, that the supplied list provides an Iterator, that supports
remove.
The list returned by Arrays#asList does not provide that, it is just a
view on the array.
> LocalAddressUtils#getMostLikelyLocalInetAddresses fails if list contains loopback

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatSlidingButtonUI.java
This PR implements the sliding buttons for FlatLaf. Sliding buttons are used when views are minimized. The sliding buttons change background color if selected or mouse is moved over them.
Old:
New:
> [NETBEANS-3428] FlatLaf: new sliding button

- .travis.yml
- platform/core.network/test/unit/src/org/netbeans/core/network/utils/hname/mac/HostnameUtilsMacTest.java
- platform/masterfs.macosx/nbproject/project.xml
- platform/masterfs.macosx/test/unit/src/org/netbeans/modules/masterfs/watcher/macosx/OSXNotifierTest.java
- Compile platform modules in macOS environment
- Add OSXNotifier test class based in LinuxNotifier235632Test
- Run `platform/masterfs.macosx` tests in macOS environment
> [TRAVIS] Compile and run tests in macOS

- ide/editor.search/src/org/netbeans/modules/editor/search/SearchComboBoxEditor.java
- ide/spi.palette/src/org/netbeans/modules/palette/ui/CheckRenderer.java
- java/maven/src/org/netbeans/modules/maven/dependencies/CheckRenderer.java
- php/php.project/src/org/netbeans/modules/php/project/connections/ui/transfer/tree/CheckRenderer.java
Fixes for check renderers and search combobox:
- check renderers had wrong background
- search checkbox had double border
Before:
After:
> [NETBEANS-3428] FlatLaf: fixes for check renderers and search combobox

- platform/core.multitabs/src/org/netbeans/core/multitabs/impl/TabDataRenderer.java
This is an attempt to fix/workaround the startup performance problem if many files are open and multitabs are used (which is not the default).
There are actually two problems:
1. `getPreferredWidth()` is invoked very often from the multitabs table listener (~60000 times for 200 open files)
2. the text (usually a filename) is always HTML (but does not contain other HTML tags), which involves slow HTML parsing
This PR addresses only 2.
> [NETBEANS-3666] improve performance of multitabs on startup if many files are open

- nbi/engine/native/jnilib/windows/src/jni_WindowsRegistry.c
The `WindowsRegistry_set32BitValue0()` function was incorrectly using the length of the Registry name (e.g. 'NoModify') as the the length of value. Since the Registry value we are setting is of type DWORD the length is indeed always exactly 4 bytes, regardless of OS bitness. 
Solution: `sizeof(dword)` will always return 4, but we might as well have hard-coded the 4.
Impact: The impact of bug has been seen when NBI sets the `NoModify` registry value in the `Uninstall` section of the Registry. The bug has existed for years but has only minor impact, for example with system analyzers flagging the 'NoModify' value as suspect or not being able to read the value with tools such as Powershell.
> [NETBEANS-2523] Installer creates invalid Win Registry value

- java/form/src/org/netbeans/modules/form/FormLoaderSettings.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties
Before:
After:
Before:
After:
The reason for the too small icons in the above images is that I took the screenshots running NB in Java 8 on a150% HiDPI screen.
> [NETBEANS-3428] FlatLaf: fixes for form designer

- ide/editor.lib/src/org/netbeans/editor/BaseKit.java
With this change, my plugin's JTextComponent's keymap listener is now invoked from the EDT. This removes the Swing threading violation.
> [NETBEANS-3674] change JTextComponent Keymap from EventDispatchThread

- platform/openide.awt/src/org/openide/awt/DropDownButton.java
- platform/openide.awt/src/org/openide/awt/DropDownToggleButton.java
DropDownButton/DropDownToggleButton are most commonly used in the various NetBeans toolbars--there is one pair of DropDownButton buttons in the editor toolbar, for instance.
(I use both DropDownButton and DropDownToggleButton in my NetBeans Platform application, and have tested both there. I have tested DropDownButton in the IDE as well. There are no current uses of DropDownToggleButton in the IDE.)
Details:
* Copy an old bugfix from DropDownButton to DropDownToggleButton (an added
updateRollover call), to fix a problem where the latter would show the wrong
icon after an icon change.
* Fix a bug where DropDownButton would occasionally get in a state where two
mouse clicks were required to open it.
* Prevent dropdown button menus from showing up when the button is disabled.
* If …
> [NETBEANS-3581] Improvements to DropDownButton/DropDownToggleButton

- platform/api.search/src/org/netbeans/modules/search/BasicSearchForm.java
- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-0.24-license.txt
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/openide.awt/src/org/openide/awt/HtmlLabelUI.java
- platform/openide.explorer/src/org/openide/explorer/view/OutlineView.java
Improvements and fixes thru FlatLaf 0.24:
- smooth scrolling (in the same way as already in NB for Windows LaF)
- fixed missing borders in table header (e.g. in "Watches" view)
- removed border from "Change Visible Columns" icon button in right-top corner of tables (e.g. in "Watches" view)
- progress bar in "Flat Dark" theme is now blue
Other fixes in NB code:
- "Flat Dark" theme: lighter gray color for editor/view borders and separators in main window
- ascending/descending icons in table header replaced with FlatLaf icons
- get rid of the focus indicator (black rectangle) in trees (HtmlLabelUI.java)
- fixed unreadable info text in "Find in Project" dialog (in dark theme)
- fixed too bright separators in "Find in Project" dialog (in dark theme) (BasicSearchForm.java)
- fixed wrong …
> [NETBEANS-3428] Update FlatLaf from 0.23 to 0.24 and other fixes

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
I thought it would better fit a 1 sized border with background color than a one with the usual lighter gray component color.
> [NETBEANS-3428] Fix the border of QuickSearch

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
This PR adds a lot of missing colors to "FlatLaf Dark" LAF.
I've searched the the three other Dark LAFs for missing colors and copied them to FlatLaf.
Some with modifications, but many without.
This PR fixes also NETBEANS-3688.
Debugging view:
Files with versioning highlighting (maybe it is necessary to click "Reset colors" button in "Options > Fonts & Colors > Versioning" to get new colors):
File chooser on Windows fix:
Tasks view fix:
> [NETBEANS-3428] FlatLaf: colors for history, versioning, debugger, bugtracking, etc

- ide/editor.lib/src/org/netbeans/editor/BaseKit.java
This is a tweak to pull request #1856. Always run "pushKeymapChange" (even if no JTextComponents affected) so that SearchableKit.fireActionChange always happens. Removes check "if(arr.length>0)".
> Base kit edt2

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/Installer.java
- platform/o.n.swing.plaf/manifest.mf
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/LFCustoms.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/aqua/AquaLFCustoms.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/gtk/GtkLFCustoms.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/metal/MetalLFCustoms.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/nimbus/NimbusLFCustoms.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/winclassic/WindowsLFCustoms.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/windows8/Windows8LFCustoms.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/winvista/VistaLFCustoms.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/winxp/XPLFCustoms.java
Also added the preferred color profile for standard supported LaF-s, so switching back some Dark to regular light LaF offers you changing the editor coloring back to default NetBeans as well.
> [NETBEANS-3428] Remove experimental from FlatLafDark

- ide/defaults/src/org/netbeans/modules/defaults/BlueTheme-editor.xml
- ide/gsf.codecoverage/src/org/netbeans/modules/gsf/codecoverage/Bundle.properties
- ide/gsf.codecoverage/src/org/netbeans/modules/gsf/codecoverage/CoverageHighlightsContainer.java
- ide/gsf.codecoverage/src/org/netbeans/modules/gsf/codecoverage/fontsColors.xml
- ide/gsf.codecoverage/src/org/netbeans/modules/gsf/codecoverage/layer.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/fontscolors/FlatLafDark-highlights.xml
The Options Panel:
The default colors:
Norway Today:
FlatLaf Dark:
Well these are the colors I could came up with, I guess they could be improved by someone more artistic than me.
> [NETBEANS-3700] No more harcoding for Code Coverage Highlights.

- php/php.project/src/org/netbeans/modules/php/project/connections/ftp/FtpClient.java
https://issues.apache.org/jira/browse/NETBEANS-3647
FTP upload stops when uploading to IIS FTP reporting a Truncated server reply: '550 '. The broken behavior can be worked around by configuring the ftp client to be lenitent when parsing server replies.
> [NETBEANS-3647] Update FtpClient.java - compatibility with IIS

- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-0.25.1-license.txt
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
Improvements and fixes thru FlatLaf 0.25.1:
- [NETBEANS-3703] fixed broken tree node expand/collapse with right/left keys on macOS
- fixed broken combobox keyboard navigation and show/hide popup on macOS
- hide menu mnemonics by default and show them only when `Alt` key is pressed (same as in Windows LAF)
- option in progress bar to use always large height even if no text is painted (for [NETBEANS-3713])
- UI default value `Tree.textBackground` now has a valid color and is no
longer `null` (for [NETBEANS-3688])
- "Find in Project" dialog: removed empty space in "(    test    )" and "(    edit    )" links
Other fixes in NB code:
- fixed border color of tabs "open documents" popup
- "FlatLaf Light" on Windows: fixed background of "places" bar in file chooser
Windows file chooser:
"open …
> [NETBEANS-3428] Update FlatLaf from 0.24 to 0.25.1 and other fixes

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatEditorTabCellRenderer.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatEditorTabDisplayerUI.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatTabControlIcon.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatViewTabDisplayerUI.java
This PR improves PR #1771
Editor and View tabs:
- tab separators
- tab text moved up 1px
- smaller tab insets
- minimize icon improved
View tabs only:
- minimized space between tab text and close button
- center tab text if close button is hidden
- make sure that as much tab text as possible is shown by dynamically reducing left/right margins
- avoid empty tabs (truncate text if necessary)
New:
Old (from PR #1771):
The tab text in views is now centered (was left aligned) because left aligned text looks horrible with tab separators.
When horizontal space becomes rare, the left/right tab margins are reduced.
Empty tabs (no tab text painted) does no longer occur.
> [NETBEANS-3428] FlatLaf: improving editor and view tabs in main window

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java
- platform/progress.ui/nbproject/project.properties
- platform/progress.ui/src/org/netbeans/modules/progress/ui/AbstractWindowRunner.java
- platform/progress.ui/src/org/netbeans/modules/progress/ui/ListComponent.java
- platform/progress.ui/src/org/netbeans/modules/progress/ui/NbProgressBar.java
- platform/progress.ui/src/org/netbeans/modules/progress/ui/PopupPane.java
- platform/progress.ui/src/org/netbeans/modules/progress/ui/StatusLineComponent.java
- progress bar in status bar now always has large height (has changed height before depending on whether text is painted in progress bar)
- cancel button replaced with vector icon
- fixed color of separator in "Processes" popup
- remove separator of last row in "Processes" popup if process was removed
- use preferred height for progress bars in "Processes" popup
Before ("Processes" popup shown):
Before, separator was not removed after background scanning finished:
After:
"Processes" popup:
> [NETBEANS-3713] FlatLaf: progress bar improvements

- ide/editor.lib/src/org/netbeans/editor/Utilities.java
- java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/breakpoints/ConditionsPanel.java
This PR:
- fixes double border in conditional breakpoint editor (FlatLaf and Windows LAF)
- fixes displaced caret in single line editor
(in FlatLaf caret was 6px to left; in other LAFs hardly noticeable 0-2px to left)
https://issues.apache.org/jira/browse/NETBEANS-3657
FlatLaf:
Windows:
> [NETBEANS-3657] FlatLaf: fix Conditional Breakpoint editor

- nb/welcome/src/org/netbeans/modules/welcome/content/Utils.java
Commit 5fb6012a7d2bfd233b4b9ba8b9b3fbc6d98e1171 moved the definition
of the foreground color into the resource bundle. Instead of the correct
constant COLOR_TAB_FOREGROUND COLOR_TAB_BACKGROUND is referenced.
The consequence of the wrong constant is an unreadable welcome screen
on LAFs, that don't override the colors.
> Use correct constant to fetch welcome screen topbar foreground

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatEditorTabCellRenderer.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatViewTabDisplayerUI.java
Fix for this: https://github.com/apache/netbeans/pull/1883#issuecomment-576024263
Editor and View tabs:
- 2px larger space between tab text and close icon
- close icon moved up 1px so that it is not on the same baseline as the tab text
Multi-tabs:
- tab text moved up 1px so that it is at the same baseline as View tabs
> [NETBEANS-3428] FlatLaf: optimized editor and view tabs in main window

- ide/editor.completion/src/org/netbeans/modules/editor/completion/CompletionScrollPane.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
Some Look and Feels use different colors for displaying selected and focused list cells. FlatLaf is one of them. This little change allows the LaF to control the selected and by that focused item in the code completion list. It could be confusing to decide which item is selected, especially on two item lists.
Before:
After:
> [NETBEANS-3717] Allow LaF to change the color of the selected item in Code Completion

- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-0.26-license.txt
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties
- platform/spi.quicksearch/src/org/netbeans/modules/quicksearch/QuickSearchComboBar.java
FlatLaf 0.26 brings new menu styling with new menu bar and popup background colors. Previously they had same background color as panels, which made popup menus hard to distinguish.
Before in FlatLaf Light:
After in FlatLaf Light:
Before in FlatLaf Dark:
After in FlatLaf Dark:
Highlight items in menu bar on mouse hover:
FlatLaf 0.26 change log:
https://github.com/JFormDesigner/FlatLaf/releases/tag/0.26
> [NETBEANS-3428] Update FlatLaf from 0.25.1 to 0.26

- enterprise/servletjspapi/nbproject/project.properties
- enterprise/web.jspparser/nbproject/project.properties
- enterprise/web.struts/nbproject/project.properties
- enterprise/websvc.restlib/src/org/netbeans/modules/websvc/swdp/swdp.xml
- groovy/gradle/nbproject/project.properties
- groovy/gradle/src/org/netbeans/modules/gradle/GradleDataObject.java
- ide/libs.jaxb/nbproject/project.properties
- ide/libs.jaxb/nbproject/project.xml
- ide/libs.jaxb/src/org/netbeans/libs/jaxb/jaxb.xml
- java/j2ee.eclipselink/external/binaries-list
- java/j2ee.eclipselink/external/eclipselink-2.5.2-license.txt
- java/j2ee.eclipselink/nbproject/project.properties
- java/j2ee.eclipselink/src/org/netbeans/modules/j2ee/eclipselink/eclipselink_lib.xml
- java/j2ee.eclipselink/src/org/netbeans/modules/j2ee/eclipselink/jpa20-persistence.xml
- java/j2ee.persistence/nbproject/project.properties
- java/java.source/src/org/netbeans/modules/java/source/JBrowseModule.java
- java/refactoring.java/src/org/netbeans/modules/refactoring/java/callhierarchy/CallHierarchyTopComponent.form
- java/refactoring.java/src/org/netbeans/modules/refactoring/java/callhierarchy/CallHierarchyTopComponent.java
- java/websvc.jaxws21/src/org/netbeans/modules/websvc/jaxws21/jaxws21.xml
- php/php.project/src/org/netbeans/modules/php/project/api/PhpSourcePath.java
- webcommon/javascript.nodejs/src/org/netbeans/modules/javascript/nodejs/file/NpmDebugLogDataObject.java
- webcommon/javascript.nodejs/src/org/netbeans/modules/javascript/nodejs/file/PackageLockJsonDataObject.java
- webcommon/typescript.editor/src/org/netbeans/modules/typescript/editor/TypeScriptDataObjectDataObject.java
Analysing the startup warnings from netbeans 11.3 revealed some problems:
- we have colliding positions/missing positions in the config file system (mimetype registrations)
- missing code base passing to InstalledFileLocator
- missed updates for library definitions, that don't anymore match the included files
I think this is a candidate for 11.3 as it fixes real problems (broken library definitions) and in general I would expect a release to be as warning free as possible.
@lkishalmi @jlahoda @Chris2011 I'd like you to have a look at this as you worked in the area/authored the code
@ebarboni please see see if you aggree to consider this for 11.3
> Fix startup warnings from netbeans 11.3

- java/java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertTextBlockToString.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertTextBlockToStringTest.java
- java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
Gives a warning for every Text block and provide a fix for converting Text blocks to String.
https://issues.apache.org/jira/browse/NETBEANS-3311
> [NETBEANS-3311] Providing support convert text block to string

- nbbuild/packaging/netbeans-dev_snap/snap/snapcraft.yaml
- nbbuild/packaging/netbeans_snap/snap/snapcraft.yaml
This is a trivial fix affecting Snap packages only. Java 11.0.6 just came out 2 days ago on Ubuntu.
> With Java 11.0.6 AntiAlias fix available on Ubuntu get rid of the suboptimal AA rendering

- groovy/gradle/src/org/netbeans/modules/gradle/ReloadAction.java
Just found this right now. The solution is the same just the action shall be moved to the same package as the NbGradleProjectImpl as it needs to call a package private method to avoid the caching.
> [NETBEANS-3773] Reload Gradle project action shall ignore caching.

- ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java
- ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/CompletionProviderImpl.java
Two small (in size)/big (in effect) fixes for the LSP client - avoid duplicate initialization (while waiting for the server to come up), and prevent NPE in code completion when no trigger characters are specified. These were unfortunate oversights/mistakes.
If there's any chance on putting this into 11.3, that would be absolutely awesome.
> Only initialize the LSP server once; prevent NPE in LSP code completion.

- platform/openide.awt/src/org/openide/awt/HtmlLabelUI.java
See https://issues.apache.org/jira/browse/NETBEANS-3739 for background information about the fix.
Before:
After:
> [NETBEANS-3739] FlatLaf: fix missing versioning colors for modified/ignored files in FlatLaf Dark

- platform/core.windows/src/org/netbeans/core/windows/view/EditorView.java
Now always do an explicit repaint of the editor area to fix issue NETBEANS-3735.
It is maybe pure chance that the effect does not occur in other LAFs because they change the border of the editor area, which does the repaint.
> [NETBEANS-3735] FlatLaf: repaint desktop after closing the last editor tab

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatToolbarDragger.java
Implementation of toolbar grippers (or dragger) following FlatLaf design. The current code does not recognize the LAF and uses a fallback Metal LAF lookalike.
**NOTE:** should support HiDPI but I couldn't test it (no HiDPI devices here). Also not tested on MacOS.
Before:
After:
> FlatLaf toolbar grips

- platform/core.multitabs/src/org/netbeans/core/multitabs/impl/ProjectColorTabDecorator.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
If option "same background color for files from the same project" (Options > Appearance > Document Tabs) is enabled, editor tabs have different background colors, but the text color was always black. This PR changes the text color for FlatLaf Dark to (nearly) white to make it consistent with other text and maybe easier to read. Other LAFs are not affected.
Before (3 files from 3 projects):
After:
The change in `FlatLaf.properties` scales the "underline" height of selected editor tab (in multi-tabs) in Java 8 on HiDPI screens.
Before (Java 8 at 150%):
After:
> [NETBEANS-3428] FlatLaf Dark: fix text color when using project colored tab

- platform/openide.util.ui/src/org/openide/util/CachedHiDPIIcon.java
- platform/openide.util.ui/src/org/openide/util/FilteredIcon.java
- platform/openide.util.ui/src/org/openide/util/ImageUtilities.java
- platform/openide.util.ui/test/unit/src/org/openide/util/ImageUtilitiesTest.java
Fix two problems caused by the recent (HiDPI-related) ImageUtilities revamp ( https://github.com/apache/netbeans/pull/998 and https://github.com/apache/netbeans/pull/1273 ).
* Make the Icon instance returned by ImageUtilities.loadImageIcon properly serializable.
* Make FilteredIcon (used by ImageUtilities.createDisabledIcon) robust against icons with zero or negative dimensions. Add a log message for the negative dimension case (once observed in NETBEANS-3671).
See:
https://issues.apache.org/jira/browse/NETBEANS-3769 (though in this case the HiDPI-related exception turned out not to be the cause of the bug)
https://issues.apache.org/jira/browse/NETBEANS-3671
> [NETBEANS-3671] Fix two ImageUtilities issues

- java/java.source.base/src/org/netbeans/modules/java/source/pretty/ImportAnalysis2.java
This one is a pretty simple fix. When the IDE needs to import a class which is not on the classpath (eg. developing a NetBeans module application and hit the implement abstract methods, when not all the dependencies specified yet).
Tested it with on-the-fly debugging. it works leaving a non resolved import statement behind, which is good.
This issue has been reported at least 1 time against 11.1
> [NETBEANS-3795] Fix auto-importing non-resolvable classes.

- platform/core.windows/src/org/netbeans/core/windows/view/EditorView.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties
This changes the background color of empty editor area (no editor open) for FlatLaf Dark and Light.
Latest screenshots see https://issues.apache.org/jira/browse/NETBEANS-3727?focusedCommentId=17030045&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17030045
Other LAFs are not affected.
Tested with Nimbus, Metal and Window LAFs.
> [NETBEANS-3727] FlatLaf: darker color for empty editor area

- java/refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/FindUsagesVisitor.java
Preventing NPE when the element is null which is lately quite possible. I do not know if that is the right behavior I leave it for our compiler expert, however this one does not do any harm.
> [NETBEANS-3621] Guard agains NPE in Find usages

- platform/o.n.swing.laf.dark/src/org/netbeans/swing/laf/dark/DarkMetalTheme.java
- platform/o.n.swing.laf.dark/src/org/netbeans/swing/laf/dark/DarkNimbusTheme.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/openide.actions/src/org/openide/actions/HeapView.java
This fixes the appearance of the HeapView widget on HiDPI displays. The widget is much simplified, consisting only of a background, an area chart showing the last 100 samples, and text showing the current used heap / total. No bitmaps are used so DPI issues should not be present. Tested on Windows 10/JDK 11 with 125% scaling factor.
NB11.2:
This PR:
The colours and presence/absence of text are configurable as before.
See bug NETBEANS-3785
> [NETBEANS-3785] Implement simplified HeapView widget

- ide/defaults/src/org/netbeans/modules/defaults/BlueTheme-editor.xml
- ide/defaults/src/org/netbeans/modules/defaults/CityLights-editor.xml
- ide/defaults/src/org/netbeans/modules/defaults/NetBeans55-editor.xml
- ide/defaults/src/org/netbeans/modules/defaults/NetBeansEarth-editor.xml
- java/java.editor/src/org/netbeans/modules/java/editor/codegen/RemoveSurroundingCodeAction.java
- java/java.editor/src/org/netbeans/modules/java/editor/resources/Bundle.properties
- java/java.editor/src/org/netbeans/modules/java/editor/resources/fontsColors-highlighting.xml
- java/java.editor/src/org/netbeans/modules/java/editor/resources/layer.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/fontscolors/FlatLafDark-highlights.xml
Exposed remove surrounding code color codes in editor color profile (Highlighting section):
Added color definitions to _NetBeans_, _Norway Today_, _CityLights_, _NetBeans55_, _NetBeans Earth_ and _FlatLaf Dark_ color profiles.
FlatLaf Dark before:
FlatLafDark after:
> [NETBEANS-3792] No more hardcoded colors in Remove Surrounding Code action

- groovy/gradle/src/org/netbeans/modules/gradle/spi/GradleFiles.java
Well this change is pretty harmless, but might help someone. Can be pushed to 11.2 if you decide.
> [NETBEANS-3600] Use gradle-wrapper.properties to detect wrapper

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
Well, this is just an alternative coloring of the HeapView on FlatLaF. Personally I think the yellow draws more attention to the eye than it should be. I also changed the view background color match the toolbar so it is more flat that way. If agreed it is trivial to merge for 11.3.
See the samples:
@DevCharly, @pedro-w  ?
> Heapview FlatLaF alternative colors

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/Bundle.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/fontscolors/FlatLafLight-annotations.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/fontscolors/FlatLafLight-highlights.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/fontscolors/FlatLafLight-tokenColorings.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/layer.xml
Initial attempt at an editor color profile that goes well with FlatLaf Light look and feel.
Still contains no syntax specific token colorings
Annotation colorings are those of default NetBeans color profile.
> FlatLaf Light editor color profile

- java/maven/src/org/netbeans/modules/maven/newproject/ChooseArchetypePanel.form
- java/maven/src/org/netbeans/modules/maven/newproject/ChooseArchetypePanel.java
This fixes the description text area in the second step of the "Project from Maven Archetype" wizard having a light background on dark LAFs.
See bug on Jira for screenshot of problem. After fix:
The hardcoded color remains as a fallback but should be rarely used now.
> [NETBEANS-3873] Fix project from maven archetype wizard

- platform/api.annotations.common/apichanges.xml
- platform/api.annotations.common/arch.xml
- platform/api.annotations.common/src/org/netbeans/api/annotations/common/SuppressWarnings.java
- platform/api.annotations.common/src/org/netbeans/api/annotations/common/package-info.java
Just a couple suggested typo fixes for the API documentation in api.annotations.common.
> Typo fixes in doco for api.annotations.common

- LICENSE
- nbbuild/build.xml
- nbbuild/license-stub.txt
Before this changeset the LICENSE file from the root of the
repository/source directory was used to create the LICENSE file of the
binary build. This worked correctly for the repository because there
only the ALv2 is present, but a source config build in the LICENSE file
also the references to the license files for the embedded source files
with foreign licenses are included.
A binary build from a source config thus contains the license info of
the source config _and_ the binary build. This is not correct, as the
binary config can contains less source only files because they are only
required at build time.
To fix this, a new license-stub.txt is introduced, that only contains
the ALv2 regardless whether it comes from the repository or from a
source config build.
> Ensure a clean license stub is used for source config builds

- nbbuild/build.xml
- nbbuild/license-stub.txt
* Ensure a clean license stub is used for source config builds
Before this changeset the LICENSE file from the root of the
repository/source directory was used to create the LICENSE file of the
binary build. This worked correctly for the repository because there
only the ALv2 is present, but a source config build in the LICENSE file
also the references to the license files for the embedded source files
with foreign licenses are included.
A binary build from a source config thus contains the license info of
the source config _and_ the binary build. This is not correct, as the
binary config can contains less source only files because they are only
required at build time.
To fix this, a new license-stub.txt is introduced, that only contains
the ALv2 regardless whether it comes from the …
> synchronize 11.3 vc2 

- .travis.yml
Travis macOS tests are broken due a issue in macOS build environment: https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/14
> [TRAVIS] Fix for macOS tests

- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/util/Utils.java
+ Added new line to the HTTP head request to the Tomcat so it would 
return successfully (according to HTTP specs)
> [NETBEANS-3903] - Netbeans 11.2 fails to detect startup of Tomcat

- apisupport/apisupport.project/src/org/netbeans/modules/apisupport/project/ui/branding/InternationalizationResourceBundleBrandingPanel.java
- enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/admin/RunnerRestFetchLogData.java
- enterprise/websvc.rest/src/org/netbeans/modules/websvc/rest/support/SourceGroupSupport.java
- ide/editor.deprecated.pre65formatting/src/org/netbeans/editor/ext/ExtFormatter.java
- ide/editor.deprecated.pre65formatting/src/org/netbeans/editor/ext/FormatTokenPositionSupport.java
- ide/editor.fold.nbui/src/org/netbeans/modules/editor/fold/ui/CaretFoldExpanderImpl.java
- ide/spi.debugger.ui/src/org/netbeans/modules/debugger/ui/views/ViewModelListener.java
- ide/target.iterator/nbproject/project.properties
- ide/target.iterator/src/org/netbeans/modules/target/iterator/api/BrowseFolders.java
- ide/xml.catalog.ui/src/org/netbeans/modules/xml/catalog/CatalogMounterModel.java
- java/ant.debugger/src/org/netbeans/modules/ant/debugger/breakpoints/PersistenceManager.java
- java/dbschema/src/org/netbeans/modules/dbschema/DBMemoryCollection.java
- java/dbschema/src/org/netbeans/modules/dbschema/TableElement.java
- java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/DBElementsCollection.java
- java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/SchemaElementImpl.java
- java/java.freeform/src/org/netbeans/modules/java/freeform/JavaProjectGenerator.java
- java/java.hints.ui/src/org/netbeans/modules/java/hints/spiimpl/refactoring/InspectAndRefactorPanel.java
- java/jshell.support/src/org/netbeans/modules/jshell/project/JShellOptions2.java
- java/websvc.saas.codegen.java/src/org/netbeans/modules/websvc/saas/codegen/java/support/SourceGroupSupport.java
- javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/actions/ControllerGenerator.java
- javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/completion/beans/FxBean.java
- platform/core.multitabs/src/org/netbeans/core/multitabs/impl/TabLayoutManager.java
- platform/core.multiview/src/org/netbeans/core/multiview/MultiViewPeer.java
- platform/core.startup/src/org/netbeans/core/startup/layers/SessionManager.java
- profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/model/HeapWalkerNode.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java
This code was previously reverted because it was checked in by accident during the release window..
It's been re-based and tested.
This change cleans up the following warning..
[repeat] /home/bwalker/src/netbeans/webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java:1454: warning: [rawt
ypes] found raw type: ArrayList
[repeat]             private List<VarNode> declaredVars = new ArrayList();
[repeat]                                                      ^
[repeat]   missing type arguments for generic class ArrayList<E>
[repeat]     E extends Object declared in class ArrayList
> [NETBEANS-3807] - cleanup ArrayList rawtype warnings..

- php/php.api.annotation/src/org/netbeans/modules/php/api/annotation/util/AnnotationUtils.java
- php/php.api.annotation/test/unit/src/org/netbeans/modules/php/api/annotation/util/AnnotationUtilsTest.java
- php/php.doctrine2/test/unit/src/org/netbeans/modules/php/doctrine2/annotations/orm/parser/DiscriminatorMapLineParserTest.java
- php/php.doctrine2/test/unit/src/org/netbeans/modules/php/doctrine2/annotations/orm/parser/EntityLineParserTest.java
- php/php.doctrine2/test/unit/src/org/netbeans/modules/php/doctrine2/annotations/orm/parser/ManyToManyLineParserTest.java
- php/php.doctrine2/test/unit/src/org/netbeans/modules/php/doctrine2/annotations/orm/parser/ManyToOneLineParserTest.java
- php/php.doctrine2/test/unit/src/org/netbeans/modules/php/doctrine2/annotations/orm/parser/OneToManyLineParserTest.java
- php/php.doctrine2/test/unit/src/org/netbeans/modules/php/doctrine2/annotations/orm/parser/OneToOneLineParserTest.java
- php/php.doctrine2/test/unit/src/org/netbeans/modules/php/doctrine2/annotations/parser/Doctrine2CommonLineAnnotationLineParserTest.java
See Jira for details: https://issues.apache.org/jira/browse/NETBEANS-3799
There were some unused test methods for the class I've modified (and failing if renamed to be included when running tests), according to git history, they were just added and never actually tested:
https://github.com/emilianbold/netbeans-releases/blame/d5e07b7d6c95bf5342eb8bc351e2d09b88d5e0ad/php.api.annotation/test/unit/src/org/netbeans/modules/php/api/annotation/util/AnnotationUtilsTest.java
I've included these test cases to run and modified the expected values so that they don't fail, specifically not to expect `ManyToOne` type.
> [NETBEANS-3799] Improve extracting types from PHP annotations

- ide/db.core/src/org/netbeans/modules/db/sql/loader/SQLEditorSupport.java
- ide/db.core/src/org/netbeans/modules/db/sql/loader/SQLExecutionLoggerImpl.java
When executing an SQL statement, each time a new exection is started by
the user a new output windows is created. This quickly clutters the
output window pane. Instead of this it would be better to reuse the
existings output window.
> [NETBEANS-3909] SQL Execution should reuse Output Window if possible

- ide/xml.retriever/src/org/netbeans/modules/xml/retriever/catalog/impl/CatalogModelImpl.java
- ide/xml.retriever/test/unit/src/org/netbeans/modules/xml/retriever/catalog/impl/CatalogModelImplTest.java
urn URIs are not correctly decoded by the JDK java.net.URI class.
It is expected that urn:xyz?fetch=true would result in an URI
reporting xyz as path and ?fetch=true as query string, but the
JDK reports null for both parts.
Instead of relying on URI class, acknowledge, that the extraction
of the relevant parts of the query string rely on direct manipulation
of the querystring, so getting the query string can take the same
code path.
> [NETBEANS-2613] Enable fetching schemas for urn schema

- enterprise/j2ee.platform/build.xml
- enterprise/j2ee.platform/external/binaries-list
- enterprise/j2ee.platform/external/generated-javaee-api-8.0.1-javadoc-license.txt
- enterprise/j2ee.platform/external/javaee-api-8.0.1-javadoc-license.txt
- enterprise/j2ee.platform/manifest.mf
- enterprise/j2ee.platform/nbproject/project.properties
- enterprise/javaee8.api/external/binaries-list
- enterprise/javaee8.api/external/javaee-api-8.0.1-license.txt
- enterprise/javaee8.api/external/javaee-web-api-8.0.1-license.txt
- enterprise/javaee8.api/external/javax.annotation-api-1.3.2-license.txt
- enterprise/javaee8.api/external/javax.enterprise.concurrent-api-1.1-license.txt
- enterprise/javaee8.api/external/javax.enterprise.deploy-api-1.7-license.txt
- enterprise/javaee8.api/external/javax.mail-1.6.2-license.txt
- enterprise/javaee8.api/external/javax.management.j2ee-api-1.1.2-license.txt
- enterprise/javaee8.api/external/javax.resource-api-1.7.1-license.txt
- enterprise/javaee8.api/external/javax.security.jacc-api-1.6-license.txt
- enterprise/javaee8.api/external/javax.xml.registry-api-1.0.8-license.txt
- enterprise/javaee8.api/external/javax.xml.rpc-api-1.1.2-license.txt
- enterprise/javaee8.api/manifest.mf
- enterprise/javaee8.api/nbproject/project.properties
- enterprise/javaee8.api/src/org/netbeans/modules/javaee8/api/javaee-api-8.0.xml
- enterprise/javaee8.api/src/org/netbeans/modules/javaee8/api/javaee-web-api-8.0.xml
- enterprise/web.jsf.editor/build.xml
- enterprise/web.jsf.editor/external/binaries-list
- enterprise/web.jsf.editor/external/generated-jsf-api-docs-2.3-license.txt
- enterprise/web.jsf.editor/external/javax.faces-api-2.3-javadoc-license.txt
- enterprise/web.jsf.editor/manifest.mf
- enterprise/web.jsf.editor/nbproject/project.properties
Notes:
- Update JSR-250 Common Annotations for the Java Platform Maintenance Review 3
- Update javaee from 8.0 to 8.0.1
- Update javax.mail from 1.6.0 to 1.6.2
- Update javax.resource-api from 1.7 to 1.7.1
- Update javax.management.j2ee-api from 1.1.1 to 1.1.2
- Update javax.security.jacc-api from 1.5 to 1.6
- Update javax.enterprise.concurrent-api from 1.0 to 1.1
- Update javax.enterprise.deploy-api from 1.6 to 1.7
- Update javax.xml.registry-api from 1.0.7 to 1.0.8
- Update javax.xml.rpc-api from 1.1.1 to 1.1.2
- Update module 'j2ee.platform' (javadoc) from 7.0 to 8.0.1
- Update module 'web.jsf.editor' (javadoc) from 2.0 to 2.3
[JAVA EE 8 Spec](https://github.com/javaee/javaee-spec/blob/master/download/JavaEE8_Platform_Spec_FinalRelease.pdf)
See page 159 for the technologies with their …
> [NETBEANS-3630] - Upgrade javaee8.api binaries

- ide/versioning.util/src/org/netbeans/modules/turbo/Memory.java
- platform/masterfs/src/org/netbeans/modules/masterfs/ProvidedExtensionsProxy.java
- platform/openide.util.lookup/src/org/openide/util/lookup/ProxyLookup.java
- webcommon/javascript2.knockout/src/org/netbeans/modules/javascript2/knockout/index/KnockoutIndexer.java
This removes all the ThreadLocal rawtype warnings..
[repeat] /home/bwalker/src/netbeans/platform/masterfs/src/org/netbeans/modules/masterfs/ProvidedExtensionsProxy.java:44: warning: [rawtypes] found ra
w type: ThreadLocal
[repeat]     private static ThreadLocal  reentrantCheck = new ThreadLocal();
[repeat]                    ^
[repeat]   missing type arguments for generic class ThreadLocal<T>
[repeat]     T extends Object declared in class ThreadLocal
> [NETBEANS-3923] - cleanup ThreadLocal rawtype warnings

- ide/lsp.client/src/org/netbeans/modules/lsp/client/Utils.java
- ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/Formatter.java
I noticed that the typescript editor is lacking formatting. I investigated and
learned, that the LSP protocol in principle supports formatting and the
typescript language server also contains the necessary support.
This changeset hooks the _format_ and _rangeFormat_  functions into the
IDE.
> Hook formating/rangeFormating into LSP Client

- java/maven/nbproject/project.xml
- java/maven/src/org/netbeans/modules/maven/newproject/BasicPanelVisual.java
- platform/openide.loaders/apichanges.xml
- platform/openide.loaders/manifest.mf
- platform/openide.loaders/nbproject/project.properties
- platform/openide.loaders/src/org/openide/loaders/TemplateWizard.java
- platform/openide.loaders/test/unit/src/org/openide/loaders/TemplateWizardTest.java
Without this change, there is some directory creation in BasicPanelVisual.store, but that method is called in several situations where directory/DataFolder creation should not occur. This PR moves the creation code to TemplateWizard.getTargetFolder(), which defers the creation until needed. Unfortunately, with a breakpoint, I have not seen getTargetFolder() invoked when creating a maven project.
This PR is designed to preserve semantic; it is highly targeted and relatively simple. There may be better/simpler/more-direct fixes; but I am unfamiliar with the overall architecture; revset which introduced the spurious directory creation:
```
changeset:   301468:76d9cafcee35
branch:      ArchetypesUI268677
parent:      299970:0c5aa5cdb86a
user:        Jaroslav Tulach <jtulach@netbeans.org> …
```
> [NETBEANS-3918] defer creation of target folder until/if needed

- ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/Formatter.java
- ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/LspMimeDataProvider.java
It was observed that XML formatting did not work after enabling LSP
formatting. The problem was caused by the MimeLookup for application/xml
that returned two ReformatTask.Factory implementations. One was the
right factory, the other the Formatter provided by the LSP Client
module.
Instead of registering the ReformatTask.Factory of the LSP client module
on the empty mime path, it is now dynamically registered by a
MimeDataProvider (LspMimeDataProvider). That MimeDataProvider ensures
that the lsp based formatter is only registered if a
LanguageServerProvider is present on the targetted mime path.
As an implementation note the LspMimeDataProvider is registered with a
position, which ensures, that it is registered with higher priority than
LegacyFormattersProvider which unconditionally …
> Only register LSP based formatting if MimePath has language server

- .travis.yml
Change Travis config to run tests for the PHP modules that are working currently
> [TRAVIS] Run tests for PHP modules

- java/debugger.jpda.visual/src/org/netbeans/modules/debugger/jpda/visual/VisualDebuggerListener.java
Older versions of JavaFX required the debugger to set the flag com.sun.javafx.runtime.SystemProperties.isDebug. Openjfx does not have this flag. When debugging openjfx there is an NPE when trying to set the flag. This PR avoid the NPE by just returning if there is not an isDebug flag.
> [NETBEANS-2559] Avoid NPE when openjfx

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java
- nbbuild/build.xml
little file generation to get all binaries-list in one file.
May save lots of time (15 per build) for Maven artefacts generation
related to: https://github.com/apache/netbeans-mavenutils-nb-repository-plugin/pull/2
> Get a file of all libraries during download

- apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardIterator.java
Query the maven repository to get the latest version of  nbm-archetype and netbeans-platform-app-archetype. If this fails for some reason it will use the hard coded version.
- nbm-archetype: 1.18 apache/netbeans-mavenutils-archetype-nbm-archetype#1
- netbeans-platform-app-archetype:  1.23 /apache/netbeans-mavenutils-archetype-netbeans-platform-app-archetype#2
> [NETBEANSINFRA-6] get latest archetype from maven repo

- java/maven/src/org/netbeans/modules/maven/newproject/BasicPanelVisual.java
NOTE: this PR only addresses the problem caused by the first changeset listed. I'm filing a 2nd issue for the spurious directory creation which is the 2nd changeset. But I'm including it here for reference/completeness since it is in the issue report.
NETBEANS-2446 problem comes from two commits (seen in main-silver)
```
changeset:   244321:021157efa98e
parent:      244318:5036dc46020f
user:        Milos Kleint <mkleint@netbeans.org>
date:        Thu Jan 24 15:12:37 2013 +0100
summary:     #217087 new wizard able to pick up the parent directory from Action's properties as initial value
```
and
```
changeset:   301468:76d9cafcee35
branch:      ArchetypesUI268677
parent:      299970:0c5aa5cdb86a
user:        Jaroslav Tulach <jtulach@netbeans.org>
date:        Tue Oct 25 21:52:49 2016 +0200 …
```
> [NETBEANS-2446] Use *parent* of saved projectFolder as projectLocation

- java/maven/test/unit/src/org/netbeans/modules/maven/ActionProviderImplTest.java
- platform/junitlib/external/binaries-list
- platform/junitlib/external/junit-jupiter-api-5.6.0-license.txt
- platform/junitlib/external/junit-jupiter-engine-5.6.0-license.txt
- platform/junitlib/external/junit-jupiter-params-5.6.0-license.txt
- platform/junitlib/nbproject/project.properties
- platform/junitlib/src/org/netbeans/modules/junitlib/Bundle.properties
- platform/junitlib/src/org/netbeans/modules/junitlib/junit_5.xml
- platform/libs.junit5/external/binaries-list
- platform/libs.junit5/external/junit-jupiter-5.6.0-license.txt
- platform/libs.junit5/nbproject/project.properties
- platform/libs.junit5/nbproject/project.xml
Notes:
- Improved reporting for failures during test discovery/execution
- Modular Javadoc
- OSGi metadata is now published in all binary JARs
- Gradle Module Metadata is now published for all artifacts
- Performance improvements and bug fixes for the Vintage engine
- Minor bug fixes and improvements
[JUnit Web Page](https://junit.org)
[Release Notes](https://junit.org/junit5/docs/5.6.0/release-notes/)
> [NETBEANS-3915] - Update JUnit from 5.5.2 to 5.6.0

- java/java.hints.declarative/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintLexer.java
- java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/DeclarativeHintLexerTest.java
- java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/use-member-ref.hint
- java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/use-member-ref.test
- java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/use-undeclared-lambda.hint
- java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/use-undeclared-lambda.test
- java/java.source.base/apichanges.xml
- java/java.source.base/nbproject/project.properties
- java/java.source.base/src/org/netbeans/api/java/source/CodeStyle.java
- java/java.source.base/src/org/netbeans/modules/java/source/pretty/VeryPretty.java
- java/java.source.base/src/org/netbeans/modules/java/ui/FmtOptions.java
- java/java.source.base/test/unit/src/org/netbeans/api/java/source/gen/LambdaTest.java
- java/java.source/src/org/netbeans/modules/java/ui/Bundle.properties
- java/java.source/src/org/netbeans/modules/java/ui/FmtBraces.form
- java/java.source/src/org/netbeans/modules/java/ui/FmtBraces.java
- java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Hacks.java
- java/spi.java.hints/src/org/netbeans/spi/java/hints/JavaFixUtilities.java
- java/spi.java.hints/test/unit/src/org/netbeans/spi/java/hints/JavaFixUtilitiesTest.java
Fixing three problems related to the declarative Java hints:
-the declarative hints use :: as a separator between snippets and conditions - but :: is also used in meber references. So this patch is trying to disambiguate the two uses.
-implicit lambdas in the target snippets get erroneously explicit parameter handling (i.e. get types for the parameter names, often even wrong like "(ERROR)")
-for implicit lambdas with a single parameters, the parameter is still wrapped with parentheses
--added a configuration option for this; and this may be the most doubtful thing in the patch
> Fix member references in Jackpot scripts

- enterprise/spring.webmvc/licenseinfo.xml
- enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/SpringConfigPanelVisual.java
- enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/SpringWebModuleExtender.java
- enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/WebProjectSpringConfigFileProvider.java
- enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/resources/layer.xml
- enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/resources/templates/applicationContext3.template
- enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/resources/templates/applicationContext4.template
- enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/resources/templates/dispatcher-servlet3.template
- enterprise/spring.webmvc/src/org/netbeans/modules/spring/webmvc/resources/templates/dispatcher-servlet4.template
Fixes issue related with introduction off SpringFramework 5: [NETBEANS-3558](https://issues.apache.org/jira/browse/NETBEANS-3558?focusedCommentId=17029730&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17029730)
- Remove `org.springframework.web.servlet.mvc.support.ControllerClassNameHandlerMapping` bean definition in `dispatcher-servlet.xml` for Spring 4 and Spring 5.
- Update XML Schema Definitions for the `dispatcher-servlet.xml` and `applicationContext.xml` templates to last version.
- Fix some warnings.
> [NETBEANS-3558] Fix SpringFramework dispatcher servlet template

- java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/DBElementsCollection.java
- java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/IndexElementImpl.java
- java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/KeyElementImpl.java
- java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/SchemaElementImpl.java
- java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/TableElementImpl.java
I came across this issue in Netbeans with the DBElementsCollection class.
Basically the hascode is being returned as a String but the code removes checking for type by treating the hashcode as an object.
This change keeps it as a String and removes the folloiwng warning..
[repeat] /home/bwalker/src/netbeans/java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/DBElementsCollection.java:41: warning: [rawtypes] found raw type: HashSet
[repeat] protected static transient HashSet instances = new HashSet();
[repeat] ^
[repeat] missing type arguments for generic class HashSet<E>
[repeat] where E is a type-variable:
[repeat] E extends Object declared in class HashSet
> [NETBEANS-3806] - cleanup hashcode in DBElementsCollection

- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/popupswitcher/SwitcherTable.java
https://issues.apache.org/jira/browse/NETBEANS-3957
tested with FlatLaf light/dark, Windows, Nimbus and Metal LaFs
> [NETBEANS-3957] fixed "opened documents list" show HTML code instead of rich text

- java/maven.embedder/build.xml
- java/maven.embedder/external/binariesembedded-list
- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/CheckEmbeddedBinaries.java
- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/DownloadBinaries.java
- nbbuild/build.xml
Hi @JaroslavTulach @matthiasblaesing 
I created another task **getallmavencoordinates** instead of using hack in **download-all-extbins**
// 
I also added a checked and added binariesembedded-list in java.maven.embedder to get a sha1 whitelist of maven coordinate for the jars we populate. (In order to get less external in maven artefacts)
Associated is a task to check in java.maven.embedd/build.xml. Not intended to be run in the build, just on update of a new Maven. 
Maybe others modules populate jar in this manner but this is a test in a area I know.
> NETBEANSINFRA-12 get better list for mavencoordinates

- ide/gsf.testrunner.ui/src/org/netbeans/modules/gsf/testrunner/ui/CommonTestsCfgOfCreate.java
- ide/gsf.testrunner/manifest.mf
- ide/gsf.testrunner/nbproject/org-netbeans-modules-gsf-testrunner.sig
- ide/gsf.testrunner/src/org/netbeans/modules/gsf/testrunner/TestCreatorProviderProcessor.java
- ide/gsf.testrunner/src/org/netbeans/modules/gsf/testrunner/api/TestCreatorProvider.java
- java/java.testrunner.ui/src/org/netbeans/modules/java/testrunner/ui/JavaTestCreatorConfiguration.java
- java/junit.ui/nbproject/project.xml
- java/junit.ui/src/org/netbeans/modules/junit/ui/AbstractJUnitTestCreatorProvider.java
- java/junit.ui/src/org/netbeans/modules/junit/ui/JUnit4TestCreatorProvider.java
- java/junit.ui/src/org/netbeans/modules/junit/ui/JUnitTestCreatorProvider.java
- java/junit/manifest.mf
- java/junit/src/org/netbeans/modules/junit/AbstractTestGenerator.java
- java/junit/src/org/netbeans/modules/junit/DefaultPlugin.java
- java/junit/src/org/netbeans/modules/junit/JUnit3TestGenerator.java
- java/junit/src/org/netbeans/modules/junit/JUnit4TestGenerator.java
- java/junit/src/org/netbeans/modules/junit/JUnit5TestGenerator.java
- java/junit/src/org/netbeans/modules/junit/TestCreator.java
- java/junit/src/org/netbeans/modules/junit/api/JUnitSettings.java
- java/junit/src/org/netbeans/modules/junit/api/JUnitTestUtil.java
- java/junit/src/org/netbeans/modules/junit/api/JUnitUtils.java
- java/junit/src/org/netbeans/modules/junit/api/JUnitVersion.java
- java/testng.ui/src/org/netbeans/modules/testng/ui/actions/TestNGTestCreatorProvider.java
JUnit5 and JUnit4 have little in common. In fact they are almost completely different frameworks. I am annoyed by the IDE pushing me to use JUnit5. Most of my projects use JUnit4 and I am happy with it. I want to continue to use JUnit4 coding style in my new projects as well.
This PR adds new testing framework JUnit4 (in addition to existing generic JUnit) and allows users that care select JUnit4 explicitly when generating tests for a class.
> Allow explicit selection of JUnit4 test generator 

- java/api.maven/src/org/netbeans/api/maven/archetype/ArchetypeWizards.java
- java/maven/manifest.mf
- java/maven/src/org/netbeans/modules/maven/api/archetype/ArchetypeWizards.java
- java/maven/src/org/netbeans/modules/maven/newproject/BasicPanelVisual.form
- java/maven/src/org/netbeans/modules/maven/newproject/BasicPanelVisual.java
- java/maven/src/org/netbeans/modules/maven/newproject/BasicWizardPanel.java
- java/maven/src/org/netbeans/modules/maven/newproject/MavenWizardIterator.java
- java/maven/src/org/netbeans/modules/maven/newproject/idenative/IDENativeMavenWizardIterator.java
This PR detects NetBeans running on JDK8 and uses "javafx-version=1.8" in such situation. Once the project is created, it is going to be full of bugs shown in editor. There is `module-info.java` in the project and it confuses the Java parser. A PR for this is forthcoming.
> Default JavaFX archetypes to javafx 1.8 when running on jdk1.8

- platform/openide.awt/src/org/openide/awt/HtmlRenderer.java
- platform/openide.awt/src/org/openide/awt/HtmlRendererImpl.java
This patch fixes a bug where some file names in the "Projects" and "Files" tabs would appear truncated on fractional HiDPI scalings (e.g. 150%) on Windows. It probably also improves text measurement on an integral 200% scaling as well, possibly on MacOS as well.
The problem was in org.openide.awt.HtmlRenderer and the associated HtmlRendererImpl class, which creates a fake Graphics2D object for the purposes of calculating text dimensions in getPreferredWidth. This Graphics2D object was not properly prepared with a HiDPI transform for its FontRenderContext, leading to inaccurate text measurement. Moreover, the GraphicsConfiguration was not retrieved for the correct monitor (in multi-monitor setups). These problems have been fixed.
Since the scratch Graphics2D object is now specific to each …
> [NETBEANS-2543] File names clipped in Files and Projects tabs

- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/DocumentViewOp.java
- ide/spi.debugger.ui/src/org/netbeans/modules/debugger/ui/views/debugging/DebuggingViewComponent.java
- platform/core.output2/src/org/netbeans/core/output2/ui/AbstractOutputPane.java
This fixes smooth scrolling in **editors**,  **Output** view and **Debugging** view for FlatLaf and Windows LaF.
Smooth scrolling requires a "precise" trackpad our mouse wheel (e.g. Macs or Surface Books) and allows scrolling by fraction of lines.
Smooth scrolling worked before fine in many views where FlatLaf or Windows LaF does the scrolling. But there are some places in NB where scrolling is done in NB, but precise rotation values are not used.
The problem is that `MouseWheelEvent.getWheelRotation()` or `MouseWheelEvent.getUnitsToScroll()` return zero when a precise trackpad/wheel is moved slowly. So the events are ignored.
Solution is to use `MouseWheelEvent.getPreciseWheelRotation()` instead.
On not precise wheels, `getPreciseWheelRotation()` returns the same value as …
> [NETBEANS-3870] FlatLaf and Windows LaF: fix smooth scrolling

- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-0.29-license.txt
- platform/libs.flatlaf/external/flatlaf-0.30-license.txt
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
FlatLaf 0.29 change log:
https://github.com/JFormDesigner/FlatLaf/releases/tag/0.29
FlatLaf 0.30 change log:
https://github.com/JFormDesigner/FlatLaf/releases/tag/0.30
This version fixes to NetBeans related bugs:
1) not all Unicode characters were rendered on Windows. See https://issues.apache.org/jira/browse/NETBEANS-4135
2) too large font on some Linux systems. Reported here: https://github.com/JFormDesigner/FlatLaf/issues/69
3) repainting of wide selection in trees on focus lost/gain did not repaint the whole line
Before:
After:
> [NETBEANS-3428] Update FlatLaf from 0.28 to 0.30

- java/java.j2semodule/src/org/netbeans/modules/java/j2semodule/ui/customizer/PathsCustomizer.form
- java/java.j2semodule/src/org/netbeans/modules/java/j2semodule/ui/customizer/PathsCustomizer.java
- java/java.j2seproject/src/org/netbeans/modules/java/j2seproject/ui/customizer/PathsCustomizer.form
- java/java.j2seproject/src/org/netbeans/modules/java/j2seproject/ui/customizer/PathsCustomizer.java
fix for https://issues.apache.org/jira/browse/NETBEANS-4030
The two nested JTree's ("Modulepath" and "Classpath") now span the whole width, which looks better for FlatLaf and Nimbus wide selection. Also the white background in Nimbus looks better than before.
Also tested with Windows, Mac and Metal LaFs, which are unchanged.
After:
Nimbus after:
Nimbus before:
> [NETBEANS-4030] FlatLaf and Nimbus: fixed selection not painted in libraries category in project dialog

- ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlLexer.java
- ide/languages.yaml/test/unit/data/testfiles/issue_NETBEANS-4167.yaml.txt
- ide/languages.yaml/test/unit/data/testfiles/issue_NETBEANS-4167.yaml.txt.tokens.txt
- ide/languages.yaml/test/unit/src/org/netbeans/modules/languages/yaml/YamlLexerTest.java
Well, this one is a trivial fix with a test case. I moves the static integers to an enum, as it was easier to debug the state machine. Though left the State object to be Integer, so no test data had to be altered.
> [NETBEANS-4167] Fix null token on { in yaml files

- java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
Updated maven embedder and indexer changed jar structure and in turn
the setup of the classrealm needs to be updated to match.
> [NETBEANS-4071] Fix plexus class setup for maven embedder

- ergonomics/ide.ergonomics/java.properties
- ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/ConfigurationPanel.java
- ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/ModulesInstaller.java
When creating new project with IDE running on JDK11, don't attempt to install nb-javac. I did following testing:
```bash
netbeans$ ant build
netbeans$ rm -rf nbuild/testuserdir nbbuild/netbeans/extra
netbeans$ ant tryme -Dnbjdk.home=/jdk8
netbeans$ rm -rf nbuild/testuserdir nbbuild/netbeans/extra
netbeans$ ant tryme -Dnbjdk.home=/jdk11
```
Only download of nb-javac is offered on OracleJDK8. Only download of OpenJFX is offered on JDK-11.
> [NETBEANS-4078] Don't install nb-javac on JDK11

- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-0.31-license.txt
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
There is only one change in FlatLaf 0.31 (compared to 0.30), which makes updating uncomplicated.
It changes "has focus" checking in FlatLaf and fixes https://issues.apache.org/jira/browse/NETBEANS-4173
In FlatLaf 0.30 the "current focus owner" was used to paint focused borders and blue list/table/tree selection. But "current focus owner" temporary changes when opening a popup menu or main menu.
Since FlatLaf 0.31 the "permanent focus owner" is used and the focused border stays where it is.
Now FlatLaf focus indication behaves the same as in Windows, macOS, GNOME and KDE.
This PR supersedes PR #2079.
FlatLaf 0.31 change log:
https://github.com/JFormDesigner/FlatLaf/releases/tag/0.31
> [NETBEANS-4173] Update FlatLaf from 0.30 to 0.31

- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/FontInfo.java
Fix a problem that caused the end-of-line marker (e.g. at 80 chars) to be displayed at an incorrect position (e.g. at 82 chars) on certain zoom levels, on Java 9 or above. This problem stems from rounding error caused by assuming that the width of each (monotype font) character is an integral number of logical pixels wide. The latter is not the case on HiDPI screens (e.g. where 10 device pixels may map to 6.67 logical pixels at 150% scaling), nor on Windows with subpixel antialiasing, and probably some other situations as well.
This also fixes less prominent problems with visual alignment of tabs vs. spaces (e.g. 8-space tabs will get the wrong width due to the same rounding error).
While looking at the related code, I discovered various other places where the same kind of rounding error …
> [NETBEANS-346] Tabs, characters, and the right Margin don't line up

- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/DebugManagerHandler.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/LanguageName.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleAccess.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/access/TruffleStrataProvider.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/ast/TruffleNode.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/ast/model/ASTNodeModel.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/ast/model/ASTTreeExpansionModel.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/breakpoints/TruffleBreakpointsHandler.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/TruffleStackFrame.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/models/DebuggingTruffleActionsProvider.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/frames/models/DebuggingTruffleTreeModel.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/source/SourcePosition.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/TruffleStackVariable.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/TruffleVariable.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/TruffleVariableImpl.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/models/TruffleVariablesActionsProviderFilter.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/models/TruffleVariablesTableModel.java
- java/debugger.jpda.truffle/src/org/netbeans/modules/debugger/jpda/truffle/vars/models/TruffleVariablesTreeModel.java
- java/debugger.jpda.truffle/test/unit/src/org/netbeans/modules/debugger/jpda/truffle/DebugSLTest.java
- java/debugger.jpda.truffle/test/unit/src/org/netbeans/modules/debugger/jpda/truffle/testapps/SLApp.java
- java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/FrameInfo.java
- java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/GuestObject.java
- java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/JPDATruffleAccessor.java
- java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/JPDATruffleDebugManager.java
- java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/SourcePosition.java
- java/debugger.jpda.truffle/truffle-backend/org/netbeans/modules/debugger/jpda/backend/truffle/TruffleAST.java
* Resolved issues NETBEANS-4208 and NETBEANS-4209,
* several more fixes and corrections,
* receiver object is displayed (this),
* [lang-name] is added to types of foreign objects for better usability,
* when "Language Developer Mode" option is on debugger steps into internal sources
* corrected tags in "Truffle AST view" (displayed in dev mode only).
> NETBEANS-4209: Update Truffle debugging for GraalVM 20.1.0

- java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/breakpoints/LineBreakpointImpl.java
- java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/ExpressionLambdaBreakpointTest.java
- java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/ExpressionStepTest.java
- java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/testapps/ExpressionLambdaBreakpointApp.java
- java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/testapps/ExpressionStepApp.java
https://issues.apache.org/jira/browse/NETBEANS-3580
> NETBEANS-3580] : Fixed Debug Expression Lambda 

- ide/csl.api/src/org/netbeans/modules/csl/editor/completion/GsfCompletionItem.java
Colors used for code completion are taken from Java.
New colors are readable when dark theme is used.
Also fixes issue NETBEANS-3706
> [NETBEANS-3707] Fixed colors used for PHP code completion

- groovy/gradle.java/src/org/netbeans/modules/gradle/java/api/GradleJavaSourceSet.java
- groovy/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleCompilerOptionsQuery.java
Trivial and safe fix for an NPE that prevents code assistance in JSP files.
> [NETBEANS-4239] Fixed NPE in GradleCompilerOptionsQuery

- .travis.yml
- nbbuild/templates/common.xml
- platform/netbinox/nbproject/project.properties
Netbeans build system has a project property to define a list of classes/packages to be excluded when run tests in a module. 
```java
test.config.stableBTD.includes=**/*Test.class
test.config.stableBTD.excludes=\
**/CachingAndExternalPathsTest.class,\
**/CachingAndExternalURLTest.class,\
**/CachingPreventsFileTouchesTest.class,\
**/LogReaderServiceTest.class,\
**/NetigsoHasSAXParserTest.class
```
This PR removes the hardcoded value from the property to allow us to exclude tests again.
> Fix ant property to exclude tests

- java/javadoc/nbproject/project.xml
- java/javadoc/src/org/netbeans/modules/javadoc/search/IndexBuilder.java
- java/javadoc/test/unit/src/org/netbeans/modules/javadoc/search/IndexBuilderTest.java
This is my first contribution and is trivial.
Javadoc title is being unescaped after parsing.
Before fix - 
After fix -
> NETBEANS-4176-Unescape javadoc title after parsing

- platform/core.multitabs/src/org/netbeans/core/multitabs/impl/ProjectColorTabDecorator.java
Fix for https://issues.apache.org/jira/browse/NETBEANS-3787
When project tab colors are enabled in Options dialog (Appearance > Document tabs), then it is painted over the blue "underline" that FlatLaf uses for active tabs. To avoid this I've moved the project color bar to the top of the tab.
Before:
After:
Other LaFs are not affected. E.g Windows:
> [NETBEANS-3787] FlatLaf: fixed active tab painting if project tab colors enabled

- webcommon/javascript.nodejs/samples_src/MessagesAngular/package.json
- webcommon/javascript.nodejs/samples_src/MessagesExpress/package.json
- webcommon/javascript.nodejs/samples_src/MessagesKnockout/package.json
There are a few known security breaches in the sample source..
Specifically the following alerts:
CVE-2019-5484
Bower before 1.8.8 has a path traversal vulnerability permitting file write in arbitrary locations via install command, which allows attackers to write arbitrary files when a malicious package is extracted.
CVE-2019-5413
An attacker can use the format parameter to inject arbitrary commands in the npm package morgan < 1.9.1.
CVE-2017-16137
The debug module is vulnerable to regular expression denial of service when untrusted user input is passed into the o formatter. It takes around 50k characters to block for 2 seconds making this a low severity issue.
I'm not saying these are critical. But, it's better we fix them to prevent any possibility of using Netbeans IDE to allow someone …
> [NETBEANS-4280] - cleanup potential security breaches

- java/java.source.base/src/org/netbeans/modules/java/source/parsing/CachingFileManager.java
- java/java.source.base/src/org/netbeans/modules/java/source/parsing/ModuleFileManager.java
If a multi-release JAR contains resources with the same name but a different extension, then only one of these resources is picked up.  This causes errors with projects using eg. FlatLaf where errors are seen in the code editor while compilation works fine.  Files such as `FlatLightLaf.properties` shadows `FlatLightLaf.class`.
This is caused by an error in CachingFileManager and ModuleFileManager using the file name and location without extension as a map key to look up multi-release files. Hopefully changes here fix this without causing problems elsewhere - better tests would be good in this area in future.
See also https://github.com/JFormDesigner/FlatLaf/issues/13
The projects attached to the JIRA issue demonstrate the issue on classpath and modulepath. Both show broken in NB …
> [NETBEANS-4291] Fix some classes not found from multi-release JARs in Java editor

- java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/save/FormatingTest.java
I have undone the change from NETBEANS-3204 and moved it to another visitor, mostly impacting switch case formatting now. All the original tests are green and I added a new test that cover this scenario.
> [NETBEANS-3973] Fixed double space before lambda arrow

- nb/updatecenters/build.xml
- nb/updatecenters/src/org/netbeans/modules/updatecenters/resources/mf-layer.xml
Mark included 3rd-party update centre as trusted and don't sign bundled nbms. This should fix the issue with the signature of the bundled nbms not matching the keystore in the updatecenter nbm - a problem for anyone using the distribution nbms, and for pushing updates to nb-javac or JavaFX to the IDE after release.
Deliberately kept light touch for 12.0.  We can probably drop all the `ide.ks` and `NetBeansKeyStoreProvider` stuff for 12.1?
> Mark included 3rd-party update centre as trusted.

- java/java.hints/src/org/netbeans/modules/java/hints/jdk/ConvertToPatternInstanceOf.java
- java/spi.java.hints/src/org/netbeans/modules/java/hints/providers/spi/HintMetadata.java
Add minSourceVersion = 14 to ConvertToPatternInstanceOf hint.
Disable hint in HintMetadata if lookup of SourceVersion by name fails.
The change to HintMetadata handles the problem with hints requiring a higher minimum version of SourceVersion than exists on the running machine. With move away from nb-javac, hints should perhaps use an integer value rather than SourceVersion here in the longer term?
> [NETBEANS-4281] Fix ConvertToPatternInstanceOf hint always showing.

- platform/core.output2/src/org/netbeans/core/output2/NbIOProvider.java
The new `I/O API and SPI`, introduced around 2014, has never had a working "reset()" to clear the output window, AFAICT. 
It looks like this new interface delegates to platform/core.output2 and this in turn is based on the old stuff in platform/openide.windows. The new interface gave us the long promised InputOutput.reset() and hid the older OutputWriter.reset(). The older OutputWriter.reset has some essential code that the newer InputOutput.reset() never invokes.
This PR makes sure there's a full reset and the output window is cleared when using the default api implementation.
Testing is tricky. The tests for the new stuff test that delegation occurs. It never actually tests a real output window. Based on the tests for the old api I've put together some tests as a module that uses …
> [NETBEANS-4203] for InputOutput.reset() do NbWriter.reset() as needed

- java/java.source.base/src/org/netbeans/modules/java/source/save/CasualDiff.java
Fixes 12.0 regression from 11.3. (might be nb-javac to jdk14 issue)
This fixes "Use @NbBundle.messages" adding a message to
``` 
@Messages("OptionsCategory_Name_OptionsPlayHack=any old")
```
and also adding a message to
```
@Messages({"OptionsCategory_Name_OptionsPlayHack=any old", "OptionsCategory_Keywords_OptionsPlayHack=keyw1"})
```
Not sure it's the best fix, it seems safe; needs review.
Questions about the fix:
- I don't understand getKind() vs instanceof (if/when it matters)
- Not sure if this check fully qualifies "assignment as annotation", but don't think that matters.
> [NETBEANS-4299] find endPos for synthetic annotation attribute

- java/form/src/org/netbeans/modules/form/editors/KeyStrokeEditor.java
Changed usages of 
InputEvent.ALT_MASK, SHIFT_MASK, CTRL_MASK and META_MASK with
InputEvent.ALT_DOWN_MASK, SHIFT_DOWN_MASK, CTRL_DOWN_MASK and META_DOWN_MASK
to avoid deprecation errors in generated code.
> NETBEANS-4192 The Gui builder uses deprecated InputEvent *_MASK constant

- java/java.j2seplatform/manifest.mf
- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
[JDK 14 Web Page](https://jdk.java.net/14/)
[API Javadoc](https://docs.oracle.com/en/java/javase/14/docs/api/index.html)
> [NETBEANS-4038] - Add javadoc for JDK 14 General-Availability Release

- java/maven/src/org/netbeans/modules/maven/ActionProviderImpl.java
Small improvement to 073c42c1cd: the IDE properly tests for JUnit5 in `runSingleMethodEnabled`, so it triggers a suggest/status line message if the project is not properly set up. But the display message and POM fix installs JUnit4+older surefire, which does not work in JUnit5 environment.
I've just improved the messages for JUnit5 case + used proper Surefire version.
> [NETBEANS-3733] Suggest surefire 2.22.0 for JUnit5 tests.

- ide/editor.fold.nbui/src/org/netbeans/modules/editor/fold/ui/FoldViewFactory.java
- ide/editor.lib2/src/org/netbeans/api/editor/caret/EditorCaret.java
(sorry, hit ENTER prematurely)
This tries to fix [NETBEANS-2082](https://issues.apache.org/jira/browse/NETBEANS-2082), and older [Bugzilla-270972](https://bz.apache.org/netbeans/show_bug.cgi?id=270972) while retaining fix for [Bugzilla-270172](https://bz.apache.org/netbeans/show_bug.cgi?id=270172).
The original fix attempted to provide hint to the Editor infrastructure, to **save caret position** when the fold was collapsed, so it could scroll back the caret into the view, when the caret went off the screen as a result of the view hierarchy redraw.
But there were two issues: 
-  the instruction to `forceUpdate` was sent on **every** fold change, not just the initial one (e.g. on fold expand, too).  This is fixed in `FoldViewFactory.java`.
- And even though it was meant as an instruction …
> NETBEANS-2082: do not scroll to caret after fold collapse, if caret is s off-screen.

- platform/applemenu/src/org/netbeans/modules/applemenu/layer.xml
When Netbeans projects is running in macOS using `ant tryme` command, this `WARN` message is logged: `WARNING [org.openide.filesystems.Ordering]: Found same position 700 for both Toolbars/Git and Toolbars/QuickSearch`
Git Toolbar has the same position than QuickSearch toolbar.
> Fix macOS QuickSearch toolbar position

- ide/o.eclipse.jgit/external/binaries-list
- ide/o.eclipse.jgit/external/org.eclipse.jgit-5.5.1.201910021850-r-license.txt
- ide/o.eclipse.jgit/nbproject/project.properties
- ide/o.eclipse.jgit/nbproject/project.xml
Currently v5.5.0
The jgit project has recently released v5.7.0 but this has some API changes and AFAICS no compelling reason to upgrade.
> [NETBEANS-4005] Update jgit to v5.5.1

- ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/ConfigurationPanel.java
- ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/FindComponentModules.java
- ergonomics/ide.ergonomics/src/org/netbeans/modules/ide/ergonomics/fod/FoDUpdateUnitProvider.java
This is a bare minimum fix to ensure that the user can opt out of nb-javac and JavaFX installation when enabling Java support via Open Project or import settings. This is particularly bad in import settings as it causes a continuous cascade of dialogs on first run. See mention in https://issues.apache.org/jira/browse/NETBEANS-3810
Merging this would (partially?) break the fix for https://issues.apache.org/jira/browse/NETBEANS-2439 in #1612 IMO that triggered what should have been a blocker for 11.3 though.
> [NETBEANS-4328] Make sure JavaFX is recommended but not required on JDK 11+.

- apisupport/apisupport.wizards/src/org/netbeans/modules/apisupport/project/ui/wizard/action/DataModel.java
- apisupport/apisupport.wizards/test/unit/src/org/netbeans/modules/apisupport/project/ui/wizard/action/DataModelTest.java
The new freemarker seems to be do a serialize/unserialize phase when processing parameters map. The original implementation put a non serializable inner class wrapped into a proxy eventually caused that a collection contained a proxy class which referenced a null object.
This solution is simply replace that kind of "smart" way to pass Java annotation value object around by creating an actual serializable model class instead.
> [NETBEANS-4365] Fix NetBeans New Action Wizard.

- java/maven/manifest.mf
- java/maven/src/org/netbeans/modules/maven/MavenCacheDisabler.java
With the cache enabled updates to the pom or the dependencies are not
picked up correctly.
Diagnosis and work-around was provided by Christian Oyarzun.
Closes: #2176
> [NETBEANS-4341] Disable maven global cache

- php/php.editor/src/org/netbeans/modules/php/editor/completion/DocRenderer.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/DocRendererTest.java
https://issues.apache.org/jira/browse/NETBEANS-3413
Uses description of inherited element when no PHPDoc is present.
> [NETBEANS-3413] Implicit inheritance of PHPDoc descriptions

- php/php.project/src/org/netbeans/modules/php/project/ui/actions/tests/GoToTest.java
- php/php.project/src/org/netbeans/modules/php/project/ui/actions/tests/SelectFilePanel.form
- php/php.project/src/org/netbeans/modules/php/project/ui/actions/tests/SelectFilePanel.java
Fixes resizing of test file selection when navigating to test file.
Files are sorted by path.
Before:
After:
> [NETBEANS-4368] Fix test file navigation dialog

- php/php.code.analysis/src/org/netbeans/modules/php/analysis/MessDetectorAnalyzerImpl.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/MessDetectorParams.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/MessDetector.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptions.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptionsValidator.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/ValidatorMessDetectorParameter.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/MessDetectorRuleSetsListCellRenderer.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/Bundle.properties
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/MessDetectorCustomizerPanel.form
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/analyzer/MessDetectorCustomizerPanel.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/Bundle.properties
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/MessDetectorOptionsPanel.form
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/MessDetectorOptionsPanel.java
Add option to select custom rule set file in PHP Mess Detector configuration.
Customizer panel is also updated.
https://issues.apache.org/jira/browse/NETBEANS-4339
Before:
After:
> [NETBEANS-4339] PHP Mess Detector - added option to use custom rules

- php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/CodeSniffer.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptionsValidator.java
- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/CodeSnifferStandardsComboBoxModel.java
Code Sniffer can be run without parameter '--standard'. In that case it is
looking for configuration file in project root.
> [NETBEANS-4337] Code Sniffer standard is optional

- php/php.composer/src/org/netbeans/modules/php/composer/commands/Composer.java
- php/php.composer/src/org/netbeans/modules/php/composer/files/ComposerJson.java
- php/php.composer/src/org/netbeans/modules/php/composer/ui/actions/ComposerActionsFactory.java
- php/php.composer/src/org/netbeans/modules/php/composer/ui/actions/ComposerScriptsAction.java
- php/php.composer/src/org/netbeans/modules/php/composer/ui/actions/UpdateAutoloaderDevAction.java
- php/php.composer/src/org/netbeans/modules/php/composer/ui/actions/UpdateAutoloaderNoDevAction.java
- php/php.composer/test/unit/data/composer-scripts.json
- php/php.composer/test/unit/src/org/netbeans/modules/php/composer/files/ComposerJsonTest.java
This PR adds actions into Composer menu to update autoloader (dump-autoload) and also submenu with scripts from composer.json.
https://issues.apache.org/jira/browse/NETBEANS-2623
New actions:
New submenu for scripts:
Implementation was inspired by "npm Scripts" menu.
> [NETBEANS-2623] Added Composer actions to update autoloader and run script

- harness/apisupport.harness/release/launchers/app.sh
Fix the platform application launcher script (for MasOS/Linux) to properly take the default_cachedir setting into account.
I encountered this problem while working on my own NetBeans Platform application, and fixed it a while back with the patch in this PR. Today, another NetBeans Platform developer reported the same problem on the mailing list.
One downside of this patch is that platform applications which encountered the problem before may now have their cache directory changed upon upgrade. Since the cache directory is considered a temporary directory which can be freely deleted at any time, this should not cause problems, other than the fact that the old cache directory may now linger around and take up disk space.
This patch does not impact the launcher script for the IDE (where the …
> [NETBEANS-4367] Properly handle default_cachedir in platform application launcher script

- .github/workflows/main.yml
- php/php.codeception/test/unit/src/org/netbeans/modules/php/codeception/coverage/CodeceptionCoverageLogParserTest.java
https://issues.apache.org/jira/browse/NETBEANS-4463
Expected file paths are normalized to match paths parsed from log file.
> [NETBEANS-4463] Fixed unit tests for Codeception on Windows

- enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/web/multiview/AbsoluteOrderingPanel.java
- enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/web/multiview/RelativeOrderingPanel.java
- enterprise/web.core/src/org/netbeans/modules/web/core/jsploader/TagLibParseSupport.java
- enterprise/web.core/src/org/netbeans/modules/web/wizards/ServletPanel.java
- enterprise/websvc.core/src/org/netbeans/modules/websvc/core/JaxWsUtils.java
- enterprise/websvc.core/src/org/netbeans/modules/websvc/core/jaxws/saas/RestWrapperForSoapGenerator.java
- enterprise/websvc.manager/src/org/netbeans/modules/websvc/manager/WebServiceManager.java
- enterprise/websvc.manager/src/org/netbeans/modules/websvc/manager/WebServicePersistenceManager.java
- enterprise/websvc.manager/src/org/netbeans/modules/websvc/manager/model/WebServiceListModel.java
- ide/refactoring.api/src/org/netbeans/modules/refactoring/api/AbstractRefactoring.java
- websvccommon/websvc.saas.codegen/src/org/netbeans/modules/websvc/saas/codegen/model/SoapClientOperationInfo.java
- websvccommon/websvc.saas.codegen/src/org/netbeans/modules/websvc/saas/codegen/util/Util.java
Remove use of the deprecated Logger.global field..
[repeat] /home/bwalker/src/netbeans/enterprise/web.core/src/org/netbeans/modules/web/wizards/ServletPanel.java:169: warning: [deprecation] global in Logger has been deprecated
[repeat]             Logger.global.log(Level.WARNING, "getServlets failed", e);
[repeat]                   ^
[repeat] /home/bwalker/src/netbeans/enterprise/web.core/src/org/netbeans/modules/web/wizards/ServletPanel.java:172: warning: [deprecation] global in Logger has been deprecated
[repeat]             Logger.global.log(Level.WARNING, "getServlets failed", e);
[repeat]                   ^
[repeat] Note: Some input files additionally use or override a deprecated API.
> [NETBEANS-4459] - remove use of deprecated field in Logger

- php/php.atoum/test/unit/data/coverage.xml
- php/php.atoum/test/unit/src/org/netbeans/modules/php/atoum/coverage/CloverLogParserTest.java
https://issues.apache.org/jira/browse/NETBEANS-4464
Directory separators had to be replaced with system-dependent value.
Because Windows use `\` as separator, replacement text has to be quoted.
> [NETBEANS-4464] Fixed unit tests for Atoum on Windows

- .travis.yml
- harness/nbjunit/apichanges.xml
- harness/nbjunit/manifest.mf
- harness/nbjunit/nbproject/project.properties
- harness/nbjunit/src/org/netbeans/junit/NbTestCase.java
- harness/nbjunit/src/org/netbeans/junit/RandomlyFails.java
- harness/nbjunit/test/unit/src/org/netbeans/junit/IgnoreTest.java
- harness/nbjunit/test/unit/src/org/netbeans/junit/NbModuleSuiteContextClassLoaderTest.java
- harness/nbjunit/test/unit/src/org/netbeans/junit/RandomlyFailsTest.java
- platform/libs.junit4/test/unit/src/org/netbeans/libs/junit4/JunitTest.java
Add support for JUnit [@Ignore annotation](http://junit.sourceforge.net/javadoc/org/junit/Ignore.html)  on [NbTestCase](https://bits.netbeans.org/dev/javadoc/org-netbeans-modules-nbjunit/org/netbeans/junit/NbTestCase.html) test case extension.
```java
@Ignore("Ignored test case")
public static class IgnoredTestCase extends NbTestCase {
public IgnoredTestCase(String n) {
super(n);
}
public void testFailed() {
fail();
}
}
```
> JUnit Ignore annotation support

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ConfigureProxy.java
Turns out that multiple invocations of `configureproxy` may actually mis-configure proxy!
* Invoke `configureproxy` ones - direct connection fails and a value is taken from the system and set to `httpProxy.host` property
* Invoke `configureproxy` second time - `url.openConnection()` succeeds (because of previously set `httpProxy.host` property) which is mistakenly treated as a sign of direct connection being possible
This PR fixes that by using `url.openConnection(Proxy.NONE)`.
> Make configureproxy idenpotent when invoked multiple times

- platform/openide.util.lookup/src/org/openide/util/lookup/implspi/ActiveQueue.java
- platform/openide.util.lookup/test/unit/src/org/openide/util/lookup/implspi/ActiveQueueWithSecurityManagerTest.java
- platform/openide.util/src/org/openide/util/TimedSoftReference.java
- platform/openide.util/test/unit/src/org/openide/util/NbBundleWithSecurityManager.properties
- platform/openide.util/test/unit/src/org/openide/util/NbBundleWithSecurityManagerTest.java
I am trying to execute application that uses `NbBundle` and `Lookup.allInstances` in a [browser](https://github.com/jtulach/bck2brwsr/commit/c79a4f5e725c79d22ebb3f714faa09271678161b) which supports only single-threaded Java.
Alas, `NbBundle` is using `TimedReference` and `AbstractLookup` is using `ActiveQueue` - both try to launch a thread. 
This change adds two tests that simulate such restricted environment by using `SecurityManager` and throwing a `SecurityException` whenever a thread is started. This change then modifies the code to catch the exception and go on.
With changes like this I managed to get an application using `NbBundle` and `Lookup` running.
> Let Lookup and NbBundle be usable in a sandbox

- .github/workflows/main.yml
- .travis.yml
- php/php.nette.tester/test/unit/data/coverage.xml
- php/php.nette.tester/test/unit/src/org/netbeans/modules/php/nette/tester/coverage/CloverLogParserTest.java
https://issues.apache.org/jira/browse/NETBEANS-4483
- Directory separators had to be replaced with system-dependent value.
- Because Windows use \ as separator, replacement text has to be quoted.
- Updated test to match line numbers after license change.
- Enabled tests in Travis and Github Actions
> [NETBEANS-4483] Fixed unit tests for Nette Tester

- apisupport/apisupport.ant/src/org/netbeans/modules/apisupport/project/universe/ModuleList.java
This avoids descending into .git/.hg and other hidden directories.
> [NETBEANS-3898] skip hidden files in ModuleList.doScanNetBeansOrgSources

- .github/workflows/main.yml
- .travis.yml
- php/php.symfony2/test/unit/data/issue232490.xml
- php/php.symfony2/test/unit/src/org/netbeans/modules/php/symfony2/commands/SymfonyCommandsXmlParserTest.java
https://issues.apache.org/jira/browse/NETBEANS-4499
- Created file `issue232490.xml` from `symfony2-commands.xml`
- Commented test SymfonyCommandsXmlParserTest:testIssue252901
- Enabled tests in Travis and Github Actions.
> [NETBEANS-4499] Fixed unit tests for Symfony 2/3

- groovy/gradle.test/src/org/netbeans/modules/gradle/test/GradleTestProgressListener.java
It seems Gradle post output events for tests SUITE-s before it would open a TestCase.
This one is a trivial fix, potential candidate fro 12.0.1 patch release.
> [NETBEANS-4410] Fixed NPE on Certain Gradle Test Executions.

- php/php.dbgp/src/org/netbeans/modules/php/dbgp/models/nodes/AbstractModelNode.java
- php/php.dbgp/src/org/netbeans/modules/php/dbgp/models/nodes/BooleanVariableNode.java
Boolean values are now displayed as `true` and `false` instead of `1` and `0`.
https://issues.apache.org/jira/browse/NETBEANS-1721
Before:
After:
> [NETBEANS-1721] Changed display of boolean values in PHP Debugger

- java/java.source.base/test/unit/src/org/netbeans/api/java/source/gen/SeparatorTest.java
The code has a test case that uses a proprietary API field - ARRAYLENGTH..
...
[nb-javac] /home/travis/build/apache/netbeans/java/java.source.base/test/unit/src/org/netbeans/api/java/source/gen/SeparatorTest.java:21: warning: ARRAYLENGTH is internal proprietary API and may be removed in a future release
[nb-javac] import com.sun.org.apache.bcel.internal.generic.ARRAYLENGTH;
[nb-javac]                                                ^
[nb-javac] /home/travis/build/apache/netbeans/java/java.source.base/test/unit/src/org/netbeans/api/java/source/gen/SeparatorTest.java:21: warning: ARRAYLENGTH is internal proprietary API and may be removed in a future release
[nb-javac] import com.sun.org.apache.bcel.internal.generic.ARRAYLENGTH;
[nb-javac]                                                ^ …
> [NETBEANS-4515] - remove use of proprietary API - ARRAYLENGTH

- .github/workflows/main.yml
- .travis.yml
- ide/csl.api/test/unit/src/org/netbeans/modules/csl/api/test/CslTestBase.java
- php/php.editor/src/org/netbeans/modules/php/editor/verification/IntroduceSuggestion.java
- php/php.editor/test/unit/data/testfiles/verification/testIntroduceSuggestion.php.testIntroduceSuggestion_01.hints
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/js/JsFormatterEmbeddedTest.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/parser/PhpParserErrorTest.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/verification/HintsTest.java
https://issues.apache.org/jira/browse/NETBEANS-4500
- Use UTF-8 when opening files.
- Use system-specific directory separators.
- Enabled tests in Github Actions.
> [NETBEANS-4500] Fixed tests for PHP Editor on Windows

- php/php.editor/src/org/netbeans/modules/php/editor/model/impl/VariousUtils.java
- php/php.editor/test/unit/data/testfiles/completion/lib/arrays/arrays.php
- php/php.editor/test/unit/data/testfiles/completion/lib/arrays/arrays.php.testArrays_05.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/arrays/arrays.php.testArrays_06.completion
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPArrayCodeCompletionTest.java
https://issues.apache.org/jira/browse/NETBEANS-4509
Fixed code completion of functions with return type "array" and specific
type in "@return" in DocBlock.
Example:
```php
/**
* @return \SplFileInfo[]
*/
function getFiles(): array { }
foreach (getFiles() as $file) {
$file->^ // Offers methods from \SplFileInfo
}
```
Before this fix methods from `\SplFileInfo` will not be offered.
> [NETBEANS-4509] PHP - code completion for function with return type

- php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/CodingStandardsFixer.java
https://issues.apache.org/jira/browse/NETBEANS-4541
Set working directory when PHP CS Fixer is run.
Project configuration file is now found.
Output before: `Loaded config default.`
Output after: `Loaded config default from "C:\Devel\PhpProject\.php_cs.dist".`
> [NETBEANS-4541] Set working directory when running PHP CS Fixer

- php/php.editor/src/org/netbeans/modules/php/editor/model/VariableScopeFinder.java
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4503/nb4503.php
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4503/nb4503.php.testNb4503_01.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4503/nb4503.php.testNb4503_02.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4503/nb4503.php.testNb4503_03.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4503/nb4503.php.testNb4503_04.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4503/nb4503.php.testNb4503_05.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4503/nb4503.php.testNb4503_06.completion
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionNb4503Test.java
https://issues.apache.org/jira/browse/NETBEANS-4503
Nested functions are in a Method/FunctionScope.
However, they are added as elements of a NamespaceScope.
i.e. Method/FunctionScope doesn't have nested FunctionScopes. NamespaceScope has them.
So, (not return the child result simply,) check whether the child result contains the parent result in the `VariableScopeFinder.findWrapper()`.
Unit test(testNb4503_01()) failed on GitHub Actions after I pushed the first commit.
However, It passed on my local pc.
After I've tried some things, I've somehow reproduced it.
```java
public void testNb4503_01() throws Exception {
Thread.sleep(1000); // added this, then reproduced
testNb4503("            $e->^test(); // test1");
}
```
Unfortunately, if I set a breakpoint, I couldn't reproduce it. Just used …
> [NETBEANS-4503] Code completion does not work in functions declared inside methods

- nbbuild/rat-exclusions.txt
When running the RAT report after a build has taken place, the report
picks up hundreds of build generated files. These files do not have a license
header and it's really not necessary as they are generated by the build process..
> [NETBEANS-4465] - update RAT license exceptions

- php/php.code.analysis/src/org/netbeans/modules/php/analysis/options/AnalysisOptions.java
https://issues.apache.org/jira/browse/NETBEANS-4562
- https://phpstan.org/user-guide/rule-levels
> [NETBEANS-4652] Change the max level of PHPStan to 8

- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/AbstractWinEditorTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/AquaEditorTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/BaseTabLayoutModel.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/BasicScrollingTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/GtkEditorTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/MetalEditorTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/NimbusEditorTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/NonStretchingViewTabLayoutModel.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/ToolbarTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/ViewTabLayoutModel2.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/WinClassicEditorTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/WinXPEditorTabDisplayerUI.java
This PR fixes the problem shown in the editor tab in the screeenshot; on some HiDPI scaling factors (150% in this case), the text in the tab may be incorrectly measured. The bug is fixed by making sure that the right FontRenderContext, with HiDPI scaling taken into account, is used when painting on a particular monitor.
See also https://github.com/apache/netbeans/pull/2025 , which fixed a similar problem in the org.openide.awt.HtmlRenderer class.
> [NETBEANS-4066] Fix overshooting text in editor tabs on HiDPI displays

- php/php.composer/src/org/netbeans/modules/php/composer/output/parsers/CliParser.java
- php/php.composer/test/unit/src/org/netbeans/modules/php/composer/output/parsers/CliParserTest.java
https://issues.apache.org/jira/browse/NETBEANS-4507
Fixed parsing of `composer search` output when package does not have
description.
This happens when [composer-asset-plugin](https://github.com/fxpio/composer-asset-plugin) is installed. Then output contains also packages without description.
> [NETBEANS-4507] Fix Composer search when package has no description

- ide/db.core/src/org/netbeans/modules/db/sql/loader/SQLEditorSupport.java
Remove the synchronization in SQLEditorSupport#closeLogger. The critical
part (ensuring logger is not closed while it could be acquired) is
protected by the finer grained loggerLock and thus the monitor on
SQLEditorSupport is not needed.
The deadlock sequence showed:
- the EDT held the monitor of SQLEditorSupport
- a task was dispatched into a request processor
- the EDT waited for the task to finish
- the task tried to enter the monitor of SQLEditorSupport
> [NETBEANS-4308] Deadlock in SQLEditorSupport

- php/php.editor/src/org/netbeans/modules/php/editor/model/impl/VariousUtils.java
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnSelf_01.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnSelf_02.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnSelf_03.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnSelf_04.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnSelf_05.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnSelf_06.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnStatic_01.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnStatic_02.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnStatic_03.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnStatic_04.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnStatic_05.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnStatic_06.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnThis_01.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/nb4185/nb4185.php.testReturnThis_02.completion
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionNb4185Test.java
https://issues.apache.org/jira/browse/NETBEANS-4185
Added test files based on [PHPCodeCompletion269108Test](https://github.com/apache/netbeans/blob/master/php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion269108Test.java) testing same feature but without return type in method.
Fixed case when native return type `self` is used in combination with PHPDoc annotations `@return static` and `@return $this.`
> [NETBEANS-4185] Support for self return type

- php/php.code.analysis/src/org/netbeans/modules/php/analysis/commands/CodingStandardsFixer.java
https://issues.apache.org/jira/browse/NETBEANS-4573
The relative paths from the working directory are used in XML log if the working directory is set. So, set it as the root directory.
> [NETBEANS-4573] PHP CS Fixer doesn't work with a directory and a file

- php/php.api.phpmodule/manifest.mf
- php/php.api.phpmodule/src/org/netbeans/modules/php/api/PhpVersion.java
- php/php.api.phpmodule/src/org/netbeans/modules/php/api/validation/ValidationResult.java
- php/php.api.phpmodule/test/unit/src/org/netbeans/modules/php/api/PhpVersionTest.java
- Add the `isSupportedVersion()` method to the PhpVersion
- Check whether the version is supported yet by PHP official
- Improve the `getLegacy()` method
- Add the `getFirstError()` and the `getFirstWarning()` methods to the `ValidationResult` class
> Minor improvements for php.api.phpmodule

- ide/editor.search/src/org/netbeans/modules/editor/search/SearchComboBoxEditor.java
https://issues.apache.org/jira/browse/NETBEANS-4444
Selection is not removed when text is input via IME. So, just remove it when the caret is changed.
> [NETBEANS-4444] The selected text is not removed in the Find Combobox when text is input via IME

- profiler/profiler.oql/src/org/netbeans/modules/profiler/oql/engine/api/impl/Snapshot.java
- profiler/profiler.oql/src/org/netbeans/modules/profiler/oql/engine/api/impl/hat.js
- profiler/profiler.oql/test/unit/src/org/netbeans/modules/profiler/oql/engine/api/impl/OQLEngineTest.java
Backport of OQL finalizables bugfix from VisualVM (see [d936905](https://github.com/oracle/visualvm/commit/d9369059b5017c868e831bd1317381718fbe55c1) and [bd9bf46](https://github.com/oracle/visualvm/commit/bd9bf46131fd9e6c1d25ec475775aefbc6540021)).
The PR corrects previous implementation of `heap.finalizables()` in OQL engine which used to fail with a `ClassCastException` for any heap file. Additionally, it also includes a small fix for JavaScript test cases which called several OQL functions incorrectly (reason why the failing behaviour of `finalizables` was not discovered before).
(cc: @JaroslavTulach)
> Backport of OQL finalizables fix

- platform/core.network/src/org/netbeans/core/network/proxy/kde/KdeNetworkProxy.java
The IDE only reads KDE4 proxy settings in `.share/kde/config/kioslaverc`, bude KDE5 stores these settings in a different place `.config/kioslaverc`. Both files should be read to preserve compatibility with older desktops.
> Include both KDE4 and KDE5 proxy settings.

- platform/core.network/src/org/netbeans/core/network/proxy/pac/impl/NbPacScriptEvaluator.java
NetBeans prefer the bundled-in `GraalVM:js` javascript engine for security reasons, but that engine cannot be used by multiple threads simultaneously. In fact, no javascript `ScriptEngine` probably can, since the shared toplevel scope is not likely to be thread-safe in a single-thread language.
The patch will simply prevent two threads from simultaneous execution in the same JS context; should not deadlock as the PAC evaluation cannot reach out to java classes.
> [NETBEANS-4123] PAC evaluator scripts runs just one at a time.

- ide/projectui/src/org/netbeans/modules/project/ui/SimpleTargetChooserPanelGUI.java
If there is no active project, then the New File Wizard does not allow to open the file chooser for selecting the folder. This patch fixes that without affecting unintended side effects. This is more of feature enhancement.
**Before**
**After**
**Expected funtionality unaffected**
> [NETBEANS-4520] Enable File Chooser in non-project New File Wizard

- ide/editor/src/org/netbeans/modules/editor/url/Parser.java
- ide/editor/test/unit/src/org/netbeans/modules/editor/url/ParserTest.java
https://issues.apache.org/jira/browse/NETBEANS-4593
> [NETBEANS-4593] Recognize a URL which contains "@"

- ide/css.editor/src/org/netbeans/modules/css/resources/layer.xml
https://issues.apache.org/jira/browse/NETBEANS-1646
Currently, CSS, SCSS, and LESS are used the same options(options for CSS). If we would like to use the options each language, need other fixes.
> [NETBEANS-1646] Formatting options for CSS

- harness/nbjunit/apichanges.xml
- harness/nbjunit/manifest.mf
- harness/nbjunit/src/org/netbeans/junit/NbModuleSuite.java
- ide/libs.graalsdk/src/org/netbeans/libs/graalsdk/impl/GraalContext.java
- ide/libs.graalsdk/src/org/netbeans/libs/graalsdk/impl/GraalEngine.java
- ide/libs.graalsdk/src/org/netbeans/libs/graalsdk/impl/GraalEngineFactory.java
- ide/libs.graalsdk/src/org/netbeans/libs/graalsdk/impl/LangContext.java
- ide/libs.graalsdk/src/org/netbeans/libs/graalsdk/package-info.java
- ide/libs.graalsdk/test/unit/src/org/netbeans/libs/graalsdk/GraalEnginesTest.java
- ide/libs.graalsdk/test/unit/src/org/netbeans/libs/graalsdk/JavaScriptEnginesTest.java
- ide/libs.graalsdk/test/unit/src/org/netbeans/libs/graalsdk/ScriptingTutorial.java
- platform/api.scripting/test/unit/src/org/netbeans/api/scripting/JavaScriptEnginesTest.java
- platform/libs.junit4/manifest.mf
- platform/libs.junit4/nbproject/project.xml
There are a few types of changes:
- the exceptions thrown are better reported: the original exception is attached as the `cause` of the `RuntimeException` (actually `PolyglotException`) thrown from eval/invoke methods.
- better (un)wrapping of `org.graalvm.polyglot.Value` from/to POJOs
- the `ScriptEngine` returned by `Scripting.createManager()` will support `ScriptContext.ENGINE` scope as the top-level language scope.
- global attributes are now supported, even before the first `eval` or other `Context`-creating method on the Engine is called.
I also somewhat checked the testu results agains GraalVM 20.1 (now travis runs 19.3.1)
> Improve GraalVM script engines interoperability.

- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Add entry to the `OFFICIAL_JAVADOC` Map
[JDK 16 API Javadoc](https://download.java.net/java/early_access/jdk16/docs/api/)
> [NETBEANS-4572] - Add javadoc for JDK 16 early access

- java/java.editor/src/org/netbeans/modules/editor/java/TypingCompletion.java
- java/java.editor/test/unit/src/org/netbeans/modules/editor/java/TypingCompletionUnitTest.java
Consider code like:
"""
"|
"""
Where '|' is the caret position. Now press backspace. This will delete the ", but also the next character (newline in this case). This makes editing inside the text block quite annoying.
Not sure if this breaks some other text block editing scenario - tests are passing, but may be cases not covered by tests.
> Fixing removal of a double-quote inside a text block.

- platform/openide.util.lookup/apichanges.xml
- platform/openide.util.lookup/manifest.mf
- platform/openide.util.lookup/src/org/openide/util/lookup/ProxyLookup.java
- platform/openide.util.lookup/test/unit/src/org/openide/util/lookup/ProxyLookupFactoryMethodsTest.java
One of the most common uses of `ProxyLookup` is to dynamically change the set of `Lookup`s being proxied (a quick grep finds 53 such cases in the NetBeans source base, and I can think of > 10 I have written in external modules).  For each consumer of the API that needs to do this, it is necessary to write identical subclasses with a public or package visibility method that exposes one of `ProxyLookup`'s `setLookups()` methods.
This patch adds `ProxyLookup.create(Consumer<Consumer<Lookup[]>>)` and `ProxyLookup.createThreaded(Consumer<BiConsumer<Executor, Lookup[]>>) `to satisfy the non-threaded and threaded-event-delivery variants supported as protected methods on ProxyLookup.  These allow a mechanism for updating the set of proxied lookups to be passed to the caller without exposing that …
> [NETBEANS-4699] Make it easy to create dynamically updated ProxyLookup instances without subclassing

- platform/openide.filesystems.compat8/src/org/openide/filesystems/FileSystemCompat.java
The Filesystems API compatibility module provides implementations for
Filesystem#getActions for several filesystems. Most filesystem
implementations are covered by the implementation in
AbstractFileSystemCompat, but this does not cover implementations
directly inheriting from Filesystem.
One such filesystem is BinaryFS.
In the SQL Editor the command window function (temp files for SQL
execution) is backed by a file in the SystemFileSystem, which delegates
in the end to BinaryFS:
SystemFileSystem-> 
ModuleLayeredFileSystem ->
BinaryFS
As BinaryFS does not implement getActions and no patch is provided for
this class, an AbstractMethodError is raised.
Instead of bailing out with an Error, the compatibility implementation
now returns an empty array to satisfy the Filesystem#getActions …
> [NETBEANS-3409] Missing popup menu for sql editor tabs

- ide/editor.search/src/org/netbeans/modules/editor/search/SearchComboBoxEditor.java
https://issues.apache.org/jira/browse/NETBEANS-4620
Probably https://issues.apache.org/jira/browse/NETBEANS-4623, too
To avoid NPE, check new value is not `null` but `Caret`. If it's `null`, `BasicTextUI.editor` field may be `null`.
```
at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1104)
at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1089)
at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1065)
at org.netbeans.modules.editor.search.SearchComboBoxEditor$ManageViewPositionListener.changed(SearchComboBoxEditor.java:290)
at org.netbeans.modules.editor.search.SearchComboBoxEditor$ManageViewPositionListener.removeUpdate(SearchComboBoxEditor.java:277)
at …
```
> [NETBEANS-4620] NullPointerException - finding occurrences

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties
Simple fix for selection background in output view, which was nearly unreadable. 
Used same selection background colors as in editor.
Before:
After:
Before:
After:
> [NETBEANS-3428] FlatLaf: fix selection background color in output view

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
Simple fix for https://issues.apache.org/jira/browse/NETBEANS-4627
Before:
After:
> [NETBEANS-4627] FlatLaf: fix wrong background color of search result table in Find Tasks Editor

- extide/libs.gradle/external/binaries-list
- extide/libs.gradle/external/gradle-tooling-api-6.6-license.txt
- extide/libs.gradle/external/gradle-tooling-api-6.6-notice.txt
- extide/libs.gradle/manifest.mf
- extide/libs.gradle/nbproject/project.properties
- extide/libs.gradle/nbproject/project.xml
Regular Gradle Tooling API upgrade.
> [NETBEANS-4717] Upgrade Gradle Tooling API to 6.6

- webcommon/javascript2.extjs/test/unit/src/org/netbeans/modules/javascript2/extjs/model/ExtModelTest.java
- webcommon/javascript2.extjs/test/unit/src/org/netbeans/modules/javascript2/extjs/model/JsStructureTest.java
It seems that for some networks CDNJS requires sending a User-Agent
header. This changeset adds it to the requests.
> Fix unittest for webcommon caused by download failures from cdnjs

- ide/lsp.client/src/org/netbeans/modules/lsp/client/LSPBindings.java
- ide/lsp.client/test/unit/src/org/netbeans/modules/lsp/client/LSPBindingsTest.java
- webcommon/typescript.editor/src/org/netbeans/modules/typescript/editor/TypeScriptDataObjectDataObject.java
Yesterday I tweeted about great [NetBeans support for TypeScript](https://twitter.com/JaroslavTulach/status/1295985307020484613) then I realized it only works in projects. Not for standalone files. I decided to fix it.
> Make LSP servers work even for files outside of any project

- nbbuild/binaries-default-properties.xml
- nbbuild/default-properties.xml
- nbbuild/installer/infra/build/build.sh
- nbi/engine/build.xml
- nbi/engine/external/applemenu-external-desktop-classes-8.2-license.txt
- nbi/engine/external/binaries-list
- nbi/engine/src/org/netbeans/installer/utils/system/launchers/impl/CommonLauncher.java
- nbi/engine/src/org/netbeans/installer/wizard/containers/InitializeMacJDK8.java
- nbi/engine/src/org/netbeans/installer/wizard/containers/InitializeMacJDK9.java
- nbi/engine/src/org/netbeans/installer/wizard/containers/SwingFrameContainer.java
This pull request fixes the NetBean RCP installer on macOS with Java 11+ since `com.apple.eawt` classes were removed with JEP 272
Supersedes the following PRs and addresses their comments: 
-  Closes #1929
-  Closes #2015
@mcdonnell-john and/or @arusinha can you please review this PR.
Note: once this PR is merged and we have a new release, we will need to update https://github.com/apache/netbeans-mavenutils-nbm-maven-harness to use the latest nbi-engine nbm as it is currently using RELEASE112.
> [NETBEANS-3342] Fix Netbeans Installer on macOS to work with Java 8 and Java 11+

- ide/slf4j.api/nbproject/project.properties
- ide/slf4j.api/nbproject/project.xml
Currently is:
external/org.slf4j.api-1.7.28.jar
Should be:
external/slf4j-api-1.7.28.jar
> [NETBEANS-4777] - Fix wrong binary-origin path for slf4j-api

- java/maven/src/org/netbeans/modules/maven/queries/UnitTestsCompilerOptionsQueryImpl.java
This change avoids the deadlock by having maven projects open use the non-locking `SourceUtils.parseModuleName(moduleInfo)` instead of invoking the parser.
It should be a safe change. Another change, for the other bad actor in the deadlock, is forthcoming
@tzezula Will you review?
> [NETBEANS-4696] maven project open use no-lock getModuleName

- webcommon/javascript2.knockout/nbproject/project.xml
- webcommon/javascript2.knockout/src/org/netbeans/modules/javascript2/knockout/index/KnockoutIndex.java
The html parser, in twisty paths, is used from many areas (for example, braceMatching). Without this change, the parser waits for project open, and this created a deadlock. (#2340 takes care of one side). However, according to analysis by @jtulach in the issue report, the html parser should not be calling into the projectui api.
This PR does not fix that, it does avoid blocking on the project ui api. A careful analysis of the html parsing code, and how it's used, should be done to see if there are any unexpected consequences of this change.
The eventual goal is to completely remove the dependency as outlined in the analysis as seen in issue [NETBEANS-4696].
> [NETBEANS-4696] html parser dont wait for projects open

- nbbuild/installer/mac/newbuild/commonfiles/get_current_jdk.sh
- nbbuild/installer/mac/newbuild/commonfiles/postinstall/postinstall
- nbbuild/installer/mac/newbuild/dmg/distribution-nbide.dist
- nbbuild/installer/mac/newbuild/dmg/distribution.dist
- nbi/engine/native/launcher/unix/src/launcher.sh
Adding the fix that was applied to generate the Mac OS installer for Apache NetBeans 12.1
> [NETBEANS-4779] Update to the mac os installer as it was failing on Big Sur

- java/maven/src/org/netbeans/modules/maven/execute/defaultActionMappings.xml
- java/maven/test/unit/src/org/netbeans/modules/maven/api/customizer/ModelHandle2Test.java
- java/maven/test/unit/src/org/netbeans/modules/maven/execute/ModelRunConfigTest.java
Notes:
- Support for JPMS module path for exec:java
- 4 Bug fixes
- 10 Enhancements
[Web Page](http://www.mojohaus.org/exec-maven-plugin/)
[Releases Notes](https://github.com/mojohaus/exec-maven-plugin/releases)
- Started NetBeans and ensure the log didn't have any errors or new warnings
- Checked that the maven actions had the new version inside a maven project:
Project Properties > Actions > `Run Project`, `Run file via main()`, `Debug project`, `Debug file via main()`, `Debug file via main()` and  `Profile file via main()`
- Run File and ensure new plugin version is used in the Output
> [NETBEANS-4666] - Upgrade exec-maven-plugin from 1.5.0 to 3.0.0

- extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDistributionProviderImpl.java
Trivial change, big effect on wrapperless Gradle projects, as they bring up an exception captured dialog, however that would be a normal operation.
> [NETBEANS-4731] Mute loud loggers when detecting gradle distribution

- platform/api.search/src/org/netbeans/modules/search/Constants.java
Some clients of ours had this problem, they had a lot of files to search inside, but NetBeans limited the maximum number of results to 500.
> Added property to allow the user to specify the max number of objects and details in search:

- platform/autoupdate.services/arch.xml
In the [Apache Netbeans documentation overview](https://bits.netbeans.org/dev/javadoc/), the Auto Update Services module shows a package name instead a short description.
This PR adds a short description in the arch-what answer and moves api export entries to the arch-overall answer.
> Change platform/autoupdate.services arch-what response

- nbbuild/antsrc/org/netbeans/nbbuild/CustomJavac.java
>  matthiasblaesing commented 6 hours ago in #2369:
>  @mcdonnell-john I was able to reproduce your problem. It happens if the build JDK and the target JDK are not the same. I had this in my ".nbbuild.properties":
```
#permit.jdk9.builds=true
nbjdk.home=/home/matthias/bin/jdk-8
```
> This will lead to ant finding the desktop classes, while in the compile run they are not present. 
Please accept apology for not spotting this problem sooner. This is an additional fix for #2337 to make it work `nbjdk.home=` set.
Up to @lkishalmi to decide whether to merge this, merge #2369 or merge both.
> Fixing nbjdk.home behavior broken by #2337 

- webcommon/javascript.nodejs/src/org/netbeans/modules/javascript/nodejs/exec/NpmExecutable.java
- webcommon/javascript.nodejs/src/org/netbeans/modules/javascript/nodejs/ui/libraries/LibraryProvider.java
IDE npm search (Web project > properties > npm > add) is broken due to output format change in npm.
This commit uses npm --parseable flag to fix and simplify output parsing.
Tested with npm 6.14.4
> [NETBEANS-4667] Fix broken npm search
