- nbbuild/default.xml
- nbbuild/templates/projectized.xml
After PR #3974, the [Apache NBLS distribution is unbuildable](https://ci-builds.apache.org/job/Netbeans/job/netbeans-vscode/1037/):
- the IDE build now requires JDK11 (which might be OK, but was not communicated on mailing list in advance, so it is a sort of bad surprise since the build started to fail between vote start and vote end)
- when the build switched to JDK11, it [turned out that it still fails](https://ci-builds.apache.org/job/Netbeans/job/netbeans-vscode/1049/) 
The failure is because of:
```
[junit] Test org.netbeans.modules.java.mx.project.SdkSuiteTest FAILED (crashed)
[junit] Error occurred during initialization of boot layer
[junit] java.lang.module.FindException: Module jdk.internal.opt not found, required by jdk.jshell
```
in `java/java.mx.project`, but essentially in …
> Do not include jdk.jshell in test mod list by default.

- java/java.mx.project/nbproject/project.properties
- java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteActionProvider.java
- nbbuild/templates/projectized.xml
Yet another fixes to fix `java.mx.project` testsuite on JDK11. Potentially other testsuites, too
- tests that access JPDA API should be now failing on JDK11, as `--limit-modules` does not allow them to see JPDA classes. This should be less controversial :) as we definitely want to access debugger support in platform from java cluster at least.
- `java.mx.project` testsuite needs `mx` binary on PATH (or know full path to it); the buildscript `git clone`s one, but it's not on path. Moreover the copy made into `build/test/unit/data` directory omits executable attribute, so the git clone sources must be used directly
Note that passing the `mx` location in system properties should also fix tests on JDK8 -- see for example [Test Java modules with nb-javac on Java …
> Allow tests to access JPDA. Pass mx path to the testsuite.

- extide/gradle/src/org/netbeans/modules/gradle/GradleReport.java
- extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java
During testing of #4041, I've encountered issues that possibly affect NB14 - fixes are simple enough. 
* If `location' does not contain a proper path (it is a description, or e.g. a remote), Paths.get() or Path.relativize() may throw an exception
* setting file locations are interpreted
> Additional fixes for Gradle reports

- platform/core.ui/src/org/netbeans/core/ui/options/filetypes/IgnoredFilesPreferences.java
- platform/masterfs/src/org/netbeans/modules/masterfs/GlobalVisibilityQueryImpl.java
Trivial enhancement on the Global ignore list adding ```.gradle/``` directories.
In general Gradle plugin adds the ```.gradle/``` directories to the project ignore list, though this might be handy as well.
> Put .gradle directories on Global ignore list.

- java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/DumpStack.java
- java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/SuiteActionProviderTest.java
- java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/TrufleSuiteTest.java
Test [org.netbeans.modules.java.mx.project.TrufleSuiteTest.testParseTruffleSourcesWithoutError](https://ci-builds.apache.org/job/Netbeans/job/netbeans-vscode/1067/testReport/org.netbeans.modules.java.mx.project/TrufleSuiteTest/testParseTruffleSourcesWithoutError/) is failing regularly. The cause was a clean action run by `SuiteActionProviderTest`, which deleted build artifacts that were necessary to assemble the class path.
> Repair failing TrufleSuiteTest.testParseTruffleSourcesWithoutError().

- java/libs.javacapi/external/binaries-list
- java/libs.javacapi/external/nb-javac-jdk-18.0.1+10-license.txt
- java/libs.javacapi/nbproject/project.xml
- java/libs.nbjavacapi/external/binaries-list
- java/libs.nbjavacapi/external/nb-javac-jdk-18.0.1+10-license.txt
- java/libs.nbjavacapi/nbproject/project.properties
- java/libs.nbjavacapi/nbproject/project.xml
- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
nb-javac got updated https://github.com/JaroslavTulach/nb-javac/pull/7
this PR bumps the nb-javac version from GA to the update release. I did **NOT** bump any module versions since master is already at 18.1 (https://github.com/apache/netbeans/pull/4045/files). Someone would have to tell me what to increment :)
18.0.1 fixes three javac related bugs:
https://bugs.openjdk.java.net/browse/JDK-8278373
https://bugs.openjdk.java.net/browse/JDK-8278834
https://bugs.openjdk.java.net/browse/JDK-8278930
delta is likely fairly small since not much happened language wise in Java 18.
we are super late in the RC cycle though, the fact that travis isn't running doesn't help the situation.
this is based on delivery
> upgrade nb-javac to 18.0.1.

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/LspTreeViewServiceImpl.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeItem.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeViewProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/WeakIdentityMap.java
- platform/openide.nodes/src/org/openide/nodes/AsynchChildren.java
- platform/openide.nodes/src/org/openide/nodes/Children.java
- platform/openide.nodes/test/unit/src/org/openide/nodes/ChildFactoryTest.java
The bug manifests in several places. Most notably in vscode DB Explorer where a `Refresh` action causes vscode-nbls communication to fail with `Node xxx is already present`. This is caused by creation of a new node - a new identity, which is equal() to the previously created node, which is still in the map (since the client may still ask for its details).
And that node is created (since keys - underlying DB data) did not actually even change is done because of some of DB children use `ChildFactory` SPI from Nodes - this is the other fix. It turned out that `add` method of the `j.u.List` passed to `ChildFactory.createKeys()` is tweaked so it detects actual addition beyond the original content - and causes interim keys refresh, which, in turn, causes Node removal for whose keys are not …
> Fix 'node id XXX already exists' error in vscode.

- java/maven/src/org/netbeans/modules/maven/execute/defaultActionMappings.xml
This can be a fix for #4089 with the option to change de default action mapping for integration test.
> change default integration test goal action mapping to failsafe

- cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPFrame.java
- cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPLiteDebugger.java
- cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPVariable.java
- java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/displayer/DynamicHub.java
- java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/displayer/JavaFrameDisplayer.java
- java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/displayer/JavaVariablesDisplayer.java
- java/java.nativeimage.debugger/src/org/netbeans/modules/java/nativeimage/debugger/displayer/Utils.java
Debugging of native images adapted for images built by GraalVM CE.
CE images have relative paths and different object layout.
> Debugging of native images built by GraalVM CE.

- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/ClassPathProviderImpl.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/CompilerOptionsQueryImpl.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/TestRootDescription.java
I would like to add `--enable-preview` to the javac parameters used internally by the IDE to parse jtreg (OpenJDK) tests.
> Set --enable-preview for jtreg tests.

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Hi, would like to see if it can help structuring release note.
I'm unaware if I can try it on my forks as labels belongs to apache/netbeans.
So this would be a first step
> test release-drafter

- groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/ASTUtils.java
- groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/language/GroovyDeclarationFinder.java
- groovy/groovy.editor/test/unit/data/testfiles/declarationfinder/ClassWithInner.groovy
- groovy/groovy.editor/test/unit/src/org/netbeans/modules/groovy/editor/api/GroovyDeclarationFinderTest.java
`ASTUtils.getOwningClass()` iterates paths in the wrong order.
A small correction is also applied to `GroovyDeclarationFinder`, where once `ASTUtils.getRange(...)` was called and once `ASTUtils.getOffset(...)`. I've extracted that to `getVariableLocation(...)` to assure that the logic is the same.
A test is included.
> Correction of getOwningClass(), including a test.

- ide/web.common.ui/src/org/netbeans/modules/web/common/ui/refactoring/RenamePanel.java
> Autofocus new name field when renaming folder #4076

- webcommon/javascript2.doc/manifest.mf
- webcommon/javascript2.doc/nbproject/project.xml
- webcommon/javascript2.editor/manifest.mf
- webcommon/javascript2.editor/nbproject/project.xml
- webcommon/javascript2.model/manifest.mf
- webcommon/javascript2.model/nbproject/project.xml
- webcommon/libs.nashorn/external/binaries-list
- webcommon/libs.nashorn/external/graaljs-parser-1.1-license.txt
- webcommon/libs.nashorn/manifest.mf
- webcommon/libs.nashorn/nbproject/project.properties
- webcommon/libs.nashorn/nbproject/project.xml
Optional function calls: base?.(arg1, arg2)
Optional indexing calls: base?.[idx]
> Update graaljs parser to handle optional chaining (?.) for indexing and function calls

- platform/openide.nodes/apichanges.xml
- platform/openide.nodes/src/org/openide/nodes/PropertySupport.java
I was working on Gradle configuration nodes to expose more information on them, while I bumped into PropertySupport and realized how old school that could be, especially if the represented value needs to be converted/formatted as well.
So I put some new age in the code. I hope you do not mind that I've removed some compile warnings alongside my additions.
Also, I'm open for feedback, method name changes etc.
> Added support for properties backed up by functional interfaces

- README.md
added section to the readme which lists config/log/cache locations. Easily linkable to users which have configuration issues. Fixed some old or broken links.
preview link: https://github.com/mbien/netbeans/tree/readme-updates#log-config-and-cache-locations
> readme updates (fixed links) + new log/config/cache section.

- ide/git/src/org/netbeans/modules/git/ui/checkout/AbstractCheckoutAction.java
- ide/git/src/org/netbeans/modules/git/ui/checkout/Bundle.properties
fixes #4148
following the reproduction steps as described in the issue, trying to check out a branch on windows from a repo which contains invalid files/paths will result in this output:
```
==[IDE]== 31.05.2022, 21:28:02 Cloning finished.
==[IDE]== 31.05.2022, 21:33:00 Checkout...
git branch --track main2 origin/main
Branch with revision origin/main, could not be created
git show conflicts
git checkout main2
==[IDE]== 31.05.2022, 21:33:03 Checkout... finished.
```
additional to the git error popup stating the error:
```
Commit e476c05de56775cd9074f307562cc947f7f5072b cannot be checked out because an invalid file name in one of the files.
Please remove the file from repository with an external tool and try again.
Invalid path: japanese/prn
```
the NPE is no longer thrown.
> fix NPE on git checkout error, print msg to output instead.

- extide/gradle/src/org/netbeans/modules/gradle/api/execute/RunUtils.java
Trivial fix for NPE. The NPE can happen if the IDE is set to not prefer Gradle Wrapper, but a specific version.
> Fix possible NPE at RunUtils.getCompatibleGradleDistribution

- README.md
- nbbuild/rat-exclusions.txt
Remove mingw from readme windows launcher are not built in the main jobs.
Add link to netbeans-license job (the new one) only focus on rat+verifylibs (IMHO MUST be green before trying to release)
(FYI) https://ci-builds.apache.org/job/Netbeans/job/netbeans-apisigcheck/ still do the api sig chek but it's unstable since long time 
Fix rat issue due to npss file not sure the categorization of this file.
> Cleanup readme and fix rat issue

- ide/project.dependency/src/org/netbeans/modules/project/dependency/ArtifactSpec.java
- ide/project.dependency/src/org/netbeans/modules/project/dependency/DependencyResult.java
- ide/project.dependency/src/org/netbeans/modules/project/dependency/ProjectDependencies.java
- ide/project.dependency/src/org/netbeans/modules/project/dependency/ProjectOperationException.java
- ide/project.dependency/src/org/netbeans/modules/project/dependency/Scope.java
- ide/project.dependency/src/org/netbeans/modules/project/dependency/Scopes.java
- ide/project.dependency/src/org/netbeans/modules/project/dependency/spi/ProjectDependenciesImplementation.java
- java/maven.embedder/apichanges.xml
- java/maven.embedder/manifest.mf
- java/maven.embedder/src/org/netbeans/modules/maven/embedder/DependencyTreeFactory.java
- java/maven.embedder/src/org/netbeans/modules/maven/embedder/EmbedderFactory.java
- java/maven.embedder/src/org/netbeans/modules/maven/embedder/impl/OfflineConnector.java
- java/maven.embedder/src/org/netbeans/modules/maven/embedder/impl/OfflineOperationError.java
- java/maven/.gitignore
- java/maven/nbproject/project.xml
- java/maven/src/org/netbeans/modules/maven/queries/MavenDependenciesImplementation.java
- java/maven/test/unit/data/projects/dependencies/golden/testCompileDependencies
- java/maven/test/unit/data/projects/dependencies/golden/testRuntimeDependencies
- java/maven/test/unit/data/projects/dependencies/repo/grp/test-lib/12.6/_remote.repositories
- java/maven/test/unit/data/projects/dependencies/repo/grp/test-lib/12.6/test-lib-12.6.jardir/META-INF/maven/nbtest.grp/test-lib/pom.xml
- java/maven/test/unit/data/projects/dependencies/repo/grp/test-lib/12.6/test-lib-12.6.pom
- java/maven/test/unit/data/projects/dependencies/src/test-lib/pom.xml
- java/maven/test/unit/src/org/netbeans/modules/maven/queries/MavenDependenciesImplementationTest.java
During testing (and usage), it turned out that the newer `DependencyGraphBuilder` does not give out as much information as the older `DependencyTreeBuilder`. Namely duplicated artifacts are omitted from the dependency report and in case of a version clash, the clashing artifact is **removed at all** from the report.
So this PR mainly rewrites the maven implementation back to the older API so that more info can be pulled out from maven.
I've realized that the client may need to allow artifact fetching (online / offline mode) as well as order to flush caches before running the query. I changed the private API so that `DependencyQuery` object is now used as a parameter (+ added a `Builder` for it). Further extensions should be API-compatible.
Strangely enough, our infrastructure (?) …
> Maven / dependency query fixes.

- extide/gradle/nbproject/project.xml
- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
- extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java
- extide/gradle/src/org/netbeans/modules/gradle/api/GradleConfiguration.java
- extide/gradle/src/org/netbeans/modules/gradle/cache/ProjectInfoDiskCache.java
- extide/gradle/src/org/netbeans/modules/gradle/nodes/ConfigurationsNode.java
Added more information on configuration both to the UI and to the API. The API supports reading simplified configuration attributes which can be useful debugging variant matching.  Planning to support published artifacts and capabilities in upcoming PR-s.
> Add property sheet for Gradle Configuration nodes

- extide/gradle/src/org/netbeans/modules/gradle/GradleModuleFileCache21.java
Fix potential NPE in GradleModuleFileCache21 when trying to resolve non-gradle artifacts.
This is a patch for #4208
> Fix potential NPE in GradleModuleFileCache21 

- java/java.editor/src/org/netbeans/modules/java/editor/resources/DefaultAbbrevs.xml
- java/java.editor/test/qa-functional/data/goldenfiles/org/netbeans/test/java/editor/codetemplates/CodeTemplatesTest/testDumpTemplates.pass
old: 
```java
.toArray(new ${clazz}[${coll}.size()]);
```
new: 
```java
.toArray(new ${clazz}[0]);
```
see #3166 for details
would have been nice if the template would be able to conditionally generate the more modern version:
```java
.toArray(${clazz}[]::new);
```
> updated col.toArray() java editor template ("2ar").

- java/java.hints/src/org/netbeans/modules/java/hints/jdk/Bundle.properties
- java/java.hints/src/org/netbeans/modules/java/hints/jdk/CheckRegexTopComponent.form
- java/java.hints/src/org/netbeans/modules/java/hints/jdk/CheckRegexTopComponent.java
- java/java.hints/src/org/netbeans/modules/java/hints/jdk/RegexExampleGeneratorPanel.form
- java/java.hints/src/org/netbeans/modules/java/hints/jdk/RegexExampleGeneratorPanel.java
wanted to check out the new regex checker with a fairly long regex (output window exception matcher from #4180), but noticed that the text fields had all fixed sizes despite it being a top component.
So I tried to fix this first ;)
- everything resizes now properly (the example generator window too)
- added vertical splitter as bonus
- moved the error msg label a little bit around (try invalid regex)
- noticed that the form had a unused JFrame stored, removed that (might have been the first version of the RegexExampleGeneratorPanel)
before.
after:
@mishrasandeep what do you think?
> Regex checker UI improvements

- .github/workflows/main.yml
- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/MavenSkeletonProject.java
- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/VerifyLibsAndLicenses.java
- nbbuild/build.xml
Try to generate a maven multimodule pom from externals libraries located in nbbuild/build/mavenpoms.
remove getmavencoordinate I introduced a year ago to debug nb-repository
On this generated folder I tried
mvn org.owasp:dependency-check-maven:7.1.0:check it could works (api rate limitation) some blocker due to too old dep.
was thinking to push the pseudo maven project to https://github.com/apache/netbeans-temp and put a dependatbot on it.
> Try to generate maven project skeleton from our dependencies

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NetBeansRunSinglePlugin.java
- extide/gradle/src/org/netbeans/modules/gradle/GradleReport.java
While trying to work with the gradle projects from liferay-portal it
was observed, that loading failed with an exception. There are two
problems:
1. The liferay build provides incomplete implementation of JavaExec,
which do not support setting the standard input
2. The generated UnsupportedOperation exception carries a null message,
rendering the @NonNull annotation in GradleReport invalid and
causing NullPointerExceptions in use sites.
Fixes:
1. Setting stdin is changed to be a best-effort operation. It is
assumed that, if the setter fails, the access to stdin is not
expected and thus does not need to be wired.
2. If a null message is passed into GradleReport, it is replaced with
an empty string.
> Improve stability of gradle build info extraction

- harness/apisupport.harness/build.xml
- java/lib.jshell.agent/nbproject/project.properties
- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
- nbbuild/templates/common.xml
- platform/libs.asm/external/asm-9.3-license.txt
- platform/libs.asm/external/binaries-list
- platform/libs.asm/nbproject/project.properties
- platform/libs.asm/nbproject/project.xml
Library Notes:
- JDK 19 support
- Bug fixes
- 317949: fix javadoc errors
- remap invokedynamic field handles properly
- add missing left curly brace in ASMifier output of visitModule
Testing:
[ASM Web Page](https://asm.ow2.io/index.html)
[Release Notes](https://asm.ow2.io/versions.html)
> Update asm from 9.2 to 9.3

- ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/CodeTemplateInsertHandler.java
- attempting to open the next completion can cause problems if the
completion itself is not implemented properly (infinite completion
loops)
- to mitigate this we can check if the last removed group of the
template had "completionInvoke" set, so that for example constructor
completions still work as expected
follow up on #2519, #3290
**history:**
#2519 fixed a separate issue, but caused also a regression. #3290 attempted to restore the functionality (<12.3) without reverting #2519 but this could cause the above mentioned issue in some situations.
example for a completion which never finishes: #3805
example for completion chaining (intended behavior):
```java
// completion for:
new HashM
// would have the (dynamically generated) template:
"HashMap<>${cursor completionInvoke}"
// and would …
```
> safer auto completion chaining

- ide/api.debugger/src/org/netbeans/debugger/registry/DebuggerProcessor.java
- ide/api.debugger/src/org/netbeans/spi/debugger/ActionsProviderSupport.java
Small bugfix for the debugger annotation processor. There was a bug in `DebuggerProcessor`. If one used only `@ActionsProvider.Registrations` and no other annotations, the processor wasn't triggered. Extracted from #4196 as this is a non-controversial bugfix.
> Register @ActionsProvider.Registrations as annotation processed by DebuggerProcessor

- java/java.lsp.server/manifest.mf
- java/java.lsp.server/nbcode/integration/nbproject/project.xml
- java/java.lsp.server/nbproject/org-netbeans-modules-java-lsp-server.sig
- java/java.lsp.server/nbproject/project.properties
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeClientCapabilities.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/UIContext.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceUIContext.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractDialogDisplayer.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractLspHtmlViewer.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractLspStatusDisplayer.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/NotifyDescriptorAdapter.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/ui/AbstractDialogDisplayerTest.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/ui/MockHtmlViewer.java
Moving abstract class `UIContext` out of public package. It contains methods that use non API classes as parameter types (strange that `sigtest` did not complained), so it cannot be subclassed/implemented outside of the `java.lsp.module` anyway.
This is an attempt to fix problems mentioned in #4189
> Moving UIContext out of public package.

- ide/csl.api/test/unit/src/org/netbeans/modules/csl/api/test/CslTestBase.java
- ide/ide.kit/nbproject/project.properties
- ide/parsing.indexing/src/org/netbeans/modules/parsing/impl/indexing/PathRegistry.java
- java/java.hints/nbproject/project.properties
- nbbuild/templates/projectized.xml
lets see if this has any side effects, I didn't do a full test run yet, only checked few specific tests - CI will tell for sure.
edit:
holy bytecode batman! The **total** went down from >2h to <1h
before:
`PHP on ubuntu-20.04/JDK 8 succeeded in 2h 4m 24s `
after: 
`PHP on ubuntu-20.04/JDK 8 succeeded in 41m 53s`
GC tweaks result in small improvements too, observable when comparing travis time totals, see https://github.com/apache/netbeans/pull/4284#discussion_r907747129
commit msg:
- set event delay to 0
- tweak JVM settings a bit (little bit more heap, use throughput GC)
the event delay caused some tests to lose >1s per test method with CPU mostly
idling. Tests with a lot of cases were observed to complete 4-5x faster after
this tweak.
e.g: OccurrencesFinderImplTest: ~10 mins -> ~2 mins
> improve php test performance

- groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyParser.java
- groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/compiler/error/GroovyError.java
Sometimes the same error is reported from Groovy parser more times. This prevents processing such duplicated errors by our infrastructure.
> Preventing to create hints more times.

- webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/hints/JsConventionRule.java
- webcommon/javascript2.editor/test/unit/data/testfiles/hints/semicolonWarningGeneratedConstructor.js
- webcommon/javascript2.editor/test/unit/data/testfiles/hints/semicolonWarningRealConstructor.js
- webcommon/javascript2.editor/test/unit/data/testfiles/hints/semicolonWarningRealConstructor.js.testSemicolonWarningRealConstructor.hints
- webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/hint/JsConventionHintTest.java
For this construct:
class A {
}
class B extends A {
}
the graaljs parser generates the default constructor:
constructor(...args) {
super(...args);
}
This irritates the semicolon hint, as the token for the semicolon can't
be found and thus the hint is generated.
Closes: #4214
> JS: Don't generate hint for missing semicolon in generated constructor node

- apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/ExamineManifest.java
- ide/xsl/src/org/netbeans/modules/xsl/grammar/XSLGrammarQuery.java
- java/debugger.jpda.projects/src/org/netbeans/modules/debugger/jpda/projects/SourcePathProviderImpl.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchRequestHandler.java
- javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/completion/beans/BeanModelBuilder.java
- platform/openide.explorer/src/org/openide/explorer/DefaultEMLookup.java
- webcommon/javascript2.source.query/src/org/netbeans/modules/javascript2/source/query/SourceElementsQueryImpl.java
Cleanup references to the generic emptySet()..
[repeat] /home/bwalker/src/netbeans/enterprise/web.jsf/src/org/netbeans/modules/web/jsf/JSFConfigUtilities.java:250: warning: [rawtypes] found raw type: Set
[repeat]         Set result = Collections.emptySet();
[repeat]         ^
[repeat]   missing type arguments for generic class Set<E>
[repeat]     E extends Object declared in interface Set
---
Please make sure (eg. `git …
> Cleanup references to the generic emptySet()..

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java
On FlatLAF on Windows, improve vertical centering of labels in buttons. The solution was to make the buttons one pixel taller, as was done in the standard Swing Windows LAF.
See before/after screenshots below.
> Improve vertical centering of FlatLAF buttons on Windows

- java/java.hints/src/org/netbeans/modules/java/hints/errors/Utilities.java
- java/java.hints/src/org/netbeans/modules/java/hints/perf/Bundle.properties
- java/java.hints/src/org/netbeans/modules/java/hints/perf/Tiny.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/perf/TinyTest.java
* repurposed a dusty perf rule to suggest `Boxed.valueOf() -> Boxed.parseType()` refactoring where applicable
* added reverse case
* added rules for overloaded method variants
* extracted some functionality into a new rule which has the lone purpose to get rid of deprecated boxed primitive construction
* some rules overlapped with other inspections, removed those to keep things simple.
* this might mean however that some inspections have to be applied multiple times, since one fix could trigger another
example:
```java
private static void a(Integer i) {}
private static void b(String foo, int i) {}
private static void c(String foo, double a, long i) {}
public static void test() {
a(Integer.valueOf(""));                             // do nothing
b("abcd", Integer.valueOf("1")); …
```
> [jackpot] Updates to autoboxing inspections

- platform/autoupdate.cli/src/org/netbeans/modules/autoupdate/cli/Bundle.properties
- platform/autoupdate.cli/src/org/netbeans/modules/autoupdate/cli/ModuleOptions.java
- platform/o.n.bootstrap/src/org/netbeans/ModuleManager.java
The module system offers several options for module management. `--enable` option seems to work well, as it directly calls `ModuleManager.enable` and enables the requested modules (+ dependencies) on the fly. But `--disable` was implemented for some reason through delayed-disable, but **unlike** plugin UI, it will not generate the next-startup information files and does not request a restart: it seems broken. I filed [NETBEANS-6516](https://issues.apache.org/jira/browse/NETBEANS-6516) to track this,
Option that would **disable modules on the fly** is missing completely. This was removed from the UI, perhaps because **removing** code from the memory is hard: there may be half-linked dangling listeners etc. But the option processing happens during startup before the UI even appears, so it …
> Implemnted --direct-disable module option.

- .github/workflows/main.yml
- ide/ide.kit/nbproject/project.properties
- webcommon/web.inspect/src/org/netbeans/modules/web/inspect/ui/CssStylesPanelProviderImpl.java
- webcommon/web.inspect/src/org/netbeans/modules/web/inspect/ui/DomPanel.java
- webcommon/web.inspect/src/org/netbeans/modules/web/inspect/webkit/knockout/unused/UnusedBindingsPanel.form
- webcommon/web.inspect/src/org/netbeans/modules/web/inspect/webkit/knockout/unused/UnusedBindingsPanel.java
enable the xserver for the commit validation matrix.
- 19ea fails unfortunately, ~~so we switch it to 18 for now~~ don't enable the xserver there, issue filed: #4299
- fixed some NPEs in UI code which appear during CV test runs:
```
cat out.log | grep -A5 "because the return value of"
[junit] java.lang.NullPointerException: Cannot invoke "java.awt.Component.getBackground()" because the return value of "javax.swing.JViewport.getView()" is null
[junit] 	at org.netbeans.modules.web.inspect.ui.DomPanel.initNoDOMLabel(DomPanel.java:268)
[junit] 	at org.netbeans.modules.web.inspect.ui.DomPanel.<init>(DomPanel.java:96)
[junit] 	at org.netbeans.modules.web.inspect.ui.DomTC.update(DomTC.java:85)
[junit] 	at org.netbeans.modules.web.inspect.ui.DomTC.<init>(DomTC.java:75)
[junit] 	at …
```
> ci xserver for commit validation matrix

- apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/ExamineManifest.java
- enterprise/glassfish.eecommon/src/org/netbeans/modules/glassfish/eecommon/api/ProgressEventSupport.java
- enterprise/payara.eecommon/src/org/netbeans/modules/payara/eecommon/api/ProgressEventSupport.java
- ide/api.debugger/src/org/netbeans/api/debugger/DebuggerManager.java
- ide/api.debugger/src/org/netbeans/spi/debugger/ActionsProviderSupport.java
- ide/bugtracking/src/org/netbeans/modules/bugtracking/RepositoryImpl.java
- ide/editor.settings.lib/src/org/netbeans/modules/editor/settings/storage/StorageImpl.java
- ide/spi.debugger.ui/src/org/netbeans/modules/debugger/ui/DebuggerManagerListener.java
- java/ant.debugger/src/org/netbeans/modules/ant/debugger/CallStackModel.java
- java/ant.debugger/src/org/netbeans/modules/ant/debugger/VariablesModel.java
- java/ant.debugger/src/org/netbeans/modules/ant/debugger/WatchesModel.java
- java/ant.debugger/src/org/netbeans/modules/ant/debugger/breakpoints/BreakpointModel.java
- java/debugger.jpda.projects/src/org/netbeans/modules/debugger/jpda/projects/SourcePathProviderImpl.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchRequestHandler.java
- javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/completion/beans/BeanModelBuilder.java
- platform/core.windows/src/org/netbeans/core/windows/persistence/ModeParser.java
- platform/openide.explorer/src/org/openide/explorer/DefaultEMLookup.java
- platform/openide.explorer/src/org/openide/explorer/propertysheet/RadioInplaceEditor.java
- platform/openide.util/src/org/openide/util/Task.java
- webcommon/javascript2.source.query/src/org/netbeans/modules/javascript2/source/query/SourceElementsQueryImpl.java
Use the copy constructor when that is all one needs. Avoid using reflection and creating a clone as it can be expensive.
Warnings like this are cleaned up..
```
[repeat] /home/bwalker/src/netbeans/platform/openide.nodes/src/org/openide/nodes/Children.java:1783: warning: [rawtypes] found raw type: Dupl
[repeat]                 Dupl d = (Dupl) this.clone();
[repeat]                 ^
[repeat]   missing type arguments for generic class Dupl<T>
[repeat]     T extends Object declared in class Dupl
```
Also, cleanup some improper usage of emptyList() and it's friends.
---
- are all your own work, and you have the right to …
> Use the copy constructor when that is all one needs.

- ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/LanguageClientImpl.java
While working with a typescript project, I multiple times copied files,
renamed, edited and closed them. I noticed, that I got a
NullPointerException from the LanguageClientImpl:
```
java.lang.NullPointerException: Cannot invoke "org.openide.filesystems.FileObject.getLookup()" because "file" is null
at org.netbeans.modules.lsp.client.bindings.LanguageClientImpl.publishDiagnostics(LanguageClientImpl.java:161)
Caused: java.lang.reflect.InvocationTargetException
at jdk.internal.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65) …
```
> LSPClient: Don't assume URL -> FileObject mapping exists

- php/php.editor/src/org/netbeans/modules/php/editor/CodeUtils.java
Create following PHP class and open it in NetBeans (current master branch):
```php
class ConstantArrayAccess {
private const NUMBER_TO_NAME_MAP = [3 => 'three'];
public function getName($number) {
$name = self::NUMBER_TO_NAME_MAP[$number];
return $name;
}
}
```
Following exception appears:
<details>
<summary>Exception stack trace</summary>
```
java.lang.AssertionError: class org.netbeans.modules.php.editor.parser.astnodes.ExpressionArrayAccess
at org.netbeans.modules.php.editor.CodeUtils.extractQualifiedName(CodeUtils.java:312)
at org.netbeans.modules.php.editor.model.impl.VariousUtils.extractVariableTypeFromVariableBase(VariousUtils.java:1153)
at org.netbeans.modules.php.editor.model.impl.VariousUtils.extractTypeFroVariableBase(VariousUtils.java:208)
at …
```
> Fixes unhandled ExpressionArrayAccess in PHP Editor

- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-2.3-license.txt
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
Update FlatLaf to v2.3.
Changes:
- https://github.com/JFormDesigner/FlatLaf/releases/tag/2.2
- https://github.com/JFormDesigner/FlatLaf/releases/tag/2.3
Selected tab underline color now changes depending on whether the focus is within the tab content
(left is focused, right is not focused):
The new color can be changed by setting UI value `TabbedPane.inactiveUnderlineColor`.
`This PR changes it to the same color used for editor and view tabs.
This release adds a shortcuts panel to the left side of all file choosers (class `JFileChooser`):
On Windows, the content of the shortcuts panel is the same as in the Java Windows L&F.
On macOS and Linux the shortcuts panel is empty and hidden.
> Update FlatLaf from 2.1 to 2.3

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/DPISafeBorder.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLightLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/HiDPIUtils.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatEditorTabCellRenderer.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatEditorTabDisplayerUI.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatViewTabDisplayerUI.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/Utils.java
This PR is a follow-up to https://github.com/apache/netbeans/pull/4286 , adding visual improvements and new configuration options for FlatLAF. Before/after screenshots (open in separate tabs at 1:1 device pixel scaling to see details):
This PR (along with [Neil's PR earlier today](https://github.com/apache/netbeans/pull/4286)) replaces https://github.com/apache/netbeans/pull/3115 , except for the improvements relating to vertical alignment of tab labels, which I will put into a separate PR later. Much of the code here is adapted from improvements that were first merged into the [Windows LAF](https://github.com/apache/netbeans/pull/2967).
Visual improvements, annotated in the screenshot above:
1) Align and connect borders between tabs and the container panel below, including on fractional …
> FlatLAF improvements and new configuration properties

- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
- java/java.source.base/src/org/netbeans/api/java/source/ElementUtilities.java
- java/java.source.base/test/unit/src/org/netbeans/api/java/source/ElementUtilitiesTest.java
fixes #4140
`ElementUtilities.getMembers()`, `getLocalMembersAndVars()`, `getLocalVars()` and `getGlobalTypes()` performance optimization.
- optimization was contributed by @notzed, see NETBEANS-6504 or #4140
- only minor changes were made from the proposed patch
This significantly improves auto completion performance on types with thousands of fields. 
example: https://github.com/apache/netbeans/issues/4140#issuecomment-1134414691 completion takes several seconds to show up before patch, after patch it shows up instantly.
Since `ElementUtilites` has many usages across NetBeans, this could potentially improve performance in other places too.
First commit is the interesting one, other is cleanup. I added tests and made sure they were green before and after patch. Its already squashed in …
> ElementUtilities performance optimization.

- .github/workflows/main.yml
The new and more secure [job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) feature might be our way out of #4116
confirmed:
```
Error: .github#L1
test-summary/action@v1 is not allowed to be used in apache/netbeans. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, …
```
> ci test reports via gh job summaries

- platform/o.n.swing.laf.flatlaf/nbproject/project.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatEditorTabCellRenderer.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatEditorTabDisplayerUI.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatTabControlIcon.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatViewTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/apichanges.xml
- platform/o.n.swing.tabcontrol/manifest.mf
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/AbstractTabCellRenderer.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/AbstractViewTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/BasicScrollingTabDisplayerUI.java
This PR makes the window system tab labels align with the icon and the "X" button, with any font and at any font size.
The font-agnostic calculation is useful because FlatLAF uses a different UI font on each OS. Accurate vertical alignment also allows more compact tab styles if desired in the future.
Details:
* API change: Allow AbstractTabCellRenderer subclasses to override text position calculation.
* In FlatLAF, improve the calculation of tab labels' Y position, to avoid the need for ad hoc adjustments and to work with a variety of font families and font sizes. Ensure that text in view tabs and editor tabs still line up.
* In FlatLAF, ensure a minimum tab height for smaller fonts, based on the expected icon size, regardless of inset settings. This will allow the same inset settings to …
> Improve alignment of text and "X" button in FlatLAF window system tabs

- java/java.navigation/src/org/netbeans/modules/java/stackanalyzer/AnalyserCellRenderer.java
- java/java.navigation/src/org/netbeans/modules/java/stackanalyzer/AnalyzeStackTopComponent.java
- added indentation for more familiar stack trace formatting
- fixed hyperlink text color when selected
- fixed TopComponent background color to be consistent with other  windows
The top component was a little bit too bright with dark theme (looked like the old color of the NB 14 dark theme and didn't fit to the rest)
Projects tab is: `#3C3F41`, Analyze Stack window was: `#46494B`, so i set it to `UIManager.getColor("Tree.background")` which is the same as the other top components (e.g projects tab).
> Analyze Stack Trace window improvements.

- java/maven/src/org/netbeans/modules/maven/newproject/idenative/IDENativeMavenWizardIterator.java
fixes #4343
- the groupId text field was ignored so far
- this fixes a bug which breaks the project if no package is provided
(since the package is used as fallback to generate a groupId which hid the issue)
(artifactId is only set for completes sake)
> maven project wizard should set groupId #4343.

- java/java.editor/src/org/netbeans/modules/java/editor/javadoc/JavadocCompletionTask.java
- java/java.editor/test/unit/src/org/netbeans/modules/java/editor/javadoc/JavaDocCompletionTaskTest.java
Provide hints for markup tags in inline snippets. Below is the screenshot for the feature
> Add markup tag completion hints for inline snippets

- cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/CPPLiteDebugger.java
- cpplite/cpplite.debugger/src/org/netbeans/modules/cpplite/debugger/utils/InputStreamWithCloseDetection.java
- cpplite/cpplite.debugger/test/unit/src/org/netbeans/modules/cpplite/debugger/OutputTest.java
- ide/extexecution.base/src/org/netbeans/modules/extexecution/base/ProcessInputStream.java
- ide/extexecution.base/src/org/netbeans/modules/extexecution/base/input/DefaultInputReader.java
When debugging a native application, not all output is visible after the application exits when the output is produced just before the exit.
The reason was that the `pty` process was closed right after `gdb` finished.
This change assures that the application output from `pty` process is fully read and that the debugging does not finish sooner than all output is provided.
An `OutputTest` is added.
> Output from pty is fully read after debugger exit.

- groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/api/parser/GroovyVirtualSourceProvider.java
This error can be reproduced i.e. on `micronaut-core/http` project; the project mixes Groovy + Java sources. Java references Groovy classes, so our `GroovyVirtualSourceProvider` generates a java stub source during indexing, so Java indexer is happy and can resolve the class' symbols.
But it seems that the stub generator stops at 1st level of type parameters and does not print potential type parameters of the actual type parameter(s). So instead of `Map<String, Map<String, ClassNode>>` it prints just `Map<String, Map>`. Javac will then complain about usage of such (incompatible) type in the java source which expects the correct one.
The fix is simple: recursively print the complete type incl. parameters and bounds.
> Recursively print type parameter's type parameters.

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
- extide/gradle/src/org/netbeans/modules/gradle/cache/ProjectInfoDiskCache.java
- java/gradle.java/apichanges.xml
- java/gradle.java/manifest.mf
- java/gradle.java/src/org/netbeans/modules/gradle/java/api/GradleJavaProjectBuilder.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/api/GradleJavaSourceSet.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceForBinary.java
In a mixed-language project, such as `micronaut-core/http`, each language produces the output typically to a separate folder, although the output is in form of .class files.
Currently Gradle project knows the set of output folders, but does not know what language produces output in which particular one, so backwards mapping in `SourceForBinaryQuery` provides **all source folders**, which is not correct.
In addition, the result of SFBQ query in Gradle/java says that sources should be always preferred. This is fine in theory, but java uses (exclusively) its cached indexed folders instead of the real output folders - so it is able to react on editing changes even before they are compiled. But other languages behave differently.
These two things in effect lead to spurious "undersolved symbol" …
> Allow to find precise output folder for each language.

- extide/gradle/apichanges.xml
- extide/gradle/manifest.mf
- extide/gradle/src/org/netbeans/modules/gradle/api/NbGradleProject.java
- extide/gradle/src/org/netbeans/modules/gradle/problems/ChangeOrRemovePropertyResolver.java
- extide/gradle/src/org/netbeans/modules/gradle/problems/GradlePropertiesEditor.java
- extide/gradle/src/org/netbeans/modules/gradle/problems/PropertiesEditor.java
- extide/gradle/src/org/netbeans/modules/gradle/problems/ProxyAlertProvider.java
Proxy settings is one of the very unpleasant parts of Gradle: normal tools tend to honour environment variables, but Gradle knows better: only respects its own settings, either in the project, or in the `~/.gradle/gradle.properties`.
This PR processes `GradleReport`s produced after project (re)load. It detects some (not all!) typical situation - the number of matches may expand:
- Connection timeout because of gradle attempting to connect directly from a corporate network that requires proxy
- Connection exception to a configured proxy that no longer works (other proxies, or a no proxy at all)
IDE settings are used to 'autodetect' the valid proxy settings, I used a well-known root DNS `8.8.8.8` that everyone should have route to.
Gradle project offer fix that will alter the .properties …
> Detect proxy issues and offer fixes.

- java/java.completion/nbproject/org-netbeans-modules-java-completion.sig
- java/java.completion/src/org/netbeans/modules/java/completion/JavaCompletionTask.java
- java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionCollector.java
- java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionItem.java
- java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionItemFactory.java
- java/java.source.base/src/org/netbeans/api/java/source/GeneratorUtilities.java
- java/java.source.base/src/org/netbeans/api/java/source/TreeMaker.java
- java/java.source/src/org/netbeans/modules/java/source/package-info.java
- java/java.source/src/org/netbeans/modules/java/source/resources/LambdaExpression.template
- java/java.source/src/org/netbeans/modules/java/source/resources/layer.xml
- platform/api.templates/arch.xml
Adds a completion item for inserting lambda expressions.
```java
Stream.of().filter();                // cursor between ()
Stream.of().filter((t) -> false);    // generated with new expression completion
Stream.of().filter((t) -> {          // old block completion item remains available
return false;
});      
```
edit:
it works but it has a problem: user changing the template could easily break the code responsible to mark the replacement String with `${...}` to make the generated code tab-navigatable.
https://user-images.githubusercontent.com/114367/174423136-45b86da0-04ff-4c83-9f96-a21c092fcc22.mp4
> lambda expression completion support.

- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Add entry to the `OFFICIAL_JAVADOC` Map for Java 20
- https://download.java.net/java/early_access/jdk20/docs/api/
> Add javadoc for JDK 20 early access

- ide/editor.actions/src/org/netbeans/modules/editor/actions/ShowInlineHintsAction.java
- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/DocumentViewOp.java
Whenever I see people using other IDEs, they have _inline hints_ enabled and find it quite useful. Thanks to @jlahoda work NetBeans also supports _inline hins_ and I am using them without any major problems for last few releases. However the feature is turned off by default and I am afraid many users of NetBeans IDE do not even know it exists. This PR proposes to turn the feature on by default.
> Enable inline hints by default

- java/form/src/org/netbeans/modules/form/project/ClassSource.java
addToProjectClassPath() would fail later with a less useful stacktrace as observed in #4365.
(this doesn't really fix a bug, defensive checks make finding bugs a bit easier)
> Let ClassSource check for null elements in constructor.

- enterprise/micronaut/src/org/netbeans/modules/micronaut/hyperlink/MicronautConfigHyperlinkProvider.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/hyperlink/MicronautJavaHyperlinkProvider.java
The relevant stacktraces for the affected threads are saved below.
As there is also a warning logged with a clear indication:
>  WARNING [org.netbeans.modules.parsing.impl.TaskProcessor]: ParserManager.parse called in AWT event thread by:
org.netbeans.modules.micronaut.hyperlink.MicronautJavaHyperlinkProvider.getPropertyName(MicronautJavaHyperlinkProvider.java:151)
Stacktraces:
```
"AWT-EventQueue-0" #24 prio=6 os_prio=0 cpu=69156.33ms elapsed=76496.39s tid=0x00007feca4122b90 nid=0x106e2a waiting on condition  [0x00007fec9756e000]
java.lang.Thread.State: WAITING (parking)
at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
- parking to wait for  <0x00000006d7905fd0> (a java.util.concurrent.locks.ReentrantLock$FairSync)
at …
```
> [GITHUB-3913] Disable Micronaut HyperlinkProviders to prevent deadlock

- java/api.debugger.jpda/src/org/netbeans/api/debugger/jpda/Bundle.properties
- java/form/src/org/netbeans/modules/form/Bundle2.properties
- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/DefaultPlatformImpl.java
- /usr shouldn't be a valid path for the default JDK
- use java.home if jdk.home/bin/java is a symlink
- updated some related warning messages
- fixes #4365
NB can't actually be started on a "JRE" (whatever a JRE is these days since it isn't well defined anymore). However, the "default jdk" path could be invalid still which will cause trouble at runtime. (looking at you, installer)
e.g trying to run NB on a "JRE" fails early so we don't have to worry about this scenario (at least not for the IDE):
```
./netbeans 
Error occurred during initialization of boot layer
java.lang.module.FindException: Module jdk.jshell not found
```
> use java.home as "default jdk" if jdk.home leads to symlinks.

- extide/gradle/src/org/netbeans/modules/gradle/GradleProject.java
- extide/gradle/src/org/netbeans/modules/gradle/GradleReport.java
It's getting somewhat usual to have project without root build.gradle (or build.gradle.kts) script, only a settings.gradle in the root.
That setup is completely valid, though it could cause NPE-s. This trivial patch fixes that.
> Fix NPE when there is no build.gradle for the root project

- ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlKeystrokeHandler.java
- ide/languages.yaml/test/unit/src/org/netbeans/modules/languages/yaml/YamlKeystrokeHandlerTest.java
Further improve the work done in #4093. Made it more consistent. As both '{}' and '[]' are language elements Pressing ```{``` or ```[``` would create the closing pair as well.
As quotes are created (usually) in pairs as well, pressing quote for a closing quote would step over the existing quote, instead of inserting another pair. So those who usually type two quotes fast, won't get annoyed.
> Improved YAML curly, bracket and quotes keystroke handling

- platform/openide.util/test/unit/src/org/openide/xml/XMLUtilTest.java
methods with 100% coverage:
toElementContent - found 1 redundant 'if' statement which always evaluates true
findSubElement
appendChildElement
copyDocument - found 1 redundant 'if' statement which always evaluates true
toAttributeValue
checkContentCharacters
findElement
fromHex
checkAttributeCharacter
toHex
findText
> added tests to org.openide.util.xml.XMLUtil:

- extide/gradle/apichanges.xml
- extide/gradle/manifest.mf
- extide/gradle/src/org/netbeans/modules/gradle/GradleReport.java
- extide/gradle/src/org/netbeans/modules/gradle/nodes/BuildScriptsNode.java
- extide/gradle/src/org/netbeans/modules/gradle/spi/GradleFiles.java
Implement minimal support for #4337. The libs.versions.toml file will be displayed under the build scripts node.
> Add minimal support for Gradle default version catalog

- php/languages.neon/src/org/netbeans/modules/languages/neon/resources/FontAndColors-FlatLafDark.xml
- php/languages.neon/src/org/netbeans/modules/languages/neon/resources/layer.xml
Changed colors of valued block, reference and number to improve legibility when using FlatLaf Dark color profile.
Before:
After:
> NEON - added FlatLaf Dark specific colors to improve legibility

- java/refactoring.java/src/org/netbeans/modules/refactoring/java/callhierarchy/Call.java
For description, see #4366 
It **was** actually a one-liner ... The problem was that Trees.getPath() won't work outside of compilation units processed by the parser - but TreePathHandle.create/from() can process any element, so I've used that as a fallback.
> #4366: Handle references to other compilation units.

- java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
The following exception appears in the log when one tries to `Attach Sources` and uses `Download`:
```
java.lang.NullPointerExceptionjava.lang.NullPointerException 
at org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl.constructQuery(NexusRepositoryIndexerImpl.java:1154)
at org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl.findBySHA1(NexusRepositoryIndexerImpl.java:1279)
at org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl.findBySHA1(NexusRepositoryIndexerImpl.java:1272)
at org.netbeans.modules.maven.indexer.api.RepositoryQueries.lambda$findBySHA1$6(RepositoryQueries.java:357)
at org.netbeans.modules.maven.indexer.api.RepositoryQueries.getQueryResult(RepositoryQueries.java:217)
at org.netbeans.modules.maven.indexer.api.RepositoryQueries.findBySHA1(Reposit …
```
> Let iterate() initialize the indexer first.

- ide/extexecution.base/src/org/netbeans/api/extexecution/base/BaseExecutionService.java
- java/maven/src/org/netbeans/modules/maven/execute/CommandLineOutputHandler.java
Since JEP400/JDK18 `Console.charset()`/`stdout.encoding`/`sun.stdout.encoding` is used by default for the console's encoding. Prior to this it was `Charset.defaultEncoding()`/`file.encoding`.
This PR changes the order the encoding is inferred by to accomodate for this behavior.
This should fix #3824 as well as #4261.
As `stdout.encoding`/`sun.stdout.encoding` is settable, in the rare case that the default value should not match the desired Output encoding it can be changed via the corresponding commandline argument.
Please see [this comment](https://github.com/apache/netbeans/issues/4261#issuecomment-1185669743) by @neilcsmith-net for further details
[Requested via](https://lists.apache.org/thread/pzv6899dn4w2syo6dk400qc3n9wr6slf)
> Change output encoding fallback behavior to account for JEP400

- java/java.source.base/src/org/netbeans/modules/java/source/parsing/PatchModuleFileManager.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/parsing/PatchModuleTest.java
Consider a binary library with an attached source. When opening a source file for the library, if the library is non-modular, the binary will be on the classpath, and the source will be able to refer to it. When the library is modular, javac will not look at the classpath anymore, but will try to lookup module-info and other dependencies on source and output path. So, we need to make sure the output path contains the binary library, so that the lookups work. This is what this patch is trying to achieve.
---
- are contributed solely under the terms and conditions of the Apache License 2.0 (see …
> [NETBEANS-4044] Fixing patching of modular libraries

- apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/MavenPackageModifierImpl.java
trying to fix #4326
try the different groupid for nbm-maven-plugin to reuse the current one in pom. If none exists create plugin section using the new groupId
> reuse existing nbm maven plugin to export package

- java/java.source.base/src/org/netbeans/modules/java/source/parsing/PatchModuleFileManager.java
Fix #4411 - protect against NPE by ensuring moduleLocations is initialized in PatchModuleFileManager::fixLocation.
I think this is the right approach rather than bailing on null.  At least, every other use in that class is via the initializing method.
> Fix #4411 - ensure moduleLocations is initialized.

- nbbuild/build.xml
Removed this target as I though it was no more used but it allow to shorten the external artefacts
> reintroduce getallmavencoordinates

- java/java.source.base/src/org/netbeans/modules/java/source/base/SourceLevelUtils.java
- java/java.source.base/src/org/netbeans/modules/java/source/parsing/JavacParser.java
I have a project that is using `record` heavily, but still compiles to old JDKs. When I run NetBeans on JDK-8 everything is OK, but when I run them on JDK-11 I get an error:
My project consists of a `pom.xml` file requesting `source` `18`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>org.netbeans.test</groupId>
<artifactId>userecords</artifactId>
<packaging>jar</packaging>
<version>1.0-SNAPSHOT</version>
<build>
<plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId> …
```
> Using record construct on JDK-11 yields an error in the editor

- ide/libs.c.kohlschutter.junixsocket/nbproject/project.properties
junixsocket loads by default the native library using System#loadLibrary
so the native libraries only need to be placed in the
modules/lib/\<arch>/\<os>
folders, so that they can be loaded directly with the requirement to
expand them and load them from java.io.tmpdir.
Closes: #4393
> Enable direct loading of native library for junixsocket instead of loading from temp

- ide/versioning.ui/src/org/netbeans/modules/versioning/ui/history/HistoryFileView.java
- ide/versioning.ui/src/org/netbeans/modules/versioning/ui/history/HistoryRootNode.java
Hello! This PR fixes issues #4367 and #4394.
> Fixed issues in history view

- php/php.code.analysis/src/org/netbeans/modules/php/analysis/ui/options/Bundle.properties
Use configuration file "phpstan.dist.neon" instead of "phpstan.neon.dist" because the former is opened as NEON file in NetBeans.
Both configuration files are supported by PHPStan. See https://phpstan.org/config-reference#config-file
Fixes #4426
> PHPStan - fixes typo in config panel and updates config file name

- java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleSourceForBinary.java
> Fix Gradle Source4Binary always returns with resources location.

- java/java.hints/src/org/netbeans/modules/java/hints/bugs/Unbalanced.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/UnbalancedTest.java
- we can make this work for final fields, non-final fields would
be more complicated [explained here](https://github.com/apache/netbeans/issues/4402#issuecomment-1192312559)
- added missing methods to READ_METHODS set
fixes #4402
> Unbalanced hint should work for fields initialized in constructor

- extide/gradle/src/org/netbeans/modules/gradle/loaders/DiskCacheProjectLoader.java
- extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleProjectLoaderImpl.java
This patch treats the on-dosk Gradle cache data as EVALUATED even if invalid. Usually there is a good chance that the information there is still better, than we can get from the heuristics.
This one would make ```ClassPathProviderImplTest.testCompilePreTrusted``` happy.
I hope this is not too late for NB15. Please review!
> Treat Gradle disk cache at least as evaluated.

- platform/janitor/src/org/netbeans/modules/janitor/Janitor.java
- platform/janitor/src/org/netbeans/modules/janitor/JanitorPanel.form
- platform/janitor/src/org/netbeans/modules/janitor/JanitorPanel.java
Small patch makes the Janitor messages on removing 'NetBeans version 64' a bit more descriptive.
> Better messages from Janitor on abandoned cache dirs.

- extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProject.java
Well, this is a bit oversight with the recent changes around how we handle configurations in Gradle. We started to include non-resolvable configurations in the IDE around NetBeans 14. That would give better information available, however no matter what the Configurations node would display a warning badge about there are some configurations left to be unresolved.
It turned out that we forgot to filter the non-resolvable configurations out of the configurations when we are checking whether a configuration is resolved or not.
Would be a nice trivial fix for NB15, However I hope there would be no more RC-s there.
> Gradle project reports unresolved configurations.

- java/java.hints/src/org/netbeans/modules/java/hints/bugs/Unused.java
based on delivery for the slim chance that this gets a review
- streams are not very good at canceling
- by using a plain loop we can simply break out of it
- further: `findUnused` is actually very fast, `convertUnused` is the slow part and wasn't cancelable before, the original code might have worked if `findUnused` returned a stream instead of a list and everything would be one pipeline (this would make the fix more complicated)
issue:
- a synthetic file with 10k fields pins a thread for about 20s
at 100%
- most editor features don't work during that time, e.g completion
- hint is enabled by default
discussion:
noticed this while benchmarking other issues (#4500)
#3886 mentioned the poor performance of `org.netbeans.modules.java.hints.bugs.Unused` and also that it isn't cancelable. …
> org.netbeans.modules.java.hints.bugs.Unused doesn't cancel properly

- nb/ide.branding/o.n.core/src/org/netbeans/core/Bundle_nb.properties
- platform/o.n.core/src/org/netbeans/core/Bundle.properties
- platform/o.n.core/src/org/netbeans/core/NotifyExcPanel.java
- platform/openide.dialogs/src/org/openide/NotifyDescriptor.java
We see users periodically reporting issues for old NB versions (e.g #4477 + discussion). So I wanted to see if the messaging could be a little bit improved.
It turned out that the exception reporter was a little bit broken, the message didn't fit into the window and it had no scrollbars, so the user would only see part of it.
related update to website:
- https://github.com/apache/netbeans-website/pull/603
this PR:
- improved the messages
* emphasized latest release requirement
* switched text to html
* added hyperlinks which open the issue page/log folder (having long URIs in wrapping/scrolling text is annoying)
- wrapped TextArea of NotifyDescriptor into a ScrollPane
- switched stack trace pane (show details) to TextArea and disabled line wrap
- slightly larger dimensions for everything
> Exception reporter improvments

- .github/workflows/main.yml
add `base_ref` to the group key so that two parallel branch sync PRs won't cancel each other
> fix CI concurrency settings

- ide/api.debugger/src/org/netbeans/api/debugger/ActionsManager.java
Well, last week I had a chance to spend a few hours debugging the ActionsManager in the debugger API.
It was not a delightful experience. The code was written in ancient Java, sometimes it was hard to find out what does it want to do. So for make the debugging work easier, I've translated some of those ancient Java to a bit modern dialect.
After all I've found a small bug at https://github.com/apache/netbeans/blob/06a31ed66a97a0be7c9c9fe2a2fc0477f7b7e8b9/ide/api.debugger/src/org/netbeans/api/debugger/ActionsManager.java#L317 where the case ```p1.equals(p2)``` was not handled well. But that it is easy to avoid to hit that codepath, so I did so in #4442, so the fix in the ActionManager was not required.
In order my translation efforts on the ActionsManager not to be vain, I've finished the …
> Modernize ActionsManager in Debugger API

- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/commands/Utils.java
When passing a file path as a plain string to the command, the `URI.toURL()` throws `IllegalArgumentException` that was not caught, and the fallback path (interpreting the string as file path) was not executed.
> Accept file paths passed as a plain string, toURL throws IAE.

- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/OrganizeImportsTest.java
- java/java.source.base/src/org/netbeans/api/java/source/GeneratorUtilities.java
Running `Organize Imports` action on the following source code removes the necessary import for `java.util.List`
```
package javaapplication;
import java.awt.*;
import java.util.List;
import java.util.*;
public class JavaApplication {
List a;
Map m;
AWTEvent e;
}
}
```
This PR should fix this problem.
> OrganizeImports fixed for clashing star imports.

- ide/docker.editor/nbproject/project.xml
- ide/docker.editor/src/org/netbeans/modules/docker/editor/DockerfileLanguage.java
- ide/docker.editor/src/org/netbeans/modules/docker/editor/DockerfileResolver.java
- ide/docker.editor/src/org/netbeans/modules/docker/editor/layer.xml
I've been missing the History view on Dockerfile-s for a long time. This one adds that.
Also moved the action registration out of ```layer.xml``` which would remove the always disabled ```Add...``` menu item from the popup.
> Added multiview [Source|History] for Dockerfile-s

- java/maven/src/org/netbeans/modules/maven/NbMavenProjectImpl.java
Minor bugfix: when loading a Maven project, the `ProjectActionContext`'s project action should be included in the cache hash, as it may (through RunConfig) goals and properties of the maven project.
With this bug, query for native-build and build will return the same artifact or even null (if the build query is first, the cached project is not native-image-packaged).
> Build action must be included in the cache key

- extide/gradle/src/org/netbeans/modules/gradle/api/NbGradleProject.java
- extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDistributionProviderImpl.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/ClassPathProviderImpl.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/classpath/GradleSourcesImpl.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/nodes/SourcesNodeFactory.java
When added the support of Generated source directories in Gradle project, the project view become a bit crowded, as the generated folders are always generated by Gradle.
Here there are two empty folder one for java and one for groovy.
Same project with the new code.
While implementing the change, I discovered a bug which prevented the freshly opened project to listen on resource changes. That one is the fist commit.
> Gradle hide empty generated folders

- enterprise/web.jspparser/src/org/netbeans/modules/web/jsps/parserapi/PageInfo.java
- ide/xml.catalog.ui/src/org/netbeans/modules/xml/catalog/CatalogNode.java
- ide/xml.catalog.ui/src/org/netbeans/modules/xml/catalog/CatalogRootNode.java
- ide/xml.core/src/org/netbeans/modules/xml/dtd/grammar/DTDParser.java
- ide/xml.tax/src/org/netbeans/modules/xml/tax/beans/editor/TreeNodeFilterCustomEditor.java
- ide/xsl/src/org/netbeans/modules/xsl/grammar/XSLGrammarQuery.java
- java/ant.debugger/src/org/netbeans/modules/ant/debugger/RunTargetsAction.java
- platform/openide.filesystems/src/org/openide/filesystems/DefaultAttributes.java
Cleanup a bunch of raw type error messages related to TreeSet. Issues like these..
[repeat] /home/bwalker/src/netbeans/enterprise/web.core.syntax/src/org/netbeans/modules/web/core/syntax/JspSyntaxSupport.java:512: warning: [unchecked] unchecked call to addAll(Collection<? extends E>) as a member of the raw type TreeSet
[repeat] ts.addAll(mapper.keySet());
[repeat] ^
[repeat] where E is a type-variable:
[repeat] E extends Object declared in class TreeSet
--- …
> Cleanup a bunch of raw type error messages related to TreeSet.

- ide/editor/src/org/netbeans/modules/editor/NbEditorDocument.java
This is a trivial one. I've found it debugging the editor infrastructure.
The mentioned issue is here: https://bz.apache.org/netbeans/show_bug.cgi?id=222763
> Cleanup debug Exception after an old issue

- java/java.lsp.server/vscode/src/extension.ts
NBLS Java should be disabled for GCN users when RH Java support is present.
> Automatically disable NBLS Java for GCN users.

- extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectFactory.java
- extide/gradle/src/org/netbeans/modules/gradle/spi/GradleFiles.java
- extide/gradle/test/unit/src/org/netbeans/modules/gradle/NbGradleProjectFactoryTest.java
- java/maven/src/org/netbeans/modules/maven/NbMavenProjectFactory.java
A multiproject build looks, [according to the documentation](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:creating_multi_project_builds) like
```
├── app
│   ...
│   └── build.gradle
└── settings.gradle
```
there's no `build.gradle` in the root. While `GradleFiles.isSubProject` already works OK with build-less projects, the `isRootProject` does not. This PR fixes that. Simple test added.
During other work, I've realized that the `ProjectFactory2` implementation for both Gradle and Maven do not return project type -- although they could. The display name is not that easy to evaluate, but both project types use a fixed ID, so it's simple to return.
> Support projects without build.gradle

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/project/LspProjectInfo.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
LSP client may need some project structure information. This PR exposes basic info on a project on the LSP protocol.
```
nbls.project.info(locations : String | String[], options? : { projectStructure? : boolean; actions? : boolean; recursive? : boolean }) : LspProjectInfo[]
```
The command accepts one or more locations as URIs (vscode.Uri.toString() for example); it will return, for each input parameter, a structure that describes the project and its direct children (if requested). If `recursive` is true, additional entries will be provided for each identified child project, recursively.
> Project info exported through LSP

- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/DocumentViewOp.java
Kind of trivial fix for a rare ```IllegalArgumentException```. There is a small chance that it would result an ```NPE``` later in the code, though as far as I've checked the call stack in #3732 the return value of ```createTextLayout(String text, Font font)``` stored, and when later retrieved it is checked for null.
> FIX-3732: Prevent possible IAE in DocumentViewOp.

- .github/ISSUE_TEMPLATE/netbeans_bug_report.yml
Make Apache NetBeans 15 the latest version in the template for bug reports.
> Make Apache NetBeans 15 the latest version for issue reports.

- .travis.yml
- ide/c.jcraft.jsch/build.xml
- platform/netbinox/nbproject/project.properties
- platform/netbinox/nbproject/project.xml
- platform/netbinox/src/org/netbeans/modules/netbinox/JarBundleFile.java
- platform/netbinox/src/org/netbeans/modules/netbinox/NetbinoxLoader.java
- platform/netbinox/test/unit/src/org/netbeans/modules/netbinox/NetbinoxMultiversionJarTest.java
- platform/o.n.bootstrap/src/org/netbeans/JarClassLoader.java
- platform/o.n.bootstrap/test/unit/src/org/netbeans/JarClassLoaderTest.java
This is an enhanced version of #3860, which implements support for multi-release jars for the JarClassLoader and the Equinox based OSGI integration.
Changes compared to the original PR:
- prevent unnecessary reads from original JAR (JAR content is cached and should be used at startup)
- use descending order for versions in `getVersions`, so that implementations for newer VMs are preferred and move runtime version limitation there
- add support for multi-release jars to NetBinox classloader by using the idea from `JarFile`, where the versioning aspect of class loading is handled below the classloader level and for NetBinox is implemented in the `JarBundleFile`
- mark the JSch module as multi-release. The JSch implementation for communication with the ssh agent can then use the JDK …
> Multi-release jar support

- java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/save/FormatingTest.java
Fix for #3720 
The space seems to occur due to the start and end positions reported for the implicit hidden final modifier, which seem to be the same as the type start and end. The issue can't be seen if `final` is added explicitly.  
This adds an extra check for whether the modifiers and type start at the same position.  I haven't checked if the reported positions of `mods` have changed from earlier versions. The might explain why the issue started appearing, and it's possible the whole enclosing `if` wasn't hit in that case. I've kept localized for now.
The issue with new lines being removed may also be related to this, but haven't managed to track down exactly what's happening - it's possibly related to the token locations. Leaving that for another fix.
> Fix extra space added in try with resources

- ide/editor.codetemplates/src/org/netbeans/lib/editor/codetemplates/CodeTemplateInsertHandler.java
Hello! This PR fixes the NPE error that occurs when you change the existing visibility declaration of a class property or method when you press Enter or click it in the autocomplete list.
> Fixed a NPE from issue #4629

- java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java
> Avoid using an invalid JavaPlatform

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/VulnerabilityWorker.java
The count actually shows number of dependencies not the number of identified issues (CVs).
> Changed wording of the vulnerability scan message.

- java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
fixes #4701
exception handler expected the message of the IOException to be not null. Curious what that exception was.
->
```
at org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl.indexLoadedRepo(NexusRepositoryIndexerImpl.java:586)
at org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl.lambda$indexRepo$6(NexusRepositoryIndexerImpl.java:663)
at org.netbeans.modules.openide.util.DefaultMutexImplementation.writeAccess(DefaultMutexImplementation.java:229)
at org.openide.util.Mutex.writeAccess(Mutex.java:252)
at org.netbeans.modules.maven.indexer.NexusRepositoryIndexerImpl.indexRepo(NexusRepositoryIndexerImpl.java:657)
at org.netbeans.modules.maven.indexer.api.RepositoryIndexer.indexRepo(RepositoryIndexer.java:42)
at …
```
> Fix possible NPE in NexusRepositoryIndexerImpl exception handler.

- java/java.editor.base/src/org/netbeans/modules/java/editor/base/javadoc/JavadocImports.java
JavadocImports fixed for illegal string trim raises a StringIndexOutOfBoundsException.(#4646)
> JavadocImports fixed for illegal string trim.

- java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorkerTest.java
`tree.type` may be `null`, and `error2Object` will return `null` for `null` input, and the current code will reset the `sym.type` to `null` as well, which is obviously problematic/wrong.
---
> Fixing error recovery for (current) record patterns.

- enterprise/web.struts/src/org/netbeans/modules/web/struts/StrutsConfigUtilities.java
- enterprise/websvc.jaxwsmodel/src/org/netbeans/modules/websvc/api/jaxws/wsdlmodel/WsdlPort.java
- enterprise/websvc.jaxwsmodel/src/org/netbeans/modules/websvc/api/jaxws/wsdlmodel/WsdlService.java
- ide/editor/src/org/netbeans/modules/editor/NbEditorKit.java
- ide/versioning.util/src/org/netbeans/modules/turbo/TurboProvider.java
- java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/FixedWatchesManager.java
- platform/openide.execution.compat8/src/org/openide/execution/NbClassPathCompat.java
Cleanup warnings related to unchecked call to add as a member of raw type List..
Here is an example.
[repeat] /home/bwalker/src/netbeans/ide/editor/src/org/netbeans/modules/editor/NbEditorKit.java:628: warning: [unchecked] unchecked call to add(E) as a member of the raw type List
[repeat]                     objects.add(null);
[repeat]                                ^
[repeat]     E extends Object declared in interface List
There are some remaining warnings. They are in generated code and therefore difficult to fix.
---
- are contributed solely under the …
> Cleanup warnings related to raw type List

- enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/ide/WildflyOutputSupport.java
- enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/ide/WildflyStartLineParser.java
- enterprise/javaee.wildfly/test/unit/src/org/netbeans/modules/javaee/wildfly/ide/WildflyStartLineParserTest.java
This PR fixes a flaw in the Wildfly server log line parsing regexes.
In the old version, JBoss EAP 6 (and 7) servers with two digit patch version (e.g. 6.4.23) are not detected, same for minor version.
In EAP 7 it is possible that there is an additional whitespace between the time it took to start the server and the time unit (e.g. 4700 ms instead of 4700ms).
That issue is also fixed.
> Fixed JBoss EAP regex patterns to match two digit minor/patch versions

- java/gradle.java/src/org/netbeans/modules/gradle/java/GradleJavaTokenProvider.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/action-mapping.xml
NetBeans 15 hardcodes the 'cleanTest' and 'test' tasks for all tests regardless of the test sourceset the code exists within.  This should be 'clean[TestSourceSetName]' and '[testSourceSetName]' instead (which still works for the default test sourceset 'test'.
---
If you're a first time contributor, see the Contributing guidelines for more …
> NETBEANS-4720 Support custom gradle test sourcesets

- java/gradle.java/src/org/netbeans/modules/gradle/java/api/GradleJavaSourceSet.java
Fix #4704. This applies to both `-source` and `-target`. This information is used by editor/hints.
With this patch and the following build.gradle excerpt
```
tasks.withType(JavaCompile).each {
it.options.compilerArgs << '--source' << '19'
it.options.compilerArgs << '--target' << '11'
it.options.compilerArgs << '-Xlint:deprecation' << '--enable-preview'
}
sourceCompatibility = 9
targetCompatibility = 9
```
There's
and the following has no errors in the editor.
```
Object o2 = 3;
return switch (o2) {
case Integer i when i >= 0 -> 3; // positive integers
case Integer i -> 4;             // negative integers
case default -> 2;
};
```
> Override gradle's compiler version from compiler args.

- extide/gradle/apichanges.xml
- extide/gradle/manifest.mf
- extide/gradle/src/org/netbeans/modules/gradle/NbGradleProjectImpl.java
- extide/gradle/src/org/netbeans/modules/gradle/actions/ActionToTaskUtils.java
- extide/gradle/src/org/netbeans/modules/gradle/api/NbGradleProject.java
- extide/gradle/src/org/netbeans/modules/gradle/api/execute/RunUtils.java
- extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java
- ide/project.dependency/src/org/netbeans/modules/project/dependency/ArtifactSpec.java
- ide/project.dependency/src/org/netbeans/modules/project/dependency/ProjectArtifactsQuery.java
- java/maven/src/org/netbeans/modules/maven/queries/MavenArtifactsImplementation.java
- platform/core.startup/src/org/netbeans/core/startup/Main.java
Note: this PR is the first from series of 3. I've split the development into 3 PRs since there are different areas that seem to be better reviewed separately. Other PRs in the series depend on this one.
Unrelated fixes:
- Maven fix- - change event is fired only after result refresh from reloaded project completes.
- `ArtfiactSpec` (still private !) API fixes; some project products do not have group at all, some have no version; the API should allow that.
- core module screws up `jdk.home` property when run without a launcher (that sets `jdk.home` beforehand) - visible mainly in tests.
Gradle fixes:
- during `toQuality` that should reload a project if `force` flag is true, the flag was sometimes ignored
Improvement:
- FINER and FINEST loglevel for `LegacyProjectLoader` will print out …
> Various fixes and improvements [1/3]

- extide/gradle/apichanges.xml
- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/TypeUtils.java
- extide/gradle/src/org/netbeans/modules/gradle/api/BuildPropertiesSupport.java
- extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProject.java
- extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java
- extide/gradle/src/org/netbeans/modules/gradle/loaders/BuildPropertiesImplementation.java
- extide/gradle/src/org/netbeans/modules/gradle/loaders/ExtensionPropertiesExtractor.java
- extide/gradle/test/unit/data/buildprops/micronaut/build.gradle
- extide/gradle/test/unit/data/buildprops/micronaut/gradle.properties
- extide/gradle/test/unit/data/buildprops/micronaut/settings.gradle
- extide/gradle/test/unit/data/buildprops/micronaut/src/main/java/com/example/Application.java
- extide/gradle/test/unit/data/buildprops/micronaut/src/main/resources/application.yml
- extide/gradle/test/unit/data/buildprops/micronaut/src/main/resources/logback.xml
- extide/gradle/test/unit/data/buildprops/micronaut/src/test/java/com/example/MicrodemoTest.java
- extide/gradle/test/unit/src/org/netbeans/modules/gradle/loaders/ExtensionPropertiesExtractorTest.java
Important Note: this is 2nd from 3 dependent PRs, depends on #4726. For  review purposes, the PR targets a feature branch in the shared repository, that will be deleted after the related PRs are merged - it allows to inspect/review changes before the base PR (#4726) is merged. The time is becoming a little issue for me :)
Traditionally a module that need information from the gradle build system other than collected by the gradle core and exposed would have to add its 'agent' into `netbeans-gradle-tooling` subproject, then implement `ProjectInfoExtractor`.
This PR allows NetBeans modules to inspect gradle build properties. Clients may even adapt to changes by listening on Gradle project's reload event. The Gradle core module loads a lot more properties from the project model in Gradle …
> API: access to build properties of gradle script [2/3]

- java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteProject.java
When running the IDE on GraalVM-java11-21.3 and working with `mx` projects I am getting reports that `org.graalvm.polyglot` package is defined in other module. Let's eliminate that problem by `--limit-modules java.se`
> Limit bootstrap libraries to java.se

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/AuditException.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/CreateKnowledgeBaseAction.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/ErrorUtils.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/KnowledgeBaseItem.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/ProjectVulnerability.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/RunFileADMAction.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/VulnerabilityWorker.java
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/commands/ProjectAuditCommand.java
The PR provides better feedback for the project audit action:
- when the code is just searching for existing audits, it displays "searching for audits"
- "executing audit" is only displayed when the project is really evaluated by the audit service
- LSP command can demand executing audit none exists in the configured KB
Some debugging leftovers in code cleaned up.
> Better messages during project audit. Code cleanup.

- platform/o.n.swing.laf.flatlaf/nbproject/project.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/Bundle.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafOptionsPanel.form
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafOptionsPanel.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/Installer.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/layer.xml
Adds ability to load custom FlatLaf property files from userdir. Checks for a `LookAndFeel` folder in config, and registers with FlatLaf. Also registers the folder and files for options export. Give user ability to override anything using FlatLaf property support documented at https://www.formdev.com/flatlaf/properties-files/
eg. file in `<userdir>/config/LookAndFeel/FlatLaf.properties` with 
```
@accentColor = #d22
@background = #ddd
```
Added button to open file in editor inside FlatLaf options panel, along with basic default content / instructions.
> Add ability to load custom FlatLaf properties from user config.

- java/java.lsp.server/vscode/CHANGELOG.md
Updates to changelog.md to list latest changes since 15.0 and also for 15.0 as I did not update at that time.
> Updates for 15.0.301 release of VSNetBeans

- platform/core.windows/src/org/netbeans/core/windows/view/ui/TabbedHandler.java
Fix for #4437. Discussion in that issue is useful in understanding this patch.
`platform/core.windows` is  a mystery to me; this patch is almost identical to getting a mouse click, except it is triggered by keyboard focus change to handle other situations where the MainWindow is activated. There may be better solutions, but I believe this is safe.
After getting a focus event, the activate code is only invoked when it is strictly needed. This is an optimization, invoking the activation code multiple times shouldn't matter; it would be like clicking on an already active window.
@jtulach, any idea for a good candidate to review this? This area was written by _Peter Zavadsky_.
> Keyboard focus can activate top component

- enterprise/payara.eecommon/src/org/netbeans/modules/payara/eecommon/api/config/J2EEVersion.java
- enterprise/payara.jakartaee/src/org/netbeans/modules/payara/jakartaee/Hk2JavaEEPlatformImpl.java
- enterprise/payara.tooling/nbproject/org-netbeans-modules-payara-tooling.sig
- enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/config/ConfigBuilderProvider.java
- enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/config/JavaEEProfile.java
- enterprise/payara.tooling/src/org/netbeans/modules/payara/tooling/server/config/PayaraV6.xml
This PR adds Payara 6 configuration xml to enable registration of Payara Server 6.x in the Apache NetBeans IDE.
> Unable to register Payara 6.x in Apache NetBeans 15

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/AttachConfigurations.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/ConfigurationAttributes.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/attach/NbAttachRequestHandler.java
- java/java.lsp.server/vscode/package.json
Add a listening connector to the VSCode extension.
It acts as an attaching connector, but the attach is reversed. VSCode opens a listening socket and the debuggee attaches to it. `"listen":"true"` property flips the attach direction.
The debuggee needs to be started after the listening debugger session is started and with `server=n`, like:
`-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:8000`
> Add debugger listening connector to LSP.

- ide/html.editor/src/org/netbeans/modules/html/editor/completion/HtmlCompletionProvider.java
- ide/html.editor/test/unit/src/org/netbeans/modules/html/editor/completion/HtmlCompletionQueryTest.java
right after opening tag, while copy and paste or closing tag token was added.
The check was not proper enough for calling auto completion after end tag. It just checked the HtmlToken.TAG_CLOSE_SYMBOL which is also the one at the end of an end tag </div">".
So each time I copy and paste "\<div>\</div>" it calles the auto completion which seemed wrong to me. See my screencapture:
I changed that behaviour and now it always comes up at the end of an open tag. Not on an end tag or on a self closing tag like an image, which was already working before: 
I will test this a couple of days to check whether there are other misbehavior or not and if there are no complaints I will merge this later by myself.
> Fix for not calling auto completion after end tag was already added

- java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorkerTest.java
When https://github.com/apache/netbeans/pull/4586 was integrated, the `VanillaCompileWorkerTest` started to fail, as error recovery no longer work properly for pattern matching and JDK 19 javac, when running on JDK <19, as `j.l.MatchException` is missing. The `MatchException` is needed by the generated code, and hence javac cannot generate the code if it is missing. This patch proposes to improve the error recovery for patterns when the class is missing - the code using the patterns would be removed, as would be done if the code would be referring to `MatchException` explicitly.
---
- are …
> Fixing error recovery when j.l.MatchException is missing, and patterns are present.

- java/java.hints/src/org/netbeans/modules/java/hints/bugs/Unbalanced.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/UnbalancedTest.java
- fix for #4402 caused #4545
- partial revert of #4421, tests are commented out, update to READ_METHODS Set is kept
@neilcsmith-net would you prefer the full PR reverted or just the actual "fix" and leave the rest as in this draft here.
> revert rushed unbalanced-hint fix (#4421).

- platform/autoupdate.ui/src/org/netbeans/modules/autoupdate/ui/wizards/Bundle.properties
- platform/autoupdate.ui/src/org/netbeans/modules/autoupdate/ui/wizards/LazyOperationDescriptionStep.java
Quick fix for a long standing annoyance.  We've had a number of users report confusion that using `Help / Check for Updates` only shows plugin updates (which are rare, especially from us) and not new releases of the IDE. In particular, that the text reads "Your IDE is up to date!" when it's not the latest release.
This change adds any update centre notification text to the dialog if no plugin updates are available.  If you want to test, change the NetBeans Distribution update link from https://netbeans.apache.org/nb/updates/dev/updates.xml.gz to https://netbeans.apache.org/nb/updates/14/updates.xml.gz and use Check for Updates.
Image without notification (default as now).
Image with update notification from NB14 catalog.
I've left the header text as is, although I think it's somewhat …
> Add update centre notifications to Check for Updates dialog

- java/languages.antlr/src/org/netbeans/modules/languages/antlr/refactoring/RefactoringActionsProvider.java
Check that EditorCookie document may be null and avoid to pass null object to NbEditorUtilities.getFileObject
> Fix for Gradle project sources popup menu invocation error #4755

- ide/team.commons/src/org/netbeans/modules/bugtracking/commons/TextUtils.java
fixes #4732
This isn't optimal since the methods are used to encode file names (255 char limit on windows), but since this is public API its still worth fixing since it didn't support non latin chars properly as seen in the issue.
> use java.net.URLEncoder/Decoder instead of buggy custom impl.

- java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java
- platform/openide.modules/nbproject/org-openide-modules.sig
- platform/openide.modules/src/org/openide/modules/SpecificationVersion.java
followup to #4672. 
- old logic didn't check installed platforms if the spec version
of the default platform was null
- cap at feature version of nb-javac (or javac, if uninstalled)
- default platform is the fallback
- converted logic to streams
This code runs when code inspections are manually run (e.g. refactor -> inspect and transform). The editor is probably just using the default platform?
I am actually not sure why this selection logic is needed at all - but this should make it less buggy at least.
> Improve java platform selection logic for hints.

- ide/refactoring.api/src/org/netbeans/modules/refactoring/spi/ui/AccessorImpl.java
- java/languages.antlr/nbproject/project.xml
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrDeclarationFinder.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrOccurrencesFinder.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrParser.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrParserResult.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrStructureItem.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrStructureScanner.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrTokenSequence.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/refactoring/Refactoring.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v3/Antlr3CompletionProvider.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v3/Antlr3Language.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v3/Antlr3ParserResult.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4CompletionProvider.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4Language.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4ParserResult.java
- java/languages.antlr/test/unit/src/org/netbeans/modules/languages/antlr/AntlrTokenSequenceTest.java
This one adds support for occurrence finder for modes and channels.
The code completion has been separated for ANTLVv3 and ANTLRv4. I've added some heuristics to make it better for v4, based on the real ANTLRv4 Lexer. Though there is still room for improvement.
I'd like to finish mu indentation support before NB16, but I thought this is complete enough for review.
> Improve support for ANTLRv4 Grammars

- ide/extexecution.process.jdk9/manifest.mf
- platform/o.n.core/test/qa-functional/src/org/netbeans/core/validation/ValidateClassFilesTest.java
With the addition of jakarta ee 10 API jars it was found, that there is an implicit assumption, that all JARs not referenced by modules have to be JDK 8 compatible. In the case of jakarta ee 10 this is an invalid assumption as it explicitly does not support JDK 8. The module that introduces the binaries correctly declares a JDK 11 dependeny, but at runtime the module <-> binary association is lost.
To prevent false positives, the test must be limited to JARs, that are directly referenced from modules.
> Limit ValidateClassFilesTest to scan only JARs referenced from modules

- java/java.project.ui/src/org/netbeans/modules/java/project/ui/NewJavaFileWizardIterator.java
Fixes a spurious error message that the file already exists shown when creating a module-info file, as reported in #4628 This is actually an `IndexOutOfBoundsException` caused by [javac changes](https://github.com/openjdk/jdk/commit/d6fb9d7256de94c3cc407b78dde3088aaf649db7) (`ModuleTree` no longer returned from `getTypeDecls()` but available from added `getModule()`).
The second commit filters out the created module name from the list of added requires. This is an older issue that became visible again that shows a cyclic dependency error.
> Fix error in wizard when creating module-info file (GH4628)

- platform/o.n.bootstrap/src/org/netbeans/NbClipboard.java
Attempt to fix an intermittent clipboard bug on Windows, where cut/paste with external applications would stop working until IDE was restarted. With this fix, the problem still occurs occasionally, but appears to go away the next time the user tries to cut/paste with an external application, without the need to restart the IDE.
This is a follow-up on https://github.com/apache/netbeans/pull/4572, with a slightly alternative approach. Instead of removing the removeFlavorListener/addFlavorListener workaround for a previous bug, we instead call fireChange() after the addFlavorChange, in case we missed some updates. This should probably have been done in any case. The effect of either version of the patch seems the same, but the version in this PR avoids sacrificing the workaround for an …
> Another attempt to fix intermittent clipboard bug on Windows

- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrParserResult.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/layer.xml
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v3/Antlr3ParserResult.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v3/preferences.xml
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4CompletionProvider.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4Formatter.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4Language.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4ParserResult.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/preferences.xml
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/snippets.xml
This is my last round of features for ANTLR support, mainly for v4 grammars. Add indent support in rule definitions, and a few code shortcuts. 
Beside of that, prevented a few of NPE-s that could happen on parsing an incomplete grammar. Also removed the ConsoleErrorListener.
> ANTLRv4 indent and code snippet support.

- platform/openide.text/apichanges.xml
- platform/openide.text/manifest.mf
- platform/openide.text/src/org/openide/cookies/EditorCookie.java
- platform/openide.text/src/org/openide/text/DocumentOpenClose.java
This PR adds, `PROP_RELOADING`, to signal begin/end of document reloading due to an external change.
This change is about handling fixup after a document is reloaded. Currently, `openide.text` adjusts any document positions such that after the reload the `PositionRef`s have the same line number and column offset. However, the **caret positions** in any editors are set to have the same offset as before; and so the caret often seems to jump around after the reload. Maintaining line/col seems preferable. This was discussed in the dev mailing list thread:
```
Detecting file changed externally, 2022, Jun 7
https://lists.apache.org/thread/tb1mkx1koctt74y48gbyqhqsbtrq56ys
```
The editors now support multiple carets and there may be other fixups after a document reload in addition to caret …
> After file external change fire reloaded event

- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-2.6-license.txt
- platform/libs.flatlaf/manifest.mf
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
- platform/libs.flatlaf/src/org/netbeans/libs/flatlaf/Installer.java
Update FlatLaf to v2.6.
This version now uses `System.loadLibrary()` to load native libs (as suggested [here](https://github.com/apache/netbeans/pull/4696#issuecomment-1264613945)),
always loads `libjawt` (as suggested [here](https://github.com/apache/netbeans/pull/4696#issuecomment-1264336570))
and fixes some minor issues.
Changes: https://github.com/JFormDesigner/FlatLaf/releases/tag/2.6
> Update FlatLaf from 2.5 to 2.6

- java/maven.hints/src/org/netbeans/modules/maven/hints/layer.xml
- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/UseReleaseOptionHint.java
- java/maven.hints/test/unit/src/org/netbeans/modules/maven/hints/pom/UseReleaseOptionHintTest.java
- converts matching source/target options to the release option
- supports properties and the standard maven-compiler-plugin
- offers only hints when source/release is set to at least 9+ (could be improved in future once I figure out how to query the JDK version of the project)
It is fairly basic and has a small cosmetic issue. I don't know how to replace elements in-place, so it simply adds the release element to the end of the list if the hint is applied, no matter where source/target was.
I also don't know how to apply hints in the junit tests. When I tried to do that it complained that the model was read only (org.netbeans.modules.xml.xam.dom.ReadOnlyAccess). I suppose its a dummy model.
How to test:
create a new java project and it should already show the hint. It only looks for …
> Implement maven pom javac release option hint (JEP 247).

- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Update JDK 19 Javadoc link from early access to the release location.
Quick fix in delivery as I noticed while testing 16-rc1 on JDK 19 that Javadoc linking is broken.  However, might be good to consider a better way of handling this in future.
> Update JDK 19 Javadoc link from EA to GA.

- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/UseReleaseOptionHint.java
- java/maven.hints/test/unit/src/org/netbeans/modules/maven/hints/pom/UseReleaseOptionHintTest.java
- NPE fix when build tag is empty
- don't show hint if there is no compiler plugin in the pom
- simplified code, added more tests
> Maven UseReleaseOptionHint fixes

- nb/autoupdate.pluginimporter/src/org/netbeans/modules/autoupdate/pluginimporter/Bundle.properties
Users which import nb-javac plugins from old NB versions complain about not being able to start NB anymore (most recent: #4799). This puts all nbjavac modules which were in NB 12.1 on the block list and will hopefully prevent this in future.
> put nb-javac modules on the plugin import block list.

- php/php.editor/src/org/netbeans/modules/php/editor/completion/DocRenderer.java
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocChildMethodSingleSentence.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocClassWithInlineTagForPhpDocumentor.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocConstInlineTag.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocConstInlineTagForPhpDocumentor.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocConstOnlyTag.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocConstWithSingleSentence.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocConstWithoutPhpDoc.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocFieldInlineTag.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocFieldInlineTagForPhpDocumentor.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocFieldOnlyTag.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocFieldWithSingleSentence.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocFieldWithoutPhpDoc.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocInterfaceWithInlineTagForPhpDocumentor.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/inheritdoc.php.testInheritdocMethodWithInlineTagForPhpDocumentor.html
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCCDocumentationTest.java
#4686
- Support `{@inheritdoc}` for fields and constants
- Replace `{@inheritdoc}` with whole parent sentences
```php
<?php
/**
* Parent class.
* 
*/
class ParentClass
{
/**
* Parernt field.
*/
public $field;
/**
* Parent const.
*/
public const CONSTANT = "CONSTANT";
/**
* Parent method.
*/
public function method() {}
}
class Child extends ParentClass
{
public $field = 'field';
public const CONSTANT = "CONSTANT";
public function method() {}
}
/**
* {@inheritDoc}
*/
class ChildWithTag extends ParentClass
{
/**
* {@inheritDoc}
*/
public $field = 'field';
/**
* {@inheritDoc}
*/
public const CONSTANT = "CONSTANT";
/**
* {@inheritDoc}
*/
public function method() {}
}
/**
* Header.
* {@inheritDoc} Child class.
* 
*/
class ChildWithTagAndAdditionalComment extends ParentClass
{
/**
* …
```
> Improve `{@inheritdoc}` behavior #4686

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/AuditOptions.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/ProjectVulnerability.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/RunFileADMAction.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/VulnerabilityWorker.java
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/commands/ProjectAuditCommand.java
This PR cleans up parmeters passed to LSP display and execute: since `knowledgeBase` is required, the `compartment` is not needed, can be derived from `knowledgeBase`.
In addition a requested `auditName` can be passed to the LSP command in case an audit is to be created (either display + force, or execute). Otherwise some default name is made up by the impl.
The PR will be eventually rebased on `delivery`
> More options for LSP audit command

- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrDeclarationFinder.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrParserResult.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v3/Antlr3ParserResult.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4CompletionProvider.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4ParserResult.java
Well, just a quick one. Lexer grammars, can only reference fragments inside rules, pure parser grammars cannot reference fragments. Add some heuristic to support lexercommands as well. + icons
> More precise code-completion for ANTLRv4 Grammars

- java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/UnusedDetector.java
Potential fix for #4276 that never marks an overriding method as unused.  The superclass definition will still be marked unused if not called.  IMO the method can be considered "used" by the superclass, and hints should be over-cautious in preference to over-eager anyway.
> Never mark overriding methods as unused, fixes GH4276.

- .github/workflows/main.yml
as discussed on the dev list -> lets enable the retry script for the micronaut tests for now
> wrap unreliable micronaut tests in retry script for now

- platform/o.n.core/src/org/netbeans/core/ui/ProductInformationPanel.form
- platform/o.n.core/src/org/netbeans/core/ui/ProductInformationPanel.java
fixes #4876
we can't add it right away, otherwise the window can't layout itself without hardcoding the size of the scrollpane. Changing window size once its visible would look weird.
> about panel needs a vertical scrollbar if the async plugin update notification appears

- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AbstractAntlrLexer.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/AntlrTokenSequence.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v3/Antlr3Lexer.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4CompletionProvider.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4Formatter.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4Lexer.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4ParserResult.java
Well, if we would have a 16-rc3 this would be a nice to have.
This one makes the formatting work if the editing happens at the end of the file.
The code completion has a fix and a feature creep. At the end of the file due to the bug in `AntlrTokenSequence` it was offering (`lexer`, `parser`, `grammar`).
The feature creep is a trivial one. We already have the unknown references collected during parsing, so why not offer to define those while not in a rule definition.
> Fixed end of file indenting and code completion for ANTLR v4

- .github/workflows/main.yml
run cache action *after* checkout, otherwise we can't hash the binaries-lists (results in empty string).
the current setup does never update the cache once its built. (I reset it manually yesterday.)
Please note that this was not the cause of the build failures where dependency downloads timed out - but this is how I found the issue in the first place.
targets delivery so that all branches benefit from it.
> ci - run cache action after checkout

- ide/projectui/src/org/netbeans/modules/project/ui/resources/license-default.txt
based on the discussion in #3678 we decided to try to hide the template link if it can't be resolved for now.
adding `all:tests` since this could potentially cause some String comparing tests to fail. Ran some locally but everything was green so far.
> hide template link as last resort if it appears to be broken.

- enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/jakartaee_9.xsd
- enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/resources/xml.xsd
This pull request changes two files to fix [apache/netbeans#4920](https://github.com/apache/netbeans/issues/4920).
1. It modifies `jakartaee_9.xsd` to import the "xml:" namespace from a local copy of `xml.xsd` instead of importing it remotely from `http://www.w3.org/2001/xml.xsd`.
2. It replaces the local `xml.xsd` file with the latest [version dated 2009-01](https://www.w3.org/2009/01/xml.xsd) instead of the previous copy which seems to have been derived from the earliest [version dated 2001-03](https://www.w3.org/2001/03/xml.xsd).
Furthermore, I made the following changes to the `xml.xsd` file from the W3C:
* I removed the XML stylesheet because it causes a same-origin policy error in Firefox when viewing the file locally: "Error loading stylesheet: An unknown error has occurred …
> Import local schema to avoid DNS lookup in build

- java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/breakpoints/MethodBreakpointImpl.java
- java/debugger.jpda/test/unit/src/org/netbeans/modules/debugger/jpda/breakpoints/MethodBreakpointImplTest.java
I am developing mixed [Java+Scala application](https://github.com/enso-org/enso/tree/330612119aba1cbcb310333ca5f06274a67d935b/engine/runtime/src/main) with the NetBeans IDE. I got debugging working, but I have problems to place a breakpoint on constructor of some classes. This is the (disassembled) source I see in the editor:
I can place a method breakpoint on it (as the triangle in the left editor gutter indicates). However the breakpoint is then later reported as misplaced.
I tracked this down to problems in recognizing constructor of such strangely named Scala classes like: `org.enso.compiler.core.IR$Name$MethodReference`. This PR extracts the _"constructor recognizing logic"_  into its own method and adds few tests to verify current behavior. Then it adds a test and a fix to make the …
> Recognize Scala class constructor

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/VulnerabilityWorker.java
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/commands/ProjectAuditCommand.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/api/NodeChangedParams.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/UIContext.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceUIContext.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/AbstractDialogDisplayer.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/NotifyDescriptorAdapter.java
The main issue fixed is the binding between LSP `UIContext` and the **first client that initializes it** and then is stuck with it. The original code gave the 1st client the priority over the client that may have been present in the computational context `Lookup.getDefault()`. The changed code will use the current Lookup.getDefault() that is transferred through various RP.Tasks - this is already implemented in UIContext.find()
* fixes ADM report, so it uses fire-and-forge `notifyLater` instead `notify`. The LSP client may use modeless UI (vscode does) and the server thread is left blocked until the user dismisses the report (in vscode the user may just ignore it or hide it into status line without dismissing)
* minor fix for tests: the structure must gson-deserialize on JDK11, so default …
> Fixes for DialogNotifier in LSP

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/VulnerabilityWorker.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/queries/DependencyText.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/queries/TextDependencyScanner.java
- java/gradle.java/test/unit/data/dependencies/parse/variousSyntax.gradle
- java/gradle.java/test/unit/src/org/netbeans/modules/gradle/java/queries/RegexpGradleScannerTest.java
The implementation of `DependencyResult.getDeclarationRange` failed to find a dependency that was specified using a map, e.g.
```
implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.17.0'
```
parser was ok, but matching ignored such dependency text. Relevant tests for various dependency entry syntaxes were added.
Additional: a subtle bug in Oracle Cloud Vulnerability Audit feature was found that resulted in NPE in some cases, so a cached audit might not appear.
@MartinBalin might be also included in NB16, if it is not too late. Please decide, I'll eventually rebase.
> Fix mapping of dependencies described as key/value maps to the source

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/GradleInternalAdapter.java
- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
The culprit for the reported error (see #4923) is a `LinkageError` as the gradle version configured for the build changed its internal APIs (a change needed to adopt Groovy 4.0). It's true that now the gradle project loader accesses even gradle internal APIs that can be less stable than the proper APIs.
This PR centralizes the gradle internal access to `GradleInternalAdapter` class. Each call to an internal API should be now guarded with `safeCall` that blocks thrown `Errors` and `RuntimeExceptions` and logs them as problems, but continue the loading process.
The main `NbProjectInfoBuilder` should be now free of references to Gradle internals. To accommodate different API versions, the Adapter can be subclassed with alternative implementations for both newer or older versions that the one …
> #4923: access to gradle internal APIs is protected from failing the project load, just logs a notification.

- java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/pm/NFABasedBulkSearch.java
@BradWalker found in #4781 a minor bug where `cancel.get()` was checked but ignored.
The last check is redundant since it is the end of the method.
This might have been a copy and paste bug, since other methods have checks like `if (cancel.get) return null;`. I suppose it was meant to only remove the `null` but leave the `return`
> NBABasedBulkSearch::encode doesn't return on cancel

- extide/gradle.editor/src/org/netbeans/modules/gradle/editor/cli/GradleCliCompletionProvider.java
- extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleCommandLine.java
- extide/gradle/src/org/netbeans/modules/gradle/configurations/NewConfigurationPanel.java
- extide/gradle/src/org/netbeans/modules/gradle/customizer/BuildActionsCustomizer.java
- extide/gradle/src/org/netbeans/modules/gradle/execute/GradleExecutorOptionsPanel.java
Playing with Ernies composite build in #4865 I've encountered  the following exception
```
java.lang.ClassCastException: class org.netbeans.modules.gradle.NbGradleProjectImpl cannot be cast to class org.openide.loaders.DataObject (org.netbeans.modules.gradle.NbGradleProjectImpl is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @512bad4a; org.openide.loaders.DataObject is in unnamed module of loader org.netbeans.StandardModule$OneModuleClassLoader @657680c2)
at org.netbeans.modules.editor.hints.HintsControllerImpl.setErrors(HintsControllerImpl.java:68)
at org.netbeans.spi.editor.hints.HintsController$1.run(HintsController.java:59)
at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
at …
```
> Prevent CCE NbGradleProjectImpl to DataObject

- extide/gradle.editor/src/org/netbeans/modules/gradle/editor/cli/GradleCliEditorKit.java
- extide/gradle/src/org/netbeans/modules/gradle/layer.xml
Neil, you are correct and right in #4946, though I'd address the issue using `@MimeRegistration` so that moves with the code in the future.
> Fix GradleCliEditorKit Registration

- platform/janitor/src/org/netbeans/modules/janitor/Bundle.properties
- platform/janitor/src/org/netbeans/modules/janitor/Janitor.java
- platform/janitor/src/org/netbeans/modules/janitor/JanitorOptionsPanel.form
- platform/janitor/src/org/netbeans/modules/janitor/JanitorOptionsPanel.java
This one adds an option to the Janitor to remove abandoned cache directories automatically.
Well, I've set the default true, as even this is a delete operation. it is just cache.  Usually it bothers me, as a user of `netbeans-dev` Snap package, which is updated weekly and leaves a cache directory behind each week.
> Remove Abandoned Cache Dirs Automatically [Janitor]

- java/maven/src/org/netbeans/modules/maven/queries/MavenDependenciesImplementation.java
- java/maven/test/unit/data/projects/dependencies/duplicates/micronaut/README.md
- java/maven/test/unit/data/projects/dependencies/duplicates/micronaut/pom.xml
- java/maven/test/unit/data/projects/dependencies/duplicates/micronaut/src/main/java/com/example/Application.java
- java/maven/test/unit/data/projects/dependencies/duplicates/micronaut/src/test/java/com/example/DemoTest.java
- java/maven/test/unit/data/projects/dependencies/golden/testCompileDependencies
- java/maven/test/unit/data/projects/dependencies/golden/testDuplicatedDependencies
- java/maven/test/unit/data/projects/dependencies/golden/testRuntimeDependencies
- java/maven/test/unit/src/org/netbeans/modules/maven/queries/MavenDependenciesImplementationTest.java
See also [NETBEANS-6519](https://issues.apache.org/jira/browse/NETBEANS-6519)
The main issue with the implementation was that the 1st encountered Dependency from Maven might be truncated / stripped of its children - and marked as a duplicate. However in the dependency API all dependencies are "equal", we cannot assume that a client does depth-first or breadth-first traversal.
With the fix, the dependency tree will be enormous, as each common library dependency will introduce a full subtree at the library's place in the dependency tree.
I plan to add an additional API to mark duplicates (= subtrees with the same contents) and possibly resolution conflicts (an artifact dependency has been resolved by a different artifact, e.g. a different version of a library). But this fix is simple and …
> [NETBEANS-6519] Maven dependency produces full tree with duplicates, avoids cycles.

- platform/core.multitabs/src/org/netbeans/core/multitabs/impl/ButtonPopupSwitcher.java
- platform/core.multitabs/src/org/netbeans/core/multitabs/impl/DocumentSwitcherTable.java
Implemented closing of a whole document list at once, based on issue [#4760](https://github.com/apache/netbeans/issues/4760)
> Close whole documents list at once

- enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/ide/WildflyKiller.java
- platform/o.n.bootstrap/launcher/unix/nbexec
gets rid of this warning:
`egrep: warning: egrep is obsolescent; using grep -E`
when using NetBeans from CLI eg.
`./netbeans --help`
> use grep -E instead of egrep

- java/maven/src/org/netbeans/modules/maven/execute/CommandLineOutputHandler.java
- java/maven/src/org/netbeans/modules/maven/options/Bundle.properties
- java/maven/src/org/netbeans/modules/maven/options/MavenSettings.java
- java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.java
- java/maven/test/unit/src/org/netbeans/modules/maven/execute/CommandLineOutputHandlerTest.java
- sets `--no-transfer-progress` as default global maven option
- removes console regexp filter which fixes #4017
- regexp filter didn't work with current maven anyway
> hide maven transfer progress via flag instead of regexp filter.

- ide/projectuiapi/src/org/netbeans/modules/project/uiapi/ProjectTemplateAttributesProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ConnectionSpec.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
- nbbuild/antsrc/org/netbeans/nbbuild/CustomJavac.java
- nbbuild/templates/projectized.xml
A follow-up to #4921. 
The most important fix is a fix to `nbjavac` task that prevents classes like `$JsCallback$` and similar to be deleted just before an incremental compilation because they are considered inner classes (without a matching outer class).
I've added additional logging to both server and client, because some thrown errors are wrapped into uninformative "Internal error". Added possibility to log-trace LSP messages (enabled by System property)
I've cleaned up the test a little:
- the exception about missing Groovy support turned into a WARNING line, if the client demands Groovy enabled, but it is simply not available. Other Reflective exceptions show stacktrace.
- fixed error that manifested by a print about 'not normalized' license template filename/path
- suppressed …
> Test bugfixes: preparation for GH action migration

- java/java.lsp.server/vscode/src/extension.ts
Auto enable/disable java support should work also in case when no folder is opened in workspace.
> VSCode: Auto enable/disable java should work when no folder is opened in workpsace.

- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/MavenSelectionHintsTask.java
Fixes #4993 by code inspection, amending mistake introduced in #3833. Both call sites require the result to be non-null: https://github.com/apache/netbeans/blob/67393d2c6d8dc52aadb3477ac86b40bfc2dc4fef/java/maven.hints/src/org/netbeans/modules/maven/hints/pom/MavenSelectionHintsTask.java#L68-L69 https://github.com/apache/netbeans/blob/67393d2c6d8dc52aadb3477ac86b40bfc2dc4fef/ide/spi.editor.hints/src/org/netbeans/spi/editor/hints/HintsController.java#L72-L75 https://github.com/apache/netbeans/blob/67393d2c6d8dc52aadb3477ac86b40bfc2dc4fef/java/maven.hints/src/org/netbeans/modules/maven/hints/pom/LspMavenErrorProvider.java#L77-L81
> Fix `NullPointerException` in `MavenSelectionHintsTask`

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/VulnerabilityWorker.java
Vulnerabilities should produce "warning" messages rather than errors.
> Use warning rather than error for vulnerability reports.

- ide/css.editor/src/org/netbeans/modules/css/editor/csl/CssCompletion.java
- ide/css.editor/src/org/netbeans/modules/css/editor/module/main/StandardPropertiesHelpResolver.java
There are two different issues:
- The documentation is fetched based on the completion result. This was only build based on the prefix. This change sorts the completion result using the node image where the cursor is currently located and sort by levenshtein distance between this image and the completion proposal. This result in preferring better matching entries.
- The documentation is looked up from the W3C specificiation HTML files. To do this the correct location is located using several regular expressions. To make this more precise a less flexible regexp is used. The other matches are retained and used as fallbacks.
Closes: #4778
> Optimize matching for CSS completion queries

- ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/CompletionProviderImpl.java
This is the test case (typescript):
```typescript
export class test {
demo() {
this.runstranget|
}
runStrangeThings(): void {
}
}
```
The codecompletion at the | mark will offer "runStrangeThings", but completion will yield "this.runstrangethings". The reason is, that the CC is invoced case-insensitive, so the original string needs to be replaced with the full result.
> LSP Client: Use full complete item to complete, not just the missing suffix

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/GradleInternalAdapter.java
- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
- extide/gradle/test/unit/src/org/netbeans/modules/gradle/api/GradleBaseProjectTest.java
Fixes #4965. There are two issues, one NPE: simply the supplier parameter is not checked (can be null) before it is asked to supply a default. Next, another call to internal API, this time introduced by Gradle 6.4 was found - reported just as a warning, not affecting rest of the operation.
Added a unit test that gradle 6.1.1 loads a default project.
> #4965: Fix issues with gradle pre-6.4

- java/gradle.java/src/org/netbeans/modules/gradle/java/output/LookupProviders.java
This is a small change that registers the Gradle JDPA and JavaCompiler output listener on General Gradle project level instead of individual plugin level, so projects that non necessary Java project, but has Java sub-projects or deals with Java/JVM in some way can have their output processed. 
Fixes #4865
> [#4865] Register JDPA and Java Compiler Output on Project level

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
- extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java
Yet another fix, restoring some pre-6.1 Gradle Compatibility.
Brief list of the changes:
* `VersionNumber` -> `GradleVersion` (VersionNumber is deprecated for a while)
* Also comparing on base version, so no comparisons to RCs are needed.
* Identify plugin by name instead of class
* Checking for MissingPropertyException-s in `getProperty` and returning `null` if that would happen.
I'm still unhappy about the issues caused by the mass auto-discovery feature.
> Fixed some Gradle introspection problems wit pre-6.1 Gradle Versions

- java/java.lsp.server/vscode/package.json
Run Configuration panel should be hidden with Java support disabled as the corresponding `Java8+` run/debug configuration is not available.
> VSCode: Hide Run Configuration panel when Java support is disabled.

- enterprise/micronaut/src/org/netbeans/modules/micronaut/gradle/MicronautGradleArtifactsImpl.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/layer.xml
The micronaut module supports 'nativeCompile' task indirectly - only if `io.micronaut.application` plugin was included. This PR reacts also on `org.graalvm.buildtools.native` plugin provided by GraalVM community  -- so it would serve native artifacts even for other configuration than just with `io.micronaut.application`.
The GraalVM plugin is also used by SpringBoot and possibly by other 4rd party plugins, too.
> Support directly native build plugin

- java/gradle.java/src/org/netbeans/modules/gradle/java/output/JavaCompilerProcessorFactory.java
Quick fix for the broken master.
Thanks @sdedic  for the insight.
I'm sorry about breaking the build.
> Made Gradle JavaCompilerProcessorFactory work in absence of a ClasspathProvider

- ide/git/src/org/netbeans/modules/git/ui/history/SearchExecutor.java
- ide/git/src/org/netbeans/modules/git/ui/history/SearchHistoryPanel.form
- ide/git/src/org/netbeans/modules/git/ui/history/SearchHistoryPanel.java
- ide/versioning.ui/src/org/netbeans/modules/versioning/ui/history/HistorySettings.java
as discussed on the [dev list](https://lists.apache.org/thread/g9w0038rdsksony6xyl4q42vnj4jrjk4), this proposes some tweaks to the versioning UI
- `git -> show history` will start with 50 entries loaded by default
- file history will show the full history by default
- search button will only show up if the advanced options are expanded since:
- everything else searches at realtime
- results will be shown on first open without the extra click since #3294
- which means the button is only useful when the advanced options are expanded
> tweaks some versioning history settings.

- .github/release.yml
needs more categories since the `other` section is quite large still.
going to try to update older releases after this is merged by doing some boolean algebra on release notes :)
```java
public class RetroNoter2000 {
public static void main(String[] args) throws IOException {
Path base = Path.of("/home/mbien/NetBeansProjects/RetroNoter2000/");
// second last file is the release of interest
List<String> files = List.of(
"HEAD_16.txt",
"HEAD_15.txt"
//            "HEAD_14.txt",
//            "HEAD_13.txt",
//            "HEAD_126.txt",
//            "HEAD_125.txt"
);
Set<String> filter = new HashSet<>();
for (int i = 0; i < files.size()-1; i++) {
filter.addAll(readPRsAsSet(base.resolve(files.get(i))));
}
Path previous = base.resolve(files.get(files.size()-1)); // tag before release of …
```
> added more categories for the release notes generator.

- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/EditorActionRegistrationProcessor.java
- java/jshell.support/src/org/netbeans/modules/jshell/editor/Bundle.properties
- java/jshell.support/src/org/netbeans/modules/jshell/resources/layer.xml
After finding a weird context mentu entry, I started investigating what this is and here you can read more about it: https://github.com/apache/netbeans/discussions/4894
So before the fix, the string looked like Editors/Popup/mimeType which  was wrong and lead to misbehavior of EditorActions in PopupMenus (Context menu). After the fix, it looks correct now Editors/mimeType/Popup. The 2 actions were added just for the Java Shell support but because of wrong order, the action were added for each editor.
Also I removed unnecessary layer.xml entry which led to an empty  entry after the original fix.
> Fix wrong popuppath by changing order of popupPresenterFilePath strings

- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/optional/StartTomcat.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/util/LogManager.java
- enterprise/web.core/src/org/netbeans/modules/web/core/api/JspColoringData.java
- enterprise/web.core/src/org/netbeans/modules/web/core/jsploader/TagLibParseSupport.java
- enterprise/web.core/src/org/netbeans/modules/web/jspcompiler/SmapResolver.java
- enterprise/web.jspparser/nbproject/project.properties
- enterprise/web.monitor/src/org/netbeans/modules/web/monitor/data/RequestAttributesOut.java
- enterprise/web.struts/src/org/netbeans/modules/web/struts/editor/StrutsConfigHyperlinkProvider.java
- ide/api.debugger/src/org/netbeans/api/debugger/Lookup.java
- java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/models/BoldVariablesTableModelFilter.java
- javafx/javafx2.editor/src/org/netbeans/modules/javafx2/editor/fxml/FxmlSchemaCatalog.java
- platform/openide.util/src/org/openide/util/MapFormat.java
- webcommon/lib.v8debug/src/org/netbeans/lib/v8debug/connection/LinkedJSONObject.java
There are a few remaining raw type List warnings remaining.. This attempt is to try and clean the bulk of them up. It's been a slog to get all this done..
[repeat] /home/bwalker/src/netbeans/ide/editor/src/org/netbeans/modules/editor/NbEditorKit.java:712: warning: [unchecked] unchecked call to add(E) as a member of the raw type List
[repeat]                         l.add(action);
[repeat]                              ^
[repeat]     E extends Object declared in interface List
The remaining ones are mostly due to generated code. They will require a different type of fix.
---
- are all your own work, and you have the right …
> Cleanup few remaining raw type List warnings..

- ide/csl.api/src/org/netbeans/modules/csl/spi/GsfUtilities.java
- platform/openide.loaders/src/org/openide/text/DataEditorSupport.java
- platform/openide.loaders/test/unit/src/org/openide/text/FileSizeThreshholdExceptionTest.java
as discussed on the [dev list](https://lists.apache.org/thread/g9w0038rdsksony6xyl4q42vnj4jrjk4), this proposes to bump the large-file warning trigger a little bit.
customizable via the `org.openide.text.big.file.size` property.
System memory and there also heap sizes grew over time, fixed perm gen became dynamic meta space. This should allow to dare a bit more in that area without showing warnings.
old limit (new is 5MB):
going to run this with all tests enabled since this could have side effects in tests, given that I found that CSL module hardcoded that value even though it is configurable via a property.
> bump large file warning from 1 to 5MB.

- .asf.yaml
should we:
- ~~enable force push protection for delivery too?~~ [Please don't!](https://github.com/apache/netbeans/pull/4785#issuecomment-1278923154) :)
- ~~add reviewer requirement for master?~~ [no](https://github.com/apache/netbeans/pull/4785#issuecomment-1278923154)
- ~~add green CI requirement before merge~~ [rather no](https://github.com/apache/netbeans/pull/4785#issuecomment-1304628234), [no](https://github.com/apache/netbeans/pull/4785#issuecomment-1307075183)
- This can't lock us out since we use `pull_request` and not `pull_request_target` which means CI uses the workflow file of the PR and not the one of the target branch (master). 
- There will be always some way to "help" generating a green checkmark. 
- In the event when CI fails entirely we probably shouldn't merge anything …
> enable branch protection for master.

- extide/gradle/src/org/netbeans/modules/gradle/GradleJavaCompatProblemsProvider.java
- extide/gradle/src/org/netbeans/modules/gradle/GradleProjectConnection.java
- extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java
- extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
- extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java
- extide/gradle/src/org/netbeans/modules/gradle/spi/execute/package-info.java
There would be more commits after this one. Need to iron out the following things:
* Use the Project dictated Gradle Version in most cases. Revert back to the supplied one only if the project JVM is misaligned.
* Project problem provider should only report misaligned project JVM and Gradle version, also offer a fix to select project JVM
* Move Gradle Compile customizer options to Gradle Execution
* Offer better Gradle JVM Selection made it available on Root project only.
> Use Project Dictated JVM for Gradle Discovery

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/GradleInternalAdapter.java
- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
- extide/gradle/test/unit/src/org/netbeans/modules/gradle/api/GradleBaseProjectTest.java
Cherry picked from master for NB17.
* Fix #4965: Avoid NPE: return null for no supplier.
* Improve compatibility for Gradle < 6.4
> #4965: Fix issues with gradle pre-6.4 (#4995)

- extide/gradle/apichanges.xml
- extide/gradle/arch.xml
- extide/gradle/manifest.mf
- extide/gradle/src/org/netbeans/modules/gradle/api/execute/Bundle.properties
- extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
- extide/gradle/src/org/netbeans/modules/gradle/execute/GradleNetworkProxySupport.java
- extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java
- extide/gradle/src/org/netbeans/modules/gradle/options/Bundle.properties
- extide/gradle/src/org/netbeans/modules/gradle/options/GradleExperimentalSettings.java
- extide/gradle/src/org/netbeans/modules/gradle/options/NetworkProxySettings.java
- extide/gradle/src/org/netbeans/modules/gradle/options/SettingsPanel.form
- extide/gradle/src/org/netbeans/modules/gradle/options/SettingsPanel.java
On a corporate network or on a VPN the user often forgets about a network change - even worse because with PAC autoconfiguration, NetBeans IDE is able to dynamically change proxy / non-proxy, depending on PAC results.
But build tools like Gradle have to get explicit instructions. The user uses NetBeans, happilly browses online resources (with an PAC-configured browser), but build actions or even project info load itself fails mysteriously on missing on unreachable artifacts.
This PR adds a check, before taking an 'online' action in Gradle, if Gradle's configuration file matches IDE's own proxy settings. If it does not, the default is to suggest the user to reconfigure Gradle - and NetBeans will even do that for the user.
The user may also choose to leave settings as they are (for whatever …
> Gradle: Support for proxy detection / autoconfiguration.

- java/java.lsp.server/nbcode/branding/modules/org-netbeans-modules-gradle.jar/org/netbeans/modules/gradle/api/execute/Bundle.properties
- java/maven/licenseinfo.xml
- java/maven/src/org/netbeans/modules/maven/api/execute/Bundle.properties
- java/maven/src/org/netbeans/modules/maven/execute/MavenCommandLineExecutor.java
- java/maven/src/org/netbeans/modules/maven/execute/MavenProxySupport.java
- java/maven/src/org/netbeans/modules/maven/execute/proxies.template.xml
- java/maven/src/org/netbeans/modules/maven/execute/proxy.template.xml
- java/maven/src/org/netbeans/modules/maven/layer.xml
- java/maven/src/org/netbeans/modules/maven/options/Bundle.properties
- java/maven/src/org/netbeans/modules/maven/options/MavenSettings.java
- java/maven/src/org/netbeans/modules/maven/options/NetworkProxySettings.java
- java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.form
- java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.java
- java/maven/src/org/netbeans/modules/maven/problems/SanityBuildAction.java
- java/maven/src/org/netbeans/modules/maven/settings.template.xml
Similar to #5006 but for Maven.  For "priming build" and maven online invocations, the proxy is checked first. If mismatch is found, the IDE asks the user (the default setting) other actions can be: ignore, auto-update maven settings.xml or override on-the-fly.
The override is done by generating a copy of the `~/.m2/settings.xml` with relevant parts changed/added, maven is then invoked with `--settings` option. Generated files are put into `$nbuserdir/var/cache`.
> Proxy autodetection + autoconfiguration for Maven.

- enterprise/maven.j2ee/src/org/netbeans/modules/maven/j2ee/ear/EarImpl.java
If the old property isn't found, try the new one. They can't both be specified, the Maven EAR plugin 3+ will refuse the build if the old property is specified. Therefore it doesn't matter which property is looked up first.
Fixes https://github.com/apache/netbeans/issues/4928.
> [NETBEANS-4928] EAR deployment considers outputFileNameMapping Maven EAR plugin property

- java/maven/src/org/netbeans/modules/maven/execute/CommandLineOutputHandler.java
- java/maven/src/org/netbeans/modules/maven/execute/cmd/ExecutionEventObject.java
Fixes #3675 by just disabling output window folds when they would otherwise lead to errors and loss of output. Observed when using `mvnd` with forked executions in a multimodule build. (The same project gets folds when building one module at a time, or using `mvn`, and probably also when skipping the mojo causing a forked execution though I did not manage to test that.)
> Avoid an `AssertionError` with Maven folds

- harness/apisupport.harness/build.xml
- java/lib.jshell.agent/nbproject/project.properties
- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
- nbbuild/templates/common.xml
- platform/libs.asm/external/asm-9.4-license.txt
- platform/libs.asm/external/binaries-list
- platform/libs.asm/nbproject/project.properties
- platform/libs.asm/nbproject/project.xml
Library Notes:
- JDK 20 support
- more checks in CheckClassAdapter
- Javadoc improvements and fixes
- module-info classes can be built without Gradle and Bnd
- parent POM updated to org.ow2:ow2:1.5.1
- Bug fixes
- 317977: CheckClassAdapter is no longer transparent for MAXLOCALS
- 317981: Add public getDelegate method to all visitor classes
- Analyzer does not compute optimal maxLocals for static methods
- Fix SignatureWriter when a generic type has a depth over 30
- Skip remap inner class name if not changed in Remapper
Testing:
[ASM Web Page](https://asm.ow2.io/index.html)
[Release Notes](https://asm.ow2.io/versions.html)
> Update asm from 9.3 to 9.4

- platform/core.multitabs/src/org/netbeans/core/multitabs/impl/DocumentSwitcherTable.java
- platform/core.windows/src/org/netbeans/core/windows/actions/ActionUtils.java
When invoking "Close All" on a tab, some tabs may pop up confirmation dialogs asking whether their work should be saved or not. Pressing the "Cancel" button in any dialog, as opposed to "Save" or "Discard", should stop showing further dialogs, and stop the overall operation. This was not previously done. (In some cases, a bunch of dialogs would be shown on top of each other simultaneously, creating visual artifacts.)
This change was made to the Close All and Close Other actions, as well as for the newly introduced "Close whole documents list at once" button in the document list dropdown (PR #4792).
In a [previous discussion](https://github.com/apache/netbeans/pull/4792), it was suggested to make the whole operation atomic (i.e. don't close any tabs at all if the user presses Cancel after …
> Have "Close All" and friends honor "Cancel" in save prompt dialogs

- .github/workflows/main.yml
- java/java.lexer/nbproject/project.properties
- java/java.lexer/test/unit/data/testfiles/testInput.java.txt.tokens.txt
- java/javadoc/nbproject/project.properties
- java/spi.java.hints/test/unit/src/org/netbeans/modules/java/hints/spiimpl/UtilitiesTest.java
- java/maven.hints (build tools job)
- java.lexer (always on since fast)
- spi.java.hints (Java label)
- refactoring.java (Java label)
- form (Java label)
- junit (always on)
- javadoc (JavaDoc label)
this required to disable some tests in `java.lexer`, `javadoc` and a single test case in `spi.java.hints`. Everything else worked fine when run directly from the IDE with JDK 19. Lets see what CI says.
> enable some important sounding java tests

- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/AllLFCustoms.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/Startup.java
Fixes issue #5041
FlatLaf uses `UIManager.getFont("defaultFont")` as base for all fonts (similar to Nimbus).
Edit: tested with FlatLaf, Windows L&F, Nimbus and Metal.
> FlatLaf: fix font of window title when using `--fontsize` argument (on Windows)

- java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/PatternMatchingInstanceof.hint
- java/java.hints.declarative/test/unit/src/org/netbeans/modules/java/hints/declarative/PatternMatchingInstanceof.test
- java/java.source.base/src/org/netbeans/modules/java/source/matching/CopyFinder.java
- java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/Utilities.java
- java/spi.java.hints/test/unit/src/org/netbeans/modules/java/hints/spiimpl/UtilitiesTest.java
- java/spi.java.hints/test/unit/src/org/netbeans/modules/java/hints/spiimpl/processor/JavaHintsAnnotationProcessorTest.java
- java/spi.java.hints/test/unit/src/org/netbeans/spi/java/hints/matching/CopyFinderTest.java
> Fixing pattern matching for binding patterns

- java/maven/src/org/netbeans/modules/maven/api/output/OutputUtils.java
- java/maven/src/org/netbeans/modules/maven/execute/CommandLineOutputHandler.java
- java/maven/src/org/netbeans/modules/maven/output/DependencyAnalyzeOutputProcessor.java
- java/maven/src/org/netbeans/modules/maven/output/JavaOutputListenerProvider.java
mvnd is using `WARN` instead of `WARNING` (switched to SLF4J it seems) and prints the output type `(stderr|stdout)` on exceptions which causes stack traces to be not parsed.
The `Level` enum is public api so we can't really change that. Instead, `WARN` is simply mapped to the `WARNING` enum.
As side effect this also fixes some of the log level parsing which means that some of the maven output is now painted in a yellowish color. This looks good with the dark theme but might need some tweaks for the light theme.
test snippet:
```java
List.of(1).clear();
}
```
NB 16:
PR applied:
> fix output window stacktrace parsing when mvnd is used.

- java/maven/src/org/netbeans/modules/maven/output/DefaultOutputProcessorFactory.java
- java/maven/src/org/netbeans/modules/maven/output/ExecPluginOutputListenerProvider.java
- java/maven/src/org/netbeans/modules/maven/output/JavaStacktraceOutputProcessor.java
stack trace processing is currently only enabled for the exec maven plugin. This PR enables it globally.
Unfortunately this is all public API so I don't think we can simply rename `ExecPluginOutputListenerProvider` and call it a day. So I created a copy and replaced the original provider with the global variant.
before:
imagine no links and no happy face
(don't worry this is not my pw it is a integration test)
this works best when #5099 is also applied, since it fixed some of the patterns.
> globally enable maven stacktrace processing.

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
The bug that provoked the investigation was
```
at java.base/java.util.ArrayList.(ArrayList.java:179)
at org.netbeans.modules.gradle.tooling.NbProjectInfoBuilder.detectSources(NbProjectInfoBuilder.java:1012)
at org.netbeans.modules.gradle.tooling.NbProjectInfoBuilder.lambda$runAndRegisterPerf$9(NbProjectInfoBuilder.java:408)
at org.netbeans.modules.gradle.tooling.NbProjectInfoBuilder.runAndRegisterPerf(NbProjectInfoBuilder.java:414)
at org.netbeans.modules.gradle.tooling.NbProjectInfoBuilder.runAndRegisterPerf(NbProjectInfoBuilder.java:408)
at org.netbeans.modules.gradle.tooling.NbProjectInfoBuilder.buildAll(NbProjectInfoBuilder.java:211)
at org.netbeans.modules.gradle.tooling.NetBeansToolingPlugin$NetBeansToolingModelBuilder.buildAll(NetBeansToolingPlugin.ja …
```
> Fixing project loading issues with micronaut complex project.

- java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBClassReader.java
Today NetBeans greeted me with the following Exception:
```
java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
at org.netbeans.lib.nbjavac.services.NBClassReader.readClassFile(NBClassReader.java:91)
at com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:374)
at com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:303)
at org.netbeans.lib.nbjavac.services.NBClassFinder.lambda$getCompleter$1(NBClassFinder.java:95)
at com.sun.tools.javac.code.Symbol.complete(Symbol.java:682)
at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1410)
at com.sun.tools.javac.code.ClassFinder.loadClass(ClassFinder.java:447)
...
```
This one is a trivial fix, not to try to get the class version if the class file is actually empty. Could happen in some …
> Prevent AOBE on empty, bad class files.

- .github/workflows/main.yml
- webcommon/javascript2.jsdoc/test/unit/src/org/netbeans/modules/javascript2/jsdoc/JsDocCodeCompletionTest.java
only a single test failed:
`JsDocCodeCompletionTest` can't use `getTestFile()` in overwritten method since the method fails the test if the file does not exist. The Test file logic in `CslTestBase::assertDescriptionMatches` has to be able to call `exists()` on a potentially not existing file when it is trying to find JDK version specific (golden) test files.
everything else in this job should be ready for 11.
meta issue: #4904
> move webcommon job to JDK 11 and fix tests where needed.

- .github/workflows/main.yml
- ide/db.dataview/test/unit/src/org/netbeans/modules/db/dataview/util/DateTypeTest.java
- ide/schema2beans/test/unit/data/TestContrivedApp.java
- ide/schema2beans/test/unit/src/tests/MainTest.java
- ide/xml.wsdl.model/test/unit/src/org/netbeans/modules/xml/wsdl/validator/WSDLSchemaValidatorTest.java
- don't test JDK APIs, lets assume that they work.
- JDK 11 fixes: javac path and java.lang.Module classname conflict.
- fix WSDLSchemaValidatorTest assertion, some xml validation errors seem to appear twice on newer JDKs.
meta issue: #4904
> move ide modules job to JDK 11 and fix tests where needed.

- ide/css.lib/src/org/netbeans/modules/css/lib/Css3.g
- ide/css.lib/src/org/netbeans/modules/css/lib/Css3Lexer.java
- ide/css.lib/src/org/netbeans/modules/css/lib/Css3Parser.java
- ide/css.lib/test/unit/src/org/netbeans/modules/css/lib/Css3ParserLessTest.java
- ide/css.prep/src/org/netbeans/modules/css/prep/editor/CPStructureItem.java
@use and @forward were parsed as SCSS tokens, which leads to failures in LESS files.
This was most probably introduced by 3a64a846ea672464466944e1177792cc6d42ccbe
Closes: #5104
> [GH-5104] Ensure @use and @forward can be parsed in less files

- ide/git/src/org/netbeans/modules/git/ui/tag/CreateTagAction.java
- ide/git/src/org/netbeans/modules/git/ui/tag/ManageTagsAction.java
This PR adds missing IMAGE_RESOURCE in actions related to git tag operations. Because of the missing IMAGE_RESOURCES the toolbar configuration tool couldn't find them.
Fixes #4914
> Fix missing ICON_RESOURCE in git tag actions

- java/java.source.base/src/org/netbeans/modules/java/source/classpath/SourceNextToBinaryQueryImpl.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/classpath/SourceNextToBinaryQueryImplTest.java
A year ago I was working on a project that integrates [JavaScript, JVM & etc. into Oracle DB](https://labs.oracle.com/pls/apex/f?p=LABS:project_details:0:15). Most of the colleagues were using Eclipse or IntelliJ, but I was very happy with NetBeans VSCode extension (btw. I needed needed VSCode remote development as the machine with all the sources was over ssh across the Atlantic ocean).
Things were working OK, but over the pair programming with colleagues I realized that NetBeans lacks better integration with sources. When their IDEs could jump to a source code, my just disassembled the `.class` file!
After a while I realized that the project is carefully structured and next to each JAR there is also `-sources.jar` and the other IDEs are able to pick it up. Just NetBeans was missing such …
> Locate sources JAR if it is next to binary JAR

- .github/workflows/main.yml
- enterprise/tomcat5/nbproject/project.properties
- enterprise/tomcat5/nbproject/project.xml
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/config/TomcatModuleConfiguration.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/deploy/TomcatManagerImpl.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/util/TomcatInstallUtil.java
The tomcat5 module used the internal classes:
com.sun.org.apache.xml.internal.serialize.OutputFormat
com.sun.org.apache.xml.internal.serialize.XMLSerializer
to modify the tomcat configuration. For this to work the usage of the
javac release option had to be disabled as only exported classes are
then accessible. This is done by specifying bootclasspath.prepend.
Having this masked a different issue which rendered the tomcat module
JDK 9+. The method:
URLEncoder#encode(String s, Charset enc)
was used, which was introduced with JDK9. The alternative
URLEncoder#encode(String s, String enc)
can be used as a drop-in replacement.
Closes: https://github.com/apache/netbeans/issues/5134
Closes: https://github.com/apache/netbeans/issues/5154
> tomcat5: Enable usage of javac release and remove internal class use (fix JDK8 and JDK17+)

- java/java.platform/src/org/netbeans/modules/java/platform/queries/PlatformSourceForBinaryQuery.java
- java/java.platform/test/unit/src/org/netbeans/modules/java/platform/queries/PlatformSourceForBinaryQueryTest.java
The `PlatformForSourceBinaryQuery` class contains support for so called _"unregistered platforms"_. However it seems that the code hasn't been updated to JDK9+ layout. This PR does that. The previously existing test (for JDK8 layout) has been copied and modified to mimic the layout of JDK9+.
> Recognize nbjrt: protocol and locate JDK9+ src.zip

- java/maven/src/org/netbeans/modules/maven/execute/defaultActionMappings.xml
- java/maven/test/unit/src/org/netbeans/modules/maven/api/customizer/ModelHandle2Test.java
- java/maven/test/unit/src/org/netbeans/modules/maven/execute/MavenExecutionTestBase.java
- java/maven/test/unit/src/org/netbeans/modules/maven/execute/ModelRunConfigTest.java
- java/maven/test/unit/src/org/netbeans/modules/maven/runjar/nbactions-template.xml
- java/maven/test/unit/src/org/netbeans/modules/maven/spi/actions/ProvidedConfigurationsTest.java
Upgrade the maven exec plugin from 3.0.0 to 3.1.0.
NetBeans is using this specific version no matter what the project defines which confused me a bit initially when comparing the log with CLI log. I suppose this is done for compatibility reasons? 
edit: found [NETBEANS-4595](https://issues.apache.org/jira/browse/NETBEANS-4595)
> upgrade exec-maven-plugin to 3.1.0.

- java/java.hints/src/org/netbeans/modules/java/hints/bugs/InfiniteRecursion.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/InfiniteRecursionTest.java
> [NETBEANS-4763] Handling switch expressions, case rules and exhaustive switches more correctly.

- java/java.lsp.server/vscode/package.json
- java/java.lsp.server/vscode/src/extension.ts
Custom run config parameters should be enabled also for 'java' configuration in addition to 'java8+'.
> LSP: Enable custom run config params for 'java' configuration.

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCIManager.java
In #5118, I have created a generic method that rethrows callable's (checked) exception using `sneaky throws` approach - but the code is not compilable on JDK8 because the JDK8 javac fails to infer types properly:
```
[nb-javac] /space/src/vscode/netbeans/java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/commands/ProjectAuditCommand.java:149: error: call() in <anonymous org.netbeans.modules.nbcode.integration.commands.ProjectAuditCommand$> cannot implement call() in OCIOperation
[nb-javac]         return OCIManager.usingSession(auditWithProfile, () -> v.findKnowledgeBase(knowledgeBase).
[nb-javac]                                                          ^
[nb-javac]   overridden method does not throw Exception
```
One way is to typecast the lambda or …
> Do not inherit "throws Exception" from Callable to compile on JDK8

- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/MissingRefOutputHint.java
The MissingRefOutput hint is marked as NO_BATCH, but it might make sense to run it in a batch mode, it just cannot be used to generate fixes in a non-interactive environment. So, marking it as query instead.
---
If you're a committer, please label the PR …
> Allow to run missing ref hint in batch mode, but mark it as not having a fix.

- platform/core.network/src/org/netbeans/core/network/proxy/NetworkProxySettings.java
I've noticed bad behaviour in KDE when the system proxy is specified manually. The `kioslaverc` then contains settings like
```
ftpProxy=ftp://proxy.acme.com:80
httpProxy=http://proxy.acme.com:80
httpsProxy=http://proxy.acme.com:80
socksProxy=socks://proxy.acme.com:80
```
and the proxy string then contains not only port specification, but the protocol part as well. The error can be seen in Tools | Options, when System proxy is selected (and KDE has a manual system proxy) - the "Test connection" button action fails with hostname prefixed by `http://`.
This PR strips the PR part from the host string.
> Strip protocol part, present e.g. if in KDE + manual proxy mode.

- java/java.mx.project/build.xml
It seems that `graalvm` project deleted the tag we'd relied on, so I've just replaced the tag name with the tag's sha1 commit id. Since it is not possible to `git clone` a specific commit, I've used an alternative technique to avoid full (big) clone -- see for example https://www.techiedelight.com/clone-git-repository-with-specific-revision/
It will be eventually better to upgrade to newer graal / mx sources.
> Fix #5196: use precise sha1 instead of deleted tag vm-20.3.0

- java/java.editor/test/unit/src/org/netbeans/modules/java/editor/javadoc/JavadocCompletionQueryTest.java
- java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
- java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementJavadoc.java
original issue https://issues.apache.org/jira/browse/NETBEANS-1309
> [NETBEANS-1309] add support for @summary javadoc tag

- java/java.lsp.server/nbcode/nbproject/platform.properties
NBLS does not bundle GraalJS implementation. In JDK16+ Nashorn was removed from the JDK and without JS implementation NBLS is not able to process PAC proxy definitions. That affects all outbound connections from NBLS, such as JDBC or OCI ADM audit requests. 
It also affects Apache NB vscode extension: since PAC processing fails and no proxy is detected, NBLS gives misleading info to the user that maven/gradle proxy is misconfigured.
> Include JS implementation for JDK16+ execution environment.

- platform/openide.util.ui/apichanges.xml
- platform/openide.util.ui/manifest.mf
- platform/openide.util.ui/src/org/openide/util/Utilities.java
- platform/openide.util.ui/test/unit/src/org/openide/util/UtilitiesTest.java
During implementation of OCI support, I've noticed that there's no Lookup-aware helper that materializes list of Actions from XML layer registrations - thing that could be generally useful for configurable nodes/features. 
This PR adds a simple variant of `actionsForPath` that creates `ContextAwareActions`.
> Allow to collect contextual actions from layer path.

- harness/apisupport.harness/release/launchers/app.sh
- nb/ide.launcher/unix/netbeans
In a previous PR (https://github.com/apache/netbeans/pull/3113), the Linux launcher was modified to fix missing font anti-aliasing on some KDE installations. This enabled greyscale anti-aliasing only, however, including on KDE installations where subpixel antialiasing was previously seen to be working. See https://github.com/apache/netbeans/issues/4228 .
This PR further enhances the auto-configuration on KDE by taking the subpixel antialiasing setting from the Xft.rgba GTK setting where available, as suggested by [NickLion](https://github.com/NickLion) in the GitHub issue above.
Tested on KDE Plasma on Ubuntu 18.04.01 in VirtualBox (triggers the awt.useSystemAAFontSettings=lcd_hrgb setting), as well as in Gnome (confirming no change in behavior here). Confirmed visually that subpixel …
> Linux launcher: Auto-detect subpixel text rendering mode on KDE

- java/maven/src/org/netbeans/modules/maven/api/output/OutputUtils.java
- java/maven/src/org/netbeans/modules/maven/classpath/AbstractProjectClassPathImpl.java
- java/maven/src/org/netbeans/modules/maven/classpath/ClassPathProviderImpl.java
- java/maven/src/org/netbeans/modules/maven/execute/CommandLineOutputHandler.java
- java/maven/src/org/netbeans/modules/maven/runjar/RunJarPrereqChecker.java
fixes #4516
- add active JDK to class path
- fix the packageName parsing of the line action when modules are involved
- open class file if no source found -> allows user to download/attach sources
second commit is for cleanup, first has the changes.
test snippet
```java
public static void main(String[] args) throws Exception {
// for a JDK/application trace
new FileReader("nonexistent");
// for a trace in 3rd party deps (guava)
ImmutableSet.of("a").iterator().remove();
}
```
devbuild link (expires in 7 days):
https://github.com/apache/netbeans/suites/10002051531/artifacts/485721202
> update OutputUtils to support stacktrace links leading to JDK files.

- ide/bugzilla/src/org/netbeans/modules/bugzilla/commands/BugzillaExecutor.java
- ide/dlight.nativeexecution/src/org/netbeans/modules/nativeexecution/api/util/MacroMap.java
- ide/mercurial/src/org/netbeans/modules/mercurial/ui/commit/CommitPanel.java
- ide/subversion/src/org/netbeans/modules/subversion/ui/commit/CommitPanel.java
- ide/versioning.util/src/org/netbeans/modules/versioning/util/common/CollapsiblePanel.java
- ide/xml/test/qa-functional/src/org/netbeans/xml/test/actions/XMLActionsTest.java
- nbi/engine/src/org/netbeans/installer/utils/system/launchers/impl/ShLauncher.java
replace() method is more fast then replaceAll() for non regex cases
> Replaced a part of replaceAll() calls to replace()

- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/commands/ProjectMetadataCommand.java
When LSP client issues project metadata command to inspect project structure / produced artifacts, the ArtifactSpec may containa reference to a FileObject, if the artifact was built already. The original idea was to serialize FileObjects as paths, but I made a wrong test -- the check should accept all FileObject subclasses.
In this case a MultiFileObject was serialized from Maven ArtifactSpec resulting in a serialization error:
```
@b18a155
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
at java.base/java.util.concurrent.CompletableFuture$Completion.r …
```
> Use custom serialization for fileobject subclasses.

- enterprise/cloud.oracle/manifest.mf
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/Bundle.properties
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCIManager.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCITenancyProvider.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OracleCloudWizardProvider.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/TenancyInstance.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/TenancyNode.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/RemoveProfileAction.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/SetDefaultProfileAction.java
- java/java.lsp.server/nbcode/branding/modules/org-netbeans-modules-cloud-oracle.jar/org/netbeans/modules/cloud/oracle/Bundle.properties
The recent commit #5118  introduced the ability to select and add OCI profiles, but damaged the Cloud Explorer for Apache Netbeans VSCode extension - it relied on the (default) OCI profile to be automatically converted into `ServerInstance`.
This PR adds an alternative mode, which can be enabled using Branding API, that automatically loads all profiles from the default OCI configuration into the Cloud explorer (in NB IDE or vscode). In the future additional profiles from custom configuration can be added when the Add Cloud / Oracle wizard is enhanced to support custom configs.
NetBeans IDE behaves as in #5118, for the user convenience, vscode extension loads profiles from the default config.
> Autoload default config profiles into ServerInstances.

- .github/workflows/main.yml
checked the CI runs of the last 18 merges to master to see if we can reduce the whack-a-mole factor a bit.
Most had `java.mx.project` failing which is already wrapped in a retry script and `continue-on-error`is set to true for merges. I couldn't reproduce the failure locally, it always passed, so this one might be tricky to fix (previews attempt #4100).
But `ide/options.editor` did also fail often. Those are fairly short tests which could benefit from a retry script - which I added with this PR.
I did also increase the job timeout on mac since the mac runners can sometimes have really high latencies or artifact download speeds.
The other tests failing were in `java/refactoring.java` and `java.source.base` which would be mitigated by #5138 if it makes it in before freeze.
> ci: add retry script to ide/options.editor tests and increase mac timeout.

- java/java.hints/src/org/netbeans/modules/java/hints/perf/Tiny.java
Well, I've bumped into this one today:
```
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "type" is null
at org.netbeans.modules.java.hints.perf.Tiny.getDestinationType(Tiny.java:537)
at org.netbeans.modules.java.hints.perf.Tiny.unnecessaryTempFromString(Tiny.java:488)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
```
This is a trivial patch for that. I've checked the invocations of `resolveType(...)` it seems that the return value is checked for `null` at other places.
> Fix possible NPE in Tiny.java

- ide/languages.toml/src/org/netbeans/modules/languages/toml/TomlLexer.java
- ide/languages.toml/src/org/netbeans/modules/languages/toml/TomlTokenId.java
- ide/lexer.antlr4/src/org/netbeans/spi/lexer/antlr4/AbstractAntlrLexerBridge.java
- ide/lexer.antlr4/src/org/netbeans/spi/lexer/antlr4/LexerInputCharStream.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v3/Antlr3Lexer.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4Lexer.java
This one is in response of https://github.com/apache/netbeans/pull/5206#issuecomment-1375911582
@matthiasblaesing Thanks for your feedback!
> Do not expose LexerInputCharStream as an API.

- nbbuild/build.xml
Make sure that the minority of modules that get rebuilt during make-nbms get the required implementation version. This patches over the issue - it does not address why these modules are being marked stale and rebuilt.
(Partial!) Fix for #5253
> Pass buildnumber into NBM sub-ant target.

- ide/csl.api/test/unit/src/org/netbeans/modules/csl/api/test/CslTestBase.java
- ide/css.editor/src/org/netbeans/modules/css/editor/module/CssModuleSupport.java
- ide/css.editor/test/unit/data/testfiles/coloring1.css
- ide/css.editor/test/unit/data/testfiles/coloring1.css.semantic
- ide/css.editor/test/unit/src/org/netbeans/modules/css/editor/csl/CssSemanticAnalyzerTest.java
CssSemanticAnalyser reported overlapping ranges for highlights, for
example when an attribute is used in a :not() pseudo class construct.
The formatting behind the embedded range is lost and results in a
broken view.
The embedded OffsetRanges need to be flattened into a sequenze of
non-overlapping ranges.
> CssSemanticAnalyser needs to flatten OffsetRanges for highlights 

- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Add entry to the `OFFICIAL_JAVADOC` Map for Java 21
- https://download.java.net/java/early_access/jdk21/docs/api/
Hopefully this will be the last manual update thanks to [PR-4837](https://github.com/apache/netbeans/pull/4837)
> Add javadoc for JDK 21 early access

- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/AntDeploymentProviderImpl.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/TomcatFactory.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/config/TomcatModuleConfiguration.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/customizer/CustomizerDataSupport.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/customizer/CustomizerGeneral.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/deploy/TomcatManager.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/j2ee/JaxRsStackSupportImpl.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/j2ee/TomcatPlatformImpl.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/registration/AutomaticRegistration.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/resources/Bundle.properties
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/resources/tomee_resources.dtd
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/ui/wizard/AddInstanceIterator.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/ui/wizard/InstallPanelVisual.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/util/LogSupport.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/util/LogViewer.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/util/TomcatProperties.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/util/TomcatUsers.java
- enterprise/tomcat5/test/unit/src/org/netbeans/modules/tomcat5/TomcatFactoryTest.java
- enterprise/tomcat5/test/unit/src/org/netbeans/modules/tomcat5/TomcatManagerTest.java
- enterprise/tomcat5/test/unit/src/org/netbeans/modules/tomcat5/util/TomcatUsersTest.java
- Add identifiers for Tomcat 10 and 10.1
- Add support for TomEE versions from 1.5 to 9
- Improve support for TomEE types and correctly identify them. (Microprofile, Webprofile, etc.)
- Improve Tomcat/TomEE version enum
- Improve Tomcat/TomEE jvm platform support
- Fix the default jvm platform that is pre-selected for Tomcat/TomEE
- Improve logic for supported profiles and jvm platforms for Tomcat and TomEE
- Improve logic for getJavadoc() method for Tomcat and TomEE
- Add missing tomcat versions to some methods
- Add isAtLeast() method to TomcatVersion
- Use enum isAtLeast() method to improve logic
- Improve support for Jakarta EE JaxRS
- Add Tests for new TomEEtype logic
- Add Tests for new Tomcat version comparison
- Add Tests for new TomEE version comparison
- Use generics
- Bump …
> Add Jakarta EE/Java EE support for Tomcat and TomEE

- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/PomModelUtils.java
This is to address a parent.relativePath warning for Maven projects on the Windows platform. The fix was suggested by Mark Herkrath <herkrath@googlemail.com> and mentioned on the dev mailing list. This fixes #5281
---
If you're a committer, please label the …
> Fix for Windows Maven parent.relativePath from Mark Herkrath

- extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java
I've bumped into this one today:
```
java.lang.IllegalArgumentException: object is not an instance of declaring class
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.netbeans.modules.gradle.loaders.LegacyProjectLoader.getLocation(LegacyProjectLoader.java:380)
```
Couldn't really know how to reproduce. I was fiddling with old Gradle versions with the new tooling.
The fix is trivial though...
> Catch IAE when Gradle error getLocation cannot be called.

- .github/workflows/main.yml
- java/java.mx.project/build.xml
- java/java.mx.project/src/org/netbeans/modules/java/mx/project/SuiteProject.java
- java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/ParseSuitesTest.java
- java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/SuiteActionProviderTest.java
- java/java.mx.project/test/unit/src/org/netbeans/modules/java/mx/project/SuiteCheck.java
GraalVM used by `java.mx.project` updated to 22.3.0 release.
> Issue #5250: Update java.mx.project to work with GraalVM 22.3.0 release.

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
If the LSP client added a folder to a workspace, then opened a file, NBLS would ask a question "File XXX is part of project Foo, do you want to open ... ?".  Since the containing folder **was** explicitly adeded the lsp client's user, this question is ... silly. 
It was caused by NBLS did not receive/process `didChangeWorkspaceFolders` notification from the LSP client. On the startup, workspace folders were 'registered' as known and NBLS does not ask "project open question" for files beneath those folders - but when the folders change during NBLS run, the added folders were not 'registered' in the same way.
> Open projects that correspond to workspace folders. Prevents "do you want to open project ?" questions.

- java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
extracted from #4999
This aims to improve the indexing experience by allowing remote index downloads while local `.m2` indices are processed.
CI should produce a dev build for this one for easier testing.
> allow concurrent local indexing while downloading remote indexes.

- java/java.debug/src/org/netbeans/modules/java/debug/TreeNavigatorProviderImpl.java
- java/java.debug/src/org/netbeans/modules/java/debug/TreeNode.java
The AST debug view for Java (`java/java.debug`) has some trouble:
- it has hardcoded all AST node kinds, so if a new AST node kind is added, it needs an update
- the highlight showing the current AST node's span is not cleared when the view is unselected
- the highlight color is really ugly
This patch attempts to improve these aspects.
---
If …
> Improving the Java AST debugging view.

- java/java.source.base/src/org/netbeans/api/java/source/SourceUtils.java
> Prevent NullPointerException when matching filenames in SourceUtils

- ide/languages.toml/src/org/netbeans/modules/languages/toml/TomlLexer.java
- ide/lexer.antlr4/src/org/netbeans/spi/lexer/antlr4/AbstractAntlrLexerBridge.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v3/Antlr3Lexer.java
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/v4/Antlr4Lexer.java
This fix makes ANTLR Token `getText()` and `toString()` methods usable when the lexer is backed by `LexerInputCharStream`. Unfortunately it seems that ANTLR does not really honor their contract when saying some methods can throw `UnsupportedOperationException`. I may file a PR for ANTLR as well, till then, this one makes debugging easier.
I also dared to change the `AbstractAntlrLexerBridge.mapToken(int antlrTokenType)` -> `AbstractAntlrLexerBridge.mapToken(org.antlr.v4.runtime.Token antlrToken)` till it's in this phase. Mappers could take advantage on the full token info as  the `getText()` method is working.
> Made ANTLR Token LexerInputCharStream Friendly

- platform/openide.filesystems/apichanges.xml
- platform/openide.filesystems/manifest.mf
- platform/openide.filesystems/src/org/openide/filesystems/FileObject.java
- platform/openide.filesystems/src/org/openide/filesystems/FileUtil.java
- platform/openide.filesystems/test/unit/src/org/openide/filesystems/FileUtilTest.java
Well as a DevOps engineer, I copy scripts and other executable inside the IDE. They lose the executable flag. That bothers me for years. Here is how I try to fix that.
Also added `FileObject` `Path` conversion methods, to make the life easier.
> Made FileUtil to copy POSIX permissions

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddADBAction.java
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBAddConnection.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/NodeActionsProvider.java
- java/java.lsp.server/vscode/package.json
Adding a new action which registers database connection for ADB from Oracle Cloud
> Adding new action which registers ADB connection

- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-3.0-license.txt
- platform/libs.flatlaf/manifest.mf
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/Installer.java
Update FlatLaf to v3.0.
Changes: https://github.com/JFormDesigner/FlatLaf/releases/tag/3.0
FlatLaf 3 comes with two new themes, which look similar to macOS:
I've added both to the list of look and feels (on all platforms, screenshots are from Windows 11):
FlatLaf 3 has new modern rounded outlined icons for `JFileChooser`, `JOptionPane`, `JPasswordField` and `JTree`:
They are e.g. used in project/file trees and in file choosers (in all FlatLaf themes):
> Update FlatLaf from 2.6 to 3.0 and add macOS light and dark themes

- java/java.source.base/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorker.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/indexing/VanillaCompileWorkerTest.java
- java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBJavaCompiler.java
Recently, I ran into a few problems with indexing massively erroneous source:
- error cleanup does not work for record components. Error should be cleaned for record components.
- if there are multiple pattern switches (preview only feature, currently) only the first may be removed from the code when the errors are being cleared, and the rest might go to `TransPatterns`, failing there. Ensuring pattern switches are cleared while clearing errors if preview is disabled.
- member references referring to methods with erroneous parameters may sometimes be kept, crashing code generator later. Such member references should be removed from the code.
- in some cases, a new source might be parsed while desugaring another, and the current cleaning code fails for that. Need to avoid attempts to clean …
> Improving indexing for erroneous sources.

- php/php.editor/src/org/netbeans/modules/php/editor/PredefinedSymbols.java
- php/php.editor/src/org/netbeans/modules/php/editor/verification/IncorrectEnumHintError.java
- php/php.editor/test/unit/data/testfiles/verification/IncorrectEnumHintError/testIncorrectEnums.php
- php/php.editor/test/unit/data/testfiles/verification/IncorrectEnumHintError/testIncorrectEnums.php.testIncorrectEnums.hints
- Checks declaration of forbidden methods.
- Adds __invoke and __debugInfo to list of magic methods.
Docs:
- https://www.php.net/manual/en/language.enumerations.listing.php
- https://www.php.net/manual/en/class.backedenum.php
- https://www.php.net/manual/en/language.enumerations.object-differences.php
- https://www.php.net/manual/en/language.oop5.magic.php
Closes  #5086, closes  #5094
> Improved method checks in enum declaration

- java/java.lsp.server/vscode/src/nbcode.ts
- platform/o.n.bootstrap/src/org/netbeans/MainImpl.java
This PR patches just the vsnetbeans branch before Apache Language Server for Java  extension release; it could be then picked up by `master` and NB17 - or other solution can be applied.
The Apache Language Server  supposes that **other extensions** can contribute modules (clusters) into Apache Netbeans language server (part of vscode extension). For example we (Oracle) deliver jdbc drivers that cannot be distributed through Apache (e.g. licensing issues).
The original code uses a misfeature that if a `extra_clusters` env variable is defined, and the application's config file (`conf/nbcode.conf` in this case)  **does not** provide a value in its [`conf/app.conf`](https://github.com/apache/netbeans/blob/master/harness/apisupport.harness/release/etc/app.conf#L68) (which is the vscode …
> Temporary fix: Support extra cluster directories.

- java/java.editor/src/org/netbeans/modules/java/editor/javadoc/JavadocCompletionTask.java
- java/java.editor/src/org/netbeans/modules/java/editor/javadoc/TagRegistery.java
- java/java.editor/src/org/netbeans/modules/java/editor/overridden/GoToImplementation.java
- java/java.editor/src/org/netbeans/modules/java/editor/semantic/Bundle.properties
- java/java.editor/src/org/netbeans/modules/java/editor/semantic/UnusedTooltipResolver.java
based on delivery
checks for `ElementKind.RECORD` are missing all over the codebase. The lexer isn't even record aware. This PR only covers `java.editor`. I had a larger changeset which checked all usages of the CLASS enum and added RECORD on a case by case basis. But it is probably not a good idea to do this blindly without being able to validate it properly.
this PR fixes three small bugs which are easily verifiable:
- tooltip on unused records will use the right bundle msg
- javadoc completion for records
- goto impl is now working for records
test code:
```java
package bugs;
public class RecordEnums {
/**
* @see bugs.RecordEnums.
*      check completion ^^^ should have records
*/
record ARecord() { }
record UnusedRecord() { }
// mouse over ^^^ should have tooltip
class AClass { } …
```
> added missing record enums to editor module.

- java/java.hints/src/org/netbeans/modules/java/hints/jdk/mapreduce/PreconditionsChecker.java
fixes #5202, targets delivery
```
java.lang.NullPointerException: Cannot invoke "com.sun.source.util.TreePath.getLeaf()" because "path" is null
at org.netbeans.lib.nbjavac.services.NBJavacTrees.getElement(NBJavacTrees.java:66)
at org.netbeans.lib.nbjavac.services.NBJavacTrees.getElement(NBJavacTrees.java:40)
at org.netbeans.modules.java.hints.jdk.mapreduce.PreconditionsChecker$VariablesVisitor.isLocalVariable(PreconditionsChecker.java:226)
```
`JavacTrees` and `NBJavacTrees` don't accept null as path parameters in the `getElement` method, so we guard against it and return `false`.
> PreconditionsChecker: fixed NPE when path is null.

- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/j2ee/TomcatPlatformImpl.java
As per Tomcat [docs](https://tomcat.apache.org/whichversion.html) Tomcat 11 minimum supported Java is 17
> Tomcat 11 min supported Java is 17

- enterprise/micronaut/nbproject/project.xml
- enterprise/micronaut/src/org/netbeans/modules/micronaut/maven/MicronautPackagingArtifactsImpl.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/layer.xml
- enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/spring-actions-maven.xml
- java/maven/apichanges.xml
- java/maven/nbproject/project.properties
- java/maven/src/org/netbeans/modules/maven/api/execute/RunUtils.java
There's a springboot module on the Plugin portal, but that one does not handle native-image compilation. Longer term, I'd like to create a dedicated native-image supporting module(s) and move the gradle+maven plugin support there. But for NBLS immediate release and NB17 release, I'd like to include a very trivial springboot support - Micronaut module is a good enterprise cluster candidate to make homeplace for it.
The PR adds ability to run native compilation from the NetBeans IDE based on springboot plugin support. In addition, springboot projects are configured differently to micronaut projects - the changes in `MicronautPackagingArtifactsImpl`  make the impl more compatible with various setups, as it now reacts on the plugin's goal regardless of whether the plugin is bound to the …
> Springboot artifacts fix

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletAction.java
This PR fixes two issues with OCI database support:
The `Download Wallet` action writes a JDBC connection string with a pathname in it, but the pathname is not properly escaped. This is not an issue on MacOS / Linux, but on Windows that uses backslashes as dir separators, the backslashes in string content are interpreted as escapes by the JDBC driver, and the resulting path will be broken.
Second, the action tries to find the appropriate JDBC driver, but `JDBCDriverManager.getDefault().getDrivers()` call may reeturn half-configured drivers, that have no JAR files associated with them. This PR makes the action to prefer such drivers that define jars with the actual driver code.
The original behaviour had the effect of selecting a wrong driver, i.e. OracleThin driver (without JARs) was …
> Proper escaping of TNS_ADMIN path. Select JDBC driver with defined implementation.

- java/java.source.base/src/org/netbeans/modules/java/source/save/Reformatter.java
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/save/FormatingTest.java
fixes #4399 targets delivery
had a hard time figuring out how the `Reformatter` works since not much is documented there, But the fix turned out to be only a small change. Comparing `scanRecord` with other methods helped a bit.
> Annotated record reformatting fix

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddADBAction.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletAction.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletDialog.java
Following the discussion in #5387, this PR cherry-picks master changes and resolves conflicts so the contents of the conflicted file is the same as in vsnetbeans_1603.
> Fix AddADBAction and DownloadWalletAction in delivery

- java/lib.nbjavac/src/org/netbeans/lib/nbjavac/services/NBAttr.java
- java/spi.java.hints/src/org/netbeans/modules/java/hints/spiimpl/batch/BatchSearch.java
- java/spi.java.hints/test/unit/src/org/netbeans/modules/java/hints/spiimpl/batch/BatchSearchTest.java
If hints are run on save, `BatchSearch` is called on a single file. Normally, if javac would crash during `toPhase`, an exception would be thrown. But, it may happen the existing parser is reused, and `toPhase` does not throw the exception, and this may be mistaken for an out-of-memory situation, to which the response is to restart the processing. This may then lead to an infinite loop.
The proposed change here is to force progress in this situation. javac crash(es) need to be handled separately, of course.
---
- are contributed solely under the terms and conditions of the Apache License 2.0 …
> [NETBEANS-4054] Ensuring progress when javac crashes while batch evaluating hints.

- php/php.editor/src/org/netbeans/modules/php/editor/actions/UsedNamesCollector.java
- php/php.editor/src/org/netbeans/modules/php/editor/model/impl/Type.java
- php/php.editor/src/org/netbeans/modules/php/editor/model/impl/VariousUtils.java
- php/php.editor/src/org/netbeans/modules/php/editor/verification/IdenticalComparisonSuggestion.java
- php/php.editor/test/unit/data/testfiles/actions/useCase_09.php
- php/php.editor/test/unit/data/testfiles/actions/useCase_09.php.usedNames
- php/php.editor/test/unit/data/testfiles/actions/useCase_10.php
- php/php.editor/test/unit/data/testfiles/actions/useCase_10.php.usedNames
- php/php.editor/test/unit/data/testfiles/codegen/testInstanceOverrideMethodWithGuessingBoolType/testInstanceOverrideMethodWithGuessingBoolType.php
- php/php.editor/test/unit/data/testfiles/codegen/testInstanceOverrideMethodWithGuessingBoolType/testInstanceOverrideMethodWithGuessingBoolType.php.testInstanceOverrideMethodWithGuessingBoolType_01.codegen
- php/php.editor/test/unit/data/testfiles/codegen/testInstanceOverrideMethodWithGuessingBoolType/testInstanceOverrideMethodWithGuessingBoolType.php.testInstanceOverrideMethodWithGuessingBoolType_02.codegen
- php/php.editor/test/unit/data/testfiles/completion/lib/tests235450/issue235450.php.testLowercase_01.completion
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/actions/UsedNamesCollectorTest.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/codegen/SelectedPropertyMethodsCreatorTest.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/typinghooks/PhpCommentGeneratorTest.java
What was done in this PR:
- deleted the built-in type `boolean`
( php does not have a built-in `boolean` type: https://www.php.net/manual/en/language.types.intro.php
Also see the warning under "Scalar Types": https://www.php.net/manual/en/language.types.declarations.php)
- fixed broken tests
- fixed issues: 
- #5283, 
- #5284
- new tests for fixed issues have been added
> PHP: removed built-in type boolean

- enterprise/micronaut/src/org/netbeans/modules/micronaut/maven/MicronautMavenConstants.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/maven/MicronautPackagingArtifactsImpl.java
Starting from Micronaut 3.8.x, micronaut plugins configure execution for `compile` goal rather than for the (now deprecated) `build` goal of the Graalvm native-image plugin.  
This PR allows to detect native compilation in older AND newer project setups. Instead of just `build` all the 'building' goals are checked: according to [the documentation](https://graalvm.github.io/native-build-tools/latest/maven-plugin.html) and `mvn help:describe`:
```
native:add-reachability-metadata
Description: (no description available)
native:build
Description: (no description available)
native:compile
Description: (no description available)
native:compile-no-fork
Description: (no description available)
native:generateResourceConfig
Description: (no description available)
native:generateTestResourceConfig …
```
> React on both build and compile goals.

- ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/GoToMarkOccurrencesAction.java
- ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/MarkOccurrences.java
- ide/lsp.client/src/org/netbeans/modules/lsp/client/bindings/refactoring/RefactoringActionsProvider.java
Observed exception:
```
java.lang.NullPointerException: Cannot invoke "javax.swing.text.Caret.getDot()" because "this.caret" is null
at java.desktop/javax.swing.text.JTextComponent.getCaretPosition(JTextComponent.java:1704)
at org.netbeans.modules.lsp.client.bindings.MarkOccurrences.<init>(MarkOccurrences.java:71)
at org.netbeans.modules.lsp.client.bindings.TextDocumentSyncServerCapabilityHandler.lambda$registerBackgroundTasks$6(TextDocumentSyncServerCapabilityHandler.java:330)
at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
at …
```
> LSP client: Prevent NullPointerException when caret is not present on text component

- java/java.graph/src/org/netbeans/modules/java/graph/NodeWidget.java
I noticed a problem using the Graph of a POM when a dark theme is selected.
The foreground color was requested from the Theme while backgrounds are hardcoded into the Class causing printing WHITE on Bright Colors.
With this fix I added transparency to these hardcoded colors so the become darker on darker backgrounds.
I also removed gradients that looked a bit outdated to my eyes.
> Fix POM Graph colors for dark themes

- java/java.editor.lib/nbproject/project.properties
- java/maven/nbproject/project.properties
Fixes increment on `maven` and `java.editor.lib` modules for NB18. Both were missed by the increment Ant task used for #5312  due to use of a colon to separate key and value. Maven module syntax was fixed in later PR for 17, but needs an additional increment for NB18.
See https://github.com/apache/netbeans/pull/5352#discussion_r1087643842
Code that doesn't work with colon is at https://github.com/apache/netbeans/blob/master/nbbuild/antsrc/org/netbeans/nbbuild/IncrementSpecificationVersions.java#L96  Of course, that could also be used as a deliberate way of bypassing increment?!
> Fix increment on maven and java.editor.lib module for NB18

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/NotifyDescriptorAdapter.java
The LSP implementation of `DialogDisplayer` ignored [`NotifyDescriptoir.getAdditionalOptions()`](https://bits.netbeans.org/dev/javadoc/org-openide-dialogs/org/openide/NotifyDescriptor.html#getAdditionalOptions--) completely. This PR merges the additional options with the standard ones, similar to the original DialogDescriptor implementation (actually `NbPresenter`).
> Display additional options prior to the standard ones.

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/LspProgressUIWorker.java
During testing of #5361, I've found out that the `LspInternalHandle` receives SWITCH event as the first one (as a result of the switch to indeterminate status), and does not report start event to the LSP client at all. As a result the progress indicator is never created in LSP client and the progress for long-running operation may remain unreported.
`sendProgress` will first send `start` event to the client, if not already started.
> Report progress start when handle immediately switches to indeterminate.

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCINode.java
- ide/db/src/org/netbeans/modules/db/explorer/action/ConnectAction.java
- ide/db/src/org/netbeans/modules/db/explorer/node/ConnectionNode.java
"Refresh" action is available on OCI nodes including the leaves; but a leaf has no `factory` set, so refresh is likely to NPE. 
The `Connect` action implementation was written so that it blocked the UI thread with a modal dialog and/or sync with the background DB connection. It should have been rewritten probably more thoroughly, but at the least I've changed the action to `asynchronous=true` - I needed to restructure it to implement `ActionListener` + `ContextAwareAction` so that it properly reports DB connection changes through action's enable once instantiated. Asynchronous=true does not work well for `NodeActions` (default constructor must not be present).
Asynchronous processing is desirable in the headless mode, when the blocked "ui" thread is actually usually the message-processing …
> Various database fixes

- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/deploy/TomcatManager.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/j2ee/JpaSupportImpl.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/j2ee/TomcatPlatformImpl.java
- Add logic to support two default provider for TomEE PluME
- Add logic to support up to JPA 2.1
- Add methods to support JPA 2.2 and 3.0; when available in NetBeans
- Fix [Issue-4146](https://github.com/apache/netbeans/issues/4146) 
Testing:
- Verify successful execution of Sigtests
- Download every version of TomEE and successfully:
- Register it
- Create Web App Project
- Check correct creation of persistence unit with JPA 1.0, 2.0 and 2.1
- Deploy and run a servlet
> Improve TomEE support for JPA (Fix 4146)

- enterprise/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/multiview/TextItemEditorModel.java
- enterprise/j2ee.sun.ddui/src/org/netbeans/modules/j2ee/sun/ddloaders/multiview/TextItemEditorModel.java
- enterprise/web.debug/src/org/netbeans/modules/web/debug/breakpoints/JspLineBreakpoint.java
- ide/schema2beans/src/org/netbeans/modules/schema2beans/BaseBean.java
- ide/schema2beans/src/org/netbeans/modules/schema2beans/BeanComparator.java
- ide/subversion/src/org/netbeans/modules/subversion/ui/status/VersioningPanel.java
- java/api.debugger.jpda/src/org/netbeans/api/debugger/jpda/ExceptionBreakpoint.java
- java/api.debugger.jpda/src/org/netbeans/api/debugger/jpda/FieldBreakpoint.java
- java/api.debugger.jpda/src/org/netbeans/api/debugger/jpda/MethodBreakpoint.java
- java/dbschema/src/org/netbeans/modules/dbschema/jdbcimpl/SchemaElementImpl.java
- java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/models/BoldVariablesTableModelFilter.java
- java/debugger.jpda.visual/src/org/netbeans/modules/debugger/jpda/visual/breakpoints/ComponentBreakpoint.java
- java/i18n.form/src/org/netbeans/modules/i18n/form/I18nServiceImpl.java
- java/i18n/src/org/netbeans/modules/i18n/I18nString.java
- platform/core.startup.base/src/org/netbeans/core/startup/layers/NbinstURLStreamHandler.java
- platform/openide.windows/src/org/openide/windows/TopComponent.java
Objects.equals() implements normalized comparsion operations for two objects.
Different forms of comparison are reduced to the normalized.
No any changes for references check are made.
> Cleanup by simplifying strings comparsion with JDK7 Objects.equals()

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletDialog.java
- java/java.lsp.server/vscode/src/extension.ts
1/ typo fix in DB password prompt
2/ make QuickPicks displayed by LSP client `ignoreFocusOut` by default. In NetBeans, revelevant dialogs are typically modal, so this is a better LSP metaphore.
> Minor / typo fixes

- platform/core.windows/src/org/netbeans/core/windows/services/DialogDisplayerImpl.java
- platform/core.windows/src/org/netbeans/core/windows/services/NbPresenter.java
- platform/openide.util.ui/src/org/openide/util/Utilities.java
When placing a dialog through NetBeans' API, if no focused component is found then use NbMainWindow. Change fallback for Utilities.findDialogParent to use NbMainWindow.
@matthiasblaesing , @neilcsmith-net , @mbien alerting since you made comments on previous PR.
This PR is a follow on to https://github.com/apache/netbeans/pull/4739. Wanted to open a bigger change earlier in the cycle, but... So this is a minimal change, hopefully more to come next cycle with detailed examination of cases from https://github.com/apache/netbeans/discussions/4887.
There are situations where
```
null == KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusedWindow();
```
And also related methods such as `getFocusOwner()`, `getActiveWindow()` are `null`.
What happens is …
> Improve Dialog Placement

- java/java.graph/manifest.mf
- java/java.graph/src/org/netbeans/modules/java/graph/DependencyGraphScene.java
- java/java.graph/src/org/netbeans/modules/java/graph/GraphNode.java
- java/maven.graph/nbproject/project.xml
- java/maven.graph/src/org/netbeans/modules/maven/graph/MavenAction.java
The two actions:
org.netbeans.modules.maven.graph.FixVersionConflictAction
org.netbeans.modules.maven.graph.ExcludeDepAction
need to manipulate the duplicate or conflict list. The returned set is read-only, so a companion method to addDuplicateOrConflict removeDuplicateOrConflict is added to remove a node from the list.
Closes: #5402
> UnsupportedOperationException in maven dependency graph "Exclude dependency" and "Fix Version Conflict" actions

- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
- enterprise/glassfish.eecommon/src/org/netbeans/modules/glassfish/eecommon/api/config/J2eeModuleHelper.java
- enterprise/glassfish.eecommon/src/org/netbeans/modules/glassfish/eecommon/api/config/ServletVersion.java
- enterprise/glassfish.javaee/src/org/netbeans/modules/glassfish/javaee/Hk2DeploymentFactory.java
- enterprise/glassfish.javaee/src/org/netbeans/modules/glassfish/javaee/Hk2JavaEEPlatformFactory.java
- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/ConfigBuilderProvider.java
- enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersionTest.java
- enterprise/j2ee.sun.dd/src/org/netbeans/modules/j2ee/sun/dd/api/ASDDVersion.java
- Add missing validations for servlet 5 and 6
- Add missing glassfish 4 objects in ASDDVersion class
- Verify successful execution of unit tests for modules glassfish.common, glassfish.javaee, glassfish.tooloing, glassfish.eecommon and j2ee.sun.dd
- Successfully register GlassFish 7.0.1, create a web app and verify that it works.
> Add support for Glassfish 7.0.1

- java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/unit/PersistenceUnitWizardPanelDS.java
- java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/unit/PersistenceUnitWizardPanelJdbc.java
The ComboboxHelper is already initialized in an asyc task a few statements before. See sister class `PersistenceUnitWizardPanelJdbc.java`
- Verify successful execution of unit tests for module j2ee.persistence
> Fix double initialization of comboHelper in Persistence Provider

- java/java.editor/src/org/netbeans/modules/java/editor/resources/DefaultAbbrevs.xml
- java/java.editor/test/qa-functional/data/goldenfiles/org/netbeans/test/java/editor/codetemplates/CodeTemplatesTest/testDumpTemplates.pass
This is a pull request for 2 new code templates in NetBeans:
- rt for "return true;"
- rf for "return false;"
Reasons:
- Both are used quite often. For example NetBeans source code has more than 14,000 "return true;" and more than 20,000 "return false;"
- They are consistent with the following existing code template in NetBeans: "re" for "return" and "rn" for "return null;"
- Easy to remember: just like rn for return null; 't' for true and 'f' for false
- Easy to use: rt and rf are next each other on the keyboard
- I've been using these code templates for at least 2 years and they remain ones of the main code templates I use
> New rt and rf abbrevations for return true; and return false;

- php/php.dbgp/src/org/netbeans/modules/php/dbgp/models/VariablesModelFilter.java
Changes default setting of filter for NULL values in PHP debugger.
Based on personal experience when I need to turn display of NULL values for almost every debugging session.
> PHP Debugger - show NULL values by default

- java/java.lsp.server/vscode/package.json
Other extension may need to add actions to project node. But without (any) group, the commands order alphabetically and after all defined groups. All project build-clean actions should form one group, but allow some prior groups to be present.
> Group and define order for project actions.

- enterprise/micronaut/test/unit/data/gradle/artifacts/multi/gradle.properties
- java/jshell.support/src/org/netbeans/modules/jshell/editor/ConsoleEditor.java
- java/maven/src/org/netbeans/modules/maven/modelcache/MavenProjectCache.java
During testing of NB17, I've seen some messages printed to the console that should not be there.
1/ Maven creates a fallback project, if the pom.xml cannot be read into the model. This is a fairly common, either because of malformed XML, inaccessible basic build plugin (i.e. empty repository) etc. Should be logged, but not at INFO level - that is likely a leftover after debugging maven actions.
```
Reload broken project (clean repository): diagnostic message
INFO [org.netbeans.modules.maven.modelcache.MavenProjectCache]: Creating fallback project for /space/tmp/vsc2/src/microtest/pom.xml
java.lang.Throwable
at org.netbeans.modules.maven.modelcache.MavenProjectCache.getFallbackProject(MavenProjectCache.java:358)
at org.netbeans.modules.maven.modelcache.MavenProjectCache.loadOriginalMavenPro …
```
> Fix spurious messages printed to the console.

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/ProjectVulnerability.java
Simple fix: during refactoring of the `ProjectVulnerability`, I have made `setKnowledgeBase` to persist the value in project setting, but did not adapt the runAudit to call `setKnowledgeBase0`.
> Audits should not automatically change persistent project settings.

- php/php.editor/src/org/netbeans/modules/php/editor/verification/UnusableTypesHintError.java
- php/php.editor/test/unit/data/testfiles/verification/UnusableTypesHintError/testDuplicateTypes_01.php
- php/php.editor/test/unit/data/testfiles/verification/UnusableTypesHintError/testDuplicateTypes_01.php.testDuplicateTypes_01.hints
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/verification/UnusableTypesHintErrorTest.java
Goes through all types and does not return on first error.
Partial fix for #5072
> Fixed detection of duplicate types

- java/java.source/src/org/netbeans/modules/java/classfile/BinaryElementOpenImpl.java
- java/java.source/src/org/netbeans/modules/java/classfile/CodeGenerator.java
- java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementOpen.java
I am still improving support for [Enso sbt projects](https://github.com/enso-org/enso/tree/develop/tools/enso4igv) in NetBeans and [GraalVM's IGV](https://github.com/oracle/graal/tree/master/visualizer). This time I'd like to improve support for _"Go to type"_.
The idea is to check _source attribute_ of parsed `.class` file as soon as _binary open_ parses the file. If the attribute is present and `FileObject` of such name can be find in provided classpaths, open it instead of disassembling the class file.
> GoToType dialog checks source attribute before disassembling bytecode

- .github/ISSUE_TEMPLATE/netbeans_bug_report.yml
- .github/ISSUE_TEMPLATE/netbeans_feature_request.yml
Update issue forms for NetBeans 17 release, and try and work around some GitHub form changes.
In particular, GitHub have changed required dropdowns to pre-select the first option.  This means a lot more people are volunteering pull requests! :smile:  It also makes the code of conduct dropdown pointless.
Swapped the pull request values, made the package selection multiple choice (will hopefully help with this issue and possible people are using multiple), and made the code of conduct section just markdown.  Left old settings commented in the hope GitHub reverse this daft choice.
> Update issue forms for NB17 and fix for some GitHub changes

- .github/ISSUE_TEMPLATE/netbeans_bug_report.yml
- .github/ISSUE_TEMPLATE/netbeans_feature_request.yml
It appears that, despite the issue form documentation, markdown headers aren't working.  Apologies for the noise!
> Remove non-working header from GitHub issues markdown.

- .github/workflows/main.yml
- README.md
- nbbuild/antsrc/org/netbeans/nbbuild/CheckModuleConfigs.java
- nbbuild/cluster.properties
both configs have the same set of clusters at the moment
This would allow us to test more clusters than those which are in the release config.
My only concern is that the order is different:
```
release:
nb.cluster.cpplite,\
nb.cluster.groovy,\
nb.cluster.php,\
${clusters.config.java.list},\
nb.cluster.apisupport,\
nb.cluster.webcommon,\
nb.cluster.enterprise
nb.cluster.ergonomics
full:
${clusters.config.java.list},\
nb.cluster.apisupport,\
nb.cluster.webcommon,\
nb.cluster.php,\
nb.cluster.groovy,\
nb.cluster.enterprise,\
nb.cluster.cpplite,\
nb.cluster.ergonomics 
```
we have to make sure that this won't cause any issues, since we would notice those issues super late. Best option would be to make sure both have the same order, but allow slightly different content.
edit: cleaned up the …
> switch CI from release to full cluster config.

- php/php.editor/src/org/netbeans/modules/php/editor/actions/FixUsesPerformer.java
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/01/B.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/01/testGH5578_01.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/01/testGH5578_01.php.fixUses
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/02/B.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/02/testGH5578_02.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/02/testGH5578_02.php.fixUses
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/03/testGH5578_03.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/03/testGH5578_03.php.fixUses
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/04/testGH5578_04.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/04/testGH5578_04.php.fixUses
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/05/testGH5578_05.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/05/testGH5578_05.php.fixUses
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/06/testGH5578_06.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/06/testGH5578_06.php.fixUses
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/07/testGH5578_07.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/07/testGH5578_07.php.fixUses
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/08/B.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/08/testGH5578_08.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5578/08/testGH5578_08.php.fixUses
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/actions/FixUsesPerformerTest.java
Fix "Fix Import" namespaces/uses placement in multiple php open tag files, when first line of php file is not empty or it is a block element, after declare statements in different scope
> Fix #5578 namespaces/use placement

- java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/MarkOccurrencesHighlighterBase.java
- java/java.editor/src/org/netbeans/modules/editor/java/JavaCodeTemplateProcessor.java
- java/java.hints/src/org/netbeans/modules/java/hints/bugs/Tiny.java
- java/java.hints/src/org/netbeans/modules/java/hints/errors/CreateElementUtilities.java
- java/java.hints/src/org/netbeans/modules/java/hints/errors/Utilities.java
- java/java.hints/src/org/netbeans/modules/java/hints/introduce/InstanceRefFinder.java
- java/java.hints/src/org/netbeans/modules/java/hints/suggestions/ExpectedTypeResolver.java
- java/java.hints/src/org/netbeans/modules/java/hints/suggestions/Lambda.java
- java/java.navigation/src/org/netbeans/modules/java/navigation/CaretListeningTask.java
- java/java.navigation/src/org/netbeans/modules/java/navigation/ElementNode.java
- java/java.source.base/src/org/netbeans/api/java/source/CodeStyle.java
- java/java.source.base/src/org/netbeans/api/java/source/DocTreePathHandle.java
- java/java.source.base/src/org/netbeans/api/java/source/GeneratorUtilities.java
- java/java.source.base/src/org/netbeans/api/java/source/TreePathHandle.java
- java/java.source.base/src/org/netbeans/modules/java/source/indexing/CheckSums.java
- java/java.source/src/org/netbeans/modules/java/classfile/AttachSourcePanel.java
- java/refactoring.java/src/org/netbeans/modules/refactoring/java/plugins/RenameRefactoringPlugin.java
- java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/MoveMembersPanel.java
- java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/UIUtilities.java
- java/refactoring.java/src/org/netbeans/modules/refactoring/java/ui/WhereUsedQueryUI.java
- platform/openide.util/src/org/netbeans/modules/openide/util/NbBundleProcessor.java
#5339 had the bits which were easily verifiable as bugs.
This PR is the bulk version of it. I searched for `ElementKind.CLASS` usage and tried to find out on a case by case basis if `RECORD` was missing based on what the code does. I didn't actually try to reproduce issues in the IDE for most of this since this would be too time consuming for all changes.
I am not sure if this is the right approach of doing this, but most changes here seemed fairly obvious/trivial so I hope this doesn't break anything.
This doesn't investigate missing `RECORD_COMPONENT` enums or add the record token to the lexer.
> Bulk added some missing ElementKind.RECORD enums.

- enterprise/websvc.restlib/src/org/netbeans/modules/websvc/swdp/swdp.xml
- java/j2ee.eclipselink/external/binaries-list
- java/j2ee.eclipselink/external/eclipselink-2.7.12-license.txt
- java/j2ee.eclipselink/nbproject/project.properties
- java/j2ee.eclipselink/nbproject/project.xml
- java/j2ee.eclipselink/src/org/netbeans/modules/j2ee/eclipselink/eclipselink_lib.xml
- java/j2ee.eclipselinkmodelgen/external/binaries-list
- java/j2ee.eclipselinkmodelgen/external/eclipselink-2.7.12-license.txt
- java/j2ee.eclipselinkmodelgen/nbproject/project.properties
- java/j2ee.eclipselinkmodelgen/src/org/netbeans/modules/j2ee/eclipselinkmodelgen/eclipselinkmodelgen_lib.xml
- java/j2ee.jpa.refactoring/nbproject/project.properties
- java/j2ee.metadata.model.support/nbproject/project.properties
- java/j2ee.persistence/nbproject/project.properties
- java/j2ee.persistenceapi/nbproject/project.properties
- nbbuild/licenses/EPL-v10-eclipselink
Library Notes:
- This is mainly a maintenance release and contains bug fixes
- Verify successful execution of unit tests for modules `websvc.restlib`, `j2ee.eclipselink`, `j2ee.eclipselinkmodelgen`, `j2ee.jpa.refactoring`, `j2ee.metadata.model.support`, `j2ee.persistence` and `j2ee.persistenceapi`
- Checked the files are in the Ant Library Manager
- Successfully create project as per [NetBeans Documentation](https://netbeans.apache.org/kb/docs/websvc/rest.html), with MariaDB, TomEE 8 plus and GlassFish 5.1.0
[EclipseLink Web Page](https://www.eclipse.org/eclipselink/)
[EclipseLink Release …
> Upgrade EclipseLink from 2.7.10 to 2.7.12

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/OCIProfile.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddADBAction.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/progress/LspInternalHandle.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/NotifyDescriptorAdapter.java
The user was presented with a selector for tenancies when asked to locate an autonomous DB from the OCI. But tenancy is not that descriptive and it's better when the user gets a selector for profiles, which usually have names meaningful to the user. Tenancy name and its region are still interesting as detail info.
This PR changes the chooser to present profiles, with tenancy+region as detail of the presented choice.
In addition, two bugs were fixed:
- a progress detail message may be coalesced into the start event, but [was not sent to the client](https://github.com/apache/netbeans/pull/5543/files#diff-1027bccfaaf5f4f1d222a283acbbd61d93bf25b5512b88a24ca1a423781af527R156)
- the creation of next `NotifyDescriptor` step in `NotifyDescriptor.ComposedInput` may block when gathering …
> When adding an Autonomous DB, present profiles instead of tenancies

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/AuditOptions.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/AuditResult.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/ProjectVulnerability.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/VulnerabilityWorker.java
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/ExtraGsonSetup.java
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/commands/ProjectAuditCommand.java
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/commands/ProjectMetadataCommand.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/LspGsonSetup.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbGsonAdapter.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
This PR extends the LSP command 'project.audit.execue/display' with several options that customize UI behaviour. In addition, the command can return the data back to the vscode for custom presentation of the result.
In the supplemental commit, I have moved  GSON (de)serialization helpers from integration module to the base LSP one and configured the server's GSON, so now some NetBeans objects can be used as results from LSP functions and will be serialized in some sane way to the JSON returned to the LSP client.
> OCI Audit project command LSP API

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBDecorationProvider.java
- java/java.lsp.server/vscode/package.json
This is Database connection context menu cleanup GCN-1406
- Action names were renamed and reordered
- Database connect/disconnect actions are displayed based on connection status. 
- Database connection status is exported via TreeItem.contextValue and available in VS Code 'viewItem'
> LSP: Database connection context menu cleanup

- enterprise/payara.micro/src/org/netbeans/modules/fish/payara/micro/project/ui/MicroProjectWizardIterator.java
On generating the Payara Micro project use the Payara Micro Maven Archetype version `1.4.0`  for Payara Micro `5.x` and the latest version of Archetype for Payara Micro `6.x`.
> FISH-7082 Use Payara Micro Maven Archetype 1.x/2.x release binary for respective Payara Micro 5.x/6.x

- java/java.lsp.server/vscode/package.json
- java/java.lsp.server/vscode/src/explorer.ts
- java/java.lsp.server/vscode/src/extension.ts
The DB view initializes asynchronously, and in the meantime, before the "Connections" node's children are fetched (possibly empty!), the area shows the Welcome view.
In this PR a new decorating wrapper/callback is defined, that allows to process children returned from the NBLS. The DB view uses that to enable the welcome view only if the number of connections (children of the root node) is 0.
> Display DB welcome only when no connections are defined.

- ide/lexer.antlr4/src/org/netbeans/spi/lexer/antlr4/LexerInputCharStream.java
It seems getText() calls (only seen at error handling so far) from ANTLR could cause and assertion at [LexerInput.readText()](https://github.com/apache/netbeans/blob/5934827e80797ec9b93ff28635ce7fca12627a70/ide/lexer/src/org/netbeans/spi/lexer/LexerInput.java#L257)
This PR makes sure that we call the readText method with arguments that satisfy that condition.
> Fix case when ANTLR getText() causes assertion in LexerInput.

- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/admin/AdminFactory.java
- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/ConfigBuilderProvider.java
- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/GlassFishV7_0_1.xml
- enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/admin/AdminFactoryTest.java
- enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersionTest.java
- enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/utils/EnumUtilsTest.java
- enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/utils/JarTest.java
- enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/utils/ServerUtilTest.java
Library Notes:
- This is mainly a maintenance release that contains bug fixes and updates of various components.
- Verify successful execution of unit tests for modules glassfish.common, glassfish.javaee, glassfish.tooloing, glassfish.eecommon and j2ee.sun.dd
- Successfully register GlassFish 7.0.2, create a web app and verify that it works.
[Release Notes](https://github.com/eclipse-ee4j/glassfish/releases/tag/7.0.2)
> Add support for GlassFish 7.0.2

- rust/rust.grammar/src/org/netbeans/modules/rust/grammar/RustLanguageLexer.java
- rust/rust.grammar/src/org/netbeans/modules/rust/grammar/antlr4/RustLexerBase.java
@vieiro You might this one. I have not tested this trough, it just compiles.
The NB lexer saves/restores the lexer input at some wierd positions, and if the ANTLR lexer state is not fully saved/restored it can cause wide range of issues.
> Save/restore the ANTLR RustLexer specific internals.

- java/maven/src/org/netbeans/modules/maven/output/TestOutputListenerProvider.java
```
java.lang.NullPointerException: Cannot invoke "org.netbeans.modules.maven.api.output.OutputVisitor$Context.getCurrentProject()" because the return value of "org.netbeans.modules.maven.api.output.OutputVisitor.getContext()" is null
at org.netbeans.modules.maven.output.TestOutputListenerProvider.processLine(TestOutputListenerProvider.java:127)
at org.netbeans.modules.maven.execute.AbstractOutputHandler.processLine(AbstractOutputHandler.java:293)
at org.netbeans.modules.maven.execute.CommandLineOutputHandler$Output.run(CommandLineOutputHandler.java:338)
at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
```
This can be …
> fixes a NPE in TestOutputListenerProvider (maven output handler).

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/DefaultDecorationsImpl.java
Make sure CTXVALUE_CAP_DELETE is added to context value only for nodes, which can be deleted.
> LSP: Fix Delete action in context menu

- java/java.lsp.server/vscode/src/extension.ts
Invoke 'java.db.preferred.connection' command only for database connection node and not for all database nodes, which are marked with `class:ddl.DBConnection` context value.
> LSP: Fix too many invocation of 'java.db.preferred.connection'

- ide/xml.axi/nbproject/project.properties
- ide/xml.xdm/nbproject/project.properties
- php/php.editor/nbproject/project.properties
- webcommon/javascript2.editor/nbproject/project.properties
This removes the last remaining "-Xmx" overrides from the project.properties. The option does not seem to be used and the property definition overrides a previous one.
In addition the "build.compiler=extJavac" option is removed as the build run correctly without this.
> Remove unnessary build options from project definitions

- java/java.lsp.server/vscode/BUILD.md
- java/java.lsp.server/vscode/README.md
Use JDK11+ for building VSNetBeans, removal of JDK8 mentions.
> Remove JDK8 as minimum for build of VSNetBeans.

- ide/editor.completion/apichanges.xml
- ide/editor.completion/src/org/netbeans/modules/editor/completion/CompletionLayout.java
- ide/editor.completion/src/org/netbeans/spi/editor/completion/CompletionItem.java
This PR adds a method CompletionItem.shouldSingleClickInvokeDefaultAction() that can optionally be implemented by editor completion item implementations. If this method is overridden to return true, a completion item will be inserted after a single click, as opposed to the existing default behavior which is to require a double-click.
This allows platform applications to use the Editor Completion API to implement combobox-like behavior. E.g. in [Ultorg](https://www.ultorg.com/) below:
(The existing double-click behavior still makes sense as a default, because the user may be clicking the item once to show documentation.)
> Added CompletionItem.shouldSingleClickInvokeDefaultAction to the Editor Completion API

- java/java.lsp.server/vscode/src/extension.ts
Limit findPath to file URLs only to prevent java.net.MalformedURLException on server side.
> VSCode: Limit findPath to file URLs only.

- ide/db.drivers/external/binaries-list
- ide/db.drivers/external/postgresql-42.5.4-license.txt
- ide/db.drivers/nbproject/project.properties
- ide/db.drivers/src/org/netbeans/modules/db/drivers/Bundle.properties
- ide/db.drivers/src/org/netbeans/modules/db/drivers/PostgreSQLDriver.xml
- ide/db.drivers/src/org/netbeans/modules/db/drivers/db2.xml
- ide/db.drivers/src/org/netbeans/modules/db/drivers/informix.xml
- ide/db.drivers/src/org/netbeans/modules/db/drivers/layer.xml
- ide/db.drivers/src/org/netbeans/modules/db/drivers/mariadb.xml
- ide/db.drivers/src/org/netbeans/modules/db/drivers/mssql.xml
- ide/db.drivers/src/org/netbeans/modules/db/drivers/postgresql.xml
This is mainly a maintenance release and contains bug fixes.
[Releases Notes](https://jdbc.postgresql.org/documentation/changelog.html)
- Include more database driver templates:
- IBM DB2 
- IBM Informix
- Microsoft SQL
- MariaDB
- Started NetBeans and ensure the log didn't have any errors or new warnings
- Checked that the file had been downloaded and referenced inside the Ant Library Manager
`jar:nbinst://org.netbeans.modules.db.drivers/modules/ext/postgresql-42.5.4.jar!/`
- Verify the new JDBC driver templates
> Upgrade PostgreSQL JDBC driver to 42.5.4

- .github/workflows/main.yml
- ide/csl.api/test/unit/src/org/netbeans/modules/csl/api/test/CslTestBase.java
fix php folding test on JDK 11+ by opening the document in advance.
`FoldingScanner#folds` calls `source.getDocument(false)` and receives non
null values on JDK 8. On JDK 11+ however the document is null, which
leads to test failures in `FoldingTest#testPHPTags` it is not known why
this happens but this fixes it by making sure the document is open
before folds are computed
note: this was likely a race condition since the php job was observed to be green on linux if restarted often enough (https://github.com/apache/netbeans/issues/4904#issuecomment-1383155575).
lets see if something else fails (edit: everything green on first attempt)
meta issue: #4904
failure was:
```
Testcase: testPHPTags(org.netbeans.modules.php.editor.csl.FoldingTest):	FAILED
Not matching goldenfile: …
```
> Test PHP cluster on JDK 11 and fix tests where needed

- java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
- indexing will disable itself if the index failed to extract due to no space left on the device (temp or cache) and notify the user. Once #5646 is merged we could potentially change this to disable only the remote indexing and keep local indexing active
- take cause and suppressed exceptions into account while scanning for "no space" messages in the exception
- added a fallback to clean up remaining files on exception, this doesn't handle the gz itself since this isn't under our control (yet #4999 would help there)
- simplified the code a bit
(note: the numbers on the screenshot make no sense since I tested while using different paths to ram disks to simulate low storage, in reality one of the two would be very low)
regarding cancelling: It can happen that while the download or …
> Improved maven indexer failure modes in low space situations

- php/php.editor/src/org/netbeans/modules/php/editor/verification/ReturnTypeHintError.java
- php/php.editor/test/unit/data/testfiles/verification/ReturnTypeHintError/testNeverReturnTypeHint.php.testNeverReturnTypeHint_02.hints
- php/php.editor/test/unit/data/testfiles/verification/ReturnTypeHintError/testReturnStatementWithoutValueHintError.php
- php/php.editor/test/unit/data/testfiles/verification/ReturnTypeHintError/testReturnStatementWithoutValueHintError.php.testReturnStatementWithoutValueHint_03.hints
- php/php.editor/test/unit/data/testfiles/verification/ReturnTypeHintError/testReturnStatementWithoutValueHintError.php.testReturnStatementWithoutValueHint_04.hints
- php/php.editor/test/unit/data/testfiles/verification/ReturnTypeHintError/testVoidReturnTypeHint.php.testVoidReturnTypeHint_02.hints
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/verification/ReturnTypeHintErrorTest.java
Adding a new hint that checks if the return statement has a value if the return type is specified for the function, as suggested in #5078.
> PHP: Adding a new error hint, as suggested in #5078.

- ide/image/src/org/netbeans/modules/image/CustomZoomAction.java
- ide/image/src/org/netbeans/modules/image/ImageDataLoader.java
- ide/image/src/org/netbeans/modules/image/ImageDataLoaderBeanInfo.java
- ide/image/src/org/netbeans/modules/image/ImageDataObject.java
- ide/image/src/org/netbeans/modules/image/ImageOpenSupport.java
- ide/image/src/org/netbeans/modules/image/ImagePrintSupport.java
- ide/image/src/org/netbeans/modules/image/ImageViewer.java
- ide/image/src/org/netbeans/modules/image/NBImageIcon.java
- ide/image/src/org/netbeans/modules/image/ZoomInAction.java
- ide/image/src/org/netbeans/modules/image/ZoomOutAction.java
- ide/image/src/org/netbeans/modules/image/action/ExternalEditAction.java
- ide/image/src/org/netbeans/modules/image/navigation/ImageNavigatorPanel.java
- ide/image/src/org/netbeans/modules/image/navigation/ImagePreviewPanel.java
The navigator window is not using antialiasing (left current version, right version from this PR):
When dragging images the cursor and the position on the image drifted apart, this is fixed. In the left part of the screenshot a drag start and end is shown for the original version, while the right side shows the new one (see the locations of the red cross and the red hand):
As part of the warning fixes, the generation of the action list had to be updated and while doing this the order was modified, so that it is more clear (separator before the image actions block and between the image and filesystem actions):
> Improve image display tool (antialias, improved dragging, optimize menu and fix warnings)

- java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
- java/maven.indexer/src/org/netbeans/modules/maven/indexer/api/RepositoryPreferences.java
- java/maven/src/org/netbeans/modules/maven/ProjectOpenedHookImpl.java
- java/maven/src/org/netbeans/modules/maven/options/Bundle.properties
- java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.form
- java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.java
allows to keep local indexing enabled while optionally disabling remote index downloads.
updated the settings UI a bit, added a description.
There is a small bug which is probably not worth the trouble of fixing: if the download started, is canceled, and the setting is then disabled again, NB will still think the download did not finish (which is technically true) and show the partial-index or indexing-in-progress notification in auto completion and search forms, restart fixes this.
> add maven indexer remote index download settings.

- java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementJavadoc.java
Show system property name rather than empty text for system property tags in the Javadoc popup. Also attempt to show the String value of unknown tags rather than missing the text out entirely.
Fixes #5403
> Show missing system properties in Javadoc popup (GH5403)

- java/java.graph/src/org/netbeans/modules/java/graph/SearchVisitor.java
- java/java.module.graph/src/org/netbeans/modules/java/module/graph/DependencyCalculator.java
Fixes #4227 - Java module graph component failing to display with a NPE. This is caused by the same issue as fixed in #4780 whereby the module tree is no longer available from `cc.getCompilationUnit().getTypeDecls()` and should be obtained by `cc.getCompilationUnit().getModule()`. Need to look across the code base for other instances of this problem.
Second commit fixes a stack overflow noticed in the search function on the graph. This seems to be due to circular dependencies being reported in the underlying dependency graph - probably some other issues to look at there, but at least it doesn't blow up for now!
> Fixes for Java module graph (GH4227)

- php/php.editor/src/org/netbeans/modules/php/editor/csl/SemanticAnalysis.java
- php/php.editor/test/unit/data/testfiles/semantic/gh5551_01.php
- php/php.editor/test/unit/data/testfiles/semantic/gh5551_01.php.semantic
- php/php.editor/test/unit/data/testfiles/semantic/gh5551_02.php
- php/php.editor/test/unit/data/testfiles/semantic/gh5551_02.php.semantic
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/SemanticAnalyzerTest.java
When there is an anonymous class in a method body, the anonymous class also removes method blocks of the enclosing class that need to be scanned. So, to prevent that, use `Map<TypeInfo, List<Block>>` instead of `List<Block>`
> Fix incorrect unused coloring #5551

- php/php.editor/src/org/netbeans/modules/php/editor/completion/DocRenderer.java
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5426.php
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5426.php.testIssueGH5426_01.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5426.php.testIssueGH5426_02.html
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCCDocumentationTest.java
#5426
This problem occurs when fields and functions have intersection types only in PHPDoc.
e.g.
```php
class Example
{
/**
* @var Type1&Type2
*/
public $field; // without type declaration
}
```
Before: `|` is shown instead of `&` (`Type1 | Type2`)
After: `&` is shown (`Type1 & Type2`)
> Show intersection types in the PHP doc window #5426

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/adm/VulnerabilityWorker.java
- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
An exception was thrown when the NB was trying to load `micronaut-core:aop` project during OCI ADM audit. The project was broken and its dependency root reported `null` artifact. ADM Vulnerability implementation then throws NPE as this is not handled well.
The PR fixes the root cause in Gradle tooling by eagerly copying the task list before iterating through it, as the task definition Map is not copied by Gradle library and may mutate during the iteration.
The a simple null check is done in vulnerability audit launcher.
> Avoid ConcurrentMod exception, tolerate broken project dependencies

- php/php.editor/src/org/netbeans/modules/php/editor/indent/FormatVisitor.java
- php/php.editor/test/unit/data/testfiles/formatting/php80/matchExpressionWithArray_01.php
- php/php.editor/test/unit/data/testfiles/formatting/php80/matchExpressionWithArray_01.php.formatted
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/indent/PHPFormatterTest.java
- https://github.com/apache/netbeans/issues/5186
e.g.
```php
match(true){
'test' => [
'key' => 'value',
],
};
```
Before: An array is broken
```php
match (true) {
'test' => [
'key' => 'value',
],
};
```
After:
```php
match (true) {
'test' => [
'key' => 'value',
],
};
```
> Fix an array formatting in a match arm #5186

- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/commands/ProjectAuditCommand.java
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/commands/ProjectMetadataCommand.java
- java/java.lsp.server/vscode/src/extension.ts
Two features in this PR:
- some command IDs have 'gcn' in their name, and the extension that provoked creation of the commands is being renamed ... and the commands should have neutral IDs anyway. Old ids were kept and marked as deprecated, neutral new names introduced.
- there was a special case when checking for conflicts - if a specific extension was installed, the LS does not ask the user, but disables itself. I made that decision configurable by package.jsons of the enabled extensions; if an extension decides that NBLS should disable itself in favour of RH java, it will do that without asking.
> Better LSP command names, conflict resolution

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/database/DatabaseNode.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/resources/layer.xml
Oracle cloud Database node is registered under `Cloud/Oracle/Database/Nodes`, but the corresponding actions are registered under `Cloud/Oracle/Databases/Actions` (note the difference Database - Database**s**). This mismatch causes that the database actions (DownloadWalletAction and OpenServiceConsoleAction) are not displayed in the context menu of Database node. This PR fixes this difference.
> Fix registration of Database node

- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
Some time in future when aliens find an old NetBeans installation somewhere, at least they will be able to read the newest javadoc.
> Calculate JDK javadoc links dynamically.

- php/php.editor/src/org/netbeans/modules/php/editor/CodeUtils.java
- php/php.editor/src/org/netbeans/modules/php/editor/model/ModelUtils.java
- php/php.editor/src/org/netbeans/modules/php/editor/model/impl/VariousUtils.java
- php/php.editor/src/org/netbeans/modules/php/editor/verification/IntroduceSuggestion.java
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumCase.php
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumCase.php.testEnumCaseFix_01a.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumCase.php.testEnumCaseFix_01b.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumCase.php.testEnumCaseFix_02a.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumCase.php.testEnumCaseFix_02b.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumCase.php.testEnumCaseFix_03a.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumCase.php.testEnumCaseFix_03b.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumCase.php.testEnumCase_01.hints
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumCase.php.testEnumCase_02.hints
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumCase.php.testEnumCase_03.hints
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethodsFix_01.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethodsFix_02.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethodsFix_03.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethodsFix_04.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethodsFix_05.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethodsFix_06.fixed
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethods_01.hints
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethods_02.hints
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethods_03.hints
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethods_04.hints
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethods_05.hints
- php/php.editor/test/unit/data/testfiles/verification/IntroduceSuggestion/testEnumMethods.php.testEnumMethods_06.hints
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/verification/IntroduceSuggestionTest.java
- Add a hint to introduce enum cases
- Fix the hint to introduce enum methods
- Fix the deprecated method (`GsfUtilities.getDocument`)
> PHP: Fix the IntroduceSuggestion hint for Enum

- php/php.editor/src/org/netbeans/modules/php/editor/model/impl/ModelVisitor.java
- php/php.editor/test/unit/data/testfiles/gotodeclaration/php81/testEnumerationsWithInterface/testEnumerationsWithInterface.php
- php/php.editor/test/unit/data/testfiles/markoccurences/php81/testEnumerationsWithInterface/testEnumerationsWithInterface.php
- php/php.editor/test/unit/data/testfiles/testEnumerationsWithInterface.php.testEnumerationsWithInterface_01a.occurrences
- php/php.editor/test/unit/data/testfiles/testEnumerationsWithInterface.php.testEnumerationsWithInterface_01b.occurrences
- php/php.editor/test/unit/data/testfiles/testEnumerationsWithInterface.php.testEnumerationsWithInterface_01c.occurrences
- php/php.editor/test/unit/data/testfiles/testEnumerationsWithInterface.php.testEnumerationsWithInterface_01d.occurrences
- php/php.editor/test/unit/data/testfiles/testEnumerationsWithInterface.php.testEnumerationsWithInterface_02a.occurrences
- php/php.editor/test/unit/data/testfiles/testEnumerationsWithInterface.php.testEnumerationsWithInterface_02b.occurrences
- php/php.editor/test/unit/data/testfiles/testEnumerationsWithInterface.php.testEnumerationsWithInterface_02c.occurrences
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/GotoDeclarationPHP81Test.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/OccurrencesFinderImplPHP81Test.java
```php
<?php
namespace Enum1;
interface ExampleInterface1 {}
interface ExampleInterface2 {}
namespace Enum2;
use Enum1\ExampleInterface1;
use Enum1\ExampleInterface2;
enum EnumImpl1 implements ExampleInterface1 {
case A = 'A';
case B = 'B';
}
enum EnumImpl2 implements ExampleInterface1, ExampleInterface2 {
case A = 'A';
case B = 'B';
}
````
> Fix GotoDeclaration in Enum implementing interface

- ide/csl.api/nbproject/project.properties
- ide/csl.api/test/unit/src/org/netbeans/modules/csl/api/test/CslTestBase.java
- php/php.editor/nbproject/project.properties
- php/php.editor/nbproject/project.xml
- php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion.java
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH4494.php
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH4494.php.testIssueGH4494_01.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH4494.php.testIssueGH4494_02.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH4494.php.testIssueGH4494_03.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH4494.php.testIssueGH4494_04.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH4494.php.testIssueGH4494_05.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH4494.php.testIssueGH4494_06.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH4494.php.testIssueGH4494_07.html
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCCDocumentationTest.java
- https://github.com/apache/netbeans/issues/4494
- Add a new test method for checking documentation when a `QueryType` is `DOCUMENTATION` to `CslTestBase`
- If `QueryType` is `DOCUMENTATION`, get a whole identifier as a prefix
```php
<?php
/**
* function gh4494.
*
* @return void
*/
function gh4494(): void {
}
/**
* function gh4494_aa().
*
* @return void
*/
function gh4494_aa(): void {
}
/**
* function gh4494_aa_bb().
*
* @return void
*/
function gh4494_aa_bbb(): void {
}
/**
* function gh4494_aa_bb_cc().
*
* @return void
*/
function gh4494_aa_bb_cc(): void {
}
gh4494_aa_bb_cc();
```
> Fix being shown incorrect documentation #4494

- php/php.editor/src/org/netbeans/modules/php/editor/csl/SemanticAnalysis.java
- php/php.editor/test/unit/data/testfiles/semantic/enumerationsWithPrivateConst.php
- php/php.editor/test/unit/data/testfiles/semantic/enumerationsWithPrivateConst.php.semantic
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/csl/SemanticAnalyzerTest.java
> Fix the highlighting for private constants of Enum

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
- extide/gradle/src/org/netbeans/modules/gradle/api/BuildPropertiesSupport.java
- extide/gradle/src/org/netbeans/modules/gradle/loaders/ExtensionPropertiesExtractor.java
- extide/gradle/test/unit/data/buildprops/micronaut/build.gradle
- extide/gradle/test/unit/src/org/netbeans/modules/gradle/loaders/ExtensionPropertiesExtractorTest.java
This PR initially started from [reviewing this change](https://github.com/apache/netbeans/pull/5400/files/0054e511f349a3d4a075d0688ec7d040021a7b7e#diff-c214cb774bb9be2ee5aaaf45a8bbc5796aa98cdf86a045378bc9fd540c7ccc8fR173) as the intention was to un-escape '\;' sequence to ';'. Then as I attempted to write tests, I've found a few rough edges of the BuildProperties API ...
Some highlights here, minor commnents inline in the diff.
1/ Gradle defines an extensibility 'ext' container for most domain object, where extra properties can be defined. After definition, they become 'part of' the domain object itself and can be referenced as such. Those extra properties were not exported in the project info. Now they're exported into the domain object's namespace.
2/ Structures (structured things that …
> Fixed key escaping; fixed list/map property extraction.

- ide/code.analysis/nbproject/project.xml
- ide/code.analysis/src/org/netbeans/modules/analysis/Utils.java
- java/java.lsp.server/nbcode/nbproject/platform.properties
- java/java.source/nbproject/project.xml
- java/java.source/src/org/netbeans/modules/java/source/JBrowseModule.java
- java/junit/nbproject/project.xml
- java/maven/nbproject/project.xml
- java/maven/src/org/netbeans/modules/maven/problems/MissingModulesProblemProvider.java
- platform/autoupdate.services/apichanges.xml
- platform/autoupdate.services/manifest.mf
- platform/autoupdate.services/nbproject/project.xml
- platform/autoupdate.services/src/org/netbeans/api/autoupdate/PluginInstaller.java
- platform/autoupdate.services/src/org/netbeans/spi/autoupdate/PluginInstallerImplementation.java
- platform/autoupdate.ui/src/org/netbeans/modules/autoupdate/ui/GuiPluginInstallerImpl.java
- platform/autoupdate.ui/src/org/netbeans/modules/autoupdate/ui/ModuleInstallerSupport.java
- platform/autoupdate.ui/src/org/netbeans/modules/autoupdate/ui/api/PluginManager.java
- platform/o.n.bootstrap/manifest.mf
- platform/o.n.bootstrap/src/org/netbeans/ModuleManager.java
This PR creates a mini-API for installing plugins. Currently modules depend on Autoupdate UI when they need to initiate installation of a plugin - but that's not necessary.  This PR creates a SPI, which is implemented by AU UI. In absence of UI, the installation fail - most of the modules do not check the outcome of the installation anyway.
With the dependency removed, AU UI can be removed from LSP distribution, which replaces the implementation done in #5620.
> Remove dependencies on Autoupdate UI

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeViewProvider.java
- java/java.lsp.server/vscode/package.json
This PR tries to fix the issue, which manifest itself as VSCode error "Element with id xxx is already registered" when expanding nodes in Database view in VSCode. 
It turns out that the error was caused by asynchronous computation of children used netbeans database module and usage of `node.getChildren().getNodes(true)` in LSP server. This implementation causes that VSCode does not see `wait node` which is normally displayed in NetBeans, because `getNodes(true)` waits for all nodes and efectively invalides the asynchronous computation of children for the VSCode. However property change events and other changes for newly created nodes are fired from netbeans code and translated via LSP to VSCode - I believe that this causes mismatch between VSCode and LSP server. 
The fix changes …
> Use wait node in VSCode for long running computation of children

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/TreeViewProvider.java
- java/java.lsp.server/vscode/package.json
> Revert "Use wait node in VSCode for long running computation of children"

- webcommon/web.clientproject/src/org/netbeans/modules/web/clientproject/sites/OnlineSites.java
- Bump HTML5 Boilerplate to 8.0.0
- Bump Twitter Bootstrap to 5.2.3
Testing:
- Verify successful execution of `ant check-sigtests`
- Create and run HTML5/JS applications
- Checked that the correct version of the template is downloaded
HTML5 Boilerplate
Bootstrap 5.2.3
> Update Online HTML5 templates:

- php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion.java
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5347.php
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCCDocumentationTest.java
- https://github.com/apache/netbeans/issues/5347
- Don't show documentation if the prefix(whole identifier) is empty
> Don't show documentation for an empty line #5347

- java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
- java/maven.indexer/src/org/netbeans/modules/maven/indexer/api/RepositoryPreferences.java
- java/maven/src/org/netbeans/modules/maven/ProjectOpenedHookImpl.java
- java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.java
When the maven general indexing is disabled, the setting for the index download is lost and forced to be false. Instead of loosing the value a new preferences getter is introduced, that calculates the effective value based on the two components:
- general indexing
- download index
Only if both settings are true, the effective value will be true.
> Maven indexing: Retain download index setting even if index setting is disabled

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/database/DatabaseNode.java
"Service Console" has been deprecated. See [this](https://adwc.uscom-east-1.oraclecloud.com/console/index.html?tenant_name=iam-ocid1.tenancy.oc1..fhfhfhfhfs33432232&database_name=adwdb1) link.
```
Service Console has been deprecated as of July 5th, 2022.
You can use Database Actions to access the same set of features available 
in Service Console. For more details on where to find each Service Console 
functionality in Database Actions, see the documentation.
```
This PR uses new replacement URL, which should provide similar functionality.
> Service Console has been deprecated - use new replacement URL

- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/CompilerPluginVersionError.java
- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/PomModelUtils.java
- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/UseReleaseOptionHint.java
- java/maven.hints/test/unit/src/org/netbeans/modules/maven/hints/pom/UseReleaseOptionHintTest.java
- java/maven/nbproject/project.xml
- java/maven/src/org/netbeans/modules/maven/api/ModuleInfoUtils.java
The plugin version query returns the version of the embedded maven distribution instead of the active distribution. This started causing issues the moment #5679 was implemented which upgrades embedded maven to a version which provides a JDK 9+ compatible plugins out of the box (which is a good thing).
We can workaround this problem by comparing maven versions, since we can infer the plugin version from it under certain conditions.
Fixes the release option and the module-info hint.
> [maven hints] try to infer compiler plugin version from active maven version.

- java/maven/src/org/netbeans/modules/maven/api/ModelUtils.java
- java/maven/src/org/netbeans/modules/maven/customizer/SourcesPanel.java
The project properties window will now update the release option if it can be found and use source/target as fallback. 
It will also make sure that both are not used at the same time. The option window itself will not convert anything to the release option, that is what the hints are for.
> make maven project properties window aware of the javac release option

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/Debugger.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/NbProtocolServer.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbLspServer.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
When the user code is run/debug, DAP protocol is used for the launch request. Although the DAP server provided `OperationContext` for reporting progress, it did not provide any other LSP client's functions to the DAP-initiated processes within NBLS. 
So when one runs (using codelen or command) a project or main class in a Maven project, with bad proxy settings, the Maven support wants to ask the user - and fails, since the DAP-initiated maven build has no access to `DialogDisplayer` that works through LSP connection with the LSP client to display confirmations.
This PR attempts to change DAP + LSP implementation so that the default Lookup for their request processing conains **both** DAP and LSP lookups (and of course request-specific items and the default Lookup as the last one).
> DAP and LSP use a common Lookup.

- extide/gradle/src/org/netbeans/modules/gradle/api/execute/GradleDistributionManager.java
- extide/libs.gradle/external/binaries-list
- extide/libs.gradle/external/gradle-tooling-api-8.1-rc-2-license.txt
- extide/libs.gradle/external/gradle-tooling-api-8.1-rc-2-notice.txt
- extide/libs.gradle/nbproject/project.properties
- extide/libs.gradle/nbproject/project.xml
Well, the usual Gradle Tooling Update. If 8.1 GA would see the sun during the beta phase, I'm going to create another one.
> Upgraded Gradle Tooling to 8.1-rc-2 with JDK 20 Support

- webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/JsStructureScanner.java
- webcommon/javascript2.editor/test/unit/data/testfiles/parser/asyncFunctions/asyncFunctions3.js.ast.xml
- webcommon/javascript2.editor/test/unit/data/testfiles/structure/issueGH4371.js
- webcommon/javascript2.editor/test/unit/data/testfiles/structure/issueGH4371.js.structure
- webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/JsStructureScannerTest.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java
- webcommon/libs.nashorn/external/binaries-list
- webcommon/libs.nashorn/external/graaljs-parser-1.2-license.txt
- webcommon/libs.nashorn/nbproject/project.properties
- webcommon/libs.nashorn/nbproject/project.xml
With this PR the modifiers are now reported correctly for the following testcase, which is based on the original report in  #4371:
```javascript
class test {
fieldTest1 = 0;
#fieldTest2 = 1;
static fieldTest3 = 2;
static #fieldTest4 = 3;
// private
#test1() {};
async #test2() {}
// public
test3() {}
async test4() {}
// static private
static #test5() {}
static async #test6() {}
// static public
static test7() {}
static async test8() {}
}
```
Resulting structure:
Closes: #4371
Closes: #5030
> JS: Improve handling of private/static fields in JS classes

- ide/options.editor/src/org/netbeans/modules/options/indentation/FormattingPanel.java
Fixes NPE Cannot invoke "java.awt.Container.validate()" because the return value of "org.netbeans.modules.options.indentation.FormattingPanel.getParent()" is null at org.netbeans.modules.options.indentation.FormattingPanel.propertyChange(FormattingPanel.java:207)
Caused by change in #5625.
To reproduce open PHP or Java project. Open Project Properties and then select Formatting category.
> Fixed Formatting under Project Properties

- php/php.editor/src/org/netbeans/modules/php/editor/indent/FmtOptions.java
- Currently, when the values of the formatting options are changed, the preview panel is scrolled to the end of the editor
- To avoid it, keep the caret position before reformatting
Before:
After:
> Avoid being scrolled to the end of the editor in the preview panel for formatting options

- ide/html.lexer/src/org/netbeans/lib/html/lexer/HtmlLexer.java
- ide/html.lexer/test/unit/src/org/netbeans/lib/html/lexer/HtmlLexerTest.java
Faced with a structure like this:
"<Jm/  a=q</>>V  />G>"
The html lexer hit an assertion as it tried to lex "a=q" as an attribute value. The sequence "<Jm/" at first looks like the start of a tag, but that is discarded once the "/" is read. Yet the lexer state is not reset to INIT, but ISP_TAG_X.
Attribute lexing assumes, that a tag was lexed first and that that information is still present, which not the case here.
> Stabelize html lexer in broken cases

- java/maven/src/org/netbeans/modules/maven/execute/MavenCommandLineExecutor.java
- java/maven/src/org/netbeans/modules/maven/execute/cmd/ShellConstructor.java
- java/maven/src/org/netbeans/modules/maven/options/MavenSettings.java
- java/maven/test/unit/src/org/netbeans/modules/maven/execute/MavenCommandParametersAnalyzerTest.java
- java/maven/test/unit/src/org/netbeans/modules/maven/execute/MavenDaemonCommandParametersAnalyzerTest.java
As `mvnd` is multi threaded by default we need to disable the event spy which is normally disabled when using multiple threads. This fixes #5479 .
The PR also contains a performance fix which saves some time on every maven command execution
> Improve maven multithreaded execution detection.

- platform/openide.explorer/src/org/openide/explorer/propertysheet/RendererFactory.java
- platform/openide.explorer/test/unit/src/org/openide/explorer/propertysheet/StringRendererTest.java
Text displayed in the property sheet is escaped if the target font does not have a glyph for some of the characters. The existing implementation escapes some Unicode characters even if the target font can display them. This is due to the reliance on `Font.canDisplay(char)` which does not handle all Unicode characters.
The solution here is to update `RendererFactory.makeDisplayable` to iterate over the code points in the string rather than the characters. It then uses `Font.canDisplay(int)` to validate the glyph availability using the code point.
Unit tests are included to verify the existing behavior is maintained. All passed for the original code except `testDoesNotEscapeDisplayableCodePoint`.
|Original|Updated|
|----|----|
|<img width="515" alt="Original (View)" …
> #4818: Update string renderer to only escape undisplayable code points.

- php/php.editor/src/org/netbeans/modules/php/editor/actions/UsedNamesCollector.java
- php/php.editor/test/unit/data/testfiles/actions/testGH4614/testGH4614_01.php
- php/php.editor/test/unit/data/testfiles/actions/testGH4614/testGH4614_01.php.importData
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/actions/ImportDataCreatorTest.java
Ignore the following cases
- `array<int, TypeName>`
- `array{'key': TypeName}`
```php
<?php
namespace Test1;
class Foo {
}
namespace Test2;
class Test
{
/**
* @param array<'foo', Foo> $param
*/
public function test1(array $param): Foo {
return $param['foo'];
}
/**
* @param array{'foo': Foo, "bar": string} $param
*/
public function test2(array $param): Foo {
return $param['foo'];
}
}
```
> Avoid showing invalid types in the Fix Imports panel

- php/php.editor/src/org/netbeans/modules/php/editor/model/impl/OccurenceBuilder.java
- php/php.refactoring/test/unit/data/testfiles/findusages/testGH4382/index.php
- php/php.refactoring/test/unit/data/testfiles/findusages/testGH4382/index.php.testGH4382_01.findUsages
- php/php.refactoring/test/unit/data/testfiles/findusages/testGH4382/index.php.testGH4382_02.findUsages
- php/php.refactoring/test/unit/data/testfiles/findusages/testGH4382/index.php.testGH4382_03.findUsages
- php/php.refactoring/test/unit/src/org/netbeans/modules/refactoring/php/findusages/WhereUsedSupportTest.java
- https://github.com/apache/netbeans/issues/4382
- Also find the new instance creation for the alias
> Fix Find Usages for __construct method #4382

- php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCompletionItem.java
- php/php.editor/test/unit/data/testfiles/completion/lib/gh3806/gh3806.php
- php/php.editor/test/unit/data/testfiles/completion/lib/gh3806/gh3806.php.testGH3806_01.cccustomtpl
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionGH3806Test.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionTestBase.java
- https://github.com/apache/netbeans/issues/3806
- Handle it as well as the `new class` context
- Fix deprecated method `GsfUtilities.getDocument` to `GsfUtilities.getADocument`
Example:
```php
throw new \Excep^
```
Before:
```php
throw new Exception()
```
After:
```php
throw new \Exception()
```
> Fix code completion in `throw new` context #3806

- java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleDependencyResult.java
Project dependencies query will fail on a project with no `build.gradle`, with just `settings.gradle`; this setup is common for umbrella projects that only includes subprojects and have no dependencies themselves.
There's an unhandled state when the buildscript is not present so the toFileObject fails with a NPE.
> Report empty set if project does not use buildscript; prevent NPE.

- extide/gradle/src/org/netbeans/modules/gradle/api/GradleBaseProjectBuilder.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleDependenciesImplementation.java
Consider dependency declaration as follows:
```
dependencies {
implementation 'org.springframework.boot:spring-boot-starter-web'
developmentOnly 'org.springframework.boot:spring-boot-devtools'
testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```
there's no version specified for `spring-boot-devtools.
The [https://github.com/apache/netbeans/blob/master/extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java#L1502](code that reports `developmentOnly_directChildren`) handles such situations using GAV without version (as specified in the buildfile) - `org.springframework.boot:spring-boot-devtools:`. 
The issue is that when **resolved** artifacts GAVs are matched against these direct children, the module …
> Better handling for dependencies w/o versions

- php/php.editor/src/org/netbeans/modules/php/editor/completion/DocRenderer.java
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5355.php
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5355.php.testIssueGH5355_01.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5355.php.testIssueGH5355_02.html
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCCDocumentationTest.java
```php
function testFunction($a) {
if ($a) {
return 1;
}
return 'str';
}
testFunction(null);
```
before:
after:
> [GH-5355] PHP: Corrects the display of the guessed return type for a function or method in the documentation

- java/java.source.base/src/org/netbeans/api/java/source/SourceUtils.java
- java/java.source.base/test/unit/src/org/netbeans/api/java/source/SourceUtilsTest.java
Fixes #5738, a regression introduced by #5152 in NB 17.
> `SourceUtils.findMatchingChild` should never return a folder

- php/php.editor/src/org/netbeans/modules/php/editor/actions/UsedNamesCollector.java
- php/php.editor/test/unit/data/testfiles/actions/testGH5330/01/testGH5330_01.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5330/01/testGH5330_01.php.fixUses
- php/php.editor/test/unit/data/testfiles/actions/testGH5330/testGH5330_01.php
- php/php.editor/test/unit/data/testfiles/actions/testGH5330/testGH5330_01.php.importData
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/actions/FixUsesPerformerTest.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/actions/ImportDataCreatorTest.java
- https://github.com/apache/netbeans/issues/5330
Example:
```php
namespace Test\SameName;
class SameNamePart{};
class OtherSameNamePart{};
namespace Test;
use Test\SameName\OtherSameNamePart;
class Example {
public function __construct(
private OtherSameNamePart $otherSameName,
private SameNamePart $sameName,
) {}
}
```
Before: `use Test\SameName\SameNamePart;` is **not** inserted
After: `use Test\SameName\SameNamePart;` is inserted
> Fix the problem that "Fix Imports" don't work when there are types that have the same suffix #5330

- webcommon/javascript2.editor/test/unit/data/testfiles/structure/objectNameMatchingNestedFunction.js
- webcommon/javascript2.editor/test/unit/data/testfiles/structure/objectNameMatchingNestedFunction.js.structure
- webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/JsStructureScannerTest.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/JsObjectImpl.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java
- webcommon/javascript2.model/test/unit/data/testfiles/model/objectNameMatchingNestedFunction.js
- webcommon/javascript2.model/test/unit/data/testfiles/model/objectNameMatchingNestedFunction.js.model
- webcommon/javascript2.model/test/unit/src/org/netbeans/modules/javascript2/model/ModelTest.java
- webcommon/libs.nashorn/src/com/oracle/js/parser/Parser.java
- webcommon/libs.nashorn/test/unit/src/com/oracle/js/parser/ParserTest.java
As analyzed by @akronenw certain JS files can lead the JS model generator of NetBeans
to create a cyclic structure. The structure looks like this:
```javascript
var Base = new function() {
// a lot of code
function Base() {
// some code
}
// more code
}
```
This is turn is at least partially responsible for seemingly endless scanning.
The implemented fix added an assert that detects cycles in the generated model and fixes the
one detected when the `paper-full.js` file is parsed.
In addition a wrong assertion in the GraalJS fork is disabled, that triggered on angular projects
and prevented usage of NetBeans with activated assertions there.
This is not a full fix, but should improve the situation and make it easier to find other
problems in that area by just using NetBeans with assertions …
> JS: Improve stability of JS model building (prevent cycles)

- ide/languages.yaml/src/org/netbeans/modules/languages/yaml/YamlKeystrokeHandler.java
- ide/languages.yaml/test/unit/src/org/netbeans/modules/languages/yaml/YamlKeystrokeHandlerTest.java
This one is a trivial change, I hope it's not disruptive.
It happens quite often that I need to edit YAML files outside of the IDE, and I accustomed the habit of typing `{}` and `[]` in pairs. This one makes the editor stepping though the right `]` and `}`-s.
> YAML: Step right curly and brackets when they are right to the caret

- ide/xml.jaxb.api/nbproject/project.xml
project metadata of JAXB API module fixed - wrapped libs are now visible under 'Libraries' node
> JAXB API module fixed

- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCCDocumentationTest.java
- Sometimes, we get the following log: Working directory: D:\a\netbeans\netbeans\php\php.editor\build\test\unit\work\o.n.m.p.e.c.P\testIssueGH5347_02
- It is the working directory for a failed test
https://github.com/apache/netbeans/blob/7f8dfdeb60ce3bec5554fc19ddb40fac0388d885/harness/nbjunit/src/org/netbeans/junit/NbTestCase.java#L524-L547
https://github.com/apache/netbeans/blob/7f8dfdeb60ce3bec5554fc19ddb40fac0388d885/harness/nbjunit/src/org/netbeans/junit/NbTestCase.java#L472-L487
> Disable PHPCCDocumentationTest.testIssueGH5347_02() in Windows

- platform/options.api/src/org/netbeans/modules/options/OptionsPanel.java
the custom buttons should set the correct foreground color when the highlighted color is set to retain contrast.
before:
after:
analog to:
(no changes visible when the accent color isn't set)
> option window: category buttons foreground color fix.

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatDarkLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/openide.util.ui/src/org/openide/util/ImageUtilities.java
Improve the appearance of disabled icons on dark LAFs, by adjusting ImageUtilities.DisabledButtonFilter.
Also adjust the disabled TabControlIcon color on both FlatLAF Light and FlatLAF Dark, to make these buttons more obviously disabled.
Before/after screenshots on FlatLAF Dark:
Before/after screenshots on FlatLAF Light (just a tiny change to the <> icons):
> Improve the appearance of disabled icons on FlatLAF Dark (and a tiny improvement on FlatLAF Light)

- nb/ide.launcher/netbeans.conf
This PR adds launch option `-Dapple.awt.application.appearance=system` to enabled dark window title bars if macOS is in dark mode.
With this PR:
Without:
Note that the window title bars get only dark if macOS dark appearance is enabled (in macOS System Preferences > General > Appearance). If macOS is in light mode, the window title bars get light color.
> macOS: dark window title bars

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/Bundle.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafOptionsPanel.form
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafOptionsPanel.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafPrefs.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/Installer.java
Since changing accent color in FlatLaf custom properties does not work as expected for Cupertino themes (see issue #5461),
I've added a combobox to the options dialog to allow setting accent color in UI. FlatLaf API is used to enable accent color so that it works correctly in Cupertino themes.
There are some predefined accent colors, which work good for light and dark themes. These are the same colors that macOS (and FlatLaf Demo app) uses. There is also a "Custom" item in the combobox that allows to set any color.
The colors are defined in `FlatLaf.properties` (key `nb.accentColors.predefined`).
> FlatLaf: change accent color in Options dialog (Appearance > FlatLaf)

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/icons/NBFlatAdapterIcon.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/icons/NBFlatTreeClosedIcon.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/icons/NBFlatTreeOpenIcon.java
Currently there is a mix between NetBeans style icons and FlatLaf outlined folder icons in many views (e.g. in Projects or Files views), which does not look good. This PR replaces the FlatLaf folder icons with NetBeans style icons in NB Explorer component.
@eirikbakke @neilcsmith-net
ATM this PR uses icons from module `o.n.swing.plaf` in module `o.n.swing.laf.flatlaf`.
It works, but I'm not sure whether this is allowed?
Or is it better to copy the icons?
> FlatLaf: use NetBeans folder icons in NB Explorer

- java/maven.grammar/src/org/netbeans/modules/maven/grammar/MavenProjectGrammar.java
- java/maven.grammar/src/org/netbeans/modules/maven/grammar/POM-abbreviations.xml
It is somewhat common to use properties for artifact versions, esp when several artifacts share the same version.
This implements basic auto completion for properties which are used as version field.
In contrast to hints, completion is implemented in the grammar and doesn't have the full context. This will only take properties into account which are in the same pom file as their usage.
> basic auto completion for maven version properties.

- webcommon/javascript2.editor/test/unit/data/testfiles/markoccurences/issueGH5184_01.js
- webcommon/javascript2.editor/test/unit/data/testfiles/markoccurences/issueGH5184_01.js.testIssueGH5184_01.occurrences
- webcommon/javascript2.editor/test/unit/data/testfiles/structure/objectNameMatchingNestedFunction.js
- webcommon/javascript2.editor/test/unit/data/testfiles/structure/objectNameMatchingNestedFunction.js.structure
- webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/JsStructureScannerTest.java
- webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/navigation/GoToDeclarationTest.java
- webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/navigation/MarkOccurrenceTest.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/JsObjectImpl.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java
- webcommon/javascript2.model/test/unit/data/testfiles/model/objectNameMatchingNestedFunction.js
- webcommon/javascript2.model/test/unit/data/testfiles/model/objectNameMatchingNestedFunction.js.model
- webcommon/javascript2.model/test/unit/data/testfiles/structure/issueGH5184_02.js
- webcommon/javascript2.model/test/unit/data/testfiles/structure/issueGH5184_02.js.model
- webcommon/javascript2.model/test/unit/src/org/netbeans/modules/javascript2/model/ModelTest.java
- webcommon/libs.nashorn/src/com/oracle/js/parser/Parser.java
- webcommon/libs.nashorn/test/unit/src/com/oracle/js/parser/DumpingVisitor.java
- webcommon/libs.nashorn/test/unit/src/com/oracle/js/parser/ParserTest.java
At least two issues are fixed by this:
- "export class XY" construct is not parsed correctly resulting in
a JS model for that class, that his missing methods
- "class XY {}; export {XY}" is not correctly parsed resulting missing
declaration handling for that member
Example that was not correctly parsed:
```javascript
export class test {
method(param){
param;
}
};
// this shows in navigator / highlighting works
class test2{
method(param){
param;
}
}
// no highlighting, Go to declaration does not work
export {test2};
```
Closes: https://github.com/apache/netbeans/issues/5184
> JS: Improve handling of export declarations (references and classes)

- ide/languages.go/manifest.mf
- ide/languages.go/src/org/netbeans/modules/languages/go/Bundle.properties
- ide/languages.toml/manifest.mf
- ide/languages.toml/src/org/netbeans/modules/languages/toml/Bundle.properties
- ide/languages.yaml/manifest.mf
- ide/languages.yaml/src/org/netbeans/modules/languages/yaml/Bundle.properties
- java/languages.antlr/manifest.mf
- java/languages.antlr/src/org/netbeans/modules/languages/antlr/Bundle.properties
While I was trying to disable the HCL support in the plugin manager for some testing, I realized that it is not possible as it was hidden.
I also changed their category to `Editing`, it felt a bit better. These might change later, if some language support goes beyond editing.
> Show antlr, go, tom, yaml  languages in auto-update, moved them to Editing

- java/maven/src/org/netbeans/modules/maven/api/execute/RunUtils.java
- java/maven/src/org/netbeans/modules/maven/customizer/CompilePanel.java
- java/maven/test/unit/src/org/netbeans/modules/maven/api/execute/Bundle_test.properties
- java/maven/test/unit/src/org/netbeans/modules/maven/api/execute/RunUtilsTest.java
"good defaults" round two, see [dev list](https://lists.apache.org/thread/rdflfdbt2v0cxz9mk198tonm0hnff1bg) or #5260
sets CoS default to `none`
some reasons why:
- CoS is an intrusive feature which sidelines the build and compiles directly into the target folder (using javac from the NB runtime)
- UX wise this asks for being an opt-in feature, enabling it via the checkbox will even display an info dialog stating the risks, a dialog users would never see when it is enabled by default
- mvnd and other incremental improvements make CoS less interesting
> disable compile-on-save by default in maven projects.

- harness/jellytools.platform/src/org/netbeans/jellytools/actions/Action.java
- ide/editor.bookmarks/src/org/netbeans/modules/editor/bookmarks/ui/GotoLineOrBookmarkPanel.java
- ide/editor.lib/src/org/netbeans/editor/MultiKeymap.java
- ide/editor.lib/src/org/netbeans/editor/Utilities.java
- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/actions/EditorActionUtilities.java
- java/java.editor/src/org/netbeans/modules/java/editor/overridden/ComputeAnnotations.java
- java/java.navigation/src/org/netbeans/modules/java/navigation/ToolTipManagerEx.java
- platform/o.n.core/src/org/netbeans/core/NbKeymap.java
- platform/openide.awt/apichanges.xml
- platform/openide.awt/src/org/openide/awt/Actions.java
- platform/openide.awt/src/org/openide/awt/Bundle.properties
- profiler/profiler.api/src/org/netbeans/modules/profiler/api/ActionsSupport.java
Keyboard accelerator strings, such as "Ctrl+R", are shown to the user in various places throughout NetBeans, e.g. in editor toolbar tooltips. On MacOS, the traditional display format for these is to use a special single-character symbol for modifier keys, and no "+" symbol. E.g. "⌘R" for Command+R. On NetBeans, though, we currently show this as "⌘+R".
This PR gets rid of the plus symbol on MacOS, to match the native convention. This is already how shortcuts are displayed in the main menu (where the accelerator display strings are generated by the OS).
> Don't show the '+' separator in keyboard accelerators on MacOS

- .github/workflows/main.yml
- java/debugger.jpda.projects/src/org/netbeans/modules/debugger/jpda/projects/IntroduceClass.java
- java/debugger.jpda/nbproject/project.properties
- java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/expr/EvaluatorVisitor.java
- java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/EvaluatorDirectTest.java
- java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/EvaluatorTest.java
- java/debugger.jpda/test/unit/src/org/netbeans/api/debugger/jpda/JPDASupport.java
When a watch contains a binding variable, it fails to show the value. This patch is trying to fix that - that's the  `case BINDING_VARIABLE:` change.
In addition to this, this patch is trying to:
- add a test for the change, that will only execute under JDK 17.
- run debugger.jpda tests on JDK 11 and JDK 17
- disabling tests that failed for me locally - I used a fairly coarse way to disable them, so that e.g. in `EvaluationTest`, only one subtest fails. This could, presumably, be improved in further patches. IMO better to run some tests, than none.
- the `info.getCompilationUnit()` -> `treePath.getCompilationUnit()` change is a bit tricky: if scanning is running, the TreePath may originate in a different javac instance than is the one held in `info`. Which then leads to end position `-1` …
> Adding support for evaluating watches containing binding variables.

- .github/workflows/main.yml
- java/debugger.jpda/nbproject/project.properties
the new job added in #5763 fails a bit too often, we might have to exclude another test (its run in a matrix so it hurts twice as much).
https://github.com/apache/netbeans/actions/runs/4710224487 3 restarts
https://github.com/apache/netbeans/actions/runs/4710854667 1 restart
edit: wrapped in retry script since it failed again
> debugger.jpda: exclude AsynchStepTest to stabilize job

- ide/git/src/org/netbeans/modules/git/Annotator.java
- ide/mercurial/src/org/netbeans/modules/mercurial/MercurialAnnotator.java
- ide/subversion/src/org/netbeans/modules/subversion/Annotator.java
- ide/versioning.core/src/org/netbeans/modules/versioning/core/ShowTextAnnotationsAction.java
- ide/versioning.core/src/org/netbeans/modules/versioning/core/api/VersioningSupport.java
- ide/versioning.ui/src/org/netbeans/modules/versioning/ui/options/GeneralOptionsPanel.java
- ide/versioning/src/org/netbeans/modules/versioning/spi/VersioningSupport.java
"good defaults" round two, see [dev list](https://lists.apache.org/thread/rdflfdbt2v0cxz9mk198tonm0hnff1bg)
enables versioning labels by default. (view -> show versioning labels, or via option window)
> enable versioning labels by default.

- ide/slf4j.api/external/binaries-list
- ide/slf4j.api/external/slf4j-api-1.7.36-license.txt
- ide/slf4j.api/nbproject/project.properties
- ide/slf4j.api/nbproject/project.xml
- ide/slf4j.jdk14/external/binaries-list
- ide/slf4j.jdk14/external/slf4j-jdk14-1.7.36-license.txt
- ide/slf4j.jdk14/nbproject/project.properties
- ide/slf4j.jdk14/nbproject/project.xml
- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
Upgrade of slf4j library (both `ide/slf4j.api` and `ide/slf4j.jdk14`) to 1.7.36.
> Slf4j library upgrade

- apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/MavenNbModuleImpl.java
- apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NBMNativeMWI.java
- apisupport/maven.apisupport/src/org/netbeans/modules/maven/apisupport/NbmWizardIterator.java
- apisupport/maven.apisupport/test/unit/src/org/netbeans/modules/maven/apisupport/NBMNativeMWITest.java
- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/CompilerPluginVersionError.java
- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/UseReleaseOptionHint.java
the new NBM project wizard could potentially block after finish is pressed, waiting for the indexer to provide complete results (#1999) for the archetype version query.
This is unnecessary since archetypes rarely change and the default is usually the correct version even if the index isn't ready yet, so we are ok with partial results.
Further, it didn't filter out snapshot releases, which could be potentially in the local repository too.
It could even downgrade the archetype version by accident under some circumstances when indexing got previously canceled since it assumed the version was always newer.
+ fixed some deprecations and NPEs in maven hints
+ bumped archetype and plugin version defaults to latest
might also fix some symptoms of #5727
> don't block in NBM wizard + skip snapshots + more.

- java/ant.hints/src/org/netbeans/modules/ant/hints/errors/EnablePreviewAntProj.java
- java/java.hints/src/org/netbeans/modules/java/hints/errors/EnablePreviewSingleSourceFile.java
- java/maven.hints/src/org/netbeans/modules/maven/hints/errors/EnablePreviewMavenProj.java
extracted from #5802
test with:
```java
Thread.ofVirtual();
```
on JDK 20, which should trigger the hint. Applying the fix should add the required flags to the compiler plugin
> add missing error code to enable-preview hint

- ide/editor.codetemplates/arch.xml
- java/maven/src/org/netbeans/modules/maven/options/MavenSettings.java
Few fixes to have the apidoc doing correct linking and generation for the release branch.
not some other pr on netbeans-jenkins-lib as we need a more advanced jdk for apidoc generation.
> release180 apidoc fixes

- .github/workflows/main.yml
- groovy/libs.groovy/nbproject/project.xml
- php/websvc.saas.codegen.php/nbproject/project.xml
- platform/api.search/nbproject/project.properties
- platform/janitor/nbproject/project.properties
- websvccommon/websvc.jaxwsmodelapi/nbproject/project.xml
preparations for the next LTS release of the JDK!
Java 20 is going to be released soon, this prepares the next round.
(not necessarily intended to be merged right away)
> bump CI matrix from 20-ea to 21-ea.

- nbbuild/antsrc/org/netbeans/nbbuild/extlibs/ignored-overlaps
`ignored-overlaps` references several files, which no longer exists in the netbeans codebase. The most common case is caused by library upgrade. This PR tries to clean-up `ignored-overlaps`, so that it contains only files actually used by netbeans.
> non-existent files removed from ignored-overlaps

- platform/core.ui/src/org/netbeans/core/ui/sysopen/SystemOpenAction.java
Rewrite the `Open in System` action with lookup listening so that it works dynamically with global context.
Now that SystemOpenAction is included in the main Tools menu ( #5770 ), the fact that the action doesn't enable and disable with the global context is very visible. When any item that is not a file is selected (service, pom navigator, etc.) the action remains enabled but non-operational. These changes ensure the action only appears when applicable.
> Make SystemOpenAction dynamic in main menu

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
On some projects, like [`micronaut-liquidbase`](https://github.com/liquibase/liquibase), the IDE reports an exception during project load and fails to load the project properly:
```
Reason: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "v" is null
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "v" is null
at org.netbeans.modules.gradle.tooling.NbProjectInfoBuilder.dumpContainerProperties(NbProjectInfoBuilder.java:737)
at org.netbeans.modules.gradle.tooling.NbProjectInfoBuilder.inspectExtensions(NbProjectInfoBuilder.java:894)
at org.netbeans.modules.gradle.tooling.NbProjectInfoBuilder.detectExtensions(NbProjectInfoBuilder.java:440)
at org.netbeans.modules.gradle.tooling.NbProjectInfoBuilder.lambda$runAndRegisterPerf$9(NbProjectInfoBuild …
```
> Avoid NPE on null value in list/map/property.

- .github/workflows/main.yml
- ide/languages.hcl/nbproject/project.xml
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/grammar/g4/HCLExpressionParser.g4
- ide/languages.hcl/test/unit/src/org/netbeans/modules/languages/hcl/grammar/HCLExpressionParserTest.java
It seems there is a bug in the HCL Grammar spec: https://github.com/hashicorp/hcl/issues/553
According to the spec an `operation` only can happen between `ExprTerm`-s not `Expression`-s making the following assignment invalid:
```
value = 1 + 2 + 3
```
This change moves the operations to the expression level, as ANTLR4 cannot handle indirect recursions, I had to move the operation rules to the expression level. I do not know if I took the left/right association directives right. That would only affect the ParserTree then the AST build up, though at the moment we do not use those that deep.
> HCL fix compound expression grammar

- php/php.phpunit/src/org/netbeans/modules/php/phpunit/PhpUnitVersion.java
- php/php.phpunit/src/org/netbeans/modules/php/phpunit/commands/PhpUnit.java
- php/php.phpunit/src/org/netbeans/modules/php/phpunit/preferences/PhpUnitPreferences.java
- php/php.phpunit/src/org/netbeans/modules/php/phpunit/ui/customizer/Bundle.properties
- php/php.phpunit/src/org/netbeans/modules/php/phpunit/ui/customizer/CustomizerPhpUnit.form
- php/php.phpunit/src/org/netbeans/modules/php/phpunit/ui/customizer/CustomizerPhpUnit.java
- php/php.phpunit/src/org/netbeans/modules/php/phpunit/ui/options/PhpUnitOptionsPanel.form
- php/php.phpunit/src/org/netbeans/modules/php/phpunit/ui/options/PhpUnitOptionsPanel.java
- php/php.phpunit/src/org/netbeans/modules/php/phpunit/ui/options/PhpUnitOptionsPanelController.java
- https://github.com/apache/netbeans/issues/5790
- Add `PhpUnitVersion`
- Don't use `NetBeansSuite.php` with PHPUnit 10 because `suite()` method is invoked no longer and we have to extend `TestCase`
- See: https://github.com/sebastianbergmann/phpunit/commit/36354a9cdc69ecabd20ac505b07541cfdde50aaa
> Fix for PHPUnit 10 #5790

- java/java.lsp.server/build.xml
- java/java.lsp.server/script/etc/nbcode.clusters
Build script modified to allow for adding extra modules when building extension vsix package (using command: `ant build-vscode-ext -Dextra.modules="<regexp>"`)
> VSCode: Allow for adding extra modules when building extension vsix package

- php/php.editor/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletion.java
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_01a.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_01b.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_01c.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_01d.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_02a.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_02b.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_02c.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_02d.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_02e.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_03a.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_03b.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_03c.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_03d.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_04a.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_04b.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_04c.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_04d.html
- php/php.editor/test/unit/data/testfiles/completion/documentation/issueGH5881.php.testIssueGH5881_04e.html
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCCDocumentationTest.java
- https://github.com/apache/netbeans/issues/5881
- Get also the prefix until the caret position to calculate the correct anchor
```php
class GH5881 {
/**
* Property $prop.
*/
public $prop;
/**
* Property $prop_aa.
*/
public $prop_aa;
/**
* Property $prop_aa_bbb.
*/
public $prop_aa_bbb;
/**
* Property $prop_aa_bb_cc.
*/
public $prop_aa_bb_cc;
/**
* Method method().
*
* @return void
*/
public function method(): void {
}
/**
* Method method_aa().
*
* @return void
*/
public function method_aa(): void {
}
/**
* Method method_aa_bbb().
*
* @return void
*/
public function method_aa_bbb(): void {
}
/**
* Method method_aa_bb_cc().
*
* @return void
*/
public function method_aa_bb_cc(): void {
}
}
$test = new GH5881();
$prop1 = $test->prop_aa_bbb;
$prop2 = $test->prop_aa_bb_cc; …
```
> Fix the problem that documentation for methods and properties is not shown #5881

- java/maven/src/org/netbeans/modules/maven/customizer/CompilePanel.java
Most importantly, make sure the Compile-on-Save feature can still be turned off via the UI following #5826 .  No longer having it enabled by default is great; no longer being (easily) able to disable it less so! :smile: 
The problem is that the value `v` is `null` when the default, as seen in CheckBoxUpdater.
I also moved the warning dialog into an invokeLater to make sure checkbox UI gets updated (at least on my system the tick doesn't show after the dialog opens). And I also temporarily hid the non-working help link - we can follow up to remove or point it at something more useful later.
> Fix the Maven Compile on Save UI.

- java/java.lsp.server/nbcode/integration.java/src/META-INF/services/org.netbeans.modules.java.lsp.server.protocol.CodeActionsProvider
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
Modified to prevent unnecessary parsing of Java sources invoked by Java editor features when Java support if off in Language Server settings.
> VSCode: Prevent unnecessary Java parsing when Java support if off.

- ide/markdown/nbproject/project.xml
- ide/markdown/src/org/netbeans/modules/markdown/MarkdownDataObject.java
- ide/markdown/src/org/netbeans/modules/markdown/MarkdownViewerElement.java
Well, I was missing the Preview functionality for Markdown files. I used some plugins a few years ago. I think the plugin portal is down at the moment, so I could not find that. I came up with something very basic. It uses the existing flexmark library we ship with the IDE. I do not think it's bulletproof, but better than nothing. Regarding that the implementation so simple, its a shame I have not done it earlier, so it could be in NB18.
> A very minimal, but functional viewer for Markdown files.

- .github/workflows/main.yml
- disable CV tests on JDK 8
- move some more jobs to JDK 11
this configuration would allow us to move new modules like rust/go/hcl to JDK 11 and to upgrade exiting modules, like the maven-indexer #4999.
[new NB release policy](https://cwiki.apache.org/confluence/display/NETBEANS/Minimum+JDK+build+and+run+policy)
> prepare NB 19 release cycle for JDK 11.

- .github/workflows/main.yml
- nbbuild/build.xml
Change default metabuild URL to https://netbeans.apache.org/nbbuild/netbeansrelease.json  This currently redirects to the GitHub content link.
Removed direct link from workflows file OPTS.  Both to test this, and so that we can redirect in future without updating the CI config.
> Add metabuild json link via netbeans.apache.org

- java/maven/src/org/netbeans/modules/maven/execute/defaultActionMappings.xml
Add `surefire.failIfNoSpecifiedTests=false` to the default action mappings for running and debugging single integration tests.
Fixes #4513
> Fix running and debugging single integration test (GH4513)

- java/maven/src/org/netbeans/modules/maven/execute/DefaultReplaceTokenProvider.java
- java/maven/test/unit/src/org/netbeans/modules/maven/execute/DefaultReplaceTokenProviderTest.java
Fix unit test on single file being reported as integration test in some cases.
Change isIntegrationTestTarget to use extractFileObjectsfromLookup() as missing DataObject conversion, and make sure an empty list returns false (due to use of allMatch on empty stream).
Fixes #4587
> Fix unit test on single file being reported as integration test GH4587

- README.md
fixes #5836
the gradle daemon is a bit of a mystery to me. I tried -D, env vars etc, the only way to make this work was to put it into the gradle.properties ([that is also how we set up CI](https://github.com/apache/netbeans/blob/fc4a7d4b04e09bb4c50f70b858fe558cf042cb7d/.github/workflows/main.yml#L123-L128)). The most confusing aspect: once it works, you can remove the properties again and it will keep working until you remove the whole `.gradle` folder. (yes I did kill the daemon manually between retries)
> add gradle JDK compatibility notice to readme build section.

- ide/libs.flexmark/external/binaries-list
- ide/libs.flexmark/external/flexmark-0.62.2-license.txt
- ide/libs.flexmark/nbproject/project.properties
- ide/libs.flexmark/nbproject/project.xml
- ide/markdown/nbproject/project.xml
- ide/markdown/src/org/netbeans/modules/markdown/MarkdownViewerElement.java
- nbbuild/licenses/BSD-flexmark
Well, this one is just another low hanging fruit.
First, I've upgraded the flexmark-java library to 0.62.2 (the last which supported Java 8), that might not have been necessary, but 0.50.x is getting dated.
I moved the Preview tab to the first in multiview. I think the generic use case with Markdown files is more read than write oriented.
Then I've added a hyperlink listener to handle the internal and external links.
Added `LSP` label as previosly to markdown only the LSP modules had dependenct on the flexmark-java libraries.
> Markdown viewer links

- java/java.hints/src/org/netbeans/modules/java/hints/bugs/Unused.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/UnusedTest.java
When there's an unused binding, the unused hint with provide a fix suggesting to remove the variable from parent. This patch currently only prevents that fix, as it is not clear what removal from parent means here. That may need some deeper thought. Also, after `_` is implemented, we might reconsider and replace with `_` on appropriate places.
--- …
> Do not attempt to remove unused binding variables for now.

- .gitignore
github will switch everything to Node 16 on the 18th of May:
https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/
[delete-artifact](https://github.com/GeekyEggo/delete-artifact) is the last remaining action which we haven't updated yet. We access the action via a git submodule since it is third-party. Other actions were bumped in #4770 and #5376
+ this PR moves the delete-artifact submodule to the [v2.0.0 tag](https://github.com/GeekyEggo/delete-artifact/releases/tag/v2.0.0)
+ bonus: updated git ignore to ignore all private folders by default
after that we shouldn't see any warnings of this kind anymore:
```
Cleanup Workflow Artifacts
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: …
```
> bump delete-artifact action to v2 to be node 16 compatible.

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
- java/java.lsp.server/vscode/src/extension.ts
Using open type, the editor focus should be placed on the type that was opened.
Seems that VSCode requests the focus correctly when lazy loading of symbol `Location` is done implementing the standard `workspaceSymbol/resolve` LSP call.
For `java.quick.open`, focus is explicitly requested to editor by calling `workbench.action.focusActiveEditorGroup`.
> Modified to ensure opened file focused.

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/database/DatabaseNode.java
"Service Console" has been deprecated. See [this](https://adwc.uscom-east-1.oraclecloud.com/console/index.html?tenant_name=iam-ocid1.tenancy.oc1..fhfhfhfhfs33432232&database_name=adwdb1) link.
```
Service Console has been deprecated as of July 5th, 2022.
You can use Database Actions to access the same set of features available 
in Service Console. For more details on where to find each Service Console 
functionality in Database Actions, see the documentation.
```
This PR uses new replacement URL, which should provide similar functionality.
> Service Console has been deprecated

- platform/core.network/src/org/netbeans/core/network/proxy/ProxyAutoConfig.java
This is a "fix" to get rid of an annoying exception thrown on every launchd as info during windows autoproxy.
I'm not sure this is right approach but "to me" as no URL are set I don't get why it should use http://wdap/wdap.dat.
So exiting early.
That the exception scaring user :p :
INFO [org.netbeans.core.network.proxy.ProxyAutoConfig]: InputStream for http://wpad/wpad.dat throws 
java.net.UnknownHostException: wpad
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
at java.base/java.net.Socket.connect(Socket.java:633)
at java.base/java.net.Socket.connect(Socket.java:583)
at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
at …
> fail proxy pac on windows if no URL

- ide/languages.hcl/build.xml
- ide/languages.hcl/nbproject/project.xml
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/BasicHCLLexer.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/HCLParserResult.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/HCLStructureItem.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/HCLStructureScanner.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/ast/ASTBuilderListener.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/ast/HCLAttribute.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/ast/HCLBlock.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/ast/HCLContainer.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/ast/HCLDocument.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/ast/HCLElement.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/ast/HCLIdentifier.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/ast/SourceRef.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/grammar/g4/HCLExpressionParser.g4
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/terraform/TerraformHCLLexer.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/terraform/TerraformLanguage.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/terraform/TerraformParserResult.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/tfvars/TFVarsLanguage.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/tfvars/TFVarsParserResult.java
- ide/languages.hcl/test/unit/data/testfiles/attributes.hcl
- ide/languages.hcl/test/unit/data/testfiles/attributes.hcl.structure
- ide/languages.hcl/test/unit/data/testfiles/blocks.hcl
- ide/languages.hcl/test/unit/data/testfiles/blocks.hcl.structure
- ide/languages.hcl/test/unit/src/org/netbeans/modules/languages/hcl/HCLStructureTest.java
- ide/languages.hcl/test/unit/src/org/netbeans/modules/languages/hcl/HCLTestBase.java
- ide/languages.hcl/test/unit/src/org/netbeans/modules/languages/hcl/grammar/HCLExpressionParserTest.java
- ide/languages.hcl/test/unit/src/org/netbeans/modules/languages/hcl/grammar/HCLParserTest.java
Well, this one is a bit more than the Navogator.
The AST is kind of ready till Attribute level. Beyond that there is the HCL Expression sub-language which AST still has to be done.
That makes possible to implement the structure scanner part for Navigator.
I've realized that the HCL Expression language can be parsed by the HCL parser itself, no need to generate a separate HCLExpressionParser. That would just duplicate a lot of internal context classes, and so it would needed a duplicate implementation of the expression AST builder.
I plan to remove the Terraform specific Lexer in the future, as that is a duplicate + small addition to the HCLLexer. That is used in the basic syntax Highlight only. It would be better to replace that with parser assisted depending on HCL language flavors.
> Navigator Support for HCL Files

- java/java.editor.base/src/org/netbeans/modules/java/editor/base/fold/JavaElementFoldVisitor.java
- java/java.editor.lib/src/org/netbeans/editor/ext/java/JavaFoldManager.java
- java/java.editor/src/org/netbeans/modules/java/editor/fold/JavaElementFoldManager.java
- java/java.editor/src/org/netbeans/modules/java/editor/fold/JavaFoldTypeProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
The motivation about this was to implement those missing folding blocks in java editor. This was just implemented for imports, classes, inner classes, methods but not for stuff inside methods like if/else if/else, try/catch and loops because all of them are treated like as code blocks.
Please bare with me and my knowledge of the stuff. Unfortunately I dunno why the if statement was implemented, that I removed from JavaElementFoldVisitor but this prevents it from adding folding rectangle to those blocks. This is the only line that I need to change in general but, now I changed the method code block to general code-blocks because now it is not only for methods anymore.
Before:
After:
It works for the mentioned blocks, but switch is still missing.
> #4447 - Fix missing code folding blocks in java editor for conditions, loops and try/catch

- java/java.completion/src/org/netbeans/modules/java/completion/JavaDocumentationTask.java
- java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionCollector.java
- java/java.editor/src/org/netbeans/modules/editor/java/JavaHoverProvider.java
- java/java.editor/src/org/netbeans/modules/editor/java/Utilities.java
- java/java.editor/test/unit/src/org/netbeans/modules/editor/java/GoToSupportTest.java
- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
- java/java.platform/src/org/netbeans/modules/java/platform/queries/PlatformJavadocForBinaryQuery.java
- java/java.sourceui/src/org/netbeans/api/java/source/ui/ElementJavadoc.java
Couple of enhancements to VSCode code completion:
- Parameter names in lambda expressions should be based on type instead of name of the corresponding type parameters
- Hovers for local variables and parameter should provide basic info on var declaration
- Links in code completion documentation and hovers should be resolved to web URLs
> VSCode: Various code completion enhancements.

- ide/api.lsp/apichanges.xml
- ide/api.lsp/manifest.mf
- ide/api.lsp/src/org/netbeans/api/lsp/Completion.java
- ide/api.lsp/src/org/netbeans/modules/lsp/CompletionAccessor.java
- ide/api.lsp/src/org/netbeans/spi/lsp/CompletionCollector.java
- java/java.editor/nbproject/project.xml
- java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionCollector.java
- java/java.lsp.server/nbproject/project.xml
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ImplementAllAbstractMethodsAction.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
- java/java.lsp.server/vscode/src/extension.ts
Code completion for anonymous inner class constructor should generate default implementation for all abstract methods.
E.g. code completion for:
```
Runnable r = new Runnable|
```
should generate:
```
Runnable r = new Runnable() {
@Override
public void run() {
throw new UnsupportedOperationException("Not supported yet.");
}
}
```
> VSCode: Completion for annonymous inner classes improved.

- enterprise/j2ee.sun.ddui/src/org/netbeans/modules/j2ee/sun/validation/constraints/NumberConstraint.java
- enterprise/j2ee.sun.ddui/src/org/netbeans/modules/j2ee/sun/validation/constraints/RangeConstraint.java
- enterprise/javaee.project/src/org/netbeans/modules/javaee/project/api/ant/ui/wizard/ImportBuildfile.java
- ide/api.debugger/src/org/netbeans/api/debugger/Properties.java
- ide/bugtracking.commons/src/org/netbeans/modules/bugtracking/issuetable/NodeTableModel.java
- ide/db.dataview/src/org/netbeans/modules/db/dataview/util/DBReadWriteHelper.java
- ide/db/libsrc/org/netbeans/lib/ddl/util/PListReader.java
- ide/db/src/org/netbeans/modules/db/explorer/dlg/CreateTableDialog.java
- ide/editor.completion/src/org/netbeans/modules/editor/completion/PatchedHtmlRenderer.java
- ide/schema2beans/src/org/netbeans/modules/schema2beans/Common.java
- ide/schema2beans/src/org/netbeans/modules/schema2beans/GraphManager.java
- java/classfile/src/org/netbeans/modules/classfile/CPDoubleInfo.java
- java/form/src/org/netbeans/modules/form/layoutdesign/LayoutDesigner.java
- java/j2ee.persistence/test/unit/src/org/netbeans/test/stub/api/Stub.java
- java/java.j2seproject/src/org/netbeans/modules/java/j2seproject/ui/wizards/ImportFoldersPanel.java
- javafx/javafx2.samples/SwingInterop/src/swinginterop/SampleTableModel.java
- nb/o.n.upgrader/src/org/netbeans/upgrade/systemoptions/SerParser.java
- platform/core.windows/src/org/netbeans/core/windows/view/ViewHelper.java
- platform/core.windows/src/org/netbeans/core/windows/view/ui/MultiSplitPane.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/BaseTabLayoutModel.java
- platform/openide.awt/src/org/openide/awt/HtmlRenderer.java
- platform/openide.explorer/src/org/openide/explorer/propertysheet/IndexedPropertyEditor.java
- platform/openide.explorer/src/org/openide/explorer/view/NodeTableModel.java
- platform/openide.filesystems/src/org/openide/filesystems/XMLMapAttr.java
- profiler/profiler.heapwalker/src/org/netbeans/modules/profiler/heapwalk/ClassesListController.java
- websvccommon/websvc.saas.codegen/src/org/netbeans/modules/websvc/saas/codegen/model/ParameterInfo.java
Cleanup the use of Double primitive wrapper. As of Java 9, the VM can do a better job of handling the
coversion from a Double primitive to a Double Object or vice versa.
This is an extension of the work done in #2498.
No tests have been touched as those expressly need to manage the conversion.
A couple of places I also cleaned up the Float.
>     Cleanup the use of Double primitive wrapper

- enterprise/micronaut/src/org/netbeans/modules/micronaut/MicronautConfigUtilities.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionCollector.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionProvider.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautConfigCompletionTask.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/completion/MicronautHoverProvider.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/hyperlink/MicronautConfigHyperlinkProvider.java
Enable Micronaut HyperlinkProviders again. Deadlocks fixed - `ParserManager.parse(...)` should not be called from AWT EDT anymore.
> Enable Micronaut HyperlinkProviders - deadlocks fixed.

- .github/ISSUE_TEMPLATE/netbeans_bug_report.yml
Update the issue report form for release of Apache NetBeans 18. Can be merged as soon as the announcement and webpage are done.
> Update issue report template for NB18

- java/java.lsp.server/nbcode/integration/build.xml
The build process is broken: the build creates fake icons for these for long time, but creates them after the jar is packaged. It works OK on dev machines, where ant clean is not routinely executed on whole nbcode project, but the build produced by apache CI is broken.
This PR hook to `-pre-jar` target, so the icons appear early enough to get packaged during 1st build as well.
> Copy fake icons before JAR is created

- java/java.lsp.server/build.xml
Steps to reproduce:
1. build the Visual Studio Code extension with `ant build-vscode-ext`
2. the following warning is in the log:
```
npm WARN deprecated vsce@2.6.4: vsce has been renamed to @vscode/vsce. Install using @vscode/vsce instead.
```
This PR upgrades `vsce` to `@vscode/vsce` and uses the latest version 2.19.
> upgrade vsce to @vscode/vsce version 2.19

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/breakpoints/NbBreakpoint.java
As you may know I am working on [mixed Java+Scala codebase](https://github.com/enso-org/enso/). I have developed a NetBeans `.nbm` extension as well as `.vsix` file to support [our sbt based projects](https://github.com/enso-org/enso/tree/0778c850941348fc8fb83eb967f64b761de3743e/tools/enso4igv).
There is a special [ToggleScalaBreakpointActionProvider](https://github.com/enso-org/enso/blob/0778c850941348fc8fb83eb967f64b761de3743e/tools/enso4igv/src/main/java/org/enso/tools/enso4igv/scala/ToggleScalaBreakpointActionProvider.java) that handles breakpoints in Scala sources. It works great in NetBeans IDE. But I'd like it to work **in VSCode as well**!
This PR copies the code from [ToggleScalaBreakpointActionProvider](https://github.com/enso-org/enso/blob/0778c850941348fc8fb83eb967f64b761de3743 …
> Breakpoints in Scala sources in VSCode

- platform/core.startup/src/org/netbeans/core/startup/Splash.java
This is a tiny UI tweak to make the progress indication text in the splash screen "Loading modules..." apply proper subpixel anti-aliasing if configured on the current OS.
> Enable sub-pixel anti-aliasing in splash screen progress text

- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java
- webcommon/javascript2.model/test/unit/data/testfiles/structure/issueGH5184_03.js
- webcommon/javascript2.model/test/unit/data/testfiles/structure/issueGH5184_03.js.model
- webcommon/javascript2.model/test/unit/src/org/netbeans/modules/javascript2/model/ModelTest.java
Fix applies same pattern, that is used in other places where ModelUtils#moveProperty is invoked.
> [JS] Fix ConcurrentModificationException scanning export class {} with multiple members

- ide/httpserver/src/org/netbeans/modules/httpserver/HttpServerModule.java
Tomcat by default places its working directory in the current working directory. This clutters the directory tree and is problematic if the current working directory is not writeable.
Closes: #5990
> Ensure tomcat basedirectory is configured and in a writeable location

- webcommon/html.angular/nbproject/project.xml
- webcommon/html.angular/src/org/netbeans/modules/html/angular/editor/AngularJsCodeCompletion.java
- webcommon/html.angular/src/org/netbeans/modules/html/angular/model/AngularWhenInterceptor.java
- webcommon/html.angular/src/org/netbeans/modules/html/angular/model/ModelUtils.java
- webcommon/javascript2.editor/nbproject/project.xml
- webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/JsCompletionItem.java
- webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/JsSemanticAnalyzer.java
- webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/doc/JsDocumentationCompleter.java
- webcommon/javascript2.editor/src/org/netbeans/modules/javascript2/editor/index/JsIndexer.java
- webcommon/javascript2.editor/test/unit/data/testfiles/hints/issueGH5740.js
- webcommon/javascript2.editor/test/unit/data/testfiles/indexer/SelfreferencingFunction.js.indexed
- webcommon/javascript2.editor/test/unit/data/testfiles/markoccurences/issueGH4376.js
- webcommon/javascript2.editor/test/unit/data/testfiles/markoccurences/issueGH4376.js.structure
- webcommon/javascript2.editor/test/unit/data/testfiles/markoccurences/issueGH4376.js.testIssueGH4376_01.occurrences
- webcommon/javascript2.editor/test/unit/data/testfiles/markoccurences/issueGH4376.js.testIssueGH4376_02.occurrences
- webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/hint/JsGlobalIsNotDeclaredTest.java
- webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/navigation/MarkOccurrenceTest.java
- webcommon/javascript2.knockout/nbproject/project.xml
- webcommon/javascript2.knockout/src/org/netbeans/modules/javascript2/knockout/model/ModelUtils.java
- webcommon/javascript2.model/manifest.mf
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/JsElementImpl.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/JsFunctionImpl.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/api/IndexedElement.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/api/JsElement.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/api/ModelUtils.java
Inside initialisation statements:
```javascript
class Test {
var1 = 123;
var2 = this.var1;
}
```
this needs to evaluate to the surrounding class, to handle this
correctly, search for the right definition of "this" needs to start
at the surrounding object, not the declaration scope of the wrapping
function.
Before:
After:
In arrow functions this is not redefined, but inherited from the outer
scope. In this sample:
```javascript
class Foo {
bar = {};
test(someArray) {
this.bar = {}; // Mark
someArray.forEach((val) => {
this.bar[val] = 1;  // Mark
});
}
}
```
this in the lines with the "Mark" comment is an instance of `Foo` and
thus it is always the same bar. The this scanning needs to skip arrow
functions.
Before (notice, that only property under the cursor is highlighted):
After (notice, …
> [JS] Improve resolving this in ClassElements and in arrow functions 

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
NBLS currently throws `UnsupportedOperationException` when vscode option `java.trace.server` is set to `verbose'. The LSP client sends a `setTrace` notification to the client which was unimplemented.
After discusson with @dbalek, I've decided to just trash the reques: log verbosity can be (and is) controlled by `-J-Dnetbeans.console.logger=true` by the vscode extension client and the number of protocol messages that appear in the client's output is quite high already.
> Ignore setTrace requests

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/launch/NbLaunchRequestHandler.java
In the VS Code, when attempting to start a program using the Run pane, without any file opened, the Run fails, as no main class is found.
This patch proposes to show a dialog so that the user can choose a main class. In case only one main class is found, it is selected automatically.
The intent behind the `getServerLookup()` -> `getServerServicesLookup()` change is to ensure the content of the default lookup is present in `context.getLspSession().getLookup()` only once. It is added there once in the session lookup, and is also part of the server lookup. So, the patch is instead using a subset of the server lookup that does not include the default lookup.
--- …
> Let the user choose main class, when none is open

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/debugging/Debugger.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/ActionProviderImpl.java
When an OpenJDK test is run, ask for JTreg when none can be found, and also look for JTreg version errors, and ask for a newer one if needed. This is particularly useful when running inside VS Code, as there's no Project configuration there.
For technical reasons, this also includes the setting of LSP lookup for debugger as in:
https://github.com/apache/netbeans/pull/5536
---
Please make sure (eg. `git log`) that all commits have a valid name and email address …
> Adding a way to directly specify JTreg when no is known

- java/debugger.jpda.ui/src/org/netbeans/modules/debugger/jpda/ui/models/EvaluatorTableModelFilter.java
While running NetBeans with assertions enabled, while tryping to open the detail/value dialog for the "String value", an AssertionError was observed.
```
java.lang.AssertionError: Debugger lock taken in AWT Event Queue!
at org.netbeans.modules.debugger.jpda.JPDADebuggerImpl$DebuggerReentrantReadWriteLock$DebuggerReadLock.lock(JPDADebuggerImpl.java:2710)
at org.netbeans.modules.debugger.jpda.models.JPDAThreadImpl$ThreadReentrantReadWriteLock$ThreadWriteLock.lock(JPDAThreadImpl.java:2581)
at org.netbeans.modules.debugger.jpda.JPDADebuggerImpl.invokeMethod(JPDADebuggerImpl.java:1080)
at org.netbeans.modules.debugger.jpda.JPDADebuggerImpl.invokeMethod(JPDADebuggerImpl.java:1022)
at org.netbeans.modules.debugger.jpda.models.AbstractObjectVariable.getToStringValue(AbstractObjectVariable.java:500 …
```
> JPDA Evaluator: Value, Description and Children should not be fetched on the EDT

- webcommon/javascript2.model/nbproject/project.xml
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java
- webcommon/javascript2.model/test/unit/data/testfiles/model/classConstructor.js
- webcommon/javascript2.model/test/unit/data/testfiles/model/classConstructor.js.model
- webcommon/javascript2.model/test/unit/src/org/netbeans/modules/javascript2/model/ModelTest.java
- webcommon/libs.nashorn/manifest.mf
- webcommon/libs.nashorn/src/com/oracle/js/parser/Parser.java
- webcommon/libs.nashorn/src/com/oracle/js/parser/ir/FunctionNode.java
- webcommon/libs.nashorn/test/unit/src/com/oracle/js/parser/DumpingVisitor.java
- webcommon/libs.nashorn/test/unit/src/com/oracle/js/parser/ParserTest.java
Before this fix, constructors in classes declared in anonymous
functions were not correctly handled as functions:
One noticeable problem was, that the parameters were reported as
unused, although being accessed in the constructor.
> [JS] Fix handling of class constructor in classes in anonymous functions 

- java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/UnusedDetector.java
- java/java.editor.base/test/unit/src/org/netbeans/modules/java/editor/base/semantic/UnusedDetectorTest.java
- java/java.hints/src/org/netbeans/modules/java/hints/bugs/Unused.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/UnusedTest.java
Recently, I ran into to issues with the unused element hint:
- the detection of unused package private elements sometimes causes problems, e.g. when the index is (for some reason) broken. Overall, it may not be possible to make this work 100%. Suggestion here is to add an option to disable the package private unused detection, with default "enabled".
- some code (OpenJDK, specifically), has private methods that are then looked up using `MethodHandles.Lookup`. The unused detection marks them as unused, which is not quite true. The idea here is to use the method names to (heuristically) try to find out which may be looked up using the `MH.Lookup`, and not mark them as unused.
---
By opening a pull request you confirm that, unless explicitly stated …
> Adding an option to disable unused hint for package private elements,  ignoring elements that possibly are looked up using MethodHandles.Lookup.

- java/maven.indexer/src/org/netbeans/modules/maven/indexer/MinimalArtifactInfoRemoteIndexCreator.java
- java/maven.indexer/src/org/netbeans/modules/maven/indexer/NexusRepositoryIndexerImpl.java
- java/maven.indexer/src/org/netbeans/modules/maven/indexer/api/RepositoryPreferences.java
- java/maven/src/org/netbeans/modules/maven/options/Bundle.properties
- java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.form
- java/maven/src/org/netbeans/modules/maven/options/SettingsPanel.java
- index only interesting fields to reduce index size and upkeep overhead
- this is achieved by using a custom index creator since filters can't remove fields
- reduces central index size from 5.7 GB to 2.8 GB (single threaded)
- reduces central index size from 6.4 GB to 3,4 GB (multi threaded)
- reduces initial indexing time to ~300s on my system (full index)
- artifact date cutoff filter is configurable in the options
- shrinks the index 1.5 GB (multi threaded, 2y filter) when enabled
The filtering is implemented via a custom index creator, for inexplicable reasons I couldn't reproduce my results from a few month ago where i removed fields in the extraction filter. Removing fields there doesn't do anything so we do that one step earlier in the pipeline. …
> maven remote index filters

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddADBAction.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletAction.java
- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/DownloadWalletDialog.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBConnectionProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBConnectionsProvider.java
- java/java.lsp.server/vscode/package.json
- java/java.lsp.server/vscode/src/dbConfigurationProvider.ts
- java/java.lsp.server/vscode/src/extension.ts
Updating a method how Database Connection properties are provided to a running application in NBLS. Former one didn't follow best security practices. Plain text password was stored in VSCode settings json. This is now removed with DBSetEnvCommand. New implementation takes it the other way around. DB connection properties are still stored in NB, when VSCode runs an application it asks NBLS for DB connection details (including password) using DBConnectionProvider.
> Adding DB configuration provider for NBLS

- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/AntDeploymentProviderImpl.java
- enterprise/tomcat5/src/org/netbeans/modules/tomcat5/j2ee/TomcatPlatformImpl.java
Library Notes:
- Tomcat 11 increased min supported Java version to 21
- Add support for Java 22
- Use try-with-resources
Testing:
- Verify successful execution of Sigtests
- Test Tomcat and TomEE and successfully:
- Register it
- Check correct Java SE support for Java 22
- Check correct Java/Jakarta EE support from JEE 7 to JakartaEE 10
- Create Web App Project
- Deploy and run a servlet
> Tomcat 11 increased min supported Java version to 21

- ide/db/src/org/netbeans/modules/db/explorer/action/ConnectAction.java
In context of LSP, when DB connection has incorrect username password, the user does not have a way to correct it. This PR tries to fix this problem and allows user to fill in new username and password, when connection fails. The same functionality was already available in netbeans, but VSCode integration (via LSP) just displayed the error dialog with exception and that's it. The LSP implenetation uses already established `headless` variable to distinguish GUI and LSP part. Common functionality of getting username/password was extracted to `Credentials` abstract class, with two implementations. One for LSP (`CredetialsLine`), which uses `NotifyDescriptor.ComposedInput`  and the second one (`CredetialsUI`) for Swing UI.
> Allow to re-enter username and password

- platform/core.multitabs/src/org/netbeans/core/multitabs/impl/TabDataRenderer.java
this makes it look consistent to regular editor tabs
multitabs code is running when for example sorted-document-list is enabled in:
`tools -> options -> appearance -> document tabs -> "Sort opened documents list by default" checkbox`
extracted from #4948
> Fix multitabs underline at top tab rendering.

- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/maven.properties
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
- java/maven/src/org/netbeans/modules/maven/NbMavenProjectImpl.java
- java/maven/src/org/netbeans/modules/maven/problems/MavenModelProblemsProvider.java
- java/maven/src/org/netbeans/modules/maven/problems/ProblemReporterImpl.java
- java/maven/src/org/netbeans/modules/maven/problems/SanityBuildAction.java
Also see #5978.
First of all, `log4j` is not a good example. The project is set up in a way that **requires** that JDK8 is **on the PATH** while maven `toolchains.xml` define JDK 9+. The project will not compile if (e.g.) JDK11 is on PATH or JDK8 is defined in toolchains.
But the example surfaced several interesting things. Most importantly, maven processes for the parent *and subprojects* are launched in parallel. In reality, parent priming build is most likely to fetch all artifacts for all projects in the reactor - so running maven for a subproject is not necessary.  So it is worth to wait for preceding priming builds to complete before trying another one.
Next bug is that, after priming, the problem reporter does not refresh early - so `SanityBuildAction` could not even re-check the …
> #5978: Maven/priming optimization

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NetBeansRunSinglePlugin.java
- extide/gradle/src/org/netbeans/modules/gradle/execute/GradleDaemonExecutor.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/action-mapping.xml
The `runSingle` task we use in Gradle to execute a specific class (not the one configured in the buildscript) brings some issues if frameworks that define their own execution properties are involved - e.g. Micronaut. 
Micronaut app plugin adds certain system properties to "run" task, and also injects a `developmentOnly` configuration - it's assumed that the application is run locally and not in a cloud environment, or otherwise deployed. When NB uses `runSingle`, the Java process does not get such configration, and so works differently than when run from the commandline. 
This PR changes NB to use the standard `run` action, but Netbeans tooling plugin configures the `JavaExec` tasks to run the specific class (still defined by project property). For compatibilty with customized …
> Configure regular "run" / JavaExec-style tasks for single-class execution. Retain runSingle for compatibility.

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBAddConnection.java
VSCode only: Sometimes new DB connection is not displayed even if URL and username, password are correctly entered. This probem is caused by unconditionally removing database commection in finally block in `validate()` method. The rest of the code expects that such connection is reused if there are no schemas. The fix is to change the finally block to remove connection only in case of connection failure or non-empty list of schemas is retrieved from database.
> Apache LS does not add DB connection

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBAddConnection.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBCommandProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBConnectionProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/htmlui/WebView.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ImplementAllAbstractMethodsAction.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeClientCapabilities.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/QuickOpen.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/SurroundWithHint.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TestClassGenerator.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ChangeMethodParametersRefactoring.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ExtractSuperclassOrInterfaceRefactoring.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/MoveRefactoring.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/PullUpRefactoring.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/PushDownRefactoring.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
- java/java.lsp.server/vscode/package.json
- java/java.lsp.server/vscode/src/dbConfigurationProvider.ts
- java/java.lsp.server/vscode/src/extension.ts
- java/java.lsp.server/vscode/src/launchConfigurations.ts
- java/java.lsp.server/vscode/src/test/suite/extension.test.ts
- java/java.lsp.server/vscode/src/test/suite/testutils.ts
- java/java.lsp.server/vscode/src/testAdapter.ts
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/CodeLensProviderImpl.java
> Reverting "Prefixing all code names of commands with 'nbls'.", as more time will be needed to discuss, validate the patch and adjust to it.

- java/java.lsp.server/vscode/src/nbcode.ts
Shell environment variable cannot contain dot. Shells map environment variables to shell variables and in most shells, variable names are limited to ASCII alphanumerical characters and _ where the first character can't be a digit.
Dot was replaced by underscode.
> shell env. variable cannot contain dot

- java/java.lsp.server/licenseinfo.xml
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/NodePropertiesProvider.java
- java/java.lsp.server/vscode/.vscode/tasks.json
- java/java.lsp.server/vscode/esbuild.js
- java/java.lsp.server/vscode/package-lock.json
- java/java.lsp.server/vscode/package.json
- java/java.lsp.server/vscode/src/extension.ts
- java/java.lsp.server/vscode/src/propertiesView/controlTypes.ts
- java/java.lsp.server/vscode/src/propertiesView/propertiesHtmlBuilder.ts
- java/java.lsp.server/vscode/src/propertiesView/propertiesView.ts
- java/java.lsp.server/vscode/src/propertiesView/script.ts
- java/java.lsp.server/vscode/src/typesUtil.ts
- java/java.lsp.server/vscode/tsconfig.json
- nbbuild/licenses/MIT-sindre-sorhus
- nbbuild/misc/prepare-bundles/src/main/java/org/netbeans/prepare/bundles/PrepareBundles.java
Adding ability to open property sheet of database connection in VSCode extension.
> Adding ability to edit database connection properties in VSCode extension

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddADBAction.java
If you clicked the Add Oracle Autonomous DB, selected oraclelabs tenancy & gcn-dev compartment. Select Database quick pick is now displayed, which actually shows another compartments. This view should actually show a mixed list of databases and nested compartments. There's no way to identify whether an entry represents a compartment or database. This fix displays a flat list of all compartments using fully qualified names in the Select Compartment quick pick to select the compartment in a single step, the same way as used in the GCN ext. This way the following Select Database quick pick can really display just databases.
> Add Oracle Autonomous DB - Select Compartment

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
Switch the FlatLaf tab type for standard JTabbedPane to card (from underline). Also add some top inset as that's necessary in a few places.
I've been running with this configured in local UI properties for months now.  I find the underline tab type, particularly when unfocused, difficult to discern which tab is active.  This seems to fit better with the editor / view tab changes too.  Thought I'd open this as a potential default change ...
> Switch FlatLaf JTabbedPane tab type to card.

- rust/rust.cargo/src/org/netbeans/modules/rust/cargo/api/CargoCommand.java
- rust/rust.project/nbproject/project.xml
- rust/rust.project/src/org/netbeans/modules/rust/project/RustProject.java
- rust/rust.project/src/org/netbeans/modules/rust/project/RustProjectActionProvider.java
- rust/rust.project/src/org/netbeans/modules/rust/project/RustProjectOperations.java
- rust/rust.project/src/org/netbeans/modules/rust/project/layer.xml
- rust/rust.project/src/org/netbeans/modules/rust/project/ui/RustProjectRootNode.java
- rust/rust.project/src/org/netbeans/modules/rust/project/ui/actions/CargoExecutionCommand.java
- rust/rust.project/src/org/netbeans/modules/rust/project/ui/actions/Command.java
- rust/rust.project/src/org/netbeans/modules/rust/project/ui/actions/CopyCommand.java
- rust/rust.project/src/org/netbeans/modules/rust/project/ui/actions/DeleteCommand.java
- rust/rust.project/src/org/netbeans/modules/rust/project/ui/actions/GlobalCommand.java
- rust/rust.project/src/org/netbeans/modules/rust/project/ui/actions/MoveCommand.java
- rust/rust.project/src/org/netbeans/modules/rust/project/ui/actions/RenameCommand.java
- rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/RustProjectOperationsTest.java
- rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Reference.Cargo.DottedName.toml
- rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Reference.Cargo.toml
- rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Test.Cargo.DottedName.toml
- rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Test.Cargo.LiteralMultilineString.toml
- rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Test.Cargo.LiteralString.toml
- rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Test.Cargo.MultilineString.toml
- rust/rust.project/test/unit/src/org/netbeans/modules/rust/project/data/Test.Cargo.String.toml
The NetBeans infrastructure provides common actions for projects. Covered by this change are:
- Versioning
- History
- Open in Terminal
- Open in System
- Find...
- Close
- Rename
- Move
- Copy
- Delete
The Debug action was removed as it is not yet implemented.
Before:
After:
> Ensure common project actions are available in Rust projects

- enterprise/micronaut/nbproject/project.xml
- enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolFinder.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/symbol/MicronautSymbolSearcher.java
- groovy/groovy.editor/src/org/netbeans/modules/groovy/editor/language/GroovyTypeSearcher.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
Adding an ability to navigate around the Micronaut projects by URI and beans.
The keyboard short cuts for that are:
Mac: Cmd-Shift-O (symbols in file), Cmd-T (symbols in workspace)
Linux/Windows: Ctrl-Shift-O (symbols in file), Ctrl-T (symbols in workspace)
Examples
@/ shows all defined request mappings (mapped path, request method, source location)
@+ shows all defined beans (bean name, bean type, source location)
> Ability to navigate around Micronaut project by URI and beans.

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBAddConnection.java
Register Database for Micro/GCN stops when username should be provided. The LSP fails with:
```
WARNING [org.netbeans.modules.java.lsp.server.protocol.Server]: Error occurred during LSP message dispatch
java.lang.NullPointerException: Property must not be null: value
at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:29)
at org.netbeans.modules.java.lsp.server.input.ShowInputBoxParams.<init>(ShowInputBoxParams.java:62)
at org.netbeans.modules.java.lsp.server.input.ShowInputBoxParams.<init>(ShowInputBoxParams.java:66)
at org.netbeans.modules.java.lsp.server.input.InputBoxStep.<init>(InputBoxStep.java:56)
at org.netbeans.modules.java.lsp.server.db.DBAddConnection.lambda$processCommand$0(DBAddConnection.java:127)
```
The `InputBoxStep` does not accept null for `value`, …
> LSP: NPE from InputBoxStep fixed

- ide/lexer.antlr4/apichanges.xml
- ide/lexer.antlr4/nbproject/project.properties
- ide/lexer.antlr4/src/org/netbeans/spi/lexer/antlr4/AbstractAntlrLexerBridge.java
- ide/lexer.antlr4/src/org/netbeans/spi/lexer/antlr4/LexerInputCharStream.java
- ide/lexer.antlr4/src/org/netbeans/spi/lexer/antlr4/package-info.java
Nothing spectacular here, just got an idea, while reading [JavaLexer](https://github.com/apache/netbeans/blob/297109f9b8a7944568a6d3fcddcee3ef625ae717/java/java.lexer/src/org/netbeans/lib/java/lexer/JavaLexer.java#L1326). It may or may not improve the editor performance. I have done no measurements. Tested with an in-progress version of my HCL Lexer, I haven't noticed any changes, however more complex languages may benefit from this.
> Flyweight Token support for ANTLR4 Lexer Bridge

- ide/spi.palette/src/org/netbeans/modules/palette/ui/DnDSupport.java
- platform/openide.explorer/src/org/openide/explorer/view/OutlineViewDropSupport.java
- platform/openide.explorer/src/org/openide/explorer/view/TreeViewDropSupport.java
When doing drag-and-drop in tree, tree-table or palette, then the insert indicator lines are painted at wrong location in NB 18 on Windows 10/11 with FlatLaf.
(red arrow indicates the correct location where the dnd lines should be painted)
The reason for this problem is that since FlatLaf 3.1 (since NB 18), glass panes are not located at location `0,0` in root pane (if FlatLaf window decorations are enabled). But NetBeans code converts locations to root pane coordinates and uses them to paint on glass pane, which is not located at `0,0` in root pane.
This PR fixes the problem for TreeView, OutlineView (e.g. used in "Search Result" view) and palette.
I've searched the NB source code for `getRootPane`, `convertPoint` and `convertRectangle` and checked results whether coordinate conversion …
> FlatLaf: fix location of drag-and-drop insert indicator lines

- ide/spi.palette/src/org/netbeans/modules/palette/ui/DropGlassPane.java
- platform/openide.explorer/src/org/openide/explorer/view/DropGlassPane.java
The drag-and-drop insert indicator lines for TreeView, OutlineView and Palette were painted using six `g.drawLine()` statements, which work fine for 100% screen scaling:
But not so good on 150% screen scaling (you can see the six single lines):
This PR changes painting to use a single filled shape and enables antialiasing. At 100%:
At 150%:
This PR also sets the painting color of the D&D line for the palette (was not set before before):
Also fixed some compiler warnings (unused imports, missing Override, ...)
> improve/fix painting of drag-and-drop insert indicator lines on HiDPI screens

- extide/o.apache.tools.ant.module/src/org/apache/tools/ant/module/api/IntrospectedInfo.java
- java/maven/src/org/netbeans/modules/maven/queries/MavenFileOwnerQueryImpl.java
- nb/o.n.upgrader/src/org/netbeans/upgrade/CopyFiles.java
- platform/core.windows/src/org/netbeans/core/windows/TopComponentTracker.java
- platform/options.api/src/org/netbeans/modules/options/export/OptionsExportModel.java
The code point '\u0000' breaks the Preferences storage as demonstrated in https://bugs.openjdk.org/browse/JDK-8068373, as preventive measure it can't be used in keys since https://bugs.openjdk.org/browse/JDK-8084823.
There are many reports of windows users running into seemingly unrelated issues, but closer investigation showed that they all had at some point "invalid code point" exceptions in the log.
this usually happens in a code pattern like this:
```java
for (String k : pref.keys()) { // contains an invalid key
... = pref.get(key, null);  // throws IAE
}
```
It is not clear what causes the corruption (and why it seems to only occur on windows), this PR adds some defensive code to cover some common cases, logs it and makes sure no corrupted properties files are imported from old …
> Defensive guards against invalid code points in preferences.

- java/java.hints/src/org/netbeans/modules/java/hints/encapsulation/ReturnEncapsulation.java
Small update which adds support for unmodifiable and sequenced collections.
Reduces some false positives. This hint is still of fairly limited use since it produces false positives for fields which are initialized in static blocks or constructors. (hint is off by default I believe)
> Update collection return encapsulation hint.

- platform/core.ui/src/org/netbeans/core/ui/sysopen/SystemOpenAction.java
As discussed in #6043 , various minor improvements to `SystemOpenAction`- add a default shortcut (`SO-S`), add to editor tab actions, and filter out `.shadow` files from list.
> Various improvements to "Open in System" action

- ide/lib.terminalemulator/src/org/netbeans/lib/terminalemulator/MyFontMetrics.java
Change the rounding strategy in the terminal font metrics so that extra cell width is only added where the character width is more than half the standard width more.
Suspected cause of #5980 - dev build for testing.
> Update rounding in terminal font metrics to address GH5980.

- .github/workflows/main.yml
- php/php.editor/nbproject/project.properties
I checked the last 10 merges to master and all of them failed on first attempt. Most failures were caused by the issue described in #5955
last 10 merge failures including test restarts till green:
```
BeforeFirstTest: org.netbeans.core.windows.awt.ValidateLayerMenuTest
BeforeFirstTest: org.netbeans.core.windows.awt.ValidateLayerToolbarTest
BeforeFirstTest: org.netbeans.modules.favorites.AddToFavoritesTest
BeforeFirstTest: org.netbeans.modules.favorites.AddToFavoritesTest
BeforeFirstTest: org.netbeans.modules.favorites.HomeFolderTest
BeforeFirstTest: org.netbeans.modules.favorites.RemoveFromFavoritesTest
BeforeFirstTest: org.netbeans.modules.favorites.RemoveFromFavoritesTest
BeforeFirstTest: org.netbeans.modules.favorites.RemoveFromFavoritesTest
BeforeFirstTest: …
```
> Stabilize some unreliable tests for smoother CI operation

- .github/workflows/main.yml
- java/maven/src/org/netbeans/modules/maven/ModuleInfoSupport.java
- java/maven/test/unit/src/org/netbeans/modules/maven/ModuleInfoSupportTest.java
I noticed, that the function "Add to Moduleinfo" that can be invoked on maven dependencies does not work. Checkin the code showed, that the access to the AST has to be updated to the current compiler interface.
> Fix wrong javac tree access for module information in modular maven project

- .github/workflows/main.yml
- apisupport/apisupport.ant/test/unit/src/org/netbeans/modules/apisupport/project/suite/BuildZipDistributionTest.java
- harness/nbjunit/src/org/netbeans/junit/NbTestCase.java
- harness/nbjunit/test/unit/src/org/netbeans/junit/NbModuleSuiteTest.java
- platform/autoupdate.services/test/unit/src/org/netbeans/modules/autoupdate/services/NewClustersRebootTest.java
- platform/o.n.bootstrap/src/org/netbeans/Bundle.properties
- platform/o.n.bootstrap/src/org/netbeans/Main.java
as previously discussed in https://github.com/apache/netbeans/pull/5852#issuecomment-1524695759, NetBeans needs to inform the user if the runtime JDK does not meet the [requirements](https://cwiki.apache.org/confluence/display/NETBEANS/Minimum+JDK+build+and+run+policy). The current warning instructed the user to install Java 7, which is a bit outdated.
> Update JDK version requirement warning

- ide/languages.hcl/nbproject/project.xml
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/BasicHCLLexer.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/HCLIndenter.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/HCLLanguage.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/HCLTokenId.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/ast/ASTBuilderListener.java
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/grammar/g4/HCLExpressionParser.g4
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/grammar/g4/HCLLexer.g4
- ide/languages.hcl/src/org/netbeans/modules/languages/hcl/grammar/g4/HCLLexerBasics.g4
- ide/languages.hcl/test/unit/src/org/netbeans/modules/languages/hcl/HCLIndenterTest.java
Making HCL editing a bit easier...
> Added basic line indenting to HCL languages.

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/FormatterDocument.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/ImplementAllAbstractMethodsAction.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
I am trying to provide [structure view for Enso VSCode extension](https://github.com/enso-org/enso/tree/develop/tools/enso4igv#building-vscode-extension) via [StructureProvider](https://bits.netbeans.org/18/javadoc/org-netbeans-api-lsp/org/netbeans/spi/lsp/StructureProvider.html). While debugging why it is no working, I realized that there is an unnecessary dependency on `LineDocument` at a lot of places which prevents my implementation of `StructureProvider` to be called.
NetBeans IDE is supposed to work with any `StyledDocument`. Additional operations are abstracted into [NbDocument](https://bits.netbeans.org/18/javadoc/org-openide-text/org/openide/text/NbDocument.html) with _effective delegation_ to NetBeans editor implementation and _reasonable fallback_ for other `StyledDocument` …
> Avoid needless dependency on LineDocument

- php/php.samples/samples_src/Calculator-PHPUnit/composer.json
- php/php.samples/samples_src/Calculator-PHPUnit/readme.html
- php/php.samples/samples_src/Calculator-PHPUnit/test/phpunit.xml
- Update the version to PHPUnit 10
- Remove the unavailable URL from readme.html
- Add setting for code coverage to readme.html
- Fix the phpunit.xml (the `filter` element is available no longer. Instead, use the `coverage` element.)
- See: https://docs.phpunit.de/en/10.1/configuration.html (https://phpunit.de/documentation.html)
> Update the PHP sample project for PHPUnit

- .asf.yaml
This PR proposes to add Benjamin Asbach to the collaborators list.
The collaborator/triage role unlocks many github features like labels, CI or issue management which makes contributing a smoother experience.
[apache doc](https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=INFRA&title=Git+-+.asf.yaml+features#Git.asf.yamlfeatures-AssigningexternalcollaboratorswiththetriageroleonGitHub)
[github doc (triage role)](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role)
@asbachb please make sure to read the CI section on the [wiki](https://cwiki.apache.org/confluence/display/NETBEANS/PRs+and+You+-+A+reviewer+Guide) to understand how PR labels are used for the NetBeans repo.
> Add @asbachb to collaborator/triage list.

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/ui/FlatEditorTabCellRenderer.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/WinFlatEditorTabCellRenderer.java
Fix FlatEditorTabCellRenderer to not return close button bounds when clipped and not painting it. This seems to be the cause of #4738 and #6143
> Fix tab closing when trying to select partly clipped tab.

- ide/db/src/org/netbeans/modules/db/explorer/action/ConnectAction.java
As of NetBeans 18, the API method DatabaseConnection.showConnectionDialog no longer works when called from the EDT. It now gives the following exception:
```
java.lang.Error: Cannot call invokeAndWait from the event dispatcher thread
at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1351)
at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1344)
at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
at org.netbeans.modules.db.explorer.action.ConnectAction$ConnectionDialogDisplayer.showDialog(ConnectAction.java:254)
at org.netbeans.modules.db.explorer.DatabaseConnection$5.run(DatabaseConnection.java:1230)
at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEvent(NbMutexEventProvider.java:97)
at …
```
> Fix 'Cannot call invokeAndWait' when invoking DatabaseConnection.showConnectionDialog

- java/form/src/org/netbeans/modules/form/Bundle.properties
- java/form/src/org/netbeans/modules/form/FormEditorCustomizer.java
- java/form/src/org/netbeans/modules/form/JavaCodeGenerator.java
For form designer I created option "Create lambda listeners if possible" which is available instead of anonymous innerclasses when possible. It's located in form properties and seems work fine. 
screenshots:
> Provide Lambda expression option in Listener generation style

- platform/janitor/src/org/netbeans/modules/janitor/Janitor.java
- platform/janitor/src/org/netbeans/modules/janitor/JanitorOptionsPanel.java
Janitor will write a `.lastUsedVersion` file into user and cache directory in order to track the version of NetBeans they are used last. From there following versions shall know the associated version of that directory. 
NetBeans used the name of the directory. In the Snap version that directory name is the Snap revision number which could result messages that `NetBeans 76 was last used ...`
It's probably easier to review the new file instead of the diff.
> Rework Janitor, try to use real version numbers, in the future

- php/php.editor/src/org/netbeans/modules/php/editor/actions/FixUsesPerformer.java
- php/php.editor/test/unit/data/testfiles/actions/testIssue210093/01/testIssue210093_01.php.fixUses
- php/php.editor/test/unit/data/testfiles/actions/testNoChanges/01/testNoChanges_01.php
- php/php.editor/test/unit/data/testfiles/actions/testNoChanges/01/testNoChanges_01.php.fixUses
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/actions/FixUsesPerformerTest.java
- https://github.com/apache/netbeans/pull/5681
- Avoid changing the file state if the created string is the same as the existing use statements
> Don't remove existing uses if they are the same as the created string for use statements

- .asf.yaml
see discussion @ [dev list](https://lists.apache.org/thread/lps7q24bcl9d2hg1rhhy68qc5fn22r3t)
reasons:
- not transparent how exactly github is squashing a PR, this can lead to noreply email commit headers etc
- squashing locally as last post-review step before merge is probably the better workflow anyway and makes it less likely to merge with the wrong setting
> turn github PR squash feature off.

- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/UpdateDependencyHint.java
Empty version Strings in the pom should not cause exceptions.
fixes #6180
> Fix NumberFormatException in maven dependency update hint.

- php/php.composer/src/org/netbeans/modules/php/composer/options/ComposerOptionsValidator.java
- php/php.composer/test/unit/src/org/netbeans/modules/php/composer/options/ComposerOptionsValidatorTest.java
- https://github.com/apache/netbeans/issues/6192
- https://getcomposer.org/doc/04-schema.md#name
- VendorName/PackageName: `^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]|-{1,2})?[a-z0-9]+)*$`
Before:
After:
> Fix the vendor name regex for Composer #6192

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
- java/java.lsp.server/vscode/package.json
- java/java.lsp.server/vscode/src/extension.ts
Blocking call for workspace symbols until projects get opened and scanning is finished.
Implementing notifications to allow for LSP clients to listen on scanning runs.
> LSP:  Block call for workspace symbols until projects get opened

- ide/editor.completion/src/org/netbeans/modules/editor/completion/CompletionSettings.java
- ide/editor.settings/src/org/netbeans/api/editor/settings/SimpleValueNames.java
- ide/options.editor/src/org/netbeans/modules/options/editor/completion/Bundle.properties
- ide/options.editor/src/org/netbeans/modules/options/editor/completion/CodeCompletionOptionsPanelController.java
- ide/options.editor/src/org/netbeans/modules/options/editor/completion/GeneralCompletionOptionsPanel.form
- ide/options.editor/src/org/netbeans/modules/options/editor/completion/GeneralCompletionOptionsPanel.java
- java/java.editor/src/org/netbeans/modules/editor/java/JavaCompletionItem.java
- java/java.editor/src/org/netbeans/modules/editor/java/Utilities.java
Here's a quick and dirty attempt at implementing an option to disable the annoying tooltips that show when completing on functions, as per [NETBEANS-5719].
---
If you're a committer, please label the PR before pressing "Create pull request" so that the right …
> [NETBEANS-5719] Add option to disable tooltips for parameter completion.

- .github/workflows/main.yml
- java/java.openjdk.project/nbproject/project.properties
- java/java.openjdk.project/nbproject/project.xml
- java/java.openjdk.project/test/unit/src/org/netbeans/modules/java/openjdk/project/ClassPathProviderImplTest.java
while reviewing #6067 I noticed that the tests were not running. Fixing them was relatively easy since the symptom is the same as in #5166.
j2seplatform dependency fixes "java.net.MalformedURLException: unknown protocol: nbjrt"
tested on JDK 11 and 21, ran them several times, seem to be reliable. They print so many stack traces though that it is hard to figure out for me if this is intended behavior or not.
meta issue #4904
> Repair openjdk.project tests and add them to CI

- .github/workflows/main.yml
- enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/WildflyClassLoader.java
- enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/WildflyDeploymentFactory.java
- enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/ide/commands/WildflyClient.java
- enterprise/javaee.wildfly/src/org/netbeans/modules/javaee/wildfly/ide/commands/WildflyManagementAPI.java
NetBeans communicates to Wildfly via management api. This functionality depends
on several Wildfly classes which are pulled from the Wildfly installation.
It seems that in 28.0.1 some classes and jars were moved which prevents NetBeans
from communicating to Wildfly.
This change simplify the current logic gathering different jars and just use
`jboss-cli-client` which should contain all necessary classes which are needed
to connect to Wildflys management interface.
I did some manual testing:
* Start / Stop /Deploy Wildfly 28.0.1
* Start / Stop / Deploy Wildfly 27.0.1
* I checked for classes loaded by plugin
* Downloaded all available Wildfly & JBoss EAP servers
* Created a test file which creates a Classloader per server and try to load the found classes
```java
/*
* Licensed to the Apache …
```
> Add support for Wildfly 28

- ide/gsf.testrunner.ui/nbproject/project.xml
- java/java.openjdk.project/nbproject/project.xml
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/ActionProviderImpl.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/ClassPathProviderImpl.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/jtreg/TestClassInfoTask.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/ActionProviderImpl.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/ClassPathProviderImpl.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/JDKProject.java
- java/java.openjdk.project/src/org/netbeans/modules/java/openjdk/project/UnitTestForSourceQueryImpl.java
- java/java.testrunner.ui/nbproject/project.xml
- java/testng.ui/nbproject/project.xml
- java/testng.ui/test/unit/src/org/netbeans/modules/testng/ui/actions/RetoucheTestBase.java
- java/testng.ui/test/unit/src/org/netbeans/modules/testng/ui/actions/TestClassInfoTaskTest.java
New versions of jtreg (the test framework for OpenJDK) support running a single test method. This patch adds support for this for junit, testng and javac's internal framework `TestRunner`, to run individual test methods. It also fixes some problems found along the way: JUnit 5 support for jtreg tests, test method inside a class marked as test are recognized for TestNG.
---
Please make sure (eg. `git log`) that all commits have a valid name and email address …
> Adding ability to run a single sub-test for tests under jtreg.

- java/java.hints.test/src/org/netbeans/modules/java/hints/test/api/HintTest.java
- java/java.hints/src/org/netbeans/modules/java/hints/bugs/NPECheck.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/bugs/NPECheckTest.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/ConvertToSwitchPatternInstanceOfTest.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/jdk/mapreduce/ForLoopToFunctionalHintTest.java
The first commit is fixing the test framework itself since some tests were using the `assertNotContainsWarnings` wrong.
`assertContainsWarnings` checks against `toString()` which is the full error state, including line number and position.
`assertNotContainsWarnings` is only checking `getDescription()`, but the doc was copied from `assertContainsWarnings` which means that all tests which actually followed the doc, didn't verify anything.
second commit makes the NPECheck hint `Objects.requireNonNull` aware.
fixes #6149
> Make NP Dereference hint aware of Objects.requireNonNull().

- enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautEntity.java
Adding progress for a whole Micronaut Entity wizard. In NetBeans there are particular progress bars displayed in modal window on top of the wizard dialog. Adding progress handle to createFromTemplate() to correctly show progress in VSCode as well
> Adding progress to Entity Classes from Database

- java/maven.embedder/src/org/netbeans/modules/maven/embedder/MavenEmbedder.java
- java/maven/src/org/netbeans/modules/maven/problems/MavenModelProblemsProvider.java
- java/maven/src/org/netbeans/modules/maven/problems/ProblemReporterImpl.java
- java/maven/test/unit/src/org/netbeans/modules/maven/classpath/AbstractProjectClassPathImplTest.java
There was a bug in the loop that causes the values NOT to be cached when the loop exited unsuccessfully, so the detection happened over and over again - computation intensive. This PR makes just one repeated attempt to resolve the artifacts, then reports whatever results are computed.
The reported error was made possible also because simple file-exists check is not enough: in the situation described by #6176, the artifact file physically exists locally (so priming detection evaluated that as an inconsistency and looped again), but is actually refused by Maven, as it is recorded to belong to a remote repository, but was never downloaded from there. The changes to `MavenEmbedder` use EnhancedLocalRepository that checks that thoroughly (the same way as Maven does during build). In addition …
> Fix cycle in problem reporter with unreachable artifacts.

- ide/api.lsp/apichanges.xml
- ide/api.lsp/manifest.mf
- ide/api.lsp/src/org/netbeans/api/lsp/LazyCodeAction.java
- java/java.hints/nbproject/project.xml
- java/java.hints/src/org/netbeans/modules/java/hints/infrastructure/JavaErrorProvider.java
- java/java.lsp.server/nbproject/project.xml
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
CodeAction edits could be computed lazily only when needed. This should speed up LSP server processing as most of the CodeAction edit computations require a modification task to be executed.
> Allow for a lazy computation of CodeAction edits.

- java/debugger.jpda/src/org/netbeans/modules/debugger/jpda/models/ShortenedStrings.java
I have also simplified some logic related to accessing the backing data. My light tests (of opening and debugging a Java app) passed.
> Fix for BigStringCustomEditor not being able to save Strings backed by byte arrays

- java/java.j2seplatform/src/org/netbeans/modules/java/j2seplatform/platformdefinition/J2SEPlatformDefaultJavadocImpl.java
- Add javadoc support for the 2nd jdk early release that happens 3 months after
the 1st jdk early release (usually the 9th day of the month).
Start of release updates for the last 5 JDK's:
|  JDK 18  | JDK 19 | JDK 20 | JDK 21 | JDK 22 |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 2021-06-10 | 2021-12-09 | 2022-06-09 | 2022-12-08 | 2023-06-08 |
Testing:
- Verify successful execution of Sigtests
- Register JDK's and verify that the javadoc is correct.
> Add javadoc support for the 2nd jdk early release

- enterprise/j2ee.ejbcore/licenseinfo.xml
- enterprise/j2ee.ejbcore/nbproject/org-netbeans-modules-j2ee-ejbcore.sig
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/api/codegeneration/SessionGenerator.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/jpa/dao/AppServerValidationPanel.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/session/SessionEJBWizard.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/resources/layer.xml
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/resources/templates/EJB40MessageDrivenBean.template
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/resources/templates/EJB40SessionLocal.template
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/resources/templates/EJB40SessionRemote.template
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/resources/templates/EJB40SingletonEjbClass.template
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/resources/templates/EJB40StatefulEjbClass.template
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/resources/templates/EJB40StatelessEjbClass.template
- enterprise/j2ee.ejbcore/test/unit/src/org/netbeans/modules/j2ee/ejbcore/api/codegeneration/SessionGeneratorTest.java
- java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/PersistenceClientEntitySelectionVisual.java
- java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/entity/EntityWizard.java
- java/j2ee.persistence/src/org/netbeans/modules/j2ee/persistence/wizard/fromdb/JavaPersistenceGenerator.java
- java/j2ee.persistence/test/unit/src/org/netbeans/modules/j2ee/persistence/wizard/entity/EntityWizardTest.java
Added ability for Jakarta EE projects to:
* Create entities from database tables
* Create message driven, stateful, stateless and session beans
This should fix #4827 #4828
> Jakarta EE Entitiy and EJB support

- platform/core.windows/src/org/netbeans/core/windows/services/DialogDisplayerImpl.java
- platform/core.windows/src/org/netbeans/core/windows/services/NbDialog.java
- platform/core.windows/src/org/netbeans/core/windows/services/NbPresenter.java
- platform/core.windows/src/org/netbeans/core/windows/services/NodeOperationImpl.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/DialogDisplayerImplTest.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/NbDialogTest.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/NbPresenterTest.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/NotifyLaterTest.java
- platform/openide.util.ui/apichanges.xml
- platform/openide.util.ui/src/org/openide/util/Utilities.java
Updates to #5989 by @rkeen-siemens to address comments and to check tests before we branch for NB19.
Fixes #5987
> Use the currently active dialog as the presenter parent

- platform/core.windows/src/org/netbeans/core/windows/services/DialogDisplayerImpl.java
- platform/core.windows/src/org/netbeans/core/windows/services/NbDialog.java
- platform/core.windows/src/org/netbeans/core/windows/services/NbPresenter.java
- platform/core.windows/src/org/netbeans/core/windows/services/NodeOperationImpl.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/DialogDisplayerImplTest.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/NbDialogTest.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/NbPresenterTest.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/NotifyLaterTest.java
- platform/openide.util.ui/apichanges.xml
- platform/openide.util.ui/src/org/openide/util/Utilities.java
As described in #5987, `DialogDisplayer.notify` won't use the active window as the parent if it is a dialog that wasn't originally shown via `NbPresenter`. This causes issues in some cases due to [JDK-8306001](https://bugs.openjdk.org/browse/JDK-8306001) because the displayed dialog does not have the previously active modal dialog as its parent.
The solution here is to use the `Dialog` overload when creating the `NbPresenter` if the currently active window is a `Dialog` instead of falling back to the main window.
> #5987: Use the currently active dialog as the presenter parent

- java/maven.embedder/src/org/netbeans/modules/maven/embedder/MavenEmbedder.java
- java/maven/test/unit/src/org/netbeans/modules/maven/classpath/AbstractProjectClassPathImplTest.java
This reverts commit e2a14bf32a5bddabee71e0fc2e35f575f7d1aacc, targets delivery
fixes #6222 ArtifactResolutionExceptions when working with maven projects
regression reproducible in RC1, see issue
> Revert "Use resolve() method that actually throws exception."

- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/Bundle.properties
- enterprise/glassfish.common/src/org/netbeans/modules/glassfish/common/ServerDetails.java
- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/admin/AdminFactory.java
- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersion.java
- enterprise/glassfish.tooling/src/org/netbeans/modules/glassfish/tooling/server/config/ConfigBuilderProvider.java
- enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/admin/AdminFactoryTest.java
- enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/data/GlassFishVersionTest.java
- enterprise/glassfish.tooling/test/unit/src/org/netbeans/modules/glassfish/tooling/utils/EnumUtilsTest.java
Library Notes:
- Add support of the MicroProfile REST Client
- Add a new way to start GlassFish
- Add support for using @Inject to inject REST artifacts
- Bug fixes and updates of various components
- Bump the GlassFish version in some tests
- Verify successful execution of `ant -Dcluster.config=release commit-validation`
- Verify successful execution of unit tests for modules `glassfish.common`, `glassfish.javaee`, `glassfish.tooling` and `glassfish.eecommon`
- Successfully register GlassFish 7.0.6, create a web app and verify that it works.
[Release …
> Add support for GlassFish 7.0.6

- platform/options.api/src/org/netbeans/modules/options/export/OptionsExportModel.java
there was a bug in the boolean logic of checkIntegrity(), introduced in #6094
(while testing I noticed that the selected LAF is stored in `/config/Preferences/laf.properties`, so to import the LAF setting (other than font colors and custom LAF properties which are in `/config/LookAndFeel/`), one would have to select the `General` category which is importing several other settings too.)
fixes #6214
> Fix options import regression

- java/maven.junit/src/org/netbeans/modules/maven/junit/JUnitOutputListenerProvider.java
Fixes #6199
There was no support for JUnit5 in JUnitOutputListenerProvider in Maven Junit which resulted in the button to be always disabled.
> Enable 'Rerun failed tests' button for JUnit5

- php/php.editor/src/org/netbeans/modules/php/editor/actions/ImportDataCreator.java
- php/php.editor/src/org/netbeans/modules/php/editor/parser/PHPDocCommentParser.java
- php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/PHPDocCommentParserTest/ReturnTypeArrayShapes01.pass
- php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/PHPDocCommentParserTest/ReturnTypeArrayShapes02.pass
- php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/PHPDocCommentParserTest/ReturnTypeGenerics01.pass
- php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/PHPDocCommentParserTest/ReturnTypeGenerics02.pass
- php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/PHPDocCommentParserTest/ReturnTypeGenerics03.pass
- php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/PHPDocCommentParserTest/ReturnTypeGenerics04.pass
- php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/PHPDocCommentParserTest/ReturnTypeGenerics05.pass
- php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/PHPDocCommentParserTest/ReturnTypeObjectShapes01.pass
- php/php.editor/test/unit/data/goldenfiles/org/netbeans/modules/php/editor/parser/PHPDocCommentParserTest/ReturnTypeObjectShapes02.pass
- php/php.editor/test/unit/data/testfiles/actions/testGH6039/testGH6039_01.php
- php/php.editor/test/unit/data/testfiles/actions/testGH6039/testGH6039_01.php.importData
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/actions/ImportDataCreatorTest.java
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/parser/PHPDocCommentParserTest.java
- https://github.com/apache/netbeans/issues/6039
- Remove `<>` and `{}` from type name
- Ignore an empty type name to avoid getting all types
> Avoid getting all types with an empty type name #6039

- java/java.lsp.server/vscode/src/dbConfigurationProvider.ts
- java/java.lsp.server/vscode/src/extension.ts
To correctly set environment variables for database connection we need to register DBConfigurationProvider for both targets - java+ and java.
> Set DB environment for java+ as well as for java

- rust/rust.grammar/src/org/netbeans/modules/rust/grammar/ast/RustAST.java
It kept me bugging, why CSL support underlines the whole line on parser error even if the exact position of the error is given.
It's not very intuitive but:
https://github.com/apache/netbeans/blob/b79fd30b2e76ed070789745cabcf14bf5cf1e330/ide/csl.api/src/org/netbeans/modules/csl/spi/DefaultError.java#L67
So the constructor used here, defaults to line-error. I thought give @vieiro  a hand, and file this trivial PR.
> Rust: More precise parser error markings in the Editor

- enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/ejb/annotation/EnterpriseBeansImpl.java
- enterprise/j2ee.dd/src/org/netbeans/modules/j2ee/dd/impl/web/annotation/AnnotationHelpers.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/action/SendJMSGenerator.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/api/methodcontroller/EjbMethodController.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/jpa/dao/EjbFacadeVisualPanel2.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/jpa/dao/EjbFacadeWizardPanel2.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/mdb/MdbPropertiesPanelVisual.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/mdb/MessageDestinationUiSupport.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/session/SessionEJBWizardDescriptor.java
- enterprise/j2ee.ejbcore/src/org/netbeans/modules/j2ee/ejbcore/ejb/wizard/session/SessionEJBWizardPanel.java
- enterprise/j2ee.ejbverification/src/org/netbeans/modules/j2ee/ejbverification/rules/AsynchronousMethodInvocation.java
- enterprise/web.jsf/src/org/netbeans/modules/web/jsf/impl/metamodel/ObjectProviders.java
- java/j2ee.persistenceapi/src/org/netbeans/modules/j2ee/persistenceapi/metadata/orm/annotation/EntityMappingsImpl.java
The options shown when selecting New > Session Bean are based on the capabilities of the used enterprise project.
The check missed some Jakarta EE versions and so were disabled.
Analysis done by @asbachb
Closes: #4892
Closes: #4830
> Bugfix: Bring back singleton option when creating a new Session Bean and interfaceless EJBs

- ide/db.core/src/org/netbeans/modules/db/sql/loader/SQLCloneableEditor.java
- ide/db.core/src/org/netbeans/modules/db/sql/loader/SQLEditorSupport.java
The construction of the editor panel for SQL is a bit special to support both using it as SQL console and file editor and allow it to execute sql statements.
In normal editors multiview elements are initialized by the infrastructure and #initializeCloneableEditor is called by it to connect the DataNode and the editor. This was missing for the SQLEditor.
Closes: #6224
> Fix: Committing SQL files does not change blue color on the file tab in editor

- java/java.api.common/nbproject/project.xml
- java/java.api.common/src/org/netbeans/modules/java/api/common/singlesourcefile/LaunchProcess.java
- java/java.api.common/src/org/netbeans/modules/java/api/common/singlesourcefile/SingleJavaSourceRunActionProvider.java
- java/java.api.common/test/unit/src/org/netbeans/modules/java/api/common/singlesourcefile/JavaFileTest.java
- java/java.hints/src/org/netbeans/modules/java/hints/errors/EnablePreviewSingleSourceFile.java
- java/java.hints/src/org/netbeans/modules/java/hints/infrastructure/JavaErrorProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/singlesourcefile/CompilerOptionsQueryImpl.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/singlesourcefile/EnablePreviewSingleSourceFile.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/singlesourcefile/CompilerOptionsQueryImplTest.java
- java/java.lsp.server/vscode/src/extension.ts
- java/java.lsp.server/vscode/src/runConfiguration.ts
- java/java.source.base/src/org/netbeans/modules/java/source/parsing/Hacks.java
(Single) source file launcher support has multiple problems inside VS Code - especially settings that are inside NetBeans done through file attributes are not accessible. This patch attempts to use the Run Configuration tab/settings to provide options for launching the single file. The same options are also parsed for use in the editor.
---
If …
> Supporting source file launcher in VS Code extension

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/LspTemplateUI.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/NbCodeClientWrapper.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/ui/NotifyDescriptorAdapter.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/UtilsTest.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/LspTemplateUITest.java
- java/java.lsp.server/vscode/CHANGELOG.md
NBLS `New from Template` command implementation strips HTML from description of templates, but leaves whitespaces as they were in the html source, so potentially more (white)spaces than necessary, including tab/newline control characters. vscode now (from June's releaase 1.80.2) starts to display control characters in quickpick UI - which looks ugly, see #6278. 
This PR:
- removes all newlines
- coalesces whitespaces into a single space
- kills leading/trailing whitespaces
Should apply only to description of templates.
Please do consider to include this fix in NB(LS) 19 release, the New from Tempalate looks really ugly.
> #6278: discard newlines, collapse and trim whitespaces.

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
While working on https://github.com/enso-org/enso/pull/7054#issuecomment-1632751826 I got following exception:
```
java.lang.NullPointerException: Property must not be null: message
at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:29)
at org.eclipse.lsp4j.MessageParams.<init>(MessageParams.java:45)
at org.netbeans.modules.java.lsp.server.protocol.TextDocumentServiceImpl.lambda$codeAction$24(TextDocumentServiceImpl.java:1058)
```
This PR avoids the `NullPointerException` and also addresses the comment that asked for delivering the stack trace.
> Use ex.printStackTrace(StringWriter) to avoid no message NPE

- java/java.source.base/src/org/netbeans/api/java/source/TreeMaker.java
- java/javadoc/src/org/netbeans/modules/javadoc/hints/AddTagFix.java
- java/javadoc/src/org/netbeans/modules/javadoc/hints/RemoveTagFix.java
Fix formatting issue with Javadoc when using the add or remove param hint. Debugging shows some error in extracting the first sentence and body, then recreating the full body. Updated TreeMaker to allow the hint to pass in the existing full body whole.
For more context see users@ thread on the error at https://lists.apache.org/thread/wqq8jnxp2c2lxyf9wxk2sqqjhrz1lhhd
> Fix Javadoc formatting error when using add/remove param hint.

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/URITranslator.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
- java/java.lsp.server/vscode/src/extension.ts
Sources from jar files should be opened as read-only preserving their true locations. There is no need to create temporary copies of these sources being opened any more.
> LSP: Open sources from Jar files as read-only from their true locations.

- platform/core.windows/src/org/netbeans/core/windows/services/DialogDisplayerImpl.java
- platform/core.windows/src/org/netbeans/core/windows/services/NbDialog.java
- platform/core.windows/src/org/netbeans/core/windows/services/NbPresenter.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/NbDialogTest.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/NbPresenterTest.java
- platform/core.windows/test/unit/src/org/netbeans/core/windows/services/NotifyLaterTest.java
Attempt to fix issue #6290 in new DialogDisplayerImpl behaviour introduced in #5989 and #6216.
Possible alternative to reverting in #6291
> Fix issue (GH6290) in new DialogDisplayerImpl behaviour

- .github/workflows/main.yml
- enterprise/j2ee.sun.dd/test/unit/src/org/netbeans/modules/j2ee/sun/dd/api/DDProviderTest.java
Not all are compatible yet, but this should not stop us from running those who are on JDK 11.
followup on #6244
> Start running enterprise tests on JDK 11

- platform/openide.util/src/org/openide/util/RequestProcessor.java
- Use Deque/ArrayDeque instead of Stack, the Deque interface should be used in preference to the legacy Stack class, it will give better performance and it is already used in synchronized blocks so there is no need for the thread-safe Stack/Vector class.
- Increase default RequestProcessor throughput from 50 to 55.
Testing:
- Verify successful execution of unit tests for module `platform.openide.util`
- Verify successful execution of sigtests
- Verify successful execution of commit-validation
- Worked normally with various projects.
> Use Deque/ArrayDeque instead of Stack in RequestProcessor class

- java/java.editor.base/nbproject/project.xml
- java/java.editor.base/src/org/netbeans/modules/java/editor/base/semantic/UnusedDetector.java
- java/java.hints/src/org/netbeans/modules/java/hints/bugs/Unused.java
- java/junit.ui/nbproject/project.xml
- java/junit.ui/src/org/netbeans/modules/junit/ui/actions/TestClassInfoTask.java
- java/spi.java.hints/apichanges.xml
- java/spi.java.hints/nbproject/project.properties
- java/spi.java.hints/nbproject/project.xml
- java/spi.java.hints/src/org/netbeans/spi/java/hints/unused/UsedDetector.java
JUnit test methods should not be marked as unused in editor.
> Do not mark test methods as unused.

- java/gradle.java/src/org/netbeans/modules/gradle/java/newproject/SimpleApplicationProjectWizard.java
Gradle create new projects using Kotlin DSL by default from version 8.2.
That could be quite confusing. It would be nice to add a DSL Language selection option to the create project wizard. However this late in the release process, simply forcing Groovy may do it.
The change is trivial, might not need another RC even if included.
> Keep using Groovy DSL for Gradle

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBAddConnection.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBCommandProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBConnectionProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/NodeActionsProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/explorer/NodePropertiesProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/htmlui/WebView.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
It is not necessarry to validity of `command` string - the infrastructure does it automatically and invokes the correct implementation of `processCommand` method.
> redundant check for supported 'command' removed

- java/java.lsp.server/vscode/package.json
- java/java.lsp.server/vscode/src/extension.ts
Add sign in database toolbar was changed to include selection of 'Add Oracle Autonomous DB' wizard or original 'Add Database Connection' wizard. This will provide same functionality when no database is configured and database panel contains two buttons. This way it is possible to add 'Oracle Autonomous DB' when some database is configured and those buttons are not there anymore.
> Allow to select 'Add Database Connection' or 'Add Oracle Autonomous DB' from database view toolbar

- ide/db.metadata.model/src/org/netbeans/modules/db/metadata/model/jdbc/JDBCProcedure.java
If `returnValue` of `org.netbeans.modules.db.metadata.model.jdbc.JDBCProcedure` is `null`, `createProcedureInfo()` is invoked every time. When `returnValue` is not `null` result are properly cached and `createProcedureInfo()` are invoked only once. Use `parameters` instead of `returnValue` to find out if `createProcedureInfo()` was already invoked.
> use 'parameters' to find out if createProcedureInfo() was already invoked

- java/java.lsp.server/vscode/package-lock.json
moderate severity vulnerability fixed by upgrading semver module.
```
semver  7.0.0 - 7.5.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix`
node_modules/semver
1 moderate severity vulnerability
```
> update npm module semver (moderate severity vulnerability)

- .github/workflows/main.yml
- java/java.source.base/test/unit/src/org/netbeans/modules/java/source/NoJavacHelperTest.java
- java/libs.nbjavacapi/nbproject/project.properties
- java/libs.nbjavacapi/nbproject/project.xml
- java/libs.nbjavacapi/test/unit/src/org/netbeans/modules/nbjavac/api/NBJavacBrandingTest.java
- test min javac version requirement check
- test module description
Should make it less likely that version increments are overlooked during javac lib wrapper updates (e.g https://github.com/apache/netbeans/pull/6206#issuecomment-1640274517).
> Add nb-javac libwrapper tests.

- java/performance/hudson/netbeans.conf
- nb/ide.launcher/netbeans.conf
Java's zip implementation doesn't use mmap anymore ([JDK-8175192](https://bugs.openjdk.org/browse/JDK-8175192), [JDK-8142508](https://bugs.openjdk.org/browse/JDK-8142508)).
> Remove obsolete sun.zip.disableMemoryMapping JVM flag.

- webcommon/javascript2.editor/test/unit/data/testfiles/structure/classInAnonymousFunction.js
- webcommon/javascript2.editor/test/unit/data/testfiles/structure/classInAnonymousFunction.js.structure
- webcommon/javascript2.editor/test/unit/data/testfiles/structure/classInAnonymousFunction2.js
- webcommon/javascript2.editor/test/unit/data/testfiles/structure/classInAnonymousFunction2.js.structure
- webcommon/javascript2.editor/test/unit/src/org/netbeans/modules/javascript2/editor/JsStructureScannerTest.java
- webcommon/javascript2.model/src/org/netbeans/modules/javascript2/model/ModelVisitor.java
- webcommon/javascript2.model/test/unit/data/testfiles/model/classInAnonymousFunction.js
- webcommon/javascript2.model/test/unit/data/testfiles/model/classInAnonymousFunction.js.model
- webcommon/javascript2.model/test/unit/data/testfiles/model/classInAnonymousFunction2.js
- webcommon/javascript2.model/test/unit/data/testfiles/model/classInAnonymousFunction2.js.model
- webcommon/javascript2.model/test/unit/src/org/netbeans/modules/javascript2/model/ModelTest.java
Consider this construct:
```javascript
(function () {
class Directory {
constructor(displayName) {
this.displayName = displayName;
}
}
class ImageFile{
constructor(displayName){
this.displayName = displayName;
}
}
})();
```
Before this change this construct was not correctly parsed and the constructor was not cleanly recognised, leading to missing usage marks (i.e. the displayName above was marked as unused).
A different fallout of that problem is visible with this:
```javascript
(function () {
class Directory {
constructor(displayName) {
this.displayName = displayName;
}
}
class ImageFile{
constructor(displayName){
this.displayName = displayName;
}
}
function getJsonData(folderURL) {
const body = folderURL;
}
})();
```
Fixed Problems:
- `constructor` from `ImageFile` is shown as a …
> JS: Fix handling of classes declared in anonymous functions

- java/java.completion/src/org/netbeans/modules/java/completion/JavaTooltipTask.java
Testsetup:
```java
public class TestParamResolution {
List.of("Hallo", "World");
testMethod("Hello", "World", "Test");
testMethod(1, "Hello", "World");
}
public static <S extends String & Comparable<String> & Serializable> void testMethod(S genericParam, String dummy1_1, String dummy1_2) {}
public static <S extends Integer> void testMethod(S genericParam, String dummy2_1, String dummy2_2) {}
public static <T extends Integer & Externalizable> void testArgumentTypeVariableParameter(T genericParam, List<? super String> x) {
testMethod(genericParam, "x", "dfd");
}
}
```
Inside main the problem can be demonstrated with all demonstrated calls. When the caret is placed in the first argument (before first comma), the parameter popup (CTRL+P) can be opened …
> Fix: Java completion parameter tooltip is not shown if previous parameter is TypeVariable

- extide/gradle/apichanges.xml
- extide/gradle/src/org/netbeans/modules/gradle/GradleJavaCompatProblemsProvider.java
- extide/gradle/src/org/netbeans/modules/gradle/spi/newproject/TemplateOperation.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/newproject/SimpleApplicationProjectWizard.java
So that we don't get a release candidate wrapper when running the new Gradle project wizard, configure it to use version `latest`.
This highlights an issue that the wrapper is actually created by the init task.  The wrapper checkbox currently has no effect except for running the wrapper task again.
Second commit fixes a typo in the project problems dialog.
Not sure if this is a better fallback solution for NB19 or not?
> Configure latest released wrapper in new Gradle project

- ide/docker.api/src/org/netbeans/modules/docker/api/DockerSupport.java
Enable to add docker instance via socket on mac with apple silicon.
#6326
> Fix: Enable to add docker instance via socket on mac with apple silicon

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBCommandProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBConnectionProvider.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TestClassGenerator.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/ChangeMethodParametersRefactoring.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/MoveRefactoring.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/PullUpRefactoring.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/refactoring/PushDownRefactoring.java
cleanup of implenetation of CodeActionsProvider.getCommands() method. Use `Collections.singleton()` for single command poviders.
> LSP: cleanup of CodeActionsProvider.getCommands()

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/Server.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
Workspace folder(s) should be scanned for projects the server initialization.
In case the workspace folder represents a project, it is immediately opened (together with its sub-projects), as it was done while searching for test methods.
In case the workspace folder does not represent a project, the folder is scanned to find all projects contained in its sub-folders.
> LSP: Scan for projects on server init.

- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-3.2-license.txt
- platform/libs.flatlaf/manifest.mf
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLaf.properties
This is a simple upgrade of the FlatLaf library from version 3.1 to 3.2, modeled after the previous version bump at https://github.com/apache/netbeans/pull/5818 .
Changes: https://github.com/JFormDesigner/FlatLaf/releases/tag/3.2
The new Windows ARM support DLL was added the list of native libraries automatically extracted from the JAR.
(I needed the update in my own NetBeans build, so offered @DevCharly to prepare the version bump PR this time.)
> Update FlatLaf from 3.1 to 3.2

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/Utils.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/UtilsTest.java
I noted an error in `html2plain` implementation: a text like
```
"<html>The Java version: 19, that is selected for the project is not supported <p>Possible solutions:<ul>List content </ul>
```
was stripped so that the text between `p` tag and the immediately following tag was removed, so the text became:
```
The Java version: 19, that is selected for the project is not supported List content
```
> Fix P + BR tag handling, LI is replaced by "* "

- extide/gradle/src/org/netbeans/modules/gradle/loaders/GradleProjectLoaderImpl.java
- extide/gradle/src/org/netbeans/modules/gradle/loaders/LegacyProjectLoader.java
- extide/gradle/test/unit/data/projects/priming/broken1/build.gradle
- extide/gradle/test/unit/data/projects/priming/broken1/gradle.properties
- extide/gradle/test/unit/data/projects/priming/broken1/settings.gradle
- extide/gradle/test/unit/src/org/netbeans/modules/gradle/NbGradleProjectImpl2Test.java
- extide/gradle/test/unit/src/org/netbeans/modules/gradle/NbGradleProjectImplTest.java
- extide/gradle/test/unit/src/org/netbeans/modules/projectapi/nb/NbProjectManagerAccessor.java
- ide/projectui/src/org/netbeans/modules/project/ui/problems/BrokenReferencesCustomizer.java
During investigation of #6368, I found out that if a **broken project** primes - and the loading fails, the `NbGradleProject` still reports `FALLBACK` as the quality - which leaves the prime action enabled, but also may confuse the API clients.
It's because `LegacyProjectLoader` loads project with `SIMPLE` quality (some dependencies are not satisfied), but it's then overwritten by `FallbackProjectLoader`. This PR returns the highest quality, but still stops as soon as the desired quality is achieved.
> Return the highest quality from all the loaders.

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/URITranslator.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/UtilsTest.java
The original commit 3fd09f3 that causes this bug changed the processing since although NBLS reported nbjrt or jar URIs in form `nbjrt:file:/space/java/17/!/modules/java.base/?CLASS#java.util.Collections`, the LSP client seems to mangle the scheme and ! by urlencoding it.  The clients sends back URIs like `nbjrt:file%3A/space/java/17/%21/modules/java.base/?CLASS#java.util.Collections`.
The original code in 3fd09f3  used URLDecoder, which demangles those parts, but also decodes other potentially URLeconded characters, such as spaces in path. 
This PR handles the specific sitiuation when there are multiple (nested) schemes like `jar:file:` or `nbjrt:file:` -- these always precede the first slash. In both cases, `!` serves as a delimiter for the inner scheme's part, followed by `/`. So only …
> #6377: workaround vscode jar/nbjrt URI mangle

- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/WinFlatEditorTabCellRenderer.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/WinFlatEditorTabDisplayerUI.java
- platform/o.n.swing.tabcontrol/src/org/netbeans/swing/tabcontrol/plaf/WinFlatViewTabDisplayerUI.java
This PR copies the previously merged [text alignment improvements](https://github.com/apache/netbeans/pull/4349) in FlatLAF window system tabs back to the older Windows LAF.
This completes the tab component saga originally started in https://github.com/apache/netbeans/pull/3115 ; this PR corresponds to the last commit of the latter.
At some point we might want to move the FlatLAF tab control implementations into o.n.swing.tabcontrol so the code can be shared, but they have some dependencies on FlatLAF-specific UI scaling utilities and so on. But the Windows LAF will probably be obsoleted by FlatLAF soon anyway.
> Copy FlatLAF label positioning improvements into the Windows LAF

- platform/openide.dialogs/src/org/openide/WizardDescriptor.java
It turned out that the little black line was the caret of a focused, 0-width JTextPane. It was mostly only visible during "loading" panels when no other component requested focus.
-> make the `messagepane` not focusable by default
The existing logic is enabling focus automatically if the text String is not empty.
https://github.com/apache/netbeans/blob/eaf1858c81b180c04a795dca0e8abf6b8080082c/platform/openide.dialogs/src/org/openide/WizardDescriptor.java#L2825
> Remove little black line from new-project wizard.

- php/php.project/src/org/netbeans/modules/php/project/ui/customizer/CustomizerTesting.java
> Fixed gap between checkboxes in php project testing settings

- php/php.editor/src/org/netbeans/modules/php/editor/parser/PHPDocCommentParser.java
- php/php.editor/test/unit/data/testfiles/actions/testGH6247/testGH6247_01.php
- php/php.editor/test/unit/data/testfiles/actions/testGH6247/testGH6247_01.php.importData
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/actions/ImportDataCreatorTest.java
- https://github.com/apache/netbeans/issues/6247
- Ignore `static` only when a PHPDoc tag is `@method`
- Add a unit test
Before:
After:
> Prevent getting an incorrect type if a return type is `static` with PHPDoc tag(`@return`) #6247

- php/php.editor/src/org/netbeans/modules/php/editor/model/impl/VariousUtils.java
- php/php.editor/test/unit/data/testfiles/completion/lib/gh6359/gh6359.php
- php/php.editor/test/unit/data/testfiles/completion/lib/gh6359/gh6359.php.testGH6359_01.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/gh6359/gh6359.php.testGH6359_02.completion
- php/php.editor/test/unit/data/testfiles/completion/lib/gh6359/gh6359.php.testGH6359_03.completion
- php/php.editor/test/unit/src/org/netbeans/modules/php/editor/completion/PHPCodeCompletionGH6359Test.java
- https://github.com/apache/netbeans/issues/6359
- `/** @var Type $field */` is recognized as not `PHPDocBlock` but `PHPVarComment`, so, check it
```php
// example
class X {
public function testX(): void {}
}
class Y {
public function testY(): void {}
}
class GH6359 {
/** @var X $testX */
protected $testX;
/** @var X|Y $testXorY */
protected $testXorY;
/** @var X&Y $testXandY */
protected $testXandY;
public function test(): void {
$this->testX->testX();
$this->testXorY->testX();
$this->testXandY->testX();
}
}
```
> Fix code completion for fields with single line var doc #6359

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
- java/java.lsp.server/test/unit/src/org/netbeans/modules/java/lsp/server/protocol/ServerTest.java
Modified to prevent errors written to log while opening workspace symbols (classes) that come from jar files.
> LSP: Prevent errors written to log on workspace symbol open.

- cpplite/cpplite.editor/nbproject/project.properties
- cpplite/cpplite.editor/src/org/netbeans/modules/cpplite/editor/lsp/LanguageServerImpl.java
There are currently two problems in CPPLite:
**STDERR is not drained and can cause LSP to block**
The language server ccls and clangd both output debugging information
to STDERR. This works while the output buffer of the language server
is not yet filled and fails when the buffer is full.
Closes: #6297
> Stabilize CPPLite: Discard STDERR

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/db/DBConnectionProvider.java
- java/java.lsp.server/vscode/src/dbConfigurationProvider.ts
- java/java.lsp.server/vscode/src/extension.ts
This PR uses temporaty file to pass DB connection details. The file is created in subdirectory of OS temporaty directory and has only minimal (read) permission for user running NBLS.Other system users does not have even read permission (this is similar to ssh private key files.  If the setting of correct permissions fails, the file the temporary file is deleted immediatelly.  The temporaty file is deleted as soon as debugging session ends. If the NBLS and VScode are hard killed and the temporary file remains on filesystem, it is deleted on the subsequent startup of NBLS.
> Pass DB connection details using file instead of env. variables

- enterprise/micronaut/src/org/netbeans/modules/micronaut/db/MicronautEntity.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/db/Utils.java
Using `io.micronaut.data.annotation.MappedProperty` instead of `jakarta.persistence.Column` annotations when generating Micronaut entity classes from database.
> Micronaut: Avoid using jakarta.persistence when generating entity classes

- java/java.lsp.server/build.xml
Top level LICENSE file in apache-netbeans-java-xx.x.xxx.vsix is missing some 3rd party library licenses namely for enterprise, cpplite, extra, groovy and webcommon clusters.
To fix it 'allmodules' should include all clusters not just 'java' and its dependencies, since apache-netbeans-java-xx.x.xxx.vsix contains enterprise, cpplite, extra, groovy and webcommon clusters.
> Fix NBLS 3rd party licenses

- rust/rust.grammar/src/org/netbeans/modules/rust/grammar/RustLanguageLexer.java
- rust/rust.grammar/test/unit/src/org/netbeans/modules/rust/grammar/antlr4/RustLexerTest.java
- rust/rust.grammar/test/unit/src/org/netbeans/modules/rust/grammar/antlr4/RustParserTest.java
- rust/rust.grammar/test/unit/src/org/netbeans/modules/rust/grammar/ast/RustASTTest.java
Antlr ErrorListener was throwing exceptions interferring with the EDT.
> RustLanguageLexer: do not throw exceptions.

- java/java.source.base/src/org/netbeans/modules/java/source/indexing/APTUtils.java
If an annotation processor initialization crashes, just log the error and continue, rather than crash the whole processing.
> Handle errors in annotation processor initialization

- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/WorkspaceServiceImpl.java
The problem was with `ParserManager.parseWhenScanFinished("text/x-java", new UserTask() {...` called before the first `JavacParser` was created by `java.source` infrastructure. Since `JavacParser` cannot be created without supplying a `ClasspathInfo`, exception was thrown and the given `UserTask` was not executed. Fixed by supplying the `ClasspathInfo` based on the opened projects.
> LSP: Fixed problem with workspace/symbols called before first JavacCompiler created.

- enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/layer.xml
Maven support warns before using lifecycle participants as they are not going to be executed during project read - it does not warn abou the known ones (as they do not change project model so much).
Micronaut repackaged its lifecycle participant in 4.0 release, so this PR just extends the exclusion list.
> Micronaut's lifecycle participant changed FQN in Micronaut 4.x

- enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/layer.xml
- enterprise/micronaut/test/unit/data/maven/micronaut4/simple/.gitignore
- enterprise/micronaut/test/unit/data/maven/micronaut4/simple/README.md
- enterprise/micronaut/test/unit/data/maven/micronaut4/simple/aot-jar.properties
- enterprise/micronaut/test/unit/data/maven/micronaut4/simple/micronaut-cli.yml
- enterprise/micronaut/test/unit/data/maven/micronaut4/simple/pom.xml
- enterprise/micronaut/test/unit/data/maven/micronaut4/simple/src/main/java/com/example/Application.java
- enterprise/micronaut/test/unit/data/maven/micronaut4/simple/src/main/resources/application.properties
- enterprise/micronaut/test/unit/data/maven/micronaut4/simple/src/main/resources/logback.xml
- enterprise/micronaut/test/unit/data/maven/micronaut4/simple/src/test/java/com/example/DemoTestForSvataTest.java
- enterprise/micronaut/test/unit/src/org/netbeans/modules/micronaut/maven/MicronautPackagingArtifactImplTest.java
Micronaut has changed its build plugin coordinates between version 3.x and 4.x. Formerly, its groupId was `io.micronaut.build` while now it is `io.micronaut.maven`.
The PR just duplicates the project service registrations, so both MN3 and MN4 projects are recognized. I've added some tests to check that the continuous mode configuration is / is not present for simple, MN3 and MN4 projects.
> Micronaut 4 build plugin recognized.

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
- extide/gradle/test/unit/src/org/netbeans/modules/gradle/api/GradleBaseProjectTest.java
- java/gradle.java/src/org/netbeans/modules/gradle/java/queries/GradleDependenciesImplementation.java
Gradle NB tooling now reports BOMs as regular dependencies and its contents as dependencies. This causes dependency graph explosion as BOMs are used in many intermediate dependencies and the project API explodes the tree eagerly. 
For proper function, a change in Dependency API is probably needed, so the client is able to identify BOMs (some flag on output), or exclude them entirely (some additional filter at input) - and to allow lazy creation of dependency tree levels, so that client can avoid the explosion which now happens in project dependency core impl. 
For now, it is more safe not to return children of BOMs; it will not affect normal dependencies as BOMs just help to select version of a library.
> Workaround: Avoid reporting BOMs among dependencies to prevent dependency graphs explosion

- .github/workflows/main.yml
java-setup action doesn't work anymore since JDK 21 has just been released and it is trying to download an ea release -> lets switch to the ga release.
going to merge as soon its green.
> Switch CI from JDK 21-ea to 21-ga.

- java/java.lsp.server/vscode/src/nbcode.ts
When the extension resides in a directory with path in space, NBLS does not start properly. It does in a basic configuration, but when another extension contributes an additional module, the passed parameter, `-J-Dnetbeans.extra.dirs=` will not be passed properly.
During testing, the arguments passed to the `nbcode` launcher are (logged from `nbcode.ts`)
```
[Extension Host] Launching NBLS with arguments: --userdir,/space/tmp/test mezera 8/user/User/workspaceStorage/bb81367d8526610b14dd61e6f4fb379f/asf.apache-netbeans-java/userdir,--jdkhome,/space/java/current,-J-Dnetbeans.extra.dirs="/space/tmp/test mezera 8/ext/oracle-labs-graalvm.micronaut-tools-0.6.0-208/nbcode/graalvmextra",--modules,--list,-J-XX:PerfMaxStringConstLength=10240,--laf,com.formdev.flatlaf.FlatDarkLaf,--direct-disable,org …
```
> Avoid double quoting extra path

- nb/ide.launcher/netbeans.conf
The `quartz` renderer doesn't exist anymore since java 7, on java 19+ the new `metal` renderer is used for MacOS systems.
closes #6316 (see comment for details)
> Remove obsolete UseQuartz JVM flag.

- nbbuild/jms-config/tools.flags
When NB is run on JDK 21, building/running NB modules fails with:
```
Error starting modern compiler
at org.apache.tools.ant.taskdefs.compilers.Javac13.execute(Javac13.java:64)
at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1388)
at org.netbeans.nbbuild.CustomJavac.compile(CustomJavac.java:131)
...
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.apache.tools.ant.taskdefs.compilers.Javac13.execute(Javac13.java:57)
... 21 more
Caused by: java.lang.IllegalAccessError: class com.sun.tools.javac.main.Main (in unnamed module @0x50ba363b) cannot access class jdk.internal.opt.CommandLine$UnmatchedQuote (in …
```
> Fixes "error starting modern compiler" issue on JDK 21.

- platform/libs.flatlaf/external/binaries-list
- platform/libs.flatlaf/external/flatlaf-3.2.1-license.txt
- platform/libs.flatlaf/manifest.mf
- platform/libs.flatlaf/nbproject/project.properties
- platform/libs.flatlaf/nbproject/project.xml
Changes: https://github.com/JFormDesigner/FlatLaf/releases/tag/3.2.1
Fixes a memory leak in multi-resolution image support and some minor bugs.
The NetBeans IDE is not affected by the memory leak, because the affected class is not used.
But NB platform apps may use it.
> Update FlatLaf from 3.2 to 3.2.1

- enterprise/payara.common/src/org/netbeans/modules/payara/common/actions/Bundle.properties
- enterprise/payara.common/src/org/netbeans/modules/payara/common/actions/OpenDomainDirectoryAction.java
- enterprise/payara.common/src/org/netbeans/modules/payara/common/actions/OpenServerHomeDirectoryAction.java
- enterprise/payara.common/src/org/netbeans/modules/payara/common/nodes/Hk2InstanceNode.java
This pull request introduces two new features to enhance the Payara Server tool's usability within the Apache NetBeans IDE. It introduces the `OpenDomainDirectory` and `OpenServerHomeDirectory` actions, which allow users to quickly open the Payara Server's domain directory and home directory respectively, directly from the Apache NetBeans IDE.
> Open the Payara Server's home and domain directory in Explorer

- enterprise/cloud.oracle/src/org/netbeans/modules/cloud/oracle/actions/AddADBAction.java
FIxed the hint should be displayed according to the current step:
1.  Select Compartment when selecting a compartment
2. Select Database when selecting a database
When a compartment without a database is selected, the hint is 'No database available in this Compartment'
> Quickpick title for database fixed

- ide/libs.flexmark/external/binaries-list
- ide/libs.flexmark/external/flexmark-0.62.2-license.txt
- ide/libs.flexmark/nbproject/project.properties
- ide/libs.flexmark/nbproject/project.xml
- ide/markdown/nbproject/project.xml
- ide/markdown/src/org/netbeans/modules/markdown/MarkdownViewerElement.java
- ide/markdown/src/org/netbeans/modules/markdown/ui/preview/MarkdownEditorKit.java
- ide/markdown/src/org/netbeans/modules/markdown/ui/preview/views/CheckboxView.java
- ide/markdown/src/org/netbeans/modules/markdown/ui/preview/views/MarkdownViewFactory.java
Added support for Checkbox on Markdown Preview and some other changes that i will explain.
Added a package **ui.preview** and  **and ui.preview.views**
- [MarkdownEditorKit.java](https://github.com/moacirrf/netbeans/blob/5836eb61945c543cd8e7d8c443e7109af7b9c3cf/ide/markdown/src/org/netbeans/modules/markdown/ui/preview/MarkdownEditorKit.java) : Is reponsible to supply a custom ViewFactory and this class has a very interesting method called getStyleSheet that is important to deal with themes on JEditorPane, so i believe that was better extract to a new class to avoid use of Anonymous class.
- [MarkdownViewFactory](https://github.com/moacirrf/netbeans/blob/5836eb61945c543cd8e7d8c443e7109af7b9c3cf/ide/markdown/src/org/netbeans/modules/markdown/ui/preview/views/MarkdownViewFactory.java) : Is …
> Checkbox support on Markdown preview

- platform/o.n.bootstrap/src/org/netbeans/NbClipboard.java
It was reported, that clipboard copy/paste actions sometimes fail in
NetBeans (#3962). It was reported, that even with logging enabled no
exception was visible.
Clipboard#setContents and Clipboard#getContents are both documentent
that they can throw IllegalStateException when the clipboard can't be
accessed.
There are two changes here:
1. If accessing the clipboard fails in `GetContents#run`, the exception will not
be swallowed, but reported on level `FINE` (just as the rest of the logging)
2. Access to the clipboard is retried, so that other programms blocking the
clipboard don't interrupt all NetBeans copy operations.
> Retry fetching clipboard contents when it initially fails

- ide/extbrowser/src/org/netbeans/modules/extbrowser/ExtBrowserImpl.java
- ide/extbrowser/src/org/netbeans/modules/extbrowser/NbDdeBrowserImpl.java
- ide/extbrowser/src/org/netbeans/modules/extbrowser/SystemDefaultBrowser.java
I originally thought I could enable the `JdkBrowserImpl` by default due to #6455, but this could potentially cause feature regressions since the impl is fairly limited.
However, looking through the code I am wondering if any of the "DDE" features still work on windows for example.
Didn't want to discard the cleanup, so I opened this PR.
> Small code cleanup in extbrowser module.

- java/java.completion/src/org/netbeans/modules/java/completion/JavaTooltipTask.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
Parameter tooltips (signature help in LSP) should be displayed also for annotations (in addition to method/constructor invocations).
> Disaplay parameter tooltips for annotations.

- ide/editor.lib2/nbproject/project.xml
- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/DocumentViewOp.java
- ide/editor/nbproject/project.xml
- ide/editor/src/org/netbeans/modules/editor/MainMenuAction.java
- ide/editor/src/org/netbeans/modules/editor/resources/NetBeans-keybindings.xml
- platform/core.windows/nbproject/project.xml
- platform/core.windows/src/org/netbeans/core/windows/ShortcutAndMenuKeyEventProcessor.java
- platform/openide.util.ui/apichanges.xml
- platform/openide.util.ui/src/org/openide/util/Utilities.java
- platform/options.keymap/src/org/netbeans/modules/options/keymap/Bundle.properties
- platform/options.keymap/src/org/netbeans/modules/options/keymap/SpecialkeyPanel.form
- platform/options.keymap/src/org/netbeans/modules/options/keymap/SpecialkeyPanel.java
This PR adds support for binding the back and forward buttons on a mouse to the back and forward code navigation actions, as requested in #5728 (and https://bz.apache.org/netbeans/show_bug.cgi?id=70961 )
This PR also allows binding extended mouse buttons, with or without modifiers, to any action in the keymap editor.
Both mouse buttons 4 and 6 are bound to back, and 5 and 7 to forwards, due to platform differences.  Triggering a dev build so we can get some testing.
Yes, treating mouse buttons as keycodes might seem slightly odd, but as we're already doing that for the mouse wheel editor zoom actions, which seems even odder ...
EDIT : screenshot of the updated special key panel, accessible from the dropdown when editing shortcuts
> Use extended mouse buttons for back / forward actions (GH5728)

- java/maven.hints/manifest.mf
- java/maven.hints/nbproject/project.properties
- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/UpdateDependencyHint.java
- java/maven.hints/src/org/netbeans/modules/maven/hints/pom/UseReleaseOptionHint.java
- java/maven.hints/test/unit/src/org/netbeans/modules/maven/hints/pom/StatusProviderTest.java
- java/maven.hints/test/unit/src/org/netbeans/modules/maven/hints/pom/UseReleaseOptionHintTest.java
- default plugins can omit the group ID, the hint should still check their versions
- made hint aware of the reporting plugin section (thanks @matthiasblaesing for noticing this)
- moved module to JDK 11 since it already has JDK 11 dependencies
example:
> UpdateDependencyHint should work on plugins with default maven group id

- platform/autoupdate.services/src/org/netbeans/modules/autoupdate/services/UpdateUnitFactory.java
With d1300be50b8864eb605cee456c4b123d768e0eca the netbeans module system was enhanced to enable modules to be filtered by architecture. Missing from that commit was adjustment to the autoupdate system, which also needs to consider the architecture when providing packages for selection.
Closes: #6460
> Autoupdate system must check org.openide.modules.arch as org.openide.modules.os is already handled

- .github/workflows/native-binary-build-lib.profiler.yml
- profiler/lib.profiler/native/scripts/buildnative-mac.sh
Work in progress for now - feedback welcome.
Update the GitHub actions workflow for profiler binaries to generate a source bundle in an initial source job, then pass this as the sources for the various native builds.  This could form the basis of releasing these native binaries via dist.a.o for consumption in the main IDE build.
This incorporates the commit from #6494 with some further adaptation as the mac script expects existing binaries to be in place.
The various placeholder files in the source bundle are an annoyance, but the scripts fail if the destination directories don't exist, and GitHub artifact upload ignores empty directories.
> Update profiler workflow for possible release process

- profiler/lib.profiler/native/scripts/buildnative-mac.sh
closes 4524
The profiler is not working on the Apple Silicon platform, see Issue 4524.
These changes discard old contents of the library for Mac (ppc, i386) because these can't be any longer updated (see also remarks in original file).
Instead this build script builds a universal library for x86_64 and arm64. My tests with NB19 on Apple Silicon where successful.
---
Please make sure (eg. `git log`) that all commits have a valid name and email address for you …
> Added arch arm64 to profiler library

- .github/workflows/main.yml
- .github/workflows/native-binary-build-lib.profiler.yml
after merging the macos job into the cv job and adding a windows config, the cv job would produce the following runs:
```
linux   JDK [11, 21]
windows JDK [11]  <-- new
macos   JDK [11]
```
- improves windows coverage and removes a job
- removes JDK 17 from the matrix since if it works on 11 and 21, it likely will also work on 17
other updates:
- add retry wrapper for debugger.jpda.truffle tests again
- bumped checkout action to v4 and download/upload actions to v3
- renamed a few jobs in the profiler yaml to align with the main yaml
- use cache/restore action for read only cache access in platform job
> Rearrange commit validation job.

- platform/o.n.bootstrap/src/org/netbeans/ProxyClassLoader.java
- platform/o.n.bootstrap/src/org/netbeans/ProxyClassPackages.java
For ProxyClassLoader class:
- Use ConcurrentMap for `packages` map and remove some synchronized blocks
- Use ConcurrentHashMap.newKeySet() instead of Collections.synchronizedSet for `ARBITRARY_LOAD_WARNINGS` set
- Remove unused variables
For ProxyClassPackages class:
- Use ConcurrentMap for `PACKAGE_COVERAGE` map and remove the synchronized methods for get and remove operations
- Use synchronized on the `PACKAGE_COVERAGE` map for the add operation. It needs to be linearizable.
Testing:
- Verify successful execution of unit tests for module `platform.o.n.bootstrap`
- Verify successful execution of sigtests
- Verify successful execution of commit-validation
- Worked normally with various …
> Use ConcurrentMap/ConcurrentHashMap.newKeySet instead of Map/Collections.synchronizedSet

- .github/workflows/main.yml
- enterprise/micronaut/nbproject/project.xml
- enterprise/micronaut/src/org/netbeans/modules/micronaut/hints/AddArgForRouteVar.java
- enterprise/micronaut/src/org/netbeans/modules/micronaut/resources/layer.xml
- java/java.hints.legacy.spi/nbproject/project.properties
- java/java.hints.legacy.spi/nbproject/project.xml
- java/java.hints/src/org/netbeans/modules/java/hints/infrastructure/CreatorBasedLazyFixList.java
- java/java.hints/src/org/netbeans/modules/java/hints/infrastructure/ErrorHintsProvider.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/infrastructure/CreatorBasedLazyFixListTest.java
- java/java.hints/test/unit/src/org/netbeans/modules/java/hints/infrastructure/LazyHintComputationTest.java
- java/java.lsp.server/src/org/netbeans/modules/java/lsp/server/protocol/TextDocumentServiceImpl.java
Micronaut reports error if a path variable is declared the URL path and the corresponding parameter is missing in a method signature. The quick-fix adds the missing parameter.
```
@Get("/path/{variable}/")
public String handle(String name_not_equal_to_variable) {
...
}
```
> Micronaut: Add missing path variable parameter fix.

- java/java.lsp.server/vscode/package-lock.json
moderate severity vulnerability fixed by upgrading debug module.
```
debug  3.2.0 - 3.2.6
Severity: moderate
Regular Expression Denial of Service in debug - https://github.com/advisories/GHSA-gxpj-cx7g-858c
fix available via `npm audit fix`
node_modules/https-proxy-agent/node_modules/debug
1 moderate severity vulnerability
```
> update npm module debug (moderate severity vulnerability)

- ide/bcpg/external/bcpg-jdk18on-1.76-license.txt
- ide/bcpg/external/binaries-list
- ide/bcpg/nbproject/project.properties
- ide/bcpg/nbproject/project.xml
- ide/bcpkix/external/bcpkix-jdk18on-1.76-license.txt
- ide/bcpkix/external/binaries-list
- ide/bcpkix/nbproject/project.properties
- ide/bcpkix/nbproject/project.xml
- ide/bcprov/external/bcprov-jdk18on-1.76-license.txt
- ide/bcprov/external/binaries-list
- ide/bcprov/nbproject/project.properties
- ide/bcprov/nbproject/project.xml
- ide/bcutil/external/bcutil-jdk18on-1.76-license.txt
- ide/bcutil/external/binaries-list
- ide/bcutil/nbproject/project.properties
- ide/bcutil/nbproject/project.xml
- switches from `jdk15on` to `jdk18on` (which is for JDK 8+, see [page](https://www.bouncycastle.org/latest_releases.html))
- updates from 1.70 to 1.76
we might need this update for #6500, lets see if everything is green
> Update bouncycastle to jdk18on-1.76.

- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/maven-actions-override.xml
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/micronaut-actions-override.xml
- java/java.lsp.server/nbcode/integration/src/org/netbeans/modules/nbcode/integration/spring-actions-override.xml
- java/maven/src/org/netbeans/modules/maven/execute/ReactorChecker.java
Unlike NB IDE, vscode has a different workflow. The NBLS extension provides Projects view with Compile-Run actions that should build dependent projects before the main work. 
The `build` action can go with `<reactor>also-make</reactor>` but Run action may not be available on the root project, so we need to `<preAction>build-with-dependencies</preAction>`.
For the case that action is executed on the reactor root itself, I've adjusted the `ReactorChecker` - it will clear preAction for reactor root.
> Build with dependencies before main action

- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafOptionsPanel.java
- platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLafPrefs.java
- platform/o.n.swing.plaf/src/org/netbeans/swing/plaf/Startup.java
Hi! This enable window decoration option for system that not support Native Window Decorations (Linux). This can be enable in Tools > Options > Appearance > FlatLaf > Window decorations.
See: https://www.formdev.com/flatlaf/window-decorations/#enable_disable_linux
> FlatLaf: Enable Window decoration option for Linux

- javafx/javafx2.kit/src/org/netbeans/modules/javafx2/kit/JavaFXWizardIterator.java
- javafx/maven.htmlui/src/org/netbeans/modules/maven/htmlui/DukeScriptWizard.java
- Its now closer to other frontend templates, like JavaFX, and has a more specific name
- Remove the "(Gluon)" postfix from the JavaFX templates since they don't seem to use anything from gluon
> Update JavaFX wizard names and move DukeScript wizard to a better position.

- php/languages.neon/src/org/netbeans/modules/languages/neon/processors/MethodCompletionProviderProcessor.java
The version for `MethodCompletionProviderProcessor` is automatically set in its super class `LayerGeneratingProcessor` https://github.com/apache/netbeans/pull/5843#issuecomment-1736554656.
~~`TreeShimsCopier` can simply set it to latest since it is only used internally.~~ resolved via #6495
this resolves warnings like:
```
warning: Supported source version 'RELEASE_7' from annotation processor
'o.n.m.l.n.p.MethodCompletionProviderProcessor' less than -source '8'.
```
or:
```
warning: Supported source version 'RELEASE_8' from annotation processor 
org.netbeans.modules.java.source.TreeShimsCopier' less than -source '11'
```
> AnnotationProcessors shouldn't set the SourceVersion unless required

- nbbuild/external/binaries-list
- nbbuild/external/codesnippet-doclet-1.0-license.txt
- nbbuild/javadoctools/template.xml
Update the codesnippet as jenkins javadoc use jdk 21 for latest javadoc build and fail to process a complete javadoc.
Build still work with jdk11.
Nightlies contains a too small zip.
> upgrade codesnippet-doclet

- ide/libs.git/src/org/netbeans/libs/git/jgit/Utils.java
closes #3719
depends on #6500 ~(this temporarily includes the linked PR for testing purposes, see last commit)~
test:
```
git config --global init.defaultBranch yoda
```
create new project or select folder, `team -> git -> init repo`, commit something and check branch name
> Read initial git branch name from user config.

- ide/api.lsp/apichanges.xml
as api doc build work again it show a bad link on api.lsp changes.
> fix link in apichanges for api.lsp

- ide/editor.actions/src/org/netbeans/modules/editor/actions/ShowInlineHintsAction.java
- ide/editor.lib2/src/org/netbeans/modules/editor/lib2/view/DocumentViewOp.java
- ide/editor/src/org/netbeans/modules/editor/resources/NetBeans-keybindings.xml
- java/java.editor/src/org/netbeans/modules/java/editor/options/Bundle.properties
- java/java.editor/src/org/netbeans/modules/java/editor/options/InlineHintsPanel.form
- java/java.editor/src/org/netbeans/modules/java/editor/options/InlineHintsPanel.java
- java/java.editor/src/org/netbeans/modules/java/editor/options/InlineHintsSettings.java
- inline hints options can now toggle the global on/off state too
- fixed issue when user enabled inline hints but nothing happened since all individual options were disabled
- added keybinding for `View -> Show Inline hints` (`ALT-I`)
- disabled by default as discussed previously
> Improve inline-hints settings, add keybinding, disable by default.

- enterprise/web.jsfapi/src/org/netbeans/modules/web/jsfapi/api/JsfVersion.java
- enterprise/web.jsfapi/test/unit/src/org/netbeans/modules/web/jsfapi/api/JsfVersionTest.java
Display `Faces VERSION` instead of `JSF VERSION` when version is at least 4.0
The name was adjusted in Jakarta Faces Specification 4.0
see #6492
> Display `Faces VERSION` instead of `JSF VERSION` 

- ide/git/src/org/netbeans/modules/git/GitModuleConfig.java
enables #4306 by default
discussed on the [dev list](https://lists.apache.org/thread/rdflfdbt2v0cxz9mk198tonm0hnff1bg) a while ago, I got distracted by other things and forgot to open a PR for it.
> Git: enable "replace invalid branch characters" by default

- .gitignore
- profiler/lib.profiler/build.xml
- profiler/lib.profiler/external/binaries-list
- profiler/lib.profiler/external/profiler-external-binaries-1-24aefa9-license.txt
~~Work-in-progress update to staged profiler binaries `1-r2196e46` with fix for Apple Silicon. Built in workflow https://github.com/apache/netbeans/actions/runs/6351527745~~ This is a follow up to #6496 and part of fixing #4524
This PR is for testing and voting purposes.  The native binaries must be voted on and moved to release, and this PR updated, before merging to master.
The previous ASF binaries are kept for now, besides being entirely overwritten for testing purposes.  We might just decide to use the mac binaries in a pattern set?
We need a versioning strategy for external native binaries - intention here is to use strictly incrementing version number plus short hash - eg. next will be `2-r<hash>` then `3-r<hash>`.
We should perhaps consider adding OS into the matrix for profiler …
> Update profiler native binaries to released 1-24aefa9

- ide/dlight.nativeexecution/external/binaries-list
- ide/dlight.nativeexecution/external/nativeexecution-external-binaries-1-24aefa9-license.txt
- ide/dlight.nativeexecution/nbproject/project.properties
~~Work-in-progress update to staged native execution binaries `1-reb9e96d` with (some!) binaries for Apple Silicon. Built in workflow https://github.com/apache/netbeans/actions/runs/6395128403~~  This is a follow up to #6513 and part of addressing #3467 .  It is enough to get the terminal support working, although other aspects might need additional work.
This PR is for testing and voting purposes.  The native binaries must be voted on and moved to release, and this PR updated, before merging to master.
The previous binaries for all existing OS are kept in place at the moment, despite the staged artefact also including macOS and Linux x86_64.
~~UPDATE : updated to use the revised staged binaries 1-24aefa9~~
UPDATE : updated to use the released binaries 1-24aefa9
> Add native execution binaries for macOS arm64 (1-24aefa9)

- extide/gradle/src/org/netbeans/modules/gradle/execute/GradleNetworkProxySupport.java
- extide/gradle/src/org/netbeans/modules/gradle/options/GradleExperimentalSettings.java
- java/maven/src/org/netbeans/modules/maven/execute/MavenProxySupport.java
- java/maven/src/org/netbeans/modules/maven/options/MavenSettings.java
The current implementations keep user decisions per project; so if some conflict between detected proxy and detected settings is reported to the user, it is reported again for each project: but tool setings are machine-wide, so they apply to all projects. 
This PR makes a simple (dirty) fix storing the decisions in a static variable, sharing between individual projects.  It's really annoing if there are more projects opened. Decisions are not shared between Maven and Gradle, so the IDE may ask 2 times (once for each build system). In a typical case, the developer uses either Maven or Gradle, so hopefully this will not happen frequently.
I would like to factor the detection out to core.network + add some APIs and turn maven + gradle into just some 'setting manipulators' ... but not before …
> Do not ask for proxies on each project.

- extide/gradle/netbeans-gradle-tooling/src/main/java/org/netbeans/modules/gradle/tooling/NbProjectInfoBuilder.java
I've worked with Micronaut 4.1.x. The project is apparently configured differently than the previous version ... so other problems surfaced.
#6537 was caused by a `StackOverflowError` - during dumping of complex structures, the traversal was not guarded against recursing through loop links inside the structure. This was fixed by noting the dumped instance in a Map and preventing the recursion if the dumper encounters that instance again.
#6536 was more tricky - it seems that `getResolvedConfiguration` and maybe other calls throw `ArtifactResolveException` for artifacts not yet in the local cache. The exception was not caught / detected properly and was treated as a load error. Now the entire analysis is wrapped by a guard, that rethrows those exceptions as `NeedOnlineModeException`, …
> #6536, #6537: avoid stack overflow, catch missing artifacts to be downloaded.

- java/maven.embedder/src/org/netbeans/modules/maven/embedder/MavenEmbedder.java
During debugging of #6525, it turned out that during the project read, the execution **sometimes** avoided the call to `setupLegacySupport` in our MavenEmebdder before invoking Maven - and when the execution finally reached e.g. `NbRepositoryModelResolver.resolveModel`, the LegacySupport was already set up by maven core - and by default for online operation.
Futher calls to `setupLegacySupport` detected an existing session (from Maven) and did not create a NB-compatible setup.
The PR just ensures the LegacySupport is set up prior to maven call, so it is consistent with NB needs.
> #6525: maven execution should setup LegacySupport before running Maven

- ide/projectui/src/org/netbeans/modules/project/ui/problems/BrokenReferencesAlertPanel.form
- ide/projectui/src/org/netbeans/modules/project/ui/problems/BrokenReferencesAlertPanel.java
minor layout tweaks, noticed this while testing #6516
->
> Layout fixes for the project problems warning dialog.
